### ISSUE TITLE
Внесение предоплаты.

### ISSUE THREAD

**Issue by popowich** [iiko/front.api.sdk#101]
Почему в 5-й версии API можно было добавить предоплату в заказ https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_Editors_IEditSession_AddPreliminaryPaymentItem.htm
А в 6-й версии только в доставочный заказ ???  
https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddPreliminaryPaymentItem.htm
хотя на сам фронте в обычный заказ есть возможность добавления предоплаты, в чем проблема оставить это и для плагина ?

**Comment by ierof** [comment]
Потому что PreliminaryPaymentItem это не совсем предоплата. 
Это предварительный платеж доставки. И в V5 был баг, что его можно было добавить в обычные заказы. 
Для работы с предоплатами в обычных заказов рекомендуется использовать каскад операций 
- `AddPaymentItem` \ `AddExternalPaymentItem`
- `IOperationService.ProcessPrepay`

В статье про [Оплатные действия](https://iiko.github.io/front.api.doc/v6/ru/Payments) это всё описано подробнее. Есть пример кода в разделе _Проведение оплаты > Добавление в заказ проведенной оплаты и превращение ее в предоплату iikoFront / Добавление в заказ предварительного платежа с последующим превращением в предоплату iikoFront_.
Это правильная работа с предолатами с точки зрения iiko. Также в статье описаны принципы "тихого проведения оплат"  с  которыми имеет смысл ознакомиться, если контекст вашего вопроса это собственный API-тип оплаты.

И т.к. я рекомендую использовать каскад  вызовов `IEditSession`> `IOperationService`, полезно прочитать раздел "[Редактирование данных](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html)" > Выполнение операций непрерываемой серией
