### ISSUE TITLE
V6 в Nuget

### ISSUE THREAD

**Issue by popowich** [iiko/front.api.sdk#102]
Непонятная для меня ситуация в нагет пакетах. По вашей схеме https://iiko.github.io/front.api.doc/versioning.html V6 зафиксированная версия - 6.4.7.0 
А вот что я вижу в нагете http://joxi.ru/5md77Lni3nVN7r 
почему под V6 идет уже 7-я версия, которая на данный момент в разработке  и почему нет других версий в списке ?

**Comment by ierof** [comment]
> V6 зафиксированная версия - 6.4.7.0

Не написано там такого :) Там нет точки между `6.4` и `7.0`. И тем более ниже написано, что API V6 выпущена в 7.0. Про это была [новость](https://iiko.github.io/front.api.doc/2019/10/14/v6-release.html) Это во-первых.
Во-вторых, версия iiko 7.0. уже выпущена: https://ru.iiko.help/articles/#!releasenotes/releasenotes-7-0

Итого: версия API V6 выпущена в версии iiko 7.0. Версия iiko 7.0 выпущена в октябре.

**Comment by ierof** [comment]
#103
