### ISSUE TITLE
Совместимость API.V6 v6.1.2013, v6.4.3013, v7.0 + iikoFront 6.4.3013, 6.1.2013

### ISSUE THREAD

**Issue by xsxVeNxsx** [iiko/front.api.sdk#103]
Основной вопрос - какую версию SDK нужно использовать, чтобы плагин работал на всех версиях iikoFront, начиная с iikoFront 6.1?

Что я пробовал:
**1. API.V6 v7.0 из Nuget + iikoFront 6.4.3013**
В логах плагина следующая ошибка:
`[2019-11-10 02:17:43,398] ERROR [ 1] - UnhandledException in host domain:
System.TypeLoadException: Не удалось загрузить тип "Resto.Front.Api.V6.ILog" из сборки "Resto.Front.Api.V6, Version=7.0.6022.0, Culture=neutral, PublicKeyToken=null".
   в System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   в Resto.Front.Api.Host.PluginDomain.Create[T](Object[] args) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Api.Host\PluginDomain.cs:строка 50
   в Resto.Front.Api.Host.Program.Main(String[] args) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Api.Host\Program.cs:строка 40`
Хотя в системе даже нет таких путей и вообще жесткого диска M:

**2. API.V6 v6.1.2013 + iikoFront 6.4.3013**
Без Manifest файла никакой реакции вообще, даже файл логов не создается. После добавления Manifest в логах плагина следующая ошибка:
`[2019-11-10 03:15:04,947] ERROR [ 1] - Отсутствует реализация метода "get_Type" в типе "Resto.Front.Api.V6.Data.Orders.DeliveryOrder" из сборки "Resto.Front.Api, Version=6.4.3013.0, Culture=neutral, PublicKeyToken=null". `

**3. API.V6 v6.1.2013 + iikoFront 6.1.2013 и API.V6 v6.4.3013 + iikoFront 6.4.3013**
Закономерно работают исправно.

**Comment by ierof** [comment]
Смотрите, про версии есть подробная [Статья в документации](https://iiko.github.io/front.api.doc/versioning.html).

Что там написано по вашему вопросу:

1. Версия API V6 выпущена (зафиксирована) в iiko 7.0. Это значит, что начиная с iiko 7.0 можно пользоватсья API V6 из nuget.
1. До версии iiko 7.0 версия API V6 была разрабатываемой — в неё вносились изменения бзе гарантии обратной совместимости => и в версии iiko 6.1 и в версии iiko 6.4 гарантировано хорошо будет работать сборка API V6 той же версии, что и iiko. Вот что написано в документации:
> Разрабатываемую версию использовать не рекомендуется, поскольку её интерфейс ещё не зафиксирован, обратная совместимость не обеспечивается, возможны любые изменения. Эта версия доступна для изучения нововведений и раннего начала разработки плагина для будущей версии API, чтобы к моменту её выпуска иметь готовый или почти готовый плагин, предоставляющий новые возможности.

Кроме того, начиная с версии iiko 6.4 мы ввели механизм [зафиксированных preview API](https://iiko.github.io/front.api.doc/2019/07/02/v6preview5-release.html). Для iiko 6.4 можете использовать [API V6Preview5 из nuget](https://www.nuget.org/packages/Resto.Front.Api.V6Preview5). Об этом тоже можно прочитать в документации.

**Comment by vcpp** [comment]
> какую версию SDK нужно использовать, чтобы плагин работал на всех версиях iikoFront, начиная с iikoFront 6.1?

V5.
