### ISSUE TITLE
DLL 6.3.3

### ISSUE THREAD

**Issue by PashaTheBestAndroidDeveloper** [iiko/front.api.sdk#104]
Добрый день!
Нам нужна ваша помощь, меня зовут Павел, и мы Украинские разработчики плагина Uployal, нам очень нравиться ваша система iiko но к сожалению неожиданно столкнулись с проблемой  блида нашего плагина на версии iiko 6.3.3 по словам с Украинской техподдержки мы можем найти все нужные для нас DLL на этом сайте nuget.org но к сожалению их там нет. Мы вернулись с тем же вопросом в тех поддержку, и нам не отвечают, то есть далее мы вынуждены ждать или искать DLL иначе наша работа просто заблочена.

То есть нам нужны DLL чтобы сбилдить плагин на версии 6.3.3 и если это возможно дополнительно DLL для версии iiko 6.4.3 
 вы можете помочь, мы будем очень благодарны, спасибо!

**Comment by vcpp** [comment]
По-хорошему, вам не нужно искать dll-файлы от конкретной сборки приложения. Схема должна быть намного проще:

1. Выбираете версию API.
2. Подключаете к плагину NuGet-пакет для выбранной версии API.
3. Собираете и распространяете плагин. Он будет совместим со всеми сборками iikoFront, где поддерживается выбранная версия API.

Допустим, вы выбрали V5, подключили NuGet-пакет [Resto.Front.Api.V5](https://www.nuget.org/packages/Resto.Front.Api.V5/) и собрали плагин под V5. Далее этот плагин можно будет установить к любой версии iikoFront 5.4.1+, то есть вышедшей приблизительно с 2017 по 2021 год. Используйте один и тот же собранный под V5 плагин и для 6.3.3, и для 6.4.3.

Однако, V5 — это довольно старая версия, она была выпущена 2 года назад. Недавно [выпущена](https://iiko.github.io/front.api.doc/2019/10/14/v6-release.html) версия V6, в ней возможностей намного больше, но она поддерживается только начиная с iikoFront 7.0.1. Если возможностей V5 вам не хватает, но вы можете рекомендовать пользователям обновиться на iikoFront 7.0.1+, пишите плагин под V6, подключив [Resto.Front.Api.V6](https://www.nuget.org/packages/Resto.Front.Api.V6/) такой плагин будет совместим с iikoFront 7.0.1 и всеми будущими версиями на 4 года вперёд.

V5 и V6 — LTS-версии, поддерживаются 4 года, это удобно. По возможности стоит выбирать именно LTS-версию. Если так получилось, что V5 не хватает, а перейти на V6 не получается из-за пользователей, которых нельзя так просто взять и обновить, придётся использовать промежуточные preview-версии, они выходили до релиза V6 и функционально довольно близки к V6. Для 6.4.3 подходят [V6Preview4](https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha) и [V6Preview5](https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha).

Во времена 6.3.3 preview-версий ещё не было, поэтому для 6.3.3 можно использовать либо релизную V5 (рекомендуется), либо собирать плагин под недоделанную на тот момент версию V6, и в этом случае вам понадобится [нестабильная V6 из SDK от 6.3.3](https://github.com/iiko/front.api.sdk/files/3842410/Unstable_V6_from_6.3.3014.0.zip).


Почитайте статью про [версионность](https://iiko.github.io/front.api.doc/versioning.html).
В первую очередь оцените возможность использовать V5 или перейти на V6, обновив пользователей.

**Comment by PashaTheBestAndroidDeveloper** [comment]
Большое спасибо за ответ, вы нам очень сильно помогли!!
Если я могу вам поставить где-то звездочки или хороший отзыв это сразу
зделаю.

Спасибо !

**Comment by vcpp** [comment]
Не, мы тут за идею, без звёздочек, лайков, кармы и прочих рейтингов :-)

Будут ещё вопросы — обращайтесь.
Наткнётесь на чужие вопросы, на которые знаете ответ — можете помочь.

**Comment by PashaTheBestAndroidDeveloper** [comment]
С удовольствием, большое спасибо !:)

**Comment by PashaTheBestAndroidDeveloper** [comment]
Здравствуйте, данная проблема присутствует, не можем запустить плагин на
версии 6.4.3, нужны длл, можете помочь 🙏



с низу лог ошибки


Vladyslav Kondurian, [19 Nov 2019, 13:10:07]:
[image: Screenshot 2019-11-19 at 15.08.14.png]

беру этот файл


у клиента 643


плагин почему-то не стартует


upp.conf не создаётся


лога соответственно нет


лицензии есть

dll-ки не заблокированы


[2019-11-18 14:30:45,870]  WARN [LoadingScreenController]
[EnumerableEx:ForEach] - Scan 'C:\Program
Files\iiko\iikoRMS\Front.Net\Plugins\Resto.Front.Api.UployalPaymentPlugin\Resto.Front.Api.UployalPaymentPlugin.dll'
failed: System.TypeLoadException: Method 'CollectData' in type
'PaymentPlugin.PluginStartup' from assembly
'Resto.Front.Api.UployalPaymentPlugin, Version=6.2.2.0, Culture=neutral,
PublicKeyToken=null' does not have an implementation.

   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly
assembly, ObjectHandleOnStack retTypes)

   at System.Reflection.RuntimeAssembly.GetExportedTypes()

   at
Resto.CashServer.Plugins.PluginsSearcher.InternalSearcher.FindPluginsInAssembly(String
assemblyPath, PluginTypeMatcher tryMatchPlugin, ICollection`1 lastErrors)
in
M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Plugins\PluginsSearcher.cs:line
98

[2019-11-18 14:30:45,964] DEBUG [LoadingScreenController]
[PluginsManager:DumpPluginsMetadata] - Found 0 new plugins:


вот что говорит cashserver.log

**Comment by vcpp** [comment]
> Для 6.4.3 подходят [V6Preview4](https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha) и [V6Preview5](https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha).

Какую из этих версий использует ваш плагин?

**Comment by vladislav250899** [comment]
> > Для 6.4.3 подходят [V6Preview4](https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha) и [V6Preview5](https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha).
> 
> Какую из этих версий использует ваш плагин?
При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
image_2019-12-11_23-59-45

При подключении этих пакетов отображается ошибка и пакет не устанавливается:

https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha
Подскажите, пожалуйста, как можно решить эту проблему?

**Comment by vladislav250899** [comment]
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70918534-d9e99a00-2027-11ea-91c9-a3b5999d058b.png)

**Comment by vcpp** [comment]
В свойствах своего проекта выберите Target Framework 4.7.2.

**Comment by vladislav250899** [comment]
> В свойствах своего проекта выберите Target Framework 4.7.2.

Спасибо! Будем пробовать.

**Comment by vladislav250899** [comment]
Здраствуйте, @vcpp! Есть ли возможность поддерживать мультиверсионность плагина? Для каждой новой версии iiko нам приходится делать новый плагин.

**Comment by vcpp** [comment]
Непонятно, почему вы делаете новый плагин для каждой версии iiko. Это неправильно. Для того и обеспечивается обратная совместимость, чтобы плагин, разработанный под определённую версию API, мог работать везде, где эта версия API поддерживается.

И на будущее:
1. Для нового вопроса лучше зарегистрировать отдельную заявку. Нам так удобнее следить за статусами заявок, другим так удобнее искать информацию, ориентируясь на заголовки.
2. Не нужно задавать персонально вопрос, не связанный с конкретным человеком. На общий вопрос об API может ответить любой разработчик iikoFront API.
