### ISSUE TITLE
Смена статуса блюда IKitchenOrderCookingItem

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#105]
Здравствуйте! Разрабатываю плагин, аналог вашего экрана готовых блюд. Как я могу поменять 
у объекта IKitchenOrderCookingItem.ProcessingStatus ?

**Comment by RomanProtas** [comment]
Я подписался на события изменения статуса блюда, в качестве аргумента мне приходит IKitchenOrder. Далее я отбираю объекты IKitchenOrderCookingItem с ProcessingStatus == KitchenOrderItemProcessingStatus.Processed и вывожу список этих айтемов в gui. Необходимо по тапу на айтем переводить его в статус KitchenOrderItemProcessingStatus.Served . Подскажите, пожалуйста, как я могу это сделать?

**Comment by vcpp** [comment]
К сожалению, кухонные заказы пока доступны только на чтение.

Полный доступ с возможностью переключать статусы давно в планах (RMS-32597), но всё руки не доходят. Рано или поздно всё-таки сделаем. Спасибо, что напомнили: если на фичу есть спрос, больше шансов, что «рано», чем «поздно» :-)

**Comment by vcpp** [comment]
[Готово](https://iiko.github.io/front.api.doc/2019/11/27/change-kitchen-orders.html).
Возможность переключения статусов станет доступна в V7Preview1.
