### ISSUE TITLE
Уведомление о начале закрытия заказа

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#106]
Добрый день.
Мы разрабатываем собственный плагин для нашей системы лояльности. Нам необходимо перехватить событие до закрытия заказ.
Дело в том, что при закрытии заказа нам необходимо сделать транзакцию у нас в плагине. И если в процессе транзакции возникает ошибка, нам необходимо отменить закрытие заказа.
Событие `SubscribeOnBillChequePrinting` не подходит, т.к. в Iiko front имеется возможность изменить заказ после печати (т.е. если после печати заказ изменился, мы дожны заново сделать транзакцию у нас в плагине).  
[OrderStatusChangeNotifier ](https://github.com/iiko/front.api.sdk/issues/7) тоже не подходит. Так как при возникновении этого события заказ уже закрыт и если у нас в плагине возникнет ошибка, то не сможем отменить заказ.

`Используем API v.5.4.1160.0`

**Comment by vcpp** [comment]
А что, если транзакция у вас прошла успешно, а заказ в итоге не смогли оплатить? Вы, наверное, захотите отменить транзакцию?

Расскажите немного о сценарии, что представляет собой эта транзация — списание бонусов?

**Comment by HakobyanAram** [comment]
> А что, если транзакция у вас прошла успешно, а заказ в итоге не смогли оплатить? Вы, наверное, захотите отменить транзакцию?
> 
Но если заказ не смогли оплатить, то заказ не закроется. Не так ли?

> Расскажите немного о сценарии, что представляет собой эта транзация — списание бонусов?
Транзакция представляет собой- списание бонусов, накопление суммы оплаты

**Comment by CLTanuki** [comment]
@HakobyanAram , полагаю, что будет очень сложно объяснить гостю в рамках действующего законодательства, что он не может получить кассовый чек потому, что на сервере есть какие-то сложности.
Во всех подобных случаях мы используем кэш и переотправку в фоне, что и вам рекомендуем.

**Comment by vcpp** [comment]
> Нам необходимо перехватить событие до закрытия заказ.
> Нам необходимо запрещать закрытие заказа на кассе при возникновении ошибки у нас в плагине.

Если ещё актуально, попробуйте реализовать расширение фискального регистратора и выполнять свои операции перед печатью чека ([`IChequeTaskProcessor.BeforeDoCheckAction`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Devices_IChequeTaskProcessor_BeforeDoCheckAction.htm)). Если понадобится отменить печать чека, выбросите исключение с указанием причины. Кассир по ситуации либо попробует повторить оплату, либо оставит заказ открытым. Примеры [тут](https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html).
