### ISSUE TITLE
При переходе с V6 на V7 ошибка в ExtendedInputDialogSettings

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#108]
На версии 6.4.2 c api v6 работал блок ExtendedInputDialogSettings
По руководству https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html

Планируем обновить клиента на 7.0.7 в связи с этим начал переводить на v7 
но встала ошибка 
Скрин приложил. В чем может быть причина. На v6 работает на v7 нет

![y701z1tyn1](https://user-images.githubusercontent.com/17568251/70701043-e4d5bf00-1cf5-11ea-8132-d6877bff73b3.png)

**Comment by vcpp** [comment]
1. Да, это ошибка в используемой под капотом технологии .Net Remoting от Microsoft. Мы нашли способ обхода, и начиная с 7.1.5 эта ошибка не должна проявляться.
2. Ошибка затрагивала только находящуюся в разработке версию V7. Все выпущенные поддерживаемые версии API должны работать без ошибок.
3. Для чего вы хотите перевести плагин на V7? Эта версия находится в разработке и публикуется лишь для ознакомления и ранних экспериментов. Без поддержки, без обратной совместимости. Если V6 устраивает, можно оставаться на V6 до 2023 года. Если нужны новые фичи, лучше дождаться релиза V7Preview1 (выйдет вместе с iikoRms 7.1). Подробнее [тут](https://iiko.github.io/front.api.doc/versioning.html).
