### ISSUE TITLE
Ошибка при подключении пакетов Nuget

### ISSUE THREAD

**Issue by vladislav250899** [iiko/front.api.sdk#109]
При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70803919-d226bd00-1dbd-11ea-8460-379c8f2cff2f.png)

При подключении этих пакетов отображается ошибка и пакет не устанавливается:   
1) https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
2) https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha

Подскажите, пожалуйста, как можно решить эту проблему?

**Comment by ierof** [comment]
https://github.com/iiko/front.api.sdk/issues/110
