### ISSUE TITLE
Ответ от iiko Front

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#11]
Приветствую!

На основе SamplePlugin пробуем создавать новый заказ:
```
var credentials = PluginContext.Operations.GetCredentials();

var editSession = PluginContext.Operations.CreateEditSession();
var newOrder = editSession.CreateOrder(null);
editSession.ChangeOrderOriginName(originName, newOrder);
var guest1 = editSession.AddOrderGuest(null, newOrder);
var guest2 = editSession.AddOrderGuest(guestName, newOrder);
var result = PluginContext.Operations.SubmitChanges(credentials, editSession);

var previouslyCreatedOrder = result.Get(newOrder);
var previouslyAddedGuest = result.Get(guest2);

decimal amountD = decimal.Parse(amount);

PluginContext.Operations.AddOrderProductItem(amountD, PluginContext.Operations.GetActiveProducts().Last(),
previouslyCreatedOrder, previouslyAddedGuest, null, credentials);
```
Всё корректно создаётся.
Однако, тип данного заказа FastFoodOrder
![image](https://user-images.githubusercontent.com/2853612/53135033-ab776b80-358a-11e9-91ea-4b2b1cc1dc3c.png)

1. Нам необходимо создать заказ на доставку типа "Resto.CashServer.Data.Deliveries.DeliveryOrder".
Подскажите, пожалуйста, как это можно реализовать?
2. Как передать в создаваемый заказ конкретные объекты? Например, id блюда и id покупателя.
3. Как получить в response ответ iikoFront? Например, номер и статус заказа.

Спасибо.

**Comment by ierof** [comment]
У доставочного заказа [`IDeliveryOrder`](http://iiko.github.io/front.api.sdk/v6/html/Properties_T_Resto_Front_Api_V6_Data_Orders_IDeliveryOrder.htm) больше свойств, чем у обычного заказа [`IOrder`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Orders_IOrder.htm).

В SDK в [EditorTester.cs ](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs) есть примеры создания доставочных заказов: см. метод `CreateDelivery`.
Как можно догадаться из названия методов, для создания доставточного заказа используется метод [`IEditSession.CreateDeliveryOrder()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_CreateDeliveryOrder_1.htm)

**Comment by ierof** [comment]
По остальным вопросам: 
2. А зачем вам конкретные id? Для гарантированной консистенции данных iiko сама назначает id создаваемым в ней объектам. 
3. Как получить обратно: когда вы создаете объект, вы получаете его [stub](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html), далее по `id` объекта его мождно получать из [operationService](https://iiko.github.io/front.api.doc/v6/ru/Intro.html#operationService)

**Comment by iDoctor** [comment]
> У доставочного заказа [`IDeliveryOrder`](http://iiko.github.io/front.api.sdk/v6/html/Properties_T_Resto_Front_Api_V6_Data_Orders_IDeliveryOrder.htm) больше свойств, чем у обычного заказа [`IOrder`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Orders_IOrder.htm).
> 
> В SDK в [EditorTester.cs ](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs) есть примеры создания доставочных заказов: см. метод `CreateDelivery`.
> Как можно догадаться из названия методов, для создания доставточного заказа используется метод [`IEditSession.CreateDeliveryOrder()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_CreateDeliveryOrder_1.htm)

Да, таким образом заказ с доставкой создаётся. Однако, он пустой.
Чтобы добавить блюдо необходимо использовать следующий код?
```
private void AddProduct()
        {
            var order = PluginContext.Operations.GetOrders().Last();
            var guest = order.Guests.Last();
            var product = PluginContext.Operations.GetActiveProducts().Last();
            PluginContext.Operations.AddOrderProductItem(42m, product, order, guest, null, PluginContext.Operations.GetCredentials());
        }
```



> 2. А зачем вам конкретные id? Для гарантированной консистенции данных iiko сама назначает id создаваемым в ней объектам.

У нас следующий алгоритм работы. Есть конфигурация 1С, в которой синхронизирован справочник Номенклатура. В 1С создаётся заказ на доставку (конкретное блюдо выбирается из справочника) и передаётся в iiko Front. То есть требуется добавить не .Last(), а что-то определённое.

Если мы добавляем ФИО и контакты заказчика, то нам по сути не важно, что данные на Фронт передаются, допустим, в виде string без привязки к базе? Так как кроме отображения ФИО с адресом на экране оператора и на чеках данная информация больше нигде не используется. Верно?



> 3. Как получить обратно: когда вы создаете объект, вы получаете его [stub](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html), далее по `id` объекта его мождно получать из [operationService](https://iiko.github.io/front.api.doc/v6/ru/Intro.html#operationService)

order.Id возвращает идентификатор в формате, в котором он представлен в XML (57b4f31a-fc50-4cae-bce7-0d3c190dc1c6). Возможно ли получить значение int?

**Comment by ierof** [comment]
3.
В iiko всё идентифицируется через Guid-ы, не через int-ы. Поэтому из iiko int-ы в качестве идентификаторов объектов вам не получить. 
[Как превратить Guid в int](https://stackoverflow.com/questions/2920696/how-generate-unique-integers-based-on-guids). Но имейте ввиду, что число возможных уникальных Guid-ов сильно превосходит число уникальных int-ов. Получается, возможны коллизии. И если вам кроме получения int-а иp Guid-а нужно будет и обратное однозначное преобразование, то вам и над решением этой задачи нужно будет подумать ;)

**Comment by ierof** [comment]
2.
> То есть требуется добавить не .Last(), а что-то определённое.

Да, скорее всего вам требуется добавлять что-то определенное, `Last` в примерах используется как просто один из способов получить объект из коллекции. Вообще это тоже скорее общепрограммистский вопрос, нежели iiko-специфичный. 
Наверное, вам правильнее сначала ознакомится со всеми примерами, которые есть в нашем SDK для близких вашим сценариям?

**Comment by iDoctor** [comment]
3. Я имею в виду разве нет возможности получить порядковый номер заказа, как на форме?
![image](https://user-images.githubusercontent.com/2853612/53166585-c5469c00-35e6-11e9-9945-44e9dc562a8c.png)

При повторном формировании заказа методом CreateDelivery() выбивает ошибку:
![image](https://user-images.githubusercontent.com/2853612/53166615-e1e2d400-35e6-11e9-9fef-1ce2f5b3bf74.png)
(Допустим, один и тот же человек сделал два заказа подряд)
Понимаю, что истина где-то рядом, но не могу уловить :) При повторном использовании метода CreateDelivery просто добавляются блюда в последний заказ с последующей ошибкой.
Возможно, необходимо принудительно закрыть сессию редактирования?

**Comment by ierof** [comment]
>1. Я имею в виду разве нет возможности получить порядковый номер заказа, как на форме?

Это свойство [`Number`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Orders_IOrder_Number.htm). Но имейте ввиду, оно не уникальное в общем случае и использовать его как уникальный ключ не рекомендуется, возможны неоднозанчности. 

> При повторном формировании заказа методом CreateDelivery() выбивает ошибку: 
(о том, что такая карта уже привязана к другому человеку)
(Допустим, один и тот же человек сделал два заказа подряд)

Если два заказа подряд, в одной сессии и вы планируете обрабатывать это в одной сессии, то достаточно просто не создавать нового клиента, а использовать существующего, созданного ранее  
методом [`IEditSession.CreateClient`]http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_CreateClient.htm). Но до того, как создавать нового клиента, можно поискать его в существующих по нужному вам алгоритму – совпадению фамилии, имени, номера телефона и т.д. См. [IOperationService.SearchClients()](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_SearchClients.htm)

**Comment by iDoctor** [comment]
### Создание нового заказа доставки
Для создания заказа на доставку используем метод из SamplePlugin:
```
        public HttpResponseMessage CreateDelivery()
        {
            var editSession = PluginContext.Operations.CreateEditSession();
            var street = PluginContext.Operations.GetActiveStreets().Last();
            var region = PluginContext.Operations.GetRegions().LastOrDefault();
            var deliveryOperator = PluginContext.Operations.GetUsers().Last();
            var address = new AddressDto
            {
                StreetId = street.Id,
                RegionId = region == null ? Guid.Empty : region.Id,
                House = "428-с",
                Building = "29-m",
                Flat = "37",
            };

            var orderType = PluginContext.Operations.GetOrderTypes().Last(type => type.OrderServiceType == OrderServiceType.DeliveryByCourier);

            var primaryPhone = new PhoneDto
            {
                PhoneValue = "+79991112233",
                IsMain = true
            };

            var secondaryPhone = new PhoneDto
            {
                PhoneValue = "+79991112244",
                IsMain = false
            };

            var primaryEmail = new EmailDto
            {
                EmailValue = "MyMail@iiko.ru",
                IsMain = true
            };

            var secondaryEmail = new EmailDto
            {
                EmailValue = "MySecondMail@iiko.ru",
                IsMain = false
            };

            var now = DateTime.Now;
            var client = editSession.CreateClient(Guid.NewGuid(), "Semen",
                                                  new List<PhoneDto> { primaryPhone, secondaryPhone }, null, now, null, null);

            var expectedDeliverTime = now.AddHours(1);
            var deliveryOrder = editSession.CreateDeliveryOrder(1149, now, primaryPhone.PhoneValue,
                address, expectedDeliverTime, orderType, client, deliveryOperator, TimeSpan.FromMinutes(60));
            editSession.ChangeOrderOriginName("ИСТОЧНИК ДОСТАВКИ!", deliveryOrder);
            var guest = editSession.AddOrderGuest("Alex", deliveryOrder);
            editSession.ChangeClientSurname("Petrov", client);
            editSession.ChangeClientNick("Batman", client);
            editSession.ChangeClientEmails(new List<EmailDto> { primaryEmail, secondaryEmail }, client);
            editSession.ChangeClientComment("Customer's Comment", client);
            editSession.ChangeClientAddresses(new List<AddressDto> { address }, 0, client);
            editSession.ChangeClientCardNumber("123456798", client, null, null);
            editSession.ChangeDeliveryComment("Delivery comment", deliveryOrder);
            editSession.ChangeDeliveryEmail(primaryEmail.EmailValue, deliveryOrder);

            var order = PluginContext.Operations.GetOrders().Last();
            var guest1 = order.Guests.Last();
            var product = PluginContext.Operations.GetActiveProducts().Last();
            PluginContext.Operations.AddOrderProductItem(42m, product, order, guest1, null, PluginContext.Operations.GetCredentials());

            SubmitChanges(editSession);

            return Request.CreateResponse(HttpStatusCode.OK, $"{DateTime.Now}. Данные успешно отправлены!");
        }
```
в котором вызывается метод IEditSession.CreateClient.
Но почему в таком случае повторный вызов метода CreateDelivery() принудительно пытается записать данные в предыдущий заказ?


### Добавление блюда
Для добавления конкретного блюда в текущий заказ необходимо использовать
`IProduct product = PluginContext.Operations.GetProductById(#productId#);`
Верно?
Метод GetProductById() использует входной параметр типа GUID.
Что это: номер блюда в формате int, id вида "57b4f31a-fc50-4cae-bce7-0d3c190dc1c6" или что-то другое?

**Comment by ierof** [comment]
> Но почему в таком случае повторный вызов метода CreateDelivery() принудительно пытается записать данные в предыдущий заказ?

Не поняла вопрос. Какие именно данные в предыдущий заказ записываются в этом утверждении? Приведенный вами код sample-плагина это "метод-комбайн", демонстрирующий возможности создания адресов, гостей и доставок. В реальной жизни, реализовывая бизнесу-логику под требования заказчика, как правило нужно, к примеру, сначала попытаться найти клиента среду существующих по нужному заказчику алгоритму. И т.д.

> Для добавления конкретного блюда в текущий заказ необходимо использовать
`IProduct product = PluginContext.Operations.GetProductById(#productId#);`
Верно?

Не обязательно. Если вам известны id продуктов системы iiko, то конечно можно пользоваться этим методом. Но если нужна какая-то бизнес-логика поиска продуктов по какому-то признаку (имени, артикулу, коду быстрого набора и т.д.), то ищите нужный продукт в коллекции [`IOperationService.GetProducts`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetProducts.htm). или [`IOperationService.GetActiveProducts`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetActiveProducts.htm).
Сравнивая нужные вам свойства [`IProduct`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Assortment_IProduct.htm). Например 
```
var product = PluginContext.Operations
	.GetActiveProducts()
	.SingleOrDefault(p => p.Name == "НУЖНОЕ ИМЯ");
```
или
```
var product = PluginContext.Operations
	.GetActiveProducts()
        .SingleOrDefault(p => p.Number == "ВАШ_АРТИКУЛ");
```

**Comment by iDoctor** [comment]
По поводу поиска продукта понял. Спасибо.

> Не поняла вопрос. Какие именно данные в предыдущий заказ записываются в этом утверждении?

При выполнении кода выше обработчик AddOrderProductItem() по всей видимости пытается работать не с новым заказом, а с последним оформленным:
![image](https://user-images.githubusercontent.com/2853612/53235228-60507c00-36a2-11e9-8ca1-2f246d0dfcdc.png)
Вероятно, это связано с тем, что в строке
`var orderType = PluginContext.Operations.GetOrderTypes().Last(type => type.OrderServiceType == OrderServiceType.DeliveryByCourier);`
получаем последний элемент последовательности Orders методом Last()

**Comment by ierof** [comment]
Ничего не нужно заставлять :) 

Проблема в вашем коде на 6-той строке снизу.
```
var order = PluginContext.Operations.GetOrders().Last();
```
Вы получаете последний существующий заказ и работаете с ним зачем-то, а не с тем `deliveryOrder`, который создали. 
Ещё вы работаете попеременно и с сессиями редактирования, и напрямую с операциями. Так не надо.
Прочитайте пожалуйста вдумчиво документацию. Хотя бы разделы (Введение) [https://iiko.github.io/front.api.doc/v6/ru/Intro.html] и [Редактирование данных](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html)
