### ISSUE TITLE
Ошибка при подключении пакетов Nuget

### ISSUE THREAD

**Issue by vladislav250899** [iiko/front.api.sdk#110]
При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70914469-bb33d500-2020-11ea-8655-2ff186579d4f.png)

При подключении этих пакетов отображается ошибка и пакет не устанавливается:

https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha
Подскажите, пожалуйста, как можно решить эту проблему?

**Comment by ierof** [comment]
Это стандартное для .net сообщение. 
Оно говорит о том ,что у вашего проекта версия .net 4.6.1, а данные nuget-библиотеки иной версии .net
Версия .net 4.7.2

**Comment by vladislav250899** [comment]
Здравствуйте, @ierof ! 
Спасибо за ответ! 
У нас возник следующий вопрос: Есть ли возможность поддерживать мультиверсионность плагина? Для каждой новой версии iiko нам приходится делать новый плагин.

**Comment by ierof** [comment]
Грубо говоря, да. Пока вы используете Preview-версии: да, для каждой сторой мажорной версии нужно иметь отдельную cборку плагина.

Т.е. если вы хотите использовать "свежие" фичи и ради этого пользуетесь Preview-версиями, о они будут совместимы с небольшим коридором версий iiko:
- V6Preview4 - [6.4- 7.0) (т.е. в 7.0 уже нет)
- V6Preview5 - [6.4- 7.1) (т.е. в 7.1 уже не будет)

Если вы хотите больший коридор совместимости, можете написать плагин на [API V5](https://www.nuget.org/packages/Resto.Front.Api.V5/), у неё коридор совместимости [5.4, ~8.0), т.е. ещё 1-2 года свежих релизов iiko.  

Вот тут подробно написано про Preview и полноценные версии API, про коридоры совместимости и т.д. 
https://iiko.github.io/front.api.doc/versioning.html
