### ISSUE TITLE
Предоплата безналичным типом оплаты. 

### ISSUE THREAD

**Issue by popowich** [iiko/front.api.sdk#112]
Здравствуйте! Версия API V6 - 6.4.2014.0 
    Суть задачи: ловить переход заказ в статус Bill и добавлять к заказу предоплату с AdditionalData в виде гостя. Ранее задавал вопрос про предоплату и получил ответ https://github.com/iiko/front.api.sdk/issues/101 т.е. нужно выполнить AddPaymentItem \ AddExternalPaymentItem а потом ProcessPrepay. Мне не удается перевести оплату добавленную через AddPaymentItem , в предоплату. При вызове ProcessPrepay  валится ошибка Resto.Front.Api.V6.Exceptions.ConstraintViolationException: Cannot process not external payment item При том эта операция ProcessPrepay  проходит, при добавлении оплаты через AddExternalPaymentItem НО только с типом оплаты, у которой проставлена галка "Может приниматься из вне" например налом. 
  Правильно ли я понимаю, перевести в предоплату можно только внешнюю оплату ? просто меня запутал предыдущий ответ, что можно использовать AddPaymentItem  то же. Меня к сожалению устраивает только безнал(и я ни как не могу проставить у него эту галку, хотя на интерфейсе она есть, но недоступна) т.к. только к нему можно привязать гостя, а это ключевой момент. Может быть есть еще какие то варианты или я что то не правильно делаю ?

**Comment by popowich** [comment]
Ответьте пожалуйста, хоть что нибудь(((

**Comment by letolika** [comment]
Добрый день.
Нужно подробнее описать проблему: скрин настроек типа оплаты и пример кода с использованием `AddExternalPaymentItem`.
Рекомендую к прочтению статью [Внешние типы оплаты](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html) в случае, если используется внешний плагинный тип оплаты.

**Comment by letolica** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
