### ISSUE TITLE
Null в событии OrderChanged

### ISSUE THREAD

**Issue by bobahml** [iiko/front.api.sdk#113]
Resto.Front.Api.Host ver. 7.0.7007.0
package id="Resto.Front.Api.V6" version="7.0.6022.0"

Событие PluginContext.Notifications.OrderChanged
поле EntityChangedEventArgs.Entity может принимать значение null.

Сценарий воспроизведения:
1. На кассе создать заказ оплатить и закрыть.
2. В списке закрытых заказов выбрать пункт "Удалить заказ"
3. В открывшемся окне выбрать пункт "Без списания"

Для удаленного заказа (в статусе Deleted) поле EntityChangedEventArgs.Entity может принимать значение null, при этом оно отмечено атрибутом  [NotNull].

**Comment by vcpp** [comment]
Как вы определили, что именно `EntityChangedEventArgs.Entity` оказывается `null`?

Класс `EntityChangedEventArgs` очень простой — там всего два свойства, которые можно задать только через конструктор, который проверяет `Entity` на `null`. Скорее всего, вы наткнулись на `null` где-то в другом месте, но с небольшой вероятностью могут быть и сюрпризы от сериализатора или среды выполнения.
У вас прямо по описанному сценарию стабильно воспроизводится?

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
