### ISSUE TITLE
Лицензионное ограничение: дополнение "PaymentPlugin.PluginName" недоступно

### ISSUE THREAD

**Issue by vladislav250899** [iiko/front.api.sdk#116]
Ранее в заведении, где iiko 6.4.3, тестировали наш плагин, Разработанный для версии 6.2.2. Для этого заказали лицензию на внешний тип оплаты. Лицензия была с Module ID (21016318), но пришлось дописать плагин из-за отсутсвие необходимых библиотек. Такой же Module ID используется в прежних лицензиях наших клиентов, где iiko 6.2.2.

При тестировании плагина на виртуальной машине с iiko 6.4.3 в тестовой среде, которую нам настроили представители технической поддержки iiko, плагин успешно работал на лицензии с другим Module ID (21005108), которая входила в тестовую лицензию.

После подключения плагина к заведению выдает ошибку: "Лицензионное ограничение: дополнение" PaymentPlugin.PluginName "недоступно". В cash-server.log и startup.log представители технической поддержки iiko нашли доказательства того, что плагин почему-то ищет в лицензии Module ID (21005108), но на заведении только Module ID (21016318).
![photo_2020-01-13_10-22-23](https://user-images.githubusercontent.com/49268908/72241104-9c5c3a80-35ee-11ea-9bcb-74b376a4cbf1.jpg)

Подскажите, пожалуйста, как решить проблему.

**Comment by vcpp** [comment]
> плагин почему-то ищет в лицензии Module ID (21005108)

Откуда-то же он берёт это число :-)
Проверьте атрибут на классе плагина и содержимое *Manifest.xml*.
