### ISSUE TITLE
Получение данных из внешнего интернета через webhook

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#117]
Здравствуйте, пишем iiko payment plugin, вроде все работает. Есть вопрос, можно ли вообще получить данные через webhok. 
Например сценарий оплаты такой.
Добавил внешний тип оплаты, отправил запрос на генерацию кода транзакции, получил код транзакции. Ждёт оплаты, сейчас у нас каждые 10 сек проверяет оплачена ли транзакция, если оплачена придет уведомление, если нет то продолжает сделать запрос. Как программист я считаю этот метод не правильной, много ресурсов нужно тратить. Можно ли как-то либо через сервера iiko слушать и передать программе iiko front данные?

**Comment by vcpp** [comment]
Это хороший вопрос.

Самый простой вариант — long polling. Из плагина отправляете запрос к своему серверу, а тот либо сразу отвечает, если транзакция уже оплачена, либо ставит запрос на паузу, ждёт, когда пройдёт оплата, и только потом возвращает ответ. Из плюсов — вы не зависите от нашей инфраструктуры, плагин мгновенно узнает о завершении оплаты. Из минусов — плагин не может отличить искусственную паузу сервера от потери связи и таймаута, поэтому в итоге это все равно периодические запросы, но с большими таймаутами.

Альтернативный вариант — передавать данные от вашего сервера к плагину через наш посреднический механизм, iikoTransport. На стороне плагина всё просто — зарегистрироваться через [`RegisterExternalOperation`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_RegisterExternalOperation.htm), и iikoTransport вызовет ваш обработчик, когда для вас придут данные. О том, как это работает в общем случае, [тут](https://iiko.github.io/front.api.doc/2018/08/03/external-operations.html). О том, как и куда отправлять данные, чтобы они пришли через iikoTransport в ваш плагин, я с ходу не отвечу, уточню у коллег.
