### ISSUE TITLE
Реализация переходов между окнами

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#118]
Здравствуйте, как мы можем реализовать переход (открытие, закрытие) между окон внутри iiko front?

Если не сможем, почему не реализуете такие функции? (для автоматизации они очень важны). Например я добавил внешнюю оплату, каждые 10 секунд проверяю успешность оплаты. Если успешно мне автоматически нужно закрыть заказ.
Также второй вопрос можем ли сделать горячие клавиши?. У нас была потребность открыть окно поиска блюд через горячие клавиши.

**Comment by vcpp** [comment]
> Здравствуйте, как мы можем реализовать переход (открытие, закрытие) между окон внутри iiko front?

Пока такой возможности нет.

> почему не реализуете такие функции?

Позвольте, я процитирую классический [ответ](https://stackoverflow.com/a/8673015):

> _The answer to that question is always the same. Features are unimplemented by default; API does not have that feature because no one designed, implemented and shipped the feature to customers.
<br/>The absence of a feature does not need justification. Rather, all features must be justified by showing that their benefits outweigh their costs. As the person proposing the feature, the onus is on you to describe why you think the feature is valuable; the onus is not on me to explain why it is not._

Когда вам нужна новая функция, вы приводите аргументы в пользу её реализации, показываете, как классно она решит некую проблему, мы соглашаемся и берём её в бэклог, либо предлагаем альтернативное решение. Опишите по шагам желаемый сценарий, что делает пользователь, что делает плагин, в чём профит.

> можем ли сделать горячие клавиши?. У нас была потребность открыть окно поиска блюд через горячие клавиши.

Ничего не понятно. Вы хотите открывать окно поиска блюд из плагина? Зачем? Какой сценарий? Или чтобы у пользователя была физическая клавиатура, с которой он через горячие клавиши будет открывать окно?
Чтобы не валить всё в одну кучу, давайте оставим здесь автозакрытие заказа и отцепим автооткрытие окна поиска блюд в отдельную заявку.

**Comment by letolika** [comment]
Похожий вопрос был тут #74

**Comment by Azamatjon** [comment]
> Похожий вопрос был тут #74

Вы меня перенаправляете к моему же второму вопросу, здесь нет ничего похожего между вопросами.

**Comment by vcpp** [comment]
>> можем ли сделать горячие клавиши?. У нас была потребность открыть окно поиска блюд через горячие клавиши.
>
> Ничего не понятно. Вы хотите открывать окно поиска блюд из плагина? Зачем? Какой сценарий? Или чтобы у пользователя была физическая клавиатура, с которой он через горячие клавиши будет открывать окно?

Давайте я вас перенаправлю к моим оставшимся без ответа вопросам :-)

**Comment by Azamatjon** [comment]
> > > можем ли сделать горячие клавиши?. У нас была потребность открыть окно поиска блюд через горячие клавиши.
> > 
> > 
> > Ничего не понятно. Вы хотите открывать окно поиска блюд из плагина? Зачем? Какой сценарий? Или чтобы у пользователя была физическая клавиатура, с которой он через горячие клавиши будет открывать окно?
> 
> Давайте я вас перенаправлю к моим оставшимся без ответа вопросам :-)

Давайте я вам скажу, есть у нас такая очень загруженная столовая, там пока через мышку нажимает и одного клиента закроют они R-Keeper'ом 3х обслуживают уже. Не быстро и не удобно выбрать всегда мышкой или сенсором выбрать, надо чтобы были горячие клавиши, если не хотят пока добавлять такую функцию на iikoFront, добавьте хотя бы возможность сделать что-то похожее в iiko front API

**Comment by letolica** [comment]
Решение по поводу работы с фронтом с помощью клавиатуры обсуждалось в #150. Внутренний номер задачи RMS-51350.
