### ISSUE TITLE
Перетирается свободная цена

### ISSUE THREAD

**Issue by axfedosenko** [iiko/front.api.sdk#119]
Здравствуйте.

Возникла проблема со свободными ценами после перехода на iiko 7 (v7.0.7007). Версия API v6.
Добавляются элементы заказа с установленной свободной ценой (predefinedPrice) через метод API [AddOrderProductItem](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm). После нажатия кнопки "Банкет начался" цена всех таких позиций сбрасывается в 0. При этом цена аналогичных позиций, добавленных через интерфейс iiko, не сбрасывается. Плагин в момент старта банкета не взаимодействует с заказом. До этого на iiko 6 и API v6 все работало.

**Comment by vcpp** [comment]
Вероятно, это было затронуто в 7.0.5 (RMS-49729). По иронии, в той задаче как раз хотели избежать непроизвольного изменения цены. Похоже на ошибку, завёл задачу для расследования (RMS-50783). Как будет решение — сообщим.

----
> элементы заказа с установленной свободной ценой (predefinedPrice) через метод API [AddOrderProductItem](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm)

Я немного уточню терминологию:
* [`PricePredefined`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrderProductItem_PricePredefined.htm) — предопределённая цена, может задаваться только плагинами и только в момент добавления блюда в заказ, изменяться не может (не считая багов). Применимо к любым блюдам.
* [`OpenPrice`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrderProductItem_OpenPrice.htm) — свободная цена, задаётся с помощью метода [`SetOpenPrice`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_SetOpenPrice.htm), может меняться как плагинами, так и пользователем. Применимо только для блюд, в настройках которых включена галочка «Свободная цена» (подробнее [тут](https://ru.iiko.help/articles/iikooffice-7-1/topic-152)).

> При этом цена аналогичных позиций, добавленных через интерфейс iiko, не сбрасывается.

Итого, вы через плагин задаётся predefined price (и он должен побеждать), а пользователь через UI — open price. Вы тоже можете задавать свободную цену с помощью [`SetOpenPrice`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_SetOpenPrice.htm).

**Comment by vcpp** [comment]
Будет исправлено в 9.0.
