### ISSUE TITLE
Получение всех заказов за период из iikoFront

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#12]
Добрый день!

Перед нами стоит задача мониторить изменение информации по заказам на терминале оператора.
Хранит ли iikoFront историю изменения параметров заказа, либо предоставляет всё _as is_, на данный момент?

**Заказы**, по которым мы хотим собирать информацию: простые, доставка курьером, с самовывозом.
Ключевая **информация**: тип заказа, текущий статус, состав блюда, планируемое время доставки/ время доставки, адрес и контакты клиента, курьер, время изменения статусов (приготовлено, отправлено, доставлено и т.п.)

Скажите, пожалуйста, возможно ли реализовать данный алгоритм?

**Comment by ierof** [comment]
Историю изменений не хранит.
Но все инструменты, чтобы реализовать наблюдателя в API есть.

**Comment by vcpp** [comment]
Возможно, вам стоит обратить внимание на API сервера, в частности, на [OLAP-отчёты](http://help.iiko.ru/articles/#!api-documentations/olap-2).
