### ISSUE TITLE
Подписка PluginContext.Notifications.OrderChanged в "Фастфуд" предприятии.

### ISSUE THREAD

**Issue by LokotoshKonstantin** [iiko/front.api.sdk#120]
Добрый день. При разработке плагина столкнулись с трудностями при работе плагина на предприятии типа “Фастфуд” (iiko Front 6.2).
Описание проблемы: не работает подписка PluginContext.Notifications.OrderChanged и PluginContext.Notifications.KitchenOrderChanged. При проведении заказа не вызываются методы. На предприятии типа "Ресторан" все работает.
Вопрос: Есть ли разница в методах подписки между “Ресторан” и “Фаст фуд” версиями организации предприятия? Если есть, то какими аналогичными методами пользоваться?

**Comment by vcpp** [comment]
В режиме обслуживания «Фастфуд» синхронизация заказов между терминалами может быть выключена, соответственно, плагин будет «видеть» лишь заказы, созданные на локальном терминале.

Чтобы включить синхронизацию заказов между терминалами, необходимо назначить один из терминалов главной кассой (подробнее [тут](https://ru.iiko.help/articles/#!iikooffice-7-1/topic-265)).
Другой вариант — установить плагин на все терминалы. Чтобы не разбираться, ставить ли плагин только на главную кассу или на все терминалы, можно указать в манифесте флаг `IsSingleInstance` и всегда ставить плагин на все терминалы (подробнее [тут](https://iiko.github.io/front.api.doc/directories.html).

Если же вдруг плагин «не видит» заказ, оплачиваемый на локальном терминале, надо будет разбираться, понадобятся логи. Логи могут содержать конфиденциальную для вас информацию, и если вы не хотите публиковать её на этой открытой площадке, можете обратиться в техподдержку (api@iiko.ru).
