### ISSUE TITLE
Открыть личную смену.

### ISSUE THREAD

**Issue by pashaparenyuk** [iiko/front.api.sdk#121]
Доброго времени суток. Немного запутались возможно в версиях api фронта, но всё же: Использую Api IikoFront V6-7. Требуется использовать метод открытия личной смены. В документации нашли , а по факту в самой dll что-то не видно метода. Версии dll на которых смотрели  Resto.Front.Api.V7.dll - 7.0.7 и 7.1.6.

Сам метод который отсутствует:

IOperationServiceOpenPersonalSession Method

Подскажите где данный метод присутствует или может его действительно нет в Dll?

**Comment by vcpp** [comment]
Возможность открывать и закрывать личные смены добавлена совсем недавно, эта функция пока доступна лишь для ознакомления в V7 в сборках 7.2.1+ (напомню, версия V7 находится в разработке и меняется в каждой сборке).
В скором времени выйдет версия V7Preview2, где новой функциональностью уже можно будет пользоваться.

Подробнее об этой функции [тут](https://iiko.github.io/front.api.doc/2019/12/27/open-close-personal-sessions.html), о версиях API [тут](https://iiko.github.io/front.api.doc/versioning.html).
