### ISSUE TITLE
Как узнать Id удаляемой предоплаты для ФР

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#124]
Добрый день

Мне необходимо контролировать какая предоплата будет удалена
Пример, гость выполнил 4 предоплаты
1. 100 рублей нал
2. 20 рублей виза
3. 40 рублей мастеркард
4. 20 рублей виза

Мне необходимо удалить 2 предоплату. Могу ли я как-то на основании данных с chequeTask OrderId получить данные именно то что я удаляю 2 операцию, а не 4 ?
Версия API 6

**Comment by astralcake** [comment]
В версии V7 (Preview1) было добавлено поле PrepaymentId в ChequeTask, позволяющее идентифицировать конкретную предоплату.
В более ранних версиях такой возможности не было.
