### ISSUE TITLE
Как слинковать Order и Reserve?

### ISSUE THREAD

**Issue by wildcherrycandy** [iiko/front.api.sdk#125]
Добрый день.

Необходимо при открытии стола из резерва (т.е. закрытии резерва и создания ордера) осуществлять однозначную их линковку. 
Как это можно сделать? Единственный вариант который мы сейчас нашли - это линковка по времени (время закрытия резерва и время создания ордера), но этот вариант железным считать нельзя, т.к. между этими событиями может пройти несколько секунд.

**Вопрос относится к обычным резервам, не банкетным.**

Используем API v5 и v6.

**Comment by vcpp** [comment]
[`BindReserveToOrder`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_BindReserveToOrder.htm)

Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Reserves.html).

**Comment by 0x00000094** [comment]
> [`BindReserveToOrder`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_BindReserveToOrder.htm)
> 
> Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Reserves.html).

Вопрос был о другом. Мы закрываем резерв с созданием заказа (не банкетный), как найти этот заказ? В резерве есть поле с заказом только для банкетов.

**Comment by vcpp** [comment]
Когда приходит гость, резервировавший стол, есть два варианта:

* закрыть резерв и создать заказ, никакой связи между резервом и заказом не останется;
* начать банкет, при этом создастся заказ, привязанный к резерву, и эта связь останется.

Это не вопрос API, это в целом в iikoFront так.
Теоретически можно было бы сохранять связь и между резервом как бронью (не банкетом) и созданным при его закрытии заказом, но нужна мотивация, зачем это делать. Опишите, почему не подходит вариант с банкетом и как планируется использовать связь между закрытым резервом и банкетом.

**Comment by 0x00000094** [comment]
Нам нужно понимать какая сумма чека гостей, сделавших эту бронь (не банкет). Единственный адекватный вариант это узнать - сделать связь между резервом-бронью (не банкетом) и созданным при его закрытии заказом.
Если такая связь уже существует для банкетных резервов, доработка для обычных броней не должна занять много времени :)

**Comment by vcpp** [comment]
Если я правильно понял, вы хотите оценить, сколько гостей и денег приносит внешний источник заказов. У нас для этого используется поле [`OriginName`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrder_OriginName.htm) — если записывать туда названия источников заказа, то затем в iikoOffice можно будет строить OLAP-отчёты в разрезе различных источников. Однако, это поле заказа. У резерва такого поля нет.

Быть может, добавить `OriginName` и резервам тоже? При закрытии резерва название источника будет копироваться в создаваемый заказ. Вам подойдёт такой вариант?

Или нужна связь именно между парами резерв-заказ, чтобы знать, сколько денег принесла каждая конкретная бронь?

**Comment by 0x00000094** [comment]
@vcpp 
> Или нужна связь именно между парами резерв-заказ, чтобы знать, сколько денег принесла каждая конкретная бронь?

Да, нужна связь именно между парами резерв-заказ, нам нужно четко понимать, из какого конкретного резерва был создан заказ, сколько принес резерв и другие поля заказа.

**Comment by vcpp** [comment]
> Единственный вариант который мы сейчас нашли - это линковка по времени (время закрытия резерва и время создания ордера), но этот вариант железным считать нельзя

Увы, более надёжного варианта до сих пор не появилось. Как в итоге показал себя вариант с отслеживанием создания заказа в момент закрытия резерва? Актуально думать над «железным» вариантом или и так работает?

Эта доработка отчасти пересекается с древним багом — это что при оплате банкетного заказа с разделением на несколько ФР в дальнейшем банкетным будет считать только первый полученный при разделении заказ, остальные потеряют свою связь с резервом (внутренний номер задачи: RMS-37797). Когда руки дойдут до исправления этой ошибки, попробуем там же спасать линковку заказа с обычными небанкетными резервами.

**Comment by 0x00000094** [comment]
> Увы, более надёжного варианта до сих пор не появилось. Как в итоге показал себя вариант с отслеживанием создания заказа в момент закрытия резерва? Актуально думать над «железным» вариантом или и так работает?

Как показала практика, такая связь иногда дает сбой, заказ теряется, если по каким-то причинам его создание занимает больше чем n секунд. Увеличение числа n может давать обратный эффект - резерв может линковаться с другими заказами. Жить можно, но все таки хочется более надежный вариант :)

**Comment by vcpp** [comment]
> Жить можно, но все таки хочется более надежный вариант :)

Понятно. Постараемся сделать в одной из будущих версий.
