### ISSUE TITLE
Синхронизация плагинов iikoFront

### ISSUE THREAD

**Issue by pashaparenyuk** [iiko/front.api.sdk#126]
Здравствуйте. Подскажите пожалуйста - почему в некоторых случаях IikoFront требует синхронизировать набор плагинов(т.е на главной кассе стоит плагин, а на офф-станции его нет, требует докинуть на офф.станцию), а в некоторых случаях не требует? Что влияет на механизм синхронизации? Не могу понять закономерности.

И еще один момент- Было бы очень удобно если бы была возможность вызвать ViewManager на экране заказа. Например в доп-меню кнопку добавить -  что-то вроде допустим PluginСontext.Integration.AddButtonToOrderScreen. В идеале чтобы в кнопку эту еще и Context приходил - по аналогии с методами из PaymentPlugin - чтобы можно было редактировать текущую сессию.  Это решило бы проблему с официантскими станциями - когда официанту приходится через экран кассы добавлять внешний тип оплаты, чтобы вызвать PaymentProcessor. Как я понял на офф.станции нет возможности привязать внешний тип оплаты. Похожие методы видел для закрытых заказов и для отмены заказа, полагаю что для открытого заказа по аналогии тоже возможно такое.

**Comment by vcpp** [comment]
> почему в некоторых случаях IikoFront требует синхронизировать набор плагинов(т.е на главной кассе стоит плагин, а на офф-станции его нет, требует докинуть на офф.станцию), а в некоторых случаях не требует?

Есть два вида плагинов:
* обычные, про которые мы здесь говорим, они запускаются в отдельных процессах и используют iikoFront API;
* внутренние, разрабатываемые в iiko, они запускаются внутри приложения iikoFront и напрямую используют внутренние функции.

Для обычных апишных плагинов никакой «синхронизации» или «докидывания» не требуется, плагины можно установить на любой терминал, на один, на несколько, на все, как хотите. Обсуждать внутренние плагины смысла нет, по ним нет ни документации, ни поддержки, ни обратной совместимости.

> возможность вызвать ViewManager на экране заказа

Да, такую возможность уже не раз просили (#98), сделаем в одной из будущих версий.
