### ISSUE TITLE
Вопросы по реализация внешней системы оплаты

### ISSUE THREAD

**Issue by A16ert** [iiko/front.api.sdk#13]
Добрый день!

1. может ли метод Pay быть асинхронным, мне нужно отправить в нём запрос, и в зависимости от ответа либо провести, либо отменить оплату. Сейчас метод асинхронный и плагин вылетает с ошибкой: Another payment processor with key '' was already registered

2. можно ли отменить оплату, используя throw new PaymentActionFailedException("Платеж не прошёл."); 
плагин вылетает с такой же ошибкой даже если метод pay пустой и реализует только это исключение (Another payment processor with key '' was already registered)

**Comment by ierof** [comment]
1. Приведенная вами ошибка говорит о том, что вы пытаетесь зарегистрировать второй процессор оплаты с тем же ключом, что уже был ранее зарегистрирован (см статью про [внешние типы оплаты](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html)).
Судя по всему вы регистрируете свой тип оплаты с пустым ключом. Задайте у вашей реализации `IExternalPaymentProcessor` непустой `PaymentSystemKey`.
Пример можно посмотреть на [gitlab.iiko.ru](https://gitlab.iiko.ru/iikoPublic/iikoFrontSDK/blob/master/Resto.Front.Api.SamplePaymentPlugin/ExternalPaymentProcessorSample.cs).

2. Это, видимо, следствие вашего предыдущего вопроса. Попробуйте правильно реализовать процессор оплаты и проверить данный кейс.

**Comment by A16ert** [comment]
да понимаю, задача как раз состоит в том что бы отправить на удалённый сервер сумму использованной кастомной валюты, и в зависимости от того какой ответ придёт от сервера продолжить оплату, либо отменить. Как раз для этого мне и нужна асинхронность

PaymentSystemKey я указываю, и думаю проблема не в нём иначе я бы не смог зарегистрировать внешний процессор оплаты в IikoOffice

**Comment by ierof** [comment]
Тогда описанное вами поведение довольно странное.
Ошибка типа `PaymentSystemRegistrationException` с текстом `Another payment processor with key '...` может вернуться только из метода `RegisterPaymentSystem`.

Сколько в вашем плагине классов, реализующих `IExternalPaymentProcessor`?
Сколько раз в вашем плагине вызывается `RegisterPaymentSystem`, в какой момента и для каких объектов?

**Comment by ierof** [comment]
@A16ert , есть новости?

Если у вас строго один тип реализует `IExternalPaymentProcessor`, его экземпляр строго один раз регистрируется в конструкторе плагина, но при оплате вашим типом данная проблема наблюдается, можно ли посмотреть на ваш исходный код?

**Comment by ierof** [comment]
@A16ert , есть новости? 
Прошло уже 17 дней... А то скоро закроем вашу заявку :)

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
