### ISSUE TITLE
Диалоговое окно

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#130]
Добрый день.
У меня имется `2D сканнер-клавиатура`.
![image](https://user-images.githubusercontent.com/51437851/80584856-64ed8e80-8a23-11ea-8fee-1de7fb188ccd.png)
 
Мне необходимо, чтобы результат отсканированного значения выводился в `Диалогe ввода произвольных строк`. Однако при сканировании в диалоговом окне ничего не отображается.
Вот код:
```
viewManager.ShowKeyboard("тест", isMultiline:false) ;
```

Следующий код работает нормально. Т.е сканирую карту, диалоговое окно автоматически   закрывается, получаю результат `ICardInputResult result `

```
ExtendedInputSettings settings = new ExtendedInputSettings {EnableCardSlider = true, EnableNumericString = true, TabTitleNumericString = "Введите нoмер карты"};
            ICardInputResult result = viewManager.ShowExtendedNumericInputPopup("Loona loyalty", "", settings) as ICardInputResult;
       
```

Пробовал в config.xml добавить следующие настройки. Не помогает
```
<allowedParsers>barcode</allowedParsers>
<useKeyboardBarcodeScaner>true</useKeyboardBarcodeScaner>
```

Пробовал в iikoOffice добавить наш сканер, тоже не помогает
![image](https://user-images.githubusercontent.com/51437851/80586437-05dd4900-8a26-11ea-9da1-53ed2cba8143.png)

Скажите пожалуйста, как сделать чтобы `Диалог ввода произвольных строк` отображал отсканированое значение 2д сканера

**Comment by HakobyanAram** [comment]
В %appdata%\iiko\CashServer\readerDevicesConfig.xml нашел наше устройство. Тип устройства был "Barcode", заменил его на "Keyboard" и он заработал.
```
  <Id>3ad01152-02d1-4ec4-a9d8-2796fdad1271</Id>
      <Name>Сканер штрихкода HID</Name>
      <Type>Barcode</Type> Заменил на  <Type>Keyboard</Type>
      <DeviceName>HID Keyboard Device</DeviceName>
      <IsAutoSettings>true</IsAutoSettings>
      <SetupMethod>PrefixSuffix</SetupMethod>
      <Prefix />
      <Suffix>\r</Suffix>
      <Mask />
      <Regex />
      <IntercharacterTimeout>0</IntercharacterTimeout>
      <CaseConversion>AutoDetect</CaseConversion>
    </Device>
```

1. Может это изменение испортить что-то в iiko?
2. После сканирования диалгоговое окно автоматически не закрывается. Возможно ли сделать так чтоб оно закрывалось, как в случае `ExtendedNumericInputPopup`?

**Comment by HakobyanAram** [comment]
Вместо того чтобы вручную изменять readerDevicesConfig.xml нашли другой путь из iikoFront.
![image](https://user-images.githubusercontent.com/51437851/80747141-0237e800-8b34-11ea-950f-8eb1231a2dbe.png)

**Comment by vcpp** [comment]
> Мне необходимо, чтобы результат отсканированного значения выводился в Диалогe ввода произвольных строк.

А почему именно диалог ввода произвольных строк? Зачем вашему сканеру экранная клавиатура? Диалог ввода штрихкодов не подходит?

> Может это изменение испортить что-то в iiko?

Эти настройки влияют только на то, как приложение интерпретирует данные от вашего устройства. Если вы указываете, что это клавиатура, то приложение будет интерпретировать ввод как ручной набор текста на клавиатуре. Если для считывателей карт и сканеров штрихкодов можно указать маркер конца (стоп-символ) или таймаут бездействия, позволяющие понять, что ввод завершён, то для клавиатурного ввода такой возможности нет. Пользователь может печатать сколь угодно медленно и как угодно долго, и никто не знает, он уже набрал, что хотел, или ещё нет. Пользователь может нажать `Enter`, что в однострочном режиме (`isMultiline: false`) будет означать завершение ввода и закрытие диалога.

> Скажите пожалуйста, как сделать чтобы Диалог ввода произвольных строк отображал отсканированое значение 2д сканера
> После сканирования диалгоговое окно автоматически не закрывается. Возможно ли сделать так чтоб оно закрывалось, как в случае `ExtendedNumericInputPopup`?

Так вы хотите, чтобы после сканирования диалог автоматически закрылся или отображал отсканированное значение? ;-)

**Comment by HakobyanAram** [comment]
> А почему именно диалог ввода произвольных строк? Зачем вашему сканеру экранная клавиатура? Диалог ввода штрихкодов не подходит?

Шаблон нашего QR кода 123-456. т.к. в ExtendedNumericInputPopup отсутствует символ  "-",  поэтому решили использовать диалог ввода произвольных строк. Наши клиенты вводят код, как вручную, так и при помощи сканнера.

> Так вы хотите, чтобы после сканирования диалог автоматически закрылся или отображал отсканированное значение? ;-)

Желательно, чтоб он автоматически закртылся.

**Comment by HakobyanAram** [comment]
> Вместо того чтобы вручную изменять readerDevicesConfig.xml нашли другой путь из iikoFront.
> ![image](https://user-images.githubusercontent.com/51437851/80747141-0237e800-8b34-11ea-950f-8eb1231a2dbe.png)

После настройки iiko выше указанным образом, время от времени выскакивает вот такое сообщение 
![image](https://user-images.githubusercontent.com/51437851/82439526-e036e300-9aab-11ea-8ecc-345d1eff0c75.png)

После чего сканер не работает (тип `"Сканер штрихкода HID"` сбрасывается с `"Клавиатура"` на `"Сканер штрихкода"`)

**Comment by HakobyanAram** [comment]
Мы решили для ручного ввода показывать `"Экранную клавиатуру"`, а при сканировании `"Диалог ввода штрихкодов"`. Но если кто-то установит тип `"Сканера штрихкода HID"` на `"Клавиатуру"`, то тогда  `"Диалог ввода штрихкодов"` не будет работать. 
Как можно через API определить тип `"Сканера штрихкода HID"`?

**Comment by rengal** [comment]
Вариант, при котором iiko распознает штрихкоды от устройства и генерирует события, но никак не блокирует клавиатурный ввод от них, подойдет для вашего сценария? То есть, клавиатурные нажатия от штрихкода будут отображены на текущем текстовом поле, где находится фокус ввода.

PS. В вашем сценарии предполагается аппаратная зависимость поведения UI (от типа подключения сканера). Например, сканер, подключенный через COM-порт или USB сканер в режиме эмуляции COM-порта никак не оказывают никакого воздействия на текстовое поле с фокусом ввода.

**Comment by vcpp** [comment]
> Шаблон нашего QR кода 123-456/125. т.к. в ExtendedNumericInputPopup отсутствует символы `"-", "/"`, поэтому решили использовать диалог ввода произвольных строк. Наши клиенты вводят код, как вручную, так и при помощи сканнера.

Да, теперь понятно, полезное требование. Подумаем, как это лучше оформить и реализуем в одной из следующих версий.

>> Пользователь может нажать `Enter`, что в однострочном режиме (`isMultiline: false`) будет означать завершение ввода и >> закрытие диалога.
>
> При `Multiline: false` `Enter` не активен. При нажатии на `Enter` ничего не происходит

Я говорил про физическую клавишу `Enter`, роль которой меняется в зависимости от флага `isMultiline` — новая строка или закрыть диалог. Разумеется, экранная кнопка `Enter` недоступна при вводе однострочного текста, ибо для закрытия диалога есть отдельная кнопка `OK`.

> время от времени выскакивает вот такое сообщение
> После чего сканер не работает

Надо разбираться с настройками таймаута, префикса и суффикса (старт-стоп флаги). Поскольку это не про API, лучше обратиться в основную техподдержку, прикрепив к заявке конфиги и логи.

> Мы решили для ручного ввода показывать `"Экранную клавиатуру"`, а при сканировании `"Диалог ввода штрихкодов"`.

А как вы определяете, какой из диалогов показать? Вы заранее знаете, как пользователь будет вводить штрихкод — через сканер или вручную?

> если кто-то установит тип "Сканера штрихкода HID" на "Клавиатуру", то тогда "Диалог ввода штрихкодов" не будет работать.
> Как можно через API определить тип "Сканера штрихкода HID"?

А кто и зачем может захотеть ввод от сканера штрихкодов учитывать как ввод с клавиатуры? Настройки устройств ввода сейчас недоступны через API.

**Comment by vcpp** [comment]
>> Наши клиенты вводят код, как вручную, так и при помощи сканнера.
>
> реализуем в одной из следующих версий.

Начиная с V7 добавили метод [`ShowExtendedKeyboardDialog`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowExtendedKeyboardDialog.htm), позволяющий комбинировать ввод штрихкода вручную и через сканер, подробнее [тут](https://iiko.github.io/front.api.doc/2021/12/09/extended-keyboard-dialog.html).

По остальным вопросам ответов не поступило, поэтому закрою задачу по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
