### ISSUE TITLE
Обработка проверки добавления позиции в заказ

### ISSUE THREAD

**Issue by popowich** [iiko/front.api.sdk#131]
Здравствуйте. Ситуация: заказ редактируется интерактивно, необходимо в плагине отловить добавление заказа, проверить по своим правилам и при некоторых условиях не дать добавить позицию или удалить ее с некоторым сообщением. Возможно ли это ? Я не нахожу события перед добавлением позиции, а после добавления уже поздно, я так понимаю, заказ залочен из из плагина не изменяем(что кстати очень печалит и создает проблемы в большом количестве решений((( )

**Comment by vcpp** [comment]
Увы, в текущих версиях API нельзя вклиниться в операцию добавления блюда в заказ, но рано или поздно мы добавим такую возможность.

Чтобы нам лучше понимать ваши потребности, поделитесь, пожалуйста, в каких случаях вы хотите ограничивать добавление блюд, в чём заключается функция плагина?

**Comment by popowich** [comment]
1. Допустим мы делаем некую систему с купонами. Юзер открывает новый заказ, накидывает позиции, в нашей форме применяет купон, при этом на позиции заказа накидывается некая скидка. Вышел из заказа. Потом открыл его снова и докидывает туда еще позицию. Вот тут было бы не плохо поймать момент перед добавлением позиции и дать окно диалога с вопросом(напомнить что тут применен купон и т.п.) и если он ответит "Нет" отменить добавление. Тут в принципе тогда и самый неудобный момент в API не мешал бы - лок на заказ для плагина, когда заказа редактируется.  
2. Но конечно самый неудобный момент в API - лок заказа окном редактирования. Лично у меня в доброй половине плагином возникает жесткая необходимость что то изменить в заказе в момент, когда он открыт, примеры: накинуть/снять скидку, оплатить заказ, изменить состав позиций и т.п. приходится колхозить и извращаться(поминая добрым и не очень словом  тех кто это придумал) А если например юзер открыл, накидал позиции и сразу перевел его в Bill тут вообще плохо т.к. заказ уже не изменяем... в общем одни велосипеды
3. Раз уж на то пошло, буду жаловать по полной))  Вот замечательная подписка ScreenChanged НО но почему так мало вариантов окон можно из нее идентифицировать ?! самое смешное, что оно срабатывает при каждом переходе, но куда оно перешло я могу только в 4-х случаях, обидно просто)  ну хотя бы свойство "ScreenName" добавьте и все ))
4. Было бы классно, если бы к заказу можно было цеплять какие то свои данные, пусть немного, просто из-за этого приходится делать свою БД, порою на 1 -2 таблицы.Было бы удобно, но наверное это сложно
5. Возможность вызова IViewManager не только в узком кругу некоторых событий, а в принципе когда нужно, надоело пилить свои кастомные диалоговые окна... 
6. Да и вот недавно столкнулся. Создаю сессию редактирования, создаю заказ доставку, накидываю позиции, забываю про некий обязательный модификатор, делаю сейв. Конечно валится ошибка Resto.Front.Api.V6.Exceptions.ConstraintViolationException: Order item modifier “Степерь прожарки” (c94d7038-1119-4b5d-9651-2ed09732210f) has invalid group amount: min = 2, max = 2, actual = 0. Ensure that interconnected product and modifier changes are in the same edit session
ок, все хорошо, но один глупый вопрос, а это в какой позиции заказа проблема ?) я было подумал c94d7038-1119-4b5d-9651-2ed09732210f -это id позиции, ан нет это скорее всего id группы или папки модификатора, НО точно не Id позиции(проверял, даже ставил свой Id новой позиции, одна из перегрузок метода это позволяет ) Вот еще одна маленькая подстава) а мне надо бы это обработать проблему и все таки записать заказ, я не буду описывать свой очередной костыль...))

Ну вот, только то что сейчас на ум пришло)) А так в целом мне нравится, хорошая система)

**Comment by letolica** [comment]
Мы добавили возможность редактировать открытый на фронте заказ в RMS-51383, редактировать заказ перед пречеком в RMS-51740. Следите за [новостями](https://iiko.github.io/front.api.doc/changelog.html).

> Вот замечательная подписка ScreenChanged НО но почему так мало вариантов окон можно из нее идентифицировать ?!

Ссылка на новость: [Расширена детализация популярных экранов](https://iiko.github.io/front.api.doc/2020/08/25/screen-changed.html).

> Было бы классно, если бы к заказу можно было цеплять какие то свои данные, пусть немного, просто из-за этого приходится делать свою БД, порою на 1 -2 таблицы.Было бы удобно, но наверное это сложно

Вы не пробовали пользоваться методами: [`TryGetOrderExternalDataByKey`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_TryGetOrderExternalDataByKey.htm), [`AddOrderExternalData`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_OperationServiceExtensions_AddOrderExternalData.htm), [`DeleteOrderExternalData`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_OperationServiceExtensions_DeleteOrderExternalData.htm)?

**Comment by vcpp** [comment]
1. Идея понятна, спасибо. Подумаем, как лучше реализовать. Поскольку добавление блюда может сопровождаться ещё и штатными диалогами (выбор размера, модификаторов, цены и т. п.), вероятно, понадобится две точки расширения — до и после штатных вопросов.
2. О, да, боль-боль. Работаем над этим, кое-что уже можно посмотреть в preview-версиях V7. Например, изменение через API заказа, открытого на экране редактирования iikoFront, доступно в V7 начиная с 7.5.2, соответственно, полноценно пользоваться этим можно будет в V7Preview5+.
3. Доработано в V7Preview4.
4. Поддерживается в V5+, см. предыдущий коммент.
5. Надо отделить нехватку типов диалоговых окон и нехватку мест, где доступен `IViewManager`. Набор штатных окон невелик, это правда, постепенно добавляем новые окна. Если есть потребность в каком-то типовом диалоге, дайте знать, постараемся добавить. Совсем уж кастомные окна, нужные только одному плагину, понятно, так и останутся кастомными в плагине. Отдельная история — это операция, в контексте которой происходит взаимодействие с пользователем. Тут тоже список постепенно расширяется с учётом спроса и ресурсов. Напишите, на каких экранах, при выполнении каких операций чаще всего не хватает `IVewManager`.
6. Интересное замечание. Можно добавить отдельный тип исключения, где будут поля с подробностями. Парсить сообщение в любом случае нехорошо, даже если бы там был нужный идентификатор. Другой вопрос, что плагину делать с этой ошибкой? Показать её пользователю, когда он завершил ввод заказа? Тогда красивее было бы делать валидацию на лету по мере ввода, благо, информация о min/max лимитах модификаторов доступна.

**Comment by letolica** [comment]
Готово. [Экран редактирования заказа позволяет вносить изменения по инициативе плагина](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html).
