### ISSUE TITLE
Диалоговое окно с тремя кнопками

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#132]
Добрый день. 
Скажите пожалуйста есть ли возмжожность отркрыть диалоговое окно с тремя кнопками `"да", "нет", "отменить"`

**Comment by vcpp** [comment]
Хм.. действительно, не хватает такого окошка, добавим (RMS-51249).

В качестве временного решения могу предложить использовать [`ShowChooserPopup`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_UI_IViewManager_ShowChooserPopup.htm) с вариантами «Да» и «Нет» (кнопка «Отмена» является частью окна). Выглядеть это, правда, будет необычно, вот пример из [документации](https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html):
![пример](https://iiko.github.io/front.api.doc/img/viewmanager/chooser.png)

**Comment by vcpp** [comment]
[Добавлена возможность показывать сообщения со стандартными сочетаниями кнопок](https://iiko.github.io/front.api.doc/2020/06/17/message-box-buttons.html).
