### ISSUE TITLE
Подписка на вход в IScreen с доставкой

### ISSUE THREAD

**Issue by Nofuq** [iiko/front.api.sdk#133]
Подскажите как именно отловить момент входа в экран с доставочным заказом
Стандартными методами через подписку на  ScreenChanged, с последующим кастом в IScreenWithOrder не получилось
Подчеркиваю что нужен именно доставочный заказ

**Comment by Nofuq** [comment]
UPD Пробовали и на API V5 и на V6, версия 7.2.6

**Comment by Nofuq** [comment]
UPD Этот IScreen сейчас кастится только в IUnkownScreen

**Comment by vcpp** [comment]
Да, сейчас у [`IScreen`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Screens_IScreen.htm) только три наследника:

- [`IOrderEditScreen`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Screens_IOrderEditScreen.htm) — экран редактирования обычного заказа (режимы фастфуд/ресторан),
- [`IOrderPayScreen`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Screens_IOrderPayScreen.htm) — экран оплаты любого заказа, включая доставочные заказы,
- [`IUnknownScreen`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Screens_IUnknownScreen.htm) — все остальные экраны, включая экран редактирования доставки.

Спасибо за напоминание, добавим детализацию для популярных экранов (RMS-51246).

**Comment by letolika** [comment]
[Готово.](http://iiko.github.io/front.api.doc/2020/08/25/screen-changed.html)
