### ISSUE TITLE
Преобразование из IOrderRootItem в IOrderCookingItem

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#134]
Добрый день.
Работаем с Resto.Front.Api V6.Есть IOrder и IKitchenOrder.В них есть IOrderRootItem и IOrderCookingItem.И если у IKitchenOrder есть BaseOrderId, который позволяет понять, какому заказу соответствует кухонный заказ, то с поиском позиций вопрос сложнее.

Собственно, сам вопрос: как, имея в наличии IOrderCookingItem, найти IOrderRootItem из заказа с BaseOrderId?

**Comment by vcpp** [comment]
> как, имея в наличии IOrderCookingItem, найти IOrderRootItem из заказа с BaseOrderId?

[`IOrderCookingItem`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Orders_IOrderCookingItem.htm) является прямым наследником [`IOrderRootItem`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Orders_IOrderRootItem.htm), а вы, наверное, спрашивали про [`IKitchenOrderCookingItem`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Kitchen_IKitchenOrderCookingItem.htm).

К сожалению, связь между блюдами в кухонном заказе и соответствующими им блюдами в исходном заказе не публикуется, поэтому сопоставить их прямо сейчас не получится. Понятно, что раз есть ссылка на исходный заказ ([`BaseOrderId`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder_BaseOrderId.htm)), то логично было бы и в кухонных блюдах давать ссылки на соответствующие исходные блюда. Спасибо за замечание, доделаем (RMS-51244).

В качестве временного решения могу предложить сопоставление по косвенным признакам — по ссылке на продукт, количеству, курсу, времени печати, составу модификаторов и т. п. Конечно, в заказе могут быть абсолютно одинаковые блюда, которые без id не различить, в этих случаях будет неоднозначность.

**Comment by vcpp** [comment]
> Спасибо за замечание, доделаем (RMS-51244).

[Доделали](https://iiko.github.io/front.api.doc/2020/06/26/kitchen-order-item-refs.html) в V7Preview3.

**Comment by CLTanuki** [comment]
Премного благодарны! Пойдём исследовать.

**Comment by RomanProtas** [comment]
Коллеги, добрый день! В api V7Preview3 для версий 7.4.1 и 7.3.6 свойства BaseOrderItemId в IKitchenOrderCookingItem нет. 
Прикрепляю скриншоты интерфейса.
![image](https://user-images.githubusercontent.com/46530239/88185170-4c64cd00-cc3c-11ea-840b-858abed76551.png)
![image](https://user-images.githubusercontent.com/46530239/88185310-74543080-cc3c-11ea-9fa6-2484b0846d1b.png)

**Comment by vcpp** [comment]
Да, вы правы.
Версия V7Preview3 ответвилась от V7 в 7.3.6, а уже после этого в 7.4.1 в V7 была добавлена обещанная доработка. Таким образом, доработка не попала в V7Preview3, свойство `IKitchenOrderCookingItem.BaseOrderItemId` доступно начиная с 7.4.1 только в незафиксированной версии V7 и в будущем попадёт в V7Preview4.

Предлагаю таки бэкпортировать доработку в V7Preview3. В вышедшие релизы это уже не попадёт, будет доступно с ближайшего (7.4.2 или 7.4.3).

В [новости](https://iiko.github.io/front.api.doc/2020/06/26/kitchen-order-item-refs.html) ошибочно указано, что доступно в V7Preview3, поправим.
