### ISSUE TITLE
Текущий авторизированный пользователь

### ISSUE THREAD

**Issue by mgdmiller** [iiko/front.api.sdk#136]
Добрый день!

Подскажите, как получить текущего авторизированного на фронте пользователя.

**Comment by mgdmiller** [comment]
От клиента поступил запрос реализовать функционал отправки целевых сообщений для пользователя. Для этого необходимо иметь информацию о текущем пользователе.

**Comment by letolika** [comment]
Заведена задача на доработку (RMS-51323).

**Comment by letolika** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/07/12/current-user-changed.html)
