### ISSUE TITLE
PluginContext.Operations.BillOrder возвращает повторную печать пречека

### ISSUE THREAD

**Issue by pgulyaev88** [iiko/front.api.sdk#137]
Доброго дня. 
Вызываю метод PluginContext.Operations.BillOrder(credentials, order, 42) для получения шаблона печати пречека, но для новых заказов на пречеке печатается "ПОВТОРНЫЙ ГОСТЕВОЙ СЧЕТ № 1" так же если сделать отмену пречека и повторно напечатать то в шаблоне уже будет писать "ПОВТОРНЫЙ ГОСТЕВОЙ СЧЕТ № 3". Подскажите пожалуйста почему пишет "повторный", и почему нумерация идёт не по порядку.

**Comment by pgulyaev88** [comment]
На фронте создаю заказ, добавил блюдо. печать, зайти в стол , пречек, отмена пречека. пречек. 
В API если billTask.IsCancellation || billTask.IsRefund то ничего не делаем, только лог пишем. в остальном случае печать пречека. посмотрел virtual-printer.log почему то туда печатается сначала счёт. в системе нет никаких принтеров кроме ФР. Заказ № 95
[virtual-printer.log](https://github.com/iiko/front.api.sdk/files/4763931/virtual-printer.log)

**Comment by letolika** [comment]
То есть вы вызываете `PluginContext.Operations.BillOrder` в `ICashRegister.DoBillCheque`?

**Comment by pgulyaev88** [comment]
Да в методе CashRegisterResult DoBillCheque. Как это показано в примере [тут](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/EditorTester.cs)

`
PluginContext.Log.Info($"Print Bill Order for {order.Number} - {order.Id} : {pos?.Name} - {pos?.Id}");
var x = PluginContext.Operations.BillOrder(credentials, PluginContext.Operations.GetOrderById(orderId), 42);
x.ToString();
PluginContext.Log.Info(x);
`
x отправляю в метод нефискальной печати PrintText()

В описании метода в [API](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_BillOrder.htm) не сказано что это печать копии.

**Comment by pgulyaev88** [comment]
Добрый день
@letolika есть информация по проблеме?

**Comment by letolika** [comment]
Добрый день.

Нажимая на кнопку "Пречек" в заказе в первый раз, происходит перевод статуса заказа из `New` в `Bill`, заодно печатается чек в `virtual-printer.log` и на принтер пречеков, который указывается в настройках отделения, в котором находится заказ. У этого первого чека заголовок _ГОСТЕВОЙ СЧЕТ_. Дальше для обработки перевода заказа в статус `Bill` управление передается в метод `DoBillCheque`. А вы в нем зачем-то еще раз вызываете пречек заказа `PluginContext.Operations.BillOrder`, что некорректно, ведь заказ уже переведен в статус `Bill`. Поскольку заказ уже переведен в статус `Bill`, статус не меняется, просто формируется еще один повторный чек, который в виде строки вы передаете в `PrintText`. У этого повторного чека, который был возвращен методом `PluginContext.Operations.BillOrder`, заголовок _ПОВТОРНЫЙ ГОСТЕВОЙ СЧЕТ № 1_. Ну и далее после отмены пречека во фронте ситуация повторяется: еще один повторный пречек из фронта даёт _ПОВТОРНЫЙ ГОСТЕВОЙ СЧЕТ № 2_, а обработчик в плагине даёт _ПОВТОРНЫЙ ГОСТЕВОЙ СЧЕТ № 3_.

Чтобы иметь возможность печатать разметку пречека в плагине, достаточно выбрать в качестве принтера пречеков ваш внешний фискальный регистратор в iikoBackOffice (тогда при нажатии на кнопку "Пречек" управление автоматически передастся в `PrintText`):
![2020-06-19_1330](https://user-images.githubusercontent.com/51158040/85123559-20b38900-b231-11ea-8253-d724b332ec34.png)
А из `DoBillCheque` вызов `PluginContext.Operations.BillOrder` нужно убрать. Потому что если клиент выставит в iikoBackOffice настройку торгового предприятия "Оставаться на экране заказа после пречека"
![2020-06-19_1333](https://user-images.githubusercontent.com/51158040/85123787-8b64c480-b231-11ea-8d4d-4b77eba6bef7.png)
 то ваш код будет падать с такой ошибкой:
`Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.`

Что касается последовательной нумерации пречеков — это работает по спецификации. Если в заголовке пречека в принципе нежелательно вести нумерацию, то можно отредактировать шаблон. Подробнее в [документации](https://ru.iiko.help/articles/#!iikooffice-7-2/topic-707).
