### ISSUE TITLE
Ввод штрихкода вручную

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#138]
Добрый день.
не дождавшись ответа на #130 вопрос решили имплементировать штрих код без символов "-" и "/". 
Для ввода штрихкода используем `"Диалог ввода штрих кодов"`
```
ExtendedInputSettings settings = new ExtendedInputSettings {EnableCardSlider = true, EnableNumericString = true, TabTitleNumericString = "Введите нoмер карты"};
ICardInputResult result = viewManager.ShowExtendedNumericInputPopup("Loona loyalty", "", settings) as ICardInputResult;
```
Возникла следующая проблема. Метод `ShowExtendedNumericInputPopup` возвращает `null`, когда ввожу код вручную (Без 2Д сканнера)

Нам нужно, чтобы пользователь имел возможность вводить штрих кода, как вручную так и `2Д сканнером`,
Скажите пожалуйста, как решить проблему?

**Comment by HakobyanAram** [comment]
Решили вопрос следующим образом:
```
ExtendedInputSettings settings = new ExtendedInputSettings {EnableCardSlider = true, EnableNumericString = true, TabTitleNumericString = "Введите нoмер карты"};
IInputResult result = viewManager.ShowExtendedNumericInputPopup("loyalty", "", settings);
if (result is INumericStringInputResult stringInputResult)
{
     return stringInputResult.NumericString;
}
if (result is ICardInputResult inputResult)
{
    return inputResult?.Track2;
}

```

**Comment by vcpp** [comment]
>> Метод `ShowExtendedNumericInputPopup` возвращает `null`, когда ввожу код вручную (Без 2Д сканнера)
>
> `if (result is INumericStringInputResult stringInputResult)`

Верно, при вводе строки цифр метод вернёт не `null`, а `INumericStringInputResult` (начиная с V6 — `NumericStringInputDialogResult`).

Спасибо, что вернулись с ответом на свой же вопрос, глядишь, кто-то ещё будет искать и найдёт. Сами видите, не успеваем отвечать...
