### ISSUE TITLE
ошибка с текстом "Необходимо разделить заказ по местам приготовления до оплаты."

### ISSUE THREAD

**Issue by jurijshevtsov** [iiko/front.api.sdk#139]
При выполнении внешней оплаты через АПИ получаю ошибку с текстом.
Resto.Front.Api.Exceptions.PaymentActionFailedException: Необходимо разделить заказ по местам приготовления до оплаты.

У меня 2 машины с iiko. На стенде все ОК, а на проде получаю данную ошибку. НА что нужно обратить внимание при оплате?

**Comment by vcpp** [comment]
Необходимо проверить необходимость разделения заказа с помощью метода [`NeedToSplitOrderBeforePayment`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_NeedToSplitOrderBeforePayment.htm).
Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/GroupsAndPointsOfSale.html).
