### ISSUE TITLE
Использование viewManager при переходе на экран оплаты.

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#14]
Поскольку тип оплаты не может быть установлен по умолчанию с ограничением по типу заказа, но при этом не валиден для заказов доставки и предоплаты, единственным выходом видится прохождение процедуры в момент перехода на экран оплаты с ручной фильтрацией.
Однако, в делегат SubscribeOnNavigatingToPaymentScreen не передаётся viewManager. Как следствие, невозможно использовать родные формы. Можете ли подксазать, как добыть viewManager либо дать xaml и xaml.cs код ExtendedInputDialog и InputDialog для соблюдения стиля iiko в стороннем решении (тип оплаты [Sail Play](https://ru.iiko.help/articles/#!special-iiko/sailplay-payment)).

**Comment by ierof** [comment]
Пример окон в рамках github выдать вам точно не можем. И как-то это не true way вот такими WA пользоваться. 

У вас достаточно сложный вопрос, потому что ваш тип оплаты:
- должен добавляться автоматически
- но не во все заказы, а в соответствии с какой-то бизнес-логикой
- и при этом добавление айтема оплаты вашего типа требует взаимодействия м пользователем. 

Нам нужно время подумать, что мы можем вам предложить как true way fix.

**Comment by CLTanuki** [comment]
@ierof , спасибо, мы уже отрисовали все формы сами.
Соблюдение визуального стиля будет возможно после доработки API.

**Comment by ierof** [comment]
Мы пока ещё думаем, что можно вам предложить для такого нетривиального бизнес-сценария, когда типы оплаты зависят от типов заказа и типов платежа. В бизнес-процессах iiko ранее таких требований не возникало: все типы пригодны для всего. А если тип не пригоден, то пользователь об этом уведомлялся в процессе добавления его в заказ. 
И крайне редко используются экзотические типы оплаты в качестве типов оплаты по умолчанию.

**Comment by ierof** [comment]
Уточните пожалуйста, какие у вас есть бизнес-ограничения для вашего типа оплаты?

Чем не подходит вам такой флоу:
- Ваш тип оплаты сделать типом "по умолчанию"
- При навигации на кассу в "неподходящих" доставочных заказах добавлять оплату наличными на полную сумму:
```
// Код (с моими константами – pin-ом сотрудника с правом добавлять оплаты):
subscription = PluginContext.Notifications.SubscribeOnNavigatingToPaymentScreen((order, pos, operations, pb) =>
{
   if (!(order is IDeliveryOrder))
	   return;
   /// TODO: Убедиться, что тут выбираются верные "Наличные", потому что вычисление эмпирическое. 
   var paymentType = PluginContext.Operations
	   .GetPaymentTypes()
	   .Last(p => p.Kind == PaymentTypeKind.Cash 
                      && p.CanDisplayChange 
                      && p.CanBeExternalProcessed
                      && p.IsEnabled &&
                      !p.IsHidden);
   PluginContext.Log.Info($"Payment type {paymentType?.Name}");
   if (paymentType == null)
	   return;
   var sum = order.ResultSum - order.Payments.Sum(s => s.Sum);
   if (sum <= 0)
	   return;
   PluginContext.Log.Info($"Payment type {paymentType.Name}, sum {sum}");
   operations.AddExternalPaymentItem(sum, false, null, paymentType, order, operations.AuthenticateByPin("777"));
});
```

таким образом получится, что при заходе на кассу для обычного заказа будет вызываться штатная механика добавления айтема, а при заходе на кассу в неподходящий заказ будут добавлены наличные. 

А чтобы застраховаться от добавления айтема в предоплатах, можно удалять такой айтем форсировано при добавлении
```
public void OnPaymentAdded(IOrder order, IPaymentItem paymentItem, [NotNull] IUser cashier, [NotNull] IOperationService operations, IReceiptPrinter printer, IViewManager viewManager,
	IPaymentDataContext context, IProgressBar progressBar)
{
	if (order is IDeliveryOrder)
	{
		var session = operations.CreateEditSession();
		session.DeletePaymentItem(paymentItem, order);
		operations.SubmitChanges(operations.GetCredentials(), session);
...
```

**Comment by ierof** [comment]
> Можете ли подксазать, как добыть viewManager

На эту тему у нас заведена задача (номер RMS-49051), планируется в релизе 6.4 и V6 (V6Preview5)

**Comment by CLTanuki** [comment]
К сожалению, механика OnPaymentAdded вызывается только ПОСЛЕ того, как пользователь ввёл сумму и нажал "добавить" в предоплатах. Такова реализация iiko, а не плагина. Это сильно фрустрирует персонал.

**Comment by ierof** [comment]
А каково было бы желаемое поведение в окне предоплат для вас?

**Comment by vcpp** [comment]
Задача RMS-49051 сделана, `IViewManager` станет доступен при переходе на экран оплаты, начиная с API V6.
Дискуссия об альтернативных вариантах достижения желаемой цели, будем считать, завершена по таймауту. Если интерес к альтернативным вариантам вдруг возродится, лучше вынести их в отдельную задачу.
