### ISSUE TITLE
FrontWeb API резервирование столов

### ISSUE THREAD

**Issue by k1p1l** [iiko/front.api.sdk#140]
Добрый день!
Требуется интегрировать iiko в web приложение. На сайте будет реализован функционал бронирование столов. 

Вопрос
Как мне получить данные о зарезервированных столах, и отправить данные о брони данного стола. В документации к   FrontWebApi  имеется пункт "Доступные справочники" в котором есть подпункт "Столы", я так понимаю это методы для бронирования столов? Какие данные я должен отправить. Какие данные я получу. 

Спасибо за оказанную помощь

**Comment by vcpp** [comment]
WebAPI (Resto.Front.Api.WebServer) пока предоставляет лишь доступ на чтение.
Для резервирования столов придётся писать .Net-плагин, описание [тут|https://iiko.github.io/front.api.doc/v6/ru/Reserves.html], пример можно посмотреть [здесь|https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/Restaurant/BanquetAndReserveView.xaml.cs].
