### ISSUE TITLE
Открытие личной смены сотрудника через FrontAPI

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#141]
Добрый день . 
Вопрос такой:
Мне нужно открыть (закрыть) личную смену сотрудника, у которого нет PIN кода.
Что нашел на данный момент:
Есть  PluginContext.Operations.AuthenticateByPin (ПИН) от возвращает ICredentials. По этим ICredentials я могу с помощью  PluginContext.Operations.OpenPersonalSession открыть личную смену.
НО! Ели у сотрудника нет ПИНкода, то через что мне получить ICredentials? или может есть какой-то другой метод открытия смены, желательно с использование Id сотрудника.
Также, через метод PluginContext.Operations.GetUserById я не могу получить ПИН сотрудника, что опять же вызывает вопрос как получить ПИНкод.
Спасибо.

**Comment by vcpp** [comment]
В текущей реализации плагинам доступна авторизация только по пин-коду.

Сотрудник — это реальный человек? Или служебная учётная запись для плагина?
Опишите, пожалуйста, сценарий работы. Подумаем, что предложить или как лучше доработать API под ваши потребности.

**Comment by DahurOuie** [comment]
Сотрудник - реальный человек. 
Сценарий работы: стыковка с терминалом учета явок. Сотрудник на терминале авторизовался, на фронт прилетела команда "открыта ли личная смена?"(это сейчас уже есть в апи) и если ответ "нет", то команда "открыть личную смену" , то же самое с закрытием смены.

**Comment by rgalk** [comment]
В задаче с внутренним номером RMS-51545 недавно выполнена доработка: в методы `OpenPersonalSession` и `ClosePersonalSession` добавлен необязательный аргумент — сотрудник, для которого предполагается открыть или закрыть личную смену. Если не указывать, то смена откроется/закроется у текущего пользователя, от имени которого действует сотрудник. Если указать, то смена откроется/закроется у указанного сотрудника.
Остается вызвать метод открытия/закрытия личной смены передав в него `ICredentials` сотрудника, у которого есть пин-код и необходимые права для открытия личной смены другому сотруднику, роль и сотрудника(`IUser`), личную смену которого требуется открыть/закрыть.

**Comment by ROSimulin** [comment]
День добрый можно уточнить RMS-51545 в какой версии будет реализован?
А то сейчас расхождение в документации  есть IUser user = null, в dll на 756 включая превью - нет
bool ClosePersonalSession(
	ICredentials credentials,
	IUser user = null
)

**Comment by rgalk** [comment]
> День добрый можно уточнить RMS-51545 в какой версии будет реализован?
> А то сейчас расхождение в документации есть IUser user = null, в dll на 756 включая превью - нет
> bool ClosePersonalSession(
> ICredentials credentials,
> IUser user = null
> )

Доработка уже выполнена в V7 и будет доступна в V7Preview6 после выпуска iikoRMS v7.6.6 (см. http://iiko.github.io/front.api.doc/versioning.html).

**Comment by vcpp** [comment]
Методы [`OpenPersonalSession`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_OpenPersonalSession.htm) и [`ClosePersonalSession`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_ClosePersonalSession.htm) обросли необязательными аргументами, позволяющими указать, какому именно пользователю требуется открыть или закрыть личную смену.

Подробнее [тут](https://iiko.github.io/front.api.doc/2021/11/01/manage-others-personal-sessions.html).
