### ISSUE TITLE
Авторизация сотрудника на фронте

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#142]
Добрый день. 
Вопрос такой:
Как я могу с помощью вызова функции АПИ авторизовать сотрудника (будто он входит по карте или ПИН коду) с помощью его Id или номеру карты (ПИН кода у сотрудника нет)?

**Comment by vcpp** [comment]
Можно имитировать прокатку карты, как это делают [эмуляторы](https://stackoverflow.com/questions/20482338/simulate-keyboard-input-in-c-sharp), клавиатурные картридеры, сканеры штрихкодов и т. п.

Вы хотите реализовать альтернативный способ авторизации (отпечатки пальцев и т. п.)?

**Comment by DahurOuie** [comment]
если через эмуляторы,то будут проблемы с механизмом считывателя на фронте. (это я уже проходил). Да и как раз нужно уйти от тог,чтобы у сотрудника была карта. Нужен именно метод , в который отправляется GUID сотрудника и он авторизуется на фронте, будто карту прокатал или пин ввел.

**Comment by vcpp** [comment]
> через эмуляторы,то будут проблемы с механизмом считывателя на фронте

А что за проблемы с механизмом считывателя? Мы сами при разработке и тестировании iikoFront помимо физических картридеров активно используем программные эмуляторы, вроде нормально работают.

> Вы хотите реализовать альтернативный способ авторизации (отпечатки пальцев и т. п.)?

И расскажите всё-таки, что вы хотите реализовать. Только возможность логиниться с экрана блокировки? Что насчёт диалогов подтверждения права?
В текущей реализации пин-код считается менее безопасным, чем карта, поэтому не все операции доступны по пин-коду. Кроме того, есть ещё вход по ключам-токенам. Важно понять, что вы хотите реализовать, чтобы правильно скрестить это с имеющейся логикой.

**Comment by DahurOuie** [comment]
Да, нужно для реализации стыковки с отпечатками.
Да, точно! Подтверждение права тоже неплохо было бы чтобы было. Грубо говоря, если пользователь авторизован, то делается подтверждение права, если нет, то логин. Если авторизован другой пользователь, то "Блокировка" и после логин. 
Можно подробнее про ключи-токены? что это и как используется?

**Comment by DahurOuie** [comment]
По поводу эмуляции: в айке по разному работает механизм считывателя в версиях 6 и 7. Разово все отрабатывает, но иногда случалось та,что слетали настройки. Поэтому эмуляция для работы в промышленных масштабах не подходит

**Comment by rgalk** [comment]
> Нужен именно метод , в который отправляется GUID сотрудника и он авторизуется на фронте, будто карту прокатал или пин ввел.
Такая доработка выполнена недавно в задаче с внутренним номером RMS-51545. 
В методы OpenPersonalSession и ClosePersonalSession добавлен необязательный аргумент — сотрудник, для которого предполагается открыть или закрыть личную смену. Если не указывать, то смена откроется/закроется у текущего пользователя, от имени которого действует сотрудник. Если указать, то смена откроется/закроется у указанного сотрудника.

**Comment by vcpp** [comment]
Сделаем в одной из следующих версий. Внутренний номер задачи: RMS-52996.
