### ISSUE TITLE
Получение списка мест приготовления

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#143]
Добрый день. 
Как можно получить список мест приготовления?
Метод GetRestaurantSections не подходит, поскольку возвращает отделы, а если приготовление происходит в другой группе, то место приготовления в результат не попадает.

**Comment by vcpp** [comment]
И правда, метод `GetRestaurantSections` возвращает отделения только для текущей группы.

Пожалуй, стоит добавить возможность получить список групп и затем для каждой группы получить список отделений. Спасибо за подсказку, подумаем, как лучше сделать, и сделаем.

**Comment by OlgaBelilovskaya** [comment]
Добрый день.
Сделано :).

В V7Preview4 теперь есть
[GetTerminalsGroups ](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetTerminalsGroups.htm)- список групп 
[GetRestaurantSectionsByTerminalsGroup ](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetRestaurantSectionsByTerminalsGroup.htm)- список отделений указанной группы
