### ISSUE TITLE
Получение списка контрагентов 

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#144]
Добрый день.
Как можно получить список именно контрагентов (поставщики)?
При вызове PluginContext.Operations.GetUsers() выдаётся список , содержащий как сотрудников ,так и контрагентов, но как именно вычленить из него отдельно контрагентов, а отдельно сотрудников, не понятно.

**Comment by letolika** [comment]
Добрый день.
На данный момент такой возможности нет. Заведена задача на доработку (RMS-51364).

**Comment by letolika** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/07/01/user-type.html)
