### ISSUE TITLE
Получение стола по умолчанию для группы

### ISSUE THREAD

**Issue by Nofuq** [iiko/front.api.sdk#146]
Добрый день, так и не нашли в API возможности получить стол по умолчанию, хотя в бэке это поле есть, подскажите есть ли такая возможность?

**Comment by vcpp** [comment]
Ай-яй, такая мелочь и не сделана. Спасибо за подсказку, добавим!

**Comment by OlgaBelilovskaya** [comment]
Добрый день. Стол [добавлен](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm)
Попадает в с V7Preview4.
