### ISSUE TITLE
Печать картинок в чеке

### ISSUE THREAD

**Issue by Nofuq** [iiko/front.api.sdk#147]
Подскажите есть ли возможность через расширение чека из iiko Front производить печать картинок?
И если есть то каким образом это сделать?

**Comment by DahurOuie** [comment]
Через функционал API никак.

**Comment by Nofuq** [comment]
Через подпись на Notifications.SubscribeOnCashChequePrinting и дальнейшим созданием CashCheque, с каким то определенным тэгом тоже не выйдет? Просто мы видели что в чеках есть шапка картинкой.

**Comment by DahurOuie** [comment]
https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Cheques_Attributes.htm
Тут описано всё разнообразие тэгов для формирования чека.
Каким-то образом отправить ESC последовательность (в теории через нее можно управлять принтером на относительно низком уровне) не получится , я все копья сломал в свое время

**Comment by letolika** [comment]
Добрый день.

Смотря какие картинки хотите печатать.
Если вы пользуетесь реальным фискальным регистратором, который сам формирует разметку фискального чека, то печать логотипа в шапке документа настраивается непосредственно в настройках ФР.
Если же разметка чека строится на iikoFront и печатается на рулонный принтер, то разметку чека можно переделать самостоятельно на любой вкус, используя [шаблоны чеков](https://ru.iiko.help/articles/#!iikooffice-7-2/topic-707). Можно даже не задействовать API.

> Также может быть напечатан логотип заведения на гостевом чеке, сервисном чеке и квитанции об оплате заказа. Для этого в принтер нужно загрузить изображение через настроечную утилиту, а затем настроить его печать в шаблоне чека. Печать логотипа настраивается с помощью специального тега **logo**, в нем нужно указать номер загруженного в принтер изображения.

Но использование тега `<logo>1</logo>` ограничено моделью и памятью принтера. В него можно загрузить единицы картинок, подразумевается обычно логотип заведения. Тег привязан к конкретному принтеру. Если принтеров несколько, например, нужно печатать логотип на пречеке, а принтер пречеков в каждом отделении свой. Поскольку шаблон один, важно, чтобы логотип, который нужно распечатать, был загружен во все принтеры пречеков с одним и тем же индексом, например, 1.

Из API печать заранее загруженного в принтер логотипа тоже возможна, но она не вынесена в качестве константы. Пример использования такой:
```
var doc = new Document
{
	Markup = new XElement(Tags.Doc, new XElement("logo", 1))
};
```
или
```
internal CashCheque OnCashRegisterChequePrinted(Guid orderId)
{
	return new CashCheque { BeforeCheque = new XElement("logo", 1) };
}
```

**Comment by CLTanuki** [comment]
@letolika , у нас есть потребность в печати графического кода.
Да, мы знаем, что можно печатать баркод. Но системный принтер не умеет этого делать, если настроен на арабскую вязь. Вот и намереваемся сделать картинкой.

**Comment by rengal** [comment]
1. Следует различать печать документов на фискальном регистраторе (ФР) и простом чековом принтере. В случае  виртуального ФР надо брать то устройство, которое настроено для печати квитанций для этого виртуального ФР - скорее всего, это простой чековый принтер.

1.1 В случае печати чека на ФР тег <logo> не поддерживается. Но возможно, печать логотипа можно настроить в шапке чека через сервисную утилиту ФР. Мне известно, что это точно работает для ФР Атол, для других моделей - нужно смотреть руководство по эксплуатации.

1.2. В случае печати на чековый принтер iiko либо генерирует и печатает весь текст картинкой (для этого нужно выбрать модель Windows-принтер), либо печатает через ESC-команды (это все остальные модели - Espon, Posiflex, Star и т.д.)

2. К сожалению, ни для одной модели принтера в шаблонах iiko нет тега, в который можно было бы записать готовый bitmap для печати его на принтере.

3. Для модели Windows-принтера не работают некоторые теги: <pagecut>, <logo>, <pulse>. Это связано с тем, что печать происходит картинкой через print spooler, и все эти команды, не предусмотрены явно (неявно, есть возможность отправить поток данных напрямую в принтер, но результат сильно зависит от производителя принтера). Также в текущей версии не поддерживается <barcode>, но тут нет принципиальной проблемы, эту команду можно добавить.

@CLTanuki , решит ли вашу задачу такой вариант - использование модели windows-принтер и доработкой со стороны iiko (поддержка тега <barcode>) ?

**Comment by CLTanuki** [comment]
@rengal
Да, очень решит. Даже можно пока в форме патча в агента.
Также прошу рассмотреть какие-либо теги для печати изображения в Windows принтер с целью немного развязать руки для всяких пограничных случаев.
Спасибо за внимание.

**Comment by Lap420** [comment]
@rengal Добрый день. Я хотел бы прояснить текущую ситуацию с печатью баркода. Мы имеем принтер Epson TM-T20iii. У нас есть задача печатать баркод из iiko. Этот баркод добавлен в шаблон квитанции об оплате в тэг <barcode>. 
Далее у нас есть два варианта печати:
1. Через Windows printer
2. Через Epson эмуляцию
Сейчас мы используем 1ый вариант, потому что Windows принтер корректно печатает арабский текст, который присутствует в нашем шаблоне.
Когда мы пробовали печатать квитанции об оплате через Epson эмуляцию, то английские символы печатались корректно, а вместо арабских символов печатались знаки вопроса. Дело оказалось в кодовой странице. 
Но это еще не всё. Арабский текст должен печататься справа налево, а английский слева направо. Сейчас весь текст печатается слева направо, из-за чего арабский текст получается некорректным. Прикладываю фото, на котором мы распечатали две одинаковые квитанции, только левый чек с Windows печати, а правый с Epson T88 эмуляцией. На фото видно, что текст выглядит по-разному. Правильно так, как на левом чеке с Windows эмуляцией.
Итого, чтобы решить нашу проблему с печатью баркода, нам надо научиться правильно печатать арабский текст через Epson эмуляцию. Можете ли Вы помочь нам в этом?
https://habrastorage.org/webt/ze/de/en/zedeenylatlip3cyancp_dvrubg.jpeg

**Comment by letolika** [comment]
На поддержку тега `<barcode>` в windows-принтере и поддержку тега `<image>` заведены 2 задачи (RMS-51365, RMS-51368).

**Comment by AlexSupport** [comment]
> 2\. Сейчас весь текст печатается слева направо, из-за чего арабский текст получается некорректным. Прикладываю фот

@Lap420 попробуйте добавить в начало этой строки специальный символ https://en.wikipedia.org/wiki/Left-to-right_mark
В шаблоне чека удобно сделать следующим образом:
1) в раздел @functions добавтьве новый метод
    public string lefttoright()
    {
        return ((Char)0x200E).ToString();
    }
2) затем этот метод добавляйте в начале строк (или первых ячеек таблицы), направление печати которых требуется инвертировать; 
например
<np />
@lefttoright():رقم تسجيل قيمة الضريبة المضافة test
<np />
или для таблицы из 4 колонок
    <ct font="f1">@lefttoright()السلعة @lefttoright()</ct>
    <ct font="f1">الكمية</ct>
    <ct font="f1" />
    <ct font="f1">@lefttoright()القيمة</ct>
    <ct font="f1">@Resources.NameColumnHeader</ct>
    <ct font="f1">@Resources.ProductAmount</ct>
    <ct font="f1" />
    <ct font="f1">@Resources.ResultSum</ct>

Также попробуйте Right-to-left mark 200F вместо 200E

**Comment by DahurOuie** [comment]
Почему нельзя сделать тэг для отправки ESC последовательностей на принтер? В этом случае можно использовать практически весь функционал устройства и не надо будет городить огород с тэгами

**Comment by rengal** [comment]
Пользователь может печатать на принтере Epson, а может, например, на принтере Star. Проблема в том, что ESC последовательность будет отправлена одна и та же (которая в шаблоне)

**Comment by rengal** [comment]
Задача с печатью <barcode> на Windows-принтере (RMS-51365) сделана и будет доступна в версии 7.4. Для более ранней версии 7.1.7014.0 отправлен патч.

**Comment by DahurOuie** [comment]
> Пользователь может печатать на принтере Epson, а может, например, на принтере Star. Проблема в том, что ESC последовательность будет отправлена одна и та же (которая в шаблоне)

Внезапно! Но почти у всех более-менее актуальных принтеров есть выбор режима команд. Плюс под узкоспециализированные задачи вопрос будет стоять в выборе железа. Ну и сама возможность использовать на 100% функционал даже 50% моделей принтеров лучше, чем добавление тегов, универсальных для 70% железок, поскольку так или иначе будут девайсы, которые будут не совместимы ни с чем.

**Comment by rengal** [comment]
В версии 7.5.2 добавлена новая модель принтера - ESC/POS Принтер, которая сочетает в себе возможности модели Epson T88 (преобразование тегов в ESC/POS команды) и печать текста графикой (позволяет использовать нестандартные шрифты, а не только тот, который зашит в кодовую страницу принтера)

**Comment by CLTanuki** [comment]
Благодарим покорнейше.
Будем посмотреть.

**Comment by rengal** [comment]
Начиная с версии 8.9 тег [image](https://iiko.github.io/front.api.sdk/v9/html/F_Resto_Front_Api_Data_Cheques_Tags_Image.htm) поддерживается на всех принтерах этикеток, а также EpsonT88, ESC/POS и Windows-принтере. Внутри тега необходимо передать монохромное изображение в виде base64 строки.
