### ISSUE TITLE
IEntity revision

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#148]
Добрый день.
Базовым интерфейсом для, кажется, всего в API является IEntity. У объектов в runtime есть поле Revision.
Вопрос: можно ли добавить поле Revision в интерфейс IEntity либо в любой другой публичный интерфейс, дабы не рефлексировать о смысле жизни с dynamic объектами?
![photo_2020-06-26_12-43-38](https://user-images.githubusercontent.com/5824716/85847445-0e48ca80-b7b0-11ea-99f6-afffeecaef44.jpg)

**Comment by CLTanuki** [comment]
P.S. Механизм ревизии в TRN, представляющий пользователю timestamp тоже очень классны=)

**Comment by vcpp** [comment]
> Базовым интерфейсом для, кажется, всего в API является IEntity. У объектов в runtime есть поле Revision.

[`IEntity`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Common_IEntity.htm) — общий базовый интерфейс для объектов, имеющих идентификатор (`Id`). Большинство объектов, реализующих данный интерфейс, не имеют ревизию.
[`IVersionedEntity`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Common_IVersionedEntity.htm) — частный случай для `IEntity`-объектов, имеющих ревизию (`Revision`). Есть два исключения — `IClient` и `IStreet`, у которых есть ревизия, но которые не реализуют указанный интерфейс. Думаю, от этих исключений можно будет избавиться.

> не рефлексировать о смысле жизни с dynamic объектами

Вот уж чего точно не стоит делать ;-)

> P.S. Механизм ревизии в TRN, представляющий пользователю timestamp тоже очень классный=)

Увы, время на компьютерах может скакать вперёд и назад из-за ntp-синхронизации, ручного переключения дат, смены часовых поясов и т. п.

**Comment by CLTanuki** [comment]
А как же время сервера и механизм синхронизации?
Взять его с сервера, UTC от него и вперёд? NTP в шкатулке может приехать с IIko,

**Comment by OlgaBelilovskaya** [comment]
> [`IVersionedEntity`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Common_IVersionedEntity.htm) — частный случай для `IEntity`-объектов, имеющих ревизию (`Revision`). Есть два исключения — `IClient` и `IStreet`, у которых есть ревизия, но которые не реализуют указанный интерфейс. Думаю, от этих исключений можно будет избавиться.

Избавились :). В V7Preview4 [IClient ](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Brd_IClient.htm)и [IStreet ](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Brd_IStreet.htm)стали реализовывать интерфейс [IVersionedEntity](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Common_IVersionedEntity.htm).

**Comment by CLTanuki** [comment]
Спасибо. Вот мы только не успеваем за вами=) Ещё на Preview3 перелезаем. Ели-ели успокаиваем потребителя при обновлении на тестовые версии=)

**Comment by OlgaBelilovskaya** [comment]
Да, это известный фактор :) Надеюсь, все пройдет спокойно, и и они будут морально готовы к Preview4 :).

**Comment by CLTanuki** [comment]
Уже готовы. Мы столько костылей городили в ожидании BaseOrderItemId у KitchenOrder...А теперь работает=)
