### ISSUE TITLE
Взаимодействие с экраном iikoFront через API

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#150]
Очень нужны методы взаимодействия с экраном iikoFront. 
Для чего нужно: 
- работать с открытым заказом. например считали сканером код, в открытом заказе происходят определенные действия. (вариант через выбор оплаты и т.д. не подходит)
- работа с фронтом с помощью клавиатуры (есть запросы)
- поиск заказа и его открытие по считыванию его кода.
и еще куча всяких применений.
Невозможность работы с открытым на фронте заказом очень ограничивает функционал!

**Comment by Azamatjon** [comment]
Похожий вопрос #118

**Comment by vcpp** [comment]
> работать с открытым заказом. например считали сканером код, в открытом заказе происходят определенные действия.

Сделали, появится в V7Preview4.

> работа с фронтом с помощью клавиатуры (есть запросы)

Запросы действительно есть, со всех сторон. Внутреннее обсуждение в RMS-51350.

> поиск заказа и его открытие по считыванию его кода

Нужны подробности, для чего это.
Есть режим «[Карта на входе](https://ru.iiko.help/articles/how-to-iiko/karta-na-vhode)», где покупатели снабжены метками (это могут быть сотрудники офисного центра в столовой или посетители аквапарка). Хотите что-то подобное?

> и еще куча всяких применений.

Универсальный доступ ко всем контролам и функциям всех экранов сделать не получится, поэтому нужна конкретика, где, чего и для чего не хватает.

**Comment by DahurOuie** [comment]
"поиск заказа и его открытие по считыванию его кода" 
Для чего надо: клиент через сайт или приложение делает резерв или банкет, приходит в заведение и,чтобы кассир не искал его резерв/банкет, он просто сканирует код и этот резерв открывается на экране

**Comment by letolica** [comment]
Готово. [Экран редактирования заказа позволяет вносить изменения по инициативе плагина](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html).

**Comment by CLTanuki** [comment]
Спасибо!
Уже трогаем=)
