### ISSUE TITLE
MyPaymentPlugin: I can not connect to my server to open operation session. But I

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#151]
Здравствуйте,
Я недавно установил плагин типов оплат, при запуске вижу следующее сообщение:
![image](https://user-images.githubusercontent.com/22041710/86388308-630baa00-bcb6-11ea-9ac8-948d1eb0b99b.png)

Как исправить?
Версия iiko: 7.2.7014.0

**Comment by vcpp** [comment]
Здесь говорим об iikoFront API, а вам нужно обратиться к разработчику плагина `ExternalPaymentPlugin`.

.. хотя в #74 вы же писали:

> я разрабатываю плагин ExternalPaymentPlugin

Если это ваш плагин, почитайте код, где вызывается метод `AddNotificationMessage`.
