### ISSUE TITLE
Проверка ПЕРЕД закрытие смены с недачей ей это сделать

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#152]
Всем привет! 
Вопрос такой: насколько возможно сделать проверку ПЕРЕД закрытием смены и , если что не так, не дать ей закрыться?

**Comment by ierof** [comment]
Попробуйте через [Расширение функционала фискального регистратора](https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html) — BeforeZReport
