### ISSUE TITLE
Плагины для iikoOffice

### ISSUE THREAD

**Issue by DahurOuie** [iiko/front.api.sdk#153]
Всем привет!
Наблюдаю,что в дистрибах есть плагины не только для фронта ,но и для офиса. Будет ли какое-то описание как их делать или тут самому придётся разбираться?

**Comment by vcpp** [comment]
В iikoOffice нет публичного API, соответственно, нет и возможности писать сторонние плагины.

Те плагины, что вы видите в дистрибутиве, выполняются непосредственно в ядре приложения, это нерасширяемый подход, там любое неосторожное действие может всё поломать, поэтому плагины пишутся самими разработчиками iikoOffice. Кроме того, внутренности ядра постоянно меняются, поэтому плагины меняются и пересобираются вместе с приложением. Теоретически возможно, не будучи разработчиком iikoOffice, самостоятельно разобраться и написать плагин, но высокая связность, отсутствие API, обратной совместимости и документации делают это неблагодарным занятием.
