### ISSUE TITLE
Front.Api и sizePrices

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#155]
Добрый день.
В API TRN есть очень удобная штука, называемая `sizePrices`.
Вопрос: как узнать изменение цены от размера через `Resto.Front.Api`, не создавая заказ? А то очень нетривиально получается.
Мы знаем кучу методов, которые отдают шкалу размеров и сами размеры. Но кто может дать изменение цены?

**Comment by letolika** [comment]
Предлагаю воспользоваться методом [GetPrice](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetPrice.htm)

**Comment by CLTanuki** [comment]
Спасибо. Закрыто.
