### ISSUE TITLE
Задержки c выполнением HTTP запросов

### ISSUE THREAD

**Issue by anytoany** [iiko/front.api.sdk#156]
Добрый день. При разработке плагина столкнулись с необычной проблемой возможно она как то связана с инфраструктурой iikoFront или кто то уже сталкивался с похожей проблемой.

Версия API V6. Iiko front 7.1 
Платежный плагин реализует внешний тип оплаты. В методе OnPaymentAddeed плагин выполняет Http запрос вот такой простой код
![image](https://user-images.githubusercontent.com/59863155/88176863-98aa1000-cc30-11ea-8ea4-a8a091360f03.png)
И выполнение тут зависает на секунд 10-20 по разному всегда. Проблем с сетью на компьютере нет, по логам сервера видно что запрос приходит примерно через 10 секунд после вызова SendAsync и сервер отвечает меньше чем за секунду.

Не накладывает ли iiko какие то ограничения на HttpClient, например количество одновременных подключений на хост и т.д., возможно устанавливает какие то свойства ?

**Comment by ierof** [comment]
Нет, каких-то ограничений iiko не накладывает. Рекомендуем попрофилировать, что именно "под капотом" происходит, на какие инфраструктурные методы уходит время
