### ISSUE TITLE
Штрих коды

### ISSUE THREAD

**Issue by mgdmiller** [iiko/front.api.sdk#157]
Коллеги, приветствую.

В процессе разработки возникла необходимость загружать штрихкоды товаров и что то не могу найти как это сделать. Как получить штрих коды товаров?

**Comment by CLTanuki** [comment]
Насколько мне известно, на текущий момент такой возможности нет.
Однако, по умолчанию артикулы генерируются из поля "артикул" товара.
https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_Number.htm

**Comment by ROSimulin** [comment]
Из не апи методов
http://192.168.1.30:8080/resto/service/import/importCsv.jsp  - там штрихкоды номенклатуры

**Comment by mgdmiller** [comment]
Немного не то. Необходимо именно апи форнта.

**Comment by rgalk** [comment]
> В процессе разработки возникла необходимость загружать штрихкоды товаров и что то не могу найти как это сделать. Как получить штрих коды товаров?

@mgdmiller, можете рассказать что планируется делать с штрих-кодами товаров?

**Comment by mgdmiller** [comment]
> > В процессе разработки возникла необходимость загружать штрихкоды товаров и что то не могу найти как это сделать. Как получить штрих коды товаров?
> 
> @mgdmiller, можете рассказать что планируется делать с штрих-кодами товаров?

Периодически возникает необходимость использовать штрих коды при обмене номенклатурой.

**Comment by rgalk** [comment]
> Периодически возникает необходимость использовать штрих коды при обмене номенклатурой.

А кто и с кем обменивается номенклатурой? И почему в этом процессе необходим штрихкод?
Опишите подробнее, чтобы мы со своей стороны могли понять цель использования и принять соответствующее решение.

**Comment by CLTanuki** [comment]
@rgalk , вот пример решения:
http://open-s.info/beopensoft/beopen-kiosk/
Штрих-код нужен для того, чтобы гость, например, торгового центра (iikoME), мог на выходе через ресторан оплатить свой заказ из ТЦ. Или для того, чтобы в отдельностоящих терминалах без кассира можно было купить. Или ещё с десяток случаев.
Сейчас пользуемся артикулами, что работает не всегда.

**Comment by rgalk** [comment]
Спасибо, @CLTanuki.
Завел задачу с внутренним номером RMS-52308.

>Или ещё с десяток случаев.

В любом случае, лучше привести описание сценариев использования штрихкодов. 
Можно вынести поле штрихкода в интерфейс продукта, но это вызовет необходимость каждый раз получать список продуктов, затем фильтровать его или же организовывать кэширование продуктов и их штрихкодов, что повлечет необходимость синхронизировать сущности и т.д. 
Быть может и не нужно выносить поле штрихкода, а вместо этого добавить метод поиска товара по штрихкоду.
Каждый сценарий даст аргументы в пользу того или иного решения.

**Comment by CLTanuki** [comment]
> В любом случае, лучше привести описание сценариев использования штрихкодов.
Метод, безусловно, будет тоже очень полезен, так как встроенные методы лучше оптимизированы и работают быстрее.
Но у нашей команды болят только внешние источники, так что нужно чтение поля. Да и iiko сама ищет по артикулам неплохо при использовании сканера.

**Comment by mgdmiller** [comment]
@rgalk Благодарим за создание задачи.
Штрих коды необходимы когда требуется подружить стороннюю систему, на пример когда заказчик хочет выгружать товары в смарт кассу. Либо же был кейс когда заказчику требовалось печатать штрих на слипах (точно кейс уже не помню но не смогли это реализовать).

**Comment by zed220** [comment]
Здравствуйте!

В API V7 добавили возможность работы со штрихкодами. Об этом можно почитать здесь:
http://iiko.github.io/front.api.doc/2021/12/07/product-barcodes.html

Спасибо за ожидание!
