### ISSUE TITLE
Добавление кнопки в заказ

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#158]
Мы используем `Resto.Front.Api.V5.dll`.  Нам необходимо, чтобы официант мог вводить номер карты вручную или с использованием 2Д сканнера. На данном этапе мы реализовали эту фунцкиональность через внешний тип оплаты. Т.е. для сканировании карты неободимо войти в кассу а затем `Безналичный расчет->Наш плагин`. 
 Однако нам необнодимо что бы кнопка сканирования/оплаты была вне окна оплаты. Так как не всегда у официанта бывает доступ к оплате заказа. Поэтому необходимо  чтобы эта кнопка была либо в окне конкретного заказа,
![WhatsApp Image 2020-07-29 at 16 59 42 (1)](https://user-images.githubusercontent.com/51437851/89728799-1481c600-da41-11ea-860e-964703edffcd.jpeg)

либо в окне, где отображаются все заказы (т.е. для каждого заказа своя собственная кнопка).

![WhatsApp Image 2020-07-29 at 16 59 42](https://user-images.githubusercontent.com/51437851/89728819-282d2c80-da41-11ea-9c46-cfe00d888719.jpeg)
1. Скажите пожалуйста имеется ли возможножность добавления кнопки в заказ? 
2. Как понять для какого заказа была нажата эта кнопка?

**Comment by ierof** [comment]
В текущей версии iiko кнопки можно добавлять только в закрытый заказ. См. [Экран закрытого заказа](http://iiko.github.io/front.api.doc/v6/ru/ActionOnClosedOrderView.html)
В бэклоге есть задача (внутренний номер RMS-41626) на добавление кнопки на экраны открытого заказа, но прогнозов по срокам по этой фиче нет.

**Comment by ierof** [comment]
https://github.com/iiko/front.api.sdk/issues/158

**Comment by ierof** [comment]
Дубль-запрос  https://github.com/iiko/front.api.sdk/issues/150

**Comment by CLTanuki** [comment]
Голосуем ЗА

**Comment by letolica** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/11/11/add-button-to-order-edit-screen.html)

**Comment by CLTanuki** [comment]
> [Готово.](https://iiko.github.io/front.api.doc/2020/11/11/add-button-to-order-edit-screen.html)

Аве всем в этом чатике!
