### ISSUE TITLE
Работа со стоп листом

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#159]
День добрый, нужен метод работы со стоп листом
Нужно
1)получить стоп лист в разрезе точки
2)изменить стоп лист в разрезе точки

Если с 1 можно через апи доставки, транспорта (апи фронта не нашёл)
То со вторым вообще не нашёл ни одного инструмента, подскажите какие есть варианты?

**Comment by letolica** [comment]
Добрый день.
> 1)получить стоп лист в разрезе точки

Получить стоп-лист на чтение можно, [есть пример в нашем SDK](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/DiagnosticMessagesTester/StopListChangeNotifier.cs).
Вот доступные для работы методы:
- [GetProductsRemainingAmounts](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetProductsRemainingAmounts.htm)
- [CheckProductsSellingRestrictions](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_CheckProductsSellingRestrictions.htm)
- [IsProductSellingRestricted](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_IsProductSellingRestricted.htm)
- [ProductsRemainingAmountsChanged](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_INotificationService_ProductsRemainingAmountsChanged.htm)

> 2)изменить стоп лист в разрезе точки

Возможности изменять стоп-лист к сожалению пока нет. Расскажите, каких методов не хватает и почему недостаточно функционала на UI iikoFront?

**Comment by ROSimulin** [comment]
Задача - кассир/официант должен видеть остатки по блюдам на кассе
1) блюда имеют ттк
2) надо написать плагин, который 
2.1) собирает информацию по остаткам по всем товарам на указанных складах ( апи сервера)
2.2) исходя из отрицательных остатков на товары пометить блюда , в ттк которых данные товары входят - переместить в стоп лист (ттк  и номенклатуру также возьму по апи сервера)
2.3)Если на товар был сделан приход = убрать стоп лист с блюд
2.4) ттк простые ( пару пф, в концепции клиента это рабочий сценарий, взаимозаменяемости у них нет)

3) исходя из выше сказанного нет апи изменять стоп-лист, Сценарий рассказал, надеюсь поможет

**Comment by letolica** [comment]
Завела задачу как feature request. Но не могу ничего сказать по поводу реализации и сроков. Внутренний номер задачи RMS-52142.

**Comment by CyCJIeHok** [comment]
Не появился такой функционал? Вообще как-то можно автоматищировать установку стоп листов?

**Comment by vcpp** [comment]
> надо написать плагин, который
2.1) собирает информацию по остаткам по всем товарам на указанных складах ( апи сервера)
2.2) исходя из отрицательных остатков на товары пометить блюда , в ттк которых данные товары входят - переместить в стоп лист (ттк и номенклатуру также возьму по апи сервера)
2.3)Если на товар был сделан приход = убрать стоп лист с блюд
2.4) ттк простые ( пару пф, в концепции клиента это рабочий сценарий, взаимозаменяемости у них нет)

Казалось бы, при чём тут iikoFront API, у вас всё кроме одного пункта построено на iikoServer API, напрашивается добавить туда возможность редактирования стоп-листов, и вы получите чисто серверное решение.

А вообще запрет продавать блюда, для которых закончились ингредиенты, настолько логичный, что, возможно, стоило было бы реализовать его штатно в iikoRms, а как кастомизацию.
