### ISSUE TITLE
Различие в типах ItemCategory в версиях 6.2 и 6.3 для ФР

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#16]
Добрый день
BillTask : CashRegisterTask
     class ChequeSale
            ItemCategory
В версии SDK 6.2 ItemCategory для чека была enum
```c#
public enum ChequeItemCategory
    {
        Goods = 0,
        ExcisableGoods = 1,
        Work = 2,
        Service = 3,
        Advance = 4,
        Mixed = 5,
        Other = 6
}
```

В версии SDK 6.3 ItemCategory стал String, какие значения теперь подаются в ItemCategory?

**Comment by ierof** [comment]
@GulnaraBikbova

**Comment by igorpooh1978** [comment]
Добрый день,

Будет ли какой-либо ответ ?

**Comment by GulnaraBikbova** [comment]
Добрый день, ItemCategory теперь просто строка - код признака предмета расчета.

В российском законодательстве появляются все новые признаки предмета расчета.  Например, для ФФД 1.1 ItemCategory равен от 1 до 19. 
Но это не всегда так, за набор кодов с версии 6.3 отвечает справочник "Признак расчета", его можно увидеть в BackOffice. Справочник можно редактировать, а также добавлять новые признаки расчета. 
В карточке блюда можно указать конкретный элемент справочника. От этого будет зависеть какой код признака предмета расчета придет в ChequeSale.ItemCategory.
