### ISSUE TITLE
System.InvalidOperationException при попытке отмены пречека

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#163]
Здравствуйте.
При открытии заказа нужно заново пересчитать и добавить скидку.
В статусе Bill редактировать заказ нельзя, поэтому перевожу в статус New с помощью
`operationService.CancelBill(credentials, order);`
внутри метода - подписчика события `SubscribeOnNavigatingToPaymentScreen`

Получаю следующую ошибку:

`Method “CancelBill” cannot be called using operation service of notification event handler, use default operation service.`

Stacktrace:
`   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationService.CancelBill(ICredentials credentials, IOrder order)
   at Resto.Front.Api.SamplePlugin.Extenders.PluginWallzyExtender.OpenWollzyWindow(IOrder order, IPointOfSale arg2, IOperationService operationService, IViewManager arg4) in C:\Users\thedc\Desktop\iikomodule\Extenders\PluginWallzyExtender.cs:line 312`

**Comment by CLTanuki** [comment]
В ошибке весьма явно предлагается использовать PluginContext.OperationService, вместо operationService-а, который прилетел в Notification и такими правами не обладает.
Должно помочь.

**Comment by theDCM** [comment]
Спасибо, сейчас попробую

**Comment by theDCM** [comment]
Не помогло

**Comment by letolica** [comment]
Добрый день.
К сожалению, отменить пречек открытого на данный момент в iikoFront заказа пока нельзя. Но данная задача уже в работе. Внутренний номер RMS-51383.

**Comment by letolica** [comment]
#150 #98

**Comment by letolica** [comment]
Готово. [Экран редактирования заказа позволяет вносить изменения по инициативе плагина](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html).
