### ISSUE TITLE
Открыть кассовую смену. Консультация

### ISSUE THREAD

**Issue by novg** [iiko/front.api.sdk#165]
Добрый день.
SDK - Resto.Front.Api.V5

Скажите, пожалуйста, как из плагина открыть и закрыть кассовую смену.

**Comment by novg** [comment]
[Здесь](https://github.com/iiko/front.api.sdk/issues/121) открытие кассовой смены обсуждается?
Это оно?

**Comment by letolika** [comment]
Добрый день.
В Api.V5 нет такой возможности. Есть в Api.v6: [OpenCafeSession](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_OpenCafeSession.htm), [CloseCafeSession](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_CloseCafeSession.htm). Но эти методы имеют много ограничений. Например, смену можно открыть/закрыть только на виртуальном ФР, который является ФР-ом по умолчанию, на главной кассе.
В Api.V5 есть только подписка на уведомления об открытии/закрытии кассовой смены, например, из UI iikoFront: [SubscribeOnCafeSessionOpening](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_INotificationService_SubscribeOnCafeSessionOpening.htm), [SubscribeOnCafeSessionClosing](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_INotificationService_SubscribeOnCafeSessionClosing.htm). Подробнее об уведомлениях в разделе ["Открытие и закрытие кассовой смены в iikoFront"](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html).

**Comment by novg** [comment]
Спасибо!
