### ISSUE TITLE
iikoFrpnt api - передача цены 

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#166]
Можно ли реализовать чтобы в заказ добавлялось не только блюдо, но и была возможность передавать цену к нему?
Аналог функции в Транспорте где можно сделать настройку доверять цене из внешнего источника. 

Для чего: Есть свое ПО КЦ и есть случаи когда Заказ  в КЦ сегодня по одной цене. а Завтра на кассе будет на это блюдо другая. И необходимо пробить заказ по старой цене. Функция передачи со своей ценой решала бы эту проблему.

**Comment by CLTanuki** [comment]
Можно создать блюдо со свободной ценой.

**Comment by Kamaew** [comment]
Да но, кассиру не желательно дать с интерфейса возможность менять цену

**Comment by letolika** [comment]
Например, метод[`AddOrderProductItem`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm), аргумент `predefinedPrice`.

**Comment by Kamaew** [comment]
@letolika  Спасибо!
