### ISSUE TITLE
ApiServer - работа с Актами списания

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#167]
В Документации по api серверу не нашел возможность работы с Актами списания. Будет ли до деланно api ? и когда ?

**Comment by letolika** [comment]
Добрый день.
Данная площадка задумана для обсуждения возникших вопросов по iikoFront API. К сожалению, здесь нет разработчиков других команд. Попробуйте направить свой вопрос [согласно статье](https://ru.iiko.help/articles/#!api-documentations/getting-started) на api@iiko.ru.
