### ISSUE TITLE
Не работает автопечать этикетки блюда при переводе статуса блюда в Served

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#168]
Доброго времени суток! При переводе статуса блюда на кухонном экране фронта этикетка блюда печатается, а при вызове PluginContext.Operations.ChangeKitchenOrderItemsProcessingStatus - нет. Используем API v7preview3 v7.4.2
Начало истории: 
https://github.com/iiko/front.api.sdk/issues/134

**Comment by CLTanuki** [comment]
Коллеги, спасите, помогите, пожалуйста=)

**Comment by letolika** [comment]
Добрый день.
К сожалению, при переводе статусов кухонных блюд чек и стикер окончания приготовления не печатаются. Завела задачу на доработку RMS-51653.

**Comment by dsshubin** [comment]
Доработка RMS-51653 сделана в версии 7.7.1.

**Comment by CLTanuki** [comment]
Спасибо. Будем ждать.
