### ISSUE TITLE
Запуск iikoOffice с параметрами для авторизации

### ISSUE THREAD

**Issue by kolur20** [iiko/front.api.sdk#169]
Коллеги, добрый день.
Собственно вопрос: можно ли при запуске приложения iikoOffice передавать ему в качестве параметров нужный сервер (домен:порт/инстанс или другого вида) и логин с паролем?
Смысл в том, что бы миновать окно логирования и выбор сервера. 
Сам офис вроде бы как принимает аргументы и парсит их по регулярному выражению "^/([\\w]+)=(\"?)(.+)\\2$", но понять что именно он ждет в аргументах не удается.

**Comment by letolika** [comment]
Добрый день.
Данная площадка задумана для обсуждения возникших вопросов по iikoFront API. К сожалению, здесь нет разработчиков других команд. Попробуйте направить свой вопрос в техническую поддержку iiko.
