### ISSUE TITLE
Настройка iikoFront для работы внесения изъятия с внешнего плагина для ФР

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#17]
Добрый день,

Есть 2 метода в примере для внесения и изъятия ДС из денежного ящика
DoPayIn и DoPayOut, я поставил на данные два метода брейкпойнты, однако при выполнении операций в iikoFront Внесение/Изъятие, фактически на эти методы данные не приходят. Как сконфигурировать iikoOffice, для того, чтобы эти два метода работали ? 

```c#
public CashRegisterResult DoPayIn(decimal sum, Guid cashierId)
        {        
            PluginContext.Log.InfoFormat("Device: '{0} ({1})'. PayIn.", DeviceName, deviceId);
            return GetCashRegisterData();
        }

        public CashRegisterResult DoPayOut(decimal sum, Guid cashierId)
        {
            PluginContext.Log.InfoFormat("Device: '{0} ({1})'. PayOut.", DeviceName, deviceId);
            return GetCashRegisterData();
        }
```
Настройки iikoOffice
![2019-03-27_14-41-30](https://user-images.githubusercontent.com/47010778/55073548-0ecf4e80-509f-11e9-8fa9-58df1429d614.png)
![2019-03-27_14-40-01](https://user-images.githubusercontent.com/47010778/55073549-0ecf4e80-509f-11e9-8fbe-fece362661c6.png)

**Comment by ierof** [comment]
Это у нас не фискальные внесения и изъятия, а просто бухгалтерские перемещения => нет команды фискальному регистратору на их печать. 
Если вам нужны фискальные внесения и изъятия, указывайте пустой Шеф-счёт. См. документацию iiko про [Типы внесений и изъятий](https://ru.iiko.help/articles/iikooffice-5-4/topic-102) п.4

**Comment by igorpooh1978** [comment]
Спасибо Вам большое за разъяснение
