### ISSUE TITLE
Выбрасывается исключение типа System.TypeLoadException при создании доставки

### ISSUE THREAD

**Issue by nagorniy-ad** [iiko/front.api.sdk#171]
Здравствуйте!
При создании доставки во время вызова метода `PluginContext.Operations.SubmitChanges` выбрасывается исключение:

> System.TypeLoadException: Method 'get_LastDefaultTerminalDeliveryDurationInMinutes' in type 'Resto.Front.Api.V6.Data.Orders.DeliveryOrder' from assembly 'Resto.Front.Api, Version=7.1.6025.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Исполнение кода прерывается, но доставка в системе создается. Используется Resto.Front.Api.V6 версии 7.0.6022.0.
С чем может быть связано данное исключение и как можно его избежать?

**Comment by letolika** [comment]
Добрый день.
К сожалению, в промежутке версий [7.1.3, 7.2.3) сломана обратная совместимость для плагинов, работающих с доставкой: версия API.V6 зарелизилась в 7.0 с полем `LastDefaultTerminalDeliveryDurationInMinutes` типа `Nullable<long>`, а начиная с 7.1.3 то же самое поле стало с типом `Nullable<TimeSpan>`. Мы исправили этот баг в 7.2.3.
Варианты решения:
- Обновить iikoRms на исправленную и более актуальную версию (>= 7.2.3), оставив плагин на Api.V6;
- Перевести плагин на [API.V7Preview1](https://iiko.github.io/front.api.doc/2020/01/15/v7preview1-release.html), оставшись на iikoRms версии 7.1.6025.0;
