### ISSUE TITLE
new ReceiptSlip

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#172]
Добрый день

Есть ли описание формирования слипов через ReceiptSlip?

**Comment by vcpp** [comment]
Язык описания разметки [тут](https://ru.iiko.help/articles/iikooffice-7-4/topic-5).
Для удобства есть наборы констант с именами [тэгов](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Cheques_Tags.htm) и их [атрибутов](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Cheques_Attributes.htm).
Пример использования [тут](https://github.com/iiko/front.api.sdk/blob/04ab80673e5af9e83a9d0920455cfa881f007195/sample/v6/Resto.Front.Api.SamplePlugin/BillChequeExtender.cs).
