### ISSUE TITLE
Another payment proccessor was already registered

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#174]
Добрый день мы имплементировали `внешний тип оплаты` следующим образом
```
 public sealed class Plugin : MarshalByRefObject, IFrontPlugin
 {
      private readonly Stack<IDisposable> _subscriptions = new Stack<IDisposable>();

       public Plugin()
       {
            MyPayment payment = new MyPayment();
            PluginContext.Operations.RegisterPaymentSystem(payment);
            _subscriptions.Push(payment );            
       }
}

```

```
public class MyPayment : MarshalByRefObject, IExternalPaymentProcessor, IDisposable
{
        public const string PaymentName = "MyPayment";
        public string PaymentSystemKey => "MyPayment key";
        public string PaymentSystemName => PaymentName;
        . . . 
}
```
`Внешний тип оплаты` настраивался через `Чейн` и реплицировался на все рестораны.
Все нормально работало, но не знаю почему сегодня получил следующую ошибку . 
```
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> Resto.Front.Api.V5.Exceptions.PaymentSystemRegistrationException: Another payment proccessor with key 'MyPayment key' was already registered.
```
Хочу отметить, что после перезагрузки iikoFront ошибка исчезла

Скажите пожалуйста с чем это связано?

<details>
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> Resto.Front.Api.V5.Exceptions.PaymentSystemRegistrationException: Another payment proccessor with key 'MyPayment key' was already registered.

Server stack trace: 
   в Resto.Front.Api.ApiExtensionsService.RegisterPaymentProcessor(String key, IPaymentProcessorWrapper processorWrapper, Func`1 failCallback) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\ApiExtensionsService.cs:строка 44
   в Resto.Front.Api.V5.OperationService.RegisterPaymentSystem(IExternalPaymentProcessor paymentProcessor) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\OperationService.cs:строка 708
   в Resto.Front.Api.V5.OperationService.Resto.Front.Api.V5.IOperationService.RegisterPaymentSystem(IExternalPaymentProcessor paymentProcessor) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\Operations.g.cs:строка 2450
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.V5.IOperationService.RegisterPaymentSystem(IExternalPaymentProcessor paymentProcessor)
   в ikko.Plugin..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   в System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance(Type type, Boolean nonPublic)
   в System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   в System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   в Resto.Front.Api.Host.PluginRunner.TryCreatePluginInstance(String assemblyPath, String className) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api.Host\PluginRunner.cs:строка 149

**Comment by vcpp** [comment]
Скорее всего, ваш плагин, запустившись вместе с iikoFront, зарегистрировал свою платёжную систему путём вызова `RegisterPaymentSystem`, после чего упал и был перезапущен. При повторном запуске плагин снова попытался зарегистрировать платёжную систему и споткнулся о свою же предыдущую регистрацию.

Начиная с V6 доступно [автоматическое освобождение ресурсов](https://iiko.github.io/front.api.doc/2018/07/18/cleanup-disconnected-plugin-resources.html) при падении плагина. Ваш плагин использует V5, там этой фичи ещё не было, хотя [автоперезапуск при падении](https://iiko.github.io/front.api.doc/2018/08/20/restart-crashed-plugins.html) появился, поэтому при перезапуске плагина зарегистрированный им экземпляр платёжной системы не был удалён и мешал зарегистрировать новый экземпляр с тем же ключом.

Посмотрите по логам, что предшествовало описанной вами ошибке, там должна быть причина падения плагина. Надо устранить эту причину, чтобы плагин не падал, тогда не будет возникать необходимость в перезапуске, соответственно, не будет и описанной вами ошибки.

Пока вы на V5, можно ещё попытаться вручную освобождать ресурсы перед падением (в вашем случае — `_subscriptions`).
А вообще имеет смысл переходить на V6, там есть автоматическое освобождение ресурсов при падении, и эта версия поддерживается iikoFront 7.0 и новее.
