### ISSUE TITLE
Запрет предоплат платежному плагину.

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#175]
Добрый вечер,

Подскажите есть ли какие-либо средства как отловить, что будет выполняться предоплатный платеж ? До момента нажатия кнопку Внести предоплату ? Или в момент нажатия на эту кнопку ?
Я вот про это окно
![image](https://user-images.githubusercontent.com/47010778/95389297-49ed4780-08fc-11eb-9869-d9eef1259fac.png)
Спасибо

**Comment by letolica** [comment]
Добрый день.
Для запрета предоплаты плагинным типом нужно в методе сбора данных `CollectData` выбросить `PaymentActionCancelledException` или `PaymentActionFailedException`. Первый эксепшн просто не добавляет предоплату, второй тоже не добавляет и показывает окно с текстом ошибки. Метод вызовется в момент нажатия на кнопку "Внести предоплату". Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html).

**Comment by igorpooh1978** [comment]
Спасибо большое за ответ, но мой вопрос был несколько иным.
Как мне понять, что была попытка оплаты из окна предоплаты ?
IPayment в  IOrder присылает 0. Как поймать остальные предоплаты понятно, но вот именно как понять что моя ПС попала в предоплаты ?

**Comment by letolica** [comment]
Если нужно запрещать проводить предоплату плагинным типом оплаты (неважно, из UI iikoFront проводится предоплата, или из плагина вызывается метод [`ProcessPrepay`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_ProcessPrepay.htm)), то можно при добавлении оплаты прописать ей некий уникальный `Id`. 

Если **оплата добавляется через UI**, `Id` можно прописать в методе [`CollectData`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_CollectData.htm)
```
var customData = new PaymentAdditionalData
{ PayId = Guid.NewGuid() };
context.SetCustomData(customData);
```
Если **оплата добавляется через плагин**, то можно передать этот уникальный `Id` в `additionalData`
```
var additionalData = new ExternalPaymentItemAdditionalData
{ CustomData = Serializer.Serialize(new PaymentAdditionalData { SilentPay = true, PayId = Guid.NewGuid() }) };
```
который впоследствии передается в [`AddExternalPaymentItem`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddExternalPaymentItem.htm).

**Далее** в методе [`Pay`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_Pay.htm) или [`PaySilently`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_PaySilently.htm) на входе вы достаете контекст оплаты, достаете из него тот самый уникальный идентификатор, который задавали при добавлении оплаты, и проверяете в [списке оплат заказа](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrder_Payments.htm) наличие оплаты с таким же `Id`. Если оплаты нет, то проводимая оплата — предоплата, кидаете `PaymentActionCancelledException` или `PaymentActionFailedException`.

```
var data = context.GetCustomData<PaymentAdditionalData>();

var existingPayment = order.Payments.SingleOrDefault(p => Serializer.Deserialize<PaymentAdditionalData>(((ExternalPaymentItemAdditionalData)p.AdditionalData).CustomData).PayId == data.PayId);
if (existingPayment == null) // prepay
    throw new PaymentActionCancelledException();
```

Но то, что в методы `Pay` или `PaySilently` приходит заказ, у которого в списке оплат нет текущей проводимой предоплаты, является деталью реализации, и в любой момент поведение может измениться. Поэтому не советуем использовать такую проверку. В будущем постараемся расширить информацию об оплатах в `Pay` и `PaySilently`.

**Comment by letolica** [comment]
Добавим больше информации в задачке RMS-51730.

**Comment by igorpooh1978** [comment]
Спасибо за пояснение

**Comment by letolica** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/12/01/more-info-about-payment-processing.html)
