### ISSUE TITLE
Плагин внешней оплаты не корректно отображается в Возврате заказов закрытых смен.

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#176]
Добрый вечер
Столкнулись со следующей проблемой
Разрабатываем платежный плагин (безналичная оплата) (Cloudhook)
При выборе нашей платежной системы при оплате заказа все нормально. и при нажатии кнопки оплатить заказ оплачивается через нашу систему
![image](https://user-images.githubusercontent.com/47010778/96348663-23c16780-10b3-11eb-9954-f0d253a17b6b.png)
Если сделать возврат ДС через возврат или удаление в закрытых заказах открытой смены, то операция проходит нормально - оплата проходит через наш плагин
![image](https://user-images.githubusercontent.com/47010778/96348715-73a02e80-10b3-11eb-9b19-936b48c1e6ce.png)
В случае если мы делаем возврат ДС из закрытой смены, то тип оплаты стоит как "Наличные", а не наша ПС
![image](https://user-images.githubusercontent.com/47010778/96348757-beba4180-10b3-11eb-86bd-87fa8a1fe77b.png)
Хотя в офисе данная оплата зафиксирована как Cloudhook
![image](https://user-images.githubusercontent.com/47010778/96348777-e6a9a500-10b3-11eb-9877-400fa9ca8f45.png)
Подскажите, почему возникает такая ситуация?

Версия iiko 7.4.6020
API V6

**Comment by letolica** [comment]
Добрый день.
Поддерживает ли ваш плагин возможность возврата товаров закрытых кассовых смен?
[Цитата из документации](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html):
> Метод ReturnPaymentWithoutOrder() вызывается, когда происходит возврат товаров внешним типом оплаты. Возможность возвращать оплату за товары без оплаченных ранее заказов внешними типами появилась начиная с версии iiko 6.2.2. Чтобы на UI возврата товаров появилась возможность выбрать внешний тип оплаты, нужно регистрировать платёжную систему с опциональным параметром canProcessPaymentReturnWithoutOrder = true. Т.е.
var disposable = PluginContext.Operations.RegisterPaymentSystem(paymentSystem, true);
В отличие от всех упомянутых выше методов, метод ReturnPaymentWithoutOrder() не имеет контекста заказа и проведённой ранее оплаты. Предполагается, что суммы и типа оплаты достаточно для выполнения возврата. В процессе данной операции доступна возможность показывать пользователю диалоговые окна и печатать квитанции, так же, как и для всех упомянутых выше методов.

**Comment by igorpooh1978** [comment]
Добрый день. Да такая возможность есть.
К сожалению ReturnPaymentsWithoutOrder немного не подходит. Т.к. плагин ведет свою собственную бд заказов и есть связь между orderId в системе и заказом в БД. 
Кратко мы отправляем данные из iiko во внешнюю систему, в том числе и информацию по проданным позициям. 
Получается, что в этом случае мы ничего передать из возврат а закрытой смены не можем. Т.к. orderId не известен. 
Или всё таки есть какие либо варианты ?

**Comment by igorpooh1978** [comment]
Дополнение.
У вас есть замечательная функция 
ShowOkPopupOnPastOrderScreen
и там отдаётся orderId

**Comment by letolica** [comment]
К сожалению, метод [`ReturnPaymentWithoutOrder`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_ReturnPaymentWithoutOrder.htm) пока не выставляет в Api информацию о возвращаемом заказе. Иных способов узнать заказ тоже нет. Мы подумаем над возможной доработкой.

**Comment by letolica** [comment]
Заведена задача. Внутренний номер RMS-51793.

**Comment by letolica** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/12/01/return-payment-without-order.html)

**Comment by ROSimulin** [comment]
я бы хотел возобновить
в ReturnPaymentWithoutOrder(decimal sum, Guid? orderId,....
Не работает var order = PluginContext.Operations.GetOrderById(orderId.Value);
Могу предположить поиск происходит только по заказам что в открытой смене
У нас сценарий требует дальнейшей работы с TryGetOrderExternalDataByKey, который также не отрабатывает

**Comment by igorpooh1978** [comment]
Для заказов закрытых смен лучше данные хранить в своей БД)
