### ISSUE TITLE
Запретить действия кассира

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#177]
Добрый день. Есть задача Запретить кассиру пробивать заказ при условии что у заказа указана определенная ценовая категория. 

Зачем: Через Api создаться и оплачивается заказ с определенной ценовой категорией, Но кассир может сделать возврат и его поправить. А после возврата ценовая у заказа не слетает, и кассир может делать с заказом что хочет. И наша задача запретить это.

**Comment by letolica** [comment]
Добрый день.
Попробуйте подписаться на событие [`SubscribeOnBeforeOrderBill`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_INotificationService_SubscribeOnBeforeOrderBill.htm). И из него по условию кидать `OperationCanceledException`. Отличить пречек из Api от пречека из UI можно, проверив пришедший на вход `IViewManager` на `null`.

**Comment by Kamaew** [comment]
Огромное Спасибо!

**Comment by Kamaew** [comment]
Только. IViewManager на null всегда ((

**Comment by letolica** [comment]
> Но кассир может сделать возврат и его поправить. А после возврата ценовая у заказа не слетает, и кассир может делать с заказом что хочет. И наша задача запретить это.

Предполагалось, что в этом сценарии действия происходят из UI, где ViewManager активен (`!= null`). Опишите сценарий точнее: как кассир оплачивает возвращенный заказ: из каких экранов какие кнопки нажимает. И сообщите пожалуйста используемую версию iikoFront и Api.

**Comment by Kamaew** [comment]
Нашел другие варианты отличить
