### ISSUE TITLE
Прием внешних заказов внутри iikoFront 

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#178]
Добрый день. Подскажите, пожалуйста, что использовать в таком бизнес сценарии:

Мы пишем интеграцию с нашем сервисом через плагин iikoFront, клиенты могут делать заказы через онлайн сайт, и эти заказы долнжы "падать" в терминал iikoFront. Комуникацию с нашим сервером для получения новых заказов уже реализовали, подскажите только в плане UI:

1. Все наши заказы официант должен принять для того чтобы создался непросредственно заказ в iiko, при этом заказ должен создатся именно от имени официанта который его принял. Для этого нужен `ICredentials`, насколько я знаю, в API нет возможности получить их для любого сотрудника, в таком случае можно запрашивать у официанта его пин код при принятии заказа через модальные окна в `IViewManager` и подставлять это значение в `AuthenticateByPin`?

2. Мы не уверены, сможем ли реализовать все нужные действия с заказом через те модальные окна, которые вы предоставляете через `IViewManager`. В таком случае лучше всего делать свой интерфейс в собственном окне? Насколько много здесь может быть "подводных камней" и насколько стаблильно это будет работать?. Основываясь на Вашей документации, с этим могут быть проблемы в свзяи с тем же Top-Most Window.

3. Есть ли в API какие-то абстракции/обертки для хранения настроек плагина? Нашли `PluginSettings`, но это кажеться не совсем то. Интересует хранение например токена, который используется для подписи и идентфикации HTTP запросов на наш сервер. Или хранение настроек возложено на разработчика?

Заранее спасибо за любую помощь.

iiko v.7.3.7, API v6 (current)

**Comment by MrOnlineCoder** [comment]
Добрый день еще раз, можете помочь по вопросам выше, они все еще актуальны? Спасибо.

**Comment by vcpp** [comment]
1. Да, можно показать диалог для ввода цифровой строки ([`NumericStringInputDialogResult`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_View_NumericStringInputDialogResult.htm), куда пользователь введёт свой пин-код, но выглядеть это будет коряво — ведь пользователь уже авторизовался в iikoFront по карте или пин-коду, а тут его попросят снова и снова вводить пин-код. Наверное, для инициированных пользователь операций стоило бы передавать связанный с ним объект [`ICredentials`]. Подумаем о такой доработке.
2. Если существующих окон недостаточно, придётся рисовать своё. Подробнее [здесь](https://iiko.github.io/front.api.doc/v6/ru/CustomWindows.html). Это будет работать, на практике такое используется. Возможно, стоило бы добавить в [`IViewManager`] методы для получения hwnd основного окна и для установки фокуса на дочернее окно. Тоже понадобится доработка.
3. Пока хранение конфигов и данных возложено на разработчика, API предоставляешь ли пути к соответствующим папкам (`GetConfigsDirectoryPath`, `GetDataStorageDirectoryPath`). Запланирована доработка, которая позволит использовать штатный механизм настроек (наследника `ApplicationSettingsBase`) с хранением в нужном месте и редактированием через iikoWeb, но прямо сейчас придётся руками..

Спасибо за хорошие вопросы!
Следите за доработками :-)

**Comment by MrOnlineCoder** [comment]
@vcpp спасибо за ответ. Вариант с авторизацией официанта через пин код думаю подойдет, это можно представить как дополнительный уровень защиты и подтверждения действий, только уточните пожалуйста может ли быть что у официанта нет пин кода а есть только карта? Если да, то как тогда поступать в такой ситуации. А доработка с ICredentials будет думаю очень актуальной, видел похожие вопросы здесь. 

С ручной конфигурацией проблем нет, наличие GetConfigsDirectoryPath вполне достаточно. 

И пожалуйста еще уточните, как проходит процесс релиза этих доработок? Они могут быть выпущены только в следующей версии API (v7) или как обновление к iikoFront?

**Comment by vcpp** [comment]
> может ли быть что у официанта нет пин кода а есть только карта? Если да, то как тогда поступать в такой ситуации.

Да, пин-кода может не быть, тогда придётся его задать в iikoOffice, либо ждать выхода версии, где операции можно выполнять от имени текущего пользователя без дополнительной авторизации.

> как проходит процесс релиза этих доработок? Они могут быть выпущены только в следующей версии API (v7) или как обновление к iikoFront?

По умолчанию, доработки делаются в *разрабатываемой версии* (сейчас это V7), от которой раз в три месяца выпускается *preview-версия* (ближайшая — V7Preview5). Если успеем сделать обсуждаемые доработки до конца года, их можно будет начать использовать в версии API V7Preview5, которая выйдет вместе с iikoRms 7.5 в начале 2021 года. Подробнее [здесь](https://iiko.github.io/front.api.doc/versioning.html).

**Comment by MrOnlineCoder** [comment]
@vcpp благодарю за информацию.

<details>
<summary>P.S.</summary>
Буду еще больше благодарен если поможете с #180 
</details>
