### ISSUE TITLE
Поиск гостя

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#179]
Добрый вечер,
`var guest = PluginContext.Operations.SearchClients("7772797686").LastOrDefault();`
Как можем искать гостя привязывать к заказу?

**Comment by vcpp** [comment]
[`PluginContext.Operations.AddClientToOrder`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_AddClientToOrder.htm)
