### ISSUE TITLE
ФР метод DoBillCheque

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#18]
Здравствуйте,

Поясните пожалуйста где в iikoFront идёт ссылка на метод DoBillCheque для внешнего ФР
```c#
        public CashRegisterResult DoBillCheque(BillTask billTask)
```

**Comment by ierof** [comment]
> идёт ссылка на метод

Вы имеете ввиду, когда вызывается [`ICashRegister.DoBillCheque()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_DoBillCheque.htm)?
Это команда ["Документ типа Счёт"](https://iiko.github.io/front.api.doc/2019/03/13/bill-chequetask-resolver.html). Она вызывается, если фискальный регистратор поддерживает печать документов типа Счёт в момент печати пречека в iikoFront или перед оплатой в режиме TableService, т.к. если устройство поддерживает документы типа "Счёт", значит в чеке оплаты должен быть указан номер счёта. 
Данный документ есть в Белоруссии и Латвии, насколько нам известно. В России такой фискальный документ не нужен.
