### ISSUE TITLE
Экспорт данных из iiko

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#180]
Добрый день. Делаем интеграцию с iiko, требуется экспортировать меню и настройки столов в нашу систему. Отправляем эти данные с iikoFront, однако заметили что IProduct и ITable не имеют всех полей, которые нам нужны, а именно например количество мест за столиком, эта информация настраивается в iikoOffice но в ITable есть только номер стола, и например в том же IProduct нет информации о весе блюда, единице измерения ну и еще до десятка других полей которые настриаваются в том же iikoOffice.

Подскажите пожалуйста, что в этом случае делать и планируется ли расширение полей в этих интерфейсах?

Не прийдется ли в этом случае подключать еще тот же iikoServer API?

Заранее спасибо.

**Comment by MrOnlineCoder** [comment]
Добрый вечер, поднимаю вопрос еще раз, спасибо.

**Comment by letolica** [comment]
Добрый вечер.

> количество мест за столиком

[Для столов добавлены название, количество мест и признак активности](https://iiko.github.io/front.api.doc/2019/12/09/table-settings.html) — должно быть доступно для всех preview-версий API.V7. Вы не уточнили, какой версией iikoFront и iikoFront.API пользуетесь.

**Comment by dsshubin** [comment]
iikoFront API не ставит своей целью поддержать полную информацию о номенклатуре. Есть альтернативные источники:
1. Server API: https://ru.iiko.help/articles/api-documentations/nomenclature
2. iikoBiz API: https://ru.iiko.help/articles/api-documentations/iiko-biz и дальше ссылка на конкретный метод получения номенклатуры https://docs.google.com/document/d/1pRQNIn46GH1LVqzBUY5TdIIUuSCOl-A_xeCBbogd2bE/edit#bookmark=kix.tll8jvhgmwmu

**Comment by MrOnlineCoder** [comment]
@letolica @dsshubin спасибо за информацию. Вопрос задал поскольку все остальные нужные нам операции впринципе можно сделать через iikoFront + на Вашей почте по интеграциям посоветовали именно iikoFront API. 

Тогда уточните пожалуйста еще такие моменты:
1. Считается ли API v7 в версии Preview  стабильной и не будет ли проблем в распространении плагина? Интересует именно насколько вообще в iiko с этим ситуация, т.е. обновляют ли iikoRMS заведения, чтобы мы могли предложить плагин на новой версии API как можно большему количество пользователей?
2. Нужны ли какие-то дополнительные лицензии или регистрации для iikoServer API и можно будет ли его реализовать, если у сервера нет доступа к интернету (RMS работает в локальной и вообще возможен ли такой вариант). Если не владеете этой информацией, то подскажите где уместно будет задать этот вопрос.

Заранее благодарю.

**Comment by MrOnlineCoder** [comment]
@letolica @dsshubin извиняюсь за настойчивость, но вопросы актуальные, сроки по интеграции вже горят :)

По возможности гляньте пожалуйста еще #181

**Comment by vcpp** [comment]
> Считается ли API v7 в версии Preview стабильной и не будет ли проблем в распространении плагина

Почитайте про [управление версиями](https://iiko.github.io/front.api.doc/versioning.html). Плагин будет работать везде, где поддерживается соответствующая версия API.

> обновляют ли iikoRMS заведения, чтобы мы могли предложить плагин на новой версии API как можно большему количество пользователей?

Обновляют, но с разной скоростью. Учитывая, что мажорная версия iikoRms выпускается каждые 3 месяца и что каждая preview-версия API поддерживается всего двумя выпускаемыми в течение полугода релизами iikoRms, стоит ожидать, что одновременно будут пользователи, у которых выбранная вами preview-версия ещё не поддерживается и уже не поддерживается. Так что для массовой аудитории придётся параллельно иметь несколько веток плагина под разные версии API. Мы скоро выкатим механизм для удобного распространения и обновления плагинов, stay tuned :sunglasses:

> Нужны ли какие-то дополнительные лицензии или регистрации для iikoServer API и можно будет ли его реализовать, если у сервера нет доступа к интернету (RMS работает в локальной и вообще возможен ли такой вариант). Если не владеете этой информацией, то подскажите где уместно будет задать этот вопрос.

Да, iikoServer API требует отдельной лицензии, подробнее [здесь](https://ru.iiko.help/articles/#!api-documentations/authorization). На этой площадке говорим только об iikoFront API. По-моему, у сервера нет аналогичной площадки, поэтому вопросы по iikoServer API лучше задавать по почте: api@iiko.ru.
