### ISSUE TITLE
Создание заказа на доставку

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#181]
Добрый вечер. Взялись за интеграцию системы доставки, возникли пару вопросов:

1. Почему нужно указывать в вызове `CreateDeliveryOrder()` дважды номер телефона (в самом клиенте (PhoneDto) и как аргумент phone), и в каких случаях могут они могут отличатся?
2. Для добавление клиента в доставку, есть методы `CreateClient()` и `GetClientById()` однако есть ли возможность сделать так, что если по указанному номеру телефона клиент существует в базе, то добавить его, а если нет - то создать нового клиента? или в этом случае нужно хранить связь с Guid клиента у нас на сервере?
3. Не совсем понятно что такое `PreliminaryOrder`, сначала думали что это предзаказ, но по факту предзаказ это может быть доставка с самовывозом, тогда что это?
4. Посоветуйте что делать при таком сценарии: заказы на доставку делаются через наш сайт, и соответственно есть смысл сначала дать официанту возможность проверить заказ и только потом подтвердить или отменить его. Можно ли реализовать это с помощью IDeliveryOrder, интересует что будет если в предприятия выключена опция подтверждения доставок. А также, у нас при подтверждении заказа нужно указать сколько будет он готовится (эта информация потом отправиться клиенту через СМС или Push уведомление), есть ли такая опция у iikoFront, и если нет, то что делать в этом случае? (возможно использовать настройку на длительность доставки, которая по умолчанию равна 15 минут, но не уверен что это правильно)

Благодарю за любую помощь по этим вопросам.

P.S. для второго вопроса нашел `SearchClients`, тогда такое можно с помощью этого метода реализовать?

iiko v.7.3.7, API v6 (current)

**Comment by MrOnlineCoder** [comment]
И еще, уточните пожалуйста, в большом количестве сущностей есть параметр `originName`, но не совсем понятно что он означает и зачем используется, и какие значения можно подставить туда.

**Comment by MrOnlineCoder** [comment]
up! ;)

**Comment by vcpp** [comment]
> 1. Почему нужно указывать в вызове CreateDeliveryOrder() дважды номер телефона (в самом клиенте (PhoneDto) и как аргумент phone), и в каких случаях могут они могут отличатся?

Строго говоря, при вызове `CreateDeliveryOrder` номер телефона вы указываете единожды — это аргумент `phone`. Данный номер телефона будет использоваться при обработке этой конкретной доставки.
Этим можно и ограничиться, начиная с V7Preview1 использовать справочник клиентов [не обязательно](https://iiko.github.io/front.api.doc/2020/02/18/create-delivery-without-client.html), аргумент `client` допускает значение `null`. В этом сценарии нет никакого другого способа указать номер телефона, кроме как явно передать его параметром `phone`.

Если же справочник клиентов используется, то надо привязать создаваемую доставку к клиенту, для чего необходимо [найти существующего клиента](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_SearchClients.htm), либо создать нового клиента. Если клиент уже был создан ранее, надо проверить актуальность списка его номеров и при необходимости [обновить](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_ChangeClientPhones.htm). У ранее созданного клиента может быть несколько номеров (например, он иногда звонит с рабочего телефона, а иногда со своего), поэтому при создании доставки необходимо указать, какой из номеров должен использоваться в данном конкретном случае. Наконец, если данный клиент обращается впервые и в базе его ещё нет, только тогда вам надо вызывать `CreateClient` и заполнять анкетные данные, и только тогда можно будет говорить о том, что один и тот же номер телефона был указан два раза подряд — сначала при создании клиента и затем при создании доставки.

> 2. Для добавление клиента в доставку, есть методы CreateClient() и GetClientById() однако есть ли возможность сделать так, что если по указанному номеру телефона клиент существует в базе, то добавить его, а если нет - то создать нового клиента? или в этом случае нужно хранить связь с Guid клиента у нас на сервере?

Сначала надо выполнить поиск по номеру телефона:
```cs
PluginContext.Operations.SearchClients(phoneNumber, SearchType.Equals, ClientFields.Phone);
```
Далее либо использовать найденного клиента, либо создавать нового.

> 3. Не совсем понятно что такое PreliminaryOrder, сначала думали что это предзаказ, но по факту предзаказ это может быть доставка с самовывозом, тогда что это?

В некоторых заведениях фастфуда при скоплении на кассе длинной очереди используется такой приём ускорения обслуживания: один или несколько вспомогательных сотрудников, вооружённых мобильными устройствами, принимают заказы у стоящих в очереди клиентов. Когда эти клиенты дойдут до кассы, им останется только оплатить заказ.

`PreliminaryOrder` — это и есть предварительный заказ (предзаказ), на кассе он будет сконвертирован в обычный заказ.

Не все могут быстро сформулировать, что они хотят — начинаются муки выбора, возникают дополнительные вопросы от клиента (о характеристиках блюд), дополнительные вопросы от кассира (upsale), это может занимать десятки секунд, целые минуты, что критично в часы пик. Дабы не блокировать кассу потенциально долгой операцией выбора блюд, операция с кассы переносится в зал и распараллеливается. Вместо вспомогательных сотрудников в зале могут использоваться терминалы самообслуживания, не умеющие проводить оплату (с умеющими ходить на кассу вообще не надо).

> 4. Посоветуйте что делать при таком сценарии: заказы на доставку делаются через наш сайт, и соответственно есть смысл сначала дать официанту возможность проверить заказ и только потом подтвердить или отменить его. Можно ли реализовать это с помощью IDeliveryOrder, интересует что будет если в предприятия выключена опция подтверждения доставок.

Проверить, включена ли на предприятии опция подтверждения доставок, вы можете с помощью метода [`IsDeliveryConfirmationActive`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_IsDeliveryConfirmationActive.htm). Если подтверждения включены, доставки по умолчанию создаются в статусе `DeliveryStatus.Unconfirmed`, а иначе сразу `DeliveryStatus.New`. Независимо от этой настройки плагин может при создании доставки пометить её подтверждённой или неподтверждённой с помощью метода [`ChangeDeliveryConfirmTime`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_ChangeDeliveryConfirmTime.htm).

Однако, если подтверждение доставок выключено в настройках, а плагин тем не менее создаст доставку неподтверждённой, эта доставка автоматически отметится подтверждённой при любом изменении со стороны пользователя. Мне кажется, лучше всего действовать согласно настройке — если хотят использовать подтверждения, то использовать, а если не хотят, то не использовать.

> А также, у нас при подтверждении заказа нужно указать сколько будет он готовится (эта информация потом отправиться клиенту через СМС или Push уведомление), есть ли такая опция у iikoFront, и если нет, то что делать в этом случае?

Отбросим сценарий, когда клиент заказывает доставку к конкретному моменту времени в будущем, потому что ему при этом неважно, когда блюда начнут готовиться и сколько времени они будут готовиться, он просто получит доставку в назначенное время.

Рассмотрим только сценарий, когда клиент заказывает доставку «как можно скорее» и блюда сразу отправляются в готовку. Здесь есть два варианта:
* Продвинутый — включено [прогнозирование](https://ru.iiko.help/articles/iikodelivery-6-3/topic-106), тут мы всё сами посчитаем с учётом загруженности кухни (сколько поваров работают в смене, сколько у них текущих и предстоящих заказов), курьеров (кто куда едет и через сколько вернётся), транспортной логистики (как далеко ехать, пробки) и прочих параметров. Вы можете забрать готовый результат из полей [`PredictedCookingCompleteTime`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IDeliveryOrder_PredictedCookingCompleteTime.htm) и [`PredictedDeliveryTime`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IDeliveryOrder_PredictedDeliveryTime.htm) — ожидаемое время завершения приготовления и вручения клиенту соответственно.
* Простой — если прогнозирование не используется, вы можете найти в доставочном или кухонном заказе блюдо с максимальной продолжительностью приготовления ([`IOrderCookingItem.CookingTime`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrderCookingItem_CookingTime.htm) или [`IKitchenOrderCookingItem.CookingTime`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrderCookingItem_CookingTime.htm)) и считать, что заказ готовится столько, сколько нужно для приготовления самого долгого блюда в нём. Если клиент не сам забирает доставку (самовывоз), а использует курьера, то прибавить стандартное время доставки ([`GetTerminalDeliveryDuration`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetTerminalDeliveryDuration.htm)). Понятно, что это очень и очень неточное угадывание, поэтому я бы либо совсем не отправлял такую оценку клиенту, либо убедился, что в оценку заложен необходимый запас.

> P.S. для второго вопроса нашел `SearchClients`, тогда такое можно с помощью этого метода реализовать?

Можно.

> в большом количестве сущностей есть параметр originName, но не совсем понятно что он означает и зачем используется, и какие значения можно подставить туда.

Это свойство есть только в заказах. Вы смотрели его [описание](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IOrder_OriginName.htm)? Убедитесь, что рядом с файлом *Resto.Front.Api.V6.dll* у вас имеется *Resto.Front.Api.V6.xml*, который нужен для отображения всплывающих подсказок по коду. Ну, либо смотрите [онлайн](https://iiko.github.io/front.api.sdk/v6/search.html?SearchText=OriginName) :-)

**Comment by MrOnlineCoder** [comment]
@vcpp большое спасибо за столь развернутый ответ! originName чесно говоря не заметил как отдельную запись в документации :) 

Информация о прогнозировании доставки очень ценная для user experience, не знали что такое есть.
