### ISSUE TITLE
Изменение статусов блюда.

### ISSUE THREAD

**Issue by ArtyomKarpenko** [iiko/front.api.sdk#182]
Добрый день, подскажите пожалуйста.
Когда я плагином буду менять статус при помощи PluginContext.Operations.ChangeKitchenOrderItemsProcessingStatus(), где последним параметром нужно передать новый статус. Статус берется из KitchenOrderItemProcessingStatus, где доступно 7 статусов.
Если я правильно понимаю, то статусы блюд могут быть переименованы или вообще исключены из списка доступных в iiko office. Отсюда вопрос, можно ли в плагине узнать какие статусы вообще доступны?

**Comment by vcpp** [comment]
Хм.. действительно, метод для переключения статусов есть, а какие статусы вообще можно использовать — неизвестно. Спасибо, что подсказали, добавим в одной из будущих версий (RMS-51837).
