### ISSUE TITLE
TryGetOrderExternalDataByKey возвращает null

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#184]
Добрый день! Используем APIv7 7.4.6
Мы подписаны на OrderEditCardSlided, в обработчике события мы вызываем
```
operations.AddOrderExternalData(MamaRomaLoyaltyPlugin.GuestInfoExternalDataKey,
                            cardTrack, order, operations.AuthenticateByPin("12344321"));
```

Далее в подписке на OrderChanged , где order.Status == OrderStatus.Closed, мы пытаемся вызвать
```
var guestId = PluginContext.Operations.TryGetOrderExternalDataByKey(order.Id, MamaRomaLoyaltyPlugin.GuestInfoExternalDataKey);
```
В ответ приходит null, с чем это может быть связано? Я предполагаю, что это связано с тем, что это вызывается в обработчике

**Comment by vcpp** [comment]
> Используем APIv7 7.4.6

На всякий случай напомню, что версия V7 находится в разработке, между сборками возможны любые изменения. Если вы запускаете плагин строго на той же сборке, из которой взят SDK, то всё ок. Подробнее [тут](https://iiko.github.io/front.api.doc/versioning.html).

> `operations.AuthenticateByPin("12344321")`

Аккуратно, эта лазейка рано или поздно будет закрыта.

> В ответ приходит null, с чем это может быть связано?

Возможно, данные изначально не были добавлены. Если вы не обрабатываете выброшенные из `AddOrderExternalData` исключения, они полетят обратно в iikoFront (`OrderEditCardSlided`), который просто запишет ошибку в лог и продолжит работу.
Возможно, к моменту чтения данные из заказа были удалены.
Возможно, к моменту чтения сам заказ с указанным id был удалён.

Чего гадать, смотрите логи :-)
