### ISSUE TITLE
Открытие и закрытие явки, при помощи front api методов. 

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#185]
У клиента используется биометрический считыватель, событие которого вызывает методы открытия или закрытия личной смены:
bool OpenPersonalSession([NotNull] ICredentials credentials, [CanBeNull] IRole role = null);
bool ClosePersonalSession([NotNull] ICredentials credentials);

Эти методы работают в iikoFront, только если терминал используется для учета рабочего времени.
Клиент хочет, что бы "руками" открыть явку было невозможно, но чтоб эти методы работали.

Сценарий: Сотрудник открывает по пин-коду iikoFront, но явка не создается.
Сотрудник прикладывает палец к Биометрическому сетевому сканеру и явка открывается.

Возможно ли это ?

**Comment by vcpp** [comment]
> Возможно ли это ?

Нет, в текущей реализации открытие/закрытие личной смены через API эквивалентно открытию/закрытию смены через iikoFront. Можно открыть через API и закрыть через UI и наоборот.

По умолчанию, открытие личной смены сопровождается созданием явки. Для отдельно взятого терминала это можно [отключить](https://ru.iiko.help/articles/iikofront-7-4/topic-15/a/h2_5), тогда открытие/закрытие личной смены любым способом (через API или UI) на этом терминале не будет влиять на учёт рабочего времени.

> Сценарий: Сотрудник открывает по пин-коду iikoFront, но явка не создается.
Сотрудник прикладывает палец к Биометрическому сетевому сканеру и явка открывается.

В чём принципиальная разница между входом по пин-коду, по карте, по USB-токену, по отпечатку пальца, по радужной оболочке глаза или по любой другой внешней логике?

Обычно пин-код считается недостаточно надёжным способом — например, опаздывающий на работу сотрудник, дабы избежать штрафа за опоздание, может позвонить коллеге, который уже находится на рабочем месте, продиктовать ему свой пин-код и попросить открыть личную смену. Это классический приём, для защиты от которого давным-давно существует [право](https://ru.iiko.help/articles/iikooffice-7-4/topic-745/a/h2_1871208149) `F_OPIN` «Подтверждать открытие персональной смены по ПИН-коду». Заберите у сотрудник это право, и они не смогут открывать личную смену по пин-коду, но смогут логиниться по пин-коду, если смена уже открыта иным способом.
