### ISSUE TITLE
Есть ли в api возможность получить сгенерированный документ пречека

### ISSUE THREAD

**Issue by d3en9** [iiko/front.api.sdk#187]
Нашел в api пару событий на которые можно подписаться 
- https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_NotificationServiceExtensions_SubscribeOnServiceChequePrinted.htm

- https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_NotificationServiceExtensions_SubscribeOnBillChequePrinting.htm

Нажатие на пречек они отлавливают, но может быть они срабатывают и при печати других чеков?

Сам пречек настраивается в шаблонизаторе razor и может быть изменен.
Предусматривает ли api возможность подписаться на событие печати пречека после формирования его в шаблонизаторе razor что бы получить сформированный им документ?

**Comment by vcpp** [comment]
> Предусматривает ли api возможность подписаться на событие печати пречека после формирования его в шаблонизаторе razor что бы получить сформированный им документ?

- Если плагин сам переключает заказ в статус `Bill` вызовом метода [`BillOrder`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_BillOrder.htm), то в ответ он получает текст чека. Это может использоваться для печати пречека в ресторане прямо возле стола, если официант использует мобильный терминал с мобильным принтером.
- Если плагин реализует внешний фискальный регистратор ([`ICashRegister`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Devices_ICashRegister.htm)), который в системе настроен как принтер пречеков, то все документы, которые должны печататься на этом устройстве, ожидаемо придут в плагин.
- Если заказ в статус `Bill` переключает пользователь, другой плагин или автоматика, то есть ваш плагин не участвует в операции ни как инициатор, ни как принтер, то нет возможности перехватить печатаемый документ. Можете привести пример, для чего это может понадобиться?

> SubscribeOnServiceChequePrinted
> SubscribeOnBillChequePrinting
> Нажатие на пречек они отлавливают, но может быть они срабатывают и при печати других чеков?

Каких других? В названии каждого уведомления указано, при печати какого чека оно срабатывает.
Вообще вы указали очень разные методы. `SubscribeOnServiceChequePrinted` вызывается после печати сервисного чека, позволяя внести изменения в заказ. `SubscribeOnBillChequePrinting` вызывается до печати пречека, позволяя дополнить разметку своими вставками.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущего комментария.
