### ISSUE TITLE
Форматирование чека Document markup

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#188]
Добрый вечер
```
                printDocument.Markup.Add(new XElement(Tags.NewParagraph));
                printDocument.Markup.Add(new XElement(Tags.NewParagraph));
                printDocument.Markup.Add(new XElement(Tags.Center , 
                    new XElement(Tags.LargeFont , "XReport")
                    ));
```
В моём понимание должно было отступить две строки и 
в центре большим шрифтом распечатать "XReport", но почему-то печать идёт слева
![image](https://user-images.githubusercontent.com/47010778/99410352-6de07780-2903-11eb-8e9a-6fc5a1a781f1.png)

Где ошибка?

**Comment by vcpp** [comment]
Дополнил ваш пример краями, смотрю *virtual-printer.log*  — текст выведен по центру.
```cs
var printer = PluginContext.Operations.GetReportPrinter();
var doc = new Document
{
    Markup = new XElement(Tags.Doc,
        new XElement(Tags.NewParagraph),
        new XElement(Tags.NewParagraph),
        new XElement(Tags.Center, new XElement(Tags.LargeFont, "Промежуточный отчёт")))
};
PluginContext.Operations.Print(printer, doc);
```

У вас точно скриншот соответствует коду? В коде "XReport", на скриншоте — "Промежуточный отчет". Покажите более полный пример, что за печать, какой контекст.
Что за принтер?

**Comment by igorpooh1978** [comment]
Добрый день. Это не принтер. Я сейчас это пропускаю через XPS.
Причем если печатаю Medium, то в XPS данные по середине

**Comment by rengal** [comment]
Пробуем воспроизвести проблему. Прошу уточнить некоторые данные. 1)Я правильно понимаю, что вы говорите о виртуальном принтере "Windows XPS Document Writer"? 2)Сейчас я вижу что в коде "Х Report", а скриншот с другим текстом. Приведите минимальный фрагмент кода, с которым воспроизводится проблема (формирование и печать документа) и скриншот с результатом печати.

**Comment by igorpooh1978** [comment]
Добрый день, 
Прошу прощения за долгий ответ
```

 var printer = PluginContext.Operations.GetReportPrinter();
           XElement printDocument = new XElement(Tags.Center ,
                new XElement(Tags.LargeFont , "Промежуточный отчет")
                );
            printDocument.Add(new XElement(Tags.Line , new XAttribute(Data.Cheques.Attributes.Symbols , "=")));

            printDocument.Add(new XElement(Tags.NewParagraph));
PluginContext.Operations.Print(printer, doc);
```

**Comment by ierof** [comment]
Извините за ещё более долгий ответ :) 
На iiko 8.8.6 всё корректно: 
```
            var printer = PluginContext.Operations.GetReportPrinter();
            XElement printDocument = new XElement(Tags.Center,
                new XElement(Tags.LargeFont, "Промежуточный"));
            printDocument.Add(new XElement(Tags.Line, new XAttribute(Data.Cheques.Attributes.Symbols, "=")));
            printDocument.Add(new XElement(Tags.NewParagraph));
            PluginContext.Operations.Print(printer, printDocument);
```
![2024-04-24_12-23-55](https://github.com/iiko/front.api.sdk/assets/4930272/1c9afb13-d2ed-46e1-92e4-2b14bdebc3c3)
