### ISSUE TITLE
Событийность изменения блюд.

### ISSUE THREAD

**Issue by ArtyomKarpenko** [iiko/front.api.sdk#189]
Добрый день. 

Перед нами стоит задача отследить изменения в блюдах. То есть если повар, например, изменил статус блюда с 2 на 3, мне нужно об этом узнать.
Подскажите есть ли возможность отслеживать изменения в блюдах. Может есть возможность Event подписания на изменение блюда где в ответ будет возвращен id заказа, id блюда и что было изменено? 
Если такая возможность есть, не могли бы вы описать об этом подробно. Спасибо.

**Comment by vcpp** [comment]
Есть уведомления об изменении обычного ([`OrderChanged`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_INotificationService_OrderChanged.htm)) и кухонного ([`KitchenOrderChanged`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_INotificationService_KitchenOrderChanged.htm)) заказов, с помощью которых вы можете отследить изменения статусов блюд.

Отдельных уведомлений про блюда нет, придётся запоминать предыдущее состояние и сравнивать с новым. В SDK есть [пример](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/DiagnosticMessagesTester/OrderItemReadyChangeNotifier.cs) отслеживания момента завершения приготовления блюд.

**Comment by ArtyomKarpenko** [comment]
Я вижу, что для OrderChanged у вас есть свойство Status (https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderRootItem_Status.htm) которое можно использовать с OrderStatus.
![image](https://user-images.githubusercontent.com/57139939/99806217-bf307700-2b4e-11eb-9d2c-d4205e160897.png)

Но в моем случае нужно KitchenOrderChanged, что бы отслеживать не конкретный заказ, а именно статус блюда.
Для него есть такое свойство? Или что-то, что позволит реализовать такое отслеживание?
![image](https://user-images.githubusercontent.com/57139939/99806560-3b2abf00-2b4f-11eb-866d-db2c71989530.png)

**Comment by vcpp** [comment]
> Но в моем случае нужно KitchenOrderChanged, что бы отслеживать не конкретный заказ, а именно статус блюда.

В заказе есть список блюд ([`IKitchenOrder.Items`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder_Items.htm)), у каждого блюда — статус приготовления ([`IKitchenOrderCookingItem.ProcessingStatus`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrderCookingItem_ProcessingStatus.htm)).

**Comment by ArtyomKarpenko** [comment]
Подскажите, если мы подписываемся на какие-то изменения, то как это работает. То есть при каждом закрытии front они сбрасываются, а при открытии начинается все по новой? Или это по другому реализовано.

Что бы было понятней, я опишу нынешнюю задачу, быть может вы дадите пояснение. 
Нам нужно отслеживать блюда у которых изменился статус и забирать 3 атрибута (id заказа, id блюда, нынешний статус). Я рассчитывал подписаться на такое изменение, это реально?
