### ISSUE TITLE
ФР метод DoPayIn

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#19]
Здравствуйте

Как на основании метода
```c#       
 public CashRegisterResult DoPayIn(decimal sum, Guid cashierId)
```
а именно переменной Guid cashierId я могу получить имя кассира выполняющего внесение?

**Comment by vcpp** [comment]
[`GetUserById`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetUserById.htm).
А вообще это нехорошо, что там id, надо было сразу `IUser` передавать.

**Comment by igorpooh1978** [comment]
Коллеги, это прекрасно что надо бы. Что мне с этим сейчас делать, как вытягивать имя ?

**Comment by ierof** [comment]
Выше же ссылкой приведен метод из `IOperationService` которым нужно воспользоваться :) Там если погулять по ссылкам или воспользоваться поиском, можно узнать все сигнатуры 

[IUser](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Security_IUser.htm) user = [PluginContext.Operations.GetUserById(cashierId)](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetUserById.htm);
var name = [user.Name](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Security_IUser_Name.htm);
