### ISSUE TITLE
Обновление статуса заказа

### ISSUE THREAD

**Issue by ArtyomKarpenko** [iiko/front.api.sdk#190]
Добрый день.
Получаю ошибку при получении заказов. Метод принимает _Guid orderId_
(строка 24) _var order = PluginContext.Operations.GetKitchenOrderById(orderId);_

В логах отследил такую ошибку. 

### [2020-11-19 18:26:18,956]  INFO [11] - System.InvalidCastException: Не удалось привести тип объекта "Resto.CashServer.Data.Orders.CommonOrder" к типу "Resto.CashServer.Services.Data.Kitchen.IKitchenOrder".

Server stack trace:
   в Resto.CashServer.EntitiesManager.RootEntitiesManager`3.TryGet[T](Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:строка 276
   в Resto.Front.Api.V7.OperationService.TryGetKitchenOrderById(Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 1184
   в Resto.Front.Api.V7.OperationService.GetKitchenOrderById(Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 1191
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.GetKitchenOrderById(Guid id)
   в ItsRestroPlugin.InfoContent.ChangeStatus(Guid orderId, Guid orderItemId, Int32 ProcessingStatus) в D:\work\its_food_plugin\ItsRestro\ItsRestroPlugin\InfoContent.cs:строка 24
[2020-11-19 18:26:18,976]  INFO [11] - While in Receive
[2020-11-19 18:26:19,897]  INFO [11] - Receive:  {"method": "post", "type": "change_status", "data": {"id": "822d1356-16f4-415d-84d5-0b59487f16f0", "item": {"id": "70c76d07-e1f3-4cd5-8467-b27c8cd86181", "status": 4}}}
[2020-11-19 18:26:19,898]  INFO [11] - Order: 822d1356-16f4-415d-84d5-0b59487f16f0 Item: 70c76d07-e1f3-4cd5-8467-b27c8cd86181 Status: 4
[2020-11-19 18:26:19,898]  INFO [11] - ChangeStatus start
[2020-11-19 18:26:19,898]  INFO [11] - System.InvalidCastException: Не удалось привести тип объекта "Resto.CashServer.Data.Orders.CommonOrder" к типу "Resto.CashServer.Services.Data.Kitchen.IKitchenOrder".

Server stack trace:
   в Resto.CashServer.EntitiesManager.RootEntitiesManager`3.TryGet[T](Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:строка 276
   в Resto.Front.Api.V7.OperationService.TryGetKitchenOrderById(Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 1184
   в Resto.Front.Api.V7.OperationService.GetKitchenOrderById(Guid id) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 1191
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.GetKitchenOrderById(Guid id)
   в ItsRestroPlugin.InfoContent.ChangeStatus(Guid orderId, Guid orderItemId, Int32 ProcessingStatus) в D:\work\its_food_plugin\ItsRestro\ItsRestroPlugin\InfoContent.cs:строка 24

Подскажите пожалуйста, в чем дело?

**Comment by vcpp** [comment]
Есть два отдельных объекта — обычный заказ ([`IOrder`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Orders_IOrder.htm)) и кухонный заказ ([`IKitchenOrder`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Kitchen_IKitchenOrder.htm)), у каждого свой идентификатор, но у вас они перепутались.

`IOrder.Id` можно использовать:
* в методе [`GetOrderById`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetOrderById.htm)
* для сравнения с [`IKitchenOrder.BaseOrderId`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder_BaseOrderId.htm)

`IKitchenOrder.Id` можно использовать:
* в методе [`GetKitchenOrderById`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetKitchenOrderById.htm)
