### ISSUE TITLE
Правильная Работа с разор шаблонами

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#192]
День добрый, спустя 7 лет редактирования разор шаблонов в notepad++ открыл его редактирование в visual studio
Сделал проект MVC, добавил  dll с фронта RazorEngine.dll Resto.Front.PrintTemplates.dll
И Понял насколько жизнь может быть проще
И остался последний момент (ошибки компилятора), где у вас расширения linq
например chequeTask.Sales.IsEmpty()
и тут       return productItem.ModifierEntries.StartWith<IOrderEntry>(productItem);
IsEmpty(), StartWith - откуда?
Моё предположение что у вас есть расширения для IEnumerable, как можно их добавить в студию?

**Comment by letolica** [comment]
Добрый день.

> IsEmpty(), StartWith - откуда?

https://www.nuget.org/packages/System.Interactive/4.0.0

**Comment by ROSimulin** [comment]
спасибо, всё ок
