### ISSUE TITLE
Прием заказов с сайта, обновление статуса заказа

### ISSUE THREAD

**Issue by KateHecate2327** [iiko/front.api.sdk#193]
Здрасвтвуйте, сейчас заказы с сайта ресторана падают на старую erp, хотим перекидывать заказы в айко, не меняя апи на сайте. Можно ли написать плагин принимающий заказ от старого апи, изменяющий формат данных для айко и добавляющий заказ в список заказов в айко?  Либо возможно вы  можете посоветовать более правильный способ сделать это при помощи front api
Заранее благодарю за ответ

**Comment by vcpp** [comment]
Конечно, можно написать плагин, принимающий заказы с сайта и добавляющий их в iikoFront.
Смотрите [документацию](https://iiko.github.io/front.api.doc/), [примеры](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/EditorTester.cs) — и вперёд :-)

Если что-то не будет получаться, или возникнут вопросы, обращайтесь.
