### ISSUE TITLE
Отсуствует порядок сортировки для групп и модификаторов

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#195]
Добрый день.
В iiko Office можно менять порядок сортировки групп модификаторов и самих модификаторов (зелёные стрелочки справа).
![image_2020-12-22_15-53-49](https://user-images.githubusercontent.com/5824716/102892425-e4c3df80-4470-11eb-8dab-6eb8caba20da.png)

Однако, интерфейс IGroupModifier, являясь частным случаем IProductGroup, не представляет значения MenuIndex или аналогичного, отражающего порядок сортировки, заданный в iikoOffice.
Равно как и ISimpleModifier не имеет этого значения.

Просим завести для сохранения возможности настраивать меню для передачи во внешние устройства\модули с фронта полностью внутри iiko.

Заранее благодарны.

P.S. Собственно, для чего хотим. Есть у нас [такая штука](https://open-s.info/beopensoft/beopen-kiosk/), которая отображает меню. И мы можем настроить всё внутри iiko, не изобретая ещё 25 средств, кроме порядка сортировки групп модификаторов.

**Comment by rgalk** [comment]
Добрый день!

Завел задачу с внутренним номером RMS-52236. Попробуем сделать как можно скорее.

**Comment by CLTanuki** [comment]
Спасибо.
Ждём.

**Comment by rgalk** [comment]
Готово задача RMS-52236 выполнена. Возможность сортировать модификаторы будет с API начиная с версии V7Preview6.

**Comment by CLTanuki** [comment]
Спасибо.

**Comment by CLTanuki** [comment]
К сожалению, в V7Preview6 не нашли.

**Comment by rgalk** [comment]
А что искали? Надеюсь? поле [MenuIndex](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_ISimpleModifierBase_MenuIndex.htm). Смотрели [заметку](https://iiko.github.io/front.api.doc/2021/03/09/modifiers-position.html)?

**Comment by CLTanuki** [comment]
Моя ошибка. Не туда смотрел.
Извиняюсь.
