### ISSUE TITLE
Получить тип налогообложение через API

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#196]
Добрый день. В преддверье поголовной смены Налогообложения. Можно ли через API Front получить Налогообложение настроенное на кассе(в ККМ) и в самой iiko ? 

Чтобы например если кассу упустили и не сделали смену заблокировать ее. до смены налогообложения.

**Comment by CLTanuki** [comment]
Добрый день.
Поскольку ФР используется iiko в монопольном режиме, для решения этой задачи в текущих известных мне реалиях iiko Вам потребуется описать собственную реализацию Resto.Front.Api.Devices.ICashRegister.

**Comment by Kamaew** [comment]
Ясно
