### ISSUE TITLE
ФР подписка на OrderStorning

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#197]
Добрый день.
API V7Preview4 (да знаю, что в любой момент может что-то измениться) ;)

```c#
subscriptions = new CompositeDisposable
{
      PluginContext.Notifications.OrderChanged.Subscribe(OrderChanged),
      PluginContext.Notifications.OrderStorned.Subscribe(obj=> OrderStorning(obj.order, obj.newOrderId) ),
      PluginContext.Notifications.CurrentUserChanged.Subscribe(CurrentUserChanged),
};
```
Делаю подписку на ряд нотификаций

Подскажите при работе Возврат заказов из закрытых смен, должна ли срабатывать нотификация OrderStorning ?

Спасибо

**Comment by letolica** [comment]
Добрый день.

> API V7Preview4 (да знаю, что в любой момент может что-то измениться)

В API.V7Preview4 ничего не изменится. Версия зафиксирована и выпущена.

> Подскажите при работе Возврат заказов из закрытых смен, должна ли срабатывать нотификация OrderStorning ?

Нет, при возврате заказов закрытых КС данное событие не генерируется.

**Comment by igorpooh1978** [comment]
> В API.V7Preview4 ничего не изменится. Версия зафиксирована и выпущена.
> 
> >
В Preview у вас всегда что-то меняется )
Спасибо за ответ.

**Comment by letolica** [comment]
> В Preview у вас всегда что-то меняется )

Если у вас есть примеры нарушения обратной совместимости какой-либо из версий API Preview\*, просьба зарепортить баг. Можно даже написать небольшой прототип плагина, демонстрирующего ошибку.
Мы выкладываем окончательные версии библиотек API в [нугет](https://www.nuget.org/profiles/iiko), этим гарантируя их неизменность.
