### ISSUE TITLE
Изменять статус Накладной через API 

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#199]
Добрый день. Можно ли серверным API как то изменять статус приходной накладной с проведен на не проведен, удален и прочее ?

**Comment by vcpp** [comment]
Здесь говорим об iikoFront API.

Про iikoServer API можно почитать [тут](https://ru.iiko.help/articles/#!api-documentations/loading-and-editing-the-invoice/a/h2_662590170), там перечислены допустимые статусы `documentStatus`: `NEW`, `PROCESSED`, `DELETED`. Специальной площадки для общения с разработчиками iikoServer API нет, поэтому вопросы по серверному и другим API можно задавать по почте: api@iiko.ru
