### ISSUE TITLE
Кастомизация чека об оплате

### ISSUE THREAD

**Issue by kstroganov** [iiko/front.api.sdk#20]
Здравствуйте,

Подскажите пожалуйста, как в приложении iikoFront, в чек об оплате добавить информацию из нашего платёжного плагина.

Предположительно, есть 2 пути сделать это: в шаблонах кассовых чеков, которые доступны для редактирования из бэк-офиса, либо подписавшись на событие PluginContext.Notifications.SubscribeOnCashChequePrinting в нашем платёжном плагине.

Но в первом случае, непонятно как получить доступ к информации из нашего платёжного плагина (например получив доступ к IPaymentDataContext).

А во втором случае, вообще непонятно как работать с объектом CashCheque, который должен возвращаться из функции обработки сообщения PluginContext.Notifications.SubscribeOnCashChequePrinting.

Помогите пожалуйста разобраться.

Спасибо.

**Comment by ierof** [comment]
Лучше идти по второму пути: через подписку на `SubscribeOnCashChequePrinting`.
Как получать – через запись через `IPaymentDataContext.SetCustomData("any data you want");` в процессе оплаты.
Как считывать в подписчике: через в заказе, id которого приходит в метод находить нужный оплатный айтем вашего типа и из него считывать `AdditionalData`

**Comment by kstroganov** [comment]
Спасибо за ответ.

Если действовать вторым способом, то у меня нет проблем с получением данных в моём плагине - в обработчике события SubscribeOnCashChequePrinting. То что Вы написали - мне понятно.

Мне непонятно другое: как именно кастомизмровать чек. Как мне работать с объектом типа CashCheque, после того как я его создал. А конкретно, как мне сделать так, чтобы на чеке, после шапки, дополнительно печатались мои данные.

**Comment by ierof** [comment]
[`CashCheque`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Cheques_CashCheque.htm) есть два поля - before и after плейсхолдеры. Вам наверное подойдёт [`BeforeCheque`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Cheques_CashCheque_BeforeCheque.htm). Он `XElement`. Как работать с ними для печати есть в [SDK Sample про печать собстенного текста в пречеке](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/BillChequeExtender.cs) и косвенно упоминается в [статье про оплаты](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html).

**Comment by ierof** [comment]
Примерно так это может выглядеть:
В каком-нибудь `Pay` сохранять данные в нужном виде – строкой, сериализовнным объектом:
```cs 
 context.SetCustomData("any data you want");
```

В конструкторе подписаться 
```cs
resource = PluginContext.Notifications.SubscribeOnCashChequePrinting(OnCheque);
```
И реализовать `OnCheque` как-то так:
```cs
private CashCheque OnCheque(Guid orderId)
{
	var order = PluginContext.Operations.GetOrderById(orderId);
	var data = order.Payments
		.FirstOrDefault(i => i.AdditionalData is ExternalPaymentItemAdditionalData)?.AdditionalData 
		as ExternalPaymentItemAdditionalData;
	return new CashCheque
	{
		BeforeCheque = data == null ? null : new XElement(Tags.Center, data.CustomData)
	};
}
```

**Comment by kstroganov** [comment]
Большое спасибо за помощь. Разобрался. Добавил информацию из плагина в чек.

Есть ещё вопрос: как можно в шаблоне чека, в настройках бек-офиса определить что оплата идёт из нашего плагина?

Вот, например, я добавил в шаблон чека такую настройку:
`    @if (Model.Extensions.BeforeCheque != null && Model.Extensions.BeforeCheque.Count() > 1)
    {
        <center>Квитанция о закрытии заказа на отель</center>
        <whitespace-preserve>@Raw(string.Join(Environment.NewLine, Model.Extensions.BeforeCheque))</whitespace-preserve>
        <center>******************************************</center>
    }`

Она работает хорошо для моего плагина, но если будет ещё плагин, который заполняет поле BeforeCheque, то это будет работать некорректно.

**Comment by ierof** [comment]
Вообще шаблоны не относятся к API iikoFront, по которому мы консультируем на данной платформе :)
Во-первых, зачем вам в шаблоне определять, что текст добавлен именно из вашего плагина? iiko при составлении квитанций по шаблонам абстрагирована от авторов всех Extension-ов.
Во-вторых, если очень нужно, вы можете придумать любое решение, зная всех "участников процесса". Какого-то true way тут нет. Можно какой-нибудь маркерный префикс добавлять вам при записи `BeforeCheque` в плагине, а в шаблоне "разбирать" `Extensions.BeforeCheque` и выполнять нужную вам логику. Шаблоны пишутся на razor, а это тоже c#.  

За более подробной консультацией про шаблоны чеков при необходимости можно обратиться в тех.поддержку iiko.

**Comment by kstroganov** [comment]
> Во-первых, зачем вам в шаблоне определять, что текст добавлен именно из вашего плагина? iiko при составлении квитанций по шаблонам абстрагирована от авторов всех Extension-ов.

Ещё раз попытаюсь объяснить что нам требуется: нам нужно чтобы при оплате через наш плагин, шаблон чека несколько видоизменялся. Как я писал в своём первом сообщении, для решения этой задачи видится 2 пути: либо определить полностью свой шаблон для нашего вида оплаты, либо каким-то образом кастомизировать общий шаблон. Поскольку Вы мне посоветовали идти по второму пути (опять же вопрос: можно ли как-то определять выбор шаблона, при оплате тем или иным плагином?), то я и пытаюсь решить эту задачу как можно более правильно.

Конечно, есть 2 поля BeforeCheque и AfterCheque и это уже даёт много возможностей, но может потребоваться больше. Например, нам нужно чтобы при оплате через наш плагин, заголовок был "Квитанция о закрытии заказа на отель", а не стандартный, который используется в шаблоне и определённый в ресурсах приложения:
`<center>@(chequeTask.IsStorno ? Resources.StornoCheque : chequeTask.IsBuy ? Resources.OrderBuyReceipt : Resources.OrderPaymentReceipt)</center>`

Это, в свою очередь, значит, что я не могу просто использовать BeforeCheque и AfterCheque в общем шаблоне, т.к. в лучшем случае я получу 2 заголовка (если, например, засуну его в BeforeCheque).

Как я понял, Вы предлагаете добавить дополнительный, "невидимый" XElement в BeforeCheque и в шаблоне определять есть он в наличии, или нет. Но это реальный костыль, который можно применять только если вообще больше нет никаких вариантов. Шаблон, при этом, превратится в непонятного монстра, где несведущий человек не сразу разберётся что к чему...

**Comment by ierof** [comment]
Можем вернуться к исходному вашему вопросу:
> в чек об оплате добавить информацию из нашего платёжного плагина.

Всё-таки, вам нужно выводить в квитанции об оплате какие-то данные, которые получаются в процессе оплаты в вашем плагине? Или менять заголовки чеков?

Если и то, и другое, то возможно вам потребуется и добавлять данные править шаблоны. И это может быть достаточно громоздко, не исключаю этого. Но шаблонный механизм на то и достаточно гибкий, чтобы иметь возможность его средствами реализовать различные требования.

Возможно, вам не стоит решать обе задачи одними средствами: добавлять кастомные данные через `CashCheque` в плагине. Менять заголовки в квитанциях анализируя `Model.ChequeTask.AdditionalPayments` или `Model.Order.Payments` в шаблоне.

**Comment by 89083428448** [comment]
Гуру программисты нужна ваша помощь,
как можно сделать так чтобы не на всех точках выходила информация например измененный номер заказа, для очереди выдачи(arrivals)
сейчас используем единый шаблон, а на 2х других точках экрана выдачи нет и смысла нет, 
так же qr для чаевых

**Comment by 89083428448** [comment]
задача сократить расход бумаги
