### ISSUE TITLE
API V7Preview4 странное поведение GetUserRoles

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#200]
Добрый день

Сейчас тестируем ряд фич новой версии API и выяснилась одна интересная вещь
Если сотруднику задать роль Системный администратор, то GetUserRoles нормально отдаёт роли пользователя
```json
// IUser.GetUserRoles()
[{"Name":"Системный администратор","Id":"96e9fd57-67e7-7beb-b97a-9537d1c2afe7"}]
///PluginContext.Operations.GetUserRoles(IUser)
[{"Name":"Системный администратор","Id":"96e9fd57-67e7-7beb-b97a-9537d1c2afe7"}]
```
Если задать управляющий или менеджер, то возвращаются пустые значения
```json
{"Name":"Управляющий","Type":1,"IsSessionOpen":true,"CellPhone":null,"Card":"","Code":"6","Id":"f3fa9698-4794-4ab7-8717-7eb55bd00ffa"}
// IUser.GetUserRoles()
[]
///PluginContext.Operations.GetUserRoles(IUser)
[]
```
Но если добавить менеджеру или управляющему должность +системный администратор, то волшебным образом отображаются обе роли
```json
{"Name":"Управляющий","Type":1,"IsSessionOpen":true,"CellPhone":null,"Card":"","Code":"6","Id":"f3fa9698-4794-4ab7-8717-7eb55bd00ffa"}
// IUser.GetUserRoles()
[{"Name":"Управляющий","Id":"1aa60fd8-a473-cad2-fd20-79f810351cc7"},{"Name":"Системный администратор","Id":"96e9fd57-67e7-7beb-b97a-9537d1c2afe7"}]
///PluginContext.Operations.GetUserRoles(IUser)
[{"Name":"Управляющий","Id":"1aa60fd8-a473-cad2-fd20-79f810351cc7"},{"Name":"Системный администратор","Id":"96e9fd57-67e7-7beb-b97a-9537d1c2afe7"}]
```

![image](https://user-images.githubusercontent.com/47010778/104354973-0f0e3780-551b-11eb-9184-fc0b0ee0e973.png)

**Comment by igorpooh1978** [comment]
Путем метода научного тыка, выяснилось, что на GetUserRoles имеет влияние флаг прав доступа F_CWAUS. 
Это корректное поведение данной функции? Ведь исходя из логики роли пользователя я должен получить вне зависимости от настроек прав доступа.

**Comment by igorpooh1978** [comment]
В продолжение - или поставить роли График работы --> "Свободный" или "Оклад".

**Comment by vcpp** [comment]
> Путем применения "метода научного тыка", выяснилось, что на GetUserRoles имеет влияние флаг прав доступа F_CWAUS.
Это корректное поведение данной функции?

Конечно, это баг. В логику формирования списка ролей сотрудника подмешалась логика открытия личной смены вне расписания сотрудником без обнаруженного вами права. Спасибо за сигнал, поправим.
