### ISSUE TITLE
Нотификация из Front'а в API об изменении CultureInfo

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#201]
Добрый день, подскажите, а есть ли какие-нибудь средства наблюдения ли планируются ли за тем, что на фронте сменили язык ?
Что-то вроде **PluginContext.Notification.CultureInfoChanged** ?
У вас есть замечательная команда для получения информации о CultureInfo на фронте. Удобно при старте мультиязычного плагина, но вот при смене "на лету" распихивать эту проверку по всему плагину не очень удобно.

**Comment by letolica** [comment]
Добрый день.
Такая задача в планах есть. Внутренний номер RMS-51727.
