### ISSUE TITLE
Передача данных фискального регистратора при открытии и закрытии кассовой смены

### ISSUE THREAD

**Issue by banforfunr** [iiko/front.api.sdk#204]
Всем привет.
Можете добавить передачу данных фискального регистратора при открытии и закрытии кассовой смены? Например, так как сделано в методах IChequeTaskProcessor.

**Comment by letolica** [comment]
Добрый день.
Под данными фискального регистратора понимается объект какого типа? [`ICashRegisterInfo`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_ICashRegisterInfo.htm)?
Под открытием/закрытием КС какие методы понимаются? [`DoOpenSession`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Devices_ICashRegister_DoOpenSession.htm) и [`DoZReport`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Devices_ICashRegister_DoZReport.htm) или [`OpenCafeSession`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_OpenCafeSession.htm) и [`CloseCafeSession`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CloseCafeSession.htm)?

**Comment by vcpp** [comment]
Начиная с V7 в объект кассовой смены добавлена информация о фискальном регистраторе: [`ICafeSession.CashRegister`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Device_ICafeSession_CashRegister.htm).
