### ISSUE TITLE
Вопрос про IChequeTaskProcessor

### ISSUE THREAD

**Issue by banforfunr** [iiko/front.api.sdk#205]
Всем привет.
Есть ли способы научить IChequeTaskProcessor.BeforeDoCheckAction вызываться только для заказа, у которого назначены фискальные типы оплат и не вызываться при для заказа с нефискальными типами/комбинированными фискальными и нефискальными?

**Comment by CLTanuki** [comment]
День добрый.
В ChequeTask есть OrderId. Можно выдрать заказ с помощью Operations.TryGetOrderById и, если у заказа не будет фискальных платежей, возвращать null (не уверен, что можно именно так) или пустой BeforeDoCheckActionResult.

**Comment by letolica** [comment]
Вообще, оплата заказа на фискальном регистраторе с ФФД >= 1.0.5 не должна начинаться, если в заказе есть комбинация фискальных и нефискальных платежей (предоплат и пр.). На UI выводится сообщение о невозможности такой оплаты. Исключение — оплаты, проводимые как скидка.

**Comment by vcpp** [comment]
> В ChequeTask есть OrderId. Можно выдрать заказ с помощью Operations.TryGetOrderById и, если у заказа не будет фискальных платежей, возвращать null (не уверен, что можно именно так)

Всё верно, `null` вернуть можно.
Это всего лишь точка, где при желании можно внести изменения в `ChequeTask`. А если желания нет, можно просто посмотреть и ничего не менять.
