### ISSUE TITLE
У IProductGroup отсутствует артикул

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#206]
Добрый день, коллеги.
У интерфейса IProductGroup отсутствует поле Number (артикул), хотя оно есть и доступно пользователю.
![image](https://user-images.githubusercontent.com/5824716/105537414-f237e800-5d02-11eb-8055-dc3236efc4b9.png)
Не будете ли любезны исправить?

**Comment by letolica** [comment]
Добрый день.
Добавим. Внутренний номер задачи RMS-52141.

**Comment by letolica** [comment]
День добрый.
Готово. Артикул для группы продуктов будет доступен начиная с API.V7Preview6.

**Comment by CLTanuki** [comment]
Спасибо.
Ждём.

**Comment by letolica** [comment]
Наконец написали новость:
https://iiko.github.io/front.api.doc/2021/06/30/product-group-number.html

**Comment by CLTanuki** [comment]
Спасибо. Уже используем=)
