### ISSUE TITLE
Нюанс SetInfoForReports

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#207]
День добрый, 
Пеймент Плагин, операция оплаты (7.4.6)
IPaymentDataContext.SetInfoForReports сохраняет данные в поле номер карты оплаты только в том случае если в настройках типа оплаты не стоит галочка "проводить как скидку"
Фискальные регистраторы например Атол не поддерживают комбинаторику фискального и нефискального типа оплаты в одном чеке, и мы вынуждены ставить галочку
По итогу такая картина в олапе (180 чек как нефискальный тип оплаты, 181 скак скидка)
![2021-01-26_113506](https://user-images.githubusercontent.com/49676927/105820408-94d5bc80-5fca-11eb-865f-b91177bfd1fc.jpg)

А по итогу задача банальная, посмотреть в бэке кто конкретно поел по внешней системе

**Comment by letolica** [comment]
Добрый день.

К сожалению, это не зависит от API фронта. Это особенности работы фронта и сервера в части оплат, проводимых как скидка. Проще говоря, для сервера оплата как скидка — это не оплата вовсе, а аналог обычной скидки, применяемой к заказу во фронте. Поэтому заполненные поля игнорируются.

**Comment by letolica** [comment]
Кстати, в методе `SetInfoForReports` можно задать 2 аргумента: `cardNumber` и `cardType`.
`cardNumber` в ОЛАПе выводится в столбце с названием _"Номер карты оплаты"_, а `cardType` — в столбце с названием _"Тип карты"_.

Спасибо за заявку. Заведена задача с внутренним номером RMS-52140. Мы подумаем, как решить проблему с отсутствием заполняемых полей для типа оплаты, проводимого как скидка. Когда задача будет решена, напишем здесь.
