### ISSUE TITLE
Barcode для продукта

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#209]
Добрый день.
В интерфейсе [продукта](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Assortment_IProduct.htm) отсутствуют данные о штрих-коде товара.
Обозначенные данные необходимы для обеспечения возможности сканирования отдельностоящими устройствами, считающими iiko мастер-системой. В частности, терминалами самообслуживания.
Будем признательны за появление поля Barcode в интерфейсе IProduct.

**Comment by CLTanuki** [comment]
@letolica , простите за глупость.
Я же сам комментировал подобный запрос - https://github.com/iiko/front.api.sdk/issues/157. А тут и самим бы пригодилось.
Собственно, уже двое за эту фичу.

**Comment by zed220** [comment]
Здравствуйте!

В версии 7 была добавлена функциональность для работы со штрихкодами. Краткое описание можно прочитать в новости:
http://iiko.github.io/front.api.doc/2021/12/07/product-barcodes.html
