### ISSUE TITLE
Выборка данных с ошибкой

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#21]
Здравствуйте!

Произвели запуск нашего плагина на рабочем терминале ресторана. Плагин представляет собой self-hosting RestAPI-приложение.

Плагин подключился корректно, логгирование работает. На тестовом сервере (на виртуальной машине) все методы выборки и создания заказов отрабатывали без ошибок. Однако, на рабочем терминале в некоторых методах получения заказов происходит странная ситуация:
Например, если на виртуалке [ВЫБОРКА](https://pastebin.com/ws5A4cG7) всех заказов по ревизии отрабатывает без ошибок, то от работающего оборудования приходит ответ:
> Newtonsoft.Json.JsonSerializationException: ISerializable type 'Resto.Front.Api.V6.Data.Orders.IDeletionMethod' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path 'Items[3].DeletionMethod', line 1, position 9070.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at SMiikoAPI.Controllers.OrdersController.GetOrdersByRevision(Int32 revision)
Причём, происходить это может в случайное время в процессе работы и иногда некоторое время после запуска iikoFront.

С чем может быть связана эта ошибка?

P.S. общался с техподдержкой по api@iiko.ru / pyrus_main@iiko.ru. Финальный ответ: "Оба этих вопроса вы можете самостоятельно проверить , написав плагин" :)

**Comment by ierof** [comment]
Судя по стеку, вы сериализуете в JSON объекты, которые получаете из API iikoFront.
И исключение говорит о том, что объект типа `Resto.Front.Api.V6.Data.Orders.IDeletionMethod` не может быть сериализован этим методом.

Т.е. конкретный сценарий, когда это не будет работать у вас: в заказе есть удаленные блюда. Никакой магии и неопределенности, никаких сбоев под нагрузкой. Проверьте.

Как это обойти вам правильно : не могу рекомендовать. Вообще, сериализовать чужие объекты не зная их специфики это очень оптимистично :)
