### ISSUE TITLE
ChangePaymentItemSum некорректно срабатывает.

### ISSUE THREAD

**Issue by zhmpng** [iiko/front.api.sdk#211]
Добрый день!
При использовании метода ChangePaymentItemSum мы передаем в него такие параметры, как decimal paymentSum, decimal? minPaymentSum, decimal? maxPaymentSum, [NotNull] IPaymentItemStub paymentItem, [NotNull] IOrderStub order.
Если наш код передаст в данный метод paymentSum, больше чем maxPaymentSum и больше чем minPaymentSum, то в таком случае в iiko Front для нашего внешнего типа оплаты отобразится сумма равная 0, а при нажатии на кнопку "Точная сумма" ее значение будет изменено на полную сумму заказа, а не на, то значение maxPaymentSum которое мы передали в метод ChangePaymentItemSum.
Версия iiko Front - 7.4.7012.0
![изображение](https://user-images.githubusercontent.com/75923630/106877378-be3cc980-66e9-11eb-9263-2eba4dca9637.png)
![изображение](https://user-images.githubusercontent.com/75923630/106877446-ce54a900-66e9-11eb-8cc2-6f651ab53a94.png)
![изображение](https://user-images.githubusercontent.com/75923630/106877463-d6ace400-66e9-11eb-8aa0-35997ae36ba8.png)

**Comment by rgalk** [comment]
Добрый день!

В вашем случае при вызове метода *ChangePaymentItemSum* с указанными параметрами не возникает исключения *ArgumentOutOfRangeException* с текстом "Payment sum cannot be greater than max payment sum (3)"?

**Comment by zhmpng** [comment]
Добрый день.
Нет, никаких исключений в таком случае не возникает у меня. @rgalk

**Comment by rgalk** [comment]
Можете привести код вызова метода ChangePaymentItemSum вместе с некоторым контекстом, чтобы было понятно как используется editSession? Также понадобятся логи фронта (cash-server.log, api.log, лог плагина).

**Comment by zhmpng** [comment]
@rgalk Добрый день. Простите за дезинформацию. Перепроверили и действительно мы получаем исключение ранее описанное вами.
