### ISSUE TITLE
Получение настройки "Запрос типа заказа при создании заказа" по API

### ISSUE THREAD

**Issue by evgenyvalavin** [iiko/front.api.sdk#213]
![image](https://user-images.githubusercontent.com/35497422/108945716-f008d680-767e-11eb-9163-b5994eb0e871.png)
Есть потребность получать настройку "Автоматического запроса типа заказа". Сможем доабвить в API?

**Comment by CLTanuki** [comment]
Добрый день.
Подскажите, пожалуйста, какую задачу решаете? Будет проще помочь, если будет понятна цель.
Спасибо.

**Comment by evgenyvalavin** [comment]
@CLTanuki добрый. Поможет только новый метод API.

iikoWaiter5
![image](https://user-images.githubusercontent.com/35497422/109419392-08665180-79ef-11eb-9946-18fa6bb77f5f.png)
Боль настройки и поддержки - отдельная дублирующая настройка. С помощью нового метода эту настройку можно будет удалить и сделать жизнь проще.

**Comment by CLTanuki** [comment]
В качестве обходного пути можно пробовать создавать или изменять статус, получать ошибку и тогда выводить запрос. Благо, ошибки вполне понятные. Кстати, сталкивались ли в API с этим ограничениями? Не уверен, что я когда-либо получал такую ошибку.
Однако, настройки ТО из офиса были бы очень полезны в целом, так как регулярно могут помочь какие-либо поля. Например, стол по умолчанию.

**Comment by vcpp** [comment]
> Есть потребность получать настройку "Автоматического запроса типа заказа"

Похоже, вы ищете [`PluginContext.Operations.GetHostRestaurant().OrderTypeFillRequirements`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Organization_IRestaurant_OrderTypeFillRequirements.htm).

> настройки ТО из офиса были бы очень полезны в целом, так как регулярно могут помочь какие-либо поля. Например, стол по умолчанию.

В прошлом году [добавили](https://iiko.github.io/front.api.doc/2020/07/31/default-table-of-group.html): [`PluginContext.Operations.GetHostTerminalsGroup().DefaultTable`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm).
Если ещё чего-то не хватает, дайте знать, добавим.
