### ISSUE TITLE
Через API блюдо определяется как доступное к продаже, но вызывает ошибку при попытке продажи

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#214]
Добрый день.
Имеется метод следующий код:
```
var products = operationService.GetAllProducts();
var sections = operationService.GetRestaurantSections();
var visibleProducts = products.Where(p => p.Type == ProductType.Modifier || operationService.GetIncludedInMenuSectionsByProduct(p).Any(s => sections.Contains(s))).ToList();
var dumpContent = visibleProducts.Select(p => $"{p.Id} {p.Name}");
DebugHelper.DumpToFile("visibleProducts", dumpContent);

```
Этот код заботливо складывает полученный список в файл visibleProducts.json в папке с данными плагина: `CashServer\EntitiesStorage\Plugins\BeOpen.Front.Plugins.JsonRPC\visibleProducts.json`.

Однако, при попытке добавить блюдо в заказ, получаем ошибку в логе `plugin-BeOpen.Front.Plugins.JsonRPC.log`.
```
[2021-03-04 15:38:40,758] ERROR [66] - Error creating order
Resto.Front.Api.Exceptions.ConstraintViolationException: Product “тест блюдо” (42560d90-dfdc-4c54-bb2d-dd5916c49386) is excluded from menu for order's table 2 (52b46281-eaa5-415f-9caa-3dedb7b26570).

Server stack trace: 
   в Resto.Front.Api.V6.Editors.Actions.AddOrderProductItem.CheckArgumentsCore(OrderItemCourse course, IProduct product, IBaseOrderBuilder order, IProductSize size, IBaseOrderGuest guest, SessionContext context) в H:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Editors\Actions\AddOrderProductItem.cs:строка 43
   в Resto.Front.Api.V6.Editors.Actions.AddOrderProductItem.Resto.Front.Api.V6.Editors.IEditActionBase.WriteChanges(SessionContext context, IDictionary`2 createdEntities, IDictionary`2 actionNumbersToCreatedApiEntities, Int32 i) в H:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Editors\Editors.g.cs:строка 664
   в Resto.Front.Api.V6.Editors.EditSessionWriter.WriteChanges() в H:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Editors\EditSessionWriter.cs:строка 204
   в Resto.Front.Api.V6.OperationService.SubmitChanges(IUser user, IEditSession editSession) в H:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\OperationService.cs:строка 1570
   в Resto.Front.Api.V6.OperationService.Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в H:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Operations.g.cs:строка 2395
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession)
   в BeOpen.Front.Plugins.JsonRPC.Transport.Services.OrderService.CreateOrder(NewOrderRequest orderRequest)

```

Для добавления используется следующий метод:
https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm

Подскажите, пожалуйста, что делаем не так?

**Comment by letolica** [comment]
Добрый день.
А в заказ добавляете из списка `visibleProducts.json`?
Просто в список складываются продукты вне зависимости от того, продаются ли они в отделении, в котором находится стол текущего заказа: `operationService.GetIncludedInMenuSectionsByProduct(p).Any(s => sections.Contains(s))`. Ваше тестовое блюдо может продаваться в "Отделении 1", но не продаваться в остальных отделениях, а заказ может находиться на столе в "Отделении 2", где это блюдо уже недоступно для продажи. Модификаторы вовсе складываются в список без проверки.

**Comment by CLTanuki** [comment]
А как проверить относимость к столу?

**Comment by letolica** [comment]
> А как проверить относимость к столу?
```
var order = operationService.GetOrders().Last(o => o.Status == OrderStatus.New);
var orderSection = operationService.GetRestaurantSections().SingleOrDefault(s => s.Tables.Contains(order.Tables[0]));
var availableForOrderProducts = operationService.GetAllProducts()
    .Where(p => operationService.GetIncludedInMenuSectionsByProduct(p).Contains(orderSection))
    .ToList();
```
> С модификаторами это технический долг. Спасибо за подсказку - сейчас исправим.

С модификаторами более особенная работа: #46

**Comment by CLTanuki** [comment]
Спасибо. Всё гениальное просто-_-
Только вот здесь логика ломается: GetRestaurantSections() возвращает секции за пределом видимости, а GetOrders нет.
Почему так?

**Comment by CLTanuki** [comment]
Проверил. API показывает, что есть разрешение продажи именно для отделения, попытка продажи в котором вызывает ошибку.

Сейчас код такой:
```cs
var products = operationService.GetAllProducts();
var group = operationService.GetHostTerminalsGroup();
var sections = operationService.GetRestaurantSections();
var visibleProducts = new Dictionary<Guid, List<string>>();
foreach (var product in products)
{
    if (product.Type == ProductType.Modifier)
    {
        visibleProducts[product.Id] = new List<string>();
    }
    else
    {
        var productSections = operationService.GetIncludedInMenuSectionsByProduct(product);
        foreach(var section in productSections)
        {
            if (sections.Contains(section))
            {
                if (!visibleProducts.ContainsKey(product.Id))
                {
                    visibleProducts[product.Id] = new List<string> { section.Name };
                }
                else
                {
                    visibleProducts[product.Id].Add(section.Name);
                }
            }
        }
    }
}
DebugHelper.DumpToFile("visibleProducts", visibleProducts);
return visibleProducts.Keys.ToList();
```

Тип номенклатуры: Блюдо.
Папка CashServer лежит в https://pyrus.com/t#id79400707.

**Comment by vcpp** [comment]
> Только вот здесь логика ломается: GetRestaurantSections() возвращает секции за пределом видимости, а GetOrders() нет.
Почему так?

Это разные справочники, и у них разные «пределы видимости».
Само приложение iikoFront и плагины «видят» всю структуру торгового предприятия — [все группы](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetTerminalsGroups.htm) и по каждой группе [все отделения](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetTerminalsGroupRestaurantSections.htm). Это глобальные справочники, которые также можно получить через [iikoServer API](https://ru.iiko.help/articles/api-documentations/corporations).
Заказы же — локальные объекты, существуют только на том тем терминале iikoFront, где были созданы, а также, если включена синхронизация (назначен главный терминал), видны на других терминалах группы. В отличие от кухонных заказов, обычные не синхронизируются между терминалами разных групп.

> API показывает, что есть разрешение продажи именно для отделения, попытка продажи в котором вызывает ошибку.

Такое может быть при включении товаров в продажу с учётом размера, ценовой категории и времени.
Метод `GetIncludedInMenuSectionsByProduct` является сильно устаревшим, он не учитывает всех этих параметров.
Есть появившийся в V5 относительно новый метод [`GetPrice`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetPrice.htm), с помощью которого можно узнать цену с учётом размера продукта, ценовой категории заказа и времени исполнения заказа (актуально для банкетов и доставок), но для блюд, которые исключены из продажи, этот метод возвращает цену по умолчанию из карточки продукта.
С 2017 года в бэклоге висит задача на выпиливание `GetIncludedInMenuSectionsByProduct` и объединение информации о цене и наличии в меню: RMS-45015. В основной план работ эта задача всё никак не попадёт :-(

**Comment by CLTanuki** [comment]
Спасибо за ответ.

> Само приложение iikoFront и плагины «видят» всю структуру торгового предприятия — все группы и по каждой группе все отделения.

На это имею заметить следующее:
![image](https://user-images.githubusercontent.com/5824716/110087351-969e5700-7da4-11eb-90a0-182364f4282e.png)
![image](https://user-images.githubusercontent.com/5824716/110087445-b766ac80-7da4-11eb-8bf8-cf927aa12015.png)
Сильно похоже, что в API видимость секций относительно ограничена.

> Такое может быть при включении товаров в продажу с учётом размера, ценовой категории и времени.

Если Вы ещё покажете, где настраивается доступность с учётом размера, ценовой категории и времени, будет отлично.

**Comment by letolica** [comment]
Судя по приложенной базе, блюдо _"тест блюдо"_ (`42560d90-dfdc-4c54-bb2d-dd5916c49386`) исключено из продажи для 2 отделений: _"Зал Fish and Chips"_ (`50cb8c4d-d161-4c2e-9915-ae485aa96cae`) и _"Зал Hungry Birds"_ (`ef7ffeed-ff31-8172-0176-aaf84a0f00d2`). Стол 2 (`52b46281-eaa5-415f-9caa-3dedb7b26570`) из стектрейса выше принадлежит как раз отделению _"Зал Hungry Birds"_, где это блюдо исключено.

**Comment by letolica** [comment]
> Сильно похоже, что в API видимость секций относительно ограничена.

Метод [`GetRestaurantSections`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetRestaurantSections.htm) возвращает только отделения текущей группы, о чем написано в документации: "Gets list of restaurant sections of the current terminals group."

**Comment by CLTanuki** [comment]
> Судя по приложенной базе, блюдо _"тест блюдо"_ (`42560d90-dfdc-4c54-bb2d-dd5916c49386`) исключено из продажи для 2 отделений: _"Зал Fish and Chips"_ (`50cb8c4d-d161-4c2e-9915-ae485aa96cae`) и _"Зал Hungry Birds"_ (`ef7ffeed-ff31-8172-0176-aaf84a0f00d2`). Стол 2 (`52b46281-eaa5-415f-9caa-3dedb7b26570`) из стектрейса выше принадлежит как раз отделению _"Зал Hungry Birds"_, где это блюдо исключено.
> 
> Приказов об изменении прейскуранта в базе нет.

Чуть выше я прислал отладочный код, который явно записал в файл "Зал HungryBirds" для блюда "тест блюдо".
Либо неверная логика поиска пересечений, либо ошибка в другом:
```cs
var products = operationService.GetAllProducts();
var group = operationService.GetHostTerminalsGroup();
var sections = operationService.GetRestaurantSections();
var visibleProducts = new Dictionary<Guid, List<string>>();
foreach (var product in products)
{
    if (product.Type == ProductType.Modifier)
    {
        visibleProducts[product.Id] = new List<string>();
    }
    else
    {
        var productSections = operationService.GetIncludedInMenuSectionsByProduct(product);
        foreach(var section in productSections)
        {
            if (sections.Contains(section))
            {
                if (!visibleProducts.ContainsKey(product.Id))
                {
                    visibleProducts[product.Id] = new List<string> { section.Name };
                }
                else
                {
                    visibleProducts[product.Id].Add(section.Name);
                }
            }
        }
    }
}
DebugHelper.DumpToFile("visibleProducts", visibleProducts);
return visibleProducts.Keys.ToList();
```

**Comment by CLTanuki** [comment]
Идея в этом коде следующая:
Если секция, доступная терминалу, содержится в секциях, в которых может продаваться товар, значит, его можно там продавать. Для отладки здесь оно добавляет имя секции в список.
Эта логика у нас работает более года и осечек нет. Даже на соседнем POS терминале из другой группы того же заведения доступность блюд корректно определяется.

**Comment by CLTanuki** [comment]
Идея в этом коде следующая:
Если секция, доступная терминалу, содержится в секциях, в которых может продаваться товар, значит, его можно там продавать. Для отладки здесь оно добавляет имя секции в список.
Эта логика у нас работает более года и осечек нет. Даже на соседнем POS терминале из другой группы того же заведения доступность блюд корректно определяется.

**Comment by letolica** [comment]
Метод [`GetIncludedInMenuSectionsByProduct`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetIncludedInMenuSectionsByProduct.htm) возвращает только те секции, продажа блюда в которых разрешена. Приказов об изменении прейскуранта в базе нет, а значит видимость продукта определяется только настройками в карточке блюда, где проблемное отделение исключено из списка возможных для продажи отделений. Т.е. то, что не сработало добавление тестового блюда в заказ, оправдано. Что касается тестового примера, Вы его запускаете на той же базе, что приложена к заявке https://pyrus.com/t#id79400707? Просто из скриншота торгового предприятия, что здесь приложен, видно, что проблемных отделений, которые здесь обсуждаются (_"Зал Fish and Chips"_ и _"Зал Hungry Birds"_), там нет.

**Comment by CLTanuki** [comment]
Скриншот для неразглашения был сделан с нашего стенда.
Фронт запускаем на той же базе, что и в заявке.

**Comment by CLTanuki** [comment]
Спасибо за помощь!
При удалении столов разрешение к продаже каким-то образом остаётся.
https://pyrus.com/t#id79513983

**Comment by letolica** [comment]
По результатам обсуждения нашла один из возможных сценариев, почему в карточке тестового блюда нет отделения _"Бар Hungry Birds"_:
Отделение в карточке товара может не показываться, если у отделения нет столов. Но тогда отделение не будет выдано и методом `GetIncludedInMenuSectionsByProduct`. Но вот если у отделения есть столы, но они все удалены, то в карточке блюда отделение по прежнему показываться не будет, а `GetIncludedInMenuSectionsByProduct` его выдаст, если ему специально не снимали галочку в карточке товара.

**Comment by CLTanuki** [comment]
Мы разошлись во времени на десятки секунд=)
Ещё раз спасибо!

**Comment by letolica** [comment]
Да, Вы меня опередили. Завела задачу на исправление бага: RMS-52261.

**Comment by CLTanuki** [comment]
Спасибо.

**Comment by letolica** [comment]
Добрый вечер. Если что, появился новый метод для определения включенности в меню блюда.
[Возможность узнать, что блюдо в конкретном размере доступно к продаже](https://iiko.github.io/front.api.doc/2024/09/09/get-included-in-menu.html).
