### ISSUE TITLE
Пример базы для отладки

### ISSUE THREAD

**Issue by asiryan** [iiko/front.api.sdk#216]
Люди добрые, подскажите, есть ли пример базы данных iiko для отладки с ценами, блюдами, категориями и т.д.?

**Comment by asiryan** [comment]
С настроенными блюдами, ценами, категориями и тд

**Comment by CLTanuki** [comment]
Добрый день. 
Мы уж и забыли, каково это, иметь чистый стенд.
Сейчас примеров БД нет. Точнее, есть, но это всё коммерческая тайна.
Хотя, вероятно, будет и неплохо получить такой функционал в демонстрационном стенде, но это дело ещё весьма нескорого будущего.

**Comment by asiryan** [comment]
Добрый день!
Очень жаль, болванка базы была бы очень кстати.

> Добрый день.
> Мы уж и забыли, каково это, иметь чистый стенд.
> Сейчас примеров БД нет. Точнее, есть, но это всё коммерческая тайна.
> Хотя, вероятно, будет и неплохо получить такой функционал в демонстрационном стенде, но это дело ещё весьма нескорого будущего.
