### ISSUE TITLE
Возможность технического сопровождения при разработке плагина

### ISSUE THREAD

**Issue by asiryan** [iiko/front.api.sdk#217]
Добрый день!

На данный момент мы работаем совместно с командой над интеграцией нашего продукта с программным обеспечением Iiko. У нас заключен договор с компанией pro-resto, номер которого я если что могу сообщить. Однако, коллеги нам не могут ничем помочь в консультациях по корректности использования front.api.sdk для написания плагина. Подскажите, пожалуйста, как нам связаться с людьми вроде вас (программистами Iiko), кто мог бы нам оказать техническую и консультативную помощь в разработке плагина? Есть ли вообще такая возможность технического сопровождения со стороны разработчиков iiko API? Разумеется не бесплатно, а в рамках договоренностей между компаниями.

**Comment by CLTanuki** [comment]
Добрый день.
Эта информация весьма публична: https://ru.iiko.help/articles/#!api-documentations/api-newprj

**Comment by asiryan** [comment]
> Добрый день.
> Эта информация весьма публична: https://ru.iiko.help/articles/#!api-documentations/api-newprj

Окей, спасибо!
