### ISSUE TITLE
Дополнительная документация по составным блюдам

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#218]
Добрый день.

Можете пожалуйста уточнить порядок работы со составным блюдом, а именно по добавлению его в заказ. Смотрели пример в SDK, но вот очередность действий и предназначение CompoundItem, PrimaryComponent не совсем понятны. 

Перед этим работали с привичными IProduct, ISimpleModifier, IGroupModifier, и как добавлять их в заказ было очевидно, а вот как эти сущности связаны с составным блюдом - не смогли понять.

Мы экспортиурем меню во внешнюю систему (онлайн меню), и поэтому задаемся вопросом как хранить эту номенкулатуру у себя чтобы потом можно было воиспроизвести создание заказа.
Соответвенно пример, есть составное блюдо "Бизнес ланч", в нем 2 группы модификаторов "Суп", "Гарнир" и 1 простой модификатор "Кофе". Как будет правильно добавить его в заказ? Куда добавлять модификаторы? Что такое компоненты и чем отличается primary от secondary? Что такое AddOrderCombo?

Заранее спасибо и извините если мы пропустили этот момент в документации, тогда пожалуйста "ткните" ссылкой для ознакомления :D

**Comment by CLTanuki** [comment]
Добрый день.
Вопрос: почему не пользуетесь API iiko Transport?
Если вкратце, составное блюдо может состоять из 2х половинок, к которым применяются разные модификаторы.
Самый простой пример - пицца. Но давайте рассмотрим на примере супа.
Также по некоторым соображениям составными блюдами являются блюда, к которым применяется шаблон модификаторов. Интересно, кстати, почему.

Берём пример из SDK от iiko 6.4, так как он основан на API V6, которое уже не меняется. Строка 98 гласит:
```cs
AddButton("Add compound item", AddCompoundItem);
```

Собственно, там находим следующее
```cs
/// <summary>
/// Добавление составного блюда.
/// </summary>
private void AddCompoundItem()
{
    var order = PluginContext.Operations.GetOrders().Last();
    var guest = order.Guests.Last();
    var product = PluginContext.Operations.GetActiveProducts().Last(p => p.Template != null);
    var template = product.Template;
    var size = template.Scale != null ? PluginContext.Operations.GetProductScaleSizes(template.Scale).First() : null;
    var editSession = PluginContext.Operations.CreateEditSession();
    var compoundItem = editSession.AddOrderCompoundItem(product, order, guest, size);
    var primaryComponent = editSession.AddPrimaryComponent(product, order, compoundItem);
    editSession.ChangeOrderCookingItemAmount(42m, compoundItem, order);
    var modifierDefaultAmounts = PluginContext.Operations.GetTemplatedModifiersParamsByProduct(product);
    AddDefaultCompoundItemModifiers(compoundItem, template, modifierDefaultAmounts, order, editSession);
    AddDefaultCompoundItemComponentModifiers(primaryComponent, template, modifierDefaultAmounts, order, editSession);
    PluginContext.Operations.SubmitChanges(PluginContext.Operations.GetCredentials(), editSession);
}
```

Расшифровывается это так:
1. Нашли заказ, гостя в нём и последнее активное блюдо с шаблоном (как мы знаем, оно как раз составное).
2. Выбрали первый размер, если размер у блюда вообще может быть.
3. Создали сессию и добавили составное блюдо в заказ.
4. Далее взяли 42.00 грибного супа (основной компонент), добавили в него модификаторы по умолчанию в соответствии с техкартой и налили в тарелку.
5. Пример не рассматривает [добавление второго компонента](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_AddSecondaryComponent.htm), так как, вероятно, при написании примера стало понятно, что добавление томатного супа в ту же тарелку немного испортит задумку шеф-повара.

**Comment by MrOnlineCoder** [comment]
@CLTanuki благодарю за ответ.

Не совсем понял про iiko transport, чем он может быть полезен в этом случае?

А как определяется каким именно компонентом вы могли добавить грибной суп? Можно ли его было добавить вторичным компонентом?

Ну и самое интересное, это как вы правильно заметили, блюда использующие схему модификатором почему то являються составными (IProdut.Template != null). Как с ними работать? Ожидали что там просто будут возвращены соотвествующие модификаторы на GetSimpleModifiers и GetGroupModifiers, как с обычным блюдом, но там пустые списки :) Зато модификаторы есть в ICompundItemTemplate, но вот как их потом добавить в чек - не поняли.

**Comment by CLTanuki** [comment]
> Не совсем понял про iiko transport, чем он может быть полезен в этом случае?

Если система внешняя, то и меню можно забирать "родным" для внешних систем способом.

> А как определяется каким именно компонентом вы могли добавить грибной суп? Можно ли его было добавить вторичным компонентом?

Конечно, я немного здесь поиздевался. Однако, технически, кажется, ограничения здесь нет. Хотя, признаюсь, самому интересно и сегодня попробую.

**Comment by vcpp** [comment]
@CLTanuki, спасибо за помощь :-)

> Смотрели пример в SDK, но вот очередность действий и предназначение CompoundItem, PrimaryComponent не совсем понятны.

Совсем коротко можно глянуть пример [`AddSplittedCompoundItemInternal`](https://github.com/iiko/front.api.sdk/blob/cb786be88240494945f82bb71cf7f475ce0b7d8e/sample/v6/Resto.Front.Api.SamplePlugin/EditorTester.cs#L300):
```cs
var compoundItem = editSession.AddOrderCompoundItem(templateProducts.First(), order, guest, size);
editSession.AddPrimaryComponent(templateProducts.First(), order, compoundItem);
editSession.AddSecondaryComponent(templateProducts.Skip(1).First(), order, compoundItem);
```
Добавляете в заказ составное блюдо и компоненты к нему. Затем можно будет добавлять модификаторы как к блюду целиком, так и к его компонентам.

> есть составное блюдо "Бизнес ланч", в нем 2 группы модификаторов "Суп", "Гарнир" и 1 простой модификатор "Кофе". Как будет правильно добавить его в заказ?
Что такое AddOrderCombo?

Скорее всего, «Бизнес-ланч» у вас является обычным блюдом в том смысле, что к нему не привязана схема модификаторов (`IProduct.Template == null`), поэтому и добавлять такое блюдо следует как обычное с помощью `AddOrderProductItem`. Вообще это устаревший подход к объединению блюд, так делали до появления комбо. У нас была двухуровневая иерархия — блюда и модификаторы, но не было возможности объединить блюда в группы наподобие бизнес-ланча, поэтому пользователи объявляли псевдо-блюдо «Бизнес-ланч» с псевдо-модификаторами, которые по смыслу настоящие блюда — «Суп», «Гарнир» и т. п., при этом они лишались возможности добавлять к этим блюдам модификаторы, ибо блюда уже сами как-бы-модификаторы, а модификатор к модификатору не поддерживается.
Позднее над блюдами и модификаторами появился третий уровень иерархии — комбинация блюд, aka комбо. Для работы с комбо необходимо использовать iikoCard или иную внешнюю систему лояльности. Это уже не относится к iikoFront API, почитайте [общую справку](https://en.iiko.help/articles/iikocard/topic-13).

> Что такое компоненты и чем отличается primary от secondary? 
> А как определяется каким именно компонентом вы могли добавить грибной суп? Можно ли его было добавить вторичным компонентом?

Primary — обязательный первый компонент, secondary — вторая половинка, может добавлять при делении составного блюда пополам. Пока составные блюда могут состоять из одной или двух частей. Теоретически могут появиться деление на неравные части, деление на три, четыре и более части, но пока большого спроса нет, не усложняем.

> составными блюдами являются блюда, к которым применяется шаблон модификаторов. Интересно, кстати, почему.

Потому что обобщение. Нет принципиальной разницы между одной целой пиццей и пиццей, разделённой на две части, потому что у них общие типы данных и методы, плюс они могут превращаться друг в друга, целую пиццу можно разделить, а разделённую — схлопнуть в целую. Ну и, кроме того, идея шаблонных блюд, когда единый набор модификаторов применим к целому классу блюд, оказалась интересной даже без учёта возможности делить блюда на половинки.

> модификаторы есть в ICompundItemTemplate, но вот как их потом добавить в чек - не поняли.

На примере пиццы: тесто — общий модификатор для всего блюда (тонкое/толстое, с бортом/без борта/сырный борт и т. п.), размер блюда (диаметр теста) тоже общий на всё блюдо, далее весь круг можно заполнить одинаково — это будет целая пицца (составное блюдо с единственным компонентом), либо левую и правую половинки можно заполнить по-разному, это будет разделённая пицца (составное блюдо с двумя компонентами). Подробнее [тут](https://en.iiko.help/articles/iikooffice-7-5/topic-224).

**Comment by MrOnlineCoder** [comment]
Спасибо @vcpp @CLTanuki за информацию! Вроде разобрался, однако хотел бы заметить что если попробовать добавить модификатор через AddOrderModifierItem на compoundItem без компонентов, то получим что то наподобии NullPointerExcpetion: Object reference set to null, и пришлось немного времени потратить чтобы понять где именно эта проблема)) Возможно стоит добавить проверку на таких как я, чтобы error был более human-friendly, а-ля "Cannot add modifier to compound item without any components." ;)
