### ISSUE TITLE
System.Runtime.Remoting.RemotingException: Объект "***.rem" отсоединен или не существует на сервере.

### ISSUE THREAD

**Issue by qt-user** [iiko/front.api.sdk#219]
Добрый день. Столкнулся с проблемой при разработке плагина iikoFront. Плагин работает, но через некоторое время просто перестает отвечать, ошибка в логе Api.log:
[2021-03-19 16:01:49,853] ERROR [ 1] - System.Runtime.Remoting.RemotingException: Объект "/1f2622cf_b6db_405e_b801_f36e3485b972/q1vzotuwz2aolarxkqbqmtdi_7.rem" отсоединен или не существует на сервере.  
Версия 7.4.6020.0
API v7
В более старом API с таким не сталкивался. 
Как я понимаю на сервере плагина (во фронте) происходит сборка мусора которая забирает ссылку на этот объект, сам плагин к слову продолжает работать, но команды с фронта не приходят. Нашел класс DisconnectableMarshalByRefObject от которого пробовал наследоваться, переопределив InitializeLifetimeService() но словил ошибку во фронте что объект не создан через некоторое время. Возможно есть у Вас готовое решение этой проблемы? 
Вот ошибка:
```
[2021-03-19 16:01:49,851]  INFO [ 1] - Task request (32d7fc20-4b73-4c8a-889f-ecae75900ff4): GetQueryInfo for device: ff206856-3d30-4a50-b8ee-483940cb0f6b.
[2021-03-19 16:01:49,853] ERROR [ 1] - System.Runtime.Remoting.RemotingException: Объект "/1f2622cf_b6db_405e_b801_f36e3485b972/q1vzotuwz2aolarxkqbqmtdi_7.rem" отсоединен или не существует на сервере.

Server stack trace:
   в System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
   в System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage(IServerChannelSinkStack sinkStack, IMessage msg, IMessage& replyMsg)

Exception rethrown at [0]:
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.Devices.IDevice.Start()
   в Resto.Front.Api.Devices.DevicesService.ExecuteWithResult(String requestId, String taskName, Guid deviceId, Func`2 action, Boolean skipAutorun) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\Devices\DevicesService.cs:строка 760
[2021-03-19 16:01:54,374]  INFO [60] - Task request (50ca6dbf-4452-4d9e-9531-95b91933b535): DoXReport for device: ff206856-3d30-4a50-b8ee-483940cb0f6b. CashierName = Тест (iiko), CashierTaxpayerId = .
[2021-03-19 16:01:54,385] ERROR [60] - System.Runtime.Remoting.RemotingException: Объект "/1f2622cf_b6db_405e_b801_f36e3485b972/q1vzotuwz2aolarxkqbqmtdi_7.rem" отсоединен или не существует на сервере.

Server stack trace:
   в System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
   в System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage(IServerChannelSinkStack sinkStack, IMessage msg, IMessage& replyMsg)

Exception rethrown at [0]:
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.Devices.IDevice.Start()
   в Resto.Front.Api.Devices.DevicesService.ExecuteWithResult(String requestId, String taskName, Guid deviceId, Func`2 action, Boolean skipAutorun) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\Devices\DevicesService.cs:строка 760
```

А так выглядит основной класс плагина унаследованный от IFrontPlugin:
```
namespace Resto.Front.Api.TT
{
    [UsedImplicitly]
    [PluginLicenseModuleId(21005108)]
    public class TestPlugin : IFrontPlugin, IDisposable
    {
        public static string pathToConfig = PluginContext.Integration.GetConfigsDirectoryPath();
        public static string pathToPluginData = PluginContext.Integration.GetDataStorageDirectoryPath();
        //private readonly Stack<IDisposable> subscriptions = new Stack<IDisposable>();
        public TestPlugin()
        {
            var cashRegisterFactory = new PrroCashRegisterFactory();
            PluginContext.Operations.RegisterCashRegisterFactory(cashRegisterFactory);
        }
        public void Dispose()
        {
            PluginContext.Log.Info("Dispose Plugin");
        }
    }
} 
```

**Comment by rgalk** [comment]
Искали в закрытых задачах ответы на свой вопрос?
Например, [тут](https://github.com/iiko/front.api.sdk/issues/208#issuecomment-770429209).

**Comment by CLTanuki** [comment]
> Искали в закрытых задачах ответы на свой вопрос?
> Например, [тут](https://github.com/iiko/front.api.sdk/issues/208#issuecomment-770429209) или [тут](https://github.com/iiko/front.api.sdk/issues/59), [тут](https://github.com/iiko/front.api.sdk/issues/64).

@rgalk , прошу Вас посмотреть на задачу RMS-49614 и https://pyrus.com/t#id44829531.
Обещали, что в V7 такого поведения не будет.

**Comment by rgalk** [comment]
> Правильно ли я понимаю, что это решено только в V7Preview5?

Верно, версия V7Preview5 выпущена с решением задачи RMS-49614. В ней убрали необходимость наследоваться от `MarshalByRefObject `и переопределять метод `InitializeLifetimeService`.

**Comment by qt-user** [comment]
Спасибо за оперативный ответ, я в заявке упомянул что видел DisconnectableMarshalByRefObject и переопределял InitializeLifetimeService(), но ваше сообщение дало понять что делал это не в том классе. Спасибо, проблема на первый взгляд решена.
