### ISSUE TITLE
Нагрузочное тестирование

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#22]
Здравствуйте!

Появилась необходимость провести нагрузочное тестирование для нашего плагина.
Взяли за пример [МЕТОД ](https://pastebin.com/VT6wJUJz)создания заказа на доставку.

Входные параметры в файле JSON:

> {
>     "phone": "+78005553535",
>     "products": [
>         {
>             "numberOrId": "555578284",
>             "amount": "3",
>             "modificators": [
>                 {
>                     "isGroupType": 1,
>                     "numberOrId": "555578557",
>                     "amount": 1
>                 }
>             ]
>         },
>         {
>             "numberOrId": "555576972",
>             "amount": "2,25",
>             "modificators": []
>         },
>         {
>             "numberOrId": "555577046",
>             "amount": "5",
>             "modificators": []
>         }
>     ],
>     "expectedDeliverTime": "2019-03-11 20:49",
>     "originName": "orig"
> }

Так как для добавления продуктов возможно только в существующий заказ, то все операции выполняются в двух EditSession.
Среднее время выполнения запроса 2,5сек. Если асинхронно запускать на клиенте выполнение данного метода, то при скорости отправки нового запроса быстрее 1,5сек периодически появляются ошибки:

> Resto.Front.Api.V6.Exceptions.EntityModifiedException: Versioned entity Resto.Front.Api.V6.Data.Orders.DeliveryOrder was modified before actions execution. Expected version: 2520, actual version: 2522.
> Server stack trace: 
>    в Resto.Front.Api.V6.Editors.EditSessionWriter.CheckExistingEntityStub[TFrontEntity](IEntity entity) в i:\\BuildAgent\\work\\master-installer\\dev\\iikoFront.Net\\Resto.Front.Api\\V6\\Editors\\EditSessionWriter.Checks.cs:строка 454
>    в Resto.Front.Api.V6.Editors.Actions.AddOrderProductItem.Resto.Front.Api.V6.Editors.IEditActionBase.CheckEntityStubs(Int32 sessionNumber, Int32 actionIndex) в i:\\BuildAgent\\work\\master-installer\\dev\\iikoFront.Net\\Resto.Front.Api\\V6\\Editors\\Editors.g.cs:строка 622
>    в Resto.Front.Api.V6.Editors.EditSessionWriter.CheckEntitiesStubs() в i:\\BuildAgent\\work\\master-installer\\dev\\iikoFront.Net\\Resto.Front.Api\\V6\\Editors\\Editors.g.cs:строка 9450
>    в Resto.Front.Api.V6.OperationService.SubmitChanges(IUser user, IEditSession editSession) в i:\\BuildAgent\\work\\master-installer\\dev\\iikoFront.Net\\Resto.Front.Api\\V6\\OperationService.cs:строка 1408
>    в Resto.Front.Api.V6.OperationService.Resto.Front.Api.V6.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в i:\\BuildAgent\\work\\master-installer\\dev\\iikoFront.Net\\Resto.Front.Api\\V6\\Operations.g.cs:строка 2160
>    в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> Exception rethrown at [0]: 
>    в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    в Resto.Front.Api.V6.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession)
>    в SMiikoAPI.Controllers.OrdersController.CreateDelivery(AddDelivery orders) в C:\\prj\\SMiikoAPI\\SMiikoAPI\\Controllers\\OrdersController.cs:строка 325

По всей видимости, API не успевает обработать до конца первый заказ, а уже вклинивается новый с ревизией +1.
Я подумал, что можно перевести редактирование в режиме EditSession на PluginContext.Operations, но почему-то здесь доступны не все методы.
_Например, в PluginContext отсутствует аналог editSessionOrder.CreateDeliveryOrder(). Почему так?_
Поэтому данную затею пришлось забросить.
Можно ли полностью перейти с обработки заказа через editSessionOrder на PluginContext?

Подскажите, пожалуйста, возможно ли для методов плагина iikoFront максимально ускорить частоту выполнения и произвести нагрузочное тестирование?

Параметры iikoFront на тестовом терминале:
![image](https://user-images.githubusercontent.com/2853612/56068912-533e3800-5d89-11e9-97ce-52a53d16713f.png)
и на терминале в работающем ресторане:
![image (1)](https://user-images.githubusercontent.com/2853612/56068921-576a5580-5d89-11e9-8d26-c94d85af1f44.png)

**Comment by ierof** [comment]
Чем менее конкретный вопрос, тем больше времени нужно для его анализа. Когда приведен комбайн-метод на >150 строк и факт, что "иногда он не работает", то разобраться очень тяжело. Лучше иметь более узкое описание проблемы.

> По всей видимости, API не успевает обработать до конца первый заказ, а уже вклинивается новый с ревизией +1.
Это вряд ли. Более вероятно, что у клиента есть какие-нибудь автоматики, которые на сразу после создания выполняют какие-либо действия с заказов. Но по имеющимся данным мне тяжело провести диагностику, какая именно у вас проблема. Т.е. тут нужно знать хотя бы одно точное время вашего инцидента и иметь в распоряжении все логи. 

> Например, в PluginContext отсутствует аналог editSessionOrder.CreateDeliveryOrder(). Почему так?

Потому что `CreateDeliveryOrder` атомарно невалидна. Попробуйте в рамках сессии редактирования вызвать только `CreateDeliveryOrder`.
В этом случае вы получите примерно такое `Resto.Front.Api.V6.Exceptions.ConstraintViolationException `
```
Order #1149 (7fd7673f-4e8d-4c76-a989-045508e43ef6) doesn't have guests. Each order must contain at least one guest, which should be added within the same edit session.
   в Resto.Front.Api.V6.Editors.EditSessionWriter.CheckOrderHasGuests(IBaseOrderBuilder order) в D:\git\resto\dev\iikoFront.Net\Resto.Front.Api\V6\Editors\EditSessionWriter.Checks.cs:строка 207
   в System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   в Resto.Front.Api.V6.Editors.EditSessionWriter.CheckOrdersHaveGuests() в D:\git\resto\dev\iikoFront.Net\Resto.Front.Api\V6\Editors\EditSessionWriter.Checks.cs:строка 200
   в Resto.Front.Api.V6.Editors.EditSessionWriter.PostCheckEditSession() в D:\git\resto\dev\iikoFront.Net\Resto.Front.Api\V6\Editors\EditSessionWriter.cs:строка 66
   в Resto.Front.Api.V6.OperationService.SubmitChanges(IUser user, IEditSession editSession) в D:\git\resto\dev\iikoFront.Net\Resto.Front.Api\V6\OperationService.cs:строка 1484
   в Resto.Front.Api.V6.OperationService.Resto.Front.Api.V6.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в D:\git\resto\dev\iikoFront.Net\Resto.Front.Api\V6\Operations.g.cs:строка 2282
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```
В рамках этой же сессии должно быть и добавление гостя: `editSession.AddOrderGuest`
Надеюсь, я ответила на эту часть вопроса.

> Подскажите, пожалуйста, возможно ли для методов плагина iikoFront максимально ускорить частоту выполнения и произвести нагрузочное тестирование?

По такой формировке вопроса: частота выполнения зависит в первую очередь от вашего кода, нежели от iikoFront. Так что увеличивайте частоту запросов.

**Comment by vcpp** [comment]
> Среднее время выполнения запроса 2,5сек.

Не смотрели, во что упирается ваш тест — в процессор, в диск, в сеть?

Полагаю, в CPU. Возьмите в руки профайлер и посмотрите, куда уходят эти 2,5 с, на вызовы каких функций API уходит больше всего времени. Подумайте, обоснованно ли эти функции тормозят. Смотрю опубликованный вами метод создания доставки, и в самом начале вижу:
```
PluginContext.Operations.GetUsers().Last(user => user.Name == "Remote Admin")
```
Вот здесь вы вытягиваете в плагин всех пользователей. `GetUsers()`, очевидно, линейно зависит от количества пользователей, что позволяет получать сколь угодно большое время в бенчмарке, просто подбирая базу с соответствующим количеством пользователей. Поскольку вам нужен один и тот же пользователь для всех заказов, напрашивается вынести его получение из метода создания заказа. Это всё ещё будет вытягивание всех пользователей в плагин, но уже однократное на весь сеанс работы, что не так заметно. Теоретически можно пойти дальше и добавить функцию поиска пользователя по имени (её пока нет, никто не просил), но в вашем сценарии это уже не даст дополнительного прироста скорости создания заказов.

Дальше та же беда:
```
var order = PluginContext.Operations.GetOrders().Last();
```
Квадратичная сложность на ровном месте! Зачем для создания нового заказа вытягивать в плагин полный список всех ранее созданных заказов? Из-за этого чем больше уже создано заказов, тем дольше создаётся каждый следующий заказ. Хуже того, метод `GetOrders()` вызывается для каждого блюда каждого нового заказа. Для создания нового заказа список старых заказов не нужен, избавьтесь от вызовов `GetOrders()`.
Кроме того, вы создаёте пустой заказ, сохраняете его, теряете на него ссылку и затем берёте *случайный* ранее созданный заказ и наполняете его блюдами. Метод `GetOrders()` даже в однопоточном сценарии не гарантирует какого-либо порядка. Неудивительно, что в многопоточном сценарии вы с помощью `GetOrders().Last()` находите заказы, создаваемые в это же время другими потоками, добавляете блюда в случайные чужие заказы и получаете `EntityModifiedException`. Во-первых, `SubmitChanges` возвращает список созданных в сессии объектов, и заказ следовало бы брать оттуда. Во-вторых, минимизируйте промежуточные сохранения, зачем вы сохраняете пустой заказ? Делайте всё атомарно одной транзакцией.

> Так как для добавления продуктов возможно только в существующий заказ, то все операции выполняются в двух EditSession.

Это не так. Начните с изучения SamplePlugin'а из SDK. Берём самый первый класс с примерами [`EditorTester`](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs) (в отличие от остальных, он изначально раскомментирован), берём в нём самый первый пример `CreateOrder`, там создаётся заказ, в него добавляются пара гостей, блюдо, и всё это атомарно сохраняется.

Думаю, идея понятна. Там ещё при добавлении каждого блюда в каждый заказ в плагин вытягивается вся номенклатура и так далее.

Вот для сравнения результаты нашего внутреннего нагрузочного тестирования, создаётся 100 заказов по 20 блюд в каждом, используя каждую поддерживаемую версию API в однопоточном и многопоточном режимах. Результат одного из сценариев для V5 на SSD:
```
single thread:
Min 16,2 ms, Avg 24,5 ms, Max 78,0 ms
Total time: 2452,9 ms (40 iterations per second)

multiple threads:
Min 23,9 ms, Avg 84,4 ms, Max 164,8 ms
Total time: 929,7 ms (107 iterations per second)
```

То же самое на HDD:
```
single thread:
Min 97,8 ms, Avg 135,2 ms, Max 269,4 ms
Total time: 13518,4 ms (7 iterations per second)

multiple threads:
Min 116,8 ms, Avg 1251,3 ms, Max 2935,9 ms
Total time: 12914,9 ms (7 iterations per second)
```

Ориентируйтесь на эти показатели.
