### ISSUE TITLE
Отсутствуют координаты в IDeliveryOrder, созданном через iikoTransport

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#221]
Если создавать доставку на iikoFront, то координаты приходят сразу, это видно на правой части скриншота. А если создавать через iikoTransport, то координат не будет(см. левая часть скриншота) до тех пор, пока сущность не отредактируется через фронт, например, пока не добавится комментарий. В чем может быть дело? Есть ли известные Вам способы обойти это?
Кусок тела запроса:
 ```
"coordinates": 
{
   "latitude": "59.934795",
   "longitude": "30.333041"
},
"deliveryPoint": 
{
   "address":
   {
      "street":
      {
         "city": "СПБ",
         "name":"Невский",
         "house":"44"
      }

```

![image](https://user-images.githubusercontent.com/46530239/112356229-70067880-8cdf-11eb-8ec9-6275272115e9.png)

**Comment by letolica** [comment]
Добрый день. Вопрос передан команде iikoTransport.

**Comment by letolica** [comment]
Завели задачу на исправление. Внутренний номер TRN-1261.

**Comment by letolica** [comment]
Здравствуйте. Исправление должно войти в версию 7.7.3.

**Comment by CLTanuki** [comment]
Спасибо.
