### ISSUE TITLE
Front API V7.  Cannot load “Plugin.Front”, because the file doesn't have special digital signature

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#222]
Добрый вечер.

На API V7 не запускается плагин. Пишет в api.log
[2021-03-30 18:49:01,415]  WARN [12] - Cannot load “Plugin.Front.PluginName”, because the file doesn't have special digital signature

И всё

**Comment by letolica** [comment]
Добрый вечер.
У Вас, как у разработчика плагина, должна быть лицензия разработчика плагинов, чтобы их запускать.

Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Licensing.html):
> Регистрация
Разработчику необходимо зарегистрировать свой плагин как лицензируемый модуль в iiko, а пользователю получить лицензию на использование этого модуля. При регистрации плагину назначается некий идентификатор, целое число, это и будет идентификатором модуля. Это может быть как новый модуль, созданный специально для этого плагина, так и универсальный, используемый для небольших частных доработок. Разработчик привязывает плагин к модулю, указывая его идентификатор с помощью атрибута PluginLicenseModuleId. Пользователю необходимо будет получить лицензию, включающую в себя соответствующий модуль.
Для регистрации, получения лицензии разработчика, получения идентификатора лицензируемого модуля и заключения договора необходимо отправить заявку по адресу api@iiko.ru.

**Comment by igorpooh1978** [comment]
Доброе утро
Лицензия есть.
Разобрался
https://iiko.github.io/front.api.doc/2018/02/16/forced-digital-signatures.html

Если вас не затруднит просто дополните информацию в 
https://iiko.github.io/front.api.doc/v6/ru/Licensing.html

А то получается для того чтобы понять надо весь список изменений лопатить )

В любом случае, спасибо за бытрый ответ
