### ISSUE TITLE
IOrder.Payments получение времени совершения платежной операции.

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#223]
Добрый день. Можно ли каким-то образом поймать время совершения платежной операции?
Плагин не для фискального регистратора, поэтому вопрос, как поймать?
Если делать по OrderChanged, то первая предоплата, также не проявляется в Payments

**Comment by igorpooh1978** [comment]
Коллеги ?

**Comment by vcpp** [comment]
Можно чуть подробнее, что вы хотите сделать?
Возможна куча вариантов: закрытие без оплаты (на нулевую сумму), внешний проведённый платёж (оплата на сайте, например), предоплаты, предварительные оплаты, ...
Вариант через [`ChequeTaskProcessor`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Devices_IChequeTaskProcessor.htm) не пробовали?

**Comment by igorpooh1978** [comment]
Спасибо за подсказку. Попробую.
Пока закрою тикет.
