### ISSUE TITLE
One or more objects used in edit session are already in use

### ISSUE THREAD

**Issue by EmilSimonyan** [iiko/front.api.sdk#224]
In the plugin of iikoFront
I'm having an exception "One or more objects used in edit session are already in use"  while I'm trying to attach a client to the order programatically by using:
var result = PluginContext.Operations.AddClientToOrder(credientials, order, client);
method.

The exception is rising when the [order window](https://user-images.githubusercontent.com/42076521/113890536-4ec08480-97d5-11eb-9df0-f65d0d4a0872.png) in iikoFront is open, if it is not open e.g. in [this window](https://user-images.githubusercontent.com/42076521/113890529-4d8f5780-97d5-11eb-9a09-514752daf7d5.png) I'm successfully attaching the client to the order. 

What can I do to attach the client to the order programatically when the order window is open?
Is there a way to subscribe page navigations events in the iikoFront plugin to manage the work I want to be done?

Feel free to suggest different solutions to attach the client to the order programatically

![1](https://user-images.githubusercontent.com/42076521/113890529-4d8f5780-97d5-11eb-9a09-514752daf7d5.png)
![2](https://user-images.githubusercontent.com/42076521/113890536-4ec08480-97d5-11eb-9df0-f65d0d4a0872.png)

**Comment by CLTanuki** [comment]
Hello.
First, You can use [OrderEditCardSlided](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_OrderEditCardSlided.htm) subscription to add user by card roll.
Or You can use [TryEditCurrentOrder](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_TryEditCurrentOrder.htm) method to try editing current order=)

Both are available in API V7 Preview4.

**Comment by vcpp** [comment]
> Is there a way to subscribe page navigations events in the iikoFront plugin to manage the work I want to be done?

Yep, use [`PluginContext.Notifications.ScreenChanged`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_ScreenChanged.htm).

**Comment by nurillaxoja** [comment]
hello is it possibe to use method AddFlexibleSumDiscount() [in this window.](https://user-images.githubusercontent.com/42076521/113890536-4ec08480-97d5-11eb-9df0-f65d0d4a0872.png) I am getting the same error

**Comment by vcpp** [comment]
> is it possibe to use method AddFlexibleSumDiscount() when opened this window. I am getting the same error. I am calling AddFlexibleSumDiscount() from OnPaymentAdded method

Yes, but instead of global `PluginContext.Operations` you have to use special local instance of `IOperationService` received as a parameter of the [`OnPaymentAdded`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPaymentProcessor_OnPaymentAdded.htm) method.

**Comment by nurillaxoja** [comment]
Please can you share one exmple of using local variable of IOperationService. I have read this on other page to but cannot find example. I have used all examples in github and offical documentation page. 
I have used 
1) PluginContext.Operations.ExecuteContinuousOperation(
                    operations =>  { } });

**Comment by nurillaxoja** [comment]
Thanks it helped but another problem occurred I will try to solve it.
