### ISSUE TITLE
Печать этикеток из плагина

### ISSUE THREAD

**Issue by RomanProtas** [iiko/front.api.sdk#225]
Коллеги, доброго времени суток! 
В настоящий момент мы можем через iiko front api получить доступ к принтеру квитанций через интерфейс IRecieptPrinter. Скажите, есть ли возможность как-то подвязаться к принтеру этикеток из плагина? Или может быть есть способы из плагины инициировать печать того или иного mrt шаблона? 
Чтобы было понятнее о чем идет речь, опишу в двух словах кейс: необходимо для позиций в заказе(некоторых или всех, регулируется пользователем) печатать этикетки, их вид должен зависеть от места приготовления позиции.
Заранее спасибо за ответ!

**Comment by vcpp** [comment]
Пока такой возможности нет.

**Comment by letolica** [comment]
#229

**Comment by rengal** [comment]
Теперь можно распечатать документ на принтере с помощью метода [PluginContext.Operations.Print](https://iiko.github.io/front.api.sdk/v9/html/Overload_Resto_Front_Api_IOperationService_Print.htm)

У методя есть две перегрузки: можно распечатать документ как по id принтера, так и по целевому назначению принтера (например, принтере квитанций)
Пример печати на принтере квитанций:
```
var printer = PluginContext.Operations.TryGetReceiptChequePrinter();
if (printer != null)
{
  var doc = new XElement(Tags.Doc,
    new XElement(Tags.SmallFont, "Hello, world!"));

    PluginContext.Operations.Print(printer, doc);
}
```
