### ISSUE TITLE
InputDialog

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#228]
Добрый день, подскажите есть ли возможность ввода decimal значений в ShowInputDialog ?

**Comment by vcpp** [comment]
Хм, похоже, что нет. Надо будет добавить.
Для чего хотите использовать — денежные суммы, дробное количество порций, что-то ещё? Наверное, какая-то базовая валидация должна быть в самом диалоговом окне.

**Comment by igorpooh1978** [comment]
> Хм, похоже, что нет. Надо будет добавить.
> Для чего хотите использовать — денежные суммы, дробное количество порций, что-то ещё? Наверное, какая-то базовая валидация должна быть в самом диалоговом окне.

В моём случае, потребовался ввод денежной суммы. 
По поводу базовой валидации по моему мнению хватит и контроля кол-ва символов после ,(.)

**Comment by CLTanuki** [comment]
> > Хм, похоже, что нет. Надо будет добавить.
> > Для чего хотите использовать — денежные суммы, дробное количество порций, что-то ещё? Наверное, какая-то базовая валидация должна быть в самом диалоговом окне.
> 
> В моём случае, потребовался ввод денежной суммы.
> По поводу базовой валидации по моему мнению хватит и контроля кол-ва символов после ,(.)

В оплатах мы перешли на использование штатной клавиатуры для ввода суммы, устанавливая min и max для платежа и вычитывая введённую сумму уже в методе Pay. Оказалось едва ли неудобнее в последних версиях.
Впрочем, вероятно, это не в методе оплаты нужно, но где же тогда?

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/v8/ru/ViewManager.html
