### ISSUE TITLE
Лицензия разработчика

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#23]
Здравствуйте!

Мы планируем производить отладку и перезапуск плагина без перезапуска iiko Front (если это возможно).

Интересует следующий момент:
На ресурсе https://iiko.github.io/front.api.doc/v6/ru/Licensing.html / https://iiko.github.io/front.api.doc/v6/ru/Debugging.html написано, что для комфортной разработки плагинов (без перезапуска iikoFront) требуется "лицензия разработчика плагинов".

> Для регистрации, получения лицензии разработчика, получения идентификатора лицензируемого модуля и заключения договора необходимо отправить заявку по адресу api@iiko.ru.  

Какую информацию нам необходимо предоставить для регистрации?
Как полученную лицензию можно применить к нашему плагину?
Понадобится что-то настраивать кроме параметра в коде [PluginLicenseModuleId(21016xxx)] ?
Как нам в таком случае настроить плагин, чтобы производить отладку без перезапуска iikoFront/VisualStudio?

**Comment by rgrigorenko** [comment]
Скорее всего вы будете использовать открытые лицензии api, в зависимости от функционала вам дадут modul id, который вы подставите в свой плагин

**Comment by vcpp** [comment]
> Какую информацию нам необходимо предоставить для регистрации?

Здесь, на github, мы можем оказать помощь только по техническим вопросам. Это место встречи разработчиков по обе стороны API, не универсальная справочная.
С правовыми (заключение договоров) и финансовыми (приобретение лицензий, биллинг) вопросами следует обращаться на api@iiko.ru. К сожалению, на официальном сайте в разделе «[С чего начать](https://ru.iiko.help/articles/#!api-documentations/getting-started)» написана ерунда, мы передадим коллегам просьбу опубликовать понятную последовательность действий. А пока напишите письмо в свободной форме :-)

> Как полученную лицензию можно применить к нашему плагину?

Это не требуется. Лицензия разработчика плагинов не привязана к конкретному плагину.

> Понадобится что-то настраивать кроме параметра в коде [PluginLicenseModuleId(21016xxx)] ?
Как нам в таком случае настроить плагин, чтобы производить отладку без перезапуска iikoFront/VisualStudio?

1. Недокументированное взаимодействие с api@iiko.ru.
2. Получаете дистрибутив iikoRms и лицензию, включающую moduleId вашего плагина и moduleId разработчика плагинов (21009108).
3. В зависимости от первого пункта, устанавливаете сервер iikoRms у себя или получаете облачный хостинг.
4. Устанавливаете приложение iikoFront. Будучи подключенным к серверу iikoRms с вашей лицензией, приложение уже будет знать про возможность отладки плагинов.
5. Открываете свой плагин в Visual Studio и в свойствах проекта указываете параметры отладки, как описано в [статье](https://iiko.github.io/front.api.doc/v6/ru/Debugging.html).
6. Запускаете приложение iikoFront.
7. Запускаете отладку плагина по F5 (Start Debugging). Обычная отладка, с breakpoint'ами и прочим. В любой момент можете остановить отладку плагина по Shift-F5, внести изменения и запустить снова. Приложение iikoFront перезапускать не потребуется.

**Comment by iDoctor** [comment]
> Это место встречи разработчиков по обе стороны API, не универсальная справочная

Я понимаю, что у вас по всей видимости изменилась команда разработчиков, активно модифицируется ПО и корректируется документация, а на GH решаются вопросы технического характера - это всё замечательно. Однако, я 2 недели пытался получить конкретный ответ в переписке с  api@iiko.ru / pyrus_main@iiko.ru, что не увенчалось успехом.
В любом случае, спасибо за пп.1-7

**Comment by rgrigorenko** [comment]
Добрый день.

К сожалению, на официальном сайте в разделе «С чего начать» написана ерунда, мы передадим коллегам просьбу опубликовать понятную последовательность действий. А пока напишите письмо в свободной форме :-)

Как полученную лицензию можно применить к нашему плагину?
Это не требуется. Лицензия разработчика плагинов не привязана к конкретному плагину.

Спасибо что вы написали нам на api@iiko.ru,  поправлю своего коллегу он мне кажется  не понял до конца ваш вопрос и написал не совсем корректно и и подходят чисто с технической стороны.
к сожалению в нашей документации нет многих моментов описывающих разработку плагинов но думаю мы это скоро исправим.

1. Итак прежде чем что то начать писать, я настоятельно вам рекомендую следовать вот этому пункту:
Расскажите о вашем проекте. Мы поможем вам расставить приоритеты и выбрать нужное API. Расскажем о тех направлениях, которые мы считаем наиболее приоритетными.

Это сделано для того, что бы мы могли не только вам помогать с техническими вопросами, как именно написать но и для себя понимать, какие есть потребности на рынке, что беспокоит наших клиентов возможно они не правильно оценивают свой подход, какое api использовать и т.д.

2. После консультации с нами вы определились как писать и что писать далее идет пункт:

В процессе разработки будут появляться вопросы. Еще раз просмотрите документацию, FAQ и примеры опубликованные на сайте. Если вы не нашли ответа задайте вопрос на  api@iiko.ru

Поскольку вы говорите про плагин к iikoFront, то вопросы лучше задавать здесь, наши коллеги квалифицированно ответят на техничнее вопросы. Если у вас вдруг возникли вопросы не по api iikoFront прошу вас писать на api@iiko.ru

3. Вы написали свой плагин и если он является коммерческим воплощением какой то идеи то приходите к нам опять и мы плавно переходим к нашему третьему пункту:

Вы написали свое приложение, а что дальше? Мы предлагаем реализовать свои проекты в нашей партнерской сети. Мы расскажем нашим партнерам о вашем продукте.


Надеюсь у вас все получиться и вы сможете реализовать свои идеи.
Удачи!

**Comment by iDoctor** [comment]
> Однако, я 2 недели пытался получить конкретный ответ в переписке с [api@iiko.ru](mailto:api@iiko.ru) / [pyrus_main@iiko.ru](mailto:pyrus_main@iiko.ru), что не увенчалось успехом.
> 
> Вы можете сказать мне номер тикета техподдержки на который вы уже 2 недели ждете ответ?

17.03 - моё сообщение на api@iiko.ru и pyrus_main@iiko.ru
26.03 - первый ответ ТП

По поводу id тикета затрудняюсь ответить. В переписке было указано "ticket ${Проблема}" и "[#ID-35614751]". Второе скорее всего id сотрудника.
Подробности переписки, полагаю, будет некорректно указывать на GH.
