### ISSUE TITLE
Проверка установленного iikoDelivery или другого плагина

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#230]
Добрый день.

Подскажите, есть ли возможность через iikoFront API узнать, установлен ли например iikoDelivery? У нас есть бизнес кейс, когда у одних клиентов заказы на самовывоз (takeaway) проводятся как обычные заказы на столе, не используя iikoDelivery, и нам интересно, можно ли в автоматическом режиме проверять наличие функционала iikoDelivery (того же IDeliveryOrder) и в зависимости от результата, проводить заказы либо через iikoDelivery, либо как обычные чеки.

Можно также обобщить вопрос на проверку наличия установленных других дополнений.

Заранее спасибо.

**Comment by vcpp** [comment]
Если под дополнениями понимать плагины, то технически iikoDelivery таковым не является, эта функциональность реализована в ядре и включается/выключается через лицензию.
Наличие лицензии на ту или иную функциональность можно проверить с помощью метода [`PluginContext.Licensing.IsEnabled(moduleId)`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_ILicensingService_IsEnabled.htm), надо только знать module id интересующей функциональности. Для доставки это 400.
