### ISSUE TITLE
V7Preview6: Поведение Donation. Status в IOrder при чаевых по картам или внешним ПС.

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#231]
Добрый день
При отмене заказа чаевые в API не переходят в состояние Storned для кар. Это правильное явление ?
Поясню. Делается плагин ФР и при обработке я делаю свой собственные z-отчет.
Соглано вашего отчета всё корректно и чаевые вернулись. А вот у меня из-за того что я проверяю состояние платежа обработать естественно его не смог. Мой вопрос. Корректно ли такое поведение Donations, что оно не переходит в состояние сторнирования
Из отчета iiko
![image](https://user-images.githubusercontent.com/47010778/119323058-f8c17680-bc86-11eb-88ef-85d6543c80b1.png)
В моём отчете естественно этих -10 по чаевым нет
![image](https://user-images.githubusercontent.com/47010778/119323224-24dcf780-bc87-11eb-8911-d20c6c3b8ceb.png)

Состояние Donation (Processed)
![image](https://user-images.githubusercontent.com/47010778/119321057-e6ded400-bc84-11eb-85c1-7fc03eb0f915.png)
Состояние Payment (Storned)
![image](https://user-images.githubusercontent.com/47010778/119321116-f827e080-bc84-11eb-8fb7-fe0f800b6872.png)

**Comment by igorpooh1978** [comment]
Поясню плагин делается для европы, и там свои тонкости с чаевыми

**Comment by letolica** [comment]
Добрый день.
Чаевые при сторнировании не отменяются, как и предоплаты. После сторнирования заказа нужно вызвать отдельный метод [`DeleteDonation`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_DeleteDonation.htm) для каждого айтема в списке чаевых.

**Comment by igorpooh1978** [comment]
Да спасибо за подсказку.
