### ISSUE TITLE
ChequeSale.TaricCode всегда передается как null в реализацию метода ICashRegister.DoCheque([NotNull] ChequeTask chequeTask, IViewManager viewManager)

### ISSUE THREAD

**Issue by qt-user** [iiko/front.api.sdk#232]
Добрый день. 
Версия iiko 7.5.6019.0
В этой версии iiko уже есть печать для блюда на фискальном чеке кода УКТВЭД для Украины (вкладка в iikoOffice "Справочник кодов ТН ВЭД ЕАЭС") через драйвер фискалов Артсофт, при анализе печати на фискальный регистратор видно что в сериализованных объектах ChequeSale которые логируются в devices.log фронта этот код из справочника ТН ВЭД передается как TaricCode, и может использоваться фискалом для печати. Но через API v7 (также проверял v7 preview5) TaricCode всегда null для элементов ChequeSale которые передаются как List в ChequeTask.Sales в метод ICashRegister.DoCheque([NotNull] ChequeTask chequeTask, IViewManager viewManager) при оплате заказа.. Нигде больше этот код в Front API получить не удалось, IProduct тоже не имеет свойства с кодом ТН ВЭД. 
Как я понимаю передачу этого кода через ChequeSale.TaricCode в  FrontSDK не реализовали, возможно добавить?

**Comment by vcpp** [comment]
Да, похоже на баг. Поле добавили, а значение забыли заполнить. Спасибо, поправим и сообщим.

**Comment by qt-user** [comment]
> Да, похоже на баг. Поле добавили, а значение забыли заполнить. Спасибо, поправим и сообщим.

Есть информация когда исправят?

**Comment by vcpp** [comment]
> Есть информация когда исправят?

Будет исправлено в версии iikoRms 7.7 (7.7.6), выпуск которой запланирован на июль.

**Comment by vcpp** [comment]
>> Есть информация когда исправят?
>
> Будет исправлено в версии iikoRms 7.7 (7.7.6), выпуск которой запланирован на июль.

Увы, исправление съехало на следующую версию, 7.8.1.
