### ISSUE TITLE
V7Preview6. Пустые значения в chequeTask.TextAfterCheque и chequeTask.TextBeforeCheque

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#233]
Коллеги, добрый день
В версии V7Preview6 приходят пустые значения для chequeTask.TextAfterCheque и chequeTask.TextBeforeCheque.
Все настроили согласно документа.

https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html
Интерфейс IChequeTaskProcessor
ч.1 
Как добавить в чек дополнительную информацию?

Обращу ваше внимание, что в API V6 данные из этих полей приходили

**Comment by letolica** [comment]
Вижу, что дубликат текущего вопроса уже имеется в нашем внутреннем таск-трекере: SPRT-27005. Нужно больше данных, т.к. проблема не воспроизводится. Давайте продолжим общение по данной проблеме там.
