### ISSUE TITLE
Оплата через api Типом оплаты External

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#234]
Добрый день. Подскажите как можно реализовать оплату типом оплаты  **PaymentTypeKind.External**  
На версии `7.3.6` Работал **PluginContext.Operations.PayOrderAndPayOutOnUser**
После обновления на` 7.6.7` стало выдавать ошибку 
`"Using payment type Банковская карта (cb0ac227-a559-4258-b743-88f6315d3555) is disabled for remote payment."`

Как можно решить данную проблему ?

**Comment by CLTanuki** [comment]
Добрый день.
Попробуйте метод `AddExternalPaymentItem` у `[IOperationService](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_IOperationService.htm)`. Необходимо учитывать, что для такого метод `CanPaySilently` у `IExternalPaymentProcessor` добавляемого типа должен возвращать `true`,

**Comment by Kamaew** [comment]
Теперь выдает . `Payment item of type Банковская карта cb0ac227-a559-4258-b743-88f6315d3555 cannot be added as external processed. PaymentType should be CanBeExternalProcessed.`

Но у этого типа оплаты я никак не поставлю "Может приниматься извне"  Так как это оплата внешняя и данные параметры просто серые в офисе. 
![2021-06-01_11-42-50](https://user-images.githubusercontent.com/17568251/120272264-95f75d00-c2ce-11eb-9c12-76b730dbc711.jpg)

при этом ранее **PluginContext.Operations.PayOrderAndPayOutOnUser** такой проблемы не имел.

**Comment by CLTanuki** [comment]
Да, мы тоже пользовались методом PayOutOnUser.
Однако, теперь используем `AddExternalPaymentItem` и `ProcessPrepay` сразу за ним. Работает с API V6 на всех версиях до 7.7.1 включительно.
```cs
var paymentItem = Operations.AddExternalPaymentItem(paymentItemSum, false, additionalData, paymentType, submittedOrder, _credentials);

Operations.ProcessPrepay(_credentials, submittedOrder, paymentItem);
```

**Comment by Kamaew** [comment]
Ну да,  послав **isProcessed = false** получил `Cannot process external payment item that is not processed externally and doesn't support silent processing.`

но видимо Сберовская интеграция не является тихой...

**Comment by Kamaew** [comment]
Есть еще варианты решения ?

**Comment by letolica** [comment]
Если тип оплаты внешний плагинный, то единственный вариант закрыть заказ из апи с таким типом — это поддержка этим типом тихой оплаты. Тихая оплата подразумевает отсутствие взаимодействия с пользователем на фронте, чтобы работающему на фронте официанту с одним заказом в произвольное время не выплыл попап с подтверждением действия оплаты совершенно другого заказа. Если же внешний плагинный тип оплаты не поддерживает тихую оплату, то единственный способ закрыть заказ с таким типом — это закрыть его с экрана кассы фронта.

Метод [`PayOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrder.htm) начиная с версии 7.4.6 стал поддерживать закрытие заказа с внешними плагинными тихими типами наравне с [`ProcessPrepay`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_ProcessPrepay.htm). Вот новость об этом: https://iiko.github.io/front.api.doc/2020/11/09/silent-plugin-payments.html

Метод [`PayOrderAndPayOutOnUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrderAndPayOutOnUser.htm) отличается от [`PayOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrder.htm) тем, что им можно оплатить/дооплатить заказ наличными или неинтегрированными банковскими картами. При этом в случае оплаты/дооплаты наличными, сумма этих наличных запишется как задолженность официанта. В случае дооплаты этим методом в заказе уже могут быть либо проведенные оплаты, либо непроведенные оплаты, поддерживающие тихую оплату (в том числе внешние плагинные типы).

**Comment by letolica** [comment]
К сожалению более детально вернуться и раскрутить проблему удалось только сейчас. Действительно, до версии 7.5.4 в метод [`PayOrderAndPayOutOnUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrderAndPayOutOnUser.htm) можно было передать тип оплаты, не являющийся тихим. Что могло привести к генерации исключения в плагине, если плагин в своем методе [`Pay`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPaymentProcessor_Pay.htm) будет взаимодействовать с UI (показ окна, например `viewManager.ShowOkPopup("Sample", "Oops!");`) Это был баг, которым видимо пользовались как фичей. В 7.5.4 (RMS-51806) мы это исправили. Правильным решением будет в плагине, тип оплаты которого вы используете, реализовать метод [`PaySilently`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPaymentProcessor_PaySilently.htm) и [`CanPaySilently`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPaymentProcessor_CanPaySilently.htm), подробнее в [`документации`](http://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html), раздел _"Тихое проведение оплаты (Silent-оплата)"_.
Типы оплат, которые можно передавать в метод [`PayOrderAndPayOutOnUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrderAndPayOutOnUser.htm), можно получить, вызвав [`GetPaymentTypesToPayOutOnUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetPaymentTypesToPayOutOnUser.htm).

**Comment by novg** [comment]
Здравствуйте.
IIKO Front v 7.9, плагин SDK Resto.Front.Api.V7
Реализовал оплату следующим образом:
`var additionalData = new ExternalPaymentItemAdditionalData
            {
                CustomData = Serializer.Serialize(new PaymentAdditionalData { SilentPay = true })
            };

            PluginContext.Operations.AddExternalPaymentItem(
                order.ResultSum,
                false,
                additionalData,
                null,
                paymentType,
                order,
                _credentials);


            order = PluginContext.Operations.GetOrderById(order.Id);
            // Закрытие заказа существующими оплатами
            PluginContext.Operations.PayOrder(_credentials, order);`

При вызове метода PluginContext.Operations.AddExternalPaymentItem возникает ошибка:
`Paying order error: System.InvalidCastException: Не удалось привести тип объекта "Resto.Front.Api.Data.Payments.ExternalPaymentItemAdditionalData" к типу "Resto.Front.Api.Data.Payments.IikoCard51PaymentItemAdditionalData".

Server stack trace: 
   в Resto.Front.Api.V7.Extensions.PaymentTypeExtensions.CreatePaymentItem(IPaymentType paymentType, Guid id, IPaymentItemAdditionalData additionalData) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Extensions\PaymentTypeExtensions.cs:строка 121
   в Resto.Front.Api.V7.Editors.Actions.AddExternalPaymentItemWithPredefinedId.Apply(Guid id, Decimal paymentSum, Boolean isProcessed, IPaymentItemAdditionalData additionalData, OrganizationDetailsInfo organizationDetailsInfo, IPaymentType paymentType, IBaseOrderBuilder order, SessionContext context) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Actions\AddExternalPaymentItem.cs:строка 80
   в Resto.Front.Api.V7.Editors.Actions.AddExternalPaymentItem.Resto.Front.Api.V7.Editors.IEditActionBase.WriteChanges(SessionContext context, IDictionary`2 createdEntities, IDictionary`2 actionNumbersToCreatedApiEntities, Int32 i) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Editors.g.cs:строка 3762
   в Resto.Front.Api.V7.Editors.EditSessionWriter.WriteChanges() в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\EditSessionWriter.cs:строка 202
   в Resto.Front.Api.V7.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1963
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2473
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)`
