### ISSUE TITLE
Получение совместимости скидки и типа оплаты

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#237]
Добрый день

Подскажите, как можно получить состояние совместимости моего внешнего типа оплаты и скидки ?
Только не на момент оплаты, а в CollectData?
Заранее спасибо за ответ
![image](https://user-images.githubusercontent.com/47010778/122215441-e3212480-ceb3-11eb-8ed1-3f2bc7b5e091.png)

**Comment by vcpp** [comment]
Хороший вопрос!
К сожалению, пока это недоступно в API.

Опишите, пожалуйста, ваш сценарий. Подумаем, как лучше спроектировать метод проверки совместимости.

**Comment by igorpooh1978** [comment]
Собственного говоря вопрос возник на базе того, что при использовании некоторых скидок клиент не хочет применять нашу внешнюю платежную систему.
Сценарий следующий.
У клиента есть автоматические скидки.
При переходе на платежный экран, и выборе нашей ПС первым срабатывает CollectData (оплата ваучерами).  
В состоянии OnPaymentAdded мы уже провели оплату ваучеров и пересчитали заказ
Соответственно когда нажимаем на кнопку Оплатить только тогда  понимаем, что данная ПС не работает с указанной скидкой.
И дабы понимать что скидка не может взаимодействовать нам бы хотелось, чтобы была какая-либо проверка именно в CollectData.

**Comment by vcpp** [comment]
Я вижу здесь две проблемы:
1. В момент выбора типа оплаты iikoFront не проверяет совместимость с имеющимися скидками. Понятно, что на момент добавления типа оплаты скидки могло ещё не быть, она разными путями могла добавиться позже, для этого редкого случая придётся оставить проверку при нажатии «Оплатить». Однако, если при выборе типа оплаты сразу очевидно, что оплатить не удастся, лучше сразу об этом сказать и не дать выбрать несовместимый тип оплаты. Это, будем считать, вопрос удобства, usability.
2. Вы зачем-то проводите оплату сразу после добавления платежа в заказ (`OnPaymentAdded`). Оплату следует проводить в методе `Pay`. Пользователь может добавить платёж и затем удалить его. Или добавить платёж и, не нажимая «Оплатить», перейти на другой экран или выключить терминал. Или даже нажать «Оплатить», но операция может быть прервана по другим причинам, не связанным с совместимостью со скидками. Не стоит полагаться на то, что после `OnPaymentAdded` заказ непременно будет оплачен.
