### ISSUE TITLE
Скидка на позиции в заказе.

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#238]
Добрый день! Используем SDK V7Preview6. Внутри OrderEditBarcodeScanned формируем заказ и добавляем позиции. После добавления позиций - на определенные позиции хотим применить скидку 100% через функционал описанный в хелпе.

/// <summary>
/// Добавление скидки с возможностью выбора блюд.
/// </summary>
private void AddSelectiveDiscount()
{
    var order = PluginContext.Operations.GetOrders().Last();
    var selectedDish = new List<IOrderProductItemStub> { order.Items.OfType<IOrderProductItem>().Last() };
    var discountType = PluginContext.Operations.GetDiscountTypes().Last(x => !x.Deleted && x.IsActive && x.CanApplySelectively);

    var editSession = PluginContext.Operations.CreateEditSession();
    editSession.AddDiscount(discountType, order);
    editSession.ChangeSelectiveDiscount(order, discountType, selectedDish, null, null);
    PluginContext.Operations.SubmitChanges(PluginContext.Operations.GetCredentials(), editSession);
}

В итоге на  PluginContext.Operations.SubmitChanges получаем -  EntityAlreadyInUseException.

Попробовали вариант с  TryEditCurrentOrder  - колбэк не срабатывает.

Вкратце задача в следующем - отсканировать клиента - пробросить в нашу лояльность(без чейна) получить подарочные блюда и добавить их в корзину со 100% скидкой. Вариант с 0 ценой не подходит так как потом начинаются проблемы при выгрузке. Какие варианты возможны?

Где можно получить примеры на  SDK V7Preview в доках примеры только на  SDK V6.
Заранее спасибо!!!

**Comment by MiAlLevin** [comment]
в [документации](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html) так же указано 
_Во входящее в SamplePlugin окно EditorTester, где собраны примеры редактирования заказа, добавлена галочка «Apply changes to order that is opened in iikoFront», при её включении изменения применяются к текущему открытому на экране заказу._
Однако в сдк данной информации нет.

**Comment by vcpp** [comment]
> ```cs
PluginContext.Operations.CreateEditSession();
PluginContext.Operations.SubmitChanges
```

Обработчик уведомления [`OrderEditBarcodeScanned`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_OrderEditBarcodeScanned.htm) получает на вход специальный экземпляр `IOperationService`, используйте его вместо `PluginContext.Operations` для редактирования текущего заказа.

> в [документации](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html) так же указано
> ...
> Однако в сдк данной информации нет.

Информация по ссылке относится к версиям API начиная с V7Preview5, а SDK у нас опубликован только для V5 и V6. Спасибо, что обратили внимание, добавим SDK для V7PreviewX тоже.

**Comment by vcpp** [comment]
> добавим SDK для V7PreviewX тоже

[Готово](https://github.com/iiko/front.api.sdk/tree/master/sample/v7preview6).
В частности, пример добавления в заказ блюда по штрихкоду [здесь](https://github.com/iiko/front.api.sdk/blob/master/sample/v7preview6/Resto.Front.Api.SamplePlugin/Screens/OrderEditScreen.cs).
