### ISSUE TITLE
Отправка заказа в цеха приготовления

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#239]
Добрый день. При интеграции с внешним сервисом создаем заказ по стандартной схеме через `EditSession`. Однако в таком случае заказ не отправляется автоматически (бегунки) в цеха приготовления. Клиент говорит что нужно открыть окно заказа, закрыть его и тогда бегунки отправляються. Бизнес кейс таков, что на момент получения заказа из внешнего сервиса, он уже был принят персоналом и должен быть сразу отправлен на приготовление.

Есть ли возможность повторить это действие автоматически из iikoFront? В API Reference (v6) не нашли такого метода, есть только интерфейсы и методы для чтения `IKitchenOrder`. Если нет, то может можно как-то настроить что-то iikoOffice для этого?

Заранее спасибо.

**Comment by CLTanuki** [comment]
Добрый день.
Рекомендую использовать метод [StartProductsCooking](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_StartProductsCooking.htm).
Передав туда список продуктов заказа IOrderRootItem as IOrderCookingItem, можно отправить все в готовку. Также необходимо проверять их статус перед отправкой - он должен быть PrintedNotCooking.

**Comment by MrOnlineCoder** [comment]
@CLTanuki благодраю за ответ! Подскажите пожалуйста еще пару моментов:
1. Перед выполнением данного метода нужно отправить на печать содержимое заказа?
2. В чем отличие от [StartCourseCooking](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_StartCourseCooking.htm) ?
3. Список IOrderRootItem можно получить только через ISubmittedEntties:Get после создания заказа через EditSession, т.е. это можно ли получить список продуктов заказа имея только IOrder "на руках"? Метода по типу GetOrderItems не нашли)
Спасибо!

**Comment by CLTanuki** [comment]
1. Да. По-крайней мере, мы так делаем в V6.
2. Чтобы готовить курс нужно, чтобы этот курс был явно простален у всех блюд. Технически это вроде как ярлык для массовой отправки.
3. IOrder.Items даст Вам необходимый результат.

**Comment by MrOnlineCoder** [comment]
@CLTanuki 

> IOrder.Items даст Вам необходимый результат.

ответ был перед носом, спасибо))

И с Вашего позволения последний вопрос: если заказ уже таким макаром был отправлен на печать и готовку, потом в заказ добавили еще товары, то просто отпраляем на печать а потом на готовку новые товары? Сейчас просто получаем ошибку "Cooking of one or more products already started. Cannot start cooking twice.", при первоначальном создании, хотя заказ всего один.

**Comment by CLTanuki** [comment]
> И с Вашего позволения последний вопрос: если заказ уже таким макаром был отправлен на печать и готовку, потом в заказ добавили еще товары, то просто отпраляем на печать а потом на готовку новые товары?

Да.
