### ISSUE TITLE
Передача изображений блюд через API iikoFront

### ISSUE THREAD

**Issue by Lexx8000** [iiko/front.api.sdk#24]
Добрый день!
Не нашел методов передачи изображений блюд в API iikoFront. Планируется их реализация? Как сейчас это реализовать?

**Comment by ierof** [comment]
Это планируется выпустить в API V6 (V6 Preview 5, которое выйдет вместе с iiko 6.4)
Внутренняя задача на это : RMS-37961, она уже в тестировании.
