### ISSUE TITLE
Динамически подгружать зависимые библиотеки

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#240]
Добрый день. Подскажите можно ли как то динамически подгружать зависимые библиотеки ?

Есть проект https://github.com/Kamaew/ExampleLibraryVersioning

Который реализует плагин для продукта iiko 
У продукта iiko есть библиотека "Resto.Front.Api.V7.dll"  и она разных версий в проекте для примера 7.3 и 7.6 .

Мой плагин делай 2 вещи. Добавляет кнопку и ловит событие оплаты заказа. 

В каждой из версии api iiko эти действия делаются по разному. И мне приходиться под каждую версию вести ветку и параллельно код в них. Это сильно усложняет разработку так как версий уже довольно таки приличное количество.  

И вот собственно подходя к вопросу. Можно ли как то сделать ветку одну? чтобы по какому то условия плагин сам понимал что нужно подгрузить ту или или иную Resto.Front.Api.V7.dll и брал метод под него для реализации из него?

**Comment by CLTanuki** [comment]
Добрый день.
До выхода стабильной версии API V7 настоятельно рекомендуется использовать API V6, так как V6 стабильна и не меняется.

**Comment by vcpp** [comment]
Думаю, лучше всего начать с прочтения статьи об [управлении версиями](https://iiko.github.io/front.api.doc/versioning.html).

> У продукта iiko есть библиотека "Resto.Front.Api.V7.dll" и она разных версий в проекте для примера 7.3 и 7.6 .
> Мой плагин делай 2 вещи. Добавляет кнопку и ловит событие оплаты заказа.

И то, и другое в API доступно давным-давно, у вас нет необходимости использовать новейшую версию, находящуюся в разработке. Выше верно рекомендовали — подключите [V6](https://www.nuget.org/packages/Resto.Front.Api.V6/), и одна и та же сборка вашего плагина будет совместима со всеми версиями iikoFront, выпущенными с 2019 до 2023 года.
