### ISSUE TITLE
Не подтверждается доставка  Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.

### ISSUE THREAD

**Issue by shityakov** [iiko/front.api.sdk#241]
При создании заказа необходимо автоматически подтверждать доставку для определенного типа
Событие DeliveryOrderChanged

```
if (order.OrderType.OrderServiceType == OrderServiceTypes.DeliveryByClient) {
                var credentials = PluginContext.Operations.GetCredentials();
                var editSession = PluginContext.Operations.CreateEditSession();
                editSession.ChangeDeliveryConfirmTime(DateTime.Now, deliveryOrder);
                PluginContext.Operations.SubmitChanges(credentials, editSession);
 }
```

Получаю ошибку  Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.  Заказ в это время не открыт во фронте. Как я понимаю нужно что -то по типу TryEditCurrentOrder, но фоном и для доставки

И еще дополнительный вопрос, как я могу отправить доставку в готовку, выполнить то, что происходит при нажатии на кнопку готовить.

**Comment by vcpp** [comment]
> Получаю ошибку `Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.` Заказ в это время не открыт во фронте.

Вероятно, заказ кратковременно занят какой-то фоновой автоматикой или другим плагином (точнее можно определить по логам). Попробуйте повторить попытку через секунду-другую.

> как я могу отправить доставку в готовку, выполнить то, что происходит при нажатии на кнопку готовить.

Так же, как и для обычного заказа — выполнить сервисную печать с помощью метода [`PrintOrderItems`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PrintOrderItems.htm).

Либо можно [настроить](https://ru.iiko.help/articles/iikodelivery-7-7/topic-17/a/h2_9) автоматическую отправку в приготовление:

> Работа с заказами на точке может выполняться в специальном режиме. При этом заказы, которые пора готовить, автоматически переходят из статуса «Ожидает» в статус «Готовится». Печатается сервисный чек. Менеджеру не нужно нажимать кнопку Готовить, чтобы отправить заказ на кухню.
>
> По умолчанию автоматическая отправка выполняется сразу после поступления заказа на точку или при его создании на точке. Момент отправки вычисляется как разница между предполагаемым временем доставки и стандартным временем приготовления. Для доставок курьером и самовывозом установлены разные стандарты времени.
>
> Для включения такого режима предназначена настройка доставки Начинать приготовление заказа: Автоматически. Эта настройка задается на уровне RMS, ее получают все iikoFront в пределах одного RMS. Автоматическая печать выполняется на главной кассе.
