### ISSUE TITLE
iiko 7.7.6020.0 Не удается закрыть кассовую смену на боевом ФР с помощью Front API V7

### ISSUE THREAD

**Issue by onestepchik** [iiko/front.api.sdk#242]
Коллеги, подскажите пожалуйста, что мы не так делаем?

Закрываем кассовую смену на боевом ФР
var cred = PluginContext.Operations.AuthenticateByPin(request.Pin);
PluginContext.Operations.CloseCafeSession(cred);
PluginContext.Operations.ClosePersonalSession(cred);

Если персональная смена открыта, то при вызове метода PluginContext.Operations.CloseCafeSession мы получаем ошибку (Требует закрыть персональную смену насколько я понял)
<img width="201" alt="Снимок экрана 2021-07-09 в 09 54 11" src="https://user-images.githubusercontent.com/85111425/125046491-5c203000-e09e-11eb-8849-81e54643bd21.png">

А если сначала закрыть персональную смену ClosePersonalSession, а потом вызвать закрытие кассовой смены CloseCafeSession, то получаем ошибку (Для закрытия смены требуется открытая персональная смена, kiosk это имя учетки)
<img width="212" alt="Снимок экрана 2021-07-09 в 09 56 12" src="https://user-images.githubusercontent.com/85111425/125046715-91c51900-e09e-11eb-9d7f-f129b38de0ef.png">

Открытие кассовой смены работает корректно. А вот закрытие смены не удается победить. Ждем подсказки ;)

**Comment by onestepchik** [comment]
Настройки раздела "Кассовые смены" в бекофисе.
<img width="755" alt="Снимок экрана 2021-07-09 в 10 24 54" src="https://user-images.githubusercontent.com/85111425/125048068-d8674300-e09f-11eb-85f9-17ca1b228223.png">

**Comment by onestepchik** [comment]
АТОЛ 30Ф ДТО 10 (Подключен как внешний фискальный регистратор, через плагин)

**Comment by onestepchik** [comment]
Коллеги, все получилось, нужно было поставить учетке, под которой мы через API открываем/закрываем смену поставить галку "Только для плагинов". В таком случае можно оставить опцию в настройках ТП "Закрывать личные смены" при закрытии кассовой смены.

**Comment by dsshubin** [comment]
В версии 7.7 сделали доработку RMS-52348, чтобы можно было закрывать и на реальных ФР. Там убрали только одну проверку, остальные остались. В данном случае проблема была в том, что это был обычный "человеческий" пользователь, а для него требуется открытая личная смена.
