### ISSUE TITLE
Нет возможности отправить доставку с внешним курьером(yandex), требует назначить обычного курьера

### ISSUE THREAD

**Issue by shityakov** [iiko/front.api.sdk#243]
Нельзя сделать, т.к требует назначить обычного курьера

PluginContext.Operations.SendDelivery(PluginContext.Operations.AuthenticateByPin("6699"), delivery);

![image](https://user-images.githubusercontent.com/45166225/125613002-13730dbd-1c42-4a57-a776-afdd3f8d9e87.png)

**Comment by igorpooh1978** [comment]
https://iiko.github.io/front.api.doc/2020/08/04/external-courier-services.html
Не то?
