### ISSUE TITLE
Служебные поля в заказе

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#244]
Добрый день! 
Есть ли возможность каким либо образом кроме как в поле комментарий в окне редактирования заказа добавлять служебную информацию в элемент заказа.

**Comment by MiAlLevin** [comment]
Используем SDK V7Preview6. Внутри OrderEditBarcodeScanned формируем заказ и добавляем позиции.

**Comment by igorpooh1978** [comment]
Перейдите на v7p7
https://iiko.github.io/front.api.doc/2021/06/17/comment-and-public-external-data.html
Там появились новые плюшки

**Comment by MiAlLevin** [comment]
Спасибо!

**Comment by vcpp** [comment]
@igorpooh1978, спасибо за поддержку :-)

**Comment by kolan72** [comment]
Добрый день,

Можно ли ожидать в более поздних версиях SDK подобного подхода, но уже по отношению к позициям заказа?
Т.е. что-то вроде метода AddOrder**Item**ExternalData(...)?

**Comment by vcpp** [comment]
> Можно ли ожидать в более поздних версиях SDK подобного подхода, но только уже по отношению к позициям заказа?
> Т.е. что-то вроде метода AddOrderItemExternalData(...)?

Пока таких планов не было, но если расскажете, для чего это нужно — подумаем. Могу предположить, что если хранить относящиеся к позициям данные в `AddOrderExternalData`, то неудобно будет следить за переносом позиций в другой заказ, чтобы переносить и данные этих позиций?

**Comment by kolan72** [comment]
Мы пишем в комментарий к позиции заказа некоторую идентифицирующую данный продукт в нашей CRM информацию. Проблема в том, что ограничить изменение комментария пользователем мы не можем (или не знаем как :)).

И кроме того, конечно, в текущем подходе  c `AddOrderExternalData `гораздо сложнее технически отслеживать изменение состояния позиции заказа, чем если бы сторонняя информация была привязана к самой этой позиции.

**Comment by darktwister1337** [comment]
Не подскажите, может кто разобрался...

Вопрос следующий: разрабатываем систему лояльности и было бы неплохо записать в заказ служебное поле (номер карты клиента (card_number), например)

В документации был найден метод `AddOrderExternalData()`, который, по идее, должен добавлять к заказу любое кастомное поле, которое потом можно отслеживать. 

Имею подписку на изменение заказа, в частности, закрытие заказа (Status = 2), 

` PluginContext.Notifications.OrderChanged.Subscribe(x => {});`
Но объект IOrder почему-то не содержит поле, которое было добавлено к этому заказу по ходу его ведения через `AddOrderExternalData()`

И отсюда встает вопрос, каким образом можно вытащить эту External информацию...

**Comment by igorpooh1978** [comment]
Вам совершенно не мешает контролировать состояние позиции самостоятельно через БД
Копайте в сторону https://stackoverflow.com/questions/5636438/difference-between-two-lists

**Comment by kolan72** [comment]
Уважаемый  igorpooh1978,
Вопрос и предложение касались непосредственно Iiko Api. Вы же указываете направления, совершенно тривиальные в данном контексте,  в которых к тому же было копано-перекопано многократно  и до Вашего бесценного комментария.

**Comment by darktwister1337** [comment]
@kolan72, это скорее всего ответ был мне, я писал комментарий, разобрался и удалил его)
Но, видимо, ответ на мой вопрос был написан через почту, отчего актуальность ответа немного снизилась

**Comment by kolan72** [comment]
Удалил свой комментарий ввиду большой вероятности именно такого развития событий.
