### ISSUE TITLE
Как вызвать то окно, которое появляется при добавлении даты рождения клиента

### ISSUE THREAD

**Issue by zelyagreen** [iiko/front.api.sdk#245]
![image](https://user-images.githubusercontent.com/65764357/125639740-2a0b76bb-fb73-442a-87ed-b072c30319f6.png)

**Comment by zelyagreen** [comment]
Интересует реализация в api.v6

**Comment by igorpooh1978** [comment]
День добрый
Никак (
Рисовать самостоятельно или через ShowKeyboard

**Comment by shityakov** [comment]
Добрый день, можете пожалуйста ответить на мой вопрос, нам это очень важно https://github.com/iiko/front.api.sdk/issues/243

**Comment by vcpp** [comment]
Увы, в API V6 нет возможности показать это окно. Добавим в V7.

Внутренний номер задачи: RMS-52840.

**Comment by vcpp** [comment]
> Добавим в V7.

[Добавили](https://iiko.github.io/front.api.doc/v7/ru/DateTimePopups.html).
