### ISSUE TITLE
DiscountItem: получение дополнительных данных

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#246]
Добрый день.

Для внешней платежной системы необходимо получить данные по используемым скидкам.
Подскажите есть ли расширение (какая процентная ставка или сумма скидки) получаемых данных из GetDiscountTypeById ?

**Comment by vcpp** [comment]
Короткий ответ — нет.

Во-первых, у встроенной в iikoRMS дисконтной системы помимо процентной ставки или суммы скидки есть ещё множество настроек и правил применения. Там нетривиальная логика, куча нюансов. Мы не публикуем в API детальные настройки скидок и не пытаемся описать в документации алгоритм их применения, потому что практически нереально будет в плагине корректно продублировать реализованную в iikoFront логику. Кроме того, эта логика постоянно меняется вместе с доработками дисконтной системы. Боюсь, что попытки вычислять скидки по исходным данным в плагине обречены на провал — у плагина будет получаться одно, а у iikoFront другое.

Во-вторых, есть внешние системы лояльности — iikoCard, например. Для нас это в чистом виде чёрный ящик — приложение iikoFront отправляет туда заказ и в ответ получает готовые посчитанные скидки.

Расскажите подробнее, какую задачу вы решаете.
Возможно, вам и не надо знать, как именно считаются скидки и достаточно будет результата применения ([`GetOrderAppliedDiscounts`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetOrderAppliedDiscounts.htm).

Кстати, несколько лет назад был похожий запрос #93.

**Comment by igorpooh1978** [comment]
Да спасибо. Это подойдёт
