### ISSUE TITLE
Информация по блюдам в Стоп-листе

### ISSUE THREAD

**Issue by unitexit** [iiko/front.api.sdk#248]
Подскажите пожалуйста, есть ли метод в API, который позволяет получить список блюд, находящихся в стоп-листе. Заранее спасибо!

**Comment by igorpooh1978** [comment]
Добрый вечер,
Не поможет?
https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetProductsRemainingAmounts.htm

**Comment by unitexit** [comment]
Спасибо большое!
