### ISSUE TITLE
Реализация бонусной системы

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#25]
День добрый, подскажите как лучше по API реализовать внешнюю бонусную систему?
По апи внешней системы мы можем следующее 
-  по номеру карты узнать баланс бонусов
-  по составу заказа узнать сколько бонусов можно списать в данном заказе
-  оплата заказа с картой (с бонусами или без)
-  отмена  заказа с картой

У нас есть опыт работы в пеймент плагинами но мы столкнулись со следующими ограничениями
- карту нужно привязывать дважды при разделении заказа на несколько ФР
- работать с картой можно только на кассовом терминале
- нет интерфейса для просмотра уже привязанной карты к заказу
- Если заказ например на 1000 р и баланс бонусов 1000р, как ограничить сумму оплаты бонусами , например не более 300 р

**Comment by rgrigorenko** [comment]
Коллеги добрый день
Напишите мне на rgrigorenko@iiko.ru свой телефон или скайп пообщаемся.

**Comment by rgalk** [comment]
Чтобы реализовать внешнюю бонусную систему потребуется:
- создать плагин, который реализует интерфейс `IExternalPaymentProcessor` и регистрирует свой тип оплаты (https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html), в настройках BackOffice указать галочку "Проводить как скидку"
-  реализовать методы `CollectData` - для сбора данных (напр. прокатка бонусной карты, номер телефона), `OnPaymentAdded` - для изменения и/или ограничения нижней и верхней границы  и/или суммы добавляемого элемента оплаты (https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_ChangePaymentItemSum.htm)
-  реализовать методы `Pay` и `Return`, в которых будет осуществляться обмен данными с системой для списания/начисления бонусов при нажатии кнопки "Оплатить" на экране кассы iikoFront.

Для решения проблемы разделение заказа на несколько ФР: можно использовать подписку на событие `SubscribeOnOrderSplitByCashRegisters` (https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_NotificationServiceExtensions_SubscribeOnOrderSplitByCashRegisters.htm) и, например, запоминать заказы в собственном хранилище.
Для отображения диалоговых окон, в которых указывать наличие/отсутствие бонусов, можно пользоваться методами объекта `IViewManager` (https://iiko.github.io/front.api.sdk/v6/html/Methods_T_Resto_Front_Api_V6_UI_IViewManager.htm, https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html).

**Comment by ROSimulin** [comment]
реализовать методы Pay и Return, в которых будет осуществляться обмен данными с системой для списания/начисления бонусов при нажатии кнопки "Оплатить" на экране кассы iikoFront.
- методы не вызываются если требуется только начисление бонусов (сумма по типу оплаты 0)
Для отображения диалоговых окон, в которых указывать наличие/отсутствие бонусов, можно пользоваться методами объекта IViewManager
- на win 10 окна западают,опять же, если я перешёл на экран кассы дополнительное окно всего лишь для текста " К заказу привязана карта "номер""  не лучший выход
- стандартный пеймент плагин не позволяет работать с картой на офф станции.

**Comment by rgalk** [comment]
>методы не вызываются если требуется только начисление бонусов (сумма по типу оплаты 0)

Расскажите, пожалуйста, поподробнее. Каким образом вы хотите начислять бонусы, в какой момент времени?
>на win 10 окна западают

Что значит западают?
> опять же, если я перешёл на экран кассы дополнительное окно всего лишь для текста " К заказу привязана карта "номер"" не лучший выход

Если это не то, что требуется, опять же, расскажите поподробнее.
>стандартный пеймент плагин не позволяет работать с картой на офф станции

Для того чтобы выполнять оплатные действия, требуется кассовая смена. Открытие кассовой смены на официантских станциях не предполагается.

**Comment by vcpp** [comment]
Будем считать, что время ожидания ответов на наши вопросы истекло. Если у вас остался интерес к реализации бонусной системы, можно будет возобновить диалог, ответив на вопросы из предыдущего комментария.

**Comment by ROSimulin** [comment]
День добрый, да предыдущие вопросы не актуальны, появились новые
В Бэк офисе в олап отчёте о продажа есть поля
"Тип бонуса" "Номер бонусной карты" "Сумма бонуса", как их можно заполнять по api?

**Comment by vcpp** [comment]
Будет удобнее, если отдельные вопросы будут обсуждаться в отдельных задачах (issue) :-)

Узкая тема, как можно более конкретный вопрос, ответ — хорошо.
Всеобъемлющий заголовок и потенциально бесконечная переписка по широкому кругу вопросов — плохо.

**Comment by ROSimulin** [comment]
Хорошо, если можно тогда эти вопросы тут, остальные, если будут сделаю в отдельных задачах?

**Comment by vcpp** [comment]
> В Бэк офисе в олап отчёте о продажа есть поля
"Тип бонуса" "Номер бонусной карты" "Сумма бонуса", как их можно заполнять по api?

Данные поля относятся к бонусным элементам заказа, эта функциональность пока недоступна через API.

В сущности, это урезанный аналог [`IPaymentItem`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Payments_IPaymentItem.htm). Идея очень простая: в любой момент в открытый заказ добавляется бонусный элемент с указанием тех самых суммы бонуса, типа и прочих полей (по аналогии с [`AddPaymentItem`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_AddPaymentItem.htm), далее при оплате бонус проводится соответствующей бонусной системой (а-ля [`Pay`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IExternalPaymentProcessor_Pay.htm), а в случае возврата оплаты бонус отменяется (а-ля [`ReturnPayment`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IExternalPaymentProcessor_ReturnPayment.htm). Разница лишь в том, что сумма бонуса ни на что не влияет (кроме отображения на экране и в отчётах), она никак не связана с платежами и фискальной подсистемой вообще. Для использования бонусов через API понадобилось бы не только добавлять их в заказ, но и регистрировать бонусную систему, которая где-то во внешнем мире начисляет или отменяет начисление бонусов. Вам такая функциональность нужна?

**Comment by ROSimulin** [comment]
Забавно, клиент показал олап, где это заполнено, в типе оплат была внешняя система.
Че сейчас это заполняется?
 Вам такая функциональность нужна? - да , тогда отпадает необходимости заходить во внешнюю систему для составления отчёта вида сколько выдано/потрачено бонусов клиентами

**Comment by vcpp** [comment]
> в типе оплат была внешняя система.

Тип оплаты — это другое. Вопрос ведь был про поле «Тип бонуса» :-)

> Че сейчас это заполняется?

«Тип бонуса» заполняется встроенными бонусными системами (iikoCard, Malina, Плас-Тек и т. п.).

**Comment by ROSimulin** [comment]
Ок, а в апи когда это планируется добавить? Тип бонуса, бонусная карта и сумма бонуса

**Comment by vcpp** [comment]
Пока не было спроса, не было и планов. Заведу задачку, подумаем, стоит ли это выставлять наружу, в каком виде этим будет удобнее пользоваться, какие там возможны сценарии использования и так далее. Точных сроков нет, но в V6 это уже явно не успеется.
