### ISSUE TITLE
Обновление номенклатуры 

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#251]
Добрый день!
Пишем свой плагин. 
В данный момент всю номенклатуру загружаем при старте плагина методом - GetAllProducts.
В данный момент очень нужен метод или событие в котором мы сможем получать данные по новым продуктам инкрементно. 
Собственно вопрос - можем ли мы из плагина узнать о том что на фронте появились новые блюда? и принудительно вызвать обновление. В идеале загрузить только новую номенклатуру.

**Comment by letolica** [comment]
Добрый день. Можете подписаться на событие [`ProductChanged`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_ProductChanged.htm). Специального метода получения продуктов по ревизии, как это сделано для заказов, к сожалению, пока не предусмотрено.

**Comment by MiAlLevin** [comment]
Спасибо - это по идее то что нужно.
