### ISSUE TITLE
Оплата заказа

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#252]
Коллеги, добрый день!
Плагин используется для проведения внешних тип оплат(собственная бонусная программа).
Помимо возможности проведения внешней оплаты мы дарим гостям некоторые блюда - путем предоставления 100% скидки на них. Учет и списание данных подарков идет через нашу СРМ систему.

После добавления подарочных блюд в заказ и не использования внешнего типа оплаты мы не можем контролировать оплату данного заказа. По сути у нас остается только событие OrderChanged. 
Например мы добавили несколько подарков в заказ со счёта клиента. А кассир выбрав добавленную позицию нажал "Плюс" и увеличил количество подарков на число большее чем есть у клиента.  В этом случае оплата успешно закроется так как все блюда со 100% скидкой и отловить событие оплаты в плагине мы уже не можем, и клиент платит только наличными. А на нашей стороне мы получим отрицательный баланс у клиента.

Вопрос - каким образом мы можем проверить заказ или отменить его оплату в подобных случаях? В какой момент и в каком методе это можно сделать?

Возможно стоит такие события отлавливать в OrderChanged и статусе заказа Bill. Тогда как корректно вызвать отмену заказа? Поскольку, например в статусе closed - генерация exception ни к чему не приводит.

**Comment by vcpp** [comment]
> А кассир выбрав добавленную позицию нажал "Плюс" и увеличил количество подарков на число большее чем есть у клиента.

Менять состав заказ можно только до пречека. При печати пречека состав заказа фиксируется, поэтому логично валидировать состав заказа непосредственно перед пречеком с помощью [`BeforeOrderBill`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeOrderBill.htm). Начиная с V7Preview5 в этом же обработчике [можно](https://iiko.github.io/front.api.doc/2020/12/23/edit-order-before-bill.html) не только отменить операцию, показав сообщение о неправильном количестве подарков, но и продолжить операцию, исправив количество подарков. Смотрите сами, как удобнее — указать кассиру на ошибку, чтобы он сам её исправил, или автоматически выкинуть из заказа лишние подарки в момент печати пречека.

**Comment by MiAlLevin** [comment]
Спасибо, попробуем!
