### ISSUE TITLE
System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток. 

### ISSUE THREAD

**Issue by banforfunr** [iiko/front.api.sdk#253]
Коллеги, добрый день! Столкнулись с проблемой, используем iikov7.6.6

Задача: редактировать заказ после создания через iikoTransport.
Я подписываюсь на создание заказа с помощью DeliveryOrderChanged, при вызове метода PrintOrderItems возникает ошибка:

`Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.`

Пробовал разными способами отсрочить выполнение колбэка: через Thread.Sleep(), Task.Delay(), с помощью методов в System.Reactive Delay() и DelaySubscription(), вызовом долгих операций из другого потока, но в этих случаях возникает ошибка:

`System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток. `

Ошибка возникает на api v7 и привьюшках, на v6 все работает штатно, но там нет необходимых нам методов. Знаете ли вы способ обойти эту проблему?

**Comment by vcpp** [comment]
> `Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.`

В общем случае неизвестно, через сколько времени объект перестанет использоваться кем-то другим. Это зависит от того, кто редактирует объект. Автоматические правки обычно блокируют заказ кратковременно, но если пользователь откроет заказ на экране редактирования, то придётся ждать, пока он выйдет с этого экрана, либо использовать [`TryEditCurrentOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_TryEditCurrentOrder.htm). Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html).

> `System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток. `

Stacktrace в студию :-)

**Comment by banforfunr** [comment]
```
System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток.

Server stack trace: 
   в System.Windows.Threading.Dispatcher.VerifyAccess()
   в Resto.Front.Main.MVC.ViewManager.ShowPopupCore(PopupState state) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.Popups.cs:строка 63
   в Resto.Front.Main.MVC.ViewManager.ShowPopupWithResult[TResult](PopupState`1 state) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.Popups.cs:строка 51
   в Resto.Front.Main.MVC.MessageBox.ShowMessageBox[TResult](IMessageBoxModel`1 model, Nullable`1 canShowAtShutdown) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\MessageBox.cs:строка 301
   в Resto.Front.Main.MVC.MessageBox.Show(String text, String caption, ButtonParams leftButton, ButtonParams middleButton, ButtonParams rightButton, Boolean canShowAtShutdown, Nullable`1 autoCloseTimeout) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\MessageBox.cs:строка 278
   в Resto.Front.Main.MVC.MessageBox.Show(String text, String caption, MessageBoxButtons buttons, Boolean canShowAtShutdown, Nullable`1 autoCloseTimeout) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\MessageBox.cs:строка 44
   в Resto.Front.Main.MVC.MessageBox.ShowYesNo(String message, String title) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\MessageBox.cs:строка 215
   в Resto.Front.Controllers.DeliveryOperationsController.PrintDeliveryStickers(IDeliveryOrder order, ICustomer customer, IReadOnlyCollection`1 productsToPrint, Boolean repeatPrint) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\DeliveryOperationsController.cs:строка 361
   в Resto.Front.Controllers.OrderOperationsController.PrintDeliveryStickersAfterServicePrintIfNeeded(IBaseOrder order, IReadOnlyCollection`1 products, Boolean repeatPrint) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\OrderOperationsController.cs:строка 1727
   в Resto.Front.Controllers.OrderOperationsController.RepeatedPrintInternal(IBaseOrderBuilder orderBuilder, IReadOnlyCollection`1 productsToServicePrint, IReserve reserve, IPermissionChecker permissionChecker) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\OrderOperationsController.cs:строка 1707
   в Resto.Front.Controllers.OrderOperationsController.PrintInternal(IBaseOrderBuilder orderBuilder, IReadOnlyCollection`1 products, IReadOnlyList`1 productAndAmountDifferences, IPermissionChecker permissionChecker, IBackgroundRunner backgroundRunner, ILockedObjectsToken token) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\OrderOperationsController.cs:строка 1608
   в Resto.Front.Controllers.OrderOperationsController.Print(IBaseOrderBuilder orderBuilder, IReadOnlyCollection`1 productsToPrint, IPermissionChecker permissionChecker, ILockedObjectsToken token) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\OrderOperationsController.cs:строка 1582
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.PrintOrderItems(IUser user, IBaseOrderEntity order, IEnumerable`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\OperationServiceInternal.cs:строка 712
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\Operations.g.cs:строка 2460
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7Preview6\OperationsInterfaces.g.cs:строка 4089
   в Resto.Front.Api.BaFoodIntegreation.Observers.OnDeliveryCreated(IDeliveryOrder delivery) в C:\Users\admin\Desktop\ds\iikoPlugin\Resto.Front.Api.iikoPlugin\Observers.cs:строка 54
```

**Comment by banforfunr** [comment]
```
Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.

Server stack trace: 
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.CheckLock(ILockHolder lockHolder) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\OperationServiceInternal.cs:строка 507
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.PrintOrderItems(IUser user, IBaseOrderEntity order, IEnumerable`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\OperationServiceInternal.cs:строка 700
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\Operations.g.cs:строка 2460
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PrintOrderItems(ICredentials credentials, IOrder order, IReadOnlyList`1 orderItems) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7Preview6\OperationsInterfaces.g.cs:строка 4089
   в Resto.Front.Api.BaFoodIntegreation.Observers.OnDeliveryCreated(IDeliveryOrder delivery) в C:\Users\admin\Desktop\ds\iikoPlugin\Resto.Front.Api.iikoPlugin\Observers.cs:строка 54
```

**Comment by vcpp** [comment]
> `System.InvalidOperationException: Вызывающий поток не может получить доступ к данному объекту, так как владельцем этого объекта является другой поток.`

Спасибо за подробности, это исключение вызвано ошибкой в нашем коде.

Вы выполняете повторную сервисную печать и, поскольку в настройках доставки указано вместе с сервисными чеками печатать ещё и стикеры, приложение iikoFront пытается уточнить у пользователя, действительно ли он хочет повторно напечатать стикеры. Ошибка в том, что приложение пытается показать на экране вопрос пользователю, хотя операция инициирована плагином и выполняется в фоне. Кстати, в V5, V6 и до V7Preview2 включительно эта ошибка проявлялась иначе — пользователь таки получал на экране неожиданное сообщение с просьбой подтвердить повторную печать стикеров.

Вероятно, первая сервисная печать выполняется автоматически самим приложением iikoFront сразу после создания заказа в соответствии с настройками доставки, поэтому в первые секунды после уведомления о создании вы получаете `EntityAlreadyInUseException`, а когда автоматическая сервисная печать завершится, заказ разблокируется, и вы уже выполняете повторную сервисную печать.

Вряд ли вам нужна повторная сервисная печать, она предусмотрена для особых ситуаций, например, когда на кухне возникла проблема с принтером или потеряли оригиналы чеков. Если плагин будет массово для всех заказов выполнять повторную сервисную печать, куча дубликатов может запутать персонал на кухне. Чтобы избежать повторной сервисной печати, не передавайте в метод `PrintOrderItems` элементы заказа, для которых сервисная печать уже выполнена, это можно определить по наличию значения у свойства [`PrintTime`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderRootItem_PrintTime.htm).

**Временное решение:** (если нужна именно повторная сервисная печать)
До обновления на исправленную версию [в настройках доставки](https://ru.iiko.help/articles/iikodelivery-7-7/topic-152/a/h3__768807509) выберите вариант печатать стикеры при печати накладной (не при печати сервисного чека) или совсем отключите печать стикеров.
