### ISSUE TITLE
Получить значение сдачи при использовании оплаты наличными.

### ISSUE THREAD

**Issue by kolan72** [iiko/front.api.sdk#254]
Для учета заказов, созданных в Iiko, в нашей CRM, мы разработали собственный плагин. 
В плагине в числе прочих атрибутов заказа мы транслируем в CRM его оплаты. Наличие в API отдельного интерфейса -  IPaymentItem - для оплат  очень удобно для нас, поскольку легко маппируется на аналогичный объект в нашей системе.

Проблема возникает при использовании типа оплаты "Оплата наличными" и превышении итоговой суммы заказа. В этом случае Iiko формирует сдачу и выдает диалоговое окно с ней. Однако значение свойства IPaymentItem.Sum, которое мы используем для трансляции соответствующей оплаты в нашу систему, содержит всю внесенную сумму, включая будущую сдачу, что разумеется, нас не устраивает.

Есть ли в API возможность получить значение сдачи или сумму оплаты наличными за вычетом сдачи? Мы уже исследовали свойства заказа, связанные с оплатами, такие как IOrder.ResultSum и другие, но ничего, связанного со сдачей, не нашли.

**Comment by igorpooh1978** [comment]
Добрый вечер.
Тут вам скорее всего все таки придётся заниматься математическими вычислениями и подменять значение на необходимое

**Comment by vcpp** [comment]
> Iiko формирует сдачу и выдает диалоговое окно с ней

На всякий случай дополню, что в зависимости от настроек избыток оплаты можно не только вернуть в виде сдачи, но и направить на [благотворительность или чаевые](https://iiko.github.io/front.api.doc/v6/ru/Donations.html).

> значение свойства IPaymentItem.Sum, которое мы используем для трансляции соответствующей оплаты в нашу систему, содержит всю внесенную сумму, включая будущую сдачу, что разумеется, нас не устраивает.

А вот тут возникает неоднозначность. В общем случае оплат, допускающих сдачу (`[CanDisplayChange](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Payments_IPaymentType_CanDisplayChange.htm) == true`), в заказе может быть несколько, и мы не можем точно сказать, какая часть суммы по каждому типу оплаты покрывает стоимость заказа, а какая — возвращается в виде сдачи. Поскольку для ведения учёта детализация сдачи по типам оплаты не требуется, мы и не задаём кассиру лишних вопросов, считаем, что он сам договорится с покупателем.

Часто в заведениях, ориентированных на туристов, если законодательство позволяет, можно расплачиваться как в местной валюте, так и в евро/долларах/и т. п. А ещё в странах, идущих в еврозону, в переходный период в обращении находятся две валюты — местная и евро. Например, в Чехии оплатить заказ можно комбинация чешской кроны и евро, при этом сдачу кассир может выдать в кронах, в евро, либо комбинацией обеих валют. Мы просто показываем кассиру одну и ту же общую сумму сдачи в каждой валюте, а дальше кассир сам решает, сколько вернуть крон и сколько вернуть евро. В результате мы можем точно сказать, сколько заплатили кронами и сколько евро, но эту информацию никто и не просит.

Пожалуй, мы могли бы публиковать сумму сдачи в API, но вы и сами можете легко её посчитать — надо из суммы всех проведённых оплат (включая предоплаты) вычесть итоговую стоимость заказа (`ResultSum`) и сумму пожертвований (`Donations`). В тривиальном случае, когда в заказе только один тип оплаты допускает сдачу, вся сумма сдачи, очевидно, приходится именно на этот тип оплаты.

**Comment by kolan72** [comment]
Спасибо за ответы.
Мы в общем и планировали вычислять сдачу предложенным образом, но на всякий случай уточняли наличие этого функционала в API. Спасибо, что напомнили про Donations.

В качестве пожелания к работе системы.
Нам требуется скорее точная сумма по каждому виду оплаты, чем дополнительная детализация самой сдачи. 
Поэтому с нашей точки зрения, очень не помешала бы возможность разбивки итоговой сдачи по оплатам, ее допускающим, подобно разбивке по типам валют, как Вы ее описали. Тогда имеющаяся неоднозначность была бы, скорее всего, устранена.

**Comment by vcpp** [comment]
> не помешала бы возможность разбивки итоговой сдачи по оплатам

Так я же написал выше, что автоматически эту разбивку вычислить неоткуда, если только спрашивать у кассира.

**Comment by kolan72** [comment]
Без кассира конечно никуда, и подразумевалась именно ручная , а не автоматическая разбивка. 
Хотя, возможно, это уже дело плагина - при нажатии "Оплатить" кассиру показывать например, форму со списком оплат, допускающих сдачу, с возможностью коррекции их сумм (и опосредованно сдач), 
а пробовать где-нибудь в имплементации метода Pay реализации интерфейса IPaymentProcessor....
