### ISSUE TITLE
V7Preview7 7.7.7009\ TryGetCafeSessionByCashRegister при открытии дня (DoOpenCafeSession) на ФР возвращает null

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#257]
Добрый день
есть код 
```
 var devId = PluginContext.Operations.GetCashRegisterInfoById(deviceId);

            var cafeSession = 
            PluginContext.Operations.TryGetCafeSessionByCashRegister(devId)?.Number ?? 0;
```
Код запрашивается из 2х точек для получения номера смены DoXReport и DoZReport
При открытии смены DoXReport также вызывается и из DoOpenCafeSession
Происходит интересная вещь. Когда идёт вызов напрямую из DoXReport и DoZReport, в этих случаях номер смены возвращается. Когда вызов XReport выполняется из DoOpenSession, то в этом случае TryGetCafeSession возвращает null

**Comment by letolica** [comment]
Добрый день.

> Когда идёт вызов напрямую из DoXReport и DoZReport, в этих случаях номер смены возвращается.

Потому что в этот момент смена есть.

> Когда вызов XReport выполняется из DoOpenSession, то в этом случае TryGetCafeSession возвращает null

Когда управление приходит в `DoOpenSession`, смены еще нет, поэтому `TryGetCafeSessionByCashRegister` возвращает `null`.
