### ISSUE TITLE
Тип обслуживания

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#259]
Добрый день.
МОжно ли как-то узнать через API тип обслуживания ?

**Comment by vcpp** [comment]
Всё не так просто. Если настроен тип обслуживания «Ресторан», вовсе не обязательно, что будут печататься пречеки.

Во-первых, в [настройках отделения](https://ru.iiko.help/articles/iikooffice-7-7/topic-266/a/h2__1316941870) есть галочка, которая прямо так и называется «Разрешить оплату заказа без пречека». Если эта галочка установлена, пречек печатается на усмотрение сотрудника, можно оплачивать заказы без печати пречека:

> При установленной галочке Разрешить оплату заказа без пречека кассир сможет принимать оплату (или предоплату) заказов в iikoFront без печати сервисных и гостевых чеков.

Во-вторых, есть функция [«Быстрый чек»](https://ru.iiko.help/articles/iikofront-7-7/topic-48/a/h2_1882421515) — по сути, временное переключение в фастфудный режим, где в принципе нет кнопки «Пречек» и заказы оплачиваются без пречека независимо от галочки «Разрешить оплату заказа без пречека»:

> Быстрый чек
>
> При работе на терминале в режиме ресторана бармен может быстро ввести заказ, переключившись в режим, похожий на фастфуд. В этом режиме не нужно указывать количество гостей и номер стола. Он сразу же может вернуться к стандартному режиму работы по столам для обслуживания гостя, долго сидящего за стойкой. Эта возможность полезна также для предприятий, работающих со сменой режима обслуживания в течение дня: днем гостей обслуживают через раздачу в режиме «фастфуд», а вечером — официанты в режиме ресторана.

Пожалуй, проще быть готовым сразу ко всем вариантам и смотреть по ситуации:
* Подписаться на событие [`BillChequePrinting`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BillChequePrinting.htm) и добавлять QR-код во все пречеки. Если какой-то заказ оплачивается без пречека, для него данный обработчик не будет вызван.
* В `CollectData`/`OnPaymentAdded` реагировать на все заказы в [статусе](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_Status.htm) `New`, полагая, что для заказов в статусе `Bill` мы уже печатали QR-код в пречеке.
