### ISSUE TITLE
Как узнать цену продукта?

### ISSUE THREAD

**Issue by xwwh** [iiko/front.api.sdk#26]
Добрый день,
Пытаюсь разобраться как можно определить цену продукта

Пока разобрался, что есть специальный метод [PluginContext.Operations.GetPrice](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetPrice.htm)
Но непонятно как определить ценовую категорию, которую нужно передавать одним из параметров. Интересует именно ценовая категория, котороая применяется автоматически при создании заказа, а не назначается вручную.
В документации нашел, что ценовая категория есть у объекта [ITerminalsGroup ](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Organization_ITerminalsGroup_PriceCategory.htm) и есть какой-то метод [PluginContext.Operations.GetHostTerminalsGroup](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetHostTerminalsGroup.htm) без описания, поэтому непонятно что это за ценовая категория и как ее можно использовать.

Насколько я понял ценовая категория зависит от номера стола, на котором создается заказ.
Можете привести пример как получить ценовую категории для заданного стола и для стола по умолчанию (если это фастфуд или когда заказ создается без указания стола)?

**Comment by vcpp** [comment]
> Но непонятно как определить ценовую категорию, которую нужно передавать одним из параметров. 

К сожалению, в текущих версиях API нет такого способа. Сейчас добавили к заказу свойство `PriceCategory`, позволяющее получить действующую для заказа ценовую категорию, это станет доступно в API V6.

> В документации нашел, что ценовая категория есть у объекта ITerminalsGroup и есть какой-то метод PluginContext.Operations.GetHostTerminalsGroup без описания, поэтому непонятно что это за ценовая категория и как ее можно использовать.

Это ценовая категория, которая неявно назначается заказам, находящимся на столах отделения, в котором находится стол по умолчанию. Сколь-нибудь полезно это значение возможно использовать только в режиме обслуживания «Фаст-фуд», потому что там столов в явном виде нет, заказы создаются на столе по умолчанию. Отсутствие документации — беда, боремся с этим, как можем :-)

> Насколько я понял ценовая категория зависит от номера стола, на котором создается заказ.

Ну почти, ценовая категория (далее ЦК) настраивается для отделения ([`RestaurantSection`](https://iiko.github.io/front.api.sdk/v6/html/Properties_T_Resto_Front_Api_V6_Data_Organization_Sections_IRestaurantSection.htm)) и неявно применяется ко всем заказам, находящимся на столах этого отделения. Кроме того, ЦК заказу можно назначить вручную, и тогда будет действовать явно назначенная ЦК. Увы, поддержка этой части функциональности в API появится лишь в V6, можно будет и узнать действующую ЦК, и задать любую выбранную ЦК.

> Можете привести пример как получить ценовую категории для заданного стола и для стола по умолчанию (если это фастфуд или когда заказ создается без указания стола)?

Для произвольного стола пока никак.
Для стола по умолчанию, а также для других столов отделения, в котором находится стол по умолчанию, ЦК можно получить уже найденным вами способом: `PluginContext.Operations.GetHostTerminalsGroup().PriceCategory`.
