### ISSUE TITLE
Проблема хранения настроек устройства ICashRegister

### ISSUE THREAD

**Issue by qt-user** [iiko/front.api.sdk#260]
Добрый день. По моему наблюдению информация о добавленном устройстве плагинного типа (ICashRegister) храниться в entity.sdf. И случаются казусы когда эти настройки "теряются": 
1\ был прецедент когда менялись настройки ГК (установили настройку "Терминал синхронизации" в 776 версии) . На закрытой кассе, все как положено. После сообщения об перезагрузке и перезапуска фронта - устройство уже не запустилось. В офисе отображалось как "Не установлено (удалить)" с возможностью только удалить. Пришлось перенастроить плагинный фр.
2\ Если ES будет поврежден или удален - настройки ICashRegister теряются, старый бекап в таких случаях не развернуть - нет смысла. восстановить xml фал настроек проще. 
3\ еще хуже был прецедент при обновлении с 756 на 776 - после обновления внешние фискальные регистраторы навсегда остановились с информацией "Не установлено (удалить)".. Опять таки перенастройка. Хотя смотрю в соответствующей таблице (базы фронта) сохранилась строка с Resto.CashServer.Data.Entities.CashServerEntities.Device.CashRegisterSettings
видимо ее не достаточно.. 

Возможен пересмотр сохранения настроек в файле? например ExternalDevices.xml?

Не могу также не вспомнить - если при настройке внешнего фискала (ICashRegister) вызов методов Setup и Start происходит больше 15 секунд в iikoOffice выдает ошибку, но на фронте устройство сохраняет, и по логу оно работает). В офисе опять таки девайс красный, не зарегистрирован и "Не установлено (удалить)", приходиться удалять и заново пробовать настроить. Не считаю проблемой то что таймаут 15 секунд, но при таймауте странное поведение. Решить эту проблему однозначно со стороны плагина тоже сложно - плагин запрашивает при первом старте по сети важные для ICashRegister данные, без них старт делать нельзя. А сети и компьютеры у клиентов бывают разные..

**Comment by vcpp** [comment]
Да, хранение настроек плагинного оборудования по недоразумению сделали в локальной базе iikoFront (*entities.sdf*).
Это известная проблема, поправим в одной из следующих версий: RMS-51399.

> Возможен пересмотр сохранения настроек в файле? например ExternalDevices.xml?

Главное — чтобы настройки не пропадали. Как именно достичь этой цели, посмотрим, вероятно, настройки будут храниться в серверной БД (iikoRMS) наравне с другими справочниками, которые можно редактировать в iikoOffice и которые не пропадают при локальной БД iikoFront.
