### ISSUE TITLE
Перестала срабатывать подписка DeliveryOrderChanged из за внешних ошибок

### ISSUE THREAD

**Issue by zhmpng** [iiko/front.api.sdk#261]
Добрый день. У нас есть плагин для автоматического подтверждения доставок, работающий по подписке DeliveryOrderChanged.

Плагин работает на Api V6 версии 7.0.6022.0 опубликованной в NuGet.
Название плагина в логах: BeOpen.Front.Plugin.DeliverConfirm_V1.0

в 9.30 по времени в логах iikoFront нам приходит доставка №492. На данную доставку подписка в плагине не сработала, выдав ошибку в api.log, и после нее в принципе перестала срабатывать.
В api.log в этот момент пишутся ошибки приходящие из плагинов связанных с доставками. Архив со всеми логами прикладываю.
[log.zip](https://github.com/iiko/front.api.sdk/files/7066606/log.zip)

Хотелось получить помощь в разборе данной ситуации и как от подобных падений подписки можно предостеречь себя.

**Comment by vcpp** [comment]
Это уязвимость в iikoFront API и эксплуатирующий эту уязвимость баг в iikoTransport, ваш плагин тут ни при чём.

1. iikoFront API позволяет плагинам задавать id для создаваемых объектов. На примере [`AddOrderProductItem`](https://iiko.github.io/front.api.sdk/v7/html/Overload_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm) можно видеть две перегрузки — у одной нет `Guid id`, там новый id будет сгенерирован автоматически, у другой есть `Guid id`, сюда плагин может передать идентификатор, полученный из внешней системы. Вторая перегрузка кажется удобной для интеграции с внешними источниками заказов, просто используем внутри системы те же id, что во внешней системе, иначе пришлось бы городить маппинг между внешними и внутренними id. Однако, возникает риск, что переданный плагином id не будет глобально уникальным, и тогда баг в отдельно взятом плагине может поломать работу других плагинов и всей системы в целом. Увы, пока лобби «нам так удобно» побеждает, но мы рано или поздно удалим перегрузку, позволяющую плагину указать id создаваемого объекта.
2. Плагин iikoTransport создаёт заказ и добавляет в него блюдо (`IOrderProductItem`) с идентификатором, который уже используется для продукта (`IProduct`). Это баг, это нарушает требование из [описания](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem_1.htm) параметра id: *Unique identifier of the new item in the order. MUST be unique not only for the order, but for the whole system. Therefore it must be taken from some synchronization operation or generated with `Guid.NewGuid()`*.
3. Приложение iikoFront для внутренних целей использует кеш, где объекты разных типов хранятся в общем словаре с доступом по id. Из-за нарушения инварианта о глобальной уникальности идентификаторов кеш вернул `IOrderProductItem` по id от `IProduct`, что привело к `InvalidCastException`.
4. Поскольку данное исключение возникло при конвертации заказа из внутреннего формата в апишный в цепочке генерации события об изменении заказа, то генерация этих событий прекратилась. Это стандартное поведение для Rx, подробнее можно почитать в книжке [«Rx.NET in Action»](https://livebook.manning.com/book/rx-dot-net-in-action/chapter-11/7):
> In the reactive pipeline, errors can happen in these four places:
> * In the observable `Subscribe` method call during subscription
> * In the observable code as it prepares the values to emit after subscription (for example, the observable tries to pull data from an external source that’s disconnected)
> * In operator code (for example, the selector function you provided for the Select operator throws an exception)
> * In the observer’s `OnNext`, `OnCompleted`, and `OnError` functions
>
> For the first three cases, the Rx guidelines state that the observer should be notified of the error via its `OnError` function and the observer subscription will terminate, meaning no more notifications from the observable will be observed by the observer.

Передам информацию о проблеме команде iikoTransport.
В качестве временного решения можно отключить плагин Resto.Front.Api.iikoTransport, но тогда доставки из внешних источников вообще перестанут приходить. Можно попробовать точечно отключить от iikoTransport источник битых заказов, но с этим лучше обратиться в техподдержку.
