### ISSUE TITLE
Событие измененного заказа `PluginContext.Notifications.OrderChanged` не вызывается

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#263]
Написал плагин для iiko 4.5.x с API v5:
```
PluginContext.Notifications
                .OrderChanged
                .Subscribe(order => OnOrderChanged(order));
```

Но данное событие не вызывается вообще. Проверил в логах, плагин работает без проблем за исключением этой проблемы.

**Comment by vcpp** [comment]
> Написал плагин для iiko 4.5.x с API v5

Версия API V5 выпущена вместе с iikoRms 5.4. Таблицу соответствия версий API и версий iikoRMS можно посмотреть [здесь](https://iiko.github.io/front.api.doc/versioning.html).

Для iikoRMS 4.5 лучше использовать стабильную на тот момент версию API V4. Если вы хотите использовать версию V5, которая в iikoRMS 4.5 находилась в разработке и не была зафиксирована, убедитесь, что используете SDK из той же сборки 4.5, что и iikoRMS. Релизная [версия V5 из NuGet](https://www.nuget.org/packages/Resto.Front.Api.V5/) может быть несовместима.
