### ISSUE TITLE
Ошибка  void PayOrder

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#264]
День добрый, важная проблема при вызове метода PayOrder доставочного заказа с уже сохранённой оплатой
Делали стыковку с внешней системой логистики краткая суть- во внешней системе назначают курьера- в айке заказ отправляется
Стоит настройка оплата доставки перед отправкой, проверял как у клиента как на демостенде версии 767 как и 778
Проблематику систематизировал, если в заказе есть внешняя оплата наличными  ( со сдачей ) или кардом 5.
Когда сумма точная или банковской картой- ошибок нет.

Ошибка когда наличные со сдачей

[2021-08-27 13:59:23,386]  INFO [ 8] - Ошибка оплаты доставки: Введенная сумма слишком большая. Дистанционная оплата невозможна. ,
Server stack trace: 
   в Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 951
   в Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 999
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2610
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:строка 4098
   в ItaliRelog.Relog.SyncOrder(IDeliveryOrder iiko, ROrder Rorder)

Если в заказе была оплата кардом 5 то ошибка вида

[2021-09-06 15:00:50,994]  INFO [ 8] - Ошибка PayOrder: В заказе уже есть элементы оплаты. Дистанционная оплата невозможна. ,
Server stack trace: 
   в Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) в I:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1062
   в Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) в I:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1110
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) в I:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2641
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) в I:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:строка 4280
   в ItaliRelog.Relog.SyncOrder(IDeliveryOrder iiko, ROrder Rorder) в Z:\Разработка\Симулин\Итали Релог\ItaliRelog\Relog.cs:строка 569

**Comment by dsshubin** [comment]
@letolica , думаю речь про доработку RMS-50049. Из того, что я знаю - сдача не обрабатывается, не надо добавлять сумму больше. И поддержка iikoCard так же не делалась, не имеет оно silent-режима.

**Comment by ROSimulin** [comment]
Да я тоже так и предположил, но если со сдачей ещё есть обходное решение, например сумму сдачи в комментарий к доставке отправлять, то как быть с кардом 5 ? 
У клиента гость оплачивает бонусами через сайт.
RMS-50049 - это 2 эти вещи?

**Comment by letolica** [comment]
На поддержку оплаты заказа/доставки методом `PayOrder`, в составе которого есть оплата iikoCard, заведена задача RMS-52844. Уведомим здесь, как поправим.

**Comment by dsshubin** [comment]
@ROSimulin , уточните, пожалуйста полный сценарий с использованием iikoCard. Откуда появляется такой заказ, как добавляется оплата iikoCard? Или пример заказа, даже надёжнее всего XML из entities.sdf.

**Comment by ROSimulin** [comment]
По апи транспорта в заказе тип оплаты - кард 5
Проще всего вом через постман создать заказ на стенде в блоке пейментс я так делал

   "payments": [
            {
                "paymentTypeKind": "Cash",
                "sum": 50,
                "paymentTypeId": "09322f46-578a-d210-add7-eec222a08871",
                "isFiscalizedExternally": false
            },
                 {
                "paymentTypeKind": "IikoCard",
                "sum": 50,
                "paymentTypeId": "a2bdcf93-6f44-4353-82f7-434d0f9ee659",
                "paymentAdditionalData": 
                 {
                     "credential": "+79996663322",
            "searchScope": "Phone",
            "type": "IikoCard"
                 }
            }
        ],

**Comment by letolica** [comment]
Добрый день, @pro100roman24!
Проблема уже решена и ждёт релиза версии 7.8.6.
Оплатить заказ типом IikoCard из iikoFront.API можно будет на любой поддерживаемой версии API, важно только, чтобы версия iikoFront была 7.8.6 или новее.

**Comment by letolica** [comment]
[Тип оплаты iikoCard5 стал поддерживать тихую оплату](https://iiko.github.io/front.api.doc/2021/10/29/silent-iikocard5.html).
