### ISSUE TITLE
Возможность узнать на каком блюде выделение в текущем заказе

### ISSUE THREAD

**Issue by qt-user** [iiko/front.api.sdk#265]
Добрый день. Полистал документацию но не нашел что интересует. Есть ли возможность при перехвате события OrderEditBarcodeScanned (или любого другого события редактирования заказа) узнать на каком блюде стоит маркер выделения в UI. Есть необходимость привязывать к выбранному на фронте блюду как комментарий (или внешнее свойство) штрихкод при сканировании. Возможно есть какое-то другое решение?

**Comment by qt-user** [comment]
Дайте пожалуйста ответ

**Comment by vcpp** [comment]
Нет, пока столь тесная интеграция с экраном редактирования не поддерживается. В принципе, опубликовать информацию о выделенном элементе несложно, но надо подумать, что плагины будут с этой информацией делать. Фокус может быть установлен не только на блюдо, но и на гостя, на комбо, на модификатор, на повременную услугу, а ещё можно выделить одновременно несколько элементов. Подумаем.

В качестве альтернативного решения могу предложить показывать диалог [`ShowChooserPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowChooserPopup.htm), где пользователю надо будет выбрать, для какого из блюд он отсканировал штрихкод. Пример такого диалога из [документации](https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html):
![chooser](https://iiko.github.io/front.api.doc/img/viewmanager/chooser.png)

**Comment by qt-user** [comment]
> В качестве альтернативного решения могу предложить показывать диалог [`ShowChooserPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowChooserPopup.htm)

Спасибо за ответ, уже давненько сделал именно такую реализацию.
