### ISSUE TITLE
Автоматическая установка стоп листов на фронте

### ISSUE THREAD

**Issue by CyCJIeHok** [iiko/front.api.sdk#266]
Нужен функционал которым можно на фронте автоматически расставлять стопы в зависимости от остатках товара на складе. Этот функционал как-то можно реализовать?

**Comment by CyCJIeHok** [comment]
походу нельзя =)

**Comment by vcpp** [comment]
Duplicates #159.

Пока не поддерживается. Сделаем в одной из следующих версий, внутренний номер задачи: RMS-52142.

**Comment by andrey-nasonov** [comment]
Добрый день! Начиная с API V8 появилась возможность редактировать стоп-лист, изменения вы можете посмотреть здесь:
http://iiko.github.io/front.api.doc/2023/05/03/stop-list-edit.html
