### ISSUE TITLE
Добавить оплату в текущий заказ

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#267]
Версия iikoFront: 7.7.7009.0

Решается следующая задача: добавить элемент оплаты в заказ после нажатия кнопки "Пречек" или кнопки на экране редактирования заказа.

```csharp
PluginContext.Notifications.BeforeOrderBill.Subscribe(MyPay);

private static void MyPay((IOrder order, IOperationService os, IViewManager vm) x)
{
    var sess = PluginContext.Operations.CreateEditSession();
    var paymentType = PluginContext.Operations.GetPaymentTypes()
        .Last(x => x.Kind == PaymentTypeKind.External && x.Name == "My payment type");
    sess.AddExternalPaymentItem(15m, false, null, null, paymentType, x.order);
    var creds = PluginContext.Operations.GetCredentials();
    PluginContext.Operations.SubmitChanges(creds, sess);  // <- Exception is thrown
}
```

При выполнении отмеченной строки выбрасывается исключение "Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use".

При попытке выполнить те же действия в меню редактирования заказа (`PluginContext.Operations.AddButtonToOrderEditScreen("My Pay", x => MyPay(x))`) результат аналогичный.

По всей видимости, если текущий заказ передаётся в функцию, то он считается "in use".

**Comment by igorpooh1978** [comment]
Смотрите в сторону NavigatingToPaymentScreen

**Comment by igorpooh1978** [comment]
или BillChequePrinting

**Comment by memoryallocator** [comment]
С `BillChequePrinting` всё работает. Спасибо.

**Comment by delta81** [comment]
С `BillChequePrinting` оплата в заказ добавляется, но на пречеке её можно отразить только в _header_ или _footer_.
Как добавить оплату до формирования пречека?

**Comment by letolica** [comment]
> Если использовать кнопку на экране редактирования заказа (AddButtonToOrderEditScreen()), выбрасывается то же исключение.

Попробуйте также `BeforeOrderBill`. [Редактирование заказа перед пречеком](https://iiko.github.io/front.api.doc/2020/12/23/edit-order-before-bill.html).
Используйте `OperationService` из колбека, или тот, который приходит на вход при подписке на уведомление.

**Comment by delta81** [comment]
Спасибо, использование правильного `OperationService` решило проблему.
