### ISSUE TITLE
Удаление типа оплаты при отказе после нажатия кнопки "Оплатить".

### ISSUE THREAD

**Issue by aitkkia** [iiko/front.api.sdk#268]
Добрый день. 
Возник вопрос по логике работы добавления/удаления типа оплаты. 
Вводная:
Добавлен новый тип внешней оплаты.
Описание действий 1- всё работает как надо:
Добавляем нужный тип оплаты и вместе с ним программно добавляем скидку привязанную к этому типу продажи - "operations.AddFlexibleSumDiscount((Decimal)(DiscountRub), paymentType.DiscountType, order, PluginContext.Operations.GetCredentials());". Операции CollectData и OnPaymentAdded проходят без ошибок. Предположим далее кассир по какой-то причине решил удалить этот тип оплаты. Нажимает крестик и подтверждает, что необходимо его удалить - всё проходит без ошибок и при этом удаляется скидка привязанная к этому типу оплаты. 
Описание действий 2- НЕ РАБОТАЕТ:
Добавляем нужный тип оплаты и вместе с ним программно добавляем скидку привязанную к этому типу продажи - "operations.AddFlexibleSumDiscount((Decimal)(DiscountRub), paymentType.DiscountType, order, PluginContext.Operations.GetCredentials());". Операции CollectData и OnPaymentAdded проходят без ошибок. Нажимаем кнопку "оплатить". Во время оплаты API возвращает отмену и для выхода из метода Pay я использую throw new PaymentActionFailedException/PaymentActionFailedException оплата не проходит, добавленный тип оплаты удаляется из добавленных типов оплаты, но скидка при этом не удаляется.

Вопросы:
1. как можно при втором описание, чтобы удалялась скидка. В методе Pay заказ уже не доступен для редактирования.
2. Как отменить операцию по кнопке Оплата и при этом, чтобы добавленный тип оплаты не удалялся?

**Comment by letolica** [comment]
> Как отменить операцию по кнопке Оплата и при этом, чтобы добавленный тип оплаты не удалялся?

Заведена задача на доработку:
RMS-53012 Front.Api: Возможность прервать проведение плагинной оплаты так, чтобы она не удалялась из заказа

**Comment by letolica** [comment]
Добрый день. Сделали задачу.
[Прерывание проведения плагинной оплаты так, чтобы она не удалялась из заказа](https://iiko.github.io/front.api.doc/2024/04/03/cancel-payment-without-deleting.html).

**Comment by letolica** [comment]
Добрый день. Сделали RMS-51932 (_Front.Api: Возможность редактировать заказ, открытый на экране оплаты_).
[Экран оплаты заказа (экран кассы) позволяет вносить изменения по инициативе плагина](https://iiko.github.io/front.api.doc/2024/08/14/edit-current-payment-screen.html).
