### ISSUE TITLE
Получение id товаров из чека

### ISSUE THREAD

**Issue by bodanrchuk** [iiko/front.api.sdk#27]
Добрый день! 
Нужна ваша помощь мы застряли на одном моменте. Нам нужно получать с айко product id из чека, чтобы мы могли на своей стороне это идентифицировать и начислять кэшбек индивидуально на каждую позицию. Мы нашли id product, но он почему-то приходит всегда другой(динамический). Как это может быть? И есть ли какой-то идентификатор позиции по которому можно ее идентифицировать?
![photo_2019-04-24_20-55-47](https://user-images.githubusercontent.com/49979887/57087346-80d32d00-6d08-11e9-9a78-8715cda07ba3.jpg)

**Comment by ierof** [comment]
Вы указываете на id элемента заказа. На несколько строчек ниже есть свойство ‘Product’. Посмотрите его содержимое

**Comment by bodanrchuk** [comment]
Извините, вот этот параметр мы используем! Но он статический!
![image](https://user-images.githubusercontent.com/49979887/57118298-0982b500-6d6b-11e9-84fd-7d587a57c484.png)
В

**Comment by ierof** [comment]
Пока по вашим вопросам не могу понять, что вам нужно? 

Если вы хотите уникально идентифицировать каждую проданную позицию заказа, то вам подойдёт Id у Items заказа, который вы на первом скриншоте отметили. Этот идентификатор не меняется для позиции заказа. Он не «динамический», как вы написали. 

Если вы хотите как-то идентифицировать продукты заказа, то это свойство Product. Это элемент справочника номенклатуры.

**Comment by bodanrchuk** [comment]
Спасибо,!

**Comment by vladislav250899** [comment]
> Пока по вашим вопросам не могу понять, что вам нужно?
> 
> Если вы хотите уникально идентифицировать каждую проданную позицию заказа, то вам подойдёт Id у Items заказа, который вы на первом скриншоте отметили. Этот идентификатор не меняется для позиции заказа. Он не «динамический», как вы написали.
> 
> Если вы хотите как-то идентифицировать продукты заказа, то это свойство Product. Это элемент справочника номенклатуры.

При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70918933-993e5080-2028-11ea-8ff7-2c784101106a.png)


При подключении этих пакетов отображается ошибка и пакет не устанавливается:

https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha
Подскажите, пожалуйста, как можно решить эту проблему?
