### ISSUE TITLE
Некорректные данные в GetVisibleProducts()

### ISSUE THREAD

**Issue by zhmpng** [iiko/front.api.sdk#272]
Добрый день. Возник вопрос следующего характера.
Сейчас столкнулись с следующей задачей: необходимо получать внутри плагина список доступных к продаже товаров.

Для этого мы воспользовались методом `PluginContext.Operations.GetVisibleProducts()` и получаем из него `List<Guid>`.
Блюда, у которых в номенклатуре бекОфиса не проставлены галочки продажи в данном отделение, в списке указанном выше, нам не приходят (мы считаем это корректным поведением)
В случае если мы сделаем все тоже самое для модификатора, запретим его продаже на точке, то данный метод нам все равно вернет его Id, указывая на то, что он является доступным к продаже, хотя это не так.

Версия используемого Api: Resto.Front.Api.V6 v7.0.6022 из NuGet
Данная история была выявлена при использование RMS 7.5 и 7.7, и  iikoFront 7.5.6015.0 и 7.7.8001.0 

Описания данного метода в документации SDK [iikoFront Api V6 Code Reference](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_IOperationService.htm) не было обнаружено.

Прошу дать фидбек по данной ситуации и предоставить описание данного метода!
Заранее, Спасибо!

**Comment by igorpooh1978** [comment]
Стесняюсь спросить, а где вы такой метод взяли ? PluginContext.Operations.GetVisibleProducts() - такой вижу даже в dll нет
![image](https://user-images.githubusercontent.com/47010778/135303594-9d8cdf95-41a0-48a6-81a0-a49d8dafe515.png)

**Comment by zhmpng** [comment]
Извиняюсь, не корректную информацию предоставил. Закрываю issue
