### ISSUE TITLE
Получить код блюда из iikoOffice

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#273]
В iikoOffice каждое блюдо имеет код (см. скриншот).
![image](https://user-images.githubusercontent.com/90399756/134656623-4ce173a1-2b13-4e2f-8def-8944524b8ee6.png)
Существует ли способ получить код данного `IOrderRootItem`? Например, если задача — сделать отображение всех блюд в заказе в массив пар вида _(код, количество)_.

**Comment by qt-user** [comment]
> В iikoOffice каждое блюдо имеет код (см. скриншот). ![image](https://user-images.githubusercontent.com/90399756/134656623-4ce173a1-2b13-4e2f-8def-8944524b8ee6.png) Существует ли способ получить код данного `IOrderRootItem`? Например, если задача — сделать отображение всех блюд в заказе в массив пар вида _(код, количество)_.

IOperationService.TryGetProductById() или IOperationService.GetProductById() согласно документации, id Найдете в самом IOrderRootItem

**Comment by delta81** [comment]
Код
```c#
foreach (var item in order.Items)
{
    var product = os.GetProductById(item.Id);
```
выбрасывает `IProduct with id {GUID} not found`.

**Comment by letolica** [comment]
Здесь есть пример, как из блюда получить название продукта из блюда заказа:
https://github.com/iiko/front.api.sdk/blob/084b4c506380102bfd307596fe1f794802d1ac82/sample/v7preview7/Resto.Front.Api.SamplePlugin/DiagnosticMessagesTester/OrderItemReadyChangeNotifier.cs#L71
Таким же образом можно получить и код быстрого доступа [`IProduct.FastCode`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_FastCode.htm)
`IOrderRootItem` — это базовый айтем заказа, у него несколько наследников. Чтобы добраться до продукта, в котором находится код быстрого доступа, нужно привести базовый айтем к необходимому типу: [`IOrderServiceItem`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_IOrderServiceItem.htm), [`IOrderProductItem`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_IOrderProductItem.htm) или один из компонентов [`IOrderCompoundItem`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_IOrderCompoundItem.htm)
