### ISSUE TITLE
Передача информации о заказе между кассами.

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#274]
Коллеги, добрый день!
Краткая схема работы нашего плагина.
Плагин используется для проведения наших бонусов на кассе. Клиент сканирует мобильное приложение на кассе, где далее отображаются бонусы и подарки.
В момент закрытия чека в событии orderchanged мы отправляем заказ в нашу систему лояльности (с возможными типами оплат, суммами и подарками.). В этот момент мы имеем заказ на кассе и все добавленные в него типы оплат, а так же "привязанного" клиента. Этой информации нам достаточно для корректного проведения транзакции и отправки в нашу систему лояльности.

Сейчас встал вопрос более сложной схемы реализации продажи.
Есть главная касса с ККМ и т.д. а так же несколько касс для менеджеров на которых установлены сканеры и формируются заказы клиентов.
Клиент может просканироваться на любой кассе и добавить бонусный тип оплаты и имеющиеся подарки. Однако конечная оплата заказа происходит на главной кассе.

По закрытию заказа на главной кассе все кассы (плагины) отлавливают событие orderchanged и пытаются отправить информацию по закрытому заказу в нашу систему лояльности. Как следствие данной конфигурации мы отправляем 3,4,5 запросов в лояльность из всех касс(плагинов) из которых только один запрос от одной кассы на которой физически "привязывался" клиент имеет информацию по текущему пользователю(внутренняя логика нашего плагина). Между кассами передается только непосредственно сам заказ.

Вопрос:
Каким образом обеспечить отсылку конечного заказа в нашу систему лояльности только из кассы на которой производилась "привязка" клиента или каким образом можно передать "объект" нашего клиента на все кассы.

**Comment by igorpooh1978** [comment]
Добрый день.
Ну как вариант 
https://iiko.github.io/front.api.doc/2020/11/23/call-remote-external-operation.html

**Comment by vcpp** [comment]
> каким образом можно передать "объект" нашего клиента на все кассы.

Если бонусы добавляются в заказ через API как внешний тип оплаты, дополнительную информацию можно сохранить в поле [`CustomData`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Payments_ExternalPaymentItemAdditionalData_CustomData.htm) класса [`ExternalPaymentItemAdditionalData`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Payments_ExternalPaymentItemAdditionalData.htm), передав его экземпляр в аргумент `additionalData` методов `AddPaymentItem`/`AddPreliminaryPaymentItem`/`AddExternalPaymentItem`. Эта информация будет храниться в заказе с привязкой к оплате, её можно прочитать из [`IPaymentItem.AdditionalData`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Payments_IPaymentItem_AdditionalData.htm).

Если привязка к оплате не требуется, можно просто сохранить в заказе произвольные данные с помощью метода [`AddOrderExternalData`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderExternalData.htm). Сохранённую таким образом информацию затем можно прочитать на соседнем терминале с помощью метода [`TryGetOrderExternalDataByKey`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_TryGetOrderExternalDataByKey.htm).

> Каким образом обеспечить отсылку конечного заказа в нашу систему лояльности только из кассы на которой производилась "привязка" клиента

Как уже предложили, можно передавать информацию между плагинами по сети. Экземпляры вашего плагина, установленные на разных терминалах, могут общаться между собой. Подробнее [тут](https://iiko.github.io/front.api.doc/2020/11/23/call-remote-external-operation.html).
В этом варианте следует учитывать, что компьютер, на котором создали заказ и привязали гостя, в момент оплаты может оказаться недоступен или выключен.

> По закрытию заказа на главной кассе все кассы (плагины) отлавливают событие orderchanged и пытаются отправить информацию по закрытому заказу в нашу систему лояльности

Если бы ваш плагин только этим и занимался, я бы предложил указать в [манифесте](https://iiko.github.io/front.api.doc/directories.html) флаг `IsSingleInstance`, в таком случае плагин запустился бы в единственном экземпляре и не дублировал бы отправку данных. Однако, в вашем случае у плагина есть и другие функции, которые должны работать на всех терминалах.

Вы можете сами использовать логику `IsSingleInstance` внутри плагина. Например, подпишитесь на событие `OrderChanged` только на главном терминале, проверив [`IsMainTerminal`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IHostTerminalSettings_IsMainTerminal.htm):
```cs
if (PluginContext.Operations.GetHostTerminalSettings().IsMainTerminal)
    PluginContext.Notifications.OrderChanged.Subscribe()...;
```

Кроме того, в обработчике уведомления об изменении заказа вы можете проверить, на каком терминале сделано изменение, чтобы игнорировать изменения, полученные с соседних терминалов. В выпущенных версиях API для этого можно было использовать метод [`TryGetLastChangedOrderTerminal`](https://iiko.github.io/front.api.sdk/v7preview7/html/M_Resto_Front_Api_IOperationService_TryGetLastChangedOrderTerminal.htm), начиная с V7 прямо в `IOrder` появится свойство `LastChangedTerminalId`.
