### ISSUE TITLE
Отсканировать QR

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#277]
Задача: отсканировать QR-код при помощи сканера штрихкодов.

При применении сканера iikoFront распознаёт его как "сканер штрихкода" и после прочтения QR-а при открытой методом `ShowKeyboard()` клавиатуре (как и при любом другом типе диалогового окна) уведомляет о том, что штрихкод "не зарегистрирован в системе". Попытки переопределить поведение сканера, установив типом устройства, например, PS/2 Keyboard, не привели к успеху: при применении сканера он добавляется в список устройств с настройками по умолчанию.

![скан](https://user-images.githubusercontent.com/90399756/135771078-e0998b3b-867f-47bc-8de8-9ea24a98235d.png)

Как настроить сканер и какие методы API нужно вызвать, чтобы плагин мог получить прочитанный код?

**Comment by zed220** [comment]
Добрый день!

Возможно, вы используете метод [ShowExtendedInputDialog](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowExtendedInputDialog.htm). Если это так, то там может быть выключена прокатка карт. Попробуйте её включить:

```
var settings = new ExtendedInputDialogSettings
{
	...
	EnableBarcode = true,
	EnableCardSlider = true,
	...
};
```

Также, пользуясь случаем, добавлю, что в версии **V7** добавлен новый диалог [ShowExtendedKeyboardDialog](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowExtendedKeyboardDialog.htm), в котором логика обработки сканирования штрихкода и прокатки карты была измененена. В новом методе всё должно заработать и без выставления параметра **enableCardSlider**.

Сообщите, пожалуйста, о результатах.

**Comment by delta81** [comment]
Спасибо, штрихкод прочитали, но уведомление всё равно появляется.

**Comment by vcpp** [comment]
> ```cs
> PluginContext.Operations.AddNotificationMessage("Баркод считан.", "SamplePlugin");
> ```

Дополню: чтобы перекрывающее уведомление не висело в углу вечно, пока пользователь не закроет его руками, необходимо задать таймаут. Сообщение о незарегистрированном штрихкоде автоматически закрывается спустя 3 секунды, такой же таймаут можно задать и перекрывающему уведомлению.

**Comment by zed220** [comment]
Здравствуйте!

Мы поправили это поведение для новой версии 8.0. Теперь в данном сценарии сообщение о ненайденном баркоде показываться не будет.
