### ISSUE TITLE
Валюты

### ISSUE THREAD

**Issue by Lizzzzzard** [iiko/front.api.sdk#278]
Добрый день, коллеги!
Настроили разные валюты в iikoFront
![image](https://user-images.githubusercontent.com/74863190/136025104-8e864878-d9c5-483c-ae15-21910f454fed.png)
Как можно отследить как проходила оплата, смотрю через sdk, но разницы между оплатой евро и оплатой рублями нет никакой
![image](https://user-images.githubusercontent.com/74863190/136816190-015c47c4-0075-46bf-99dc-404e39dc114c.png)
В офисе в кассовой смене так же не видно чем платил клиент.
Подскажите как мы можем это отслеживать? Каким методом можно узнать заказ был оплачен евро или рублями? 
Если таких методов нет, то будут ли они реализованы?

**Comment by vcpp** [comment]
> Задачу можно закрыть

Здесь, на github закрою, а RMS-52980 рано или поздно сделаем.
