### ISSUE TITLE
ID кофейни

### ISSUE THREAD

**Issue by Polazhenko** [iiko/front.api.sdk#279]
Использую front api 7preview7

Есть сеть кофеен по франшизе. В основном в кофейне два терминала, один из них - главная касса. Хотим в веб сервисе идентифицировать кофейню одним ид. 

Планируем использовать IRestaurant.CrmId, но есть подозрения, что если разные кофейни принадлежат одному юр.лицу - то этот ИД у них будет одинаковый. А хотелось бы идентифицировать кофейню по номеру, как сущность, не важно сколько там терминалов или каком юр.лицу они принадлежат, спасибо.

**Comment by vcpp** [comment]
В общем случае никому верить нельзя:
* Работающие в разных кофейнях кассы могут быть разнесены по разным группам одного и того же торгового предприятия, словно это смежные площадки в одной локации. Такие кофейни не получится различать по серверу iikoRms, лицензии и прочим общим признакам.
* Некоторые сети размножаются клонированием базы данных, поэтому полагаться на глобальную уникальность идентификаторов групп и других объектов структуры торгового предприятия тоже нельзя.

В частных случаях — а вы, видимо, говорите об одной конкретной сети — лучше смотреть, как фактически реализована сеть.

Между прочим, а почему бы вам самим не создать идентификатор, который будет храниться в [папке плагина](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPluginIntegrationService_GetConfigsDirectoryPath.htm)? Сгенерируете при первом запуске на главном терминале, и вот вам ваш уникальный идентификатор кофейни, который будет жить вместе с этим главным терминалом.
