### ISSUE TITLE
Получения списка столиков

### ISSUE THREAD

**Issue by ArhTresh** [iiko/front.api.sdk#28]
При попытке получить список столиков при помощи "var table = PluginContext.Operations.GetTables();" функция возвращает все столики, в том числе удаленные/скрытые, как получить список столиков без удаленных/скрытых, а именно тех которые отображаются в программе iikoFront в окне зала.

**Comment by ArhTresh** [comment]
Дополняю, функция возвращает все столики, с разных банкетных залов, даже те которые скрытые, удаленных столиков она не выводит( и не нужно). Необходимо вернуть столики с одного банкетного зала и не скрытые.

**Comment by vcpp** [comment]
> Необходимо вернуть столики с одного банкетного зала и не скрытые.

Список столов зала можно получить непосредственно у этого зала: [`IRestaurantSection.Tables`](https://iiko.github.io/front.api.sdk/v5/html/P_Resto_Front_Api_V5_Data_Organization_Sections_IRestaurantSection_Tables.htm), там будут только неудалённые столы этого зала (отделения).
