### ISSUE TITLE
Удаление заказа в bill, closed

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#281]
Добрый день. 

- Можно ли как то удалить заказ в статусах bill , closed 
- И удалить оплату в статусе Processed

У клиента свой КЦ и после передачи заказа с комбинированной оплатой есть случае когда 1 платеж прошел а второй нет. И Тот что прошел в статусе Processed удалить не удается
Также Если заказ прошел и в статусе closed но его нужно удалить и пробить уже измененный (там в КЦ что то изменилось. Или вообще отказалось )  тоже удалить заказ не удается. 

Удается удалить только заказ в New если по нему нет оплат

**Comment by letolica** [comment]
Добрый день, я не могу говорить о сроках.
Завела дополнительную задачу на сторнирование заказа. Задача на удаление закрытого заказа вытекает из возможности его сторнировать и возможности вернуть предоплаты, если они есть. Дальше можно вызывать существующие методы `DeletePrintedOrderItems`, затем `DeleteOrder`. Итого список задач к реализации пока такой:

- RMS-49715 Front.Api: удалять проведенные платежи (предоплаты)
- RMS-53010 Front.Api: возврат закрытого заказа (сторнирование)

**Comment by ierof** [comment]
Уже можно: https://iiko.github.io/front.api.doc/2023/10/18/storno-order.html
