### ISSUE TITLE
Получить IViewManager при изменении заказа

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#282]
Задача: вывести pop-up при изменении заказа.
Подписка на `OrderChanged` (`PluginContext.Notifications.OrderChanged.Subscribe(order => {})`) позволяет получить только заказ. Возможно ли восстановить контекст для получения `IOperationService` и `IViewManager`?

**Comment by vcpp** [comment]
> Задача: вывести pop-up при изменении заказа.

Для взаимодействия с пользователем на экране редактирования заказа по инициативе плагина можно использовать метод [`TryEditCurrentOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_TryEditCurrentOrder.htm), передав туда callback, принимающий `IViewManager`. Подробнее [тут](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html).

Если же ваше всплывающее окно должен вызвать сам пользователь, можно разместить [кнопку](https://iiko.github.io/front.api.doc/2020/11/11/add-button-to-order-edit-screen.html), на которую пользователь должен будет нажать. Можно ещё зарегистрировать [обработчик прокатки карты или сканирования штрихкода](https://iiko.github.io/front.api.doc/2020/07/24/order-edit-card-barcode-handlers.html).

> Подписка на `OrderChanged`

Подписка на `OrderChanged` не привязана к UI и уведомляет о любых изменениях заказов, включая те, что сделаны фоновой автоматикой, другими плагинами, либо получены с соседних терминалов.

> Насколько я понимаю, объект `IViewManager` доступен только в методе, который вызывается при передачи управления от iikoFront к плагину. И удаляется после возврата метода.

Так и есть.

> Вариант который приходит, что бы не терять объект - не делать возврат.

Пока плагин не вернёт управление, выполняемая плагином операция будет считаться продолжающейся, на UI приложения будет висеть прогрессбар, пользователь не сможет продолжать работать.

> В описанной ситуации диалоговое окно можно создать как свое произвольное WPF окно.

На эту тему есть отдельная [статья](https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html).

**Comment by vcpp** [comment]
Кстати, вы не уточнили, какое сообщение хотите показать. Немодальные сообщения, которые будут выводиться в левом верхнем углу, можно показывать в любой момент с помощью методов [`AddNotificationMessage`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_AddNotificationMessage.htm), [`AddWarningMessage`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_AddWarningMessage.htm) и [`AddErrorMessage`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_AddErrorMessage.htm).
