### ISSUE TITLE
неверно применяется скидка при передаче оплаченного заказа через api front 

### ISSUE THREAD

**Issue by hedkrabe** [iiko/front.api.sdk#283]
Добрый день! Мы используем api iiko front для передачи заказов на станцию. В случае если в заведении активна скидка на товар, то на переданную нами предоплату (передаем сумму уже с учетом скидки) повторно применяется активная скидка, в следствии этого получаем ошибку {\"code\":-1,\"message\":\"Введенная сумма слишком большая.\",\"description\":\"\",\"httpStatusCode\":500}"
Что пробовали сделать:
1) передавать сумму без учета скидки - ошибка идентична
2) в RMS, в разделе скидки и оплаты убирали совместимость скидок с используемой нами валютой

Что нам нужно - понять каким образом сделать так, чтобы при наличии скидок сумма переданной предоплаты, сходилась с итогом.
Заранее спасибо!

**Comment by vcpp** [comment]
Приведите, пожалуйста, максимально простой пример, как можно воспроизвести ошибку. Пусть там будет один товар, одна скидка, одна предоплата. Ну и арифметика — ожидаемая и фактическая.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
