### ISSUE TITLE
PaymentActionFailedException во время попытки закрыть заказ.

### ISSUE THREAD

**Issue by AlexDragonLore** [iiko/front.api.sdk#284]
Во время работы планина, каждый третий заказ не закрывается через дистанционную оплату.  Падает на методе - PluginContext.Operations.PayOrder . Выдает ошибку -
[2021-10-25 15:37:59,563] ERROR [11] - Resto.Front.Api.Exceptions.PaymentActionFailedException: Заказ не может быть заблокирован. Повторите попытку позже.
Прикладываю логи - 
[cash-server.log](https://github.com/iiko/front.api.sdk/files/7418013/cash-server.log)
[api (3).log](https://github.com/iiko/front.api.sdk/files/7418014/api.3.log)

Какие есть причины такого нестабильного поведения, и есть ли способы убрать эту ошибку?

**Comment by vcpp** [comment]
Плагин вносит изменения в заказ и сразу же пытается его оплатить. В текущей реализации iikoFront дистанционная оплата всегда выполняется на [главном терминале](https://ru.iiko.help/articles/iikooffice-7-7/topic-265/a/h2__1634860086). Если бы плагин был установлен на главном терминале и там же выполнял бы оплату, такой ошибки бы не было. Однако, в вашем случае плагин вносит изменения, находясь на одном терминале, а дистанционная оплата затем выполняется на другом, главном терминале. Если терминал, где работает плагин, не успеет передать последние изменения и разблокировать заказ (а это выполняется асинхронно), то главный терминал не сможет приступить к оплате заказа.

Это известные грабли, описанные в [документации](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html):

> Плагин, использующий функции редактирования данных, предпочтительно устанавливать на главную кассу. Установка на другие терминалы допускается, но в некоторых сценариях возможны разовые отказы в применении изменений, вызванные деталями реализации. Возможно, в одной из следующих версий эти ограничения будут сняты.

Пока мы не устранили эти грабли, в качестве временного решения могу предложить:
* если это возможно, установить плагин на главный терминал
* добавить небольшую задержку перед выполнением оплаты

Пример:
`
[2021-10-27 20:12:59,641] DEBUG [151] - End calling “BeOpen.Plugins.Front.Paybo” plugin's continuousOperation callback
[2021-10-27 20:12:59,667] DEBUG [151] - Plugin “BeOpen.Plugins.Front.Paybo” is calling PayOrder operation
`
Тут в 20:12:59,641 плагин завершил пакетную операцию с проведением предоплаты, а уже спустя 26 мс инициировал оплату. Мне кажется, пауза в 0,5-1 секунду перед оплатой значительно снизила бы вероятность возникновения ошибки.

Чтобы снизить вероятность до нуля, понадобится доработка на нашей стороне. Внутренний номер задачи: RMS-52997.
