### ISSUE TITLE
Отследить нажатие кнопки "Платежи"

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [iiko/front.api.sdk#285]
Здравствуйте! Подскажите пожалуйста, у меня стоит задача, что когда пользователь нажимает кнопку "Платежи" нужно выполнить определенные действия и показать "модальное окно", как я могу отследить нажатие этой кнопки? Или хотя бы подскажите в каком направлении мне действовать?

![image](https://user-images.githubusercontent.com/29563929/138906632-64f4da05-a197-483b-9ddd-2a994453ced8.png)

**Comment by vcpp** [comment]
Увы, пока нет возможности взаимодействовать с экраном редактирования доставки, но рано или поздно мы это сделаем.

Чтобы нам точнее понимать ваши потребности, расскажите, пожалуйста, подробнее сценарий использования. Когда сотрудник ответит на вопрос, участвует ли клиент в бонусной программе, что должно произойти дальше? Достаточно ли плагину возможности показывать окна (`IViewManager`) или понадобится ещё и возможность вносить изменения в заказ (`IOperationService`)? В каких ещё случаях нужно спрашивать об участии клиента в бонусной программе? При переходе на экран оплаты, например?

**Comment by AgPeHaJIuH1** [comment]
Надо будет и показывать диалоговые окна и так же взаимодействовать с заказом.

Идея такова: если клиент участвует в программе лояльности, то он сможет через наше "внешнее" API оплатить часть заказа бонусами. Для этого мы реализуем интерфейс IExternalPaymentProcessor, но так же хотелось бы отследить переход на экран оплаты, для того что бы "кассир" не забывал предложить "клиенту" зарегистрироваться в нашей программе лояльности.

PS я почему то думал, что должно было вызывается событие PluginContext.Notifications.SubscribeOnNavigatingToPaymentScreen когда пользователь переходит на экран оплаты... Но нет...

**Comment by AgPeHaJIuH1** [comment]
Так же я пробовал событие PluginContext.Notifications.ScreenChanged, но через него тоже не удалось получить нужный функционал.

**Comment by AgPeHaJIuH1** [comment]
![image](https://user-images.githubusercontent.com/29563929/140992656-004a55cf-3ec1-408d-a875-f77724b10ebb.png)

Ещё огромная просьба, добавить в интерфейс и передавать нам (я правда не знаю как и когда) ID текущего "внешнего типа оплаты", иначе приходится городить костыль, вроде того, как на скрине

Так как он (в данном случае) регистрируется через iikoOffice я могу получить ID только так...
Или подскажите, может я ошибаюсь и я где то ещё могу получить ID?

@vcpp

**Comment by vcpp** [comment]
> Или подскажите, может я ошибаюсь и я где то ещё могу получить ID?

В какой момент, в каком методе вы хотите знать ID типа оплаты? На скриншоте видно, что вы заполняете свойство в методе `Pay`, но не видно, где вы затем читаете значение из этого свойства.

**Comment by AgPeHaJIuH1** [comment]
Попробую объяснить
Мне надо провести "реальную транзакцию" через внешнее API только ПОСЛЕ закрытия заказа. Для этого я подписываюсь событие PluginContext.Notifications.OrderChanged (скрин 1)
В методе я получаю текущий Order, и мне надо понять какие из методов оплаты являются "моими", что бы провести транзакцию (скрин 2)

![image](https://user-images.githubusercontent.com/29563929/141004150-4fdbdeb3-29a0-46a6-b881-492e14f62170.png)
![image](https://user-images.githubusercontent.com/29563929/141004663-16d250ae-a189-4beb-a615-c8d6800d4d56.png)

**Comment by AgPeHaJIuH1** [comment]
PS по свойству 
IExternalPaymentProcessor.PaymentSystemName невозможно определить, моя ли это система оплаты или нет, так как если в iikoOffice имя "внешнего типа оплаты" было изменено, мне придет именно оно, а не моё (указанное в PaymentSystemName)

В общем то самое надежное - это иметь возможность как то получить Type.ID моего типа оплаты

**Comment by vcpp** [comment]
> по свойству IExternalPaymentProcessor.PaymentSystemName невозможно определить, моя ли это система оплаты или нет, так как если в iikoOffice имя "внешнего типа оплаты" было изменено, мне придет именно оно, а не моё (указанное в PaymentSystemName)

Вероятно, вы говорите о [`IPaymentType.Name`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Payments_IPaymentType_Name.htm) — это название типа оплаты для пользователя, оно задаётся пользователем в iikoOffice и показывается пользователю на UI iikoFront, в отчётах и пр. На это название, конечно, нельзя полагаться. Название типа оплаты не обязано совпадать с кодовым названием платёжной системы.

Вам следует использовать метод [`GetPaymentSystemName`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetPaymentSystemName.htm), который позволяет из `IPaymentType` получить кодовое название платёжной системы. Если это ваш тип оплаты, то метод вернёт именно ту строку, которую вы указали в [`IPaymentProcessor.PaymentSystemKey`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_IPaymentProcessor_PaymentSystemKey.htm).

Не путать кодовое название платёжной системы `PaymentSystemKey` и название для пользователя `PaymentSystemName`. Только сейчас заметил противоречие, что метод, возвращающий `PaymentSystemKey`, по недоразумению называется `GetPaymentSystemName`. Начиная с V7 переименуем в `GetPaymentSystemKey`.

Возвращаясь к вашему решению хранить id типа оплаты в свойстве `CurrentPaymentTypeId` в экземпляре `IPaymentProcessor`, могу предложить более изящную альтернативу. В данном случае с учётом `GetPaymentSystemName` эта альтернатива не нужна, но вдруг в будущем пригодится: вы можете хранить свои данные непосредственно в [`IPaymentItem.AdditionalData`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Payments_IPaymentItem_AdditionalData.htm), их можно положить туда при добавлении ([`AddExternalPaymentItem`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddExternalPaymentItem.htm)) или позднее ([`ChangeExternalPaymentItemCustomData`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_ChangeExternalPaymentItemCustomData.htm)). Пример можно найти в методе `AddAndProcessExternalPrepay` [тут](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html).


> Мне надо провести "реальную транзакцию" через внешнее API только ПОСЛЕ закрытия заказа.

Ох, это ненадёжный путь. Во-первых, если компьютер выключится после закрытия заказа, но до обработки плагином события о его изменении, то при следующем запуске надо будет как-то понять, что оплата в одном из закрытых заказов в реальности ещё не проведена. А во-вторых, что вы делаете, если «реальную транзакцию» провести не удалось? Генерация `PaymentActionFailedException` уже не поможет.

**Comment by AgPeHaJIuH1** [comment]
> Во-первых, если компьютер выключится после закрытия заказа, но до обработки плагином события о его изменении, то при следующем запуске надо будет как-то понять, что оплата в одном из закрытых заказов в реальности ещё не проведена. А во-вторых, что вы делаете, если «реальную транзакцию» провести не удалось? Генерация PaymentActionFailedException уже не поможет

На данный момент ничего не делаем =) Но мне и правда стоит поднять этот вопрос с заказчиком

В остальном мне все понятно, спасибо за разъяснения!

А в системе не может быть несколько внешних типов оплаты с одинаковыми PaymentSystemKey? Это значение уникальное?

**Comment by vcpp** [comment]
> А в системе не может быть несколько внешних типов оплаты с одинаковыми PaymentSystemKey? Это значение уникальное?

Надо различать платёжную систему (payment system) и тип оплаты (payment type).
`PaymentSystemKey` — кодовое название платёжной системы, оно уникально. Не может быть двух платёжных систем 
  с одинаковым `PaymentSystemKey`. Метод [`RegisterPaymentSystem`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_RegisterPaymentSystem.htm) проверяет наличие платёжной системы с кодовым названием из [`IPaymentProcessor.PaymentSystemKey`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_IPaymentProcessor_PaymentSystemKey.htm) и, если такой нет, создаёт, а если уже есть, то использует ранее созданную. Логика работы платёжной системы реализуется плагином в `IPaymentProcessor`, при этом зарегистрировать два экземпляра `IPaymentProcessor` с одинаковыми `PaymentSystemKey` невозможно, для второго и следующих экземпляров метод `RegisterPaymentSystem` будет возвращать `PaymentSystemRegistrationException` с сообщением _Another payment processor with key XXX was already registered_.

В iikoOffice пользователь создаёт тип оплаты, указывая зарегистрированную вами платёжных систем. Он может не делать этого, и тогда не будет ни одного типа оплаты, использующего вашу платёжную систему. Количество типов оплаты, использующих вашу платёжную систему, может быть любым — 0, 1, 2, 3, ..., но обычно 0 (ещё не настроили) или 1 (уже настроили).

Строгий ответ на ваш вопрос — в системе может быть несколько типов оплаты, привязанных к одной и той же платёжной системе. Обработка всех этих типов оплаты будет выполняться одним и тем же вашим `IPaymentProcessor`.

**Comment by AgPeHaJIuH1** [comment]
Вы отлично все разъяснили! Спасибо!
