### ISSUE TITLE
Узнать через API iikoFront доступно ли к продаже блюдо/модификатор?

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#286]
Добрый день. В задаче [issues/214](https://github.com/iiko/front.api.sdk/issues/214 ) Вы писали что :
_Есть появившийся в V5 относительно новый метод GetPrice, с помощью которого можно узнать цену с учётом размера продукта, ценовой категории заказа и времени исполнения заказа (актуально для банкетов и доставок), но для блюд, которые исключены из продажи, этот метод возвращает цену по умолчанию из карточки продукта._

Но ведь получается это баг ? который якобы выдают за фичу. 
Ведь я делаю запрос цены и специально шлю по какой ценовой я хочу узнать цену и жду что мне вернутся цена по выбранной мною ценовой. А если ее нет, то (ошибка, или еще что то, но ни как не цена с базового или с карточки). 
С таким же успехом он мог начать мне рандомный цифры слать. А что информации от них столько же.

Из этого следуют **просьба завести в разработку задачу на исправления поведения метода GetPrice** дабы он возвращал то чего я жду, а не левую цифру которую он мне подсунул так как не смог найти нужную. 
Или же **завести аналогичный метод для верной проверки цены. И если блюда нет в ценовой метод должен об это сообщить.** 

Вторая часть. Это можно ли как то сейчас узнать: **Блюдо / модификатор включены ли в ценовую?** а то ловить лицом Exception при попытке работать с заказом без возможности как то заранее прогнать валидацию. Очень не приятно и костыльно.

**Comment by vcpp** [comment]
> Но ведь получается это баг ? который якобы выдают за фичу.

Да, текущее поведение ошибочно. Нет смысла сообщать цену блюда, которое в принципе не продаётся с указанными параметрами (размер, ценовая категория, время). Исторически получилось два отдельных метода — одно для определения цены (`GetPrice`), другое для проверки доступности в меню (`GetIncludedInMenuSectionsByProduct`), и второе застряло в прошлом, о чём я писал в #214: _в бэклоге висит задача на выпиливание GetIncludedInMenuSectionsByProduct и объединение информации о цене и наличии в меню: RMS-45015. В основной план работ эта задача всё никак не попадёт :-(_

> просьба завести в разработку задачу на исправления поведения метода GetPrice

Задача-то есть, но времени на неё, увы, не хватает. RMS-45015 по-прежнему в бэклоге и в V7 вряд ли попадёт.

> можно ли как то сейчас узнать: Блюдо / модификатор включены ли в ценовую?

Нет, нормального способа пока нет.
Некоторые выкручиваются тем, что в карточке блюда указывают нулевую цену и предполагают, что блюдо не продаётся с указанными параметрами (размер, ценовая категория, время), если `GetPrice` возвращает 0, но тогда, во-первых, все блюда придётся явно включать в продажу через приказы об изменении прейскуранта, во-вторых, трюк не сработает в бесплатными позициями, которые могут быть включены в продажу с нулевой ценой. Можно, наверное, вместо нуля указать какую-то другую маловероятную в реальной жизни магическую константу (0,07?), но это все равно неудобный костыль.

В качестве временного решения можно попробовать использовать iikoServer API, там это поддерживается начиная с v2. К сожалению, [тут](https://ru.iiko.help/articles/#!api-documentations/nomenclature) сильно устаревшая документация, актуальный пример мог бы выглядеть так:
Request
```
http://localhost:8080/resto/api/v2/price?dateFrom=2019-01-01&dateTo=2021-08-31&type=SCHEDULED
```
<details>
<summary>Response</summary>
<pre>
{
    "result": "SUCCESS",
    "errors": [],
    "response": [
        {
            "departmentId": "6713a472-973e-4215-8e0f-e3142945befd",
            "productId": "4a5e8eea-8d6a-44f9-a72d-db834d666cf2",
            "productSizeId": null,
            "prices": [
                {
                    "dateFrom": "2021-07-16",
                    "dateTo": "2500-01-01",
                    "price": 12,
                    "pricesForCategories": [],
                    "includeForCategories": [],
                    "included": true,
                    "dishOfDay": false,
                    "flyerProgram": false,
                    "documentId": "631407d4-d004-49a5-941c-2e4c86a8c9e0",
                    "schedule": {
                        "id": "a31ffb8a-05dd-42a1-9cc6-b1c6d4826ddf",
                        "name": "Выходные",
                        "periods": [
                            {
                                "begin": "19:00",
                                "end": "23:59",
                                "daysOfWeek": [
                                    5
                                ]
                            },
                            {
                                "begin": "00:00",
                                "end": "23:59",
                                "daysOfWeek": [
                                    6
                                ]
                            },
                            {
                                "begin": "00:00",
                                "end": "00:00",
                                "daysOfWeek": [
                                    7
                                ]
                            }
                        ]
                    }
                },
                {
                    "dateFrom": "2021-08-01",
                    "dateTo": "2500-01-01",
                    "price": null,
                    "pricesForCategories": [
                        {
                            "categoryId": "515d91b3-f4e3-46fa-abc2-de7567df95c9",
                            "price": 14
                        },
                        {
                            "categoryId": "67a54111-99ff-40cc-9f34-f2feddd0ff2b",
                            "price": 13
                        }
                    ],
                    "includeForCategories": [
                        {
                            "categoryId": "515d91b3-f4e3-46fa-abc2-de7567df95c9",
                            "include": true
                        },
                        {
                            "categoryId": "67a54111-99ff-40cc-9f34-f2feddd0ff2b",
                            "include": true
                        }
                    ],
                    "included": false,
                    "dishOfDay": false,
                    "flyerProgram": true,
                    "documentId": "d57dfa32-7e4a-446c-b2e4-e28e065b2112",
                    "schedule": {
                        "id": "598ce53a-c49c-4cd5-8248-1e2b4f0994cf",
                        "name": "Рабочий полдник",
                        "periods": [
                            {
                                "begin": "16:00",
                                "end": "17:00",
                                "daysOfWeek": [
                                    1,
                                    2,
                                    3,
                                    4,
                                    5
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "departmentId": "6713a472-973e-4215-8e0f-e3142945befd",
            "productId": "a00a470c-6cc9-4b7f-835f-393e41af8fcf",
            "productSizeId": "e4a246af-d94f-4505-ae2e-7bc854e6908a",
            "prices": [
                {
                    "dateFrom": "2021-07-16",
                    "dateTo": "2500-01-01",
                    "price": 99,
                    "pricesForCategories": [],
                    "includeForCategories": [],
                    "included": true,
                    "dishOfDay": false,
                    "flyerProgram": false,
                    "documentId": "631407d4-d004-49a5-941c-2e4c86a8c9e0",
                    "schedule": {
                        "id": "a31ffb8a-05dd-42a1-9cc6-b1c6d4826ddf",
                        "name": "Выходные",
                        "periods": [
                            {
                                "begin": "19:00",
                                "end": "23:59",
                                "daysOfWeek": [
                                    5
                                ]
                            },
                            {
                                "begin": "00:00",
                                "end": "23:59",
                                "daysOfWeek": [
                                    6
                                ]
                            },
                            {
                                "begin": "00:00",
                                "end": "00:00",
                                "daysOfWeek": [
                                    7
                                ]
                            }
                        ]
                    }
                },
                {
                    "dateFrom": "2021-08-01",
                    "dateTo": "2500-01-01",
                    "price": null,
                    "pricesForCategories": [
                        {
                            "categoryId": "515d91b3-f4e3-46fa-abc2-de7567df95c9",
                            "price": 101
                        },
                        {
                            "categoryId": "67a54111-99ff-40cc-9f34-f2feddd0ff2b",
                            "price": 100
                        }
                    ],
                    "includeForCategories": [
                        {
                            "categoryId": "515d91b3-f4e3-46fa-abc2-de7567df95c9",
                            "include": true
                        },
                        {
                            "categoryId": "67a54111-99ff-40cc-9f34-f2feddd0ff2b",
                            "include": true
                        }
                    ],
                    "included": false,
                    "dishOfDay": false,
                    "flyerProgram": true,
                    "documentId": "d57dfa32-7e4a-446c-b2e4-e28e065b2112",
                    "schedule": {
                        "id": "598ce53a-c49c-4cd5-8248-1e2b4f0994cf",
                        "name": "Рабочий полдник",
                        "periods": [
                            {
                                "begin": "16:00",
                                "end": "17:00",
                                "daysOfWeek": [
                                    1,
                                    2,
                                    3,
                                    4,
                                    5
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "revision": 187657
}
</pre>
</details>

**Comment by Kamaew** [comment]
Добрый день. А изменился статус RMS-45015 ? Есть шанс что GetPrice начнет работать правильно ?

**Comment by vcpp** [comment]
Увы, пока без движения :-(
Шанс, конечно, есть, но там загвоздка в том, что нет очевидного простого способа решения, поэтому задача каждый раз откладывается, и так уже шестой год. Возможно, её стоит сделать уже хотя бы в каком-то минимальном урезанном виде, чем всё надеяться найти время на проектирование API для цен и всего, что на них влияет.

**Comment by Kamaew** [comment]
Добрый день. А изменился статус RMS-45015 ? Есть шанс что GetPrice начнет работать правильно ?

**Comment by letolica** [comment]
Добрый вечер. Возможно вашу ситуацию решит новый метод.
[Возможность узнать, что блюдо в конкретном размере доступно к продаже](https://iiko.github.io/front.api.doc/2024/09/09/get-included-in-menu.html).
