### ISSUE TITLE
Событие смены Culture на кассе

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#289]
Добрый день. Я вроде читал что было событие завязавшись на которое можно реагировать не смену Culture в айко. Чтобы при смене локализации на фронте. Сделать автоматическую смену локализации плагина. Подскажите есть ли это?

**Comment by vcpp** [comment]
Да, в V7 появится событие `CurrentCultureChanged`. Задача в процессе.

**Comment by Kamaew** [comment]
Ну и по традиции. Напишите номер задачи

**Comment by igorpooh1978** [comment]
Доброе утро, 
https://github.com/iiko/front.api.sdk/issues/201
:)

**Comment by Kamaew** [comment]
Говорю же где то читал что было такое. Странно что поиск не выдал. Ну тогда ждем
