### ISSUE TITLE
Как убрать валиадцию пустого поля..

### ISSUE THREAD

**Issue by bodanrchuk** [iiko/front.api.sdk#29]
У нас реализовано, что клиент может оплатить часть заказа наличкой, а часть бонусами. 
Но клиент может не оплачивать бонусами, если хочет получить кэшбек. Как убрать валидацию поля оплаты бонусами на стороне iiko? Что бы можно было закрыть чек плагина со суммой "0". 
На стороне бэкенд/плагина валидацию на данное поле не ставили.

**Comment by ierof** [comment]
Судя по описанию, вы пользуетесь [`IViewManager.ShowInputPopup`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_UI_IViewManager_ShowInputPopup.htm) – это инструмент для ввода положительных чисел.
Посмотрите в сторону [`IViewManager.ShowExtendedNumericInputPopup`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_UI_IViewManager_ShowExtendedNumericInputPopup.htm)

Подробная статья про диалоговые окна: https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html
Статья про API V6 и методы имеют другие наименования. Но суть та же, что и в V5.

**Comment by bodanrchuk** [comment]
Спасибо!

**Comment by vladislav250899** [comment]
> Судя по описанию, вы пользуетесь [`IViewManager.ShowInputPopup`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_UI_IViewManager_ShowInputPopup.htm) – это инструмент для ввода положительных чисел.
> Посмотрите в сторону [`IViewManager.ShowExtendedNumericInputPopup`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_UI_IViewManager_ShowExtendedNumericInputPopup.htm)
> 
> Подробная статья про диалоговые окна: https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html
> Статья про API V6 и методы имеют другие наименования. Но суть та же, что и в V5.

При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70918828-68f6b200-2028-11ea-8910-f9f73dbc3d2a.png)


При подключении этих пакетов отображается ошибка и пакет не устанавливается:

https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha
Подскажите, пожалуйста, как можно решить эту проблему?
