### ISSUE TITLE
Изменить статус доставки по id 

### ISSUE THREAD

**Issue by 929895588** [iiko/front.api.sdk#290]
Я проверил Resto.Front.Api.SamplePlugin к сожалению я там не нашел скрипт для изменение статус доставки, есть примеры изменение комментарии заказа и другие. Скажите пж как я могу изменить статус доставки по ID?

**Comment by 929895588** [comment]
Хотим изменить статус заказа от "Готовится" -> Приготовлен

**Comment by vcpp** [comment]
У самой доставки нет статусов «Готовится» и «Приготовлен». Статусы доставки можно посмотреть [тут](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Brd_DeliveryStatus.htm).

Слова «Готовится», «Приготовлен» и прочая информация на экране отображается на основе совокупности статусов доставки ([IDeliveryOrder.DeliveryStatus](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IDeliveryOrder_DeliveryStatus.htm)), заказа ([IDeliveryOrder.Status](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_Status.htm)) и блюд ([IOrderRootItem.Status](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderRootItem_Status.htm)).
Для того, чтобы доставка считалась приготовленной, надо завершить приготовление всех её блюд и модификаторов на кухне, переведя их в статус `KitchenOrderItemProcessingStatus.Processed` с помощью метода [`ChangeKitchenOrderItemsProcessingStatus`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_ChangeKitchenOrderItemsProcessingStatus.htm).

Для возможности управления статусами блюд на кухне необходимо включить KDS, то есть в настройках отделений, где готовятся блюда, должна стоять галочка «Показывать блюда на кухонном экране», тогда при отправке доставочного заказа в приготовление создастся привязанный к нему через поле [`BaseOrderId`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder_BaseOrderId.htm) кухонный заказ, и вы сможете отметить блюда приготовленными или поданными.

Без включения KDS и использования кухонных заказов назначать блюдам промежуточные статусы не получится, можно только довести до финального статуса «Подано» с помощью метода [`ServeOrderCookingItem`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_ServeOrderCookingItem.htm).

**Comment by 929895588** [comment]
KDS я установил и посмотрел как это работает, у меня еще вопрос. Есть примеры изменить статус заказа?

**Comment by vcpp** [comment]
> Есть примеры изменение статус заказа?

У заказа статусов [не так много](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_OrderStatus.htm) — изначально `New`, после [печати пречека](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_BillOrder.htm) `Bill`, после [оплаты](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrder.htm) `Closed`.
Пример изменения статуса приготовления блюд можно посмотреть в [KitchenLoadMonitoringView](https://github.com/iiko/front.api.sdk/blob/master/sample/v7preview7/Resto.Front.Api.SamplePlugin/Kitchen/KitchenLoadMonitoringView.xaml.cs).
