### ISSUE TITLE
Сборка плагина из примера завершается ошибкой 

### ISSUE THREAD

**Issue by darktwister1337** [iiko/front.api.sdk#291]
Добрый день, собираю плагин и подключаю отладку согласно топику https://iiko.github.io/front.api.doc/v6/ru/Debugging.html, но получаю ошибку

![image](https://user-images.githubusercontent.com/45266610/141744476-676277e2-69a5-4cfb-b000-ebca370dfe4c.png)
[2021-11-10 21:35:45,882]  WARN [ 1] - Не удалось подключиться к IPC-порту: Не удается найти указанный файл.

С чем это может быть связано и как это можно вылечить?

**Comment by darktwister1337** [comment]
iikoFront запущен от имени администратора, студия также от имени админа,

Лицензия используется от payment api, которую скинул менеджер.

**Comment by igorpooh1978** [comment]
Скорее всего связано с типом вашей лицензии (д.б. для разработчика)

**Comment by darktwister1337** [comment]
@igorpooh1978 
> Скорее всего связано с типом вашей лицензии (д.б. для разработчика). Именно ваша лицензия iiko, а не LicenseModuleId

Нет, лицензию поставили разрабочика на всю айко, но по-прежнему ничего.

**Comment by igorpooh1978** [comment]
Просто исходя из вашего сообщения именно нет связи с Resto.Front.Api.Host.exe
проверяйте вашу строку соединения )

**Comment by darktwister1337** [comment]
> Просто исходя из вашего сообщения именно нет связи с Resto.Front.Api.Host.exe проверяйте вашу строку соединения )

Стесняюсь спросить, а что за строка соединения?)
Запуск и параметры в студии имеете в виду? Или в самом плагине где-то?

В студии запуск = C:\Program Files\iiko\iikoRMS\Front.Net\Resto.Front.Api.Host.exe

И параметры: /a="C:\Users\kosm7\Desktop\sample\v7preview7\Resto.Front.Api.SamplePlugin\bin\Debug\Resto.Front.Api.SamplePlugin.dll" /c=Resto.Front.Api.SamplePlugin.SamplePlugin /m=Лицензия /l="C:\Projects\Front.Api Sdk\Logs\sample-plugin.log"

**Comment by igorpooh1978** [comment]
В целом, все верно. Попытайте ещё вашего менеджера. А вдруг ...
Да кстати VS и фронт под админом особо не нужно, если только не что-то мощное делаете.
И проверьте ешё раз путь до dll прям скопирните строку и и проверьте есть ли такое размещение в реальности

**Comment by vcpp** [comment]
> получаю ошибку

Самое интересное на скриншоте скрыто за вопросительными знаками. Можно указать русский в качестве языка по умолчанию для программ, не поддерживающих юникод. Эту настройку периодически [перепрятывают](https://superuser.com/questions/497857/how-to-change-language-for-non-unicode-programs-in-windows-8), но вы её найдёте. А вообще рекомендую не использовать локализацию, ибо термины и сообщения об ошибке на английском гораздо лучше гуглятся :-)

> Не удалось подключиться к IPC-порту: Не удается найти указанный файл.
С чем это может быть связано и как это можно вылечить?

Процесс Resto.Front.Api.Host.exe, в котором живёт ваш плагин, не смог подключиться к процессу iikoFront.Net.exe.
Возможные варианты:
- приложение iikoFront.Net.exe вообще не запущено
- приложение iikoFront.Net.exe находится в процессе запуска и висит на экране загрузки. Механизм хостинга плагинов включается, когда всё остальное уже готово к работе, так что надёжный вариант — дождаться, когда приложение запустится и перейдёт на экран логина,
- приложение iikoFront.Net.exe начало выключаться
- версии Resto.Front.Api.Host.exe и iikoFront.Net.exe не совпадают (маловероятно, если приложение установлено инсталлятором). Достаточно сверить версию, которую вы видите в шапке лога своего плагина (7.7.8001.0), и версию, отображаемую в верхнем левом углу окна iikoFront.
- ограничения антивируса/файрвола и т. п. Тут трудно дать универсальный рецепт — с параметрами по умолчанию отладка работает, а дальше всё индивидуально. Можно попробовать начать с чистой установки (например, в виртуальной машине), убедиться, что отладка работает, и затем, доустанавливая и донастраивая софт, поймать момент, когда отладка перестанет работать. Это муторно и есть риск, что отладка так в итоге и не отвалится.

Логи/журнал событий не смотрели? В api.log после записи _Plugin hosting service started_ тишина? А если установить плагин в папку Plugins, он запустится приложением iikoFront (без отладки)?
Как запускаете приложение iikoFront 

> iikoFront и Visual Studio запущены от имени администратора

Так тоже должно работать, но с нашей стороны нет необходимости запускаться от имени админа. И, если я правильно понимаю, при отсутствии доступа, связанном с разным уровнем привилегий, должно быть исключение `Win32Exception` с внятным сообщением об отсутствии доступа.

> связано с типом вашей лицензии (д.б. для разработчика).

В случае неподходящей лицензии было бы исключение `ConnectionDeniedException` с указанием причины.

> проверьте ешё раз путь до dll прям скопирните строку и и проверьте есть ли такое размещение в реальности

В случае проблем с командной строкой было бы исключение `CommandLineException` с указанием причины. На скриншоте видно, что из файла плагина были успешно прочитаны версия (v0.0.0.0) и [метаданные](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo?view=net-6.0#properties), тут всё в порядке.

**Comment by darktwister1337** [comment]
В общем, насколько я понял, у меня были какие-то проблемы с правами (стоял оригинальный чистый образ win10 (но которую, каким-то образом я умудрился поломать)). Несколько софтин маячили до этого об "Access Denied". (они работали на уровне ядра-драйвера от Ring-0). Как такое может быть - не ясно =)

Переустановка windows на самую актуальную версию решила эту проблему, так что спасибо за поддержку!

**Comment by darktwister1337** [comment]
> А если установить плагин в папку Plugins, он запустится приложением iikoFront (без отладки)? Как запускаете приложение iikoFront

При запуске таким образом iikoFront выкидывало следующую ошибку.
![image](https://user-images.githubusercontent.com/45266610/142977947-c3474f62-6df9-4f77-8e0d-9df6dbbba7ff.png)


iikoFront запускался по-разному, то от имени администратора, то с ярлыка от пользователя. (Перед началом отладки само собой).
