### ISSUE TITLE
Применить скидку по каждому блюду в заказе отдельно

### ISSUE THREAD

**Issue by Polazhenko** [iiko/front.api.sdk#292]
Добрый день, 

Задача - наложить скидку из внешней системы лояльности. После нажатия кнопки "Касса" - плагин применял бы скидки по каждому блюду (где-то на блюдо скидка 50%, где-то 0%, где-то 10%) и бариста видел бы и мог бы показать клиенту окончательный расклад и потом сделать оплату. 

Использую front api 7preview7. Ловлю переход на экран "Касса" подпиской на 
`PluginContext.Notifications.NavigatingToPaymentScreen.Subscribe(x => OnNavigatingToPaymentScreen(x.order, x.pos, x.os, x.vm, x.context));`

OpenPrice поддерживают не все блюда.
Пока удалось на весь заказ навесить скидку в Х рублей через AddFlexibleSumDiscount
Но хотелось бы по каждому блюду отдельно изменить цену в заказе...

**Comment by vcpp** [comment]
Внутренний номер задачи: RMS-53603.

**Comment by vcpp** [comment]
> OpenPrice поддерживают не все блюда.

Помимо свободной цены, есть ещё предопределённая цена блюда (`predefinedPrice`). Предопределённую цену можно задать любому блюду или модификатору в момент добавления заказ. Если предопределённая цена задана, она будет использоваться вместо всех остальных цен (свободной, из прейскуранта, из карточки товара).

Хотя для системы лояльности, конечно, нужны именно скидки/надбавки. Пока закрою эту задачу. Как сделаем — напишем.

**Comment by fader1** [comment]
> Внутренний номер задачи: RMS-53603.

Добрый день!   
Тоже очень хотелось бы возможность применения скидок отдельно по каждому блюду.
Когда ориентировочно можно рассчитывать на возможность появления такого функционала в API ?

**Comment by aitkkia** [comment]
> Внутренний номер задачи: RMS-53603.
Добрый день
Тоже бы хотелось узнать, когда можно будет использовать такой функционал.

**Comment by vcpp** [comment]
Можно использовать начиная с V8Preview6, [добавлен](https://iiko.github.io/front.api.doc/2023/05/18/different-discount-for-different-items.html) новый [метод](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Editors_IEditSession_ChangeSelectiveDiscount_1.htm).
