### ISSUE TITLE
Как изменить время кухонный заказ по каждому чеку?

### ISSUE THREAD

**Issue by 929895588** [iiko/front.api.sdk#293]
Хочу изменить время приготовления чека, но я в front api не нашел, есть ли такая функция?

**Comment by vcpp** [comment]
Непонятно, что именно вы хотите поменять. Время приготовления — это нормативная продолжительность приготовления ([`IOrderCookingItem.CookingTime`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderCookingItem_CookingTime.htm) и [`IKitchenOrderCookingItem.CookingTime`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrderCookingItem_CookingTime.htm))? Или фактическое время завершения приготовления ([`IOrderCookingItem.CookingFinishTime`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderCookingItem_CookingFinishTime.htm) и [`IKitchenOrderCookingItem.ProcessingCompleteTime`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrderCookingItem_ProcessingCompleteTime.htm))?

Кроме того, должны ведь какие-то последствия быть, если вы что-то меняете в одном месте, что-то должно пересчитаться в другом. Расскажите лучше, в чём цель, а там подумаем.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущего комментария.
