### ISSUE TITLE
Принтер не печатает

### ISSUE THREAD

**Issue by nurillaxoja** [iiko/front.api.sdk#294]
Добрый день
1. У меня проблема с печатью чека в принтере. Использовал `printer.Print(slip)` в методе ExternalPaymentProcessor 
->OnPaymentAdded но не печатает и не выдаёт ошибок в try . В iiko Office добавил принтер и напечатал тестовый текст. 

![demo](https://user-images.githubusercontent.com/45284957/142607357-fb3d977a-9dee-4217-8583-4aff3188b67a.png)

2. Как можно использовать шаблоны чеков в коде iiko font

**Comment by vcpp** [comment]
> не печатает и не выдаёт ошибок в try

Метод [`IReceiptPrinter.Print`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IReceiptPrinter_Print.htm) работает асинхронно, поэтому ошибки в плагин не возвращаются. Уведомление о неуспешной печати показывается в левом верхнем углу экрана и записывается в лог. Посмотрите, что в логе.

> Как можно использовать шаблоны чеков в коде iiko font

Вопрос непонятен. Шаблоны чеков используются неявно при печати соответствующего чека. Например, запускаете приготовление блюд — шаблон сервисного чека формирует разметку чека, который напечатан на кухне.
Расскажите, какую задачу вы решаете.

**Comment by nurillaxoja** [comment]
> Метод [`IReceiptPrinter.Print`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IReceiptPrinter_Print.htm) работает асинхронно, поэтому ошибки в плагин не возвращаются. Уведомление о неуспешной печати показывается в левом верхнем углу экрана и записывается в лог. Посмотрите, что в логе.

Я поискал и вчера и нашёл virtual-printer.log там ведёт ошибку
```
[2021-11-23 11:50:18,437]  INFO [73] [FilePrintQueue:PrintInvalidPrintTask] - 
No receipt printer defined for CashRegister: VG
Payment System     Plugin
```

![инструменты](https://user-images.githubusercontent.com/45284957/142982177-0ae90191-ca9e-47b4-8f2f-d9157a4b5d3d.png)
![vg](https://user-images.githubusercontent.com/45284957/142983110-0f3ce46e-df4e-4d0b-84c9-9043721b6db5.png)
кроме того если в IikoFont -> Сервис -> Отчеты -> напечатать любой отчёт в log пишет предыдущий ошибку  но принтер добавлен и печатает тестовый печать  

> Как можно использовать шаблоны чеков в коде iiko font 

iikoOffice -> Администрирование -> Шаблоны чеков ->  как их использовать в плагине

**Comment by vcpp** [comment]
> No receipt printer defined for CashRegister: VG

А, так у вас не указан принтер квитанций. Укажите его в настройках [точек продаж](https://ru.iiko.help/articles/iikooffice-7-8/topic-265/a/h2_1860095416).

> iikoOffice -> Администрирование -> Шаблоны чеков -> как их использовать в плагине с помощью кода

Явно — никак. Могу повторить пример неявного использования: _запускаете приготовление блюд — шаблон сервисного чека формирует разметку чека, который напечатан на кухне._ Сейчас нет возможности взять шаблон сервисного чека, скормить ему входные параметры и получить текст разметки.
Если хотите в явном виде перечислять список шаблонов и напрямую запускать их, опишите, в каком сценарии возникает такая потребность, подумаем, как реализовать. Лучше отдельной заявкой, чтобы тут не смешивать два вопроса, первый из которых решён.
Для отчётов совсем недавно [реализовали](https://iiko.github.io/front.api.doc/2021/10/29/get-front-reports-markup.html) возможность получения разметки из плагина. Пока в упрощённом виде, правда, без параметров, но для текущих потребностей хватило.
