### ISSUE TITLE
CreateEditSession() в другом потоке?

### ISSUE THREAD

**Issue by Polazhenko** [iiko/front.api.sdk#296]
Строка: 
`var` editSession = os.CreateEditSession();

генерирует эксепшен: 
` System.Runtime.Remoting.RemotingException:` Затребованная служба не найдена.

Надо вызывать код только из основного потока?

**Comment by vcpp** [comment]
> Надо вызывать код только из основного потока?

В плагине нет понятия основного потока, как это бывает в GUI-приложениях. Можно использовать любой поток.

> генерирует эксепшен:
`System.Runtime.Remoting.RemotingException:` Затребованная служба не найдена.

Нужно больше информации:
* Исключение возникает постоянно в 100% случаев? Или разово в определённой ситуации?
* Работало ли при этом само приложение iikoFront? Возможно, приложение упало, и потому плагин не смог до него достучаться.
* Какая версия iikoFront?
* Сможете предоставить логи или сценарий с кодом, по которому мы сможем повторить ошибку у себя?

**Comment by Polazhenko** [comment]
версия 7preivew7, я вызывал отдельный поток из callback, видно это ключевой момент был, когда вызвал последовательно то всё ок, фронт в это время всегда работал.

`private void OnNavigatingToPaymentScreen(IOrder order, IPointOfSale pos, IOperationService os, IViewManager vm, INavigatingToPaymentScreenOperationContext context)
`        {
`            PluginContext.Log.Info($"OnNavigatingToPaymentScreen order (id=[{order.Id}])");
`            if (!IsOnline)
`                return;
`
`            GetDiscountCurOrderAsync(order, os, vm, context).Wait();
`        }
`

**Comment by vcpp** [comment]
Вероятно, вы пытаетесь использовать ресурсы за пределами их времени жизни.

Передаваемые в обработчик уведомления объекты типа `IVewManager`, `IOperationService` и пр. доступны только во время работы этого обработчика, потому что выполняемая приложением iikoFront операция приостанавливается и ждёт, что сделают плагины. Вы можете показывать окна, вносить изменения в заказ и так далее. В этот момент никто не взаимодействует с пользователем (висит прогрессбар), никто не меняет заказ, который вы можете монопольно редактировать и так далее. Как только вы возвращаете управление из обработчика, считается, что вы завершили обработку уведомления, iikoFront завершает текущую операцию и работает дальше — показывает следующие окна, вносит изменения в заказ...

Таким образом, потоки здесь ни при чём, вы можете использовать любой поток, но важно учитывать время жизни объектов — полученный обработчиком локальный экземпляр `IOperationService` можно использовать только до возврата управления из обработчика. В произвольный момент времени вы можете использовать глобальный экземпляр `PluginContext.Operations`, но он не позволяет вносить изменения в заказ, открытый в приложении iikoFront. Заказ, открытый на экране редактирования, можно попробовать поменять через `TryEditCurrentOrder`, но для экрана оплаты такой возможности пока нет, но мы над этим работаем.

Кроме того, надо будет подумать, как упростить диагностику. По задумке, плагин должен получать `ObjectDisposedException` при обращении к уничтоженному объекту, но, как мы видим, торчат уши межпроцессного взаимодействия. Попробуем добавить обёртки, чтобы `RemotingException` не пролезал в плагин.
