### ISSUE TITLE
Отрисовка картинки через принтер

### ISSUE THREAD

**Issue by denis660** [iiko/front.api.sdk#297]
Здравствуйте

Как напечатать картинку в чеке ? Используя XML шаблон для печати
Стандартный протокол escpos  позволяет отправлять картинку на принтер

**Comment by Polazhenko** [comment]
а принтер у поса не будет матричный? потянет картинку?

**Comment by vcpp** [comment]
Сейчас доступны два варианта:
* основной — заранее загрузить картинку в принтер и при печати использовать тэг `logo` с номером картинки в памяти принтера, подробнее [тут](https://ru.iiko.help/articles/iikooffice-7-7/topic-5/a/h3_2099599836)
* недокументированный — передавать картинку в формате base64 прямо при печати с помощью тэга `image`, это пока поддерживается только для принтеров этикеток (Zebra EPL, TSPL).

**Comment by Polazhenko** [comment]
А у XElement, что используется для формирования чеков есть параметр Tags.QRCode - по нему есть какая-то документация, как им можно воспользоваться, выглядит как будто нужная штука для печати QR кодов в чеках.

`afterCheque.Add(new` XElement(Tags.QRCode, "https://play.google.com/"));

**Comment by denis660** [comment]
> Сейчас доступны два варианта:
> 
> * основной — заранее загрузить картинку в принтер и при печати использовать тэг `logo` с номером картинки в памяти принтера, подробнее [тут](https://ru.iiko.help/articles/iikooffice-7-7/topic-5/a/h3_2099599836)
> * недокументированный — передавать картинку в формате base64 прямо при печати с помощью тэга `image`, это пока поддерживается только для принтеров этикеток (Zebra EPL, TSPL).

Попробовали тег image, не помогло, вы можете дать пример кода с этим тегом и тестовой картинкой ?

**Comment by letolica** [comment]
#147

**Comment by rengal** [comment]
Начиная с версии 8.9 тег [image](https://iiko.github.io/front.api.sdk/v9/html/F_Resto_Front_Api_Data_Cheques_Tags_Image.htm) поддерживается на всех принтерах этикеток, а также EpsonT88, ESC/POS и Windows-принтере. Внутри тега необходимо передать монохромное изображение в виде base64 строки.
```
<doc>
  <f0>Test image</f0>
  <image align="center">iVBORw0KGgoAAAANSUhEUgAAAH0AAAAnCAYAAAAilUe0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGQSURBVHhe7ZELioBADEO9/6VdChsopT91FhaSBwOaZqIl1y3oUOmEqHRCVDohKp0QlU6ISidEpROi0glR6YSodEJUOiEqnRCVTsiflX5debTX7Tk7wD97Kt3wOTgV2ay6EzX4/PFs5hnxTuX7wvnEX6qf9fq01CbDk+ndN574vba5Fz3THESfkWlfOJcU6JYC0zKbDNBlPflGluO1bA68nnmmuWH6dPcr55IC3VKgWhBsMsCbHKPK8nr1HOl89r7JiT5Q6W84k5KAn8wO6GZGfAeZXnmN7ezpcyT6/IlkmtH5qztPOZOS0C0FpkU2GeBNjmEzzL1v8xzpfNM7MD2bVfobzqQkdEuBaZFNBuiyum8YmHtfphn2HjWQ3QfxXpeRzSr/G84lBbqlQLUg2GR4Mn36hlF5Oj0SvdO9bG7EHCPTvnAuKdAtBbBMPGCrd7MNlbfLwKzyTJq/i9PpJzmfKP49Kp0QlU6ISidEpROi0glR6YSodEJUOiEqnRCVTohKJ0SlE6LSCVHphKh0Ou77B2lqCvgaSElqAAAAAElFTkSuQmCC</image>
</doc>
```
