### ISSUE TITLE
Тех карта

### ISSUE THREAD

**Issue by MubinjonMuinov** [iiko/front.api.sdk#298]
Как запретит показ тех карты в кухонном экране?

**Comment by MubinjonMuinov** [comment]
![image](https://user-images.githubusercontent.com/61738844/143595288-ae77925d-bc12-4ad8-910d-e3e26feb8553.png)

как убрать доступа из сотрудников?

**Comment by vcpp** [comment]
Никак.

Возникает два встречных вопрос:
1. При чём здесь API?
2. Что плохого в том, что повар посмотрит тех. карту?

Поскольку некоторым клиентам эта кнопка нужна, совсем убрать её не получится. Можно подумать о том, чтобы добавить очередную настройку, либо очередное право, либо пытаться угадывать необходимость кнопки по какому-то условию, либо как-то ещё обойти проблему, с которой вы столкнулись. Чтобы предложить какое-то решение, надо прежде понять, в чём проблема.

**Comment by MubinjonMuinov** [comment]
Добрый день!
У нас есть полуфабрикаты для нас это ОЧЕННННЬ КОНФИДЕНЦИАЛЬНО! Тех карту полуфабрикатов знает только работники цеха и руководство. Но через кухонный экран->тех карта эти конфиденциальности становится доступными для всех). Вот по этому хотим каким-то образом себя защитить.

**Comment by vcpp** [comment]
> Тех карту полуфабрикатов знает только работники цеха и руководство.

Получается, что некоторым пользователям всё-таки нужна возможность смотреть тех. карту?

> через кухонный экран->тех карта эти конфиденциальности становится доступными для всех

Для всех поваров? Или для всех сотрудников вообще?
Доступ на кухонный экран регулируется [правами](https://ru.iiko.help/articles/#!iikooffice-7-8/topic-745/q/F_KDS/qid/853513/qp/1) F_KDS и F_EKDS, что позволяет запретить использование кухонного экрана официантам, кассирам, хостес и прочим сотрудникам, кому KDS по работе не нужен. Останутся только повара из других цехов. Они тоже не должны знать рецепты полуфабрикатов? А рецепты своих блюд им можно смотреть?

> хотим убрать доступы

У техподдержки уже есть аналогичная заявка трёхлетней давности, я прицепил ваше обращение туда же, внутренний номер SPRT-19833. Как видите, запросов на доработку всегда больше, чем ресурсов на их реализацию, поэтому непопулярные некритичные хотелки могут долго ждать своей очереди. Вы можете попробовать продвинуть эту заявку, обратившись в техподдержку и добавив заявке популярности (сколько ресторанов нуждаются в фиче) и/или критичности (чем грозит бизнесу утечка конфиденциальных техкарт). Если совсем никак, можно рассмотреть вариант платной доработки. В любом случае, вам в техподдержку, здесь на гитхабе в рамках обсуждения iikoFront API это не решить.

**Comment by MubinjonMuinov** [comment]
F_KDS и F_EKDS - сейчас мы так и сделали, убрали доступы у всех кто раньше имели доступ кухонном экране. Мы хотим использовать кухонный экран при одном условии там не дольно показывать тех карту полуфабрикатов остальные(блюдо) можно. Думаю это очень важно для так как полуфабрикаты это конфиденциально и вот по этому хотим увидеть на iikoChain-е возможности убрать полуфабрикаты(на iiko это заготовки) из кухонный экран.
