### ISSUE TITLE
метод Pay в интерфейсе IExternalPaymentProcessor

### ISSUE THREAD

**Issue by Anton-Grebenkin** [iiko/front.api.sdk#299]
Добрый день.
В интерфейсе IExternalPaymentProcessor есть метод Pay, если сумма оплаты 0, то
метод Pay не вызывается. Как сделать, чтобы при нулевой сумме наш тип оплаты не удалялся и вызывался метод Pay?

**Comment by aitkkia** [comment]
![image](https://user-images.githubusercontent.com/59682448/144178311-93efc48a-2232-4a3a-8ab5-b0992ea644f6.png)
Если сперва добавить внешнюю оплату, а потом наличные или картой, то да IIKO удалит оплату с нулевой суммой(по крайней мере у меня). 
Делаю так - **добавляю карту/наличные с нужной суммой и потом уже нужную оплату с нулевой суммой**.

**Comment by Anton-Grebenkin** [comment]
Но мне нужно, чтобы оплата оставалась при любом порядке добавления

**Comment by Anton-Grebenkin** [comment]
Может есть вариант подписаться на оплату заказа, и в подписке проводить нашу оплату?

**Comment by Anton-Grebenkin** [comment]
Подписался на событие изменения заказа, если статус = closed и в заказе нет моего типа оплаты, провожу продажу.
Нормальное решение?

**Comment by Anton-Grebenkin** [comment]
Теперь возникли проблемы с возвратом...

**Comment by aitkkia** [comment]
> Теперь возникли проблемы с возвратом...
> Как по order-у понять что делают возврат?

Если у вас плагин зарегистрирован внешний тип оплаты и реализует интерфейс IExternalPaymentProcessor, то есть метод, который вызывается, когда у вас в оплате есть ваш тип оплаты - "void ReturnPayment(decimal sum, Guid? orderId, Guid paymentTypeId, Guid transactionId, [NotNull] IPointOfSale pointOfSale, [NotNull] IUser cashier, IReceiptPrinter printer, IViewManager viewManager, IPaymentDataContext context, IProgressBar progressBar);"([ссылка](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html)) - он вызывается, когда осуществляется возврат на кассе.


> Подписался на событие изменения заказа, если статус = closed и в заказе нет моего типа оплаты, провожу продажу. Нормальное решение?

А у вас при этом на экране закрытого заказа видно, что был добавлен тип оплаты?
![image](https://user-images.githubusercontent.com/59682448/144534572-2e9a937b-c968-4bb8-b231-ff118fbcb6c9.png)

**Comment by Anton-Grebenkin** [comment]
Нет, я не смог добавить свой тип оплаты в подписке, метод ReturnPayment не будет вызываться. Я ловлю закрытие заказа и отправляю данные в свою систему, теперь хочу ловить возврат. Проблема в том, что я не могу отличить возврат от оплаты по заказу, и в том и другом случае status = closed

**Comment by aitkkia** [comment]
> 

Не разу не сталкивался с проблемой регистрации типа оплаты, где-то есть "[SamplePaymentPlugin](https://github.com/iiko/front.api.sdk/tree/master/sample/v6/Resto.Front.Api.SamplePaymentPlugin)".

**Comment by vcpp** [comment]
> Как сделать, чтобы при нулевой сумме наш тип оплаты не удалялся и вызывался метод Pay?

Итак, сейчас вы пытаетесь использовать фиктивную оплату на нулевую сумму. Всегда ли эта оплата нулевая? Вероятно, при оплате или возврате заказа вам нужно выполнять какие-то операции, не связанные с движением денежных средств. Что это за операции? Могут ли они быть неуспешными? Всегда ли эти операции нужны (всегда ли кассир добавляет ваш тип оплаты)? Возможно, вместо фиктивного проведения нулевой оплаты вам стоит [реализовать](https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html) собственное расширение для фискального регистратора ([`IChequeTaskProcessor`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Devices_IChequeTaskProcessor.htm)) и ловить печать кассовых чеков через [`BeforeDoCheckAction`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Devices_IChequeTaskProcessor_BeforeDoCheckAction.htm).

Альтернативный вариант — это таки идти путём проведение нулевых оплат. В таком случае надо подумать, как это должно выглядеть на UI. Допустим, по умолчанию используется один тип оплаты, а кассир, не удаляя дефолтную оплату, выбирает другой тип оплаты, либо кассир сначала выбрал один тип оплаты, а затем выбрал другой. Сейчас мы предполагаем, что предыдущая нулевая оплата не пригодилась, поэтому автоматически удаляем её из заказа. Как понять, что нулевая оплата должна остаться в заказе? Просто убрать автоудаление, заставив кассира удалять ненужные нулевые оплаты руками, нехорошо. Нужен какой-то критерий, который позволит понять, что нулевую оплату следует оставить. Если это фиксированный параметр платёжной системы, может, добавить флажок вида `requireZeroPaymentProcessing` в метод [`RegisterPaymentSystem`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_RegisterPaymentSystem.htm) по аналогии с `canProcessPaymentReturnWithoutOrder`?

Отдельный вопрос — должна ли нулевая оплата попадать в фискальный чек?

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
