### ISSUE TITLE
Удаленная отладка плагина

### ISSUE THREAD

**Issue by avrezvanov** [iiko/front.api.sdk#3]
1) Настроил удаленную отладку согласно документации
2) На удаленном хосте запустил iikoFront
3) При запуске проекта получаю следующие ошибки:

`"Resto.Front.Api.Host.exe" (CLR v4.0.30319: DefaultDomain). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll". Невозможно найти или открыть PDB-файл.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: DefaultDomain). Загружено "\\xxx.xxx.xxx.xxx\c$\Program Files\iiko\iikoRMS\Front.Net\Resto.Front.Api.Host.exe". Символы загружены.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "\\xxx.xxx.xxx.xxx\c$\Program Files\iiko\iikoRMS\Front.Net\Resto.Front.Api.V4.dll". Символы загружены.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "\\xxx.xxx.xxx.xxx\c$\Program Files\iiko\iikoRMS\Front.Net\Resto.Front.Api.V5.dll". Символы загружены.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "\\xxx.xxx.xxx.xxx\c$\Program Files\iiko\iikoRMS\Front.Net\Resto.Front.Api.V6.dll". Символы загружены.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "\\xxx.xxx.xxx.xxx\c$\Program Files\iiko\iikoRMS\Front.Net\Resto.Framework.dll". Символы загружены.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll". Невозможно найти или открыть PDB-файл.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll". Невозможно найти или открыть PDB-файл.
Вызвано исключение: "System.IO.FileNotFoundException" в Resto.Front.Api.Host.exe
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll". 
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll". Невозможно найти или открыть PDB-файл.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll". Невозможно найти или открыть PDB-файл.
"Resto.Front.Api.Host.exe" (CLR v4.0.30319: Resto.Front.Api.Host.exe). Загружено "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\mscorlib.resources.dll". Сборка модуля выполнена без символов.
Программа "[19064] Resto.Front.Api.Host.exe" завершилась с кодом 0 (0x0).`

Если всё тоже самое проделать на локальном хосте, то всё работает как положено. 
Что делаю не так?

**Comment by avrezvanov** [comment]
Немного перефразирую вопрос.
**Можно ли настроить удаленную отладку плагина.** 
У нас на отдельном сервере поднята Айка. 
Программисты работают на своих машинах. 
Все находятся в одной сети. 
Было бы очень удобно пользоваться удаленной отладкой. 
Если подцепится к удаленному процессу, то срабатывают не все брекпоинты и через раз. 
Если нужна дополнительная информация, скажите, предоставлю.

**Comment by vcpp** [comment]
Мы не пробовали использовать удалённую отладку, но специальных ограничений нет, теоретически это может работать.

Попробуем, напишем, взлетает или нет. Если там какая-то простая загвоздка, сразу и поправим.
Пока посмотрите, в логах что-нибудь есть? В журнале событий Windows?

**Comment by bildeyko** [comment]
Работаете под vs 2017? В 2015 отдаленная отладка была кривенькой. Она у меня нормально подключалась и останавливалась на брейкпоитнах, но не загружала переменные и их значения. Просто были пустые строки.
У самого iiko развернута на удаленной машине, удаленная отладка работает без проблем.

У вас настроена подгрузка PDB файлов с серверов символов Microsoft?

**Comment by vcpp** [comment]
Проверил удалённую отладку — таки работает (VS 2017).

Если у вас локальная отладка работает, а удалённая нет, проблема, скорее всего, в целом в использовании удалённой отладки и загрузке модулей/pdb, это не имеет отношения к iikoFront API. Ладно бы удалённая отладка других приложений работала, а ошибки возникали только для *Resto.Front.Api.Host.exe*...

> Если подцепится к удаленному процессу, то срабатывают не все брекпоинты и через раз.

Ну, это точно не к нам. Это общие вопросы о том, как пользоваться отладчиком Visual Studio. С такими вопросами лучше на stackoverflow.com. Если есть подозрения, что отладчик работает неправильно, нужно обратиться к разработчикам отладчика.
Когда ставите breakpoint, не предупреждает ли Visual Studio о том, что точка останова не сможет сработать? Не выглядит ли breakpoint как disabled? Обычно там сразу и причина указывается. Например, инструкция, на которой вы хотите остановить выполнение, может быть выброшена при оптимизации при сборке в конфигурации Release.
