### ISSUE TITLE
Время обновления PluginSettings.

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#30]
Добрый день.
Подскажите, пожалуйста, какое время проходит до обновления фронтом информации, получаемой с помощью Integration.GetPluginSettings?
Ввиду отсутствия понимания, сейчас приходится удалять entities с фронта для скорости.

**Comment by ierof** [comment]
Вообще, каждый вызов `GetPluginSettings` это получение актуального состояния того, что лежит в entities.sdf 
Соответственно, чтобы после обновления каких-либо настроек получились актуальные данные, нужен такт общения фронт -> сервер -> фронт (все фронты группы). 
При стабильной связи фронта с сервером это происходит в течение нескольких секунд точно. А скорее всего быстрее.

Если у вас есть какие-то проблемы, которые решаются только удалением entities.sdf, можете привести пример кода, который вы используете для диагностики и который работает неправильно, не так, как вы ожидаете. 

На всякий случай уточню, что метод `Integration.GetPluginSettings()` получает экземпляр объекта `IApiPluginSettings` по состоянию на момент вызова и при изменениях сущности в iikoFront данный API-объект автоматически не меняется. Его нужно заново запрашивать от iikoFront.

**Comment by CLTanuki** [comment]
Сейчас ещё немного доисследуем и выложу. Спасибо.

**Comment by vcpp** [comment]
> При стабильной связи фронта с сервером это происходит в течение нескольких секунд точно. А скорее всего быстрее.

Там же long polling, никаких нескольких секунд, немедленно при наличии связи.

> Сейчас ещё немного доисследуем и выложу. Спасибо.

Прошло две недели, будем считать, что уже неактуально. Тем не менее, если остались вопросы или появится новая информация, пишите :-)
