### ISSUE TITLE
Права необходимые плагину для проведения оплаты.

### ISSUE THREAD

**Issue by aitkkia** [iiko/front.api.sdk#300]
Добрый день.
В тестовом окружение использовался pin для учётной записи уровня ADM.
![image](https://user-images.githubusercontent.com/59682448/144035361-419fd10a-2232-423d-962b-712f71420b57.png)
![image](https://user-images.githubusercontent.com/59682448/144035408-361ba34e-27a7-493d-b2b1-9eab0a4202ce.png)

У клиента плагину не выдали права ADM, но проставили права согласно возможно необходимым.
При выполнение AddExternalPaymentItem IIKO выдала сообщение об ошибке:
Actions AddExternalPaymentItem require permission Проводить административные операции с платежными системами.

После чего плагину были добавлены права.
![WhatsApp Image 2021-11-30 at 14 26 23](https://user-images.githubusercontent.com/59682448/144036015-e4b3ceb9-d550-4e22-9af8-4710fa23634b.jpeg)
Проводить административные операции с платежными системами.
При повторной попытке ошибка не изменилась. 
Подскажите какие права и настройки должны быть у плагина для добавления типа оплаты/ProcessPrepay/PayOrder?
Логи во вложение.
[log.zip](https://github.com/iiko/front.api.sdk/files/7625208/log.zip)

[2021-11-30 11:04:23,933] ERROR [65] - Ошибка оплаты заказа.
Resto.Front.Api.Exceptions.PermissionDeniedException: Actions AddExternalPaymentItem require permission Проводить административные операции с платежными системами.

Server stack trace: 
   в Resto.Front.Api.V6.Editors.EditSessionWriter.CheckPermission(IUser user, Permission permission, String actions) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Editors\EditSessionWriter.Checks.cs:строка 765
   в System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext) в d:\a\1\s\Ix.NET\Source\System.Interactive\System\Linq\Operators\ForEach.cs:строка 24
   в Resto.Front.Api.V6.OperationService.SubmitChanges(IUser user, IEditSession editSession) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\OperationService.cs:строка 1585
   в Resto.Front.Api.V6.OperationService.Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Operations.g.cs:строка 2395
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession)
   в Resto.Front.Api.Extensions.OperationServiceExtensions.AddExternalPaymentItem(IOperationService operationService, Decimal paymentSum, Boolean isProcessed, IPaymentItemAdditionalData additionalData, IPaymentType paymentType, IOrder order, ICredentials credentials)
   в Resto.Front.Api.Tapper.Api.TapperServiceImpl.PaymentOrder(OrderPayment request, String AuthId) в D:\Work\Project\CSharp\iiko\Tapper\Source\Resto.Front.Api.Tapper\Api\TapperServiceImpl.cs:строка 184

**Comment by igorpooh1978** [comment]
Добрый вечер, а гулька на "Только для плагинов" где ?

**Comment by aitkkia** [comment]
> Добрый вечер, а гулька на "Только для плагинов" где ?

Добрый день.
В итоге стали применять пин-код "12344321".
Спасибо всем.
