### ISSUE TITLE
Доставка как услуга.

### ISSUE THREAD

**Issue by MubinjonMuinov** [iiko/front.api.sdk#302]
Вот уже 6 месяцев мы работаем и наслаждаем работой iiko, мы используем почти все ПО iiko, но один наши поступки нас дают покой. У нас есть кол центр клиенты нам звонят и мы принимаем заказы, на пример пицца, бургер и напитки. Кромы этого у нас есть товары(  блюда))))  ) "Доставка 100руб" до "Доставка 1000руб". Зависимости от местоположение клиента мы добавляем на чек "Доставка Nруб".  Когда доставщик доставит заказов они забирает "Доставка Nруб" из чека. 

Пицца 1шт 1000руб
Бургер 1шт 200руб
Доставка 1шт 100руб

ИТОГО 1300руб на чеке и на бухгалтерии тоже такая сумма но доставщик забирает за услуга 100руб в этом моменте бухгалтерия требует от кассира 1300руб как Вы уже заметили это 100% не правильно. Хотим спросить можно это как-то исправить через api(на пример удалить товар доставку из чека после печати чтобы клиент увидел сумму чека а бухгалтерию без доставки) или есть другой способ который можно сделать эту без api.? Думаю это уже есть но мы до сих пор не заметили)

**Comment by vcpp** [comment]
Прежде чем автоматизировать ваш сценарий, надо разобраться с предметной областью, чтобы, например, у налоговой не возникло вопросов, куда на пути к кассе испаряется часть уплаченной по чеку суммы. Для этого нужно знать законодательство страны, в которой вы работаете, нужно знать, какая у вас система налогообложения, как оформлены трудовые отношения с курьерами и пр. Проработкой решения на таком уровне занимаются аналитики. Вы можете начать с общения со своей бухгалтерией, привлечь аналитиков со стороны или запросить консультацию через техподдержку iiko. В результате вам, возможно, удастся настроить желаемый сценарий вовсе без нового плагина, например, через [чаевые](https://ru.iiko.help/articles/iikofront-7-9/topic-54).

На этой площадке в основном разработчики, здесь мы консультируем по техническим аспектам использования iikoFront API. Если всё-таки понадобится писать плагин и возникнут технические вопросы по использованию iikoFront API, обращайтесь, постараемся помочь.
