### ISSUE TITLE
Ограничения IEditSession при работе с заказом.

### ISSUE THREAD

**Issue by zhmpng** [iiko/front.api.sdk#304]
Доброго времени суток. Столкнулись с проблемой ограничения IEditSession, при редактирование плагином заказа, имея при этом открытый экран редактирования заказа на API 7preivew6. 

Инцидент возникает в обработчике дополнительной кнопки 
`PluginContext.Operations.AddButtonToOrderEditScreen("ITEMS SEARCH", buttonHandler, _svgImg)`

Проблема заключается в следующем, при вызове обработчика данного события, экран iikoFront блокируется прогрессбаром и все изменения внесенные в ходе работы обработчика, применяются только по окончанию его работы. Нам же нужно, чтобы экран не был блокирован и блюда добавленные в заказ сразуже отображались в самом заказе.

Все варианты реадактирования заказа имеющиеся сейчас в SDK не дают такой возможности нам. 
Вариант такой как `IOperationService` из callback обработчика работает только пока сам обработчик активен и не завершил свою работу, при этом в ходе его работы имеем блокировку экрана прогрессбаром, иначе мы получаем ошибку `System.Runtime.Remoting.RemotingException: Затребованная служба не найдена.`
Вариант использования `TryEditCurrentOrder(
	Action<(IOrder order, IOperationService os, IViewManager vm)> callback
)` так же продолжает удерживать экран заблокированым прогрессбаром и все изменения внесенные в ходе `EditSession` так же применяются только после окончания его работы. В следствии чего он нам тоже не подходит.
А вариант `PluginContextOperations.CreateEditSession()` так вообще не позволяет этого делать, возвращая ошибку `Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.`  так как `EditSession` заблокирована самим iikoFront.

В связи с чем возникает вопрос, а есть ли вообще какой то вариант это обойти? Если нет, то планируется ли вообще продвижения в сторону упращения и улучшения работы с `IEditSession`

**Comment by theDCM** [comment]
Привет. Попробуйте сделать `buttonHandler` асинхронным. Так экран блокироваться не будет.

**Comment by vcpp** [comment]
> Проблема заключается в следующем, при вызове обработчика данного события, экран iikoFront блокируется прогрессбаром и все изменения внесенные в ходе работы обработчика, применяются только по окончанию его работы.
Нам же нужно, чтобы экран не был блокирован и блюда добавленные в заказ сразуже отображались в самом заказе.

Действительно, в каждый момент времени с заказом работает кто-то один — либо пользователь, либо плагин. Нажимая на кнопку, пользователь запускает внешнюю операцию, и пока она не завершится, пользователь не может вернуться к экрану редактирования заказа. При этом плагин во время выполнения операции может показывать окна и как-то взаимодействовать с пользователем. Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html).

Расскажите, подробнее, какой сценарий вы пытаетесь реализовать? Что за операцию выполняет плагин, почему она выполняется долго и почему вы хотите, чтобы пользователь продолжал работу, не дожидаясь завершения начатой им операции?

> `TryEditCurrentOrder(Action<(IOrder order, IOperationService os, IViewManager vm)> callback)` так же продолжает удерживать экран заблокированым прогрессбаром и все изменения внесенные в ходе `EditSession` так же применяются только после окончания его работы.

Верно ли я понимаю, что вы вносите несколько изменений отдельными сессиями, между которыми большие паузы? В таком случае, ничто не мешает внести первую порцию изменений и разблокировать экран (вернуть управление из callback'а). Когда будете готовы внести вторую порцию изменений, снова вызовете `TryEditCurrentOrder`.

> В связи с чем возникает вопрос, а есть ли вообще какой то вариант это обойти? Если нет, то планируется ли вообще продвижения в сторону упращения и улучшения работы с `IEditSession`

По данному случаю пока не вполне ясно, какую задачу вы решаете, поэтому простого ответа нет. Универсальный ответ — это что мы непрерывно занимаемся упрощением и улучшением iikoFront API, и открыты к любым замечаниям и предложениям.

**Comment by zhmpng** [comment]
> Расскажите, подробнее, какой сценарий вы пытаетесь реализовать? Что за операцию выполняет плагин, почему она выполняется долго и почему вы хотите, чтобы пользователь продолжал работу, не дожидаясь завершения начатой им операции?
> 

В общем сценарий работы выглядит следующим образом. Через плагин регистрируется кнопка: `PluginContext.Operations.AddButtonToOrderEditScreen("ITEMS SEARCH", buttonHandler, _svgImg); `. Нажимая на нее, пользователю открывается дополнительное WPF окно, в котором можно произвести поиск по внешней номенклатуре (не заведенной в РМС) и соответственно добавить выбранные блюда в открытый на данный момент заказ. 
Пример добавленного окна WPF: 
![image](https://user-images.githubusercontent.com/75923630/152773885-71be8d42-1c44-4dee-b4f7-8bfa6b77a728.png)

Оно добавляется в правую часть интерфейса, как показано на примере. В момент когда данное окно открыто и полноценно функционирует, не должен быть заблокирован фронт для пользователя, т.е. можно одновременно добавлять блюда как из номенклатуры самого РМС, так и из внешней. 

Сейчас же мы не имеем возможности вносить какие либо изменения в состав заказа, пока экран редактирования заказа не будет закрыт, а нам необходимо отображать добавленные блюда из внешней номенклатуры сразу же, как это делается при добавление из номенклатуры РМС. 

Метод `TryEditCurrentOrder` так же не позволяет нам этого делать, так как он так же будет ожидать закрытия экрана редактирования заказа.

**Comment by vcpp** [comment]
> Метод `TryEditCurrentOrder` так же не позволяет нам этого делать, так как он так же будет ожидать закрытия экрана редактирования заказа.

Метод `TryEditCurrentOrder`, как и кнопка, ничего не знают про ваши окна, они просто ждут, когда вы вернёте управление из callback'а. Когда плагин вернул управление, операция считается завершённой и прогрессбар закрывается.

Теперь понятно. Вы хотите, чтобы функция кнопки «Item search» ограничивалась открытием окна внешнего поиска. Только открытием. Сам внешний поиск при этом не является частью операции, запускаемой по нажатию на эту кнопку. Обработка нажатия на кнопку должна завершаться сразу после показа окна: показали окно, вернули управление из обработчика нажатия на кнопку. Дальше пользователь сможет по своему усмотрению использовать UI iikoFront (ту его часть, что не перекрыта вашим окном), либо ваше окно. При добавлении блюд через внешний поиск можно будет использовать `TryEditCurrentOrder`.

Окно внешнего поиска будет просто висеть поверх окна iikoFront, можете закрыть его при повторном нажатии на кнопку «Item search», либо при навигации на другой экран ([`INotificationService.ScreenChanged`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_ScreenChanged.htm)). Для красоты, конечно, следовало бы сделать кнопку «Item search» залипающей, но пока залипающие кнопки, как и обновление внешнего вида кнопок на лету [поддерживаются](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_UpdatePaymentScreenButtonState.htm) только на экране оплаты. Как только добавим аналогичную возможность для кнопок на экране редактирования заказа, надо будет доработать плагин, чтобы при открытом окне внешнего поиска кнопка отображалась зажатой (checked), а при закрытом — отжатой (unchecked).

> Пример добавленного окна WPF

Это скриншот из доработки, сделанной в 8.0.1. Правда, наш поиск ищет только по внутренней номенклатуре.
