### ISSUE TITLE
Хэндлер операции BeforeOrderBill в режиме ресторана вызывается не во всех экземплярах плагина.

### ISSUE THREAD

**Issue by kolan72** [iiko/front.api.sdk#305]
Экземпляры плагина нашей системы лояльности установлены на всех терминалах, используется режим ресторана. Оплата и/или привязка  клиента к нашей системе лояльности может происходить на всех терминалах.

Флаг `IsSingleInstance`  в манифесте отсутствует.

На одном терминале (далее - терминале привязки клиента) мы оформляем заказ с привязкой клиента вплоть до перехода в режим кассы, на другом(далее - терминале оплаты), переходим в режим кассы и пытаемся заказ оплатить.
Оплата происходит без ошибок, но заказ в нашей системе оказывается не корректным - у объекта заказа отсутствуют свойства клиента, наполнение которых  должно происходить в методе обработчика `BeforeOrderBill` на терминале привязки.

Кроме того, первой строкой метода обработчика `BeforeOrderBill` мы пишем отладочное сообщение в лог, но на терминале привязки клиента соответствующей записи в логе нет, из чего мы и сделали вывод, что вызов обработчика происходит только на терминале оплаты.

Подписка на событие `BeforeOrderBill` происходит в конструкторе плагина, вызовом `PluginContext.Notifications.BeforeOrderBill.Subscribe(beforeOrderBillHandler.Handle)`.

В обработчике `BeforeOrderBill` мы в том числе валидируем количество бонусов-позиций заказа в нашей системе лояльности и отказаться от него на данный момент не можем.

Тестирование проводилось на последних версиях Resto.Front.Api.V7Preview7.dll,  Resto.Front.Api.V7Preview6.dll.

**Comment by kolan72** [comment]
P.S. Данная проблема - полное отсутствие вызова обработчика наблюдается при использовании Resto.Front.Api.V7Preview7.dll версии 7.7.6020-alpha. для

**Comment by letolica** [comment]
Добрый день.
Данное событие генерируется непосредственно на том фронте, на котором происходит перевод статуса заказа в пречек. Перевод заказа в пречек может происходить на любом фронте, соответственно, ваш плагин, подписанный на `BeforeOrderBill`, должен быть установлен на всех фронтах. И это событие получит тот плагин, чей фронт перевел заказ в соответствующий статус.
