### ISSUE TITLE
Нам помогли с продлением лицензии, но, кажется, все поломалось.

### ISSUE THREAD

**Issue by darktwister1337** [iiko/front.api.sdk#306]
Добрый день, разрабатываем плагин под iikoFront. Изначально, как было указано на сайте, хотели получить лицензию разработчика. Но нас вежливо проигнорировали два месяца, отчего пришлось покупать лицензию.

В ближайшем прошлом (буквально неделю назад), у нас закончилась лицензия. Описали ситуацию с трудностями со стороны iiko, лицезнию нам продлил персональный менеджер. Но возникла какая-то проблема при дебаге плагина. 

Сразу после продления лицензии на моей машине начала выбрасываться ошибка "`Cannot connect “Debug” launched outside the iikoFront.`", после нее с разницей в буквально пару минут - "`Не удалось подключиться к IPC-порту`", а у моего товарища (решили проверить на другом компьютере) выбрасывается ошибка.
"`Cannot connect “Debug” launched outside the iikoFront`."

Порылся в предыдущих issues, нашел, что проблема может быть с лицензией. Написал менеджеру, он сказал, что все возможные модули активны, включая лицензию на разработку плагина. Куда рыть дальше - не ясно.
Время идет, лицензия уходит, а зацепок куда копать вообще нет =)

Ничего не менялось, просто в iikoOffice была нажата кнопка "Установить лицензию", но почему-то все перестало работать...

Не подскажите, в чем может быть проблема?

**Comment by letolica** [comment]
Добрый день.
Ошибка с текстом `"Cannot connect “Debug” launched outside the iikoFront."` выбрасывается в случае, когда плагин подключается к фронту из-вне, например из [Visual Studio для отладки](https://iiko.github.io/front.api.doc/v6/ru/Debugging.html), и в текущей действующей лицензии не представлен модуль разработчика плагинов (PluginDeveloper).
