### ISSUE TITLE
Получение списка концепций с RMS

### ISSUE THREAD

**Issue by denis660** [iiko/front.api.sdk#307]
Здравствуйте.
Как получить список концепций и кодов концепци с RMS ?

у RMS есть справочник https://ru.iiko.help/articles/#!api-documentations/entities-list

Но там нельзя получить список концепций, приходится делать OLAP отчет, можно с этим смириться. Есть только проблема, пока не пройдут первые продажи, в OLAP отчете не получить эти концепции. 
Концепции нам необходимы для настройки собственной интеграции с IIKO, думаю многим это было бы полезно

**Comment by denis660** [comment]
Не нашел раздела по RMS, чтобы там создать Issues , поэтому написал сюда 🤷‍♂️

**Comment by vcpp** [comment]
> Не нашел раздела по RMS

К сожалению, для iikoServer API аналогичной площадки нет. Вы можете задать вопросы по электропочте: api@iiko.ru.
