### ISSUE TITLE
Как получить идентификатор модуля лицензии

### ISSUE THREAD

**Issue by nurillaxoja** [iiko/front.api.sdk#308]
Здравствуйте.
Я написал плагин и у меня есть вопрос   
1.  Как можно в iikoFront или iikoOffice посмотреть License ModuleId который использоваться в плагине

**Comment by vcpp** [comment]
Непонятный вопрос. Вы разрабатываете плагин и хотите узнать, откуда взять moduleId для вашего плагина?
Вам [сюда](https://iiko.github.io/front.api.doc/v6/ru/Licensing.html):

> Для регистрации, получения лицензии разработчика, получения идентификатора лицензируемого модуля и заключения договора необходимо отправить заявку по адресу [api@iiko.ru](mailto:api@iiko.ru).
