### ISSUE TITLE
ExternalHierarchy Id

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#31]
Коллеги, мы тут смотрим в тип данных ExternalHierarchy (выгрузка в iikoBiz) и видим, что он имеет Id. Однако, не очень понятно, что же он означает. Формально, это кажется похожим на возможность хранения разных ExternalHierarchy для разных целей.
Вопрос: насколько кощунственным будет добавление рядом нового экземпляра ExternalHierarchy с новым Id для использования в целях отдельностоящего приложения?

**Comment by ierof** [comment]
Боюсь, что на этой площадке нет никого, кто обладал бы экспертизой по iiko.biz API, тут только евангелисты iikoFront API, а это два не пересекающихся проекта в iiko с разными командами разработки. 
Поэтому рекомендую написать на api@iiko.ru этот вопрос. 

Но с точки зрения моих общих знаний iikoBiz и здравого смысла ваша идея звучит разумно :)

**Comment by Fulborg** [comment]
Увы, это одна из тех вещей, которые закладывались на этапе проектирования системы, но так и не были воплощены в жизнь. В целом, не делалось явных ограничений что "ExternalHierarchy должна быть единственной и уникальной", и когда-то давным давно даже подразумевалось что их станет несколько, они все будут выгружаться в iiko.biz в API и будут доступны пользователям. Но потом от этой идеи отказались и сейчас подразумевается что эта сущность будет представлена в единственном экземпляре. Сходу прошелся - не увидел мест, где наличие второй такой сущности что-нибудь сломало бы, но не советовал бы это делать, потому что:
1) Могут все же быть какие-то узкие места, которые перестанут работать
2) Я точно не готов подписаться, что мы не сломаем эту совместимость в будущем, положившись на то что эта сущность должна быть уникальна, сейчас это негласно подразумевается.
