### ISSUE TITLE
Доступ к текущей организации из плагина

### ISSUE THREAD

**Issue by Anton-Grebenkin** [iiko/front.api.sdk#310]
Для интеграции с нашей системой лояльности, нам необходимо по апи выгружать номенклатуру, организации и кассиров из iiko, а потом при проведении продажи из плагина, понимать в какой организации проводится продажа. Есть такая возможность?

**Comment by letolica** [comment]
Добрый день.
Вы имеете в виду настройки текущего торгового предприятия?
[IOperationService.GetHostRestaurant](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetHostRestaurant.htm)

**Comment by Anton-Grebenkin** [comment]
Спасибо
