### ISSUE TITLE
TryGetOrderExternalDataByKey возвращает "null" вместо null

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#311]
`string data = _operationService.TryGetOrderExternalDataByKey(_order.Id, "dataKey");`
В случае, если по ключу данные отсутствуют, то data = "null", а не null.

**Comment by vcpp** [comment]
Вы хотите сказать, что вместо нулевой ссылки (`null`) получаете строку с текстом "null"?

Проведите эксперимент — вместо ключа, который вы обычно используете при вызове `AddOrderExternalData`, используйте при чтении какой-нибудь другой гарантированно несуществующий ключ. Например, так: `PluginContext.Operations.TryGetOrderExternalDataByKey(order, Guid.NewGuid().ToString())`. Так мы проверим, а действительно ли запись с указанным ключом не существует. Вероятно, ваш или другой плагин раньше записали в заказ строку с текстом "null" и ключом "dataKey" (`PluginContext.Operations.AddOrderExternalData("dataKey", "null", false, order, credentials)`).
