### ISSUE TITLE
Изменить статус доставки до логического конца.

### ISSUE THREAD

**Issue by MubinjonMuinov** [iiko/front.api.sdk#314]
1) Принимаем заказ
2) Изменяем статус заказ через кухонный экран. ("Приготовлено")
3) Фасовщик упокоевают по чеку и изменяет статус на "Подано"
4) Через FrontApi мы изменяем статусы заказов на "Waiting" и потом на "OnWay"

```
                var TokenID = new Guid(Token);
                var credentials = PluginContext.Operations.AuthenticateByPin("2581");
                if (PluginContext.Operations.IsDeliveryConfirmationActive())
                {
                    var delivery = PluginContext.Operations.GetDeliveryOrders().LastOrDefault(d => d.Id == TokenID);
                   
                    PluginContext.Operations.PrepareDeliveryForSending(credentials, delivery);
                    delivery = PluginContext.Operations.GetDeliveryOrderById(delivery.Id);
                    Debug.Assert(delivery.DeliveryStatus == DeliveryStatus.Waiting);
                    
                    delivery = PluginContext.Operations.GetDeliveryOrderById(delivery.Id);
                    PluginContext.Operations.SendDelivery(credentials, delivery);
                    delivery = PluginContext.Operations.GetDeliveryOrderById(delivery.Id);
                    Debug.Assert(delivery.DeliveryStatus == DeliveryStatus.OnWay);
                }
```
 5) После "В пути" доставщик доставляет заказ и нажимает кнопку "Доставлено"("iikoDeliveryMan")
6) После 2 минуты ожидание "iikoDeliveryMan" даёт ошибку "Выбранной точке приготовления не удалось принять доставку. Обратитесь в службу поддержки: Can change property Address only if delivery is in Unconfirmed or New status.".

Мы работаем по схему:
-Коллцентр принимает заказ отправит в точку(там их несколько).
-Точки готовить заказ.  
-Доставщик доставить заказ.

у всех есть своя программа(CallCanter, Front, iikoDeliveryMan)

**Comment by letolica** [comment]
Добрый день.
Указанный вами код не может выдать ошибку вида `"Can change property Address only if delivery is in Unconfirmed or New status."`. Данная ошибка может возникнуть только при вызове [ChangeDeliveryAddress](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_ChangeDeliveryAddress.htm), когда на момент вызова доставка в любом статусе, кроме Unconfirmed или New.

**Comment by MubinjonMuinov** [comment]
Но мы вообще не изменяем адрес, кроме этого эту функцию ChangeDeliveryAddress мы первый раз увидели здесь.

**Comment by vcpp** [comment]
> "iikoDeliveryMan" даёт ошибку

А при чём тут ваш плагин? Если я правильно понял, ваш плагин отправляет доставку в путь, и она таки отправляется в путь. Тут всё хорошо.
С проблемами в работе iikoDeliveryMan лучше обращаться в техподдержку. Могут быть проблемы в цепочке через iiko.biz или iikoTransport, не связанные с вашим плагином. Для проверки можете попробовать отправить доставку в путь без использования вашего плагина, просто руками через UI приложения iikoFront.
