### ISSUE TITLE
Получение CurrencyCode

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#318]
Добрый день
Подскажите пожалуйста как получить CurrencyCode ?

в
'''
PluginContext.Operations.GetHostRestaurant().Currency
'''
можно получить только символ валюты, а вот код валюты (iso4217) и 3х буквенное обозначение нельзя.

**Comment by vcpp** [comment]
К сожалению, пока такой возможности нет. Постараемся добавить в V8.

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/2022/09/30/currency-details.html
Появилось в iiko 8.3
