### ISSUE TITLE
Закрытие заказа

### ISSUE THREAD

**Issue by xwwh** [iiko/front.api.sdk#32]
Подскажите пожалуйста как можно закрыть (оплатить) заказ через API?
Попробовал вызвать метод [IOperationService.PayOrder](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_PayOrder.htm), но получил ошибку "Method “PayOrder” isn't licensed."

**Comment by ierof** [comment]
У нас немного некорректно написана [статья про типы лицензий API](https://ru.iiko.help/articles/#!api-documentations/apistart). 

Для операций оплатного контура (в том числе таких как закрытие заказа) требуется ключ формата iikoAPIPayment. 
Из внутренней документации по лицензированию
> ModuleID оканчивается на 08: можно создавать тип оплаты.
ModuleID оканчивается на 18: можно создавать тип оплаты, можно добавлять оплаты в заказ, можно оплачивать дистанционно.
