### ISSUE TITLE
BillChequePrinting происходит дважды

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#320]
Сценарий: перед печатью пречека провести транзакцию, добавить информацию о транзакции в пречек.

В конструкторе класса подписались на _BillChequePrinting_:
`PluginContext.Notifications.BillChequePrinting.Subscribe(ChequeAppend)`

<details>
  <summary>ChequeAppend(Guid guid)</summary>

```
PluginContext.Log.Info("ChequeAppend()");
PluginContext.Log.Info("TryEditCurrentOrder(ApplyPayment)");
PluginContext.Operations.TryEditCurrentOrder(ApplyPayment);
PluginContext.Log.Info("Edited");
return new BillCheque();
````
</details>

<details>
  <summary>ApplyPayment((IOrder, IOperationService, IViewManager) context)</summary>

`PluginContext.Log.Info("Apply payment");`
</details>

<details>
  <summary>Лог</summary>

```
[2022-01-30 19:21:04,997]  INFO [12] - ChequeAppend()
[2022-01-30 19:21:04,998]  INFO [12] - TryEditCurrentOrder(ApplyPayment)
[2022-01-30 19:21:05,000]  INFO [ 6] - ChequeAppend()
[2022-01-30 19:21:05,001]  INFO [ 6] - TryEditCurrentOrder(ApplyPayment)
```
</details>

Других записей, связанных с описанными функциями, нет.

Является ли это поведение ожидаемым? Видимо, _TryEditCurrentOrder(ApplyPayment)_ триггерит _BillChequePrinting_ ещё раз. Как можно этого избежать?

UPD: если убрать _TryEditCurrentOrder(ApplyPayment)_, _ChequeAppend()_ также вызывается дважды. Баг ли это?

**Comment by vcpp** [comment]
1. Обработчик может вызываться несколько раз, если он несколько раз подписан на событие или если событие происходит несколько раз. Обе гипотезы можно проверить по логу *api.log*. Впрочем, наличия багов тоже нельзя исключать, поэтому если ни одна из двух указанных выше гипотез не подтвердится, понадобятся логи (папка *%AppData%\iiko\CashServer\Logs*).
2. Редактирование заказа при обработке уведомления `BillChequePrinting` невозможно, т.к. у обработчиа нет специального локального экземпляра `IOperationService`, как это бывает в некоторых других уведомлениях, а использование глобального `PluginContext.Operations` будет приводить к `EntityAlreadyInUseException`. В вашем примере метод `ChequeAppend` не обрабатывает данное исключение, оно улетит в источник уведомления и приведёт к отписке «сломанного» обработчика. Чтобы иметь возможность редактировать заказ, подпишитесь на [`BeforeOrderBill`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeOrderBill.htm). Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html).
