### ISSUE TITLE
Интеграция с бонусной системой через плагин SamplePaymentPlugin

### ISSUE THREAD

**Issue by zhanjkee** [iiko/front.api.sdk#323]
Здравствуйте!

Пишу интеграцию с внешней бонусной системой и для его реализации выбрал шаблон плагина "SamplePaymentPlugin".
Через плагин необходимо начислять и списывать бонусы клиента.

У меня возникли трудности с начислением бонуса. Не получается провести оплату с 0 суммой через плагин. (Тип оплаты удаляется из списка автоматический если добавить "Наличные" или "Банковские карты") То есть не будет вызов метода IPaymentProcessor.Pay()

Попробывал подписаться на событие PluginContext.Notifications.CashChequePrinting. Все ок, но событие не всегда отрабатывает (по непонятной мне причине).

Подскажите пожалуйста, есть ли какой-нибудь другой метод, который может помочь?

Исходный код: https://github.com/zhanjkee/iiko-sagi/blob/master/src/Resto.Front.Api.Sagi.Plugin/ExternalPaymentProcessor.cs

**Comment by vcpp** [comment]
Duplicates #299,

Чтобы не писать одно и то же там и тут, предлагаю закрыть эту задачу и продолжить в #299. Посмотрите [этот](https://github.com/iiko/front.api.sdk/issues/299#issuecomment-1030912199) комментарий, там есть вопросы, изначально заданные по другому случаю, но касающиеся и вашего случая тоже.

**Comment by zhanjkee** [comment]
> Duplicates #299,
> 
> Чтобы не писать одно и то же там и тут, предлагаю закрыть эту задачу и продолжить в #299. Посмотрите [этот](https://github.com/iiko/front.api.sdk/issues/299#issuecomment-1030912199) комментарий, там есть вопросы, изначально заданные по другому случаю, но касающиеся и вашего случая тоже.

Ок, спасибо)
