### ISSUE TITLE
Метод IOperationServicePayOrder выбрасывает PaymentActionFailedException.

### ISSUE THREAD

**Issue by AlexDragonLore** [iiko/front.api.sdk#325]
У клиента при оплате заказа дистанционно, иногда выбрасывается ошибка PaymentActionFailedException, непонятно в чем проблема, потому что это плавающая ошибка, и проблема точно не в типах оплаты, тк эта ошибка встречается 1 к 50 оплат. 
Вот ошибка, логи за день тоде прикладываю:

 Error in AddPayOrder method Resto.Front.Api.Exceptions.PaymentActionFailedException: В заказе уже есть элементы оплаты. Дистанционная оплата невозможна.

Server stack trace: 
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\OperationServiceInternal.cs:строка 991
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\OperationServiceInternal.cs:строка 999
   в Resto.Front.Api.V7Preview6.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview6\Operations.g.cs:строка 2610
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
[logs.zip](https://github.com/iiko/front.api.sdk/files/8041698/logs.zip)

   в BeOpen.Plugins.Front.Paybo.ProcessingRequests.Helpers.PayOrder(Guid reserveId, ICredentials credentials, List`1 payments, List`1 surcharges) в C:\Users\
[logs.zip](https://github.com/iiko/front.api.sdk/files/8041662/logs.zip)
Alex\Source\Repos\beopen.plugins.paybo\BeOpen.Plugins.Front.Paybo\ProcessingRequests\Helpers.cs:строка 111

В чем может быть проблема?
Спасибо.

**Comment by vcpp** [comment]
> Вот ошибка, логи за день тоде прикладываю

Спасибо, что сразу логи приложили, там можно найти чуть более понятное объяснение:
```
[2022-02-08 16:15:13,927]  WARN [116] [MainCashOrderPaymentService:PayOrderAndPayOutOnUser] - Payment of order f9387ed3-a239-40c5-9618-69a8f93b0896 failed. Cannot process not silent payment item e6a861fa-ff44-4f33-a072-2bd919686651 of payment type ea6b84a9-eb8c-4f61-b75d-67d66f7297cc.
```

Судя по всему, ваш собственный тип оплаты «Paybo баллы BMB» (ea6b84a9-eb8c-4f61-b75d-67d66f7297cc) не поддерживает «тихую» оплату, то есть метод [`CanPaySilently`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPaymentProcessor_CanPaySilently.htm) возвращает `false`. Если на самом деле проведение оплаты не требует показа окон или иного взаимодействия с пользователем, возвращайте `true`, тогда ваш тип оплаты можно будет использовать не только с экрана оплаты, но и через API, а также дистанционно с других терминалов. Краткая инструкция по этой фиче [тут](https://iiko.github.io/front.api.doc/2020/11/09/silent-plugin-payments.html), полная статья [здесь](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html).
