### ISSUE TITLE
Обработать предоплату в момент формирования пречека

### ISSUE THREAD

**Issue by delta81** [iiko/front.api.sdk#326]
Сценарий: добавить в заказ внешнюю нефискальную оплату как предоплату при формировании пречека.

Чтобы обработать событие формирования пречека, подписались на `BeforeOrderBill`. Но метод `ProcessPrepay()` должен быть вызван с помощью глобального `IOperationService`, который ожидаемо выдаёт `EntityAlreadyInUseException`.

Означает ли это, что добавление предоплаты в заказ при формировании пречека невозможно?

**Comment by vcpp** [comment]
> Означает ли это, что добавление предоплаты в заказ при формировании пречека невозможно?

Добавить-то `IPaymentItem` можно, но выполнить проведение в обработчике `BeforeOrderBill` не удастся, да.
У платёжных операций часто более строгие ограничения, чем у простого редактирования.
В качестве корявого альтернативного решения можно попробовать отменять пречек, выбрасывая `OperationCanceledException` с сообщением пользователю «Всё хорошо, просто выйди из редактора заказа», дождаться навигации с этого экрана, затем провести предоплату и уже самим из плагина напечатать пречек. Выглядеть, конечно, будет странно, да и если операция инициирована не с UI, а, например, другим плагином (мобильный терминал), то другой плагин может не понять.
