### ISSUE TITLE
Customization of ExtendedInputDialog

### ISSUE THREAD

**Issue by hamaronooo** [iiko/front.api.sdk#327]
Здравствуйте! **v7Preview7**
Подскажите пожалуйста, существует ли способ кастомизировать окно ShowExtendedInputDialog при запросе Barcode?
Хотелось бы убрать данный "калькулятор" (как на скриншоте) ну или хотябы сделать вместо него нормальную клавиатуру, т.к. те QR коды, которые мы сканируем содержат как буквы, так и цифры.

Мой вызов диалога:
```
var settings = new ExtendedInputDialogSettings
{
    EnableBarcode = true,
    TabTitleBarcode = "QR код"
};
IInputDialogResult dialogResult = vm.ShowExtendedInputDialog(
                "Отсканируйте QR код клиента системы Momentum",
                "НЕ используйте клавиатуру расположенную ниже",
                settings);

switch (dialogResult)
{
    case null:
        break;
    case BarcodeInputDialogResult barcode:
        code = barcode.Barcode;
        break;
    default:
        throw new NotSupportedException(nameof(dialogResult.GetType));
}
```

Еще есть следующте методы, но нет типа `Barcode`:
```
var result1 = (BarcodeInputDialogResult)vm.ShowInputDialog("", InputDialogTypes.Card);
var result2 = vm.ShowInputDialog("", InputDialogTypes.Number);
```

Дело в том, что такой вид диалога (с возможностью ручного ввода) может сбивать с толку кассира.
Мог я что-либо упустить?

![image](https://user-images.githubusercontent.com/61544995/153864256-3f3b69cb-052d-4828-ac50-3cdf1613d648.png)

**Comment by vcpp** [comment]
> существует ли способ кастомизировать окно ShowExtendedInputDialog при запросе Barcode?
> Хотелось бы убрать данный "калькулятор" (как на скриншоте)

Увы, для штрихкода такой вариант не предусмотрен. Предполагали, что штрихкоды иногда плохо считываются (деформации/повреждения/блики и пр.), и их может понадобиться ввести вручную. Ориентировались, правда, на наиболее распространённые линейные цифровые штрихкоды вроде EAN13, не подумали про двумерные, буквенно-цифровые. Для QR-кодов возможность ручного ввода практически не имеет смысла, надо для этого какой-то флажок предусмотреть. Эти коды обычно хорошо считываются, а если уж не считается, то не судьба, никто не будет вводить длинную буквенно-цифровую комбинацию.

То, что вы хотите, прямо сейчас реализовано для считывателя карт — при вызове `ShowExtendedInputDialog` с единственным флагом `ExtendedInputDialogSettings.EnableCardSlider` показывается окно без цифровой клавиатуры с приглашением прокатать карту (аналогично окну проверки права). Если сканер штрихкода используется только для вашего плагина, можно попробовать настроить его как считыватель карт.

> ну или хотябы сделать вместо него нормальную клавиатуру

Это работает хоть сейчас:
```cs
var dialogResult = vm.ShowExtendedKeyboardDialog("Отсканируйте QR код клиента системы Momentum", enableBarcode: true);
```

Будет буквенно-цифровая клавиатура с возможностью отсканировать штрихкод. На выходе `StringInputResult` для вручную введённой строки, либо `BarcodeInputResult` для штрихкода.
