### ISSUE TITLE
Уведомление об оплате заказа

### ISSUE THREAD

**Issue by KonstantinZalomov** [iiko/front.api.sdk#33]
Для интеграции с внешней бонусной системой нам нужно сообщать удаленному серверу о списании и начислении баллов.

Для списания используем IExternalPaymentProcessor, при наличии нашей оплаты баллами срабатывает метод Pay где можно пообщаться с сервером и сообщить, сколько баллов было потрачено.

Вопрос: где можно пообщаться с сервером, чтобы сообщить ему об оплате заказа рублями (и где можно спросить у кассира идентификатор гостя) ? По нашей логике, в таком случае гость должен получать на свой счёт 10% от суммы, оплаченной в рублях (нужно сообщить нашему серверу, что гость с идентификатором M оплатил N рублей; в случае возврата также нужно сообщить).

Пробовали добавлять на кассе оплату нашим типом с нулевой суммой - но это не очень удобно, вылезает предупреждение для кассира, и метод Pay для нулевой оплаты не срабатывает.

Подскажите, как можно решить нашу задачу?

**Comment by ierof** [comment]
Добрый день!

К сожалению, прямого пути реализовать это через API iikoFront нет. 
Если вы как-то обратитесь в тех.поддержку iiko или ваш заказчик обратится к своему партнёрскому менеджеру по поводу этой проблемы, то стоит упомянуть необходимость доработки номер RMS-32765 *(iikoFront API для интеграции с Бонусными системами)*
Пока она не имеет версии реализации => гарантий, что она будет сделана, нет. 

Какие WA я могу вам рекомендовать, чтобы получить возможность взаимодействия с юзером на экране кассы:
- всё-таки, через добавление оплатного айтема. Но сам айтем в заказ в итоге не добавлять, а в где-то у себя сохранять, что для заказа с таким-то ID нужно выполнить вот такие-то бонусные механики при закрытии.

Как правильно отследить закрытие заказа:
- либо посмотреть, что было рекомендовано в аналогичном вопросе (https://github.com/iiko/front.api.sdk/issues/7)
- либо посмотреть класс-пример `OrderStatusChangeNotifier` в SDK от версии iiko 6.4
