### ISSUE TITLE
Скидки через iikoFront Api

### ISSUE THREAD

**Issue by ualieva** [iiko/front.api.sdk#330]
Добрый день! 
Можем ли мы через iikoFront Api передавать скидки на блюда, а не на весь заказ используя:
1. CanApplySelectively  - признак, что скидку можно применить не к заказу,  а к позиции отдельно
2. ChangeSelectiveDiscount  - функцию, с помощью которой указывается к какой позиции нужно применить скидку

**Comment by aitkkia** [comment]
https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Orders_IDiscountType_CanApplySelectively.htm

https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_OperationServiceExtensions_ChangeSelectiveDiscount.htm

**Comment by vcpp** [comment]
> Можем ли мы через iikoFront Api передавать скидки на блюда, а не на весь заказ

Да, можете.
Почитайте [статью](https://iiko.github.io/front.api.doc/v6/ru/Discounts.html), посмотрите [примеры](https://github.com/iiko/front.api.sdk/blob/master/sample/v7/Resto.Front.Api.SamplePlugin/EditorTester.cs). Если что-то не будет получаться или возникнут дополнительные вопросы — пишите.
