### ISSUE TITLE
Получение через ApiFront имя Таба

### ISSUE THREAD

**Issue by AndruBerzin** [iiko/front.api.sdk#332]
Добрый день!
Подскажите возможно через ApiFront получить имя Таба?
Не могу найти.

**Comment by Keeplod** [comment]
что за таб?)

**Comment by letolica** [comment]
Добрый день.
@AndruBerzin, имя таба сожержится в заказе: [`IOrder.TabName`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_TabName.htm).
@Keeplod, вот статья: [Режим табов](https://ru.iiko.help/articles/#!iikofront-7-9/topic-69).
