### ISSUE TITLE
Звук на принтер при печати через api

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#336]
Добрый день. В Документации есть теги https://iiko.github.io/front.api.sdk/v7/html/Fields_T_Resto_Front_Api_Data_Cheques_Tags.htm для печати. Есть ли тег для звука на принтер ?
У клиента при печати из айки звук на звонок включенный в принтер идет. А при печати через API не идет. Хотелось бы понять почему и как это исправить ?

**Comment by letolica** [comment]
Добрый день. Для звонка на принтер или открытия денежного ящика, привязанного к принтеру, предусмотрен атрибут звонка к тегу документа, значение которого надо оставить пустым:
```
<doc bell="">
...
</doc>
```
Для удобства использования у нас есть и строковая константа: [`Bell`](https://iiko.github.io/front.api.sdk/v7/html/F_Resto_Front_Api_Data_Cheques_Attributes_Bell.htm)
