### ISSUE TITLE
Получить данные из персональной карточки официанта

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#337]
Доброго времени суток,
Мы разрабатываем сейчас плагин, у нас задача получить привязанные данные из карточки сотрудника. Я не нашёл ничего касаемого этого вопроса внутри `IUser`? Что можете посоветовать? Есть ли альтернативы?
iikoFront.API v7
![image](https://user-images.githubusercontent.com/22041710/156728681-f78b66f0-5f9f-48d8-b62b-cdf6f5fc386d.png)

**Comment by Azamatjon** [comment]
@vcpp @ierof Есть какие нибудь варианты?

**Comment by mkobozev** [comment]
@Azamatjon добрый день!
Опишите сценарий в котором вам нужно задействовать поле комментарий из карточки сотрудника ?

**Comment by letolica** [comment]
Данное поле невозможно получить через апи фронта. Оно даже во фронт не выгружается. Как вариант, рассмотреть апи сервера.
