### ISSUE TITLE
IUser  в ICredentials

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#34]
Добрый день. Через уведомление INotificationService.UserChanged перехватил пользователя который сейчас открыл смену. Получил IUser теперь хочу под этим пользователем создать заказ. Как из имеющегося IUser получить ICredentials ?

По заявке id37639201 сказали обратиться тут

**Comment by vcpp** [comment]
> Как из имеющегося IUser получить ICredentials ?

Никак.
Для выполнения операций от имени какого-то пользователя необходимо знать его пин-код и получать `ICredentials` вызовом [`AuthenticateByPin`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_AuthenticateByPin.htm).

Вообще для плагина, создающего заказы в фоне без ведома сотрудника, лучше завести отдельную учётку, не приписывать человеку действия, которые он не совершал, это позволит раздельно настраивать права для плагина и для сотрудников, раздельно видеть действия плагина и сотрудников в журнале событий и так далее. Пока для этого нужно вручную создать учётную запись в iikoOffice, включить галочку «Только для плагинов», назначить пин-код и прописать этот пин-код где-то в конфиге плагина, чтобы он мог им пользоваться. В одной из будущих версий сделаем автоматическое создание учётки для плагина.

**Comment by ierof** [comment]
Добавлю, что возможность получать через `IUser` его `ICredentials` это аналогично тому, чтобы хранить ключи от квартиры в замочной скважине снаружи или пароль на наклейке на мониторе :) 

В iiko есть система прав и ограничений. И если бы плагин мог сначала выбрать нужного ему юзера, а потом посмотреть его пароль, это бы открывало дыру в безопасности.
