### ISSUE TITLE
Получить ID заказа.

### ISSUE THREAD

**Issue by MubinjonMuinov** [iiko/front.api.sdk#340]
Добрый день коллеги!
Недавно решили распечатать qr на чеке и проводит опрос между клиентами и записать эти опроси прямо на iiko через API вот здесь https://ru.iiko.help/articles/#!api-documentations/otzyv, у нас осталось только получить deliveryId и всё. По этому хотим спросит как получит deliveryId на вовремя печатью чека. 

Например:
var id=order.deliveryId;
`<qrcode size="normal" correction="medium"> http://site.f/?t=@id </qrcode>`

**Comment by MubinjonMuinov** [comment]
это можно использовать в шаблон чеков?

**Comment by MubinjonMuinov** [comment]
@helper Body()
{
    var delivery = Model.Delivery;
    var order = delivery.Order;

    var orderx = delivery.Id;
    // или 
   var orderx = order.Id;


  тоже ошибка

**Comment by vcpp** [comment]
> это можно использовать в шаблон чеков?

Нет, iikoFront API нельзя использовать в шаблоне чеков.
По шаблонам чеков отдельная [документация](https://ru.iiko.help/articles/#!iikooffice-7-9/topic-6), ищите нужные поля в `TemplateModels.xml`. Вероятно, вам нужны `Model.Delivery.DeliveryId` и `Model.Delivery.Order.OrderId`.
