### ISSUE TITLE
Оплата заказа без печати чека по умолчанию в рамках плагина

### ISSUE THREAD

**Issue by hamaronooo** [iiko/front.api.sdk#341]
Здравствуйте!

Подскажите пожалуйста, существует ли возможность, при наличии _телефона\email_ клиента из внутренней лояльности (клиент в контексте моего плагина), отменить печать чека (например из метода `Pay` `IPaymentProcessor`'a) и отправить чек на _телефон\email_ клиента.
Вот [тут](https://iiko.github.io/front.api.doc/v6/ru/Payments.html#%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B0-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0) у метода `PayOrder `есть перегрузка с `ChequeAdditionalInfo.chequeAdditionalInfo`, но не понятно как ей пользоваться в контексте `IPaymentProcessor`'a.

**Идея:** Не печатать чек по умолчанию, если в контексте плагина есть клиент с телефоном\email, для экономии чековой ленты.

**Comment by letolica** [comment]
Добрый день.

[Добавлена возможность указать способ отправки чека при оплате заказа в соответствии с ФЗ-54](https://iiko.github.io/front.api.doc/2020/07/23/cheque-info-on-order-pay.html), если оплачиваете из плагина.
[Добавлена возможность выбрать способ отправки чека в соответствии с ФЗ-54](https://iiko.github.io/front.api.doc/2019/11/25/cheque-info-on-navigating-to-payment.html), если оплачиваете из экрана кассы фронта.

**Comment by hamaronooo** [comment]
@letolica Спасибо!
Правильно ли я понял, что использовать (по 2ому способу) нужно так?
```
 public void OnNavigatingToPaymentScreen(
            IOrder order,
            IPointOfSale pos,
            IOperationService os,
            IViewManager vm,
            INavigatingToPaymentScreenOperationContext context
        )
        {
            context.ChequeAdditionalInfo = new ChequeAdditionalInfo(
                needReceipt: false,
                "88005553535",
                email: "exmaple@mail.com",
                settlementPlace: "???");
        }
```
Какую строку нужно помещать в поле `settlementPlace`, немного не понятно ((

**Comment by letolica** [comment]
Вот есть [пример](https://github.com/iiko/front.api.sdk/blob/86e6266ff24524c2e49e7601236b12191f0f1a1b/sample/v7/Resto.Front.Api.SamplePlugin/NotificationHandlers/NavigatingToPaymentScreenHandler.cs#L48).
`settlementPlace` - это место расчета, настраивается в ФР. Для курьерских доставок проставляется как адрес доставки. В примере его берут из предыдущего значения. Рекомендую сделать так же.

**Comment by hamaronooo** [comment]
@letolica Еще раз спасибо, все работает! 
Последний вопрос) 
Я так понял, что по дефолту INavigatingToPaymentScreenOperationContext является null, соответственно `currentInfo?.SettlementPlace` не загружается сам из настроек (?), как можно решить данную проблему нативно, или же, если данная настройка `null` или `String.Empty`, то она подставится из настроек позже автоматически?

**Comment by letolica** [comment]
Сам контекст `NotNull`.
Информация о чеке (`ChequeAdditionalInfo`) в контексте `CanBeNull`. Если оставить конкретно `settlementPlace` как `null`, то место расчета подставится из настроек ФР.

**Comment by hamaronooo** [comment]
@letolica Большое спасибо!
