### ISSUE TITLE
iiko/front.api.sdk как связать с сайтом. Есть ли возможность из внешней системы запрашивать данные из через запросы post 

### ISSUE THREAD

**Issue by DARYAlesina10** [iiko/front.api.sdk#342]
Есть ли возможность из внешней системы   запрашивать данные  в front.api.sdk  через запросы post или get например мы с сайта хотим послать запрос о каком либо заказе. Если да то разъясните подробнее как это делается. Не можем найти нигде никаких внятных документаций , существуют ли они???

**Comment by letolica** [comment]
Добрый день.
Есть пара вариантов:
1. [Front Web API](https://ru.iiko.help/articles/#!api-documentations/front-web-api)
2. [iikoCloud API](https://ru.iiko.help/articles/#!api-documentations/trn-general)

**Comment by DARYAlesina10** [comment]
Подскажите, у нас стоил iiko локальная лицензия , мы сможем их подключить в этом случае? и какая из них подойдет больше если мы планируем работать, в том числе и изменять, чеки банкеты резервы заказы

**Comment by letolica** [comment]
Могу порекомендовать ознакомиться со статьей ["Какими бывают лицензии API"](https://ru.iiko.help/articles/#!api-documentations/apistart) и в целом с разделом ["API документация. Начало работы"](https://ru.iiko.help/articles/#!api-documentations/getting-started).

**Comment by DARYAlesina10** [comment]
Мы уже изучили их. нет понимания полного. как это работает. До Вас мы работали с другой системой которая удачно сдохла(poster). Помогите пожалуйста разобраться с вопросом который я выше задавала. Наш интегратор вообще ничего не понимает  и не может на помочь

**Comment by MubinjonMuinov** [comment]
mubinjonmuinov@gmail.com у нас есть опыт давайте мы Вам поможем.

**Comment by vcpp** [comment]
> Есть ли возможность из внешней системы запрашивать данные в front.api.sdk через запросы post или get

Нет. iikoFront API требует реализации плагина под .NET. Подробнее [тут](https://iiko.github.io/front.api.doc/v6/ru/Intro.html). Далее плагин уже может передавать данные через get/post-запросы. Получается такая цепочка: iikoFront ↔ плагин ↔ внешняя система.

На этой площадке консультируем по техническим аспектам взаимодействия между iikoFront и плагином, здесь общаются разработчики, а у вас высокоуровневый вопрос общего характера. Сейчас ситуация выглядит так, что вам нужна помощь в постановке задачи и выборе варианта решения. Вопрос про лицензию пока преждевременный, потому что неясно, что вы выберете. Может, вы надумаете централизованно забирать данные через iikoCloud, может, воспользуетесь одним из существующих плагинов для получения данных через веб-запросы, а может и решитесь на разработку нового плагина специально под свою задачу. Напишите на api@iiko.ru, там вам помогут определиться.
