### ISSUE TITLE
Лицензирование модуля

### ISSUE THREAD

**Issue by vitalaqua74** [iiko/front.api.sdk#344]
Подскажите какой ModuleID использовать для функционала изменения имени гостя в заказе
При разработке вроде бы все заработало, установив клиенту сообщение что проблема с лицензированием
Хотя установили лицензию API

**Comment by vcpp** [comment]
> Подскажите какой ModuleID использовать для функционала изменения имени гостя в заказе

Вы получили лицензию разработчика, обратившись по адресу api@iiko.ru? Там же вам должны были выдать module id для вашего плагина.

> При разработке вроде бы все заработало, установив клиенту сообщение что проблема с лицензированием
Хотя установили лицензию API

1. Можете процитировать сообщение, чтобы можно было понять, о какой именно проблеме идёт речь?
2. Какой module id указан в атрибуте [`PluginLicenseModuleId`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Attributes_PluginLicenseModuleIdAttribute.htm) и в манифесте вашего плагина? В лицензию клиента этот module id включён?
3. Если на одном компьютере плагин работает, а на другом «*сообщение что проблема с лицензированием*», можно предположить, что проблема не в самом плагине, а в среде его использования, с этим лучше обратиться в обычную [техподдержку](https://iiko.ru/support).
