### ISSUE TITLE
FR: Кнопки плагина в заказах на доставку

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#345]
Хочется иметь возможность добавлять кнопку плагина в экран заказа доставки

**Comment by letolica** [comment]
Здравствуйте.
Возможность добавления плагинных кнопок на экран редактирования доставки пока не сделана из-за архитектурных ограничений с ручным сохранением доставки (доставку надо сохранять нажатием на кнопку). В первую очередь мы хотим научить фронт сохранять доставку на лету, а уж потом добавлять все фишки с редактированием доставки из апи по инициативе плагина аналогично обычному экрану заказа (если [заказ открыт на UI](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html), [по плагинной кнопке](https://iiko.github.io/front.api.doc/2020/11/11/add-button-to-order-edit-screen.html), [по прокатке карты или сканировании ШК](https://iiko.github.io/front.api.doc/2020/07/24/order-edit-card-barcode-handlers.html)).
Внутренний номер задачи для добавления плагинных кнопок на экран редактирования доставки: RMS-53534.
Пока можете попробовать воспользоваться [плагинными кнопками на кассе](https://iiko.github.io/front.api.doc/2021/08/09/add-action-for-payment-screen.html). Для доставок они тоже доступны.
Мы оповестим вас здесь, как только задача RMS-53534 будет сделана.
