### ISSUE TITLE
Почему если запрашиваю заказ по id приходит пустой массив 

### ISSUE THREAD

**Issue by DARYAlesina10** [iiko/front.api.sdk#347]
(
    [correlationId] => c23d496e-0565-44f4-aea6-f14d4d60ee4a
    [orders] => Array
        (
        )

)
Хотя id заказа указан верно, и ошибки он не возвращает а только пустой массив.
Запрашиваю через iiko cloud api через пост запрос на https://api-ru.iiko.services/api/1/order/by_id использовав полученный токен

**Comment by DARYAlesina10** [comment]
вопрос решен, неправильная настройка айко транспорт)

**Comment by vcpp** [comment]
Так получилось, что у продуктов iiko есть несколько API. На данной площадке консультируем по iikoFront API — это API кассового приложения, позволяющее писать .NET-плагины. Если я правильно понимаю, вы пытаетесь использовать облачный веб-API.

Я передам ссылку на ваш вопрос коллегам из команды iikoCloud API, а вообще такие вопросы можно задавать по адресу api@iiko.ru.

**Comment by AndreevOlegArtemovich** [comment]
Добрый день, DARYAlesina10, я из команды iikoCloud API, посмотрел по логам ваши запросы - вы шлёте в запрос на получение заказа идентификатор "b3...", которого не существует в базе данных заказов iikoCloud API. На текущий момент по вашей организации имеется всего 1 заказ на стол и у него другой идентификатор.
Где именно вы взяли тот идентификатор, который шлете в запросах к https://api-ru.iiko.services/api/1/order/by_id?
В ответе на запрос создания этого заказа на стол такой идентификатор возвратится не мог.
