### ISSUE TITLE
Получение credentials пользователя.

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#348]
Добрый день! 
Есть оператор без права удаления позиций в заказе. 
Так же есть необходимость в определенный момент удаление данных позиций из плагина.
Для этого мы перед удалением проверяем права текущего пользователя  и в случае необходимости повышаем его права через ShowCheckPermissionPopup

В итоге получаем iUser.

Вопрос каким образом можно получить credentials этого пользователя. 
Так как сейчас мы удаляем по стандартной схеме -  с получением credentials  через PluginContext.Operations.AuthenticateByPin(request.Pin)

Так же есть второй вопрос - при удалении позиций используя credentials PluginContext.Operations.AuthenticateByPin(request.Pin) мы не видим удаленные позиции в iIKO RMS

**Comment by MiAlLevin** [comment]
Коллеги по второму вопросу. 
Сейчас для удаления всех позиций в заказе мы создаем сессию редактирования, далее берем все orderitem и делаем им orderitemdelete. Только после этих операций мы делаем submitchages. В итоге в журнале мы видим только последнюю удаленную позицию. Подскажите как нам корректно удалять позиции чтобы видеть их все в журнале.

**Comment by Keeplod** [comment]
> Коллеги по второму вопросу. Сейчас для извлечения всех позиций в распоряжение мы далее создаем сессию, берем все заказы и делаем им заказы удаляем. Только после этих операций мы делаем рассылки. В конце концов в журнале мы видим только видимую удаленную высыпь. Подскажите, как нам скорректировать позицию, чтобы видеть их все в журнале.

а что за журнал используете?

**Comment by vcpp** [comment]
1. Если плагин действует от своего имени, он должен выполнять операции под своей служебной учётной записью. Для этого необходимо зарегистрировать учётную запись для плагина, выдать ей все необходимые права, назначить ей пин-код и использовать этот пин-код в плагине при вызове `AuthenticateByPin`. Таким образом, у плагина будет возможность удалять позиции тогда, когда он считает нужным. Дальше уже на усмотрение плагина, в вашем случае перед удалением позиций можно вызвать `ShowCheckPermissionPopup`.

Такой подход позволит различать в журнале событий удаления, выполненных непосредственно пользователем, от удалений, выполненных плагином. Другое дело, если плагин ничего сам по себе не делает, а просто применяет изменения, которые пользователь выполняет на мобильном терминале, тогда пользователь авторизуется на мобильном терминале по пин-коду, и плагин использует этот пин-код для выполнения операций.

2. Это баг, вернее, недоделка. К сожалению, не все сделанные через API изменения корректно отображаются в [журнале событий](https://ru.iiko.help/articles/iikochain-7-9/topic-106). Поправим.
