### ISSUE TITLE
Не точность в документации

### ISSUE THREAD

**Issue by OhMyGoodness** [iiko/front.api.sdk#349]
https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_PayOrder.htm

В описании указан интерфейс "IOperationServicePayOrder" хотя такого не существует. Невозможно его никак найти

*даже в ссылке указан пробел, вероятней всего имеется ввиду IOperationService.PayOrder

**Comment by vcpp** [comment]
Вероятно, у вас браузер как-то криво отображает эту страницу. Посмотрите исходный код страницы, там всё в порядке.
Может, какой-нибудь плагин так ловко вырезает рекламу?
