### ISSUE TITLE
Запуск iiko Front из 1с

### ISSUE THREAD

**Issue by Adoishe** [iiko/front.api.sdk#35]
Здравствуйте!

Существует необходимость авторизации пользователей iiko в 1с и только потом осуществлять запуск iiko Front. Может быть есть параметры запуска?
Я читал https://ru.iiko.help/articles/#!api-documentations/front-web-api но не нашел путей решения.

**Comment by ierof** [comment]
1. Более полная документация по iikoFront API тут: https://iiko.github.io/front.api.doc/
2. API это про получение данных из программы, совершение каких-либо операций в рамках неё. Не про старт программы.

Я бы рекомендовала вам попробовать это решить какой-нибудь сторонней утилитой (возможно, написанной самостоятельно), которая бы не давала стартовать процессу iikoFront, пока не выполнены нужные вам условия его старта.
