### ISSUE TITLE
Получение данных о проведённом чеке

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#350]
Здравствуйте.
Подскажите, пожалуйста. Можно ли после оплаты получить данные о чеке, а именно ФД, ФН, ФПД?
Если да, то в какой момент?

**Comment by letolica** [comment]
#357

**Comment by letolica** [comment]
Добрый день.
Для начала предложу ознакомиться в примером реализации интерфейса [IChequeTaskProcessor](https://github.com/iiko/front.api.sdk/blob/master/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs). Скорее всего вам понадобится метод [AfterDoCheckAction](https://github.com/iiko/front.api.sdk/blob/30e5419a48cfce6a85a60645461fa1c22d178f4e/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs#L61). Там на вход приходят несколько аргументов, из которых можно попытаться выудить хотя бы какую-нибудь информацию о фискальном документе
- **[ChequeTask](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_Tasks_ChequeTask.htm) chequeTask**
- **[PostResult](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_Results_PostResult.htm) result**, который можно попытаться скастить к [CashRegisterResult](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_Results_CashRegisterResult.htm)
- **[ICashRegisterInfo](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_ICashRegisterInfo.htm) device**

Заполнение тех или иных полей также может зависеть и от модели фискального регистратора.
Попробуйте реализовать пример и поискать в результатах то, что вам нужно, в связке с реальным ФР. Если чего-то будет не хватать, напишите. Подумаем, как нам нужно будет доработать апи, чтобы информация о фикальных чеках была доступна не только фронту и ФР, но любым другим желающим плагинам.

**Comment by letolica** [comment]
А напишите, зачем вам эти данные? Хотим понимать, насколько это актуально и востребовано может быть.

**Comment by theDCM** [comment]
Добрый день. Хотим слать чеки об оплате на почту клиентам. Чтобы найти чек в ОФД нам и нужны ФД, ФН, ФПД.

**Comment by letolica** [comment]
Уточните, какими моделями ФР вы (или ваши клиенты) пользуетесь. И почему не пользуетесь встроенным функционалом отправки фискальных чеков на почту? Вот [документация](https://ru.iiko.help/articles/how-to-iiko/fz-54/a/h2_12).

**Comment by theDCM** [comment]
Не пользуемся встроенным функционалом по причине того, что хотим делать собственные чеки. У нас программа лояльности, будет удобно, если мы сможем указывать какие-либо дополнительные поля для каждого пользователя отдельно

**Comment by letolica** [comment]
Дополнительные поля в фискальном чеке мы тоже поддерживаем. Их можно заполнить всё в том же [IChequeTaskProcessor](https://github.com/iiko/front.api.sdk/blob/master/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs) в методе [BeforeDoCheckAction](https://github.com/iiko/front.api.sdk/blob/30e5419a48cfce6a85a60645461fa1c22d178f4e/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs#L23). В примере как раз построение дополнительной разметки.

**Comment by theDCM** [comment]
А есть пример чека, который получает клиент? И можем ли адрес отправки чека установить где-нибудь в [BeforeDoCheckAction](https://github.com/iiko/front.api.sdk/blob/30e5419a48cfce6a85a60645461fa1c22d178f4e/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs#L23)?

**Comment by letolica** [comment]
> А есть пример чека, который получает клиент?

У меня к сожалению таких примеров нет. Для этого нужно смотреть результат на разных ФР (с привлечением тестировщика с многообразием моделей ФР), потому что на каждой модели место, отведённое для печати свободного текста, может различаться. Единственное, что гарантируется, так это то, что [BeforeDoCheckActionResult.BeforeCheque](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Device_BeforeDoCheckActionResult_BeforeCheque.htm) будет располагаться в верхней части чека до списка блюд, а [BeforeDoCheckActionResult.AfterCheque](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Device_BeforeDoCheckActionResult_AfterCheque.htm) будет располагаться в нижней части чека после списка блюд. Почитайте документацию ["Расширение функционала фискального регистратора"](https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html). 

> И можем ли адрес отправки чека установить где-нибудь в [BeforeDoCheckAction](https://github.com/iiko/front.api.sdk/blob/30e5419a48cfce6a85a60645461fa1c22d178f4e/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs#L23)?

К сожалению, [BeforeDoCheckActionResult](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Device_BeforeDoCheckActionResult.htm) позволяет расширить только шапку и подвал фискального чека, изменить имя кассира и список позиций чека. Но установить почту, на которую нужно отправить фискальный чек, можно двумя способами. [Вот здесь есть ответ](https://github.com/iiko/front.api.sdk/issues/341#issuecomment-1073554742).

**Comment by letolica** [comment]
@theDCM, кажется, я немного вас дезинформировала, прошу прощения. Выяснилось, что нефискальные строки, коими являются строки, задаваемые в [BeforeDoCheckAction](https://github.com/iiko/front.api.sdk/blob/30e5419a48cfce6a85a60645461fa1c22d178f4e/sample/v7/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs#L23), не отправляются в ОФД. Они только печатаются на бумажном чеке ФР. Эти строки не будут отображаться в электронном чеке, сформированном ОФД.

Напишите модели ФР, которые нужно поддержать. Завела задачу на доработку с внутренним номером RMS-53535. Но о сроках реализации ничего не могу сказать.

**Comment by letolica** [comment]
Добрый день.
Пробросили в апи необходимые поля:
https://iiko.github.io/front.api.doc/2023/03/31/fn-fd-cashregisterresult.html
