### ISSUE TITLE
Печать QR в пречеке

### ISSUE THREAD

**Issue by Orean83** [iiko/front.api.sdk#351]
Добрый день.
Мы хотим в пречеке при помощи тега qrcode печатать QR со ссылкой на веб страницу.
В формировании ссылки используются символы & (амперсанд) для перечисления параметров запроса.
При сканировании QR мы обнаружили, что символ & преобразуется в сущность &amp; , что не позволяет правильно обрабатывать ссылку.
Есть ли возможность передавать в QR непосредственно сам символ &, например запретом преобразования?

**Comment by igorpooh1978** [comment]
Добрый день
urlencode вам поможет

**Comment by Orean83** [comment]
Добрый день.

Мы добавили в скрипт такую строку:
<qrcode size="small" correction="Medium">@HttpUtility.UrlEncode("https://test.test/test?p=123&s=321")</qrcode>
Считали сканером строку. В итоге получился такой QR-код:
https%3a%2f%2ftest.test%2ftest%3fp%3d123%26s%3d321
Если вставить её в браузер, он не воспринимает её как адрес и пытается искать в поисковой системе как строку.
Поясните, пожалуйста, как именно использовать urlencode, чтобы он нам помог?

**Comment by igorpooh1978** [comment]
Добрый вечер. А зачем вы всю строку загоняете ? В вашем случае & ставьте вручную
```
var str = $"https://test.test/test?p={HttpUtility.UrlEncode(param1)}";
```
Ну или как вариант сделать словарь <string,string> собрать строку

**Comment by Orean83** [comment]
> 

А в чём тогда смысл urlencode на оставшейся части строки? У нас там нет спецсимволов.
Проблема лишь в том амперсанде, который стоит между параметрами.  urlencode - если применить к амперсанду - превратит его в %26, это будет мешать использовать амперсанд как разделитель параметров.

Давайте ещё раз убедимся, что мы одинаково понимаем проблему.
Вот фрагмент кода, для генерации пречека.
<line/>
    @("https://test.test/test?p=123&s=321")
<line/>
<center><qrcode size="small" correction="Medium">
    @("https://test.test/test?p=123&s=321")
</qrcode></center>
<line/>

Если его использовать, то в первой части, между линиями напечатается текст
https://test.test/test?p=123&s=321
Во второй - qr, который при считывании превращается в 
https://test.test/test?p=123&amp;s=321

А нам нужно, чтобы там был точно такой же текст, как в первой части.
Если Вы знаете как это можно решить при помощи urlencode - подскажите, пожалуйста, что изменить в этом примере.

**Comment by igorpooh1978** [comment]
Вы проверяете на живом принтере ? ПОпробуйте на XPS или PDF что там будет.

**Comment by Orean83** [comment]
> Вы проверяете на живом принтере ? ПОпробуйте на XPS или PDF что там будет.

проверил, действительно, в PDF все правильно печатает, но нам же нужно чтобы печать шла на принтер, как быть?

**Comment by igorpooh1978** [comment]
Есть большое подозрение, что это принтер (что за принтер кстати?) может себя так вести ну или его драйвер в iiko.

**Comment by Orean83** [comment]
> Есть большое подозрение, что это принтер (что за принтер кстати?) может себя так вести ну или его драйвер в iiko.

Это Атол-20Ф

**Comment by igorpooh1978** [comment]
Пишите в ТП iiko )

**Comment by Orean83** [comment]
> Пишите в ТП iiko )

Ок)) спасибо, попробую) они просто зачастую именно сюда отправляют)
