### ISSUE TITLE
Оплата заказа без печати чека не работает в  API LTS-версии V7.

### ISSUE THREAD

**Issue by kolan72** [iiko/front.api.sdk#352]
В нашем плагине лояльности необходимо обеспечить возможность оплатить заказ без печати чека c отправкой его на Email гостя. До недавнего времени мы использовали Resto.Front.Api.V7Preview7 и реализовали в плагине предлагаемую [возможность](https://iiko.github.io/front.api.doc/2019/11/25/cheque-info-on-navigating-to-payment.html) 
[, с примером](
https://github.com/iiko/front.api.sdk/blob/86e6266ff24524c2e49e7601236b12191f0f1a1b/sample/v7/Resto.Front.Api.SamplePlugin/NotificationHandlers/NavigatingToPaymentScreenHandler.cs#L48) и разъяснениями в #341.

Данный подход был тщательно протестирован и с использованием  Resto.Front.Api.V7Preview7 его работа не вызывает нареканий.

Однако с переходом на [Resto.Front.Api.V7 (LTS-версия)](https://iiko.github.io/front.api.doc/2022/01/20/v7-release.html) мы получили полностью неработоспособное решение - чек печатается, почта на подставляемый в конструктор объекта `ChequeAdditionalInfo ` Email не отправляется.

Кроме того, в режиме кассы окно, вызываемое по кнопке _Отправка чека_, данный Email так же не содержит, что было одним из критериев успешной работы функционала в 7Preview7.

Тестирование проводилось с минимальными правами кассира.

**Comment by kolan72** [comment]
Да, с последней версией iikoFront, а именно:

**Comment by kolan72** [comment]
Т.е., отвечая на вопрос, именно с таким соответствием фронта и API имеем данную проблему.

**Comment by vcpp** [comment]
Странно, что с одной и той же версией iikoFront 7.9 плагин на V7Preview7 работает корректно, а переведённый на V7 плагин не работает, потому что реализация `INavigatingToPaymentScreenOperationContext` выглядит идентичной в V7Preview7 и V7.

Вероятно, происходит ошибка где-то в другом месте, отчего плагин не получает уведомления `NavigatingToPaymentScreen`. Вы ещё не смотрели логи? Самое интересное может быть в логе вашего плагина, либо в *api.log*. Обычно бывает запись вида «Exception in “...” plugin's handler for “NavigatingToPaymentScreen”: ...», когда обработчик уведомления выбрасывает непредусмотренное контрактом исключение.

Если сами в логах ничего подозрительного не найдёте, могу предложить два варианта:
* подготовить минимальный пример плагина, воспроизводящего ошибку на V7, воспроизвести с его помощью ошибку на тестовом стенде и прислать нам исходники плагина и полный комплект логов,
* либо прислать ваш реальный плагин, полный комплект логов и указание на время или номер заказа, при оплате которого не было учтено указание отправлять чек по почте.

Первый вариант можно прямо сюда прикрепить (публичный доступ), второй вариант, наверное, лучше через техподдержку для соблюдения конфиденциальности.

**Comment by kolan72** [comment]
Спасибо за содержательные советы. Из того, что пока сделано:
Лог плагина смотрели, в том числе записи, относящиеся к `NavigatingToPaymentScreen` - ничего подозрительного по теме не увидели.
Также смотрели api.log, тоже все в порядке.
Минимальный тестовый плагин сделали, ошибка воспроизвелась, логи возможно пришлем.
Но пока продолжили попытки решить проблему другими способами. 
О результатах обязательно сообщим.

**Comment by kolan72** [comment]
Решили проблему удалением лишних (т.е. не относящихся к текущему проду) плагинов на тестовом стенде.
Отправка чека на Email как альтернатива его печати в  API LTS-версии V7 работает.
Еще раз спасибо за помощь.
