### ISSUE TITLE
Как добавить товар с размером?

### ISSUE THREAD

**Issue by MubinjonMuinov** [iiko/front.api.sdk#353]
Хотим добавить блюда с размером но у нас это не получается, если блюда без размера тогда товар добавится.

вот пример
```
            var credentials = PluginContext.Operations.GetCredentials();
            Guid GI = new Guid("c079fcd9-9d57-423c-91e3-2f1cce673638");

            IProduct product1 = PluginContext.Operations.GetProductById(GI);
            IProduct product2 = PluginContext.Operations.GetProductById(GI);

            var productSize = product1.Scale == null ? null : product1.Scale.DefaultSize ?? PluginContext.Operations.GetProductScaleSizes(product1.Scale).First();

            // создаём заказ, добавляем в него пару гостей, одному из гостей добавляем блюдо, и всё это атомарно в одной сессии
            var editSession = PluginContext.Operations.CreateEditSession();
            var newOrder = editSession.CreateOrder(null); // заказ будет создан на столе по умолчанию

            var guest1 = editSession.AddOrderGuest(null, newOrder); // настоящего гостя ещё нет (он будет после SubmitChanges), ссылаемся на будущего гостя через INewOrderGuestItemStub

            editSession.ChangeOrderOriginName("Sample Plugin", newOrder);
            var guest2 = editSession.AddOrderGuest("Alex", newOrder);
            editSession.AddOrderProductItem(2m, product1, newOrder, guest1, productSize);
            var result = PluginContext.Operations.SubmitChanges(editSession);

            var previouslyCreatedOrder = result.Get(newOrder);
            var previouslyAddedGuest = result.Get(guest2); // настоящие гости уже есть, можно ссылаться напрямую на нужного гостя через IOrderGuestItem

            PluginContext.Operations.AddOrderProductItem(17.3m, product2, previouslyCreatedOrder, previouslyAddedGuest, null, credentials);
```

**Comment by Keeplod** [comment]
var **productSize** = product.Scale == null ? null : product.Scale.DefaultSize ?? PluginContext.Operations.GetProductScaleSizes(product.Scale).First();

PluginContext.Operations.AddOrderProductItem(17.3m, product2, previouslyCreatedOrder, previouslyAddedGuest, **productSize** , credentials);

**Comment by MubinjonMuinov** [comment]
не получилось

**Comment by Keeplod** [comment]
А какая ошибка?

**Comment by vcpp** [comment]
Вы в первом сообщении написали _не получается_, а во втором уточнили, что _не получилось_. Этого недостаточно, нужны подробности — что именно вы наблюдаете, какие ошибки возникают, что в логах и т. п.

По примеру я вижу два замечания:
* вы дважды запрашиваете продукт с одним и тем же id, добавляете его в первый раз с проверкой на размер (`product1`) и затем тот же самый продукт пытаетесь добавить без проверки на размер, передавая константу `null` в качестве размера (`product2`) — разумеется, последнее не будет работать, если у продукта задана шкала размеров,
* вы берёте дефолтный или первый попавшийся размер из шкалы, не проверяя его на совместимость с конкретным продуктом — поскольку в карточке продукта на вкладке «[Шкала размеров](https://ru.iiko.help/articles/iikochain-8-0/topic-22)» можно снять галочки «Доступен» для некоторых размеров, в коде их стоит исключить из рассмотрения примерно [так](https://github.com/iiko/front.api.sdk/blob/master/sample/v7/Resto.Front.Api.SamplePlugin/PreliminaryOrders/ProductItemModel.cs):
```cs
PluginContext.Operations.GetProductScaleSizes(product.Scale)
    .Except(PluginContext.Operations.GetDisabledSizesByProduct(product))
```
