### ISSUE TITLE
Бесконечная рекурсия 

### ISSUE THREAD

**Issue by Lizzzzzard** [iiko/front.api.sdk#354]
Коллеги, в версии 7.9.7 при использовании api v7 при запросе заказа `PluginContext.Operations.TryGetOrderById` получаем order и вместе с ним бесконечную рекурсию в RestaurantSection 
![image](https://user-images.githubusercontent.com/74863190/164031189-fbf1c4df-c56a-4794-8159-2ab51a8c915c.png)

**Comment by pro100roman24** [comment]
Сегодня тоже с этим столкнулся, там действительно есть бесконечная рекурсия.
Например, если взять переменную типа ITable, допустим назовем её table, то можно обратиться к её параметру RestaurantSection, затем к параметру Tables, назем взять первый стол из листа через First(), а затем опять обратиться к RestaurantSection и так бесконечно:

table.RestaurantSection.Tables.First().RestaurantSection.Tables.First().RestaurantSection.Tables.First().RestaurantSection.Tables.First()..........

Из за этого не получается десериализовать стол в json. Ругается на рекурсию. Пришлось делать отдельно класс, создавать переменную этого класса и перекладывать параметры стола по одному в новую переменную, без RestaurantSection, чтоб потом её десериализовать. Это трудоёмко, особенно если учитывать, что стол может лежать в переменной типа IOrder, для которого тоже приходится писать отдельно класс, создавать новую переменную этого класса и перекладывать в него каждый параметр отдельно, вместо того, чтоб просто всю переменную IOrder закинуть на десериализацию в json.

**Comment by igorpooh1978** [comment]
Добрый день
```
               var settings = new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                };
                string jsonSer = JsonConvert.SerializeObject(data, settings);
```

**Comment by pro100roman24** [comment]
Спасибо

**Comment by vcpp** [comment]
> если взять переменную типа ITable, допустим назовем её table, то можно обратиться к её параметру RestaurantSection, затем к параметру Tables, назем взять первый стол из листа через First(), а затем опять обратиться к RestaurantSection и так бесконечно

В V7 для удобства в [ITable](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Organization_Sections_ITable.htm) [добавили](https://iiko.github.io/front.api.doc/2021/11/02/restaurant-section-added-to-table.html) ссылку на соответствующее отделение [RestaurantSection](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_Sections_ITable_RestaurantSection.htm).

С БД и нормализацией это никак не связано, просто в одних сценариях нужно из отделения получить список столов, а в других — по столу определить, в каком он отделении. До V6 включительно, когда ссылка была только из отделения на стол, в плагине приходилось считывать все отделения, затем во всех отделениях перебирать все их столы в поисках нужного нам стола. Это и в коде громоздко, и вычислительно дорого, поэтому приходилось городить кеш на стороне плагине, что ещё больше усложняло код. Теперь прямые ссылки в обе стороны, удобно.

В рукописном коде никто не будет, имея ссылку на отделение, брать из него стол и смотреть, в каком отделении находится этот стол, так что проблема, видимо, только с библиотеками, которые рекурсивно обходят граф объектов и спотыкаются на циклических ссылках.

> 
```cs
ReferenceLoopHandling = ReferenceLoopHandling.Ignore
```

Спасибо, коллега :-)
Мы, мягко говоря, не успеваем оперативно отвечать, и взаимная помощь здесь очень кстати.
