### ISSUE TITLE
Как найти и получить принтер блюд

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#355]
Вопрос собственно как мне получить принтер блюд?
Есть несколько методов, которые возвращают какие угодно принтера, но только не принтер блюд.
TryGetStickerPrinter()  - возвращает принтер стикеров
TryGetBillPrinter() - возвращает принтер пречеков
TryGetDocumentPrinter() - возвращает принтер отчетов
TryGetReceiptChequePrinter() - возвращает принтер квитанций
GetReportPrinter() - возвращает принтер отчетов.
А как найти именно принтер блюд по нужному мне отделению или блюду мне не понятно, объясните

**Comment by letolica** [comment]
Добрый день.
Пожалуй, никак. В апи принтер блюд не доступен. А для чего он нужен, поделитесь пожалуйста?

**Comment by pro100roman24** [comment]
Пишем плагин, который отслеживает остатки товаров на складах, и когда остаток по товару становится меньше минимального, заданного в настройках, должна пройти печать на принтер кухни типа:
"ВНИМАНИЕ! ОСТАТОК ПО ТОВАРУ ТАКОМУ-ТО СТАЛ МЕНЬШЕ МИНИМАЛЬНОГО"
По ТЗ клиент хочет, чтоб печать шла на тот принтер кухни, на который шла печать блюда, которое и привело к списанию товара. Сейчас как обходной путь используем метод TryGetStickerPrinter() и выводим печать на принтер стикеров, но это не совсем удобно, пришлось делать шаблон-заглушку для стикера, чтоб они не печатались. Это получилось использовать только потому, что клиенту не нужны стикеры в принципе. Если бы например в одном отделении они были бы нужны, а в другом нет, то не прокатил бы такой вариант.
Было бы здорово иметь возможность получить именно принтер блюд. И это наверно было бы логично, странно что можно получить любой другой принтер, кроме этого.

**Comment by letolica** [comment]
Завела задачу на доработку с внутренним номером RMS-53532. Когда мы её сделаем, напишем сюда.

**Comment by andrey-nasonov** [comment]
Сделано
https://github.com/iiko/front.api.doc/blob/gh-pages/_posts/2023-01-26-dish-printer.md
