### ISSUE TITLE
Выходит тип ошибки, за место сообщения ошибки

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#356]
Создаю заказ с указанием DeliveryId
Второй такой же заказ с тем же DeliveryId
submit инкапсулирован

> try
> {
>     SubmitChanges(EditSession, ContinuousOperation);
> }
> catch (CannotCreateEntityException ex)
> {
>        PluginContext.Log.Error("CannotCreateEntityException: " + ex.Message);
> }
> catch (Exception ex)
> {
>     PluginContext.Log.Error("Exception: " + ex.Message);
> }

Получаю: 
                            

> [2022-04-21 14:37:07,780] ERROR [23] - CannotCreateEntityException: Выдано исключение типа "Resto.Front.Api.Exceptions.CannotCreateEntityException".

**Comment by letolica** [comment]
Добрый день. Такое сообщение выдается для исключений, у которых не задано поле `message`. Мы генерируем `Resto.Front.Api.Exceptions.CannotCreateEntityException` как раз таким образом, не заполняя у него `message`.
