### ISSUE TITLE
FR: Возможность взаимодействия с фискальным регистратором через SDK.

### ISSUE THREAD

**Issue by zhmpng** [iiko/front.api.sdk#357]
Хотелось бы иметь возможность получать данные ФПД регистрации фискального чека и соответсвенно инициализации такой регистрации, как пример сценария: отправляем в память позиции и сумму заказа, в ответ получаем ФПД регистрацию фискального чека, и получаем результат.
   Данный функционал был бы очень полезен в интеграциях с внешними сервисами.

**Comment by letolica** [comment]
Добрый день.
Пробросили в апи необходимые поля:
https://iiko.github.io/front.api.doc/2023/03/31/fn-fd-cashregisterresult.html
