### ISSUE TITLE
Получения признака "Удалён" для объекта стол(ITable) в версии API v6.

### ISSUE THREAD

**Issue by aitkkia** [iiko/front.api.sdk#358]
Добрый день.
Как можно понять, что стол удалён. В интерфейсе есть признак "Удалён":
![image](https://user-images.githubusercontent.com/59682448/165499620-2ec92964-4b3e-4353-bfdd-8995db7f2e4d.png)

В коде для (V6) не нашёл метод позволяющий получить признак "Удалён"
https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Data_Organization_Sections_ITable.htm
`public interface ITable : ISerializable, IEntity
    {
        int Number { get; }
    }`

При этом в API V7 есть признак - https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Organization_Sections_ITable.htm.
Как-то можно не переходя на V7 понять, что стол удалён?

**Comment by letolica** [comment]
Попробуйте убедиться, что стол присутствует в списке столов отделения:
[IRestaurantSection.Tables](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Organization_Sections_IRestaurantSection_Tables.htm)

**Comment by aitkkia** [comment]
Да, действительно, не внимательно посмотрели метод - `IReadOnlyList<IRestaurantSection> GetRestaurantSections();`. Спасибо за консультацию.
