### ISSUE TITLE
API V7 / PaymentProcessor / ReturnPayment

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#359]
Доброй ночи
Обнаружил интересный баг или фича?
Если проводилось 2 внешних платежа с разными суммами в рамках 1 заказа, то при возврате я имею что
paymentItemId одинаков для них обоих. При этом transactionId разные.
```
        public void ReturnPayment(decimal sum, Guid? orderId, Guid paymentTypeId, Guid transactionId, [NotNull] IPointOfSale pointOfSale, [NotNull] IUser cashier, IReceiptPrinter printer, [NotNull] IViewManager viewManager, IPaymentDataContext context)
```
я про paymentTypeId

**Comment by letolica** [comment]
Добрый день!
`paymentTypeId` - это идентификатор типа оплаты [`IPaymentType`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Payments_IPaymentType.htm), который настраивается в бэк-офисе. Если вы добавляете 2 оплаты одного и того же типа, то `paymentTypeId` у них будет ожидаемо одинаковым.
В некоторые методы на вход приходит сам элемент оплаты [`IPaymentItem`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Payments_IPaymentItem.htm), из которого можно получить и идентификатор уже самого элемента оплаты, и его тип оплаты. В указанном методе это не реализовано. Если нужен сам элемент оплаты, то можем завести задачу на доработку.

**Comment by igorpooh1978** [comment]
Да прошу прощения, не внимателен.

**Comment by igorpooh1978** [comment]
Немного разовью тему. Поправьте меня. `PaymentItem.Id`

**Comment by vcpp** [comment]
> `transactionId` штука "воздушная" и может после перезагрузки фронта иметь уже другие значения (по крайней мере такое состояние я поймал при Pay). Таким образом, когда я выполняю возврат более или менее я могу привязаться именно к PaymentItem.Id

Транзакция создаётся непосредственно перед началом оплаты (перед вызовом `Pay` или `PaySilently`). В случае успешного проведения оплаты (возврат управления из указанных методов без исключений) транзакция помечается выполненной. Далее в случае отмены оплаты (`ReturnPayment`) вы увидите ту же транзакцию с тем же id. Однако, если оплата завершилась ошибкой (исключение из методов `Pay` или `PaySilently`), либо оплата не завершилась ничем (работа приложения была прервана во время оплаты), при повторной попытке оплаты создаётся новая транзакция с новым id.
