### ISSUE TITLE
Как сделать синхронизацию между мобильным приложением и кассовой системой?

### ISSUE THREAD

**Issue by bodanrchuk** [iiko/front.api.sdk#36]
Мы занимаемся сервисом лояльности. Сейчас перед нами поставлена задача разработать собственное мобильное приложение, которое будет синхронизироваться с кассой iiko клиента.
В нем предусмотрен такой функционал:
1.Формирование заказа. Возможность добавлять позиции меню к заказу.
2.Идентификация клиента с помощью считывания нашего qr/ bar-code.
3.Закрытия чека в iiko / нашей системе. (Как дополнительный функционал).

Вопрос: Есть ли у вас такие методы API с помощу которых мы можем сделать интеграцию с кассовой системой и нашим моб. приложением? Возможно получить API которое используется у ваших моб. приложением iiko?

**Comment by ierof** [comment]
Смотрите, мы тут компетентны отвечать только на вопросы про [iikoFront API](https://ru.iiko.help/articles/#!api-documentations/api-iikofront). 

Это API для написания плагинов к терминалам iikoFront. Подробно о том, что из себя представляет данной API написано [во введении](https://iiko.github.io/front.api.doc/v6/ru/Intro.html). Т.е. чтобы внешнему сервису как-то взаимодействовать с кассой iikoFront по средствам iikoFront API, на этой кассе должен быть уставлен плагин, написанный вами на .Net с нужной вам логикой.

**Comment by ierof** [comment]
Напишите на api@iiko.ru, возможно, там менеджер по интеграциям даст вам рекомендации.

**Comment by vladislav250899** [comment]
> Напишите на [api@iiko.ru](mailto:api@iiko.ru), возможно, там менеджер по интеграциям даст вам рекомендации.

При разработке плагина для версий 6.3.3 и 6.4.3 мы столкнулись с проблемой:
![image_2019-12-11_23-59-45](https://user-images.githubusercontent.com/49268908/70918757-46649900-2028-11ea-93c2-1e837e6cf77f.png)


При подключении этих пакетов отображается ошибка и пакет не устанавливается:

https://www.nuget.org/packages/Resto.Front.Api.V6Preview5/6.4.1746-alpha
https://www.nuget.org/packages/Resto.Front.Api.V6Preview4/6.4.1210-alpha
Подскажите, пожалуйста, как можно решить эту проблему?
