### ISSUE TITLE
API V8preview1 / PaymentProcessor / OnPaymentDeleting

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#360]
Доброй ночи
В версии 8.0.8015 появился метод OnPaymentDeleting.
В нем очень не хватает IOperationService, как в OnPaymentAdded.
    К примеру метод OnPaymentAdded имеет на входе сл. св-ва
```
public override void OnPaymentAdded([NotNull] IOrder order, [NotNull] IPaymentItem paymentItem, [NotNull] IUser cashier, [NotNull] IOperationService operationService, IReceiptPrinter printer, [NotNull] IViewManager viewManager, IPaymentDataContext context)
```

тут присутствует IOperationService.
А вот в OnPaymentDeletingего нет, что очень очень плохо, т.к. к примеру для ваучеров я ничего удалить из заказа при удалении платежа я не могу (проверено) и соответственно мне выдает что заказ уже кем-то занят (
Простой пример
```
public override void OnPaymentDeleting([NotNull] IOrder order, [NotNull] IPaymentItem paymentItem, [NotNull] IUser cashier, IReceiptPrinter printer, [NotNull] IViewManager viewManager, IPaymentDataContext context)
        {
                var operationService = PluginContext.Operations;
                var voucherOrder = operationService.GetOrderById(order.Id);

                var editSession = operationService.CreateEditSession();
                editSession.AddOrderProductItem(
                    1m, PluginHelpers.GetAdditionalDishToMealVoucher(),
                    voucherOrder, voucherOrder.Guests.LastOrDefault(), null);
                if (editSession.HasChanges)
                {
                    operationService.SubmitChanges(editSession);
                }
        }

```
заваливается
![image](https://user-images.githubusercontent.com/47010778/166564053-f86b9680-6140-4f26-9bde-46cb0323b3b7.png)
```
[2022-04-07 15:46:04,553] DEBUG [52] - Plugin “Resto.Front.Api.ArgenteaPaymentPlugin” is calling AuthenticateByPin operation
[2022-04-07 15:46:04,564] DEBUG [52] - Submitting edit session #-2147483647 for plugin “Resto.Front.Api.ArgenteaPaymentPlugin” with 1 actions: AddOrderProductItem
[2022-04-07 15:46:04,564] DEBUG [52] - Cancelled submitting edit session #-2147483647 for plugin “Resto.Front.Api.ArgenteaPaymentPlugin”: Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.
   в Resto.Front.Api.V8.Editors.EditSessionWriter.LockEntities(ILockedObjectsToken lockedObjectsToken) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\Editors\EditSessionWriter.cs:строка 109
   в Resto.Front.Api.V8.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в J:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\OperationServiceInternal.cs:строка 1949
```
Еще один нюанс – не работает с ExternalPaymentItem, т.е. я его не могу остановить, если платеж внешний
Хотя Pay работает на ура

**Comment by letolica** [comment]
Добрый день.
Когда мы делали [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IPaymentProcessor_OnPaymentDeleting.htm), то решили для начала сделать его в урезанном варианте исключительно в соответствии с требованиями. Требовалось иметь возможность отменять удаление, предотвращать удаление внешней плагинной оплаты. Это требование было выполнено: предотвратить удаление плагинной оплаты можно выбросом исключений [`PaymentActionCancelledException`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Exceptions_PaymentActionCancelledException.htm) или [`PaymentActionFailedException`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Exceptions_PaymentActionFailedException.htm). Дальше мы ожидаем фидбека и дальнейших требований по доработкам.

> Еще один нюанс – не работает с ExternalPaymentItem, т.е. я его не могу остановить, если платеж внешний
Хотя Pay работает на ура

Попробуйте выброс указанных исключений.
Мы, кстати, должны были написать новость об этой доработке и забыли. Исправимся :)

**Comment by igorpooh1978** [comment]
Ещё небольшое дополнение. Это уже наверное все же баг. Если использовать API V7 на версии iikoFront 8.0.6017 (где уже есть API v8p1). При нажатии на "крестик" возникает exception о не возможности удалить оплату
![image](https://user-images.githubusercontent.com/47010778/166665850-6bcbf085-92f9-4ed2-8f85-36a30baba409.png)

**Comment by letolica** [comment]
Спасибо. Разбираемся.

**Comment by nick-ser** [comment]
Добрый день. Спасибо за информацию. Действительно, описанное поведение является ошибкой. Данный баг был поправлен и в ближайшем релизе его уже не будет.

**Comment by vcpp** [comment]
> Мы, кстати, должны были написать новость об этой доработке и забыли. Исправимся :)

[Исправились](https://iiko.github.io/front.api.doc/2022/03/18/external-payment-removing-api-notification.html).

> Если использовать API V7 на версии iikoFront 8.0.6017

Да, баг, поправим в 8.1.

> очень не хватает IOperationService

Завёл задачку в бэклог: RMS-53597. Возможно, мы раньше сделаем возможность редактирования заказа на экране оплаты (по аналогии с `TryEditCurrentOrder`), и вы сможете вносить изменения сразу после `OnPaymentDeleting`.
