### ISSUE TITLE
Некорректная работа Plugin.Front.CardSlideEmulator

### ISSUE THREAD

**Issue by Lizzzzzard** [iiko/front.api.sdk#361]
Коллеги, в очередной раз сталкиваемся с проблемой работы CardSlideEmulator, работаем с ним для разблокировки фронта.
Примерно с версии 7.7 начались проблемы с тем что если карта состоит из букв, то она не читается вообще, и фронт пишет "карта не зарегистрирована в системе", прикладываю пример, где я сканирую карту 1716823588 и все хорошо работает, в кэш сервере вижу запись 
[2022-05-05 11:44:36,454]  INFO [21] [CardProcessor:CardRolledHandler] - Card slided 1:, 2:171****588, 3:
далее сканирую карту 74B2B251, фронт говорит "карта не зарегистрирована в системе", если остановить видео то видно что доходят только цифры 
![image](https://user-images.githubusercontent.com/74863190/166891532-24d74b4c-bb81-4a82-90d9-ee8f90571c17.png)

![2022-05-05-11-44-30](https://user-images.githubusercontent.com/74863190/166890555-60bbaf0b-6cdf-487c-bf11-e81beedefaa5.gif)

используем мы для прокидывания карты вот такой простой код
![image](https://user-images.githubusercontent.com/74863190/166889830-cbb8be71-16ba-4528-9c5e-114a8252152d.png)

Может сможете подсказать в чем причина данного поведения, с версии 797 появилась эта проблема у всех и даже с картами которые состоят из цифр, а в логе кеш сервера всегда одно и тоже 
[2022-05-05 11:09:07,331]  INFO [51] [CardProcessor:CardRolledHandler] - Card slided 1:<bar******************************************************************r"/>, 2:C**D, 3:ba***de

**Comment by letolica** [comment]
Добрый день.
Здесь мы обсуждаем функционал iikoFront.API. Функционал обработки считывания (прокатки, сканирования) карт реализован внутри iikoFront и к апи отношения не имеет. Правильнее и эффективнее с таким вопросом обратиться в [техподдержку](https://iiko.ru/support). Они помогут разобраться с настройками и заведут задачу на разработку, если действительно есть ошибка.
