### ISSUE TITLE
Печать "Квитанция об оплате".

### ISSUE THREAD

**Issue by aitkkia** [iiko/front.api.sdk#363]
Добрый день.
Если реализовать интерфейс IChequeTaskProcessor, то можно добавлять свои данные в печать чека. Не понятно, что делать, если данные необходимо вывести при печати "Квитанция об оплате" или предчек?

**Comment by igorpooh1978** [comment]
Добрый день
https://iiko.github.io/front.api.doc/2021/07/01/repeat-before-order-bill.html

**Comment by letolica** [comment]
Добрый день.
Попробуйте [CashChequePrinting](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_CashChequePrinting.htm), [BillChequePrinting](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BillChequePrinting.htm).

**Comment by aitkkia** [comment]
@letolica, SubscribeOnBillChequePrinting - позволяет работать с предчеком, а IChequeTaskProcessor с чеком, но в случае если тип оплаты стоит не фискальный(настройка в iikofront в типах оплаты), то при печати чека мы не попадаем в BeforeDoCheckAction.
CashChequePrinting/BillChequePrinting - нет в v6. Постараюсь проверить плагин для v7.

**Comment by vcpp** [comment]
> CashChequePrinting/BillChequePrinting - нет в v6.

Есть, в V6 был немного другой контракт: [`SubscribeOnCashChequePrinting`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_INotificationService_SubscribeOnCashChequePrinting.htm)/[`SubscribeOnBillChequePrinting`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_INotificationService_SubscribeOnBillChequePrinting.htm). Пример [тут](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePlugin/BillChequeExtender.cs).

Впрочем, если вы пишете плагин под iikoRMS 7.9 и новее, то лучше, конечно, сразу выбрать V7, чем начать с V6 и через год мигрировать на V7.
