### ISSUE TITLE
Подписка на событие печати предварительного заказа на банкет

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#364]
Добрый день. Мне нужно во FrontAPI подписаться на событие печати чека предварительного заказа на банкет.
Так как клиент изъявил желание печатать этот чек на притер А4 в совершенно другом формате, хочу написать плагин, который будет подписан на это событие и печатать по собственному шаблону на принтер А4.

Но я не нашел в Notifications подписки на событие печати предварительного заказа на банкет, подскажите, может есть какой то обходной путь? Либо есть ли возможность добавить в Notifications это событие в ближайшем обновлении API Front?

**Comment by letolica** [comment]
Добрый день.
> подскажите, может есть какой то обходной путь?

Добавить на экран редактирования заказа плагинную кнопку ([AddButtonToOrderEditScreen](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_AddButtonToOrderEditScreen.htm)) и по нажатию печатать чек произвольного формата на произвольный принтер. Не нажимать на кнопку печати предварительного заказа на экране редактирования банкета, а нажимать на плагинную кнопку на экране редактирования заказа.

**Comment by pro100roman24** [comment]
Ну как обходной вариант да, наверно так и сделаем. А добавить это в Notifications  не запланируете?

**Comment by vcpp** [comment]
Могу предложить ещё два корявых обходных варианта:
* Реализовать фиктивный фискальный регистратор исключительно ради метода [`PrintText`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Devices_ICashRegister_PrintText.htm) и назначить его принтером пречеков. В таком случае в плагин будет приходить стандартная разметка предварительного заказа банкета, которую можно игнорировать и использовать вызов метода просто как сигнал, который вы хотели. Дальше остаётся взять текущий редактируемый [резерв](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Screens_IReserveEditScreen_Reserve.htm) и напечатать для него произвольный чек на произвольный принтер. В качестве побочного эффекта в плагин пойдут и остальные [документы, печатаемые на принтере пречеков](https://ru.iiko.help/articles/iikooffice-8-0/topic-266/a/h3_675922635) — сам пречек, накладная доставки, табличка о резервировании стола, придётся разводить эти операции по разным терминалам, чтобы по умолчанию использовался реальный принтер пречеков, а на терминале для печати предзаказов — ваш плагин.
* Задать пользовательский шаблон типа «Чек предварительного заказа на банкет». В razor-шаблоне вы фактически пишете произвольный код на C#, мы пока не ограничиваем этот код какой-либо песочницей, поэтому вы можете выполнить печать непосредственно из кода шаблона, вызвать какой-нибудь веб-сервис для печати, либо каким-нибудь образом отправить сигнал вашему плагину. Не забудьте только, что формально вы пишете шаблон чека, поэтому в конце надо будет вернуть разметку, состоящую из единственного тэг `nodoc`, чтобы штатная печать на принтер пречеков не сработала.

В `Notifications`, конечно, надо добавить, но прежде уточню формат — вы ожидаете нечто вроде [`BeforeServiceCheque`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeServiceCheque.htm), чтобы отменить штатную печать путём генерации [`OperationCanceledException`](https://docs.microsoft.com/dotnet/api/system.operationcanceledexception)?

**Comment by rengal** [comment]
1. В API V9Preview2 будут подписки 
```PluginContext.Operations.RegisterBeforeFormatDocumentHandler``` ```PluginContext.Operations.RegisterAfterFormatDocumentHandler```
Эти подписки срабатывают при печати любых документов.

```csharp
/// <summary>
/// Allows modifying the document before the formatting. Returning 'null' from the callback will result in no changes being applied to the document markup.
/// </summary>
/// <param name="callback">
/// Callback to return modified document.
/// </param>
[NotNull]
IDisposable RegisterBeforeFormatDocumentHandler([NotNull] Func<(Guid printingDeviceId, Resto.Front.Api.Data.Print.Document documentMarkup), Resto.Front.Api.Data.Print.Document> callback);
/// <summary>
/// Allows modifying the document after the formatting. Returning 'null' from the callback will result in no changes being applied to the document markup.
/// </summary>
/// <param name="callback">
/// Callback to return modified document.
/// </param>
[NotNull]
IDisposable RegisterAfterFormatDocumentHandler([NotNull] Func<(Guid printingDeviceId, Resto.Front.Api.Data.Print.Document documentMarkup), Resto.Front.Api.Data.Print.Document> callback);
```

3. Подписка содержит только разметку документа: `RegisterBeforeFormatDocumentHandler` - неотформатированную, `RegisterAfterFormatDocumentHandler` - отформатированную, но не содержит тип документа или данные. Чтобы передать какие-нибудь данные, можно воспользоваться тегом <section>
```
<doc>
   <section name="documentType" data="banquet" />
   <section name="orderId" data="@Model.OrderId" />
  ...
</doc>

4. Если не устраивают возможности стандартной разметки, то в ближайшее время появится поддержка тега <html>, в которой возможности по формированию разметки документов практически не ограничены.

**Comment by pro100roman24** [comment]
Это крутое решение
