### ISSUE TITLE
Создание складских документов при закрытии кассовой смены

### ISSUE THREAD

**Issue by Denisov111** [iiko/front.api.sdk#369]
Здравствуйте! Необходимо в IikoFront сгенерировать акты реализации и акты приготовления отдельно для каждого склада списания при закрытии кассовой смены. Для этого нужно получить склад списания по каждому заказу/блюду. Подскажите, есть ли возможность получить склады списания? Версия API v7.

**Comment by ierof** [comment]
Нет, такой возможности нет, у нас не предполагается выставление в API iikoFront контура по документообороту iikoKitchen. Как создание документов, так и признаки этого контура у продуктов.
