### ISSUE TITLE
Как прервать процесс выполнения оплаты?

### ISSUE THREAD

**Issue by KellsoHP** [iiko/front.api.sdk#37]
Доброго дня.
Как прервать процесс выполнения оплаты после  нажатия кнопки "оплатить"?

Желаемый кейс такой:
1. При нажатии кнопки "Оплатить", выполняется запрос к внешней системе, пусть будет REST API.
1. От API приходит какой-то ответ, после которого мы должны прервать процесс.
1. После прерывания, возвращаемся на экран оплаты. Чек не напечатался.

---

Плагин использует Resto.Front.Api.V5 - 5.4.1160

**Comment by GulnaraBikbova** [comment]
Добрый день.
Это можно сделать на api версии V6Preview4.

См. статью: https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html

**Comment by KellsoHP** [comment]
> Добрый день.
> Это можно сделать на api версии V6Preview4 ( v6.4 )
> 
> См. статью: https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html

Правильно я понимаю, что бы использовать V6Preview4, необходимо IikoFront версии 6.4+?

**Comment by KellsoHP** [comment]
Или перефразирую вопрос, начиная с какой версии iiko front можно использовать api V6Preview4?

**Comment by CLTanuki** [comment]
@KellsoHP , мы уже используем. Приходится пересобирать под разные версии, но уже вполне можно.

**Comment by CLTanuki** [comment]
С другой стороны, мы обычно делаем это в  подписке на INotificationService.OrderChanged, где складываем в кэш всё, что не обработалось, и отправляем позже.

**Comment by KellsoHP** [comment]
Спасибо!
