### ISSUE TITLE
Экран меню плагина не модальный.

### ISSUE THREAD

**Issue by fader1** [iiko/front.api.sdk#370]
Добрый день! 

Подскажите пожалуйста, как можно сделать экран с меню как в плагине Plazius. Скриншот такого экрана у плагина Plazius: https://disk.yandex.ru/i/llRFOx5N2ZDe-A
(В API нашёл только про то как работать Диалоговыми Popup окнами, а как сделать подобное меню на основном экране нет информации)

**Comment by aitkkia** [comment]
https://iiko.github.io/front.api.doc/v6/ru/CustomWindows.html - возможно поможет. Но на самом в работе это выглядит не очень красиво. То есть возможно сделать так "может оказаться позади окна iikoFront" и это ужасно. Поэтому делаем на весь экран форму + убираем у неё кнопки свернуть/развернуть/изменения размера окна.

**Comment by vcpp** [comment]
> Подскажите пожалуйста, как можно сделать экран с меню как в плагине Plazius. Скриншот такого экрана у плагина Plazius: https://disk.yandex.ru/i/llRFOx5N2ZDe-A

Именно как на скриншоте у Plazius не получится, в этом случае речь идёт о плагине старого образца, который работает не через API, а прямо внутри приложения iikoFront. Можно посмотреть, как работает API-версия их плагина (Resto.Front.Api.Platius).

Если вам просто нужен диалог с четырьмя кнопками, как на скриншоте, используйте [`ShowChooserPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowChooserPopup.htm). Если среди методов `IViewManager` не найдёте подходящего готового диалога, придётся делать собственное окно и показывать его поверх всех окон. Ссылку на [статью](https://iiko.github.io/front.api.doc/v6/ru/CustomWindows.html) вам уже дали, можете ещё посмотреть примеры [тут](https://github.com/iiko/front.api.sdk/issues/10).

> в работе это выглядит не очень красиво

Да, сложно попасть в стиль, повторить пропорции, цветовую схему... А потом пользователь выберет светлую тему, и плагинное окно все равно будет выглядеть инородно. Мы пока не придумали, как изящно решить эту проблему.
