### ISSUE TITLE
Нужна информация по Resto.BackApi.Core

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#372]
Добрый день. Подскажите пожалуйста, если есть возможность.
Есть ли где-то, какая то информация по созданию плагинов для iikoOffice?
Я нашел сэмпл плагина для бэкофиса, но не понимаю, можно ли как то настроить отладку в реальном времени.
Хотелось бы научиться писать плагины для бэкофиса.

**Comment by aitkkia** [comment]
https://iiko.github.io/front.api.doc/v6/ru/Debugging.html - смотрели?

**Comment by pro100roman24** [comment]
> https://iiko.github.io/front.api.doc/v6/ru/Debugging.html - смотрели?

Какое это имеет отношение к моему вопросу?
Я спрашиваю где найти информацию по отладке плагинов для БЭКОФИСА айко.

**Comment by vcpp** [comment]
Duplicates #153.
