### ISSUE TITLE
Внесение небольших дополнений в раздел Отладка на https://iiko.github.io/front.api.doc для VS2022

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#373]
Всем привет!

В процессе работы тут натолкнулся на интересный баг в с VS2022 17.2 в при отладке проекта.
Проект не стартует, при этом во вкладке build видно что загрузка файла host.exe ломается на log4net.dll

строка отладки выглядела так
Debug --> General 
![image](https://user-images.githubusercontent.com/47010778/174639042-65d2a6db-9d65-465b-8072-b250a10d6983.png)
если проект делается под Project Sdk (.csproj)
```
<Project Sdk="Microsoft.NET.Sdk">
</Project>
```
Напоролся на то, что при старте проекта в режиме отладки, проект просто прекратил свою работу, при чем под VS2017 он успешно стартует.
Решение подсказал ваш коллега (Павел), за что ему отдельное и огромное спасибо. 
Проблема оказалась в том, что при наличии в строке соотношения \net472 \n отрабатывает как перевод каретки, а  не \n
имеем
```
/a="C:\Projects\Front.Api Sdk\Resto.Front.Api.SamplePlugin\bin\net472\Debug\Resto.Front.Api.SamplePlugin.dll" /c=Resto.Front.Api.SamplePlugin.SamplePlugin /m=21005108 /l="C:\Projects\Front.Api Sdk\Logs\sample-plugin.log"
```
под дебагом не запуститься
Простое решение, добавить в корень проекта файл Directory.Build.targets со следующим содержанием
```
<?xml version="1.0" encoding="utf-8" ?>
<Project>
  <PropertyGroup>
    <PluginTargetPath>$(TargetPath.Replace('\','/'))</PluginTargetPath>
	  <PluginTargetDir>$(TargetDir.Replace('\','/'))</PluginTargetDir>
  </PropertyGroup>
</Project>
```
а в Debug --> General 
```
/p=Resto.Front.Api.Plugin /a=$(PluginTargetPath) /c=Resto.Front.Api.Plugin.Plugin /m=21011234 /l=$(PluginTargetDir)/log/plugin.log
```

BTW. Под VS2019 наблюдал такое же поведение

**Comment by ierof** [comment]
Статью обновили https://iiko.github.io/front.api.doc/debugging.html
