### ISSUE TITLE
AddOrderGuest Submit api front v7

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#374]
```
IEditSession EditSession = PluginContext.Oprations.CreateEditSession();

var GuestId = new Guid("0a810b06-8936-4d35-829b-9497a220ec33");
string GuestName = "Гость";
var Guest = EditSession.AddOrderGuest(GuestId, GuestName, DeliveryOrder);

SubmitChanges(EditSession);
```

```
IEditSession EditSession = PluginContext.Oprations.CreateEditSession();

var GuestId = new Guid("0a810b06-8936-4d35-829b-9497a220ec33");
string GuestName = "Гость";
var Guest = EditSession.AddOrderGuest(GuestId, GuestName, DeliveryOrder);

SubmitChanges(EditSession);
```

При реализации второго кода получаю исключение ArgumentException Элемент с тем же ключом уже был добавлен.
Все как бы хорошо, но гость добавился и касса вылетает с фотальной ошибкой 

> FATAL [LoadingScreenController] [MainController:CurrentDomain_UnhandledException:300] - Unhandled exception
> System.ArgumentException: Элемент с тем же ключом уже был добавлен.
>    в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
>    в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    в System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    в Resto.CashServer.Services.Extensions.RootOrderItemExtensions.BuildStringView(IEnumerable`1 items, IEnumerable`1 guests, IOrderPrices orderPrices, ProductListStringViewBuilder builder) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer.Services\Extensions\RootOrderItemExtensions.cs:строка 292
>    в Resto.CashServer.Services.Extensions.RootOrderItemExtensions.GetLinearStringView(IEnumerable`1 items, IEnumerable`1 guests, IOrderPrices orderPrices) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer.Services\Extensions\RootOrderItemExtensions.cs:строка 283
>    в Resto.Front.Model.Orders.OpenedOrderInfoModel.Update(IBaseOrder baseOrder) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Orders\OpenedOrderInfoModel.cs:строка 68
>    в Resto.Front.Model.Deliveries.DeliveryInfoModel.UpdateOrder(IDeliveryOrderEntity order, ILockedOrderInfoModel lockedOrderInfo) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Deliveries\DeliveryInfoModel.cs:строка 502
>    в Resto.Front.Model.Deliveries.DeliveryInfoModel.Update(IDeliveryOrderEntity order) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Deliveries\DeliveryInfoModel.cs:строка 435
>    в Resto.Front.Model.Deliveries.DeliveryInfoModel..ctor(IDeliveryOrderEntity order, ICustomerEntity customer) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Deliveries\DeliveryInfoModel.cs:строка 208
>    в Resto.Front.Model.Deliveries.DeliveriesListModel.AddOrUpdateDelivery(IDeliveryOrderEntity order) в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Deliveries\DeliveriesListModel.cs:строка 276
>    в System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext) в d:\a\1\s\Ix.NET\Source\System.Interactive\System\Linq\Operators\ForEach.cs:строка 24
>    в Resto.Front.Model.Deliveries.DeliveriesListModel.Update() в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\Deliveries\DeliveriesListModel.cs:строка 466
>    в Resto.Front.Model.ModelFactory.EnsurePrimaryModelsCreated() в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Model\ModelFactory.cs:строка 683
>    в Resto.Front.Controllers.LoadingScreenController.<>c__DisplayClass13_0.<DoStartup>b__2() в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Controllers\LoadingScreenController.cs:строка 243
>    в Resto.Framework.Common.UiDispatcher.<>c__DisplayClass18_0.<Execute>b__0() в L:\BuildAgent\work\master-installer\dev\Framework\dev\Net\Resto.Framework\Src\Common\UiDispatcher.cs:строка 118
> --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
>    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    в Resto.Framework.Common.UiDispatcher.Execute(Action action, DispatcherPriority priority) в L:\BuildAgent\work\master-installer\dev\Framework\dev\Net\Resto.Framework\Src\Common\UiDispatcher.cs:строка 131
>    в Resto.Front.Controllers.LoadingScreenController.DoStartup() в L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Controllers\LoadingScreenController.cs:строка 281
>    в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    в System.Threading.ThreadHelper.ThreadStart()

**Comment by igorpooh1978** [comment]
ну ведь у вас действительно добавлен гость с тем же id зачем ?

**Comment by Keeplod** [comment]
> ну ведь у вас действительно добавлен гость с тем же id зачем ?

@igorpooh1978 Я планирую все варианты, и если такое произойдет придется лезть в БД front и испралять, по другому кассой работать не возможно.

**Comment by igorpooh1978** [comment]
Не очень понял варианта такой работы, но видимо имеет место быть. Может просто распишите всю процедуру и коллеги с iiko расскажут как быть.

**Comment by Keeplod** [comment]
@igorpooh1978 Нет необходимости всей процедуры, проблема в том что submit выдает исключени (что правильно), но в тоже время и отрабатывает сессию (что не ок)

**Comment by vcpp** [comment]
Возможность указывать id извне — дыра. Удобная, но дыра. Если заказ получен из внешнего источника, удобно указать непосредственно идентификаторы, сгенерированные внешним источником. Однако, если при этом допустить дублирование идентификаторов, всё сломается. Правильный вариант — иметь маппинг с внешних идентификаторов на внутренние, это муторно, но что поделать.

У метода `AddOrderGuest` есть две [перегрузки](https://iiko.github.io/front.api.sdk/v7/html/Overload_Resto_Front_Api_Editors_IEditSession_AddOrderGuest.htm). Используйте [ту](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderGuest_1.htm), что не позволяет указать id.

При использовании перегрузки, позволяющей указать id, необходимо обеспечить глобальную уникальность этого идентификатора. Из [комментария](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderGuest.htm): _Unique identifier of the new guest in the order. MUST be unique not only for the order, but for the whole system. Therefore it must be taken from some synchronization operation or generated with Guid.NewGuid()_.
Поскольку проблем, вызванных неправильным использованием этой перегрузки становится всё больше, мы удалим её в V8.
