### ISSUE TITLE
Значение поля 'Operation' в ответе запроса 'Get programs' iikoCloud API

### ISSUE THREAD

**Issue by maxpostal** [iiko/front.api.sdk#375]
Добрый день.

Меня к вам направила Команда поддержки API <iiko_client_api@iiko.ru>

Я использую АПИ iiko Cloud https://api-ru.iiko.services/ в плагине интеграции бонусной системы с WooCommerce, а именно метод https://api-ru.iiko.services/api/1/loyalty/iiko/program для получения программ лояльности.
Мне не совсем ясен смысл параметра `Programs - marketingCampaigns - orderActionConditionBindings - conditions - settings - Operation` в ответе АПИ, точнее его цифровой код.

![image](https://user-images.githubusercontent.com/10470303/174963451-c6bf8cf7-bfe3-4a4e-8f5f-2a818b3e17ab.png)

На сколько я понимаю 4 - это больше, а 1 - это меньше, верно?
Есть ли где-то список всех возможных вариантов?

Заранее спасибо.

**Comment by vcpp** [comment]
> Меня к вам направила Команда поддержки API [iiko_client_api@iiko.ru](mailto:iiko_client_api@iiko.ru)

Это странно. На данной площадке консультируем по iikoFront API — это API кассового приложения, позволяющее писать .NET-плагины. Я передам ссылку на ваш вопрос коллегам из команды iikoCloud API. К сожалению, пока нет прямого способа обратиться к ним за консультацией, только через общую техподдержку.

**Comment by d0nncha** [comment]
> На сколько я понимаю 4 - это больше, а 1 - это меньше, верно? Есть ли где-то список всех возможных вариантов?
Добрый день!
Полный список следующий:
Less = 1,
LessOrEqual = 2,
Greater = 3,
GreaterOrEqual = 4,
Equal = 5,

**Comment by maxpostal** [comment]
Благодарю.
