### ISSUE TITLE
ERROR GetOrders and GetDeliveryOrders API v7

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#379]
Если есть один и более доставочные заказы с блюдами разделенными на гостей то получаю ошибку при функции
GetOrders или GetDeliveryOrders:
Не удалось привести тип объекта "Resto.Front.Api.V7.Data.Assortment.Product" к типу "Resto.Front.Api.Data.Orders.IOrderGuestItem".
Как быть?

PS Ошибка выходит только если гость добавлен через апи https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderGuest.htm
Может быть связано с тем что я добавляю гость не в StubOrder?

Хмм... При создания гостя использовал новый id и все работает... Конфликт id какой-то ?

Но если заказ по GetDeliveryOrderById ошибки нету, только при получении всех заказов выходит ошибка

**Comment by vcpp** [comment]
> При создания гостя использовал новый id и все работает

Да, идентификаторы должны быть глобально уникальны. Комментарий из справки по приведённой вами [ссылке](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderGuest.htm): _Unique identifier of the new guest in the order. MUST be unique not only for the order, but for the whole system. Therefore it must be taken from some synchronization operation or generated with Guid.NewGuid()_.

А вообще используйте лучше [перегрузки](https://iiko.github.io/front.api.sdk/v7/html/Overload_Resto_Front_Api_Editors_IEditSession_AddOrderGuest.htm), не позволяющие указать id, тогда мы сами сгенерируем их с помощью `Guid.NewGuid()`. Наличие используемой вами перегрузки — дыра. Указывая неуникальные идентификаторы, вы можете нарушить работу приложения. Начиная с V8 планируем удалить перегрузки, позволявшие указать id.
