### ISSUE TITLE
Не прогружается PublicData заказа на сервер

### ISSUE THREAD

**Issue by ZakharovOpen** [iiko/front.api.sdk#380]
API v7
При попытке записать externalData в заказ со статусом Closed публичные данные записываются в заказ (ее можно получить через плагин), но на сервер инф не попадает, такое ощущение, что не поднимается ревизия и поэтому данные не прогружаются
![report](https://user-images.githubusercontent.com/88644943/175523583-b20b3ead-13d8-4ebe-83fc-ff87fc7c5620.png)
![code](https://user-images.githubusercontent.com/88644943/175523587-3341e713-74ff-44e9-90d0-5cdf0dc427ca.png)
![log](https://user-images.githubusercontent.com/88644943/175523589-430b2221-6f8e-462e-be25-4d1d19d98a43.png)
.

**Comment by vcpp** [comment]
В текущей реализации данные отправляются на сервер в момент оплаты, соответственно, новые данные, добавленные после оплаты, на сервер отправлены не будут. Не подумали, что в закрытом заказе будут происходить изменения, обычно закрытый заказ или «оживает» при возврате, или удаляется при закрытии кассовой смены.

Пока затрудняюсь классифицировать это как баг или фичу, подумаем.
Судя по коду, вы добавляете внешние данные сразу после завершения оплаты. Почему бы не делать в процессе оплаты, например, по событию [`BeforeDoCheque`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeDoCheque.htm)?

**Comment by ZakharovOpen** [comment]
@vcpp  к сожалению, то же не отработал метод.
Т.е. история повторилась, в бд фронта инф записалась, а вот на сервер не попала.
Логи:
```
[2022-08-18 14:04:30,132]  INFO [12] - Order = f9455c36-025d-4f09-b34d-c46819210fba (49)
[2022-08-18 14:04:30,133]  INFO [12] - publicData = Internal order id - 351166828
[2022-08-18 14:04:30,141]  INFO [12] - extData = 
[2022-08-18 14:04:30,183]  INFO [12] - extDataN = Internal order id - 351166828
```
```
[2022-08-18 14:04:34,972]  INFO [ 9] - Order = 7d62ac2f-03b2-44af-bc2e-720dfe60dac9 (50)
[2022-08-18 14:04:34,973]  INFO [ 9] - publicData = Internal order id - 351166839
[2022-08-18 14:04:34,979]  INFO [ 9] - extData = 
[2022-08-18 14:04:35,013]  INFO [ 9] - extDataN = Internal order id - 351166839
```
![image](https://user-images.githubusercontent.com/88644943/185381199-3746248b-8231-44b7-a099-c489df664b00.png)
![image](https://user-images.githubusercontent.com/88644943/185381288-bfbd2c97-9523-4639-a13e-18d02d9384c9.png)
![image](https://user-images.githubusercontent.com/88644943/185381320-397c2d4f-8744-403c-9055-d79f31f66a24.png)

**Comment by vcpp** [comment]
Хм.. Оказалось, после оплаты на сервер отправляются данные, зафиксированные до оплаты, то есть мы не учитываем изменения, внесённые в процессе оплаты. Ошибка. Поправим в одной из следующих версий.

Внутренний номер: RMS-53884.

**Comment by mbagritsevich** [comment]
Поправлено в v8. Теперь изменить нужные данные можно подписавшись на BeforeDoCheque.
