### ISSUE TITLE
Алкоголь

### ISSUE THREAD

**Issue by mgdmiller** [iiko/front.api.sdk#382]
Добрый день, коллеги.

Как во фронтовом api определить что продаваемый товар является маркируемым (алкоголь, сигареты)?

**Comment by vcpp** [comment]
В момент оплаты, если вы реализуете [`ICashRegister`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Devices_ICashRegister.htm) или [`IChequeTaskProcessor`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Devices_IChequeTaskProcessor.htm), можете смотреть поля [`ChequeSale.CommodityMark`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Device_Tasks_ChequeSale_CommodityMark.htm) и [`ChequeSale.CommodityCode`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Device_Tasks_ChequeSale_CommodityCode.htm). Напрямую для [`IProduct`] пока, к сожалению, нельзя узнать. Напишите подробнее, какой сценарий хотите реализовать и для законодательства какой страны.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
