### ISSUE TITLE
Получение сгруппированных блюд

### ISSUE THREAD

**Issue by yunmikun2** [iiko/front.api.sdk#383]
Здравствуйте, у нас есть необходимость организовать получение
"сетов" блюд из iikoFront.

Получение данных из iikoFront происходит через обращение к REST API
интерфейсу через плагин
https://ru.iiko.help/articles/#!api-documentations/front-web-api.

Группировка блюд обозначается следующим образом. В iikoChain, по пути
"Товары и склады" -> "Блюда", в основном блюде (по нажанию двойного
клика) открывается вкладка "Технологические карты" добавляется
тех. карта с отдельными элементами. Полученное блюдо будет являться
сетом.

Вопрос заключается в том, как можно получить данные сгруппированные
элементы через iikoFront API?

Если это невозможно, то возможно ли получить эти же данные через REST
API у iikoChain?

Если и это невозможно, то какие альтернативные способы группировки
блюд в сеты мы можем использовать, чтобы была возможность получить их
через REST API?

**Comment by vcpp** [comment]
> Вопрос заключается в том, как можно получить данные сгруппированные
элементы через iikoFront API?

Увы, это пока не поддерживается.

> Если это невозможно, то возможно ли получить эти же данные через REST
API у iikoChain?

Посмотрите API технологических карт [тут](https://ru.iiko.help/articles/api-documentations/recipes).
