### ISSUE TITLE
Внешний тип оплаты. Не поставить галочку "может приниматься извне"

### ISSUE THREAD

**Issue by fader1** [iiko/front.api.sdk#384]
Почему внешняя платёжная система не может приниматься извне?   
Для заказов в ресторане всё норм, созданный в плагине тип оплаты "Внешний тип оплаты" добавляется в заказ без проблем.
Но к сожалению нельзя поставить галочку "может приниматься извне"  и получается ограничение при получении доставок с сайта не возможно использовать регистрируемый в плагине тип оплаты "Внешний тип оплаты" https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html
Это очень не удобно. К примеру, (назовём созданный тип "Оплата баллами"), при доставке в случаях когда весь процесс оплаты происходит онлайн на сайте, то хотелось бы присылать с сайта заказ с этим же типом оплаты в флагом "проведён".
Или в случаях заказов с сайта  с оплатой в ресторане, было бы хорошо присылать заказ с типом "Оплата баллами" как не проведённый, чтобы уже при оплате на фронте срабатывал плагин и проводил эту оплату.
Но как раз созданный тип оплаты не виден через iikoDelievryAPI (нельзя поставить галочку "может приниматься извне" в настройках типа оплаты), и получается мы не можем отправить заказ в ресторан с использованием зарегистрированного в созданном плагине внешнего типа оплаты. 

Пожалуйста, если возможно, хотелось бы иметь возможность использовать в заказах доставки регистрируемого из плагина "внешнего типа оплаты". (чтобы как в типах "Банковские карты" можно было ставить галочку "может приниматься извне" с возможностью проведения "Как внешний так и на стороне ресторана" )

**Comment by fader1** [comment]
В итоге пришлось поступить следующим образом:
Когда гость выбирает на сайте "списать баллы", то мы добавляем в заказ тип оплаты "Баллы сайт" созданный на основе базового типа "банковская карта".
При поступлении заказа доставки на терминал, плагин подменяет этот тип на свой "Оплата Баллами" (базовый тем "внешняя оплата" регистрируемый плагином с привязкой скидки в настройках).
В случаях, когда требуется проведение оплаты и списание баллов на кассе (в iikoFront), то всё хорошо.
НО, когда Онлайн-оплата и списание баллов проводится на сайте, то заказ доставки поступает в терминал с типами оплат "Онлайн-оплата" (базовый тип "банковская карта") и "Баллы сайт" (базовый тип также "банковская карта"), но оба типа ПРОВЕДЁННЫЕ (с isProcessedExternally = true ).
И вот тип "Баллы сайт" мы не можем заменить на ПРОВЕДЁННЫЙ "Оплата Баллами".  Iiko не даёт "внешний" тип оплаты регистрируемый плагином добавить в заказ как ПРОВЕДЁННЫЙ.  
(AddExternalFiscalizedPaymentItem или AddExternalPaymentItem с isProcessed=true  выдают ошибку:   **Resto.Front.Api.Exceptions.ConstraintViolationException**: "Payment item of type Оплата Баллами ..... cannot be added as external processed. PaymentType should be CanBeExternalProcessed."
)
Если пробовать провести его командой Pay. то заказ доставки **перескакивает на шаг отправки** (минуя готовку и т.д.), что не допустимо в данном  случае.
В итоге решено оставить пока так. Но минус в том что в списке заказов заказ не отображается как "Оплачено" (хотя он оплачен и баллы списаны). что несколько путает сотрудников.
(в заказе в доп. параметрах выставляем флаг, что на самом деле баллы по заказу уже списаны, и при проведении этой оплаты "Оплата Баллами" на терминале на шаге отправки заказа, смотрим, если есть такой флаг, то просто не выполняем в плагине фактическое списание баллов, и этот тип оплаты становится "проведённым").
Есть ещё вариант НЕ подменять тип "Баллы сайт" (банковская карта) на "Оплата Баллами" (плагинный "внешний платеж"), тогда сразу видно что заказ "Оплачен", НО получается что тип оплаты "Баллы сайт" падет в чек и отчеты в дальнейшем как выручка, как оплата банковской картой, а надо как скидка (как в случае "внешней оплаты" ("Оплата Баллами"), регистрируемой плагином с привязкой скидки в настройках).

Так что очень надеемся что в будущих версиях API можно будет  добавлять сразу проведённым "внешний тип оплаты" регистрируемый плагином, чтобы он мог быть CanBeExternalProcessed.  Спасибо!

**Comment by vcpp** [comment]
> очень надеемся что в будущих версиях API можно будет добавлять сразу проведённым "внешний тип оплаты"

Да, так и будет. Текущее ограничение сильно усложняет востребованные сценарии работы, постараемся снять это ограничение.

Внутренний номер заявки: SPRT-28389.
