### ISSUE TITLE
Resto.Front.Api.v8 убрали GetOrderAppliedDiscounts

### ISSUE THREAD

**Issue by AlibekMeldekhanov** [iiko/front.api.sdk#385]
Как получить скидки примененные к заказу IAppliedDiscountItem

**Comment by igorpooh1978** [comment]
https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_IOrder.htm
вроде как вот они

**Comment by AlibekMeldekhanov** [comment]
> https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_IDiscountItem.htm
> 
> https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_IOrder.htm вроде как вот они

для получения суммы  Call [!:IOperationService.GetOrderAppliedDiscounts] to get calculated sums. Но этот метод не доступен или его убрали. 
поменял на https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IOrder_PaymentDiscounts.htm

**Comment by letolica** [comment]
[IOrder.PaymentDiscounts](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IOrder_PaymentDiscounts.htm) — это оплатные скидки.
Обычные скидки: [IOrder.AppliedDiscounts](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IOrder_AppliedDiscounts.htm)

**Comment by vcpp** [comment]
То, что в V6 надо было получать отдельным вызовом метода [`GetOrderAppliedDiscounts`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetOrderAppliedDiscounts.htm), начиная с V7 доступно непосредственно в заказе: [`AppliedDiscounts`]https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_AppliedDiscounts.htm).

Прежний вариант имел недостатки — между получением `IOrder` и вызовом `GetOrderAppliedDiscounts` заказ мог успеть поменяться, так что плагин не мог надёжно получить согласованное заказа и его скидок, заказ мог вообще удалиться, то есть плагин мог вовсе не успеть получить скидки. Запрос скидок приходилось выносить в отдельный вспмогательный с обработкой ошибок, муторно и громоздко. Теперь и надёжнее, и код проще, но при миграции с V6 на V7 и новее приходится заменять вызов метода на чтение свойства.
