### ISSUE TITLE
Json serialization issue

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#386]
Всем привет.
Хочу сериализировать `Rest.Front.Api.V7.Data.Orders.Order` с использованием` Newtonsoft.Json.JsonConvert.SerializeObject()`
```
 var order = PluginContext.Operations.GetOrderById(OrderId);
 var result =  JsonConvert.SerializeObject(order, Formatting.None);
             
```
Получаю исключение

> Self referencing loop detected with type 'Resto.Front.Api.V7.Data.Organization.Sections.RestaurantSection'. Path 'Items[0].Kitchen.Tables[0]'.

**Comment by igorpooh1978** [comment]
https://github.com/iiko/front.api.sdk/issues/354#issuecomment-1114635359
