### ISSUE TITLE
Как можно получить данные закрытого заказа средствами Front SDK 7 уже в закрытой смене

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#388]

**Comment by Keeplod** [comment]
Нашел метод https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetPastOrder.htm
а если я хочу получить заказы за определенный период? (iikoServer знаю, но хочется через SDK)

**Comment by vcpp** [comment]
> а если я хочу получить заказы за определенный период?

Тогда придётся использовать iikoServer API.
Всё-таки iikoFront — кассовое приложение, там только оперативные данные. Расскажите, какую задачу вы хотите решить?

**Comment by Keeplod** [comment]
Клиент хотел по кнопочке получать заказы гостя за определенный период.
