### ISSUE TITLE
Добавление email для отправки чеков в runtime

### ISSUE THREAD

**Issue by MrNeuronix** [iiko/front.api.sdk#389]
Добрый день!
Ищем способ добавить имейл гостя для отправки ему чека о заказе, вместо печати.
Наш плагин получает имейл в процессе работы (выбор нашего типа оплаты -> сканирование QR кода с телефона гостя -> обмен данными с нашим облаком -> получение имейл гостя в ответе). Т.е. workaround с подпиской на событие перехода на экран оплаты не подходит, т.к. в этот момент данных о госте у нас еще нет.
Насколько я понял, остается на текущий момент только вариант с созданием/добавлением/поиском существующего iiko гостя с соответствующим имейл и добавление его в заказ.
Хочется понять, можем ли мы это сделать в виде редактирования заказа и получить некий кусочек кода, как это правильно сделать. В примерах не нашел.
Версия API - видимо 7, но если получится и для 6 сделать - будет отлично.

**Comment by rgalk** [comment]
> остается на текущий момент только вариант с созданием/добавлением/поиском существующего iiko гостя с соответствующим имейл и добавление его в заказ.
Посмотрите метод [SearchClients](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_SearchClients.htm), он позволяет искать гостей по различным полям (см. [ClientFields](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Search_ClientFields.htm)), искать гостей можно по вхождению подстроки, а также по полному совпадению.

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/2024/05/02/set-cheque-additional-info.html
