### ISSUE TITLE
Получить сумму Наличных в кассе

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#39]
Добрый день. У меня плагин для Инкассации и формировании сопроводительных документов для банка. 
Есть задача Когда кассир собирает сумку инкассаторам. И мне нужно показать Рекомендуемую сумму к сдаче. Которая формируется из Наличных за несколько дней. 
1) С начало я это получал от сервера через ОЛАП. Но возникает проблема если нет интернета ,нет рекомендуемой суммы. 
2) Перешел на запись каждого чека после оплаты через API фронта себе в БД. Но возникают случае когда при сбоях сумма ко мне не записывается. И рекомендуемая сумма не корректна. 

Теперь возникает вопрос. Можно ли из api вытянуть значение SalesCash из  БД events.sdf  таблицы CloseSessionEvents ?

**Comment by CLTanuki** [comment]
@Kamaew , работать с iiko напрямую через БД идея крайне неопрятная. Можно сделать плагин, в котором вы сможете отслеживать закрытые заказы и складывать в кэш (вами заботливо написанный) суммы.

**Comment by Kamaew** [comment]
Как написано в пункте 2 я так и делаю. но в этом тоже случаются ошибки. 
Я и хотел узнать может есть определенный объект в api который бы мне просто отдал эту цифру. а я тут велосипеды пишу

**Comment by ierof** [comment]
Нет, к iikoFront API нет канала к данным внутреннего пользования из кэша.

**Comment by Kamaew** [comment]
Спасибо. Жаль
