### ISSUE TITLE
iiko front 7.9.7013 Shadow orders

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#390]
Если доставочный заказ вернуть из статуса "отправлен", то создается новый заказ с новым id, а старый уходит в тень его не видно  в интерфейсе в отличии от нового, для чего это и как с этим работать?

**Comment by vcpp** [comment]
Это касается не только доставок, но любых заказов. Если заказ оплатить и вернуть (сторнировать), исходный заказ помечается как удалённый, скрывается с UI, вместо него создаётся новый заказ. У вас, вероятно, настроена оплата заказа при отправке доставки, поэтому при отмене отправки выполняется сторнирование и пересоздание. Если настроить оплату при закрытии доставки, то при отправке оплаты не будет, соответственно, отмена отправки не будет приводить к пересозданию заказа.

Для чего это — хороший вопрос, но это не про API, это общий подход. Старый заказ хранится для истории, для отчётов, изменения в новом заказе не могут изменить событие в прошлом.
Как с этим работать — созданный при сторнировании заказ ссылается на своего предшественника через [`StornedOrderId`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_StornedOrderId.htm).

Если у вас есть конкретная проблема или не получается реализовать какой-то сценарий, сформулируйте вопрос поточнее.
