### ISSUE TITLE
Метод CreateBanquet игнорирует аргумент externalId

### ISSUE THREAD

**Issue by zabei** [iiko/front.api.sdk#392]
Не удается создать банкет с заданным `externalId`. 
Банкет создается с пустым Guid (00000000-0000-0000-0000-000000000000), несмотря на передачу конкретного Guid в качестве аргумента.

`reserve = editSession.CreateBanquet(posReserve.timeFrom, client, reserveTables, externalId: newGuid);`

В логах мы видим следующее:

> [2022-08-23 08:48:58,209]  INFO [11] - NewGuid: 93b1db86-bb34-491c-99d6-ff1049c3719d
> [2022-08-23 08:48:58,646]  INFO [11] - SavedReserve.externalGuid: 00000000-0000-0000-0000-000000000000

если заменить метод `CreateBanquet` на `CreateReserve` с теми же аргументами - все работает и бронь создается с указанным `externalId`

Версия SDK - 7.9.6015

**Comment by vcpp** [comment]
Это баг. Поправим в ближайшем релизе (8.2) для всех поддерживаемых версий API.

> если заменить метод `CreateBanquet` на `CreateReserve` с теми же аргументами - все работает и бронь создается с указанным `externalId`

Да, и перегрузка [`CreateBanquet`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_CreateBanquet.htm), принимающая заказ, тоже работает корректно. Если для вас допустимо создавать банкет сразу с заказом, в качестве временного решения можете попробовать сначала создать заказ, а потом превратить его в банкетный.

**Comment by Ivannumberone** [comment]
> 

Добрый день. Описанная вами проблема будет решена в версии 8.2, для всех версий API
