### ISSUE TITLE
Сбой обработчика события PluginContext.Notifications.OrderChanged.

### ISSUE THREAD

**Issue by kolan72** [iiko/front.api.sdk#394]
Добрый день,
В своем плагине мы используем подписку на событие `PluginContext.Notifications.OrderChanged` для отправки закрытого заказа в нашу систему лояльности. В теле функции-обработчика ее выполнение фиксируется в логе.
Однако время от времени данный обработчик "слетает" - мы не видим его работу в логе, соответственно заказы в нашу систему лояльности не поступают. При том, что непосредственно предшествующий ему обработчик события `BeforeOrderBill` работает исправно. 
Судя по логам,  сбой обработчика `PluginContext.Notifications.OrderChanged` может быть связан с закрытием смены - по крайней мере по времени.
Среди наших предположений насчет причин такого сбоя:

- закрытие смены, как уже было указано;
- влияние параллельно работающих плагинов;
- не(корректно) обработанная ошибка  в теле функции-обработчика;

Хотелось бы узнать насколько реалистичны наши предположения. 
И еще - насколько эффективным может быть process kill/перезапуск всего iikoFront на событие закрытия смены `CafeSessionClosing` как способ гарантированно восстановить сбойный обработчик?

**Comment by igorpooh1978** [comment]
Доброе утро.
Вы посмотрите в error.log  возможно вы там найдете источник вашей проблемы

**Comment by vcpp** [comment]
Обработчик `OrderChanged` перестаёт вызываться, если он однажды сгенерировал исключение. Инфомацию об этом исключении можно найти в _api.log_. Пример лога есть в #377, ищите строку вида `Exception in “XXX” plugin's OnNext handler for notification “OrderChanged”`.

> Хотелось бы узнать насколько реалистичны наши предположения.

В большинстве случаев, причина в том, что обработчик сгенерировал исключение, хотя, конечно, нельзя исключать баги и в API, и в .NET. Дабы не гадать, посмотрите в лог.

> И еще - насколько эффективным может быть process kill/перезапуск всего iikoFront на событие закрытия смены CafeSessionClosing как способ гарантированно восстановить сбойный обработчик?

Надеюсь, с помощью информации из лога нам удастся исправить ошибку и не придётся никого убивать/перезапускать. Если не будет получаться, пишите, вместе найдём и устраним причину. Зачем думать о костылях, пока не исчерпаны возможности локализовать и исправить ошибку? :-)

Даже если хочется перезапустить программу после сбоя, достаточно перезапустить отдельно взятый плагин, не останавливая работу iikoFront и других плагинов. Подробнее [тут](https://iiko.github.io/front.api.doc/2018/08/20/restart-crashed-plugins.html).

**Comment by kolan72** [comment]
Спасибо за ответы, будем изучать логи...
