### ISSUE TITLE
Как сделать вывод QR кода на экран оплаты?

### ISSUE THREAD

**Issue by afinderfall** [iiko/front.api.sdk#395]
Есть задача по бизнесу, 
1. Формирование QR кода и вывод его на экран оплаты
2. Далее, отправка запроса во внешний сервис.

Я использую 7 версию iiko.front.api. 

Все что я нашел у viewManager с пристакой Show, никак не подходит под такое решение. Ничего из доступных варинатов не может выводить хотя img. 

Можете ли подсказать, как можно такое реализовать?

**Comment by afinderfall** [comment]
![image](https://user-images.githubusercontent.com/33827989/188309677-6904b8e6-1787-41a2-89ec-3d13ccca005b.png)
вывод QR кода, должен быть на этой странице

**Comment by igorpooh1978** [comment]
https://github.com/iiko/front.api.sdk/issues/10

**Comment by vcpp** [comment]
Увы, пока придётся рисовать окно самому и показывать его поверх окна iikoFront по ссылке от коллеги из предыдущего комментария или из [отсюда](https://iiko.github.io/front.api.doc/v6/ru/CustomWindows.html).

Мы понимаем, что это влечёт кучу неудобств, что самодельное окно может выглядеть инородно, без поддержки цветовых схем и прочего, но ближайший приоритет — базовые диалоговые окна.
