### ISSUE TITLE
Как подписаться под события?

### ISSUE THREAD

**Issue by afinderfall** [iiko/front.api.sdk#396]
Нужно в рамках бизнес задачи, вызывать помимо внутренних IIKO реализаций, еще и кастомные реализации.
Использую версию iiko.front.api 7. 

Речь идет об функциях
1. Печать Х-отчета 
2. Внести деньги
3. Изъять деньги

Речь идет о функциях на этой странице IIKO
![image](https://user-images.githubusercontent.com/33827989/188309831-37314454-a0e8-4f4b-8af3-f665e5229be9.png)

При вызове каждой из них, я должен так же добавить туда свою кастомную логику (вызовы во внешний сервис).

**Comment by igorpooh1978** [comment]
https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor.html
