### ISSUE TITLE
Внести в заказ внешние данные, полученные при закрытии заказа

### ISSUE THREAD

**Issue by D1splaced** [iiko/front.api.sdk#397]
Добрый день!
При написании плагина для интеграции с внешней системой лояльности возник вопрос.

API системы лояльности работает следующим образом:
Сначала в эту систему отправляется запрос с итоговыми данными по заказу (список блюд, общая стоимость, сколько гость списывает бонусов и т.д.) -  в системе на счету замораживается указанное количество бонусов, рассчитывается, сколько бонусов будет начислено гостю по результату, в ответ приходит код для подтверждения/отмены закрытия заказа.
Далее нужно отправить второй запрос - на подтверждение/отмену закрытия заказа с указанием этого кода. При подтверждении заказ появляется в системе лояльности как успешно завершённый. В ответ приходит ID заказа, который нужно будет использовать при возврате заказа, если таковой понадобится.

Первый запрос я отправляю через интерфейс IExternalPaymentProcessor через метод Pay(), тут проблем нет.
Второй запрос я отправляю через интерфейс IChequeTaskProcessor через метод AfterDoCheckAction(), потому что прежде чем отправлять подтверждение закрытия заказа, я хочу убедиться, что он действительно закрылся. И вот тут возникает сложность. Я хотел бы сохранить информацию об ID заказа (который может понадобиться для возврата) в сам заказ. Но в методы интерфейса IChequeTaskProcessor не передаются экземпляры IOperationService. Если я использую PluginContext.Operations, то получаю исключение Resto.Front.Api.Exceptions.EntityAlreadyInUseException. То же самое исключение я получаю, если использую PluginContext.Operations, подписавшись на событие изменения (закрытия) заказа.
Есть ли какие-то рекомендации, как мне поступить?

**Comment by vcpp** [comment]
> Второй запрос я отправляю через интерфейс IChequeTaskProcessor через метод AfterDoCheckAction(), потому что прежде чем отправлять подтверждение закрытия заказа, я хочу убедиться, что он действительно закрылся.

Ближайшая точка расширения с возможностью редактировать заказ — это [`BeforeDoCheque`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeDoCheque.htm), обработчик этого уведомления вызывается после проведения оплат, но до печати чека. После печати чека, увы, пока нет точек расширения с возможностью редактировать заказ, разве что подождать, пока процесс оплаты полностью завершится и заказ разблокируется. На практике «подождать» означает в цикле пытаться записать данные в заказ, пока не получится, делая небольшие паузы между попытками. Не слишком изящно, но, пожалуй, самое простое.

Альтернатива — собственное хранилище. Можете хранить маппинг внутренних id на внешние в папке `PluginContext.Integration.GetDataStorageDirectoryPath()`, благо, возврат заказа можно делать только на той же кассе. Это муторный вариант — собственное хранилище надо как-то очищать по мере закрытия кассовых смен и удаления заказов, зато никто не заблокирует доступ, можно записывать в свои файлы в любой момент.

Ну а на будущее подумаем о добавлении симметричного уведомления `AfterDoCheque`, либо возможности удобно дождаться разблокировки заказа.
