### ISSUE TITLE
Какие итемы скрывает метод CancelNewDeliveryAndHideItemsFromOlap

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#398]
До отмены заказа приходится удалить отпечатанные позиии и оплаты после провожу метод CancelNewDeliveryAndHideItemsFromOlap так же пробовал CancelNewDelivery но не вижу разницы, в отчетах заказ с блюдами есть в любом случае. Что в итоге скрывает CancelNewDeliveryAndHideItemsFromOlap ?

**Comment by vcpp** [comment]
Метод `CancelNewDelivery` отменяет новую доставку, при этом в зависимости от некоторых условий, связанных с требованиями фискальной системы той или иной страны, удаление заказа может быть выполнено через удаление всех блюд и нулевую оплату. Для оплаты, даже нулевой, требуется наличие открытой кассовой смены, далее этот заказ будет виден в OLAP-отчётах, информация о нём может быть отправлена в фискальную систему. Используйте этот метод для отмены доставки по причинам, связанным с предметной областью.

Метод `CancelNewDeliveryAndHideItemsFromOlap` отменяет новую доставку, удаляя заказ «бесследно». Поскольку API не позволяет узнать итоговую сумму заказа, не создавая заказ, иногда приходится создавать «пробный» заказ и, если суммы не сходятся с ожидаемыми, удалять его. Чтобы не путать подобные удаления с обычными и не искажать статистику, сделан отдельный метод. Используйте этот метод только для отмены по техническим причинам.
