### ISSUE TITLE
Диалоговое окно для ввода денежной суммы

### ISSUE THREAD

**Issue by D1splaced** [iiko/front.api.sdk#399]
Добрый день.
Хотелось бы узнать, возможно ли в будущем добавление специализированного диалогового окна для ввода денежных сумм как в iikoCard5?

![iikocard5](https://user-images.githubusercontent.com/79542489/188599527-45c2201a-e7e6-4575-854b-b554bba64f95.png)

В рамках интеграции с внешней системой лояльности мне нужно сделать, чтобы кассир мог ввести через диалоговое окно определённую сумму денег и отправить запрос с этой суммой.  Я использую метод ShowInputDialog, и в принципе его функционала хватает, но есть недостатки.
1. Невозможность ввода дробных сумм (конкретно в моём случае все числа целые, так что это не проблема, но в других случаях может быть по-другому).
2.  Нет кнопки "точная сумма" (по большей части компенсируется тем, что можно поставить значение по умолчанию равным точной сумме). Также нет ограничения на максимальное значение. Мелочь, но с такой опцией было бы чуть удобнее.
3. Нельзя выбрать нулевое значение. Т.е. можно сделать, чтобы нажатие на отмену обрабатывалось как ввод нулевого значения, но во-первых, это не совсем интуитивно понятно для кассира, и во-вторых, возможна ситуация, когда ноль и отмену нужно будет обрабатывать по-разному.

**Comment by vcpp** [comment]
Duplicates #228.

Запланирована доработка, внутренний номер RMS-52943.

**Comment by aitkkia** [comment]
> Duplicates #228.
> 
> Запланирована доработка, внутренний номер RMS-52943.
Добрый день.
В итоге доработка выполнена? 
На будущее, как можно узнавать статус задач "RMS-52943"?
