### ISSUE TITLE
Получение товаров из чека

### ISSUE THREAD

**Issue by bosh2000** [iiko/front.api.sdk#4]
Для сбора статистики по покупкам, хотим собирать все продукты которые проходят через покупки  нашей бонусной системы. 

Вот пример кода.
делаю по примеру из sdk

            var order = PluginContext.Operations.GetOrders().Last();
            PluginContext.Operations.PrintOrderItems(PluginContext.Operations.GetCredentials(), order,
                new List<IOrderRootItem> { order.Items.Last() });

идея понятна. Вот мой код.

            var orderTest = GetOrderSafe(orderId);
            var orderItems = orderTest.Items;
            foreach (var orderItem in orderItems)
            {
                Product=PluginContext.Operations.TryGetProductById(orderItem.Id);
                ProductGroup=PluginContext.Operations.TryGetProductGroupById(orderItem.Id);
            }

но возвращается пустые значения. Что я делаю не так?

**Comment by bosh2000** [comment]
Так как ТП отправляет все сюда, а потом отвечает на почту, пишу тут ответ , он работает

public Order ToSendingOrder(Guid id)
        {
            try
            {
            IOrder order = PluginContext.Operations.GetOrderById(id);
                Order result = new Order();
                result.id = order.Id;
                result.number = order.Number;
                result.status = order.Status.ToString();
                result.total_sum = order.ResultSum;
                result.products = GetOrderProducts(order.Items);
                return result;
            }
            catch (Exception ex)
            {
                PluginContext.Log.Error(ex.ToString());
                return null;
            }
        }

        private List<OrderItem> GetOrderProducts(IReadOnlyList<IOrderRootItem> items)
        {
            var result = new List<OrderItem>();
            foreach (var line in items)
            {
                if (!(line is IOrderProductItem)) continue;
                var product = line as IOrderProductItem;
                var item = new OrderItem();
                item.id = product.Product.Id;
                item.name = product.Product.Name;
                item.price = product.Price;
                item.amount = product.Amount;
                item.total = product.ResultSum;
                result.Add(item);
            }

            return result;
        }

**Comment by ierof** [comment]
> Что я делаю не так?

вы передаете id объектов типа [`IOrderRootItem`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Orders_IOrderRootItem.htm) в методы получения объектов других типов. К примеру [`IOperationService.TryGetProductById`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_TryGetProductById.htm) возвращает [`IProduct`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Assortment_IProduct.htm).
Посмотрите, какие есть наследники у `IOrderRootItem` и какие у них есть свойства.
