### ISSUE TITLE
Плагин внешней оплаты, возникает исключение "тип не помечен как сериализуемый"

### ISSUE THREAD

**Issue by D1splaced** [iiko/front.api.sdk#403]
Добрый день!
Есть плагин внешней оплаты, сделанный на основе вашего плагина SamplePaymentPlugin.
На фронте версии 8.0.6 он работает нормально.
При запуске плагина на фронте версии 7.9.7 при использовании метода GetActivePaymentTypes(this) выдаётся исключение: 

> System.Runtime.Serialization.SerializationException: Тип "Resto.Front.Api.SamosalePlugin.ExternalPaymentProcessorSample" в сборке "Resto.Front.Api.SamosalePlugin, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" не помечен как сериализуемый.

Добавление атрибута [Serializable] классу ExternalPaymentProcessorSample на ситуацию не повлияло.
Прилагаю логи с кассы
[логи.zip](https://github.com/iiko/front.api.sdk/files/9682818/default.zip)
С чем может быть связана проблема?

**Comment by vcpp** [comment]
Это был баг, существовавший в V7Preview7 и V7 в интервале [7.7, 8.0). Используемая вами версия 7.9.7 входит в интервал, и там вы наблюдаете баг. В 8.0.6 мы этот баг уже поправили.

В качестве временного решения для версий ниже 8.0 можете унаследовать ваш класс от `MarshalByRefObject` и переопределить метод `InitializeLifetimeService` , как это требовалось делать в V6 ([пример](https://github.com/iiko/front.api.sdk/blob/master/sample/v6/Resto.Front.Api.SamplePaymentPlugin/ExternalPaymentProcessorSample.cs)).

**Comment by D1splaced** [comment]
Сделал, как вы сказали, проверил, что плагин корректно работает и с версией 7.9.7, и с версией 8.0.6.

Хотелось бы уточнить, чревато ли чем-то предложенное вами решение. То есть если клиент в будущем обновится с версии 7.9.7 на более новую, то необходимо ли будет заменить плагин, или и так всё будет работать?

**Comment by vcpp** [comment]
> если клиент в будущем обновится с версии 7.9.7 на более новую, то необходимо ли будет заменить плагин, или и так всё будет работать?

Можно ничего не делать, будет работать и так.

Недостатки есть, но они не критичны:
* немного лишнего кода
* потенциальная утечка памяти — переопределение `InitializeLifetimeService` позволяет задать неограниченное время жизни объекта, что приемлемо для плагина, который регистрирует платёжную систему (`RegisterPaymentSystem`) однократно при запуске и либо вообще не отменяет регистрацию, либо отменяет (`Dispose`) при выключении, но если вы вдруг зачем-то захотите многократно пересоздавать экземпляры `ExternalPaymentProcessorSample`, надо будет для ставших ненужными экземпляров вызывать `RemotingServices.Disconnect`.
