### ISSUE TITLE
Возможность менять текст на кнопках в окнах IViewManager

### ISSUE THREAD

**Issue by D1splaced** [iiko/front.api.sdk#404]
Добрый день.
Хотелось бы узнать, возможно ли в будущем добавление функционала для изменения стандартного текста на кнопках в окнах, вызываемых методами `IViewManager`?
 В своём плагине я довольно активно использую `ShowChooserPopup`, и по логике работы плагина кнопка Отмена должна была бы называться Закрыть или Продолжить, т.к. при нажатии на неё происходит закрытие окна с обработкой полученных ранее данных. Слово "Отмена" вызывает у конечного пользователя некоторое недоумение и мысли, что что-то может отмениться.
Разумеется, на функционал это никак не влияет, но так было бы чуть удобнее. Аналогично, возможность выбора текста кнопок могла бы быть полезна в диалоговых окнах с одним/двумя/тремя ответами.

**Comment by vcpp** [comment]
Конечно, сделать переопределение текста на кнопках можно. Когда-нибудь сделаем, внутренний номер задачи: RMS-53956.

Для `ShowChooserPopup` в качестве временного решения к списку вариантов можно добавить выбранный по умолчанию вариант для продолжения с ранее полученными данными, тогда по нажатию на кнопку «Отмена» можно будет по-честному отменять операцию.

**Comment by mbagritsevich** [comment]
Сделано
https://iiko.github.io/front.api.doc/2023/02/20/dialog-buttons.html
