### ISSUE TITLE
ChangeOrderExternalNumber работает НЕ как ожидается

### ISSUE THREAD

**Issue by hamaronooo** [iiko/front.api.sdk#405]
_Версия IIKO FRONT: 8.1.7008.0
Пакет в плагине: Resto.Front.Api.V8Preview1 (8.0.6.6017-alpha)_

В новой, 8ой версии API есть способ утсановить для заказа поле ExternalNumber.
На сколько я понимаю, оно должно в итоге оказаться на сервере - в базе данных.

С помощью плагина пытался установить это поле несколькими способами.
Однако в БД оно так и не появилось.
**Прошу подсказать, что я делаю не так?**

1)	В PaymentProcessor с внедренным IOperationService
![image](https://user-images.githubusercontent.com/61544995/194266735-0c9f34c8-ac2e-4409-a419-689b553c8ccf.png)

2)	В PaymentProcessor с созданным
![image](https://user-images.githubusercontent.com/61544995/194266777-c4f862c8-567a-4ad4-9d36-e71fbeb76d84.png)

3)	В IFrontPlugin (исключение не генерируется, но в базу чейна данные не попадают)
![image](https://user-images.githubusercontent.com/61544995/194266911-a8d745b3-f98c-4d6f-ae3d-487254fe68d4.png)

БД: 
![image](https://user-images.githubusercontent.com/61544995/194266537-76bafe11-6ef9-4ab5-a79f-336f403e4b78.png)

**Comment by vcpp** [comment]
К сожалению, сейчас на сервер отправляются лишь данные, которые присутствовали в заказе до начала оплаты. Информация, записанная в заказ во время оплаты и после оплаты, доступна только локально и на сервер не отправляется. Поправим в одной из будущих версий. Если вы знаете номер заказа во внешней системе заранее, попробуйте задать его до начала оплаты.

Duplicates #380.
Внутренний номер: RMS-53884.

**Comment by mbagritsevich** [comment]
Поправлено в v8. Теперь изменить нужные данные можно подписавшись на BeforeDoCheque.
