### ISSUE TITLE
Добавление платежной системы в iikoOffice. 

### ISSUE THREAD

**Issue by mahab-22** [iiko/front.api.sdk#408]
Добрый день! Стоит задача сделать плагин оплаты через внешнюю платежную систему Paykeeper. Получили лицензию iikoRMS на 60 дней. По инструкции установил и настроил iikoOffice, iikoFront. Все запустилось , работает корректно. Скачал front.api.sdk/sample)/v7/Resto.Front.Api.SamplePaymentPlugin, добавил System.Windows.Forms messagebox туда, где проиcходит успешное добавление платежной системы:
 PluginContext.Log.Info($"Payment system '{paymentSystem.PaymentSystemKey}': '{paymentSystem.PaymentSystemName}' was successfully registered on server.");
            MessageBox.Show("ОК!!", $"{paymentSystem.PaymentSystemKey}", MessageBoxButtons.OK, MessageBoxIcon.Information, MessageBoxDefaultButton.Button1, MessageBoxOptions.DefaultDesktopOnly);
            Скомпилировал с помощью MVS 2022, установил в папку plugins. Запустил  iikoOffice и  iikoFron. Получил сообщение "ок" об успешном добавлении платежной системы, но в  iikoOffice платежная система не отображается. Скажите, пожалуйста, что и как проверить? Почему не происходит добавление ПС?

P.S. Прошу дать развернутый ответ, т.к. опыта работы в C# и MVS нет (работаю в другом направлении).

**Comment by vcpp** [comment]
> в iikoOffice платежная система не отображается

Где именно вы её ищете?
После регистрации платёжной системы вам нужно вручную настроить внешний тип оплаты по инструкции [для пользователей](https://ru.iiko.help/articles/iikooffice-8-2/topic-94) или [для разработчиков плагинов](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html), в выпадающем списке «Безналичный тип» вы должны увидеть свою платёжную систему.

**Comment by mahab-22** [comment]
Добрый день. Спасибо за ответ. Некоторые слова из инструкции ввели в заблуждение разобрался, запустил.
