### ISSUE TITLE
Получить уникальный id для каждой торговой точки через iikoFront. Интеграция с LoyaltyPlant

### ISSUE THREAD

**Issue by annajimm** [iiko/front.api.sdk#409]
Здравствуйте, это команда разработки LoyaltyPlant.

Наше решение представляет собой мобильное приложение с программой лояльности. 
Возник вопрос по уникальным id для торговых точек в нашем решении для программы лояльности для ресторанного бизнеса (instore plagin iiko, работает через iikoFront).
У нашего общего партнера GreenBox возникла проблема с уникальными id для каждой точки. В качестве id точки мы сейчас используем id RMS, но некоторые общие партнеры (в т.ч. GreenBox) используют один RMS для сети ресторанов и в данный момент эту проблему приходится решать в ручном режиме. Ранее мы предположили, что в качестве уникального id для каждой торговой точки мы можем использовать составной id, например вида idRMS_idGroup. Подскажите пожалуйста, будет ли это корректно и как получить такой id через iikoFront?

**Comment by ierof** [comment]
_"Торговая точка"_ — что имеется ввиду? Ресторан, в котором несколько касс? POS-терминал?
Если первое, то это что-нибудь из объекта [IRestaurant](https://iiko.github.io/front.api.sdk/v8/html/Properties_T_Resto_Front_Api_Data_Organization_IRestaurant.htm), получаемого из [IOperationService.GetHostRestaurant](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_GetHostRestaurant.htm) 
Если второе, то на кассовой точке это что-нибудь из объекта [IPointOfSale](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Organization_IPointOfSale.htm) получаемого из  [`IOperationService.GetHostTerminalPointsOfSale`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_GetHostTerminalPointsOfSale.htm)
