### ISSUE TITLE
Добавление email для отправки чеков в runtime. Интеграция с LoyaltyPlant.

### ISSUE THREAD

**Issue by annajimm** [iiko/front.api.sdk#410]
Добрый день!
Ищем способ добавить имейл гостя для отправки ему чека о заказе, вместо печати.

Наше решение представляет собой мобильное приложение с программой лояльности. Весь процессинг лояльности происходит на нашей стороне и у нас хранится база клиентов. Мы хотим, чтобы при сканировании qr-кода из нашего приложения email клиента из нашей базы передавался  в систему iiko, чтобы после оплаты заказа со стороны iiko чек отправлялся не на печать, а на почту клиента, которую мы передадим. 

Наш плагин получает имейл в процессе работы (выбор нашего типа оплаты -> сканирование QR кода с телефона гостя -> обмен данными с нашим облаком -> получение имейл гостя в ответе). Т.е. workaround с подпиской на событие перехода на экран оплаты не подходит, т.к. в этот момент данных о госте у нас еще нет. Мы уже обращались к вам с этой [ проблемой](https://github.com/iiko/front.api.sdk/issues/389).

Подскажите пожалуйста, будет ли корректным такой флоу:
1.  Кассир на iiko выбирает наш тип оплаты  
2. Кассир сканирует QR код с телефона гостя 
3. Наш плагин отправляет запрос с QR-кодом в наше облако 
4. В ответ плагину приходит ответ с номером телефона пользователя
5. Плагин вызывает метод [SearchClients](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_SearchClients.htm) с полученным номером телефона
6а. Если клиент находится в системе iiko, то он будет добавлен к заказу
6б. Если клиент не находится в системе iiko, то он будет создан в системе iiko и добавлен к заказу
7. После оплаты чек будет отправлен на email клиента

Нужно ли добавить еще какие-то методы для того, чтобы  добавить гостя к заказу и отправить чек ему на электронную почту? Как это правильно сделать?

Версия API - 7, если получится и для 6 сделать - будет отлично.

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/2019/11/25/cheque-info-on-navigating-to-payment.html
