### ISSUE TITLE
Как узнать в каком режиме работает iikoFront средствами SDK7? (agent/normal)

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#413]

**Comment by vcpp** [comment]
В обработчиках, где предполагается показ окон, плагин получает ненулевое значение типа `IViewManager`. Но если там `null`, это не всегда означает работу в режиме службы, это может быть просто фоновая операция, не связанная с UI-контекстом.
Напрямую через API узнать режим работы пока невозможно. В качестве временного решения можно проверить список процессов — наличие *iikoFront.Net.exe* косвенно указывает на работу в обычном UI-режиме.

Чтобы лучше понимать вашу потребность, расскажите, в каком сценарии вам важно знать режим работы приложения?

**Comment by Keeplod** [comment]
Это необходимо когда реализуется плагин для всех фронтов, единсвенное что нужно понимать мне как разработчику, что некоторые функции нужно будет отключать так как интерфейса у службы нету .

**Comment by vcpp** [comment]
> некоторые функции нужно будет отключать так как интерфейса у службы нету

Если ваше взаимодействие с пользователем ограничивается использованием `IViewManager`, то достаточно проверить данный объект на `null`. А вот если вы рисуете что-то своё, то нужны будут подробности, потому что «интерфейса нет» не только у службы, но и у десктопного приложения в рамках выполнения фоновой операции, инициированной другим плагином или соседним терминалом.

Представьте, стоит терминал с заблокированным экраном, рядом с ним никого нет, а в фоне он выполняет какую-то операцию, при этом приложение формально в оконном режиме, не служба, но и показывать что-либо на экране не имеет смысла, никто не увидит. Ещё хуже, если пользователь на терминале выполняет одну операцию, а в фоне в это же время выполняется другая, при этом пользователь даже не будет знать, что параллельно с его действиями в фоне что-то сработало по таймеру, по команде какого-то из плагинов или дистанционно с соседнего терминала, и попытки показывать пользователю что-то, связанное с фоновой операцией, будут запутывать и мешать.

Дайте знать, если надумаете поделиться сценарием, в котором вам важно знать режим работы приложения, это позволит нам спроектировать более изящную поддержку этого сценария в API, нежели проверка списка процессов.
