### ISSUE TITLE
Печать на принтера из списка оборудования

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#414]
Добрый день. 
в api есть метод 
`bool Print([NotNull] IPrinterRef printer, [NotNull] Document document, bool checkIsCompleted = false);`
Есть возможные 5 IPrinterRef  
```

        IPrinterRef TryGetBillPrinter([CanBeNull] IRestaurantSection section = null, bool checkIsConfigured = false);
        IPrinterRef TryGetDocumentPrinter([CanBeNull] IRestaurantSection section = null, bool checkIsConfigured = false);
        IPrinterRef TryGetStickerPrinter([CanBeNull] IRestaurantSection section = null, bool checkIsConfigured = false);
        IPrinterRef TryGetReceiptChequePrinter(bool checkIsConfigured = false);
        IPrinterRef GetReportPrinter();
```

Есть задача имея 4 цеха Гор.цех, Хол.цех, Мангал, Пекарня
Печатать на них. 
Было бы удобно иметь возможность получать добавленные принтера из списка оборудования в виде IPrinterRef   и слать на любой из них нужный мне чек

**Comment by vcpp** [comment]
А как вы будете определять, какой принтер к какому цеху относится?

Может, удобнее будет добавить метод `IPrinterRef TryGetDishPrinter([CanBeNull] IRestaurantSection section = null)`? Из коробки получите маппинг цеха на принтер, будет работать дублирующая печать, если настроен дублирующий принтер блюд, а также будет печать на резервный принтер, если основной неисправен.

**Comment by Kamaew** [comment]
Ну по плану было получать списки принтеров и хранить что к чему привязано но ваш вариант тоже приемлем

**Comment by Kamaew** [comment]
Подскажите внутренний номер задачи. и есть ли уже план по версии реализации ?

**Comment by ierof** [comment]
Фича вошла в API V8.
[Добавлена возможность выбора принтера блюд]: (https://iiko.github.io/front.api.doc/2023/01/26/dish-printer.html)
Релиз с зафиксированным Preview выйдет ориентировочно в апреле. Для тестовых целей и разработки можно запросить текущий двух-недельный релиз и состаться на библиотеку, а не на nuget
