### ISSUE TITLE
Полная оплата заказа с доставкой

### ISSUE THREAD

**Issue by mahab-22** [iiko/front.api.sdk#415]
Добрый день!
Есть следующая задача. У платежной системы Paykeeper есть API для управления счетами - это создание, отправка, изменение, удаление. Необходимо сделать плагин, который посредством этого API будет автоматически управлять счетами на заказы с доставкой. Для создания я пытаюсь использовать подписку PluginContext.Notifications.DeliveryOrderChanged.Subscribe, которая дает мне изменение статуса заказа с доставкой. А вот по полной оплате заказа не совсем понятно,  лучше использовать статус closed, исходя из того, что закрытый заказ не бывает неоплаченный, или есть какая-то возможность получить событие полной либо завершающей оплаты?
Вот [здесь](https://github.com/iiko/front.api.sdk/issues/7#issuecomment-455253500) прочитал, что оплата может быть бонусами, со 100% скидкой, но все-таки закрывать счет на оплату по завершению заказа, может быть, не очень правильно?
Коллеги я web программист, только знакомлюсь с MVS C#, поэтому прошу поподробнее. Как поступили бы вы? Спасибо!

**Comment by vcpp** [comment]
Всё зависит от требований. Попробуйте расписать возможные сценарии и проверить, устроит ли вас отслеживание перехода в статус `Closed`. Обратите внимание, что есть отдельно статус заказа ([`OrderStatus`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_OrderStatus.htm)) и статус доставки ([`DeliveryStatus`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Brd_DeliveryStatus.htm)). Если настроена оплата до отправки курьера, то заказ может быть в статусе `Closed` (оплачен), пока сама доставка будет `OnWay` (в пути).
