### ISSUE TITLE
Распределение лицензий по кассам

### ISSUE THREAD

**Issue by Lizzzzzard** [iiko/front.api.sdk#418]
Есть лицензированный плагин и ввиду необходимости совпадения списков установленных плагинов на главной и всех ведомых кассах, этот плагин был установлен на все кассы. Клиент имеет одну лицензию, в итоге получаем ожидаемый результат, что на остальных трех кассах выходит ошибка лицензирования, а лицензию занимает в основном гк, так как она запускается первая, а клиент хочет использовать плагин на ведомом терминале.
Использовать данную конфигурацию техническая поддержка строго запрещает https://pyrus.com/t#id149584413
![image](https://user-images.githubusercontent.com/74863190/209918128-3187554d-40d7-4a91-b8d9-2076376c19ed.png)
Если альтернативные способы делать это, возможно через sdk?

**Comment by vcpp** [comment]
>  ввиду необходимости совпадения списков установленных плагинов на главной и всех ведомых кассах

Такой необходимости нет. Терминалы могут иметь разные наборы API-плагинов. Если вы устанавливаете плагин вручную, вы можете выборочно установить его на нужные терминалы.

> лицензию занимает в основном гк, так как она запускается первая

Если плагин при запуске может определить, что на данном терминале он не нужен, он может добровольно выключиться с помощью [`PluginContext.Shutdown`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_PluginContext_Shutdown.htm), чтобы освободить лицензию для другого терминала.

> Использовать данную конфигурацию техническая поддержка строго запрещает https://pyrus.com/t#id149584413

Правильно запрещает. Настройка `ignoreFrontVersionCheck` не только вредна, но в вашем случае ещё и бесполезна, так как она не влияет на плагины, работающие через Front API.
