### ISSUE TITLE
Управление номерами заказов

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#419]
Есть ресторан, где установленно 2 кассы и 1 Экран очереди (статус заказов для гостей)
Если работают 2 кассы, они генерирую одни и теже номера заказов и на экране очереди получается беспорядок ввиде продублированных заказов:
заказ 1 с кассы 1
заказ 1 с кассы 2
заказ 2 с кассы 1
заказ 2 с кассы 2
Можно ли управлять номерами? самым простым решением я вижу сделать на первой кассе четные значения на второй нечётные... но как это реализовать?

**Comment by vcpp** [comment]
Нет, через API нельзя задавать номера для создаваемых на кассе заказов.

Могу предложить два варианта:
* Объединить обе кассы в одну [группу](https://ru.iiko.help/articles/iikooffice-8-2/topic-265) и одну из касс назначить главной («Главный терминал»), тогда обе кассы будут использовать единую сквозную нумерацию заказов. Прежде чем менять настройки, надо выяснить, почему изначально настроили независимую работу касс. Если кассы начнут работать совместно, синхронизироваться будут не только номера заказов, но и сами заказы (достаточно будет запускать плагин на любой из касс в режиме [`IsSingleInstance`](https://iiko.github.io/front.api.doc/directories.html)), а также другие данные (например, личные смены). Однако, при выключении главной кассы (главного терминала) другая касса не сможет работать.
* Использовать внешние номера заказов ([`ChangeOrderExternalNumber`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Editors_IEditSession_ChangeOrderExternalNumber.htm). Эта функция доступна начиная с V8Preview2, можете в качестве номера задавать заказам любые строки длиной до 50 символов, они будут отображаться наряду с основным номером. Эта функция предполагалась для заказов, полученных из внешних систем (через агрегатор, например), и назначать ею суррогатные номера заказам, созданным на кассах самого ресторана несколько избыточно, но если очень хочется, чтобы кассы работали независимо друг от друга и при этом номера их заказов не повторялись, то почему бы и нет.
