### ISSUE TITLE
Внешний фискальный регистратор CashRegisterResult

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#42]
Добрый вечер.

С какой версии iiko в классе CashRegisterResult появилось
Success — true — операция прошла успешно, false — операция не выполнилась или прошла с ошибкой.
Message — текстовое сообщение выполнения команды ФРом. IikoFront выводит данный текст на экран, если операция прошла неуспешно.
ссылка на документацию
https://iiko.github.io/front.api.doc/v6/ru/CashRegisters.html

Мы работаем на 6.3 и подобных переменных не имеем

**Comment by GulnaraBikbova** [comment]
Допущена неточность в документации.

Если плагин возвращает CashRegisterResult - для фронта это будет считаться успешным результатом выполнения команды.
Если плагин кидает исключение - для фронта это означает неуспех. Текст исключения будет отображен на фронте.

**Comment by igorpooh1978** [comment]
Спасибо за разъяснение. Исключение д.б. DeviceException?

**Comment by GulnaraBikbova** [comment]
> Исключение д.б. DeviceException?
Да

**Comment by igorpooh1978** [comment]
Благодарю
