### ISSUE TITLE
Есть ли функционал редактирования стоп-листа у SDKv7+?

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#420]
Сейчас посмотрел по вопросам, более года назад говорили сделают =) заявка была RMS-52142
Требуется для удалённого управления стоп-листом. 
PS Сотрудники которые могли использовать UI IIKOFront, начали злоупотреблять данной функцией и права им порезали...

**Comment by vcpp** [comment]
Увы, эта задача всё ещё в бэклоге.
А можете поделиться сценарием злоупотребления?

Duplicates #159, #266.

**Comment by Keeplod** [comment]
@vcpp Злоупотребление, достаточно простое( 
Повар не хочет готовить то или другое блюдо и ставит в стоп лист из-за чего КЦ не может создать доставочный заказ с данной позицией.

**Comment by andrey-nasonov** [comment]
Добрый день! Начиная с API V8 появилась возможность редактировать стоп-лист, изменения вы можете посмотреть здесь:
http://iiko.github.io/front.api.doc/2023/05/03/stop-list-edit.html
