### ISSUE TITLE
Как получить ICookingPlaceType?

### ISSUE THREAD

**Issue by lampaa** [iiko/front.api.sdk#421]
Не смог из продукта вытянуть это поле, как его можно получить?

**Comment by rengal** [comment]
Сейчас нельзя, но выполняется задача (внутренний номер RMS-54231), где, в частности, будет добавлено свойство типа [ICookingPlaceType](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_ICookingPlaceType.htm) в `IProduct`. Напишу тут после выполнения задачи.

**Comment by lampaa** [comment]
Спасибо, очень жду. Оно будет работать с любым айко, верно же? А есть примерные даты когда будет реализовано, мне надо понимать на что рассчитывать

**Comment by lampaa** [comment]
@rengal есть новости?

**Comment by rengal** [comment]
С любой версией работать не будет, так как нельзя изменить API выпущенных версий. Сейчас в разработке API V8, поэтому задача попадёт в V8 и очередную V8Preview-версию. Подробнее о версионности: https://iiko.github.io/front.api.doc/versioning.html
Задача сейчас в тестировании.

**Comment by lampaa** [comment]
> С любой версией работать не будет, так как нельзя изменить API выпущенных версий. Сейчас в разработке API V8, поэтому задача попадёт в V8 и очередную V8Preview-версию. Подробнее о версионности: https://iiko.github.io/front.api.doc/versioning.html Задача сейчас в тестировании.

Беда, а в V7 может есть вариант это поле как-то вытащить?

**Comment by rengal** [comment]
нет, API V7 уже выпущен и не может быть изменен.

**Comment by lampaa** [comment]
@rengal а если iikoFront на 7 версии, то sdk 8 версии будет работать?

**Comment by vcpp** [comment]
Вы уверены, что хотите именно `ICookingPlaceType` — тип места приготовления? Что вы планируете с ним дальше делать?
На практике обычно интерес представляет непосредственно место приготовления блюда, которое можно взять из [`IOrderCookingItem.Kitchen`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderCookingItem_Kitchen.htm).

**Comment by lampaa** [comment]
@vcpp на тип места приготовления завязано раздельная оплата блюд и алкоголя, соответственно в этом весь смысл)

**Comment by lampaa** [comment]
В общем получилось только список групп получать для блюда, если кто-то тоже этим страдает, то вот:

```C#
var parent = ProductExtensions.TryGetParent(prod.Product);

while (parent != null)
{
    groups.Add(parent.Name);
    parent = ProductGroupExtensions.TryGetParent(parent);
}
```

**Comment by pro100roman24** [comment]
> Вы уверены, что хотите именно `ICookingPlaceType` — тип места приготовления? Что вы планируете с ним дальше делать? На практике обычно интерес представляет непосредственно место приготовления блюда, которое можно взять из [`IOrderCookingItem.Kitchen`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrderCookingItem_Kitchen.htm).


Да, мы тоже столкнулись с такой проблемой, вроде простая вещь, а её нет.
Это очень нужно, для разделения алкоголь/не алкоголь.
Чтобы можно было понять, какое блюдо на какой ФР пойдет ДО разделения заказа на 2.

**Comment by vcpp** [comment]
Начиная с V8 можно будет получить места приготовления: [`IProduct.CookingPlaceType`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Assortment_IProduct_CookingPlaceType.htm).

**Comment by pro100roman24** [comment]
> Начиная с V8 можно будет получить места приготовления: [`IProduct.CookingPlaceType`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Assortment_IProduct_CookingPlaceType.htm).

Отличная новость.
Подскажите, а с какой версии iiko это будет нормально работать?

**Comment by pro100roman24** [comment]
> Начиная с V8 можно будет получить места приготовления: [`IProduct.CookingPlaceType`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Assortment_IProduct_CookingPlaceType.htm).

Отличная новость, спасибо!

**Comment by lampaa** [comment]
@vcpp где взять 8 версию с этим параметром? в Resto.Front.Api.V8Preview7 нет, а больше версий в NuGet нет.

**Comment by vcpp** [comment]
> где взять 8 версию с этим параметром?

До релиза V8 нужно брать SDK, идущий в комплекте с конкретным дистрибутивом, совместимость с другими версиями не гарантируется.
NuGet-пакет будет опубликован после релиза V8, об этом будет заметка [тут](https://iiko.github.io/front.api.doc/changelog.html).
