### ISSUE TITLE
Id заказа отличается от Id заказа созданное через iikoTransport API

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#422]
Похожая проблема как в https://github.com/iiko/front.api.sdk/issues/276 созданный заказ через iikoTransport API `orderId` не совпадает с `orderId` в плагине.
В чем может быть проблема?

**Comment by letolica** [comment]
Цитирую коллег из команды транспорта:

> Сейчас в методах получения информации о заказе в стол есть поле `posOrderId`, это как и есть `orderId` фронтового заказа https://api-ru.iiko.services/#tag/Orders/paths/~1api~11~1order~1by_id/post
