### ISSUE TITLE
Как получить секцию текущего заказа в Resto.Front.Api.V7?

### ISSUE THREAD

**Issue by ilfuser** [iiko/front.api.sdk#425]
Здравствуйте!

Как получить секцию текущего заказа?

Сейчас делаем переход с версии апи 6 на 7-ю и понадобилось добавить проверку на то, в какой секции (зоне) ресторана был сделан заказ.

Секции это, например, бар, кальянная, столики и т.д.

В документации нашли функции для получения секции по Id и списка секций ресторана:
```
PluginContext.Operations.GetRestaurantSectionById
PluginContext.Operations.GetRestaurantSections
PluginContext.Operations.GetTerminalsGroupRestaurantSections
PluginContext.Operations.TryGetRestaurantSectionById
PluginContext.Operations.TryGetSectionSchemaByRestaurantSection
```

А вот как получить конкретную секцию текущего заказа?

Подскажите, пожалуйста, есть ли такой функционал и где он описан в документации?

**Comment by vcpp** [comment]
Текущий открытый на экране редактирования или оплаты заказ получить через [`IScreenWithOrder.Order`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Screens_IScreenWithOrder_Order.htm), вместо `IScreenWithOrder` могут быть `IClosedOrderScreen`, `IOrderEditScreen`, `IOrderPayScreen`, `IDeliveryOrderEditScreen`, `IUnmodifiableDeliveryOrderScreen`. Ну, либо получаете `IOrder` иным удобным вам способом (если не получается — пишите подробнее сценарий, подскажем).

Далее смотрим [`IOrder.Tables`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Orders_IOrder_Tables.htm), там будет список столов, к которым привязан заказ. Обычно там единственный стол, но большие заказы (обычно банкетные) могут быть привязаны сразу ко многим столам, в этом случае отделение (секция) определяется по первому столу в списке, поэтому в любом случае смотрим первый стол: `Order.Tables.First().RestaurantSection`.
