### ISSUE TITLE
Расчет скидки при добавлении гостя в заказ

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#427]
Добрый день, у нас в плагине идет привязка гостя к заказу методом AddClientToOrder.
Гость к заказу привязывается, но не срабатывает скидка по его клубной карте.
К карте привязана простая скидка 10% на заказ например.
Но когда привязываем гостя к заказу через AddClientToOrder скидка не применяется.
Как это можно исправить?
Есть ли какой то метод для "обновления" скидок в заказе?

Понятное дело, что можно сделать в плагине поиск по номеру карты клиента, понять какая ему там положена скидка, и привязать её плагином. Но это не удобно и не универсально.
А если у гостя какие то скидки по iikoCard должны быть? Нам тоже плагином нужно запрашивать в карде эти скидки и самим плаином их назначать? Слишком сложно.

Ведь если вручную, без плагина, привязать гостя к заказу, то фронт автоматом привязывает все возможные скидки, которые положены гостю?
Может есть какая то возможность запустить этот процесс проверки скидок через наш плагин?

**Comment by pro100roman24** [comment]
Не актуально, решили все таки через привязку скидки к заказу отдельно

**Comment by vcpp** [comment]
> если вручную, без плагина, привязать гостя к заказу, то фронт автоматом привязывает все возможные скидки, которые положены гостю?

Нет, фронт лишь предлагает это сделать:
```
Для данного клиента установлена рекомендованная скидка «Название скидки».
Применить скидку гостя Имя_Гостя к заказу?
```
Пользователь может как согласиться, так и отказаться от этого предложения. В случае с плагином такой вопрос задать невозможно, поэтому инициатива на стороне плагина.

Кстати, помимо скидки у клиента также может быть рекомендованная ценовая категория, и её фронт тоже предложит назначить. Плагин это может сделать с помощью [`ChangePriceCategory`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_ChangePriceCategory.htm).

**Comment by pro100roman24** [comment]
Странно, у меня на демостенде при привязки карты к заказу фронт ничего не спрашивает, сразу назначает скидку на заказ. С ценовой категорией то же самое, сразу назначает, не спрашивая ничего
