### ISSUE TITLE
Вес позиции

### ISSUE THREAD

**Issue by IbragimSarakayev** [iiko/front.api.sdk#428]
Добрый день. 
Как можно получить вес продукта в плагине?

**Comment by igorpooh1978** [comment]
product.Amount

**Comment by igorpooh1978** [comment]
http://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Orders_IOrderProductItem.htm
Amount - не оно ?

**Comment by IbragimSarakayev** [comment]
Не, это количество порций

**Comment by vcpp** [comment]
> Не, это количество порций

Это универсальное количество. Для порционных товаров — количество порций, для весовых — вес (в килограммах), для повременных — время (в минутах), и так далее.
Вы лучше расскажите, какую задачу вы решаете и что у вас не получается при использовании `Amount`.

**Comment by IbragimSarakayev** [comment]
> > Не, это количество порций
> 
> Это универсальное количество. Для порционных товаров — количество порций, для весовых — вес (в килограммах), для повременных — время (в минутах), и так далее. Вы лучше расскажите, какую задачу вы решаете и что у вас не получается при использовании `Amount`.

При создании заказа, данные по заказу выгружаются в наш сервис. Сейчас нам требуется данные по весу item-а в заказе, и на основе веса показывать кбжу на 100 гр.

**Comment by IbragimSarakayev** [comment]
Так же как можно получить вес блюда у сущности IProduct?

**Comment by vcpp** [comment]
Ах, вот оно что. То, что вы спрашиваете, называется [*выход готового продукта*](https://ru.iiko.help/articles/iikooffice-8-3/topic-3090). Вес или объём каждой порции блюда могут задаваться непосредственно в карточке блюда, либо вычисляться автоматически из технологической карты. В Front API эта информация недоступна, но её можно получить через Server API.

> Сейчас нам требуется данные по весу item-а в заказе, и на основе веса получать кбжу на 100 гр.

Нормированные на 100 гр. значения пищевой ценности можно получить из через `IProduct`:
* [`FoodValueFat`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_FoodValueFat.htm)
* [`FoodValueProtein`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_FoodValueProtein.htm)
* [`FoodValueCarbohydrate`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_FoodValueCarbohydrate.htm) 
* [`FoodValueCaloricity`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Assortment_IProduct_FoodValueCaloricity.htm).

**Comment by IbragimSarakayev** [comment]
@vcpp спасибо за ответ

**Comment by IbragimSarakayev** [comment]
А кбжу на порцию я могу в Front API получить?

**Comment by VassiliyAn** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/85997773/222343435-4e8de57e-b821-4b1e-a146-e317ce25edb2.png">
Вот здесь показывается вес готового блюда, значит где-то он на айкофронте есть. 

Где его можно получить?

**Comment by vcpp** [comment]
> Вот здесь показывается вес готового блюда, значит где-то он на айкофронте есть.

На скриншоте — действующая технологическая карта блюда. На фронте техкарты не хранятся, они загружаются с сервера по запросу. Вы можете сами загрузить их, используя [Server API](https://ru.iiko.help/articles/#!api-documentations/recipes).

Можно было бы на фронте завести локальный кеш техкарт, чтобы отдавать вес готового блюда через Front API. Тут загвоздка в том, что фронт может работать автономно без связи с сервером, и на момент продажи актуальная техкарта может быть недоступна, а содержимое кеша может быть устаревшим. Потом, когда связь восстановится, сервер выполнит складские операции в соответствии с действовавшими на момент продажи техкартами.

**Comment by vcpp** [comment]
Внутренняя задача на локальный кеш техкарт: RMS-52543.
