### ISSUE TITLE
Внешний фискальный регистратор ChequeTask

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#43]
Добрый вечер,

В классе ChequeTask есть два поля
SettlementAddress - адрес расчета
SettlementPlace - место расчета
Заполняется согласно настройкам ФР «Администрирование» => «Настройки оборудования» => «Настройки ФРа» => «Дополнительная информация»
Однако на основании каких значений или полей я должен принимать решение о перезаписи адреса и места в ФР?
Если при заполнении этих полей, вне зависимости от конфигурации Режима обслуживания курьером, данные подаются в SettlementAddress и SettlementPlace 
![изображение](https://user-images.githubusercontent.com/47010778/59148753-89a8d400-8a15-11e9-95e6-3206e3bb7f05.png)

**Comment by GulnaraBikbova** [comment]
Добрый день, поля SettlementAddress и SettlementPlace рассчитываются на фронте согласно настройкам бэка, что вы приложили. И уже в готовом виде отдается в плагин.

То как эти поля заполняются, завесит от режима обслуживания заказа, доставка это или нет.

У вас какая проблема возникла с этими параметрами?

**Comment by igorpooh1978** [comment]
Если поля заполнены, то они подаются постоянно в Settlement... Вне зависимости от настроек "Адрес и место расчёта". Это так и должно быть?

**Comment by GulnaraBikbova** [comment]
Не совсем поняла. Какие поля заполнены? Что передаются в SettlementAddress и SettlementPlace?

**Comment by igorpooh1978** [comment]
Если у меня заполнены поля "Адрес расчета" и "Место расчёта" в "Режим обслуживания обычный заказ и доставка самовывоз" эти данные подаются в SettlementAddress и SettlementPlace. 
Я хочу понять. Если эти поля заполнены, то в этом случае я должен  подавать данные значения в ФР на печать. Если эти поля пустые, то печатаются данные зашитые в принтер (я имею в виду адрес).

**Comment by GulnaraBikbova** [comment]
Поняла Вас, да все верно.

**Comment by igorpooh1978** [comment]
Добрый вечер.
Могу ли я получить эти значения напрямую из настроек.

**Comment by GulnaraBikbova** [comment]
Добрый день, сейчас нет возможности их считать напрямую из CashRegisterSettings, только в ChequeTask.

**Comment by igorpooh1978** [comment]
Спасибо за разъяснение
