### ISSUE TITLE
Плагин SamplePaymentPlugin не появляется в списке доступных внешних типов оплаты

### ISSUE THREAD

**Issue by tayabuz** [iiko/front.api.sdk#430]
Мною был собран тестовый пример для актуальной версии API.  https://github.com/iiko/front.api.sdk/tree/master/sample/v7/Resto.Front.Api.SamplePaymentPlugin
В PluginLicenseModuleId подставила значение, предоставленное вендором.
В настройках внешнего типа оплаты в iikoOffice не появляется тип тестового примера.
Для сборки использую Microsoft Visual Studio Enterprise 2019 Version 16.11.23.
Плагин лежит в папке: C:\Program Files\iiko\iikoRMS\Front.Net\Plugins\Resto.Front.Api.SamplePaymentPlugin

Проблема в том, что данный плагин не появляется в списке внешних типов оплаты. Виден плагин другого производителя - INPAS DualConnector

**Comment by vcpp** [comment]
Начните с чтения логов (лог самого плагина, затем *api.log*). По текущему описанию можно только гадать, а это неэффективный способ диагностики. Если не будет получаться с чтением логов — давайте их сюда, если их допустимо публиковать. Если в логах есть что-то конфиденциальное, передавайте их через техподдержку.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
