### ISSUE TITLE
Добавление через API  воду с маркировкой

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#431]
Добрый день.  Плагин создает через api и добавляет в заказ товары. После чего оплачивает заказ
С началом маркировки воды. Есть вопрос 
Версия iiko 8.2.7014.0 заказ создается без ошибок и оплачивается. Как понимаю в 8.3.6 это поправили и он спросит марки при переходе на экран оплаты. То есть теперь заказ создаться но не оплачивается.

Как провести автоматескую оплату если в заказе есть марки?
**Cделайте метод который в тихом режиме проверит переданную марку и вернет результат. Если результат ОК то закроет заказ с нужными типами оплаты.**

Кейс использования:
Я буду считывать марку на своей стороне. И передавать в айку товар и его марку. 
И Хотел бы чтобы был метод куда бы я передал эту марку и товар и произошла проверка . На основании проверки я мог бы добавить в заказ уже проверенный товар и заказ бы автоматически оплатился бы в айки. Без участия кассира.

**Comment by vcpp** [comment]
Да, логичный сценарий. К сожалению, пока сканирование марок реализовано только на UI, поддержку в API появится чуть позже.

**Comment by vcpp** [comment]
Внутренний номер задачи: RMS-54451. Для начала будут поддерживаться только марки формата ФФД 1.2 для целого количества товаров.

**Comment by rengal** [comment]
Новые команды добавлены в Api.V8

Пример проверки кода маркировки:

```
var cashRegisterId = PluginContext.Operations.GetHostTerminalPointsOfSale().FirstOrDefault().CashRegister.Id;
var sale = new Resto.Front.Api.Data.Device.Tasks.ChequeSale("Tobacco", "12345", 100, 1,
  string.Empty, 1, 20, 0, 0, 100, string.Empty, ChequeTransferType.FullPayment)
{
  Ffd12 = new Resto.Front.Api.Data.Device.Tasks.Ffd12ChequeSaleData("<markingCode>", 2, null, null, null, 1)
};
var task = new CheckFfd12MarkingTask(Guid.NewGuid(), "Admin", Guid.NewGuid(), string.Empty)
{
  ChequeSale = sale
};
PluginContext.Operations.CheckFfd12Marking(credentials, cashRegisterId, task);
```


Пример передачи марки в позицию заказа
```
var editSession = PluginContext.Operations.CreateEditSession();
editSession.ChangeOrderItemMarkingCode(markingCode, order, productItem);
operationService.SubmitChanges(credentials, editSession);
```

Если на открыто окно редактирования заказа, нужно обернуть вызов в PluginContext.Operations.TryEditCurrentOrder
```
PluginContext.Operations.TryEditCurrentOrder(x => x.os.ChangeOrderItemMarkingCode(markingCode, order, productItem, os.GetCredentials()));
```

**Comment by Kamaew** [comment]
А с какой версии iiko доступный данные методы ?

**Comment by vcpp** [comment]
> А с какой версии iiko доступный данные методы ?

Метод `ChangeOrderItemMarkingCode` будет доступен начиная с V8Preview6 (8.5).
