### ISSUE TITLE
Тихая оплата

### ISSUE THREAD

**Issue by mahab-22** [iiko/front.api.sdk#434]
Здравствуйте!
Пытаюсь провести тихую оплату. Вот с таким кодом все работает, но только если экран не на заказе, который оплачивается тихо.
```
 const bool isProcessed = true;
var order = PluginContext.Operations.GetOrders().Last();
                    var paymentType = PluginContext.Operations.GetPaymentTypes().Last(x => x.Kind == PaymentTypeKind.Card);
                    var additionalData = new CardPaymentItemAdditionalData { CardNumber = "123456" };
                    var credentials = PluginContext.Operations.GetCredentials();
                     var paymentItem = PluginContext.Operations.AddExternalPaymentItem(1000m, isProcessed, additionalData, null, paymentType, order, credentials);
                        PluginContext.Operations.ProcessPrepay(credentials, order, paymentItem);
                        PluginContext.Operations.PayOrder(credentials, order);
```

Ав вот с таким кодом (скопирован [отсюда](https://iiko.github.io/front.api.doc/2020/11/09/silent-plugin-payments.html)) оплата вносится, но заказ не оплачивается.
```
const bool isProcessed = false;
                    var order = PluginContext.Operations.GetOrders().Last();
                    var paymentType = PluginContext.Operations.GetPaymentTypes().Last(x => x.Kind == PaymentTypeKind.External);
                    var additionalData = new ExternalPaymentItemAdditionalData { CustomData = Serializer.Serialize(new PaymentAdditionalData { SilentPay = true }) };
                    var credentials = PluginContext.Operations.GetCredentials();
                     var paymentItem = PluginContext.Operations.AddExternalPaymentItem(1000m, isProcessed, additionalData, null, paymentType, order, credentials);
                        order = PluginContext.Operations.GetOrderById(order.Id);
                        PluginContext.Operations.PayOrder(credentials, order);
```

То есть мне нужно, чтобы первый кусок кода работал также и на экране оплачиваемого заказа, либо чтобы работал второй кусок кода как заявлено. Подскажите, пожалуйста, что делать?

**Comment by igorpooh1978** [comment]
А тем чем вы пытаетесь провести оплату "тихую оплату" поддерживает ?

**Comment by mahab-22** [comment]
> А тем чем вы пытаетесь провести оплату "тихую оплату" поддерживает ?

А что Вы понимаете под "тем чем"?)) Первый участок кода работает в Sample Pay plugin , а вот второй [заявлен](https://iiko.github.io/front.api.doc/2020/11/09/silent-plugin-payments.html) как тихая оплата работает как я сказал наполовину. Если подскажете, буду благодарен, первый проект на с# пока не могу понять некоторые реализации при их разнообразии.
