### ISSUE TITLE
Закрытие заказа безналичной оплатой с контрагентом

### ISSUE THREAD

**Issue by MrOnlineCoder** [iiko/front.api.sdk#435]
Добрый день!

Пытаемся закрыть в плагине заказ с безналичной оплатой с контрагентом, однако почему-то получаем ошибку.

Делаем так:

```csharp
CreditPaymentItemAdditionalData additionalData = new CreditPaymentItemAdditionalData();
additionalData.CounteragentUserId = Guid.Parse("our-user-id");

editSession.AddPaymentItem(
	order.Resultsum,
	additionalData,
	paymentType,
	order
);

PluginContext.Operations.SubmitChanges(credentials, editSession);

PluginContext.Operations.PayOrder(credentials, order);
```

Однако выскакивает странная локализированная ошибка в стиле "У заказа уже есть элемент оплаты", при этом без типа исключения. Сам элемент оплаты добавляется, но заказ не закрываеться. С другими типам оплат такой проблемы нет. В чем может быть проблема?

API v6 (вынуждены использовать его из-за проблем с совместимостью у клиента)
Заранее спасибо!

**Comment by letolica** [comment]
Добрый день.
Тип оплаты в кредит (контрагентом) не поддерживает тихую оплату, поэтому закрытие заказа из апи с такой оплатой невозможно. Завела задачу на доработку с внутренним номером RMS-54524.
Начиная с версии 8.4.3 сообщение об ошибке перестало быть локализованным и конкретный кейс содержит примерно такой текст: _"Payment of order #17 (d8db5e70-da02-479e-885c-ca82bdfdaa7f) failed. Cannot process not silent payment item a8be2f5e-d1fb-4ee4-986e-b5b43c1bfc0d of payment type 193cef86-b6bd-287d-8363-5bdeaa1c7630."_

**Comment by letolica** [comment]
@MrOnlineCoder, а скажите, какой бизнес-сценарий использования именно безналчной оплаты контрагентом? Нельзя ли решить этот сценарий оплатой без выручки?
[Тип оплаты "Без выручки" стал поддерживать тихую оплату](https://iiko.github.io/front.api.doc/2023/02/22/silent-writeoff-payment-type.html)

**Comment by MrOnlineCoder** [comment]
@letolica на самом деле у клиента изначально была неверная конфигурация - мы хотели через плагин провести оплату онлайн (клиент оплатил онлайн, в айко нужно автоматически провести оплату отдельным типом). Они сделали его как безналичным типом, с контрагентом юр. лица платежной системы. Мы его переговорили сделать как описано в руководстве, через тип оплаты "Банковские карты", и все заработало
