### ISSUE TITLE
Проблема с добавлением данных в ExternalData у Order

### ISSUE THREAD

**Issue by tayabuz** [iiko/front.api.sdk#437]
Я разрабатывают платежный плагин, используя открытое API. Использую вот такой код для сохранения и последующего чтения записанных в ExternalData данных.
PluginContext.Operations.ExecuteContinuousOperation(
 operations =>
 {
      var editSession = operations.CreateEditSession();
      editSession.AddOrderExternalData("test", "test123", false, order);
      var authByPin = operations.AuthenticateByPin("1111");
      operations.SubmitChanges(authByPin, editSession);
      String rrnFromExtData = operations.TryGetOrderExternalDataByKey(order, "test");
 });

В результате при выполнении получаю следующую ошибку
Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.
Без использования ExecuteContinuousOperation я получаю такое же исключение.

У меня возникают следующие вопросы:
1) Что требуется в качестве PIN для AuthenticateByPin?
2) Возможно ли произвести успешную запись не требуя Credentials в SubmitChanges?

**Comment by fader1** [comment]
Скорее всего у вас заказ "занят".  или открыт в окне редактирования на терминале или в окне кассы, или какой-то процесс в это время его занял и уже вносит изменения.
PluginContext.Operations может получить доступ к внесению изменений в заказ только если он в этот момент никем и ничем не занят.
Тут или использовать IOperationService operations который передаётся из айко вместе с аттрибутами функции (если оно там есть).   Или ждать пока освободится  (при получении такой ошибки делать паузу, и пытаться повторить.).
К примеру:
 При открытии заказа в окне кассы в Notifications.NavigatingToPaymentScreen передаётся IOperationService operations.  И этот operations как раз имеет доступ в этот момент к редактированию заказа, а через PluginContext.Operations не удастся что-то изменить в заказе.

**Comment by ierof** [comment]
Ваша проблема не связана с `Credentials`, ваша проблема связана с тем, что заказ открыт в данный момент на UI.
В такие заказы API не может внести изменения. Как предложили выше, можно например добавлять `AddOrderExternalData` при навигации на кассу или в [`INotificationService.BeforeDoCheque`]
(https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_INotificationService_BeforeDoCheque.htm). Или периодически пытаться сохранить заказ. Или, если вы точно знаете что заказ открыт на экране заказа на UI iikoFront, то через [`IOperationService.TryEditCurrentOrder`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_TryEditCurrentOrder.htm). Смотря для чего вам нужны эти данные. 

По поводу `Credentials` -- в API V8 появился метод [`GetDefaultCredentials`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_GetDefaultCredentials.htm) см. https://iiko.github.io/front.api.doc/2024/04/03/default-credentials.html
