### ISSUE TITLE
Не видно PluginSettings в iikoOffice

### ISSUE THREAD

**Issue by fader1** [iiko/front.api.sdk#438]
Добрый день! 

Пытаюсь задействовать PluginSettings.
В документации написано "settings will be available in entity editor in iikoOffice".
Но как бы не старался, в iikoOffice в редактировании типа оплаты так и не появляются никакие текстовые поля и чекбоксы.
Притом настройки сохраняются и далее функцией GetPluginSettings их можно получить. Но в бэкофисе их не видно.
Версия 7.9.7013.0

```

var paymentType = PluginContext.Operations.GetPaymentTypes().First(k => k.Name.Contains("Онлайн-оплата") && k.IsEnabled == true);
var listSettings = new List<ISetting> {
                new TextBox("testBox", "Тут должен быть текст", "Нужное текстовое поле", false, 255),
                new CheckBox("checkboxTest", true, "Очень нужный чекбокс", false)
            };
var testSetting = new PluginSettings(Guid.Parse("5e3782bd-0a5b-4428-94c1-cc60446fd165"), paymentType.Id, 3, listSettings);
testSetting.DisplayName = "Должен быть заголовок настроек";
var settingsIniiko = new List<IPluginSettings>(){ testSetting }; 
PluginContext.Integration.UpdatePluginSettings(settingsIniiko);    

```

**Comment by ierof** [comment]
Добрый день! 
Да, вы нашли функционал, который мы не доделали :-)
Он не описан в документации и примерах и как-то заброшен.  
Я думаю, в будущей версии API мы изменим этот протокол без иллюзий, что будет показано что-то на UI.
Модели будут упущены, для сохранения обратной совместимости и данных, которые уже были сохранены. 
А в скором времени (надеюсь, в течение 2024 года) для настроек будет предложен иной механизм, он сейчас в тестировании. Он будет описан в документации.
