### ISSUE TITLE
Вопросы о PIN в AuthenticateByPin

### ISSUE THREAD

**Issue by tayabuz** [iiko/front.api.sdk#439]
Для получения ICredentials необходимо вызвать метод
var credentials = operationService.AuthenticateByPin(pin);
Правильно ли я понимаю, что для работы моего плагина (фоновая операция) потребуется отдельная учетная запись? 
Как ее можно получить? Кто задает для нее PIN?

**Comment by vcpp** [comment]
Если плагин, например, реализует интеграцию с мобильными терминалами для официантов, тогда все его действия выполняются от имени определённого официанта, который логинится на мобильном терминале по пин-коду, который затем используется плагином.
В вашем случае, вероятно, речь о фоновой автоматике, которая работает по собственной инициативе, и в этом случае, вы правы, нужна отдельная учётная запись. К сожалению, автоматическое создание учётных записей для плагинов ещё не реализовано, поэтому процесс несколько корявый, учётную запись придётся создавать вручную, обычно это делает специалист по внедрению, поддержке или тот, кто администрирует систему. PIN-код учётной записи плагина задаётся вручную и затем каким-то образом передаётся в плагин (это вне API). Например, его можно записать в конфиг плагина. Либо плагин, если он ещё не настроен, может зарегистрировать кнопку для ввода настроек, и когда пользователь нажмёт на эту кнопку, запросит ввод пин-кода и сохранит его где-нибудь в хранилище учётных записей.
