### ISSUE TITLE
Статусы в перечислении CashRegisterStatusField

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#44]
Добрый день!

Поясните, пожалуйста, что ожидает увидеть iiko по следующим статусам перечисления CashRegisterStatusField, которые могут запрашиваться в методе GetCashRegisterStatus:
```c#
enum CashRegisterStatusField
{
  // код ошибки последней операции? 
  /// <summary>Error code.</summary>
  ErrorCode,

  // доступен ли ОФД? Вроде для этого есть статус IsOfdConnected
  /// <summary>Offline mode.</summary>
  OfflineMode,

  // доступность ФН? Работает или нет?
  /// <summary>Fiscal storage.</summary>
  FiscalStorage,

  // ?
  /// <summary>Extended status.</summary>
  ExtendedStatus,

  // код ответа ОФД на отправку последнего документа?
  /// <summary>Ofd response code.</summary>
  OfdResponseCode,

  // ?
  /// <summary>Fiscal storage response code.</summary>
  FnResponseCode,

  // количество неоправленных в ОФД документов?
  /// <summary>Ofd buffered documents.</summary>
  OfdBufferedDocuments,

  // дата последнего фискального документа?
  /// <summary>Datetime of Ofd cheque.</summary>
  OfdChequeDateTime,

  // сумма последнего фискального документа?
  /// <summary>Sum of Ofd cheque.</summary>
  OfdChequeSum
}
```

**Comment by fraddy91** [comment]
ErrorCode - Код состояния ККМ, иными словами код ошибки самого оборудования, не ФН и не ОФД
RegisterDateTime - Текущее время на внешнем устройстве в формате yyyy-MM-dd HH:mm:ss (используется в рамках российского законодательства, ФЗ-54 запрашивается из фискального накопителя)
IsOfdConnected - Есть ли связь с провайдером ОФД (используется в рамках российского законодательства, ФЗ-54, запрашивается из фискального накопителя)
SessionStatus - Статус смены на внешнем устройстве (0-закрыта; 1-открыта; 2-истекла) (используется в рамках российского законодательства, ФЗ-54 запрашивается из фискального накопителя)
RestaurantMode - Активирован ли режим работы "Ресторан" (Используется в рамках законодательства Республики Беларусь, меняет механизм работы iiko Front, все данные об изменении заказа передаются в ФР "в прямом эфире")
OfflineMode - Активирован ли автономный режим ККМ (используется в рамках российского законодательства, ФЗ-54)
ExtendedStatus - Расширенный статус, одноимённый запрос из ФН по законодательству РФ, может использоваться и для других устройств, информационное поле
FiscalStorage - Присутствует ли фискальный накопитель (используется в рамках российского законодательства, ФЗ-54)
OfdResponseCode - Код ошибки от оператора фискальных данных (ОФД) (используется в рамках российского законодательства, ФЗ-54)
FnResponseCode - Код ошибки от ФН (используется в рамках российского законодательства, ФЗ-54)
OfdBufferedDocuments - Количество документов в буфере фискального накопителя, которые не были успешно отправлены оператору фискальных данных (используется в рамках российского законодательства, ФЗ-54)
OfdDocumentNumber - Фискальный признак документа, запрашивается из ФН (используется в рамках российского законодательства, ФЗ-54)
OfdUrl - Адрес оператора фискальных данных в сети Интернет, который был указан при регистрации, или изменён позднее, чаще всего есть возможность запросить у оборудования (используется в рамках российского законодательства, ФЗ-54)
OfdOrgName - Название оператора фискальных данных, который был указан при регистрации, или изменён позднее (используется в рамках российского законодательства, ФЗ-54)
OfdSalesAddress - Адрес расчета, который был указан при регистрации, или изменён позднее. Адрес расчёта являлся не обязательным в ФН версии 1.0, может отсутствовать, подробнее можно прочитать в свежем ФФД и документации конкретного устройства (используется в рамках 
российского законодательства, ФЗ-54)
OfdKkmRegistrationNumber - Регистрационный номер ККМ (используется в рамках 
российского законодательства, ФЗ-54)
OfdChequeDateTime - Дата и время первого (то есть самого старого) не переданного чека, который висит с буфере и ожидает передачи оператору фискальных данных (используется в рамках 
российского законодательства, ФЗ-54)
OfdChequeSum - Сумма последнего чека (используется в рамках 
российского законодательства, ФЗ-54)

**Comment by bildeyko** [comment]
Спасибо, отличное дополнение.

**Comment by bildeyko** [comment]
> OfdDocumentNumber - Фискальный признак документа, запрашивается из ФН (используется в рамках российского законодательства, ФЗ-54)

Требуется ФП именно последнего чека или последнего любого фискального документа? Потому что в ФН создаются разные документы:

- открытие/закрытие смены
- регистрация
- отчет о текущем состоянии расчетов
- чеки и чеки коррекции

**Comment by fraddy91** [comment]
> > OfdDocumentNumber - Фискальный признак документа, запрашивается из ФН (используется в рамках российского законодательства, ФЗ-54)
> 
> Требуется ФП именно последнего чека или последнего любого фискального документа? Потому что в ФН создаются разные документы:
> 
> * открытие/закрытие смены
> * регистрация
> * отчет о текущем состоянии расчетов
> * чеки и чеки коррекции

Это именно общий номер документа, не чека покупки/продажи.
