### ISSUE TITLE
Как назначить скидку внешнего типа оплаты?

### ISSUE THREAD

**Issue by tayabuz** [iiko/front.api.sdk#440]
Модуль внешнего типа оплаты получает информацию от своего сервера о необходимости скидки на определенную сумму. Как проинформировать об этой скидке iiko? Необходимо ли создавать свой тип скидки для этого случая?

**Comment by ierof** [comment]
Да, можно завести нужную маркерную скидку в iikoOffice и в своём процессоре оплаты, в [IPaymentProcessor.OnPaymentAdded](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IPaymentProcessor_OnPaymentAdded.htm) через параметр `IOperationService operationService` добавлять эту скидку.
