### ISSUE TITLE
Как получить схему работы предприятия фастфуд или ресторан?

### ISSUE THREAD

**Issue by dn110779nag** [iiko/front.api.sdk#445]
Столкнулилсь с проблемой, что при создании заказа по схеме фастфуда стол нельзя указывать.  А при заказе за столом он нужен. Как проверить, по какой схеме работает ресторан ?

**Comment by evgenyvalavin** [comment]
Хм, странно. Создание заказа всегда требует стол же

**Comment by dn110779nag** [comment]
нет, если в офисе поставить настройку фастфуд, то апи на попытку создать заказ с указанием стола даст неочевидную ошибку "Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index"

![image](https://github.com/iiko/front.api.sdk/assets/8987609/05fa4500-86df-451a-8f4b-38262f6c1394)

**Comment by vcpp** [comment]
> Как получить схему работы предприятия фастфуд или ресторан?

Увы, тип обслуживания не публикуется в API. Можно добавить, если есть потребность, но там есть нюансы — например, начиная с V8 в режиме «Ресторан» можно создавать «фастфудные» заказы (подробнее [тут](http://iiko.github.io/front.api.doc/2022/10/12/ts-ff-tabs.html)).

> при создании заказа по схеме фастфуда стол нельзя указывать.

Можно. Если стол не указан, заказ создаётся на [столе по умолчанию](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm). Если указать стол явно, заказ будет создан на указанном столе.

> Создание заказа всегда требует стол же

Нет, аргумент `tables` метода [`CreateOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_CreateOrder.htm) помечен атрибутом `CanBeNull` и сопровождается комментарием: *If tables is null or empty, then order will be created on the default table (depending on select iikoFront mode).*

> апи на попытку создать заказ с указанием стола даст неочевидную ошибку "Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.

А можете стектрейс показать?

**Comment by evgenyvalavin** [comment]
> > Как получить схему работы предприятия фастфуд или ресторан?
> 
> Увы, тип обслуживания не публикуется в API. Можно добавить, если есть потребность, но там есть нюансы — например, начиная с V8 в режиме «Ресторан» можно создавать «фастфудные» заказы (подробнее [тут](http://iiko.github.io/front.api.doc/2022/10/12/ts-ff-tabs.html)).
> 
> > при создании заказа по схеме фастфуда стол нельзя указывать.
> 
> Можно. Если стол не указан, заказ создаётся на [столе по умолчанию](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm). Если указать стол явно, заказ будет создан на указанном столе.
> 
> > Создание заказа всегда требует стол же
> 
> Нет, аргумент `tables` метода [`CreateOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_CreateOrder.htm) помечен атрибутом `CanBeNull` и сопровождается комментарием: _If tables is null or empty, then order will be created on the default table (depending on select iikoFront mode)._
> 
> > апи на попытку создать заказ с указанием стола даст неочевидную ошибку "Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
> 
> А можете стектрейс показать?

На самом деле режим работы Фаст Фуд или Ресторан было бы очень полезно иметь определять через API. И тут "в режиме «Ресторан» можно создавать «фастфудные» заказы" ничем не мешает т.к. это только для фронта применимо. В Waiter нам приходится на текущий момент делать отдельный параметр "FastFoodMode" чтоб избежать ошибок "Cannot use course first in FastFood Service Mode". Если бы возможность достать тип обслуживания была, мы бы убрали такие ошибки и убрали лишние затраты на поддержку.
![image](https://github.com/iiko/front.api.sdk/assets/35497422/c21266af-249c-48e8-9593-ba71f1972f8c)

**Comment by dn110779nag** [comment]
> > Как получить схему работы предприятия фастфуд или ресторан?
> 
> Увы, тип обслуживания не публикуется в API. Можно добавить, если есть потребность, но там есть нюансы — например, начиная с V8 в режиме «Ресторан» можно создавать «фастфудные» заказы (подробнее [тут](http://iiko.github.io/front.api.doc/2022/10/12/ts-ff-tabs.html)).
> 
> > при создании заказа по схеме фастфуда стол нельзя указывать.
> 
> Можно. Если стол не указан, заказ создаётся на [столе по умолчанию](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm). Если указать стол явно, заказ будет создан на указанном столе.
> 
> > Создание заказа всегда требует стол же
> 
> Нет, аргумент `tables` метода [`CreateOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_CreateOrder.htm) помечен атрибутом `CanBeNull` и сопровождается комментарием: _If tables is null or empty, then order will be created on the default table (depending on select iikoFront mode)._
> 
> > апи на попытку создать заказ с указанием стола даст неочевидную ошибку "Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
> 
> А можете стектрейс показать?

```
[2023-06-08 10:15:01,951] ERROR [80] - [rJtY2J] Ошибка при создании заказа
System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index

Server stack trace: 
   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   в Resto.CashServer.EntityBuilders.NotifyChangesList`1.get_Item(Int32 index) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityBuilders\NotifyChangesList.cs:строка 117
   в Resto.CashServer.Services.OrderService.ConvertToTableServiceOrderIfNeed(IBaseOrderBuilder orderBuilder) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.Edit.cs:строка 769
   в Resto.CashServer.Services.OrderService.ChangeOrderTables(IBaseOrderBuilder orderBuilder, TablesList tablesList, IReadOnlyDictionary`2 cookingPlaceDictionary, Boolean resetToFastFoodDefaultTable) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.Edit.cs:строка 752
   в Resto.Front.Api.V7.Editors.Actions.ChangeOrderTables.Apply(IBaseOrderBuilder orderBuilder, IReadOnlyList`1 tables, SessionContext context) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Actions\ChangeOrderTables.cs:строка 72
   в Resto.Front.Api.V7.Editors.Actions.ChangeOrderTables.Resto.Front.Api.V7.Editors.IEditActionBase.WriteChanges(SessionContext context, IDictionary`2 createdEntities, IDictionary`2 actionNumbersToCreatedApiEntities, Int32 i) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Editors.g.cs:строка 8494
   в Resto.Front.Api.V7.Editors.EditSessionWriter.WriteChanges() в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\EditSessionWriter.cs:строка 202
   в Resto.Front.Api.V7.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1965
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2473
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:строка 4519
   в Resto.Front.Api.monoPayment.mono.processors.logic.order.OrderCreationService.CreateOrder(CreateOrderOnTablePayload dto) в /src/client/mono/processors/logic/order/OrderCreationService.cs:строка 307
   в Resto.Front.Api.monoPayment.mono.processors.logic.order.OrderCreationService.CreateAndPayOrder(CreateOrderOnTablePayload dto) в /src/client/mono/processors/logic/order/OrderCreationService.cs:строка 82

```


Пользуюсь апи версии 7, т.к.

Апи версии 8 еще в стадии превью и наш плагин сейчас работает на 200+ ресторанов и не все вовремя обновляются

**Comment by dn110779nag** [comment]
Еще одна ошибка в догонку
Пытаюсь создать заказ на столе через сессию, стола оказывается столом по умолчанию, в результате получаю ошибку 


            IEditSession editSession = PluginContext.Operations.CreateEditSession();
            ExpzLogger.Info("Пытаемся создать заказ");
            var newOrder = editSession.CreateOrder(null);
            editSession.ChangeOrderOriginName(dto.OriginName, newOrder);
            editSession.ChangeOrderComment(dto.ExternalId, newOrder);
            ExpzLogger.Info($"Пытаемся найти стол по id {dto.TableId}");
            ITable table = operations.GetTableById(dto.TableId);
            ExpzLogger.Info($"Найден стол # {table.Number}; name: {table.Name}; active: {table.IsActive}; " +
                $"section: {table.RestaurantSection.Name}");
            editSession.ChangeOrderTables(newOrder, new List<ITable>() { table });
            .....
            var result = PluginContext.Operations.SubmitChanges(credentials, editSession);
            IOrder order = result.Get(newOrder);
            ExpzLogger.Info($"Заказ создан Id: {order.Id}, Number: {order.Number}");



[2023-06-10 14:32:46,055] ERROR [16] - [SrSTN8] Ошибка при создании заказа
System.ArgumentException: The order is already on specified tables.
Имя параметра: tables

Server stack trace: 
   в Resto.Front.Api.V7.Editors.Actions.ChangeOrderTables.CheckArguments(IBaseOrderBuilder order, IReadOnlyList`1 tables, SessionContext context) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Actions\ChangeOrderTables.cs:строка 43
   в Resto.Front.Api.V7.Editors.Actions.ChangeOrderTables.Resto.Front.Api.V7.Editors.IEditActionBase.WriteChanges(SessionContext context, IDictionary`2 createdEntities, IDictionary`2 actionNumbersToCreatedApiEntities, Int32 i) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Editors.g.cs:строка 8494
   в Resto.Front.Api.V7.Editors.EditSessionWriter.WriteChanges() в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\EditSessionWriter.cs:строка 202
   в Resto.Front.Api.V7.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1965
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2473
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:строка 4519
   в Resto.Front.Api.monoPayment.mono.processors.logic.order.OrderCreationService.CreateOrder(CreateOrderOnTablePayload dto) в /src/client/mono/processors/logic/order/OrderCreationService.cs:строка 310
   в Resto.Front.Api.monoPayment.mono.processors.logic.order.OrderCreationService.CreateAndPayOrder(CreateOrderOnTablePayload dto) в /src/client/mono/processors/logic/order/OrderCreationService.cs:строка 82
[2023-06-10 14:32:46,055]  INFO [16] - [SrSTN8] baseUrl => https://api.shaketopay.st4g3.com, path => /callback/createOrderOnTable, callbackUri => https://api.shaketopay.st4g3.com, callbackPath => /callback/debug-command


Не могу найти, где можно получить стол по умолчанию.
В итоге если задавать заказ в сессии, то не получается заказ создать вообще. Если создавать заказ, а потом менять стол, то получится куча повисших заказов на неправильных столах

**Comment by dn110779nag** [comment]
нашел, как определить стол по умолчанию

**Comment by vcpp** [comment]
> На самом деле режим работы Фаст Фуд или Ресторан было бы очень полезно иметь определять через API. 

Появится в одной из будущих версий (внутренний номер RMS-54790).

> ```
> System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
>
> Имя параметра: index
> Server stack trace: 
>   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   в Resto.CashServer.EntityBuilders.NotifyChangesList`1.get_Item(Int32 index) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityBuilders\NotifyChangesList.cs:строка 117
> ```

Ошибка вызвана отсутствием в заказе гостя. Попробуйте сначала добавить гостей, а поменять столы.

> Не могу найти, где можно получить стол по умолчанию.

[`PluginContext.Operations.GetHostTerminalsGroup().DefaultTable`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_DefaultTable.htm)

**Comment by evgenyvalavin** [comment]
> Появится в одной из будущих версий (внутренний номер RMS-54790).

Близится релиз API V8. Очень хочется чтобы такой простой параметр появился в API V8.
На текущий моментн не нашел такого параметра в API v8 Preview.

**Comment by vcpp** [comment]
> Очень хочется чтобы такой простой параметр появился в API V8.

[`ITerminalsGroup.ServiceMode`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_ServiceMode.htm).

**Comment by letolica** [comment]
[Тип обслуживания в группе](https://iiko.github.io/front.api.doc/2023/11/22/service-mode.html).
