### ISSUE TITLE
PayOrderAndPayOutOnUser isnt licensed

### ISSUE THREAD

**Issue by shubyonkin** [iiko/front.api.sdk#447]
Пытаюсь оплатить заказ(тест) с помощью первого  попавшегося типа оплаты, получаю ошибку PayOrderAndPayOutOnUser   isnt licensed
код:
```
var paymentTypes = PluginContext.Operations.GetPaymentTypesToPayOutOnUser();
            
          
PluginContext.Operations.PayOrderAndPayOutOnUser(PluginContext.Operations.GetCredentials(), order, paymentTypes.Last(), order.FullSum);
```

**Comment by vcpp** [comment]
Эта ошибка означает, что лицензия на ваш плагин, определяемая по `moduleId`, не допускает выполнение кассовых операций. Надо заново запросить moduleId, указав, что плагину нужна возможность выполнять кассовые операции.
