### ISSUE TITLE
Документация iiko back office

### ISSUE THREAD

**Issue by d3vvcom** [iiko/front.api.sdk#448]
Здравствуйте, есть задача для написания плагина расширяющий функционал явки сотрудников с помощью открытие и закрытие явки через подтверждение распознаванием лица. В аналогичном плагине beopen biometric имеется два плагина один для фронта (iikoFront API) и плагин для backOffice. К сожалению в открытых источниках не смог найти документацию для написания плагина для backOffice. Буду рад если подскажите где его взять, и что для этого нужно. Спасибо. 

P.S. api@iiko.ru направили меня сюда

**Comment by vcpp** [comment]
Хм, странно, что сюда направили, здесь консультации только про Front API.

В любом случае, обе версии BackOffice — классическое WinForms-приложение и веб-приложение aka iikoWeb — не располагают публичным API. Для работы с явками посмотрите [iikoServer API](https://ru.iiko.help/articles/api-documentations/employees/a/v1.API%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2-%D0%AF%D0%B2%D0%BA%D0%B8).
