### ISSUE TITLE
Передавать SettlementAddress и SettlementPlace в DoCorrection

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#45]
Добрый день!

Считаю, что в CorrectionTask должна быть информация об адресе и месте расчета, как в ChequeTask.

С какой ситуацией столкнулись мы: при регистрации кассы можно не указывать адрес/место, тогда касса требует указание этих значений при создании фискальных документов. 
Чек коррекции является фискальным документом, касса требует значения, но в DoCorrection их никак не получить из iiko.

**Comment by GulnaraBikbova** [comment]
Добрый день.

Сейчас для чека коррекции не передается настройка "Адрес и место расчета".
Могу предложить вам добавить свою аналогичную настройку "Адрес расчета для чека коррекции", и "Место расчета для чека коррекции" и их считывать из CashRegisterSettings в DoCorrection(). 
Подойдет ли Вам такой вариант?

**Comment by bildeyko** [comment]
Я думаю да, так и сделаем.
