### ISSUE TITLE
Лимит на оплату в плагине оплаты

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#450]
Добрый день!
В нашем плагине реализован PaymentProcessor для нашей лояльности.
Таким образом на стороне фронта мы можем оплачивать как наличным, безналичным так и нашим внешним видом оплаты.
В данный момент возникла необходимость ограничить оплату заказа нашим видом оплаты в плагине в 30%. Остальные виды оплаты должны работать без ограничений.
Т.е. нашим видом оплаты в плагине мы должны иметь возможность оплаты не более 30% от суммы заказа.

Варианта - кроме как реализовать всю логику в нашем плагине мы не нашли. Видим в этом варианте достаточно много подводных камней.

В rKeeper данная функциональность включалась настройкой - "Максимальный процент"

![image](https://github.com/iiko/front.api.sdk/assets/68583005/dcde5c00-586b-4d26-b882-4d687a15b3ca)

Схема с Card-ом нам к сожалению так же не подходит.

Возможно есть специфичные настройки в RMS или в SDK FrontAPI?

**Comment by kolan72** [comment]
В аргументах некоторых методов интерфейса `IPaymentProcessor` присутствует конечно аргумент типа `IPaymentItem`. Но в его свойствах ничего близкого к теме ограничения суммы по проценту вроде бы не находится. 
Так что если такое ограничение и есть, то видимо действительно только где-то в настройках.

**Comment by MiAlLevin** [comment]
> Добрый день! В нашем плагине реализован PaymentProcessor для нашей лояльности. Таким образом на стороне фронта мы можем оплачивать как наличным, безналичным так и нашим внешним видом оплаты. В данный момент возникла необходимость ограничить оплату заказа нашим видом оплаты в плагине в 30%. Остальные виды оплаты должны работать без ограничений. Т.е. нашим видом оплаты в плагине мы должны иметь возможность оплаты не более 30% от суммы заказа.
> 
> Варианта - кроме как реализовать всю логику в нашем плагине мы не нашли. Видим в этом варианте достаточно много подводных камней.
> 
> В rKeeper данная функциональность включалась настройкой - "Максимальный процент"
> 
> ![image](https://user-images.githubusercontent.com/68583005/244305372-dcde5c00-586b-4d26-b882-4d687a15b3ca.png)
> 
> Схема с Card-ом нам к сожалению так же не подходит.
> 
> Возможно есть специфичные настройки в RMS или в SDK FrontAPI?

Коллеги, возможно в SDK есть возможность перехватывать события изменения оплаты в заказе и тем самым ограничивать вводимые суммы на клавиатуре?
![image](https://github.com/iiko/front.api.sdk/assets/68583005/1010c15b-f535-4ad3-b6e9-f777d975840f)

Например, можно баллами оплатить не более 30%. Заказ на 100 рублей. Переходим на безналичную оплату и пытаемся ввести сумму. При вводе более 30 рублей счетчик сбрасывается на "0". А так же есть ли возможность управления кнопкой "Точная сумма"???

**Comment by igorpooh1978** [comment]
Посмотрите в сторону ChangePaymentItem и его работу в методе OnPaymentAdded

**Comment by MiAlLevin** [comment]
Да, спасибо - через него и реализовали. Думалось что есть просто некая настройка и плагин дописывать не придется.

**Comment by vcpp** [comment]
> Посмотрите в сторону ChangePaymentItem и его работу в методе OnPaymentAdded

[`ChangePaymentItemSum`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_ChangePaymentItemSum.htm)?

> Думалось что есть просто некая настройка и плагин дописывать не придется.

К сожалению, простой настройкой на уровне типа оплаты в большинстве случаев не обойтись, максимально допустимую сумму оплаты обычно приходится указывать через плагин. Как минимум, надо учитывать остаток на бонусном счёте конкретного покупателя. Кроме того, допустимый процент оплаты бонусами может зависеть от суммы заказа и от «уровня» покупателя в системе лояльности. Если подключено сразу несколько систем лояльности и их допускается комбинировать, надо также учитывать, какие другие бонусные оплаты уже добавлены в заказ.
