### ISSUE TITLE
Проверка должности

### ISSUE THREAD

**Issue by LeeTwelve** [iiko/front.api.sdk#451]
Добрый день, как я понял, нельзя  создавать собственные пермишены, чтобы потом вызывать авторизационный попап.

Можно ли как-то сделать проверку должности?

**Comment by vcpp** [comment]
> как я понял, нельзя создавать собственные пермишены, чтобы потом вызывать авторизационный попап.

Верно, добавить новое право не получится.
Однако, можно проверять любое из существующих прав:
* [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermission.htm) — проверить наличие права без показа окна
* [`ShowCheckPermissionPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowCheckPermissionPopup.htm) — показать диалог подтверждения права
* Если уж очень нужно отдельное своё право, вместо добавления нового права можно среди существующих трёхсот с лишним выбрать какое-нибудь неиспользуемое и начать использовать в своих целях. Название, конечно, будет неподходящим, с этим либо смириться, либо вручную поправить через resx-файл.

> Можно ли как-то сделать проверку должности?

Можно проверить, какие роли (должности) назначены указанному сотруднику ([`GetUserRoles`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetUserRoles.htm)). Показать диалог а-ля прокатайте карту любого сотрудника с такой-то ролью — нельзя.
