### ISSUE TITLE
Вызов DirectIO фискального регистратора из IChequeTaskProcessor

### ISSUE THREAD

**Issue by dushad** [iiko/front.api.sdk#452]
Добрый день,

Мы хотим в Штрихе выставить значение во внутреннюю таблицу через DirectIO внутри нашего обработчика IChequeTaskProcessor.BeforeDoCheckAction, есть ли какая то возможность в Api V7 для этого?

Спасибо.

**Comment by vcpp** [comment]
Такую возможность [добавили](http://iiko.github.io/front.api.doc/2023/05/15/api-cashregister.html) совсем недавно в V8. Не дожидаясь релиза V8, прямо сейчас можно начать использовать [`CashRegisterDirectIO`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_CashRegisterDirectIO.htm) в [V8Preview6](https://www.nuget.org/packages/Resto.Front.Api.V8Preview6/).
Увы, в V7 это недоступно.
