### ISSUE TITLE
Четко понимать IReserve: банкет или резерв?

### ISSUE THREAD

**Issue by evgenyvalavin** [iiko/front.api.sdk#453]
Сейчас в Front API есть тип IReserve.

Звучит как-будто это именно резерв. Но на самом деле IReserve может быть и банкетом.
В итоге в моих кругах появилось более общее понятие Бронирование (Booking). Бронированием является как Резерв, так и Банкет. Противоречий нет.

**Проблема:** не понятно какой метод вызывать для старта IReserve.
Во Front API есть два метода которые намекают на начало:
1. IEditSession.StartBanquet(IReserve...);
2. IEditSession.ActivateReserve(IReserve...);

Какой из них когда вызывать если по IReserve не понятно резерв это или банкет? Можно предложить определять банкет по наличию заказа в IReserve.Order (can be null). Но смотреть на это нельзя, т.к. банкет может быть без заказа.

Итого нормальная работа с банкетами/резервами невозможна.

**Что хочется:**
1. Идеально конечно IBooking с общими properties для IReserve и IBanquet.
2. Хотя бы в IReserve добавить bool IsBanquet.

**Comment by vcpp** [comment]
> Хотя бы в IReserve добавить bool IsBanquet.

Эх, там есть такое свойство, но по недоразумению его забыли опубликовать, поэтому плагинам оно недоступно :-(
Странно, что никто раньше не заметил... Спасибо за подсказку, будет добавлено в следующей версии API.

> Проблема: не понятно какой метод вызывать для старта IReserve.
В качестве временного решения до выхода новой версии API вы можете вызывать оба метода, добавив обработку ожидаемого исключения:
```cs
try
{
    PluginContext.Operations.StartBanquet(IReserve...);
}
catch (ConstraintViolationException e) when (e.Message == "Cannot start reserve. Start operation is supported only for banquets.")
{
    var es = PluginContext.Operations.CreateEditSession();
    es.ActivateReserve(IReserve...);
    PluginContext.Operations.SubmitChanges(credentials, es);
}
```
Ожидаемые исключения:
* `StartBanquet` для резерва выбросит `ConstraintViolationException`: *Cannot start reserve. Start operation is supported only for banquets.*
* `ActivateReserve` для банкета выбросит `ConstraintViolationException`: *Cannot close banquet. Closing reserve and creating order is meaningless for banquets, which are intended to coexist with orders.*
