### ISSUE TITLE
IEditSession.ChangeOrderTables requires F_DOP permission

### ISSUE THREAD

**Issue by evgenyvalavin** [iiko/front.api.sdk#459]
При наличии у пользователя права F_CMP (Change table in order with printed items) IEditSession.ChangeOrderTables сменить стол у заказа не выйдет, если будет отсутствовать право F_DOP (Авторизовывать опасные операции вводом ПИН-кода).

### Проблема
Resto.Front.Api.Exceptions.PermissionDeniedException: Access denied. User must have Сменять номер стола с отпечатанными блюдами and Авторизовывать опасные операции вводом ПИН-кода permissions to move printed items.

Выглядит багом потому что:

1. Пин код и так обязательно требуется при работе через API. IOperationService.AuthenticateByPin(...)
2. Для IEditSession.MoveOrderItemToAnotherOrder(...) право F_DOP не требуется. Отсюда неконсистентность поведения с IEditSession.ChangeOrderTables.
3. На фронте через UI стол сменть возможно без права F_DOP.

### Ожидается
Право  F_DOP не проверяется для IEditSession.ChangeOrderTables

**Comment by evgenyvalavin** [comment]
Актуально

**Comment by evgenyvalavin** [comment]
@letolica привет!
Проблема актуальна

**Comment by letolica** [comment]
Привет, @evgenyvalavin.
Спасибо за сигнал, и приношу извинения за долгое ожидание.
Да, это баг. Завела задачу с внутренним номером RMS-55806.
Постараемся поправить и по итогу отпишемся тут.

**Comment by evgenyvalavin** [comment]
> Привет, @evgenyvalavin. Спасибо за сигнал, и приношу извинения за долгое ожидание. Да, это баг. Завела задачу с внутренним номером RMS-55806. Постараемся поправить и по итогу отпишемся тут.

Благодарю за ответ!

**Comment by letolica** [comment]
Исправили во всех поддерживаемых версиях API начиная с версии iikoFront 8.8.2.
