### ISSUE TITLE
Неверный результат GetIncludedInMenuSectionsByProduct

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#46]
Столкнулись на объекте, который работает через iikoChain. Воспроизведено на обычном экземпляре. 
### Ситуация
Есть отделение "Киоск", к отделению прикреплена ценовая категория "Для киоска". С помощью приказов регулируется, продается ли модификатор в этой ценовой категории или нет.
По приказу модификатор продается **только** в ценовой категории "Для киоска", следовательно должен продавать в отделении "Киоск". В основных свойствах модификатора ни у одного отделения не стоят галочки для продажи, потому что есть приказ.
**Базовый прайс-лист:**
![image](https://user-images.githubusercontent.com/2943468/59602440-6960cf80-910f-11e9-83db-c63429baa07b.png)
**Прайс-лист для ценовой категории:**
![image](https://user-images.githubusercontent.com/2943468/59602424-5d750d80-910f-11e9-9fdc-dacf37eb625c.png)
**Места продажи в свойствах позиции:**
![image](https://user-images.githubusercontent.com/2943468/59601950-3bc75680-910e-11e9-8a83-754a9a16477b.png)

### Ожидание
Приказы более приоритетны, чем галочки в основных свойствах, поэтому GetIncludedInMenuSectionsByProduct должен вернуть список, содержащий отделение "Киоск".

### Что в реальности
GetIncludedInMenuSectionsByProduct возвращает пустой список (из нашего лога):
`[2019-06-17 14:17:07,410]  INFO [25] - ProductsFilterInfo – Продукт Скрытый модиф по приказу[e9baa85b-a79f-4290-99fa-3651da1539d2] не продается в настроенном отделении. Продается только в отделениях: []`
Если же в свойствах модификатора поставить галочку, что продается в отделении "Киоск", тогда метод вернет это отделение (лога не будет):
![image](https://user-images.githubusercontent.com/2943468/59602247-f0617800-910e-11e9-83db-1c1d76ebb80a.png)

Получается, для метода приоритетнее галочки, а не приказы:

- Если галочка стоит и по приказу позиция продается, метод вернет отделение;
- Если галочка стоит, но по приказу позиция не продается, метод не вернет отделение;
- Если галочка не стоит, но по приказу позиция продается в отделении, метод не вернет это отделение, а должен.

Это же справедливо, если позиция продается по базовому прайс-листу. В основных свойствах написано "Включено по приказу", но метод все равно не возвращает нужное отделение:
**Базовый прайс-лист:**
![image](https://user-images.githubusercontent.com/2943468/59602539-a331d600-910f-11e9-83bb-2179c7f73b6a.png)
**Прайс-лист для ценовой категории:**
![image](https://user-images.githubusercontent.com/2943468/59602561-ac22a780-910f-11e9-9f94-903eb0e539ee.png)
**Места продажи в свойствах позиции:**
![image](https://user-images.githubusercontent.com/2943468/59602571-b349b580-910f-11e9-86a6-90eb3bcc0e83.png)

Ради эксперимента, в свойствах выберем несколько отделений, но кроме "Киоск":
![image](https://user-images.githubusercontent.com/2943468/59602995-e476b580-9110-11e9-9697-04d6b037a2d2.png)
Несмотря на то, что позиция по приказу продается в отделении, этого отделения не будет в списке (наш лог):
`[2019-06-17 15:00:30,514]  INFO [58] - ProductsFilterInfo – Продукт Скрытый модиф по приказу[e9baa85b-a79f-4290-99fa-3651da1539d2] не продается в настроенном отделении. Продается только в отделениях: [{"Id":"9e9bae9d-b70f-4a75-b1dc-6f5e71fa7130","Name":"Новое отделение"},{"Id":"1d5d5ca7-7644-f3bf-015f-fd2a7e3300c4","Name":"Бар"},{"Id":"1d5d5ca7-7644-f3bf-015f-fd2a7e3300c6","Name":"Зал"}]`

### Заключение
Так быть не должно. Список должен содержать отделение "Киоск", а метод ставить в приоритет продажи по приказам, а не по галочкам из свойства. Потому что на объектах, которые работаю через iikoChain все крутится вокруг приказов и вообще нет возможности редактировать эти галочки.

**Comment by ierof** [comment]
Галочка "включать в прайс-лист" в карточке модификатора даёт возможность добавлять его в заказ как независимое блюдо. Она не влияет на его свойства как модификатора продукта. 
Метод `GetIncludedInMenuSectionsByProduct ` показывает, что именно включено в иерархическое меню, поэтому в описанном вами кейсе всё работает корректно. Проверьте с UI, ваш "Скрыть модиф по приказу" должен был появиться как независимый элемент меню. Т.е. метод `GetIncludedInMenuSectionsByProduct` именно про меню, не больше, не меньше.  

Что касается приказов — вы правильно заметили, что они управляют видимостью модификаторов в составе блюда. Получается, ваш вопрос сводится к: "Как заранее узнать, виден ли модификатор в данном отделении в составе модификаторов блюда"?

**Comment by ierof** [comment]
Заранее проблематично получить список доступных модификаторов с учётом отделений/ценовых категорий. Тут могу рекомендовать разве что сначала первично получать модификаторы для всех продуктов `PluginContext.Operations.GetSimpleModifiersByProduct(product)` / `PluginContext.Operations.GetGroupModifiersByProduct(product)`, он будет широкий, без учёта приказов. А потом, уже при добавлении позиций проверять `IOrderProductItem.AvailableSimpleModifiers` / `IOrderProductItem.AvailableGroupModifiers` 

У нас на это завела issue: *учитывать ценовые категории / отделения в GetSimpleModifiersByProduct и GetGroupModifiersByProduct*, но сроков обещать не могу.

**Comment by letolika** [comment]
@bildeyko, а можно узнать сценарий, в котором понадобилось знать в каких отделениях продается проблемный модификатор? Вы хотите продавать его отдельно от основного блюда или всё-таки вместе с основным блюдом?

**Comment by bildeyko** [comment]
Продавать как зависимый модификатор. 
И нам важно _заранее_ понять, виден модификатор в отделении или нет. В противном случае мы предложим для заказа клиенту на киоске самообслуживания недоступный модификатор, недоступность которого сможем проверить только на этапе формирования заказа.

**Comment by letolika** [comment]
@bildeyko, прошу прощения за долгое ожидание ответа.
`GetIncludedInMenuSectionsByProduct` действительно не очень ожидаемо работает с модификаторами. Как верно подметила @ierof, данный метод показывает, что именно включено в иерархическое меню. А в иерархическое меню указанный в примере модификатор не включен. В этом можно убедиться на UI фронта. Но, как Вы правильно заметили, данный модификатор включен в меню, как зависимый. И этот продукт можно добавлять к блюдам.
Завела задачу на доработку (RMS-50342).
Спасибо за подробный пример воспроизведения. Следите за новостями и обновлениями нашего API: [https://iiko.github.io/front.api.doc/changelog.html](url)

**Comment by letolika** [comment]
http://iiko.github.io/front.api.doc/2019/12/09/get-modifiers-via-price-category.html
