### ISSUE TITLE
Событие BeforeOrderBill передает в качестве IViewManager null, когда происходит оплата заказа 

### ISSUE THREAD

**Issue by Leo506** [iiko/front.api.sdk#461]
## Проблема
Когда происходит оплата заказа в обработчик события BeforeOrderBill в качестве IViewManager приходит null, из-за чего может возникнуть NullReferenceException. О том, что IViewManager может быть null нет нигде упоминания. Ни в документации, ни в самой API (параметр не отмечен как nullable)

## Ожидается
Отметить параметр как допускающий nullable значение
```c#
INotification<(IOrder order, IUser user, IOperationService os, IViewManager? vm)> BeforeOrderBill { get; }
```

**Comment by vcpp** [comment]
В текущей реализации код в основном размечается атрибутами `CanBeNull` и `NotNull`, которые нельзя применить в случае `ValueTuple`. Вы правы, пора переходить на nullable reference types. Спасибо за подсказку!
