### ISSUE TITLE
Печать информации на "ТОВАРНЫЙ ЧЕК" из плагина.

### ISSUE THREAD

**Issue by aitkkia** [iiko/front.api.sdk#466]
Добрый день.
В "Квитанция об оплате заказа" добавить дополнительную информацию можно без проблем через IChequeTaskProcessor.
1. Необходимо добавить информацию в товарный чек. Информация разная в зависимости от введённых данных - поэтому через шаблон сделать не получается.
2. Не могу найти пример как извлечь данные в шаблоне сохранённые через SetRollbackData/SetCustomData/AddOrderExternalData?

**Comment by vcpp** [comment]
> Необходимо добавить информацию в товарный чек.

Увы, это пока не поддерживается. Можете чуть подробнее рассказать, в каком именно виде вы планируете добавлять информацию в чек? Что-то вроде `BillCheque` с возможностью передать из плагина в шаблон 4 значения (`BeforeHeader`, `AfterHeader`, `BeforeFooter`, `AfterFooter`)?

> Не могу найти пример как извлечь данные в шаблоне сохранённые через SetRollbackData/SetCustomData/AddOrderExternalData

Данные, записанные через `AddOrderExternalData`, можно считать в шаблоне из `Model.Order.ExternalData`, там будет `IDictionary<string, string>` со всеми данными всех плагинов. Данные, заданные с помощью `SetRollbackData` и `SetCustomData` из шаблона читать не предполагается, эти данные записываются и считываются плагином.

**Comment by aitkkia** [comment]
> > Необходимо добавить информацию в товарный чек.
> 
> Увы, это пока не поддерживается. Можете чуть подробнее рассказать, в каком именно виде вы планируете добавлять информацию в чек? Что-то вроде `BillCheque` с возможностью передать из плагина в шаблон 4 значения (`BeforeHeader`, `AfterHeader`, `BeforeFooter`, `AfterFooter`)?
> 
Да, хотелось бы работать с ним плюс минус как с IChequeTaskProcessor.
> > Не могу найти пример как извлечь данные в шаблоне сохранённые через SetRollbackData/SetCustomData/AddOrderExternalData
> 
> Данные, записанные через `AddOrderExternalData`, можно считать в шаблоне из `Model.Order.ExternalData`, там будет `IDictionary<string, string>` со всеми данными всех плагинов. Данные, заданные с помощью `SetRollbackData` и `SetCustomData` из шаблона читать не предполагается, эти данные записываются и считываются плагином.
Спасибо. Попробую.

**Comment by rengal** [comment]
В API V9Preview2 появилась возможность подписаться на обработчик [BeforeFormatDocument](https://iiko.github.io/front.api.sdk/v9/html/M_Resto_Front_Api_IOperationService_RegisterBeforeFormatDocumentHandler.htm). 
Обработчик принимает на вход документ в виде xml-разметки, вносит необходимые изменения и возвращает модифицированный документ.

Чтобы задать в шаблоне, где именно нужно добавить дополнительную информацию, можно использовать один или несколько тегов `<section>` в шаблоне документа:
`<section name="myplugin_section_name" data="@order.Id"`>
В обязательном уникальном атрибуте "name" нужно передать название секции, которое будет обрабатывать ваш плагин
В опциональном атрибуте "data" можно передать какую-то информацию из модели данных в обработчик в вашем плагине (например, orderId)

Пример использования есть в SamplePlugin
