### ISSUE TITLE
Отсутствует список платажей в IOrder.Payments

### ISSUE THREAD

**Issue by lampaa** [iiko/front.api.sdk#468]
На объекте есть система лояльности, которая создает свой тип оплаты. Добавляем часть оплаты бонусами.

При получении объекта заказа через `PluginContext.Operations.GetOrderById` в объекте `Payments` ничего не появляется. Но через какое-то время иногда платеж появляется и пропадает. Потом опять появляется, но уже с новым идентификатором О_о. 

Что это такое, почему так может быть?

**Comment by ierof** [comment]
Состав оплат зафиксирован и окончательный после того, как заказ перешёл в статус `Closed`.
До этого ядро в праве добавлять и удалять  платежи по своим правилам.
