### ISSUE TITLE
ShowExtendedInputDialog возвращает null если в settings NumericInputMode = NumericInputMode.Decimal

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#469]
Добрый день, вопрос по новому функционалу API
В api V8 появилась возможно показывать диалоговые окна с возможностью вводить дробное число, если указать NumericInputMode.Decimal.
https://iiko.github.io/front.api.doc/v8/ru/ViewManager.html
Попробовал это сделать, диалоговое окно отображается нормально, запятая есть, работает, но ShowExtendedInputDialog всегда возвращает null, если указать в его настройках NumericInputMode.Decimal.
При чем не важно какое значение вводить в диалоге - "0,7", "456,5" или целое число "123", результат всегда null.

Вот пример моего кода:

var settings = new ExtendedInputDialogSettings()
            {
                NumericInputMode = NumericInputMode.Decimal,
                TabTitleNumericString = "Количество",
            };
            var dialogResult = vm.ShowExtendedInputDialog("Картофель ранний", "Укажите оставшееся количество товара", settings);
            
Я использую сборку Resto.Front.Api.V8 версии 8.5.8002.0.
Проверял на Resto.Front.Api.V8Preview6 - то же самое.
Похоже на баг, ну или я что-то не так делаю, подскажите пожалуйста

**Comment by pro100roman24** [comment]
В статье https://iiko.github.io/front.api.doc/v8/ru/ViewManager.html

Приведен пример:
var settings = new ExtendedInputDialogSettings
{
    NumericInputMode = NumericInputMode.Decimal,
    TabTitleNumericString = "Decimal number",
    MaxDecimalValue = 500,
    DefaultDecimalValue = 50
}

var dialogResult = viewManager.ShowExtendedInputDialog(
                "Заголовок окна", 
                "Подзаголовок, поясняющий что именно нужно ввести пользователю.",
                settings) 
    as NumericStringInputDialogResult;
if (dialogResult == null)
    return;
// analyze result

Но класса NumericStringInputDialogResult не существует в Resto.Front.Api.Data.View.
Это кажется устаревший класс.
Я нашел в Resto.Front.Api.Data.View класс DecimalInputDialogResult и попробовал привести к нему результат ShowExtendedInputDialog, но толку нет, когда результат null в любом случае.

**Comment by igorpooh1978** [comment]
Я подозреваю что вы должны использовать именно V8, а не V8pX, а это только через прямое подключение dll или ждать новое превью

**Comment by pro100roman24** [comment]
В том то и дело, что я пробовал и v8 и V8Preview6 - одно и то же.
Всегда возвращается null из инпутдиалога, если ввести дробное значение.

**Comment by badDev1337** [comment]
Добрый день, поддерживаю, до сих пор независимо от введенных данных возвращается null, API V8 Preview 6

https://github.com/iiko/front.api.sdk/assets/135623085/9735266a-36fb-4576-949f-57e097e78855

**Comment by zed220** [comment]
Здравствуйте!

Спасибо за информацию. Это баг. Внутренний номер задачи RMS-55386. Мы напишем здесь сообщение, когда его исправим.

Спасибо!

**Comment by mbagritsevich** [comment]
Баг поправили, можно будет использовать в новых версиях.
Обновили статью https://iiko.github.io/front.api.doc/v8/ru/ViewManager.html
