### ISSUE TITLE
Внешний фискальный регистратор СorrectionTask.VatSum.TaxName

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#47]
Добрый день,
Подскажите пожалуйста, откуда из iiko поступают эти данные (как это сконфигурировать)
Заранее спасибо

**Comment by ierof** [comment]
@fraddy91 @GulnaraBikbova ☝️

**Comment by fraddy91** [comment]
> Добрый день,
> Подскажите пожалуйста, откуда из iiko поступают эти данные (как это сконфигурировать)
> Заранее спасибо

Добрый день, данное поле не передаётся в рамках чека коррекции.
Передаются поля:

- TaxableSum - расчётная сумма, введённая пользователем.

- TaxAmount - сумма НДС, считается по проценту введённого процента ставки

- IsTaxable - является налогооблагаемым (false только для ставки "Без НДС")

- IsCalculated - является ли ставка рассчитанной (18/118, 10/110, 20/120 etc...)

- TaxPercent - процент ставки налога

- TaxId - Идентификатор налоговой ставки для внешнего устройства, в случае чека коррекции он берётся не из настроек устройства а из константных значений по ФФД (ФЗ-54)
