### ISSUE TITLE
добавление данных о чаевых в модель данных  для  OLAP  по продажам

### ISSUE THREAD

**Issue by maximemmmm** [iiko/front.api.sdk#474]
сейчас  единственная возможность рассчитать  выплаты официанту в **одном** отчете, которые содержат  как почасовую ставку, так и чаевые по кредитным картам, так и продажи за период по сотруднику это делать кастомный отчет на фронте, что  неудобно и  для изменения любого параметра нужно хорошо разбираться в  программировании.    

Планируется ли добавление ( или можно ли это как то сделать) данные  транзакций типов платежей помеченных как типы платежей для чаевых в модели данных  которая используется для ОЛАП отчетов по продажам? 

Аналогичный вопрос об отработанных часах в каждой роли  сотрудника -   можно ли эти данные тоже добавить в модель данных?

**Comment by ierof** [comment]
Это вопрос не про iikoFront API.
API имеет возможность добавлять "интегрированные чаевые" -- https://iiko.github.io/front.api.doc/v6/ru/Donations.html (это https://ru.iiko.help/articles/#!iikofront-8-2/topic-54)
Какие уже есть интеграции можете ознакомиться с https://ru.iiko.help/articles/#!special-iiko/tips

Как правильнее смотреть отчётность по чаевым -- это стоит обратиться к своей сервисной организации, которая поддерживает iiko у вас. Или через https://iiko.ru/contacts
