### ISSUE TITLE
Удаление заказа в статусе Closed

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#476]
https://github.com/iiko/front.api.sdk/issues/281
Т.к данный тикет закрыт, подскажите есть ли возможность удалить оплаченный заказ по апи, методов не увидел

**Comment by letolica** [comment]
Добрый день.
Да, в статье [Возврат заказа (сторнирование)](https://iiko.github.io/front.api.doc/2023/10/18/storno-order.html) даже привели пример удаления.
