### ISSUE TITLE
Как организовать передачу гостевого счета во внешнюю систему (систему управления отелем)?

### ISSUE THREAD

**Issue by VMescheryakov** [iiko/front.api.sdk#477]
Добрый день
Есть пример плагина для такого функционала?

**Comment by vcpp** [comment]
Именно такого примера нет.
Опишите, пожалуйста, подробнее, какой именно сценарий вы хотите реализовать?

**Comment by VMescheryakov** [comment]
Если счет оплачивается видом оплаты "На счет в отеле" то показывается диалог авторизации гостя, диалог делает запрос в PMS, запрос возвращает ссылку на счет в отеле, баланс и кредитный лимит. В счете ресторана запоминается информация  о счете в отеле. После того как счет закрывается весь состав счета передается в отель так как там будет распечатан фискальный чек

**Comment by vcpp** [comment]
Самое простое — подписаться на изменение заказов и при смене статуса на `Closed` отправлять информацию о нём во внешнюю систему. Нечто подобное есть в [`OrderStatusChangeNotifier`](https://github.com/iiko/front.api.sdk/blob/master/sample/v8/Resto.Front.Api.SamplePlugin/OrderStatusChangeNotifier.cs).

Чуть более надёжно — реализовать `IChequeTaskProcessor` и отправлять данные во внешнюю систему непосредственно в процессе оплаты. Пример реализации этого интерфейса есть [тут](https://github.com/iiko/front.api.sdk/blob/master/sample/v8/Resto.Front.Api.SamplePlugin/ChequeTaskProcessor.cs), но там только дополнение чека, вам скорее будет полезен метод [`AfterDoCheckAction`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Devices_IChequeTaskProcessor_AfterDoCheckAction.htm).

Надо ещё учесть, что заказ сначала могут оплатить, а затем оплату могут отменить, поэтому надо предусмотреть выгрузку не только при оплате, но и при возврате (сторнировании).

Вы попробуйте, а если что-то не будет получаться или появятся более конкретные вопросы — постараемся помочь :-)
