### ISSUE TITLE
Внешний фискальный регистратор FiscalRegisterTaxItems 

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#48]
Коллеги, корректно ли прописать налоговые ставки 10/110 и 20/120 как показано ниже ?
Или есть какие-либо рекомендации ?
'''
 FiscalRegisterTaxItems = new List<FiscalRegisterTaxItem>
                {
                    new FiscalRegisterTaxItem("1", false, true, 20, "НДС 20%"),
                    new FiscalRegisterTaxItem("2", false, true, 10, "НДС 10%"),
                    new FiscalRegisterTaxItem("3", false, true, 0, "Без НДС"),
                    new FiscalRegisterTaxItem("4", false, true, 0, "НДС 0%"),
                    new FiscalRegisterTaxItem("5", false, true, (decimal)(20.0 / 120), "НДС 20/120"),
                    new FiscalRegisterTaxItem("6", false, true, (decimal)(10.0 / 110), "НДС 10/110")

'''

**Comment by fraddy91** [comment]
Добрый день,

Не корректно.
Вот основные принципы:
- Идентификатор налоговой ставки [первый параметр конструктора] должен соответствовать заводской настройке на оборудовании, то есть в вашем случае ставка с идентификатором "1" соответствует НДС 20%, с идентификатором "2" соответствует НДС 10% и т.д. Для большинства ККМ она числовая, поэтому строка может вызывать недоумение, но на практике у нас имеются экземпляры со строковыми идентификаторами "А", "Б"....

- Второй параметр IsTaxable обозначает что строка является налогооблагаемой, проставляется в true для всех ставок кроме "Без НДС".

- Третий параметр IsCalculated нужен для ставок, которые являются расчетными. То есть true передаётся для ставок 20/120, 18/118 и т.д.

- Четвертый параметр TaxPercent - процент налога. Для НДС 20, и НДС 20/120 передаётся 20, для 10 и 10/110 передаётся 10.

- Пятый параметр просто имя ставки, оно будет отображаться, например, в BackOffice и в других местах.

В вашем случае будет 
`new FiscalRegisterTaxItem("1", false, true, 20m, "НДС 20%"),`
`new FiscalRegisterTaxItem("2", false, true, 10m, "НДС 10%"),`
`new FiscalRegisterTaxItem("3", false, false, 0m, "Без НДС"),`
`new FiscalRegisterTaxItem("4", false, true, 0m, "НДС 0%"),`
`new FiscalRegisterTaxItem("5", true, true, 20m, "НДС 20/120"),`
`new FiscalRegisterTaxItem("6", true, true, 10m, "НДС 10/110")`


Правилом хорошего тона, при наличии возможности менять эти настройки в оборудовании, будет считывать эти налоговые ставки из ККМ и сохранить в настройки в момент запуска оборудования (IDevice.Start), открытия смены (ICashRegister.DoOpenSession), получении состояния девайса (IDevice.GetDeviceInfo), основываясь на поведении самого устройства. Например, если настройки НДС возможно изменить только при закрытой смене, достаточно будет считать их при запуске и открытии смены. Если настройки зашиты производителем и не меняются, то достаточно будет заводских.

**Comment by igorpooh1978** [comment]
Доброе утро
`                    new FiscalRegisterTaxItem("1", true, false, 20m, "НДС 20%"),
                    new FiscalRegisterTaxItem("2", true, false, 10m, "НДС 10%"),
                    new FiscalRegisterTaxItem("3", false, false, 0, "Без НДС"),
                    new FiscalRegisterTaxItem("4", true, false, 0, "НДС 0%"),
                    new FiscalRegisterTaxItem("5", true, true, 20, "НДС 20/120"),
                    new FiscalRegisterTaxItem("6", true, true, 10, "НДС 10/110")`

**Comment by fraddy91** [comment]
Абсолютно верно.

**Comment by igorpooh1978** [comment]
Спасибо за помощь
