### ISSUE TITLE
Событие на Возврат из закрытой кассовой смены

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#480]
Добрый день. Подскажите появилось ли какое ни будь **событие** на которое можно было бы отреагировать в плагине **при Возврате заказа из закрытой кассовой смены**?

Заказ был оплачен Наличными. а не своим типом оплаты.

**Comment by letolica** [comment]
Добрый день.
В Api V8 появилось событие.
https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_INotificationService_PastOrderStorned.htm
