### ISSUE TITLE
Возможно ли перенести Combo в другой заказ?

### ISSUE THREAD

**Issue by dn110779nag** [iiko/front.api.sdk#481]
Реализуем фичу разделения счета через плагин фронта.
Я понимаю, что можно удалить комбо , а затем создать новое в другом заказе. Но тут мы можем напороться на лимиты складов.
Есть ли какой-то аналог метода
https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_MoveOrderItemToAnotherOrder.htm
для комбо?

P. S. Пробовал через IEditSession.MoveOrderItemToAnotherOrder перенести все OrderItem из заказа, которые относятся к этому комбо в одной сессии получил ошибку

System.ArgumentException: Cannot break combo “Комбо ТЕСТ” (a0227de4-3cb4-49e3-bd97-4ae9c558a5be) by moving only part of its items to another order.

Server stack trace: 
   в Resto.CashServer.Services.OrderService.<SplitMovingItemsIntoComboGroups>d__79.MoveNext() в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:строка 0
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Resto.CashServer.Services.OrderService.MoveProductsToAnotherOrder(IBaseOrderBuilder orderBuilderFrom, IBaseOrderBuilder orderBuilderTo, IReadOnlyCollection`1 itemsToMove, IReadOnlyList`1 newGuests, IReadOnlyDictionary`2 cookingPlaceDictionary) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:строка 291
   в Resto.Front.Api.V7.Editors.Actions.MoveOrderItemToAnotherOrder.Apply(IRootOrderItemBuilder orderItem, IBaseOrderBuilder sourceOrder, IBaseOrderGuest destinationGuest, IBaseOrderBuilder order, SessionContext context) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Actions\MoveOrderItemToAnotherOrder.cs:строка 61
   в Resto.Front.Api.V7.Editors.Actions.MoveOrderItemToAnotherOrder.Resto.Front.Api.V7.Editors.IEditActionBase.WriteChanges(SessionContext context, IDictionary`2 createdEntities, IDictionary`2 actionNumbersToCreatedApiEntities, Int32 i) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\Editors.g.cs:строка 7754
   в Resto.Front.Api.V7.Editors.EditSessionWriter.WriteChanges() в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\EditSessionWriter.cs:строка 202
   в Resto.Front.Api.V7.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1965
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2473
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

**Comment by vcpp** [comment]
> Есть ли какой-то аналог метода [`MoveOrderItemToAnotherOrder`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_Editors_IEditSession_MoveOrderItemToAnotherOrder.htm) для комбо?

Пока нет, надо будет добавить. Внутренний номер задачи: RMS-55967.
