### ISSUE TITLE
Проблемы с производительностью

### ISSUE THREAD

**Issue by dn110779nag** [iiko/front.api.sdk#485]
Разрабатываем плагин для ресторанов. Уже подключено несколько сотен ресторанов. В ходе работы плагина используем в том числе методы

PluginContext.Operations.GetOrders()
PluginContext.Operations.GetOrderById(Guid id)

В большинстве ресторанов всё работает отлично, GetOrders() отрабатывает до 1 секунды, GetOrderById вообще 40-60мс. Но есть пару ресторанов, в которых GetOrders отрабатывает медленно, причем GetOrderById  отрабатывает те же 40-60 мс. 
А вот GetOrders  - с утра секунды 1,5, а к вечеру - доходит до 15 сек и больше.
В этих ресторанах плагин стоит на главной станции, к которой подключается 5-9 фронтов.

Что можно оптимизировать в данном случае? Что надо донастроить? или надо посмотреть в сторону апгрейда железа?
Есть какие-то рецепты?

**Comment by vcpp** [comment]
Причин может быть много.

В первую очередь, необходимо понимать, что метод `GetOrders`, возвращающий все имеющиеся в приложении заказы, имеет линейную зависимость от количества заказов. Если на передачу одного заказа требуется около 60 мс, то на 250 таких заказов потребуется 60х250=15000 мс. Во многих заведениях к вечеру действительно могут быть сотни заказов (в фастфудах — тысячи), но большинство из них, как правило, закрыты и не меняются. Чтобы плагин мог эффективно работать при большом количестве заказов, вместо многократного получения полного списка (`GetOrders`) рекомендуется запрашивать лишь те заказы, которые поменялись после предыдущего запроса ([`GetChangedOrders`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetChangedOrders.htm)). Это позволит избежать повторной передачи заказов, которые не менялись.

Скорее всего, переход на инкрементное чтение заказов решит проблему. Если же проблемы с производительностью `GetOrders` не связаны с накоплением заказов в течение дня, для диагностики понадобятся конфигурация, логи, настройки, справочники и пр. Для этого надо будет передать разработчикам API копию папки *CashServer*, скопированную с главного терминала в момент медленной работы (например, вечером перед закрытием кассовой смены). Эти данные могут содержать конфиденциальную информацию, поэтому их необходимо передать через техподдержку. Будет хорошо, если вы сможете воспроизвести проблему, подключив профилировщик (например, [dotTrace](https://www.jetbrains.com/profiler/)), и передать результат профилирования вместе с копией папки *CashServer*.
