### ISSUE TITLE
Уведомление о выборе типа оплаты в окне Платежи (Сохранённые оплаты) заказа доставки

### ISSUE THREAD

**Issue by D1splaced** [iiko/front.api.sdk#486]
Добрый день.
Нами написан плагин для внешней системы лояльности. Изначально он разрабатывался сугубо для обычных заказов. Окно плагина открывается или при нажатии на кнопку плагина, или при добавлении соответствующего типа оплаты (через метод `OnPaymentAdded`). В окне плагина указано количество доступных бонусов, и можно указать количество бонусов для списания.
Клиент хочет доработку, чтобы использовать плагин с заказами доставки.
Причём, насколько я понимаю, клиент хочет добавлять бонусы через окно Платежи, до перехода к окну Отправить (для доставки) или Закрыть (для самовывоза).
Кнопку плагина ни в окно редактирования заказа доставки, ни в окно Платежи добавить нельзя.
Метод `OnPaymentAdded` вызывается только после того, как ты выбираешь тип оплаты, указываешь сумму и нажимаешь Оплатить или Сохранить без оплаты. Это не очень интуитивно и требует много действий.
При этом при использовании оплаты IikoCard диалоговое окно для списания бонусов открывается в тот момент, когда ты выбираешь тип оплаты. 
Хотелось бы реализовать такой же функционал как у IikoCard, чтобы окно плагина открывалось сразу при выборе типа оплаты. Или, возможно, вы предложите какой-то альтернативный способ для удобного добавления оплаты бонусами в заказ доставки.

**Comment by vcpp** [comment]
> Кнопку плагина ни в окно редактирования заказа доставки, ни в окно Платежи добавить нельзя.

К сожалению, взаимодействие с экраном редактирования доставки пока не поддерживается. Об этом часто спрашивают (#345, #366), в одной из будущих версий такая возможность может быть реализована. Внутренний номер задачи для этой доработки: RMS-53534.

> Хотелось бы реализовать такой же функционал как у IikoCard, чтобы окно плагина открывалось сразу при выборе типа оплаты.

Да, это удобный и логичный вариант. Осталось реализовать его поддержку на стороне API. Как сделаем — напишем.
