### ISSUE TITLE
Внешний фискальный регистратор PrintText (печать нефискального текста)

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#49]
Добрый вечер.
Подскажите 
<barcode data="..."/>] - какие данные подразумевают поступать ? Только цифры ?
<qrcode size="..." correction="...">...text...</qrcode>
с переменной size - понятно. Что есть correction ? 
Спасибо.

**Comment by vcpp** [comment]
Вопрос про метод [`PrintText`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_PrintText.htm)? В него может приходить любой текст, например, какой-нибудь отчёт.

> с переменной size - понятно. Что есть correction ?

А можно контекст, откуда это? В `PrintText` такого нет.

**Comment by igorpooh1978** [comment]
Добрый день,

Прошу прощения забыл вставит
```
        /// <summary>
        /// Печать текстового (нефискального) чека, информационного, рекламного, пречек и т.д.
        /// Могут присутствовать следующие теги:<para />
        /// <![CDATA[<f0/>]]> - дальше будет шрифт 0<para />
        /// <![CDATA[<f1/>]]> - дальше будет шрифт 1<para />
        /// <![CDATA[<f2/>]]> - дальше будет шрифт 2<para />
        /// <![CDATA[<papercut/>]]> - отрез ленты<para />
        /// <![CDATA[<bell/>]]> - звонок<para />
        /// <![CDATA[<barcode data="..."/>]]> - штрихкод<para />
        /// <![CDATA[<logo data="..."/>]]> - логотип<para />
        /// <![CDATA[<qrcode size="..." correction="...">...text...</qrcode>]]> - QR-код<para />
        /// </summary>
        /// <param name="text">Текст для печати, строки разделены символом LF (\\n)</param>
        /// <param name="cashierId"></param>
        /// <param name="cashierName"></param>
```

Интересует         /// <![CDATA[<qrcode size="..." **correction**="...">...text...</qrcode>]]> - QR-код<para />

**Comment by vcpp** [comment]
Понял, вас интересует используемый в iiko язык описания разметки печатных форм. К сожалению, не нашёл этого описания в общем доступе, попросил занимающихся документацией коллег опубликовать.

Пока процитирую описание тэга qrcode:
> qrcode — форматирование вложенного текста как двумерный штрихкод (QR-код). Поддерживает только текст. Если устройство не поддерживает вывод штрихкодов, то данный тэг будет проигнорирован. Опциональны атрибуты размера `size` QR-кода и степени помехоустойчивости `correction`. Пример тега: `<qrcode size="normal" correction="medium"> http://www.iiko.ru/ </qrcode>`
Атрибуты:

| Название | Возможные значения | Назначение |
| ----------- | ------------------------- | -------------- |
| size | tiny, small, normal, large, extralarge | Размер QR-кода |
| correction | low, medium, high, ultra | Степень коррекции (помехоустойчивости). Для малого размера не следует указывать значения ultra/high, т.к. это может привести к ошибке распознавания QR-кода. |
