### ISSUE TITLE
Как отловить событие сканирования QR?

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#490]
Добрый день!
Для сканирования карты в плагине имплементировали следующий функционал.
1. В заказе установили кнокпку
2. После нажатия на кнопку пояляется диалоговое окно ввода данных 'Numeric Input'
3. Пользователь нажимает на поле ввода карты и сканирует карту.

Возможно ли узнать отсканированное значение без открытия диалога ввода?

**Comment by pro100roman24** [comment]
Подпишитесь просто на событие PluginContext.Notifications.OrderEditBarcodeScanned да и всё.
Туда будут приходить события сканирования qr кода.
