### ISSUE TITLE
IEditSession.MarkOrderAsAdditional() does nothing

### ISSUE THREAD

**Issue by evgenyvalavin** [iiko/front.api.sdk#491]
Configuration:
Front 8.7.6032
Front.API.V8

Проблема
IEditSession.MarkOrderAsAdditional(order, parentOrder, credentials) совершенно ничего не делает. Даже не генерит OrderChanged notification через Front API. [GroupOrderId ](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IOrder_GroupOrderId.htm) тоже null после выполнения метода.
IOperationSession.SubmitChanges() вызывается после IEditSession.MarkOrderAsAdditional();

Ожидается
IEditSession.MarkOrderAsAdditional(order, parentOrder, credentials) работает как описано [здесь](https://iiko.github.io/front.api.doc/2023/03/01/additional-order.html).

**Comment by evgenyvalavin** [comment]
@letolica привет!
Нашли проблему. Просим помощи

**Comment by evgenyvalavin** [comment]
Есть инфа что работает, коллеги проверяют

**Comment by vcpp** [comment]
Возможно, код либо не выполнялся, либо прервал выполнение из-за исключения. Встречается ли в *api.log* 
имя функции `MarkOrderAsAdditional` или запись вида `Submitting edit session`? Нет ли там рядом исключения?

**Comment by evgenyvalavin** [comment]
> Возможно, код либо не выполнялся, либо прервал выполнение из-за исключения. Встречается ли в _api.log_ имя функции `MarkOrderAsAdditional` или запись вида `Submitting edit session`? Нет ли там рядом исключения?

Точно! Есть же api.log. Спасибо!
Смогли понять в чем дело.
ParentOrderId это вообще не про Дозаказ. GroupOrderId - вот это про дозаказ.

Все работает по итогу.
