### ISSUE TITLE
Разливное пиво из iiko в ФР

### ISSUE THREAD

**Issue by ZakharovOpen** [iiko/front.api.sdk#492]
Добрый день.
Коллеги делаем плагин для разливного пива, сканировать марки будем в своих WPF.
Просим уточнить, какую именно информацию надо переда в позицию заказа в ChequeSale, чтобы данные о маркировке ушли в офд? 
Достаточно ли будет передать GTIN и CommodityCode или необходимо будет добавлять данные в Ffd12ChequeSaleData свойство позиции, если да, то какие?

Пробовали вот так подставлять значения.
![image](https://github.com/iiko/front.api.sdk/assets/88644943/087b3daa-bd16-44d4-84bd-75403c7ec740)
Формировался вот такой чек:
`{"CashPayment":200.00,"CashPayments":[{"Name":"Наличные","Sum":200.00,"PaymentRegisterId":"","IsDefaultNonCash":true,"Comment":null}],"CardPayments":[],"CreditSum":0.0,"ConsiderationSum":0.0,"RoundSum":0.0,"BillNumber":0,"OperationTime":"2024-02-02T15:08:39.0704189+03:00","OpenTime":"2024-02-02T15:08:16.7696589+03:00","IsOfdElectronicChequeOnly":false,"OfdPhoneNumber":"","OfdEmail":"","TaxationSystem":null,"SettlementAddress":null,"SettlementPlace":null,"CustomerDetailsInfo":null,"PrepaymentIds":[],"IsProductRefund":false,"AdditionalChequeAttribute":null,"IsPaymentTypeFastReplacement":false,"EInvoiceType":0,"IsRefund":false,"IsCancellation":false,"Sales":[{"Name":"Пиво Светлое","Code":"85625890000891250500","Price":200.00,"Amount":1.0,"GuestName":"Гость 1","Section":1,"Vat":7.0,"DiscountSum":0.0,"IncreaseSum":0.0,"Sum":200.00,"IsTaxable":true,"Comment":"","TaxId":"4","CommodityCode":null,"CommodityMark":"01046006820391052156uIcYK93V+JI","Discount":0.0,"Increase":0.0,"TransferType":4,"ItemCategory":"1","Contractor":null,"GtinCode":null,"ProductId":"ff9c2b6d-7dbe-4ee4-933e-bcdabbc8c6a7","TaricCode":"2203 00 090 0","Ffd12":{"MarkingCode":"01046006820391052156uIcYK93V+JI","Status":1,"IsFractionalAmount":null,"AmountNumerator":null,"AmountDenominator":null,"Unit":41},"KzChequeSaleData":null,"UkraineChequeSaleData":null,"UzChequeSaleData":null,"IsCalculated":false,"IsSplitVat":false}],"CancellingSaleNumber":0,"DiscountPercent":0.0,"IncreasePercent":0.0,"ResultSum":200.00,"DiscountSum":0.0,"IncreaseSum":0.0,"PrepaymentSum":0.0,"TableNumberLocalized":"Стол: 1 Заказ: 40","OrderId":"435a549e-604f-4a5c-ae03-fe3dd4ba357c","OrderNumber":40,"TableNumber":1,"PrintVat":true,"PrintArticle":false,"TextAfterCheque":{"Markup":null},"TextBeforeCheque":{"Markup":null},"Id":"b6439cb1-126a-4086-b912-ebd4ab8bd896","CashierName":"sa","CashierId":"b2cc5e53-b682-4d6a-a332-96330412d0a4","CashierTaxpayerId":""}`
но в ФОД данных нет по маркировке.

Так же пробовали проверять марку:
![image](https://github.com/iiko/front.api.sdk/assets/88644943/3d1dbb92-d015-4a4f-ba7f-2bd953ff03bf)
получали позицию для проверки:
`{"Name":"Пиво светлое ","Code":"85625890000891250511","Price":200.0,"Amount":1.0,"GuestName":"","Section":1,"Vat":0.0,"DiscountSum":0.0,"IncreaseSum":0.0,"Sum":200.0,"IsTaxable":false,"Comment":null,"TaxId":"","CommodityCode":null,"CommodityMark":"01046006820391052156uIcYK93V+JI","Discount":null,"Increase":null,"TransferType":4,"ItemCategory":null,"Contractor":null,"GtinCode":null,"ProductId":"00000000-0000-0000-0000-000000000000","TaricCode":"2203 00 090 0","Ffd12":{"MarkingCode":"01046006820391052156uIcYK93V+JI","Status":1,"IsFractionalAmount":null,"AmountNumerator":null,"AmountDenominator":null,"Unit":41},"KzChequeSaleData":null,"UkraineChequeSaleData":null,"UzChequeSaleData":null,"IsCalculated":false,"IsSplitVat":false}`
результат не выдал ошибку.
`{"IsOnlineValidationError":false,"OnlineValidationErrorDescription":"","ItemProcessCode":0,"MarkingCodeType":0,"MarkingParseResult":0,"LocalValidateResult":0,"OnlineValidateResult":5,"ItemStatusCode":0}`

**Comment by ZakharovOpen** [comment]
В итоге выяснили, методом проб, что сущность **ChequeTask** передаваем метод **BeforeDoCheckAction** является копией основной сущности , а не ссылкой и изменяя ее, мы ни как не влияем на основную сущность **ChequeTask** , передаваемую в ФР. 

Тестировали на: Версия iiko 8.7.6032.0 , SDK V8 (8.7.6032) и SDK V7 (7.9.6015)
ChequeTaskProcessor пробовали инициализировать со свойством IsPrimary равным true и false.

Код плагина:
![image](https://github.com/iiko/front.api.sdk/assets/88644943/56e410d9-92ed-42ec-96e6-92d979e0df7d)


Пример:
Добавили в заказ воду, отсканировали марку нативными средствами iiko.
Далее, в методе **BeforeDoCheckAction** вывели инф по чеку, видно, что есть маркировка воды:
![image_2024-02-05_20-53-19](https://github.com/iiko/front.api.sdk/assets/88644943/e1733021-0b43-4b34-8aef-a7c75b375e28)
После чего изменили позицию, подменив марку и категорию на пивные:
![image_2024-02-05_20-53-19 (2)](https://github.com/iiko/front.api.sdk/assets/88644943/242ec284-ae83-45ce-93fd-80dab7f6e638)
В результате в методе **AfterDoCheckAction** видим, что марка и категории вернулись обратно на данные по воде.
![image_2024-02-05_20-53-19 (3)](https://github.com/iiko/front.api.sdk/assets/88644943/8c2f1590-7a18-4cbd-8248-496e37c3ba6c)
Т.е. изменения не применились и в ФР отправилась изначальна инф о позиции заказа.

**Comment by ZakharovOpen** [comment]
вопрос снимается, проблема была в том. что из метода мы null возвращали, а надо было новую сущность Result и в нее передать измененные позиции
![image](https://github.com/iiko/front.api.sdk/assets/88644943/cc58010d-41fb-46ab-bf3c-86a593afe77a)

**Comment by vcpp** [comment]
> вопрос снимается

Хорошо, что удалось разобраться самостоятельно :-)
