### ISSUE TITLE
Карта приготовления блюд

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#493]
Добрый день.
Подскажите, возможно ли как-то получить Карту приготовления блюд через iikoFront APi?
![image](https://github.com/iiko/front.api.sdk/assets/59730103/f72eecb1-0772-4da4-ba66-27abc06322d7)

Интересует именно связка "Тип места приготовления" <> "Точка продажи"

Нужно для того, чтобы можно было понять по ТМП какие блюда при разделении на какой ФР будут отправлены.
Часто возникает потребность узнать эту информацию в момент печали пречека или даже раньше этого момента.
ТМП с api V8 получить можно, хотелось бы ещё иметь возможность вытащить карту приготовления.

**Comment by vcpp** [comment]
Увы, логика работы карты приготовления блюд довольно сложная, поэтому сами настройки не публикуются. Настройки задаются на уровне группы и переопределяются на уровне отделений, и там, и там можно задавать исключения для отдельно взятых блюд, и чтобы правильно определить место приготовления, надо знать и стол, на котором открыт заказ, и терминал, на котором выполняется операция.

Можно подумать о том, чтобы добавить сервисный метод, который для заданных условий определит соответствующую точку продажи. Нечто подобное уже реализовано в методе [`NeedToSplitOrderBeforePayment`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_NeedToSplitOrderBeforePayment.htm), который для заказа, оплата которого не предполагает разделения, возвращает возможную будущую точку продажи.

**Comment by pro100roman24** [comment]
Согласен, сама Карта приготовления блюд довольно сложна.
НО, я прошу лишь дать возможность получить связку именно "Тип места приготовления" <> "Точка продажи"
Что на каком отделении готовится не сильно интересует, это можно вытащить из свойства Kitchen в блюдах, в конкретном заказе.
Очень нужна именно соотношение ТМП и кассы, на которую этот ТМП назначен.
Эта настройка не переопределяется в отделениях, это вполне статичные данные и они не меняются от заказа к заказу.

Метод NeedToSplitOrderBeforePayment выполняет другую функцию, он лишь говорит нам о том, нужно ли делить чек.
Вот если бы этот метод возвращал бы конкретный список блюд, что на какую кассу пойдет при разделении, это было бы отлично. Например если от возвращал бы N количество списков с блюдами, по списку на каждую кассу.
Или если бы возвращал пары типа key / value где key это id блюда, а value - это id точки продаж, на которую блюдо пойдет при разделении, вот это бы решило проблему.

Я уже написал много плагинов для айко, и эта тема периодически всплывает, особенно в плагинах, завязанных на оплату, очень не хватает этого.

Пример 1:
Плагин для оплаты заказа по QR коду на столике, гость сканирует QR и есть потребность показать гостю:
"Сумма по ООО:"
"Сумма по ИП:"

Но не разделив чек на фронте мы не можем получить информацию какое блюдо куда пойдет.

Пример 2:
Плагин лояльности, оплата бонусами.
На пречеке плагин печатает:
"Итого можно оплатить бонусами 200р"
Потом заказ делится на 2 и официант не в курсе сколько бонусов из этих 200р можно кинуть в первый заказ, а сколько во второй, потому что сумма может быть поделена совсем по-разному.

Есть потребность прямо на пречеке печатать:
"Можно оплатить бонусами:
                                                 по ИП - 50р.
                                                по ООО - 150р"
                                                
 Сейчас приходится обходиться костылями, а именно прописывать в конфиге плагина какой ТМП на какой ФР будет закрыт, чтоб это работало, а потом в заказе проверять ТМП блюд.
 Спасибо что в апи V8 хотя бы добавили ТМП к продуктам, а на плагинах на V7 даже такой костыль не помогает.

**Comment by vcpp** [comment]
Добавили ['TryGetPointOfSaleByCookingPlaceType'](https://iiko.github.io/front.api.sdk/v9/html/M_Resto_Front_Api_IOperationService_TryGetPointOfSaleByCookingPlaceType.htm).
