### ISSUE TITLE
Получение структуры чека в iiko Front.

### ISSUE THREAD

**Issue by MiAlLevin** [iiko/front.api.sdk#494]
Добрый день!

Подскажите каким образом можно получить полную структуру напечатанного чека по заказу со всеми тегами(1212, 1214, 2108 и т.д.)?

Мы понимаем что можно получать раздельно информацию о ККТ (CashRegisterStatus) и информацию по чеку(BillTask, Sales и т.д.)
Но не понятно как разворачивать информацию по структуре чека - например ItemCategory (код признака предмета расчета, который соответствует позиции), согласно справочнику - соответствует тэгу 1212. Как вытащить всю структуру по уже напечатанному чеку. Где правильней перехватывать данное событие? 

Так же нигде не нашел упоминание где выдернуть 2108 (мера количества предмета расчета).

**Comment by rengal** [comment]
В Api V9Preview2 будет метод `PluginContext.Operation.GetDocumentFiscalTags`.
Метод читает полную структуру TLV из ФН по номеру фискального документа. Но нужно учесть, что срок хранения документа в ФН ограничен (но не могут быть менее сроков, указанных в ст. 4.1 54-ФЗ)

```csharp
/// <summary>
/// Read fiscal tags of the document from FN.
/// </summary>
/// <param name="credentials">
/// The credentials returned by <see cref="AuthenticateByPin" /> method.
/// </param>
/// <param name="cashRegister">
/// Cash register.
/// </param>
/// <param name="task">
/// Task containing information about the fiscal document number.
/// </param>
FiscalTagsResult GetDocumentFiscalTags(ICashRegisterInfo cashRegister, [NotNull] GetFiscalTagsTask task, [NotNull] ICredentials credentials);      
```
