### ISSUE TITLE
Ошибка "Cannot use cafe session"

### ISSUE THREAD

**Issue by pro100roman24** [iiko/front.api.sdk#495]
Добрый день, у нас плагин, работает на API V7
Плагин служит для удаленной оплаты заказов, со стороннего сервиса прилетает команда, плагин вносит оплату в заказ и закрывает заказ.
На версии iiko 8.4.6018.0 поймали ошибку при оплате заказа:
"Cannot use cafe session."

Не могу понять, что означает данная ошибка?

Ошибка в логе плагина:
[2024-02-08 14:39:20,220] ERROR [19] - Payment of order #13 (652ac46a-d0d7-4908-8bff-65e42538ce41) failed. Cannot use cafe session.

Такая же ошибка в api логе. В cash-server логе вообще ничего нет.

[plugin-PayOrder.log](https://github.com/iiko/front.api.sdk/files/14209250/plugin-PayOrder.log)
[api.log](https://github.com/iiko/front.api.sdk/files/14209252/api.log)
[cash-server.log](https://github.com/iiko/front.api.sdk/files/14209253/cash-server.log)

**Comment by vcpp** [comment]
> "Cannot use cafe session."
> Не могу понять, что означает данная ошибка?

Она означает, что кассовая смена закрыта. Сообщение об ошибке действительно непонятное, начиная с 8.5 будет нормальное сообщение вида «Кассовая смена закрыта».

> В cash-server логе вообще ничего нет.

Это лог с локальной кассы. В версиях API до V7 включительно оплата всегда выполняется дистанционно на кассе главного терминала, так что в таких случаях следует смотреть логи не только локального терминала, но и главного. Начиная с API V8 [добавлена](https://iiko.github.io/front.api.doc/2023/02/22/pay-order-local.html) возможность выбрать, оплачивать локально или дистанционно.
