### ISSUE TITLE
Тэг Tags.Pair не работает.

### ISSUE THREAD

**Issue by sin39rus** [iiko/front.api.sdk#497]
Добрый день. При формировании отчета для печати, строки с тэгом Tags.Pair полностью игнорируются (не печатаются). Пробовал в версиях V8, V8Preview5
```
       private void Print(IReceiptPrinter printer)
        {
            printer.Print(new ReceiptSlip
            {
                Doc = new XElement(Tags.Doc,
                    new XElement(Tags.Center, "Отчет"),
                    new XElement(Tags.Pair, "Test Printer", "123"),  //Напечатано не будет.
                    new XElement(Tags.Line))
            });
        }
```
Как альтернатива может быть использовать таблицу, но не хватает примера для Tags.Table.

**Comment by letolica** [comment]
Добрый день.
[Здесь](https://github.com/iiko/front.api.sdk/blob/a8bc794d517f798a2735145efc7974d902900b0c/sample/v8/Resto.Front.Api.SamplePlugin/Kitchen/PrintDocumentGenerator.cs#L24) есть пример работы как с тегом `pair`, так и с тегом `table`.

**Comment by sin39rus** [comment]
Спасибо, все заработало.
