### ISSUE TITLE
Добавление в заказ продукта с модификатором (через сессию)

### ISSUE THREAD

**Issue by avrezvanov** [iiko/front.api.sdk#5]
Необходимо добавить продукт к заказу, и эта задача работает отлично с товарами у которых нет модификаторов.
Как только встречается товар с модификатором, не важно каким (платным, бесплатным  и т.д. ..), плагин падает.
Есть понимание что такие продукты нужно добавлять сразу с модификаторами, добавлять нужно через сессию.
Но как это сделать до конца понимания нет. 
За ранее мне не известно есть ли у добавляемого продукта модификатор или нет.
Ниже пример кода который НЕ работает. На данный момент застрял на получении списка продуктов заказа из сессии. 

`
		/// <summary>
        /// Добавить продукт к заказу
        /// </summary>
        /// <param name="productId">Идентификатор добавляемого продукта</param>
        public static void AddProductToOrder(Guid productId)
        {
            try
            {
                //Получили необходимый заказ
                IOrder order = PluginContext.Operations.GetOrders().Where(x => x.Id == pOredrId).FirstOrDefault();

                //Выбрали продукт который необходимо добавить к заказу
                IProduct product = PluginContext.Operations.GetActiveProducts().Where(x => x.Id == productId).FirstOrDefault();
                
                //Открыли сессию
                var editSession = PluginContext.Operations.CreateEditSession();
                                
                //Добавли продукт к заказу
                var productItem = editSession.AddOrderProductItem(1, product, order, order.Guests.FirstOrDefault(), null, OrderItemCourse.Default, 0);                
                
                //Берем добавленный ранее продукт, но здесь его естественно нет                
                //Как получить список продуктов заказа из сессии, для дальнейшего добавления модификатора 
                var orderItem =  order.Items.OfType<IOrderProductItem>().Where(x=>x.Product.Id == productId).FirstOrDefault();

                //Берем его первый модификатор
                var groupModifier = orderItem.AvailableGroupModifiers.First();

                //Добавить модификатор к продукту 
                 editSession.AddOrderModifierItem(1, orderItem.Product, groupModifier.ProductGroup, order, orderItem,0);                                
                

                PluginContext.Operations.AddNotificationMessage("Товар добавлен в заказ.", "", new TimeSpan(0, 0, 5));
                
            }
            catch (Exception exp) {
                PluginContext.Operations.AddErrorMessage("Внимание ошибка!" + exp.Message, "");
                
            }
        }
`

**Comment by ierof** [comment]
По первых, вам нужно разобраться, что такое editSession. Вы ей неправильно пользуетесь. 
[В статье](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html) описано: 

> Сессия редактирования — это некое подобие транзакций в базах данных. Все действия, даже одиночные, выполняются в рамках сессий следующим образом:
> - Создаётся сессия IEditSession с помощью вызова PluginContext.Operations.CreateEditSession.
> - В рамках сессии выполняется одно или несколько действий.
> - Сделанные изменения сохраняются методом PluginContext.Operations.SubmitChanges.
>
> Сделанные на втором шаге изменения не видны до их успешного сохранения

Что из этого следует:  *Изменения в заказе не появятся, пока вы не вызовете `SubmitChanges`*

` var productItem = editSession.AddOrderProductItem(1, product, order, order.Guests.FirstOrDefault(), null, OrderItemCourse.Default, 0);`
а далее переменная `productItem` вами нигде не используется. А должна ;) Как раз к ней в рамках сессии и нужно добавлять модификаторы, а затем коммитить сессию

**Comment by avrezvanov** [comment]
@ierof  Вот любите вы всё загадками говорить.  
Если бы была достаточно подробно описанная документация, было бы всё намного проще. 
Из статьи я прекрасно понимаю зачем нужен SubmitChanges. 
И когда его делать. 
Вопрос в другом, как добавить товар с модификатором???? 

По поводу использования productItem у меня тоже были мысли, НО!!! Покажите место в документации где описан способ использования, методы  и т.д.  ? Возможно взгляд замылен, и я не вижу. 

Я пытаюсь добавить товар с модификатор больше месяца, прошу помощи, как разработчики расскажите как это делается.

**Comment by ierof** [comment]
> Вот любите Вы всё загадками говорить.

Мы любим говорить загадками, чтобы не сразу давать готовые куски кода, а давать направление для размышления. Идеи. Чтобы была мотивация как-то разбираться, а не бездумное *stackoverflow driven development* с копированием готовых фрагментов кода.

> Из статьи я прекрасно понимаю зачем нужен SubmitChanges.
И когда его делать.

Точно? :) Потому что в примере кода 
```
var productItem = editSession.AddOrderProductItem(1, product, order, order.Guests.FirstOrDefault(), null, OrderItemCourse.Default, 0);                
var orderItem =  order.Items.OfType<IOrderProductItem>().Where(x=>x.Product.Id == productId).FirstOrDefault();
```
вы сначала добавляете что-то в рамках сессии. Сессию пока не коммитете, а потом лезете в заказ, полученный ранее, и пытаетесь там найти тот продукт, добавление которого вы ещё не закоммитили. Т.е. в этот момент в заказе. У вас есть только "заглушка" этого продукта. 

Метод [`AddOrderModifierItem`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_Editors_IEditSession_AddOrderModifierItem_5.htm) описан в документации. Все поля снабжены комментариями.
А вы вызываете его вот так:
```
editSession.AddOrderModifierItem(1, orderItem.Product, groupModifier.ProductGroup, order, orderItem,0);
```
Я вижу ошибку во втором параметре – вы зачем-то передаете туда продукт текущего айтема, к которому добавляете модификатор. А по сигнатуре там должен быть продукт-модификатор. 
И ошибка в пятом параметре. Вы туда какой-то мифический `orderItem` передаете, хотя должен быть как раз полученный вами ранее `productItem`.
Т.е. допустим вы хотите добавить продукт "Блин" и модификатор к нему "Сметана" из группы "Добавки". Вторым параметром должна быть "Сметана", третьим "Добавки", а 5-м айтем заказа, который "Блин".

И ещё моя рекомендация: заводить issue не в стиле "[ваша программа не работает](https://bash.im/quote/268537)" ;) Вы приводите фрагмент кода, но не приводите конкретное исключение, которое у вас возникает. А в исключении скорее всего содержался бы ответ на вопрос: что именно у вас не работает. 
В вашем примере исключение у вас было бы либо NRE при обращении к `orderItem`-у, потому что его не нашлось в заказе, либо что-то подобное.

**Comment by avrezvanov** [comment]
Я тоже хочу во всём разобраться и я не сторонник копипастить, но когда документации очень мало и в ней не всё описано, трудно сделать что то хорошо, практически пальцем в небо приходится тыкать. 
Если я сделаю коммит, то сразу же получу ошибку. Потому как нельзя добавить в заказ продукт у которого есть обязательный модификатор.
> Я вижу ошибку во втором параметре 

Это уже мои изыскания, я пробовал всё подряд :) 

> Т.е. допустим вы хотите добавить продукт "Блин"

Не совсем так. 
Я хочу добавить в заказ продукт. У которого возможно есть модификатор, а может быть и нет. Но давайте упростим задачу. 
Я хочу добавить в заказ продукт у которого есть модификатор и он обязательный и количество минимум 1.

> var productItem = editSession.AddOrderProductItem(1, product, order, order.Guests.FirstOrDefault(), null, OrderItemCourse.Default, 0);                

Таким образом я добавляю продукт в заказ в рамках сессии.
У добавляемого продукта есть модификатор.
Если я сейчас сделаю коммит сессии, то получу ошибку, что нельзя добавить товар без модификатора. 
На основании чего я делаю вывод,  мне нужно получить модификатор который есть у добавленного продукта. 
С помощью каких методов это сделать в документации не описано. 
Думается мне, что я это могу сделать из **productItem** , но опять таки не знаю как, потому как в документации ни слова.

@ierof я реально хочу разобраться,  как всё это работает, но когда негде прочитать и спросить некого , очень сложно.

**Comment by ierof** [comment]
> С помощью каких методов это сделать в документации не описано.

Вот! Вот мы и добрались до сути вашего вопроса. Без лишней лирики. Суть вопроса в том, как узнать. какие модификаторы должны добавляться вместе с продуктом.

Метод [`IOrderProductItem.AvailableGroupModifiers`](https://iiko.github.io/front.api.sdk/v5/html/P_Resto_Front_Api_V5_Data_Orders_IOrderProductItem_AvailableGroupModifiers.htm) он для блюд, которые уже добавлены заказ. Это некий кэш, который позволяет быстро получить список всех модификаторов.
Но при добавлении нового продукта его модификаторы нужно также получать из номенклатуры.
Это методы [`IOperationService.GetSimpleModifiersByProduct(IProduct product)`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_GetSimpleModifiersByProduct.htm) и [`IOperationService.GetGroupModifiersByProduct(IProduct product)`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_GetGroupModifiersByProduct.html).

Т.е. в вашем случае это код
```
//Выбрали продукт который необходимо добавить к заказу
IProduct product = PluginContext.Operations.GetActiveProducts().Where(x => x.Id == productId).FirstOrDefault();
// хотя можно было так:
// IProduct product = PluginContext.Operations.GetActiveProducts().FirstOrDefault(x => x.Id == productId);
// или вот так:
// IProduct product =PluginContext.Operations.GetProductById(productId);

var simpleModifiers = PluginContext.Operations.GetSimpleModifiersByProduct(product);
// и по аналогии групповые модификаторы ...
```

Далее, чтобы понять, какие модификаторы из этих являются обязательными для продукта изучите свойства у:
- [`ISimpleModifier`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Assortment_ISimpleModifier.htm)
- [`IGroupModifier`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Assortment_IGroupModifier.htm) 
- [`IChildModifier`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Assortment_IChildModifier.htm)

У них у всех есть что-то с именем `MinimumAmount`. 

Возвращаясь к требованию начинать описание максимально по сути: если бы вопрос начинался с того, что вы попробовали добавить блюдо, у которого есть обязательные модификаторы, вам при показалось исключение с сообщением вроде
> `Order item modifier “моды” (3424f0ee-1528-4ec5-a297-a92b9db434dd) has invalid group amount: min = 1, max = 10, actual = 0. Ensure that interconnected product and modifier changes are in the same edit session.` 

И вы бы у нас более конкретно спросили, а где брать модификаторы для продукта обязательные модификаторы. И тут я согласна, что не самое понятное сообщение в исключении. Где-то фигурирует `Order item modifier` , где-то `product changes`. fyi @vcpp 
Чтобы его правильно интерпретировать, нужно знать, какие есть свойства у связанные модификаторов и продуктов. Что такое обязательные модификаторы, что такое групповые модификаторы и т.д. Это описано в хэпле по продукту iiko 
https://ru.iiko.help/articles/#!iikooffice-5-4/topic-3100
https://ru.iiko.help/articles/iikofront-5-4/topic-52

**Comment by ierof** [comment]
@avrezvanov, вы получили ответ на вопрос, который вас интересовал? Можно закрыть эту issue?

**Comment by avrezvanov** [comment]
@ierof Вот теперь картина стала проясняться. 
**Спасибо!**

В итоге получился такой код:

>      /// <summary>
        /// Добавить продукт к заказу
        /// </summary>
        /// <param name="productId">Идентификатор добавляемого продукта</param>
        public static void AddProductToOrder(Guid productId)
        {
            try
            {
                //Получили необходимый заказ               
                IOrder order = PluginContext.Operations.GetOrderById(pOredrId);
                //Выбрали продукт который необходимо добавить к заказу
                IProduct product = PluginContext.Operations.GetProductById(productId);  
                //Получили модификаторы добавленного продукта
                var simpleModifiers = PluginContext.Operations.GetSimpleModifiersByProduct(product);
                var groupModifier = PluginContext.Operations.GetGroupModifiersByProduct(product);    
                //Открыли сессию
                var editSession = PluginContext.Operations.CreateEditSession();           
                //Добавили продукт к заказу
                var productItem = editSession.AddOrderProductItem(1, product, order, order.Guests.FirstOrDefault(), null, OrderItemCourse.Default, 0);               
                //Если есть одиночные модификаторы
                simpleModifiers.ForEach(delegate(ISimpleModifier item) {
                    editSession.AddOrderModifierItem(1, item.Product, null, order, productItem, 0);
                });
                //Если есть групповые модификатор 
                groupModifier.ForEach(delegate(IGroupModifier item)
                {
                    item.Items.ForEach(delegate(IChildModifier itemChild)
                    {
                        editSession.AddOrderModifierItem(1, itemChild.Product, item.ProductGroup, order, productItem, 0);
                    });   
                });         
                PluginContext.Operations.AddNotificationMessage("Товар добавлен в заказ.", "", new TimeSpan(0, 0, 5));                
                var submitSeession = PluginContext.Operations.SubmitChanges(PluginContext.Operations.GetCredentials(), editSession);
                closeWindowDiscountCharge();
            }
            catch (Exception exp) {
                PluginContext.Operations.AddErrorMessage("Внимание ошибка!" + exp.Message, "");                
                closeWindowDiscountCharge();
            }
        }
> 

Если будут замечания и/или рекомендации по данному коду, с удовольствием готов выслушать.

**Comment by avrezvanov** [comment]
> Смотря что вы хотите :) 
Хочу не я, а заказчик.  На данный момент, было принято решение, если есть модификатор добавлять в кол-во 1 шт.  
Про что Вы говорите, я понимаю, заказчик тоже понимает. :)
Хотя я с Вами соглашусь, решение какое то не универсальное, и не очень красивое.
