### ISSUE TITLE
Методы внешней системы оплаты

### ISSUE THREAD

**Issue by VelizarGremori** [iiko/front.api.sdk#50]
Добрый день, возник вопрос связанный с работай iiko.Front

Когда конкретно происходит вызов методов IExternalPaymentProcessor'а EmergencyCancelPayment, OnPreliminaryPaymentEditing, ReturnPayment и Pay. На практике обнаружил, когда вызываются только последние два (ReturnPayment и Pay).

Спасибо

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor
