### ISSUE TITLE
Стоимость Комбо

### ISSUE THREAD

**Issue by skip59** [iiko/front.api.sdk#501]
Добрый день, подскажите пожалуйста. 

Добавляю комбо в заказ методом AddOrderCombo, но цена комбо выставляется равной не указанной в параметрах AddOrderCombo поля Price, а сумме цен блюд из комбо.
![combo](https://github.com/iiko/front.api.sdk/assets/121165542/4555d174-ce78-422a-9e71-8b74399801ac)

На скрине ниже, добавлено 2 комбо. Первый с помощью API, второй через UI фронта
![combo2](https://github.com/iiko/front.api.sdk/assets/121165542/e2363756-8b21-4d9d-a337-2b178e7840e2)

Комбо добавленное через API не встает цена заданная нами, а высчитывается из стоимости составных блюд, а комбо добавленное через UI подставляется в стоимость заказа именно стоимость самого комбо. 

Не получается разобраться почему цена комбо-блюда не учитывается в стоимости заказа при добвалении через API фронта.

**Comment by ierof** [comment]
Да, вы верно заметили, что цена всего комбо в этом случае выполняет декоративную функцию.
Этим методом `AddOrderCombo` сейчас можно добавить два типа комбо
- тесно интегрированные с iikoCard. Но для этого данные про эти комбо нужно узнавать не через API iikoFront, а через API iikoCard или внешние меню. Это не сфера поддержки команды API iikoFront
- декоративные комбо. Как в вашем примере. Они просто будут как некий именованный признак в составе заказа, но это не будет скидкой.

Манипуляции с ценой во втором случае нужно делать через параметр `predefinedPrice` у метода [`AddOrderProductItem`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Editors_IEditSession_AddOrderProductItem.htm). Но, обратите внимание, это будет модификация цены, а не скидка. 
В этом случае код будет примерно такой:
```
            var price1 = 50;
            var price2 = 75;
            var productItem1 = editSession.AddOrderProductItem(1, product1, order, guest, size, predefinedPrice: price1);
            var productItem2 = editSession.AddOrderProductItem(1, product2, order, guest, size, predefinedPrice: price2);
            var firstComboGroupId = Guid.NewGuid();
            var secondComboGroupId = Guid.NewGuid();
            var comboItems = new Dictionary<Guid, IOrderCookingItemStub>
            {
                { firstComboGroupId, productItem1 },
                { secondComboGroupId, productItem2}
            };
            var sourceActionId = Guid.NewGuid();
            var programId = Guid.NewGuid();
            var totalPrice = price1 + price2;
            editSession.AddOrderCombo(Guid.NewGuid(), "Случайное комбо", 1, totalPrice, sourceActionId, programId, comboItems, order, guest);
            os.SubmitChanges(editSession);
```
