### ISSUE TITLE
Закрытие заказа на фр, который установлен на ведомом терминале

### ISSUE THREAD

**Issue by Leo506** [iiko/front.api.sdk#503]
Есть главная касса, на которой установлен платежный плагин. Необходимо, в зависимости от типа оплат, закрывать заказ не на главной кассе, а на одной из ведомой. Есть ли такая возможность во фронтовом API? Нашел только как получить инфу о подключенных фискальниках

**Comment by ierof** [comment]
Вызывать с главной кассы операцию "Оплати заказ N на кассе M" нельзя. 
Но можно к примеру положить плагин на все кассы и сделать метод медплагинного взаимодействия "закрой заказ N", в котором будет оплата заказа на локальном терминале: [Оплата заказа на текущей кассе](https://iiko.github.io/front.api.doc/2023/02/22/pay-order-local.html)
