### ISSUE TITLE
PaymentsPlugin System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта

### ISSUE THREAD

**Issue by lallison21** [iiko/front.api.sdk#505]
При разработке плагина сторонней оплаты столкнулись со следующей ошибкой:

При сборки и размещении .dll файла в папку Plugins и при запуске iikoFront в логах нашего плагина выскакивает следующая ошибка
![image](https://github.com/iiko/front.api.sdk/assets/87948221/84a4ee23-e4ce-45d8-ab19-047dbc802f69)

В логах даже нету информации о запуске нашего плагина. То есть он даже не инициализирует его конструктор
![image](https://github.com/iiko/front.api.sdk/assets/87948221/7fefef4b-18ef-4a3e-b33a-afe1b6c08e0b)

**Comment by ierof** [comment]
```

[2024-04-17 11:20:22,376] INFO [1]
[2024-04-17 11:20:22,376] INFO [1]
Host process Resto. Front.Api.HitPaymentPlugin. V8 (10248) for "Resto. Front.Api.HitPaymentPlugin.HitPaymentPlugin" class from "C:\Program Files\iiko\iikoRMS\Front.Net\Plugins\Resto. Front.Api.HitPaymen
Plugin assembly info:
Resto. Front.Api.HitPaymentPlugin v1.0.0.0, (Resto. Front.Api.HitPaymentPlugin.dll v1.0.0.0, Resto. Front.Api.HitPaymentPlugin)
[2024-04-17 11:20:22,392] INFO [1] [2024-04-17 11:20:22,454] INFO [1]
Created plugin domain "Resto. Front.Api.HitPaymentPlugin.V8" using "C:\Program Files\iiko\iikoRMS\Front.Net\Resto. Front.Api.Host.exe.Config" Registering ipc channel... [2024-04-17 11:20:22,564] INFO [1] - Initialized as V8 plugin. [2024-04-17 11:20:22,618] INFO [1] Plugin context initialized, creating plugin instance... [2024-04-17 11:20:22,665] ERROR [1] - UnhandledException in host domain: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
Server stack trace:
-
B Resto. Front.Api.Host.VersionSpecificOperations.V8SpecificOperations.Resto. Front.Api.Host.VersionSpecificOperations. IVersionSpecific Implementation.InitializeCulture() в K:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto. B Resto. Front.Api.Host.VersionSpecificOperations. InitializePluginCulture() в K:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto. Front.Api.Host\VersionSpecificOperations.cs:Cтpoka 43 B Resto. Front.Api.Host.PluginRunner.Run(String assemblyPath, String className, String pluginName, Int32 moduleId, String serviceUri) B K: \BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto. Front.Api.Host\PluginRunner.cs: cтpo B System.Runtime.Remoting.Messaging. StackBuilderSink._PrivateProcessMessage (IntPtr md, Object[] args, Object server, Object[]& outArgs) B System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage (IMessage msg)
Exception rethrown at [0]:
B System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage (IMessage reqMsg, IMessage retMsg)
B System.Runtime.Remoting. Proxies. Real Proxy.PrivateInvoke(MessageData& msgData, Int32 type)
B Resto. Front.Api.Host.PluginRunner.Run(String assemblyPath, String className, String pluginName, Int32 moduleId, String serviceUri)
B Resto. Front.Api.Host. Program.Main(String[] args) в K:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto. Front.Api.Host\Program.cs:Cтpoka 40
[2024-04-17 11:20:24,852] INFO [1] - Unregistering ipc channel...
[2024-04-17 11:20:24,852] INFO [1] - Unloading plugin domain...
```
1. Какая версия iiko?
2. SDK получен из nuget https://www.nuget.org/packages/Resto.Front.Api.V8 ? 
3. В том, что вы подкладываете в папку `Plugins` нет ли случайно `Resto.Front.Api.V8.dll`? Не должно быть

**Comment by lallison21** [comment]
1. Если вы говорите про версию iikoFront, то она у нас версии 8.5.8002
2. SDK да, мы получали из nuget. Версия SDK у нас 8.7.6032
3. Да, в папку Plugins мы закидываем файл Resto.Front.Api.V8.dll. Так как
при сборке v6 версии, без  Resto.Front.Api.V6.dll он не запускается. Мы по
аналогии с 6 версией, которая нормально запускается, собираем и 8 версию,
но безуспешно 8 версия нивкакую не хочет работать

ср, 24 апр. 2024 г. в 12:07, Irina Erofeeva ***@***.***>:

**Comment by ierof** [comment]
Класть dll более свежей версии API в папку с плагином бесполезно :) API V8 из nuget будет работать на iiko 8.7.6032 и более новых.
На 8.5.8002 будет работать [V8Preview6](https://www.nuget.org/packages/Resto.Front.Api.V8Preview6/8.5.5017-alpha) и [V8Preview4](https://www.nuget.org/packages/Resto.Front.Api.V8Preview5/8.4.6018-alpha).
См. https://iiko.github.io/front.api.doc/versioning.html -- тут описано, какие версии API на какой версии iiko работают. 
Если вам нужна именно V8.dll, то скомпилируйте на той же версии, что iikoFront. Но по функциональному V8 из  8.5.8002 это [V8Preview6](https://iiko.github.io/front.api.doc/tag/v8preview6).

И dll API не нужно подкладывать в папку плагина, она резолвится из корневой папки iikoFront.
