### ISSUE TITLE
Как открыть Денежный ящик через команду для Принтера

### ISSUE THREAD

**Issue by andreidigori** [iiko/front.api.sdk#507]
Есть такая задача - открыть Денежный ящик через команду для Принтера, так как ФР не существует уже.

Нашел команду/тег "bell" но не уверен если заработает...

Есть тег именно для этого?

**Comment by vkotelevskiy** [comment]
Добрый день!
Так как интересующая Вас версия API не указана - отвечу в общем случае.
Отправить команду на открытие денежного ящика можно двумя способами
1. Сформировать и отправить на печать документ с единственным тегом pulse.
Документ с командой имеет вид:
` Doc = new XElement(Tags.Doc, new XElement("pulse"));`
Затем, отправить сформированный документ на печать, например:
`var printer = PluginContext.Operations.TryGetReceiptChequePrinter();
PluginContext.Operations.Print(printer, doc);`
2. Воспользоваться уже имеющимся методом OpenCashDrawer в IOperationService
`var printer = PluginContext.Operations.TryGetReceiptChequePrinter();
PluginContext.Operations.OpenCashDrawer(printer);`
