### ISSUE TITLE
Последовательность не содержит соответствующий элемент

### ISSUE THREAD

**Issue by Monnero** [iiko/front.api.sdk#509]
При вызове `printer.Print()` в методе `Pay ` выбрасывает следующую ошибку:

![image](https://github.com/iiko/front.api.sdk/assets/34159774/19087bba-8f62-40ee-8b5d-1a6a21a74616)

В iikoOffice принтер добавили

![image](https://github.com/iiko/front.api.sdk/assets/34159774/3e155e67-d227-4e71-a168-ea18d5946bc7)

На кассовый терминал также добавили

![image](https://github.com/iiko/front.api.sdk/assets/34159774/13ad4704-69e6-46d7-8035-2cc975e6588b)

На кассовом терминале принтер появился, работает

![image](https://github.com/iiko/front.api.sdk/assets/34159774/20c094fc-f7ac-49f7-aa5e-f2e49e81bb9b)

Вызов того же  `printer.Print()` в методе `PaySilently` ошибку не вызывает.
Как исправить эту ошибку и вызвать `printer.Print()` в методе `Pay `?

**Comment by ierof** [comment]
Приложите пожалуйста логи из `%appdata%\iiko\CashServer\Logs\`:
1. Вашего плагина
2. api.log
3. cash-server.log

Потому что скрин это ошибка в платежной системе, но не факт, что связанная с методом `printer.Print()`

**Comment by Monnero** [comment]
[plugin-Resto.Front.Api.HitPaymentPlugin.V8.log](https://github.com/iiko/front.api.sdk/files/15332353/plugin-Resto.Front.Api.HitPaymentPlugin.V8.log)
[api.log](https://github.com/iiko/front.api.sdk/files/15332349/api.log)
[cash-server.log](https://github.com/iiko/front.api.sdk/files/15332336/cash-server.log)

**Comment by ierof** [comment]
Это наш баг в ядре, появился в версии 8.5.6, исправлен в 8.7.7
Так что рекомендация тут -- обновиться на 8.7.7 и новее.
