### ISSUE TITLE
Свойство CashRegisterDriverParameters.IsCancellationSupported

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#51]
Добрый день.

Как влияет значение свойства `CashRegisterDriverParameters.IsCancellationSupported` на взаимодействие фронта и кассы? Вызывается какая-то команда?

**Comment by vcpp** [comment]
Если я правильно понимаю, эта настройка актуальна для стран (Беларусь, Латвия), где отмена продажи может быть привязана к самой продаже по номеру.

Если касса поддерживает операцию аннулирования, у кассира будет выбор — выполнить аннулирование или сторнирование, а иначе будет доступно только сторнирование. Аннулировать можно только продажу целиком, сторнирование может быть ещё и попозиционным. При аннулировании плагин получит команду `BillTask` с флагом `IsCancellation = true` и номером продажи, которую нужно отменить (`CancellingSaleNumber`). При сторнировании `IsCancellation = false`, номер продажи не определён (фактически 0).

**Comment by bildeyko** [comment]
Понял, спасибо. Для нас пока не актуально .
