### ISSUE TITLE
получение ICashRegisterInfo в плагине  

### ISSUE THREAD

**Issue by Monnero** [iiko/front.api.sdk#511]
Нам необходимо создавать отчет при закрытии смены, для этого в методе `CafeSessionClosing ` мы вызываем `PluginContext.Operations.GetReportMarkupById`, но у него в параметрах ICashRegisterInfo, который не ясно откуда получить. Подскажите, как получить ICashRegisterInfo?

**Comment by vkotelevskiy** [comment]
Добрый день! 
Чтобы получить интересующий Вас объект, необходимо выбрать конкретную точку продаж, а затем обратиться к ее кассовому аппарату. Сделать это можно, например, так:
`var cashRegister = PluginContext.Operations.GetHostTerminalPointsOfSale().FirstOrDefault()?.CashRegister;`
