### ISSUE TITLE
После обновления на версию айко 8.8.8 получаем исключение при попытке оплатить заказ который содержит маркированную позицию с отложенным сканированием

### ISSUE THREAD

**Issue by badDev1337** [iiko/front.api.sdk#514]
Добрый день.
После обновления с версии 8.1.7 на версию 8.8.8 стали получать исключение при попытке оплатить заказ(оплата происходит с помощью метода OperationService.PayOrder) который содержит маркированную позицию с возможностью отложенного сканирования. 
Текущая версия плагина работает на api v7. Пробовал перевести плагин на api v8, не помогло, немного поменялось сообщение из исключения, но смысл тот же.
Ошибка на v8:
Resto.Front.Api.Exceptions.PaymentActionFailedException: Payment of order #2298 (0960fac9-30b9-4bfb-96ef-6a5fbe8f661d) failed.
Ошибка на v7:
 Payment of order #40 (561ced12-0140-451f-b9e0-1b1fa3652f1a) failed. Reason: OrderBillOperationFailed. Details: Cannot print bill cheque for order #40 (561ced12-0140-451f-b9e0-1b1fa3652f1a) with unmarked items Бона Аква 0,5 бут. (5f2d81f8-c28b-40ff-9830-8b4c1a7aa57a).
Если необходимо предоставлю полные логи.

Смысл ошибки понятен, мы пытаемся оплатить заказ содержащий маркированную продукцию без сканирования марки ЧЗ.
Но у данной позиции настроено отложенное сканирование, и соответственно, если ее пробивать на фронте, то в диалоговом окне сканирования марки, можно выбрать нет и не сканировать ее.
Вопрос как тогда нам перенести аналогичное поведение на плагин. Единственное, что я нашел это интерфейс IOuterEconomicActivityNomenclatureCode, который предоставляет информацию о маркировке, но как его применить мне пока непонятно. Пытался использовать метод ChangeOrderItemMarkingCode передав во входящий параметр метода в значении марки null, но тогда метод падает в исключение(кстати у вас указано в описании данного метода ,параметр mark помечен атрибутом[not null], но в описании самого метода указано "Specifies the new value for the marking code. **_Set to Null to reset the marking code._**"). Подскажите пожалуйста какой метод нужно использовать, чтобы фронт разрешил пропустить сканирование марки, в данной ситуации.

**Comment by rgalk** [comment]
Добрый день.
К сожалению, в Front API отсутствует возможность пропустить сканирование марки по инициативе плагина. Эту несправедливость устраним в одной из очередных версий Front API. Внутренний номер задачи приложу немного позднее.
Расскажите немного подробнее о решаемом вами сценарии, чтобы мы могли точнее реализовать желаемое.

> Пытался использовать метод ChangeOrderItemMarkingCode передав во входящий параметр метода в значении марки null, но тогда метод падает в исключение

Какое исключение вы получаете? Можете приложить stacktrace?

> в описании самого метода указано "Specifies the new value for the marking code. Set to Null

Исправим. Спасибо за внимательность.

**Comment by badDev1337** [comment]
> Добрый день. К сожалению, в Front API отсутствует возможность пропустить сканирование марки по инициативе плагина. Эту несправедливость устраним в одной из очередных версий Front API. Внутренний номер задачи приложу немного позднее. Расскажите немного подробнее о решаемом вами сценарии, чтобы мы могли точнее реализовать желаемое.

Добрый день, у нас киоск самообслуживания, соответсвенно на текущий момент возникла проблема с продажей воды, так как гость оформляя заказ на киоске на руках еще бутылки с водой не имеет, чтобы даже чисто теоретически произвести сканирование.

> Какое исключение вы получаете? Можете приложить stacktrace?
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: ChangeOrderItemMarkingCode.MarkingCode

Server stack trace: 
   в Resto.Front.Api.V8.Editors.Actions.ChangeOrderItemMarkingCode.Resto.Front.Api.V8.Editors.IEditActionBase.PreCheckArguments(SessionContext context) в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\Editors\Editors.g.cs:строка 9763
   в Resto.Front.Api.V8.Editors.EditSessionWriter.PreCheckActions() в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\Editors\Editors.g.cs:строка 12612
   в Resto.Front.Api.V8.Editors.EditSessionWriter.PreCheckEditSession() в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\Editors\EditSessionWriter.cs:строка 52
   в Resto.Front.Api.V8.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\OperationServiceInternal.cs:строка 2190
   в Resto.Front.Api.V8.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(IEditSession editSession, ICredentials credentials) в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V8\Operations.g.cs:строка 2910
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.SubmitChanges(IEditSession editSession, ICredentials credentials)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.SubmitChanges(IEditSession editSession, ICredentials credentials) в G:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V8\OperationsInterfaces.g.cs:строка 6178

**Comment by rgalk** [comment]
> System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: ChangeOrderItemMarkingCode.MarkingCode

Спасибо, это еще один баг.

**Comment by rgalk** [comment]
Сформированы задачи с внутренними номерами: RMS-56801, RMS-54323 и RMS-56802. Напишу отдельно когда задачи будут решены.

**Comment by letolica** [comment]
Добрый день.
Задачи
RMS-56802 Front.Api: Метод ChangeOrderItemMarkingCode не принимает аргумент null
RMS-56801 Front.Api: Возможность пропускать сканирование марки в API
сделаны и будут доступны начиная с версии RMS 9.0.5 и Front.Api V9Preview3.
Чуть позже будет новость в https://iiko.github.io/front.api.doc/changelog.html
