### ISSUE TITLE
Описание полей заказа из IikoFrontApi

### ISSUE THREAD

**Issue by lallison21** [iiko/front.api.sdk#515]
Мы получаем заказы из IikoFront за смену по следующему URL (http://127.0.0.1:9042/api/orders), но какие поля что значат не нашли в документации. Подскажите пожалуйста, какое поле что означает

**Comment by ierof** [comment]
Имена переменных в облегченном Web-API совпадает с SDK-API: https://iiko.github.io/front.api.sdk/v8/html/Properties_T_Resto_Front_Api_Data_Orders_IOrder.htm
