### ISSUE TITLE
Вопрос по методу PaymentProcessor.ReturnPaymentSilently

### ISSUE THREAD

**Issue by Leo506** [iiko/front.api.sdk#518]
В API V8 в `PaymentProcessor ` появился новый метода `ReturnPaymentSilently`. В каких случаях вызывается данный метод?

**Comment by GulnaraBikbova** [comment]
Начиная с API V8PreviewV7 появилась возможность [возвращать проведенные платежи и предоплаты](https://iiko.github.io/front.api.doc/2023/07/17/unprocess-payment.html).

`ReturnPaymentSilently()` вызывается при сторнировании оплаты\предоплаты, в случае если `CanPaySilently()` вернет для него `true`. 

О silent-оплатах можно ознакомится [здесь](https://rgalk.github.io/front.api.doc/v6/ru/PaymentProcessor.html).

**Comment by GulnaraBikbova** [comment]
В [статье об оплатах](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html) есть упоминание об этом:

> В зависимости от ответа возвращаемого значения метода [CanPaySilently](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_CanPaySilently.htm) iikoFront вызовет Pay или PaySilently метод процессора плагина.

C `ReturnPayment` и `ReturnPaymentSilently` точно также.
Дополним [статью об оплатах](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html), чтобы не возникало вопросов.
