### ISSUE TITLE
Отсутствует реализация метода "get_BeforeProceedOrderPayment" в типе "Resto.Front.Api.V9Preview1.NotificationService" 

### ISSUE THREAD

**Issue by kolan72** [iiko/front.api.sdk#519]
Добрый день,

Пытались адаптировать плагин для своей системы лояльности лояльности под Resto.Front.Api.V9Preview1 (ранее был настроен на более старый пакет).

Получили в логе плагина (скрин):

![image](https://github.com/iiko/front.api.sdk/assets/6088210/e3d6c25a-3ba0-4800-937e-ef72cb434bf6)

Т.е. плагин загружается, но валится с ошибкой отсутствия реализации метода API. 

Заполнение ключевых узлов в файле Manifest.xml 
```
<ApiVersion>V9Preview1</ApiVersion>
<RestartOnCrash>true</RestartOnCrash>
```

Можете подсказать решение проблемы?

**Comment by kolan72** [comment]
Версия фронта  8.9.3011

Лог плагина:

[plugin.log](https://github.com/user-attachments/files/16163822/plugin.log)

**Comment by rgalk** [comment]
Добрый день!

В перевыпущенной версии Front API вместе с выпуском 8.8.9 появился новый метод-нотификация. Как раз на него и ссылается исключение из скриншота, который вы приложили, именно этого метода не хватает в сборке iiko 8.9.3. Хронологически так получилось, что версия 8.8.9 вышла позднее версии 8.9.3. В версии 8.8.9 API получило новый метод, а все выпущенные ранее, т. е. 8.9.1–8.9.4  — нет, поэтому обновление плагина с API V9Preview1 версии 8.8.9 возможно только на версию 8.9.5, где упомянутый выше метод тоже доступен.
В качестве WA можно откатить версию API обратно до пакета версии 8.8.5 либо обновиться на 8.9.5, тогда плагин будет получать недостающий метод.

_Прикладывайте вырезку из лога в текстовом виде, так текст и ошибка будут доступны для поиска. Тогда другие коллеги, кто тоже натолкнется на данную проблему, смогут ознакомиться с информацией._
