### ISSUE TITLE
ФР чек коррекции CorrectionDocumentType

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#52]
Добрый день

Подскажите, почему при выборе Операции "Коррекция рассхода" 
![изображение](https://user-images.githubusercontent.com/47010778/59973822-36a25580-95ad-11e9-8091-dd01301d7199.png)
в CorrectionDocumentType возвращается значение 3, которое не описано
```
namespace Resto.Front.Api.V6Preview4.Data.Device.Tasks
{
    //
    // Summary:
    //     Correction document type.
    public enum CorrectionDocumentType
    {
        //
        // Summary:
        //     Income correction.
        Sale = 0,
        //
        // Summary:
        //     Expense correction.
        Buy = 1
    }
}
```

**Comment by ierof** [comment]
Да, это Баг в iiko.
Уже исправлен в текущих бета-версиях 6.4

**Comment by igorpooh1978** [comment]
Я тестировался на 6.4

**Comment by ierof** [comment]
Официального релиза 6.4 ещё не было. он будет ориентировочно 1 июля.
Судя по номеру на вашем скриншоте, у вас какая-то ранняя версия. 

Сейчас идёт стабилизация и бета-тест версии 6.4, есть более стабильные превью.
