### ISSUE TITLE
API не проверяет права F_CASH и F_APIO при оплате заказа

### ISSUE THREAD

**Issue by Leo506** [iiko/front.api.sdk#522]
Добрый день.

Обнаружили, что API (V7, V8) позволяет выполнить операцию оплаты (`PayOrder`, `PayOrderAndPayOutOnUser`) даже если у пользователя нет на это прав (F_CASH и F_APIO)

**Comment by GulnaraBikbova** [comment]
Добрый день.
`PayOrderAndPayOutOnUser` - расчет официанту. Необходимые права: F_PAW или (F_CASH и F_APIO).
`PayOrder` - оплата заказа, в котором достаточно внесенных денежных средств. Необходимые права: F_PAW или F_CASH.

В [статье](https://ru.iiko.help/articles/#!iikofront-8-9/topic-43) описаны права доступа для оплатных действий, также, [документация api](https://iiko.github.io/front.api.doc/v6/ru/Payments.html).

`PayOrderAndPayOutOnUser` - расчет официанту. Необходимые права: F_PAW или (F_CASH и F_APIO).
`PayOrder` - оплата заказа, в котором достаточно внесенных денежных средств. Необходимые права: F_PAW или F_CASH.

**Comment by Leo506** [comment]
Спасибо за ответ
