### ISSUE TITLE
При отключенном размере блюда дает добавить его в заказ

### ISSUE THREAD

**Issue by gucciamg** [iiko/front.api.sdk#523]
Добрый день.

Столкнулись с такой проблемой. У блюда отключен один размер (через приказ), при этом в вейтере этот размер **дает** выбрать.
При сохранении такого заказа выходит ошибка, что размер исключен для продажи для данного стола.
На фронте этот размер выбрать нельзя. 

Как мы можем обрабатывать такие кейсы?

**Comment by letolica** [comment]
Добрый день.
К сожалению, пока никак не удастся обрабатывать такие кейсы. Но мы завели задачу с внутренним номером RMS-57158. Постараемся сделать.

**Comment by letolica** [comment]
Закрою заявку. Как сделаем, оповестим тут.

**Comment by letolica** [comment]
Добрый вечер. Готово.
[Возможность узнать, что блюдо в конкретном размере доступно к продаже](https://iiko.github.io/front.api.doc/2024/09/09/get-included-in-menu.html).

**Comment by letolica** [comment]
#286
