### ISSUE TITLE
MoveOrderItemToAnotherOrder throws Resto.Front.Api.Exceptions.ConstraintViolationException: Estimated guests count is less than added guests count

### ISSUE THREAD

**Issue by Leo506** [iiko/front.api.sdk#524]
Добрый день.

После обновления iiko до версии 8.9.6026 метод на перемещение блюда из одного заказа в другой (`MoveOrderItemToAnotherOrder`) начал выдавать ошибку "`Resto.Front.Api.Exceptions.ConstraintViolationException: Estimated guests count is less than added guests count`". На версии 8.8.9 работало без ошибок

Что делали?
1. Создать новый заказ через API (EstimatedGuestsCount использовали 0, 1 и 100)
2. Добавить в новый заказ гостя, в которого будет происходить перенос (через API)
3. Удалить автоматически созданного гостя (через API)
4. Вызвать метод переноса позиции

Заказ, из которого происходил перенос, состоял из нескольких гостей и блюд.
Через UI iikoFront перенос работает корректно

**Comment by TRudaya** [comment]
Доброго времени суток, 
1. можно подробнее вызовы которые были сделаны, можно в рамках пунктов?
2. есть ли simple guest deletion модуль?
3. банкет или обычный заказ?

**Comment by amilchak** [comment]
Если есть модуль simple guest deletion, то это известная проблема - будет решена в 8.9.7.

**Comment by Leo506** [comment]
@amilchak что это за модуль такой "simple guest deletion"? Можно ли его как-то отключить?
@TRudaya создали небольшой проект плагина, который вызывает перенос блюд: https://github.com/Leo506/MoveOrderItemsIssue
Как воспроизвести проблему:
1. Создали заказ
![image](https://github.com/user-attachments/assets/bb69d30b-216f-4f2b-babf-a0dcad1801b8)
2. Нажали на кнопку переноса(Move Order Items test). Перенос происходит на дефолтный стол
3. Получаем ошибку 
![image](https://github.com/user-attachments/assets/29ad9b75-9362-4182-8c62-bdfb413f9594)

**Comment by amilchak** [comment]
@Leo506 как мне стало известно, отключить simple guest deletion не получится. Ваша проблема действительно в этой лицензии и она будет исправлена в 8.9.7. На текущий момент, не дожидаясь новой версии, могу посоветовать только увеличивать EstimatedGuestsCount самим, на число перенесенных гостей, сразу после переноса (в этой же сессии). К сожалению, не всегда очевидно сколько гостей будет перенесено и вам придется посчитать это самим - в вашем простом примере это 1: я добавил такую строчку чтобы перенос корректно заработал. 
<img width="829" alt="image" src="https://github.com/user-attachments/assets/f4820af8-1ff7-4666-a9ae-ab8f92a99da5">
Так же в качестве хитрости, можно увеличивать EstimatedGuestsCount значительно, а потом, уже в другой сессии, снижать его до количества гостей в заказе (правда такая логика не всегда приемлема)

**Comment by Leo506** [comment]
Спасибо за ответ
