### ISSUE TITLE
Запрос на получение IViewManager при переходе на IOrderEditScreen

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#526]
Здравствуйте!

У меня есть кастомное окно, которое открывается поверх экрана iikoFront и отображается исключительно на странице редактирования заказа. В этом окне присутствует поле ввода, и мне хотелось бы использовать метод viewManager.ShowKeyboard() для ввода данных.

Однако в текущей реализации я не имею возможности получить экземпляр ViewManager, необходимый для этого метода.

**Comment by igorpooh1978** [comment]
Добрый день.
Можете если работаете через AddButtonToOrderEditScreen пробросьте IViewManager в своё окно и пользуйтесь
Если ScreenChanged - нет

**Comment by Keeplod** [comment]
К сожалению, через него не работаем(

**Comment by letolica** [comment]
Здравствуйте.
https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html

> На время выполнения callback’а показывается прогрессбар. В callback будут переданы текущий заказ, локальная версия [IOperationService](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_IOperationService.htm) для редактирования текущего заказа, а также [IViewManager](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_UI_IViewManager.htm) с возможностью показывать диалоговые окна и [менять текст](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ChangeProgressBarMessage.htm) на прогрессбаре.
