### ISSUE TITLE
GetProductsRemainingAmounts() хотелось бы получить не только остаток блюд, но и время добавления в стоп-лист.

### ISSUE THREAD

**Issue by Keeplod** [iiko/front.api.sdk#529]
https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetProductsRemainingAmounts.htm
Если зайти в стоп-лист через UI iikoFront там будет время добавления, а в запросе GetProductsRemainingAmounts, оно к сожалению отсутсвует.

**Comment by letolica** [comment]
Здравствуйте.
[Доступны дата и время добавления блюда в стоп-лист](https://iiko.github.io/front.api.doc/2024/10/01/stop-list-item-operation-date.html).
