### ISSUE TITLE
В какой версии появилось свойство CashRegisterResult.Success?

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#53]
Добрый день
В документации увидел свойство CashRegisterResult.Success. Я правильно понимаю, что оно появится в версии 6.4?

**Comment by vcpp** [comment]
В самом `CashRegisterResult` нет свойства [`Success`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Results_PostResult_Success.htm), оно унаследовано из базового класса `PostResult`.

Вся эта функциональность по работе с оборудованием появилась в версии API V6, которая зарелизится в iikoRms 7.0. В iikoRms 6.4 этим можно начать пользоваться в рамках API V6Preview5 (информация о preview-версиях вот-вот появится [тут](https://iiko.github.io/front.api.doc/versioning.html)).
