### ISSUE TITLE
Возможность работать с асинхронными методами в sdk iiko front

### ISSUE THREAD

**Issue by sudolover** [iiko/front.api.sdk#530]
Добрый день.

Уже несколько раз сталкивался с тем, что в некоторых методах и коллбеках кнопок, нотификаций не получается корректно работать с асинхронным кодом.

В частности точно помню про Payment processor, коллбеки нотификаций, в которые проброшен IViewManager, IOperationService.

Для примера сейчас опишу сценарий из AddButtonToOrderEditScreen.

Коллбек кнопки добавленной на экран редактирования заказа
```
        private async void OrderEditScreenButtonCallback((IOrder order, IOperationService os, IViewManager vm) tuple)
        {
            try
            {
                tuple.os.AddNotificationMessage("Before await", nameof(OrderEditScreenButtonCallback)); 
                await TaskAsyncExample();
                tuple.os.AddNotificationMessage("After await", nameof(OrderEditScreenButtonCallback));
            }
            catch (Exception ex)
            {
                PluginLogger.Error(nameof(ButtonsHandler), $"Got exception in {nameof(OrderEditScreenButtonCallback)}", ex);
            }
        }
```

Некий асинхронный метод
```
        private async Task TaskAsyncExample()
        {
            await Task.Delay(TimeSpan.FromSeconds(5));
        }
```

 tuple.os.AddNotificationMessage("Before await", nameof(OrderEditScreenButtonCallback));  До ожидания асинхронного метода, все ок, доступ к IOperationService и ко всему кортежу есть.

  tuple.os.AddNotificationMessage("After await", nameof(OrderEditScreenButtonCallback)); 
Получаем исключение: 

```
System.Runtime.Remoting.RemotingException: Затребованная служба не найдена.

Server stack trace: 
   в System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationServiceInternal.AddNotificationMessage(String message, String sender, Nullable`1 timeout)
   в Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.AddNotificationMessage(String message, String sender, Nullable`1 timeout)
```

И такое поведение во всех коллбеках, так же и в Payment processor, работать будет только если запустить такую задачу синхронно через Task.Run либо через Wait().
Если я правильно понимаю то ограничение такое понятно, так как предоставляемые коллбеки или методы в Payment processor являются void и вы их просто у себя не можете ожидать. Поэтому получается что после любого await в таких методах доступа к предоставляемым вами объектам физически нет. Я прав или есть все же какой-то способ работы кроме того чтобы запускать задачи синхронно?

**Comment by vcpp** [comment]
Вы правы, текущая реализация Front API не поддерживает `Task` и, соответственно, `async/await`. Ожидается, что ваш callback работает синхронно, то есть возвращает управление после завершения операции.

Поддержка асинхронного API может быть добавлена в одной из будущих версий.
