### ISSUE TITLE
Подскажите как получить код ИКПУ товара/продукта?

### ISSUE THREAD

**Issue by Rustik1976** [iiko/front.api.sdk#535]
Здравствуйте, подскажите пожалуйста как получить код ИКПУ
при получении списка товаров/продуктов 
var productList = order.Items.OfType<"IOrderProductItem">();
foreach (var product in productList)
{
    var name = product.Product.Name;
    var ikpu = product.Product.????;
}
мне надо вытащить ИКПУ каждого элемента, но его там нет.

**Comment by vkotelevskiy** [comment]
Добрый день. 
Код ИКПУ можно получить следующим образом
`var ikpu = product.Product.UzFiscalCode;`
Подробнее см. https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Assortment_IProduct_UzFiscalCode.htm
Также, обратите внимание, что поле UzFiscalCode было добавлено в версии V9Preview2, и будет доступно только в этой и **следующих** версиях api.

**Comment by Rustik1976** [comment]
Здравствуйте, большое спасибо за пояснение, дело в том, что мы используем демо платформу с версией 8.5.8 в этой версии долго искал и всё же нашел
![image](https://github.com/user-attachments/assets/b66222a8-7091-4c30-81f7-bbd2a79916bb)
