### ISSUE TITLE
Как получить список сотрудников текущего предприятия?

### ISSUE THREAD

**Issue by drunix23** [iiko/front.api.sdk#537]
Выбор пользователей с типом Employee:

`PluginContext.Operations.GetUsers().Where(u => u.Type == UserType.Employee)`

 возвращает сотрудников всех предприятий, входящих в группу. Как выбрать только тех, кто работает в заведении, в котором запущен плагин?

**Comment by igorpooh1978** [comment]
В API - никак.
Через server

**Comment by vcpp** [comment]
Начиная с V8 метод `GetUsers` по умолчанию возвращает только сотрудников текущего подразделения. Кроме того, добавлено свойство [`IUser.AssignedToCurrentDepartment`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Security_IUser_AssignedToCurrentDepartment.htm), с помощью которого можно определить, привязан ли пользователь к текущему подразделению. Подробнее [тут](https://iiko.github.io/front.api.doc/2023/07/27/users-of-current-department.html).
