### ISSUE TITLE
Проблема с ShowOkPopup() и ShowErrorPopup()

### ISSUE THREAD

**Issue by a9-studio** [iiko/front.api.sdk#54]
https://iiko.github.io/front.api.doc/v6/ru/ViewManager.html 
Из всего IViewManager не работают два метода: ShowOkPopup() и ShowErrorPopup()
Если использовать в своем плагине какой-либо из них, плагин полностью перестает работать. При этом никакого исключени или ошибки не выбрасывает. Пробовали сначала в своем плагине, потом в "чистом" SamplePlugin из SDK - аналогично, все работает кроме этих двух методов

Код плагина - просто скопировали из SDK, там в SamplePlugin есть окошко с кнопкой "Ок" - оно не работает точно так же.

Версия API:
![image_2019_07_01T10_03_51_904Z](https://user-images.githubusercontent.com/48734750/60429504-dee69880-9c03-11e9-8b80-4d9c7518de5c.png)

**Comment by ierof** [comment]
Версию API вы не указали, это версия iiko. 
По [версиям API](https://iiko.github.io/front.api.doc/versioning.html) — сейчас стабильная версия API это V5. Версия V6 сейчас в разработке. 
Статья, на которую вы сослались про API V6.
В [новостях](https://iiko.github.io/front.api.doc/2018/12/29/show-ok-error-messages.html) добавлена статья об интересных вам окнах датирована декабрём 2018 года. Эти методы появились в более новых релизах API V6, до версии 6.3 этих методов не было.

> Код плагина - просто скопировали из SDK 

SDK от той же версии iiko — 6.2.2? Или от какой-то более свежей?
В принципе, стабильный sample на API V5 [выложен именно в этом проекте на Github](https://github.com/iiko/front.api.sdk/tree/master/sample).
