### ISSUE TITLE
Проблема добавления скидки.

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#56]
Добрый день. 
Мы пишем плагин для нашей системе лояльности.
Для того чтобы применить скидку на заказ,  делаем следующие шаги.
1. В iiko office создали скидку с типом `DiscountByFlexibleSum.`
2. После сканирования карты добавляем скидку вызывая метод `PluginContext.Operations.AddFlexibleSumDiscount`

По выше изложенному сценарию  все работает нормально. Однако вслучае изменения заказа (т.е. если заказ изменился после первого сканирования), необходимо повоторно сканировать карту т.к. значения процента скидки может изменится(процент скидки зависит от суммы закза).
Но при повторном вызове фунцкции `PluginContext.Operations.AddFlexibleSumDiscount` получаем исключение
> "Such discount or increase already in the order (Id = 0e226a6e-ed1b-43e1-bf80-3e516373482c)"}

Я попробовал удалить затем добавить скидку.
```
PluginContext.Operations.DeleteDiscount
PluginContext.Operations.AddFlexibleSumDiscount
```
в этом случае получаю исключение
> Versioned entity Resto.Front.Api.V6.Data.Orders.Order was modified before actions execution. Expected version: 1035, actual version: 1036.

 Если данным методом не возможно пересчитать и внести скидку заново, то какой есть альтернативный вариант ?

**Comment by vcpp** [comment]
Судя по всему, вы пытаетесь внести изменение в неактуальное состояние заказа. Допустим, вы каким-то образом получили актуальный заказ (объект [`IOrder`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Orders_IOrder.htm)), меняете его, вызывая `DeleteDiscount`, после чего в системе заказ уже новый (с учётом удаления скидки), но у вас остаётся ссылка на тот же самый старый объект `IOrder`, в котором скидка ещё есть. Чтобы продолжить вносить изменения, нужно было бы перечитать заказ (например, с помощью [`GetOrderById`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_GetOrderById.htm)), тогда у вас снова была бы актуальная версия объекта.

Это общий подход. Однако, в вашем случае рекомендуется более изящный вариант — выполнить обе операции (удаление и добавление скидки) одновременно в рамках одной сессии редактирования: создаёте объект `IEditSession`, вызываете у него одноимённые методы `DeleteDiscount` и `AddFlexibleSumDiscount`, затем коммитите сессию. Этот вариант и быстрее (ибо пакетный), и надёжнее (ибо транзакционно).

**Comment by vcpp** [comment]
Посмотрите пример в [SDK](https://github.com/iiko/front.api.sdk/blob/dee57eefe543227236e6735f6de43c854d49cc2b/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs#L684):
```cs
var editSession = PluginContext.Operations.CreateEditSession();
editSession.AddDiscount(discountType, order);
editSession.ChangeSelectiveDiscount(order, discountType, selectedDish, null, null);
SubmitChanges(editSession);
```

Разница лишь в том, что в примере `AddDiscount`+`ChangeSelectiveDiscount`, а у вас будет другая пара `DeleteDiscount`+`AddFlexibleSumDiscount`.
