### ISSUE TITLE
IPaymentType и rmsSettings/getPaymentTypes

### ISSUE THREAD

**Issue by xsxVeNxsx** [iiko/front.api.sdk#57]
Используем iiko.Front 6.1.2, Resto.Front.Api.V6.
Есть API запрос к office серверу по роуту **/api/0/rmsSettings/getPaymentTypes**. Он выдает json типов платежей в виде:
```
{
    "paymentTypes": [
        {
            "id": "09322f46-578a-d210-add7-eec222a08871",
            "code": "CASH",
            "name": "Наличные",
            "comment": "",
            "combinable": true,
            "externalRevision": 8038497,
            "applicableMarketingCampaigns": null,
            "deleted": false
        },
        {
            "id": "d8470b01-80ff-4a42-9c57-a6c71a44a083",
            "code": "BONUS",
            "name": "BONUS",
            "comment": "BONUS",
            "combinable": true,
            "externalRevision": 10598867,
            "applicableMarketingCampaigns": null,
            "deleted": false
        }
    ]
}
```
Аналогичный запрос списка типов платежей методом **PluginContext.Operations.GetPaymentTypes()** в SDK выдает массив типа **IPaymentType**. Проблема в том, что у этого интерфейса нет свойства "code", который есть в json, приведенный выше. Есть ли аналогичное свойство для типа платежа в SDK? 
Исходя из [документации](https://iiko.github.io/front.api.sdk/v6/html/Properties_T_Resto_Front_Api_V6_Data_Payments_IPaymentType.htm) ближайшее по смыслу к нему - это свойство 'Kind'. Но это заранее заведенный enum. Мне же нужно произвольное значение для группировки типов платежей.

**Comment by ierof** [comment]
И правда, в API iikoFront не выставлено свойство `Code`. Единственный надёжный маппинг тут будет по `id`.

**Comment by vcpp** [comment]
> Есть ли аналогичное свойство для типа платежа в SDK?

Нет, это поле доступно только на сервере. Приложению iikoFront это поле не нужно, поэтому туда его не протаскивали, соответственно, и в API оно недоступно. Однако, если в этом есть потребность, ничего не мешает протащить и опубликовать.

Опишите, пожалуйста, чуть подробнее предполагаемый вами сценарий использования этого поля, что за плагин, для чего он хочет группировать типы оплаты по коду и т. д.

<sup>Для коллег из iiko: поле добавлено в RMS-32813.</sup>

**Comment by vcpp** [comment]
Хорошо, будем считать, что потребности в доработке пока нет. Если интерес появится, пишите.
