### ISSUE TITLE
Уведомление о завершении оплаты

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#58]
Есть ли возмжность получить уведомление о завершении оплаты?

**Comment by ierof** [comment]
Вас интересует:

1. момент закрытия заказа в iiko?
   1. на текущей кассе?
   2. на любой кассе?
2. момент окончания печати фискального чека в iiko?

Для первого в свежих версиях SDK есть пример: `OrderStatusChangeNotifier`.
Для второго есть [расширение печати чеков](https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor) — `AfterDoCheckAction`

**Comment by HakobyanAram** [comment]
> Для первого в свежих версиях SDK есть пример: OrderStatusChangeNotifier.

Откуда скачать свежие версии [здесь](https://github.com/iiko/front.api.sdk/tree/master/sample) и [здесь](https://iiko.github.io/front.api.sdk/v6/search.html?SearchText=OrderStatusChangeNotifier) не могу найти OrderStatusChangeNotifier

**Comment by ierof** [comment]
Свежая версия распространяется вместе с дистрибутивом iiko. Запросите SDK от версии 6.3 или 6.4

**Comment by HakobyanAram** [comment]
> Для первого в свежих версиях SDK есть `пример: OrderStatusChangeNotifier.`

Не подскажите где можно посмотреть пример

**Comment by ierof** [comment]
> Запросите SDK от версии 6.3 или 6.4
Напишите на api@iiko.ru, если вам не дали API SDK вместе с дистрибутивом iiko.

**Comment by HakobyanAram** [comment]
Ранее вы сказали, что для получения уведомления о закрытии заказа я должен использовать либо OrderStatusChangeNotifier либо AfterDoCheckAction

> Вас интересует:
> 
> момент закрытия заказа в iiko?
> на текущей кассе?
> на любой кассе?
> момент окончания печати фискального чека в iiko?
> Для первого в свежих версиях SDK есть пример: OrderStatusChangeNotifier.
> Для второго есть расширение печати чеков — AfterDoCheckAction.

 А также Вы  [отвечали](https://github.com/iiko/front.api.sdk/issues/61)

> Разрабатываемую версию использовать не рекомендуется, поскольку её интерфейс ещё не зафиксирован, обратная совместимость не обеспечивается, возможны любые изменения. Эта версия доступна для изучения нововведений и раннего начала разработки плагина для будущей версии API, чтобы к моменту её выпуска иметь готовый или почти готовый плагин, предоставляющий новые возможности.
> 
> По разрабатываемым версиям API нет обратной совместимости. API V6 разрабатываемая версия API и в версии iiko 6.3, и в версии iiko 5.5.
> Вам нужно собрать свой плагин на SDK от iiko 5.5 для клиента.
> 
> А лучше — пользоваться зафиксированными версиями API. Например, API V5. Тогда вам не придётся пересобирать свои плагины под версии клиента.

Получается я немогу использовать ни OrderStatusChangeNotifier ни AfterDoCheckAction (т.к. находятся в API V6). 

Есть ли другие варианты уведомления о закрытии заказа для версий ниже ?

**Comment by ierof** [comment]
На API V5 можно реализовать подобное:
см https://github.com/iiko/front.api.sdk/issues/7
