### ISSUE TITLE
Ошибка оплаты

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#59]
Мы пишем плагин для нашей системы лояльности. 
Нам необходимо, чтобы клиент мог оплатить не наличными, а по накопленным баллам.
Для этой цели, мы имплементировали следующий класс
```
 public class OurPayment : MarshalByRefObject, IExternalPaymentProcessor, IDisposable
{
}
```
добавили этот Payment в плагин следующим образом
```
public sealed class Plugin : MarshalByRefObject, IFrontPlugin
{
        private readonly Stack<IDisposable> _subscriptions = new Stack<IDisposable>();
        public Plugin()
        {
            Debugger.Launch();
            OurPayment оurPayment = new OurPayment ();
            PluginContext.Operations.RegisterPaymentSystem(оurPayment );
            _subscriptions.Push(оurPayment );
        }
}
```
добавили внешний тип оплаты в iikoOffice
![image](https://user-images.githubusercontent.com/51437851/60677226-f8047900-9e91-11e9-9922-90e8fb4633bb.png)

Переодически (но не всегда) при выборе "Безналичный расчет" затем "OurPayment" получаю следующую ошибку 
![image](https://user-images.githubusercontent.com/51437851/60676937-36e5ff00-9e91-11e9-9ea2-63b5334f8401.png)

**Comment by ierof** [comment]
В приведенном вами коде всё в порядке. Скриншот присланного вами сообщения это результат ошибки в каком-то из методов `OurPayment `, вашей реализации интерфейса. 

Без логов точнее сказать сложно. Загляните в `%appdata%\iiko\CashServer\Logs\`. Там есть полезные вам логи: `cash-server.log`, `api.log` и `plugin-[ИМЯ_ВАШЕГО_ПЛАНИГА].log`

**Comment by HakobyanAram** [comment]
После нажатия на  "Безналичный расчет" затем "OurPayment" появляются логи:
`в cach-server.log`

> [2019-07-08 11:22:57,420]  INFO [ 1] [PaymentScreenController:OnInitPaymentItem] - Initing payment item: ExternalPaymentItem[735a90f3-1c41-4120-8d80-98f363617edd] of type [9b3c1b33-fc0f-4513-a59d-3643cbb7a2ec]
> [2019-07-08 11:22:57,421]  INFO [ 1] [PaymentInitializationController:InitializeExternalPaymentItem] - Initing external payment.
> [2019-07-08 11:22:58,469] DEBUG [ 1] [CardProcessorBase:ClaimProcessors] - Claiming processors
> [2019-07-08 11:22:58,470] DEBUG [ 1] [CardProcessorBase:ClaimProcessors] - Claiming processors
> [2019-07-08 11:22:58,470] DEBUG [ 1] [CardProcessorBase:ClaimProcessors] - Claiming processors

`а в api.log`

> [2019-07-08 11:26:19,758] ERROR [47] - System.Runtime.Remoting.RemotingException: Requested Service not found
> 
> Server stack trace: 
>    at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Resto.Front.Api.V6.IExternalPaymentProcessor.CollectData(Guid orderId, Guid paymentTypeId, IUser cashier, IReceiptPrinter printer, IViewManager viewManager, IPaymentDataContext context, IProgressBar progressBar)
>    at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.CollectData(Guid orderId, Guid paymentTypeId, IUser cashier, IPluginPrinter printManager, PluginViewManager viewManager, IPluginPaymentDataContext paymentContext, IPluginProgressBar progressBar) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 33
>    at Resto.Front.Api.ApiExtensionsService.PerformPaymentAction(IExternalPaymentItem item, String key, Decimal sum, Nullable`1 orderId, Guid transactionId, ICashRegister cashRegister, IUser cashier, ActionType type, Action`1 changeProgressBarMessage) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\ApiExtensionsService.cs:line 113

**Comment by ierof** [comment]
По стеку ошибка происходит в вашей реализации `CollectData`
1. Если вы пишете на API V6, вы используете SDK той же версии, что iikoFront?
1. Если вы снабдите вашу реализацию `CollectData` логированием через `PluginContext.Log` и обработкой исключений, что будет в вашем логе?

**Comment by HakobyanAram** [comment]
> Если вы пишете на API V6, вы используете SDK той же версии, что iikoFront?
А как это узнать?

> Если вы снабдите вашу реализацию CollectData логированием через PluginContext.Log и обработкой исключений, что будет в вашем логе?

У меня имеется логирование  `PluginContext.Log.Info`

**Comment by vcpp** [comment]
> По стеку ошибка происходит в вашей реализации `CollectData`

`RemotingException` происходит на стороне iikoFront при попытке вызвать метод MBR-объекта, созданного плагином. Если ошибка возникает не сразу, а спустя некоторое время, вероятно, проблема в истечении времени жизни объекта, так что интересует реализация не столько метода `CollectData`, сколько расположенного рядом `InitializeLifetimeService`.

**Comment by ierof** [comment]
bq. В Reference проекта я добавил Resto.Front.Api.V6.dll, которая находится в папке C:\Program Files\iiko\iikoRMS\Front.Net
Тогда версия библиотеки правильная. 

Попробуйте добавить логирование в начале метода, чтобы убедиться, что управление приходит штатно. И добавить `try-catch` на всё тело метода. Ведь для меня загадка, что у вас может происходить в `TransactionController.Instance`.

Можете очистить логи, повторить вашу проблему и приложить три лога, о которых я говорила выше? Посмотрим, там ли мы ищем проблему? Или что-то идёт не так раньше и описанное это уже следствие.

**Comment by ierof** [comment]
bq. расположенного рядом InitializeLifetimeService.
О, да... не обратила сразу внимания на эти стандартные грабли.

@HakobyanAram , вы случайно не удалили из Sample строчки кода
```
// Note http://msdn.microsoft.com/en-us/library/23bk23zc(v=vs.100).aspx
public override object InitializeLifetimeService() { return null; }
```
Не заглянув по ссылке? :)

**Comment by HakobyanAram** [comment]
> @HakobyanAram , вы случайно не удалили из Sample строчки кода

Sample-ах не переопределен InitializeLifetimeService метод. Я тоже не переопределил. Вероятно причина в этом.


Я должен был переопределить  public override object InitializeLifetimeService() { return null; } чтобы дать пожизненое время жизни обекту OurPayment?
```
 public class OurPayment : MarshalByRefObject, IExternalPaymentProcessor, IDisposable
{
    public override object InitializeLifetimeService() { return null; }
}
```

**Comment by ierof** [comment]
> Я должен был переопределить public override object InitializeLifetimeService() { return null; } чтобы дать пожизненое время жизни обекту OurPayment?

Да. 

> Sample-ах не переопределен InitializeLifetimeService метод. Я тоже не переопределил. Вероятно причина в этом.

Подскажите, откуда вы брали пример `IExternalPaymentProcessor`? В текущих официальных примерах SDK точно есть.

**Comment by HakobyanAram** [comment]
> Подскажите, откуда вы брали пример IExternalPaymentProcessor? В текущих официальных примерах SDK точно есть.

`ftp://iiko-6.2:YH2ojOJK@ftp.iiko.ru/6.2.4011.0/SDK/Resto.Front.Api.SamplePaymentPlugin/`
эту сылку нам дал  Владимир Пасечников Команда тех. поддержки

**Comment by ierof** [comment]
Проверила. `ExternalPaymentProcessorSample.cs`, строки 22-23:
```
        // Note http://msdn.microsoft.com/en-us/library/23bk23zc(v=vs.100).aspx
        public override object InitializeLifetimeService() { return null; }
```
:)

**Comment by vcpp** [comment]
Подумаем о том, чтобы спрятать от разработчика плагина связанные с .Net Remoting детали реализации iikoFront API. Это реально не имеет отношения к ни к платежам, ни к чему, просто необязательные грабли.

**Comment by HakobyanAram** [comment]
> Проверила. ExternalPaymentProcessorSample.cs, строки 22-23:

Спасибо не заметил

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @HakobyanAram)
