### ISSUE TITLE
Документация где?

### ISSUE THREAD

**Issue by ivada** [iiko/front.api.sdk#6]
Где взять документацию?
По ссылке https://gitlab.iiko.ru/iikoPublic/iikoFrontSDK/tree/master/Docs доступны только содержание документаций, а текста внутри chm нет совсем.
![default](https://user-images.githubusercontent.com/46180253/50466319-6e9a5880-09cf-11e9-82f5-889da366370f.png)

**Comment by vcpp** [comment]
Документация по коду [здесь](https://iiko.github.io/front.api.sdk/v5/). Это актуальная версия того, что на скриншоте. То же самое, но в формате chm, распространяется в составе SDK. Именно эти chm-файлы, только восьмимесячной давности, кто-то выложил на gitlab, не обращайте внимания.
История изменений и развёрнутые статьи [здесь](https://iiko.github.io/front.api.doc/).

Обе эти ссылки есть в README этого репозитория :-)
