### ISSUE TITLE
Несколько вопросов

### ISSUE THREAD

**Issue by Persik3D** [iiko/front.api.sdk#60]
Добрый день, интересует несколько вопросов:
1) Как изменить сумму external платежа?
2) Где брать credentials? Каждый раз через AuthenticateByPin?)
3) Как печатать QR-Code на чеках. 
4) Не могу найти как сделать виртуальный принтер для чеков. Нужно как то проверить же, но не могу найти что-то=\
5) Есть ивент пречека? Могу ли я добавить в пречек дополнительную информацию для печати?

iikoFront version: 6.3.3014.0

**Comment by ierof** [comment]
1. В каких сценариях у вас это не получается сделать методом `ChangePaymentItemSum` [из OperationService](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_OperationServiceExtensions_ChangePaymentItemSum.htm)` или [из EditSession](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Editors_IEditSession_ChangePaymentItemSum.htm)? 
1. По-хорошему вам нужно завести какого-нибудь служебного. Каждый раз не обязательно брать. Можно получить один раз и пользоваться. 
1.  [`Tags.QRCode`](http://iiko.github.io/front.api.sdk/v6/html/F_Resto_Front_Api_V6_Data_Cheques_Tags_QRCode.htm) : `new XElement(Tags.QRCode, "any text")` 
1. Поясните вопрос, что вы понимаете под "виртуальным принтером чеков".
1. См. [`INotificationService.SubscribeOnBillChequePrinting`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_INotificationService_SubscribeOnBillChequePrinting.htm). Если заполнять [`BillCheque`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Cheques_BillCheque.htm), он будет напечатан. В Sample [есть пример](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/BillChequeExtender.cs)

**Comment by Persik3D** [comment]
1. Мне сказали что это ошибка которую исправили в новой версии. Жду обновления:) Надеюсь все заработает.
2. Хорошо, спасибо.
3. Мне прийдется печатать уникальный QR-Коды. Генерировать мы будем их на своей стороне, возможна ли печать как изображения? 
4. Мне нужна возможность печати чека в PDF или в любой другой аналог для проверки. Как выглядит чек и тд.
5. Хорошо, спасибо.

Пока что остались актуальными 3ий и 4ый вопросы

**Comment by ierof** [comment]
п3. Если речь не о печати QR-кодов в чеках iiko, то метода _"получить каротину QRCode по строке"_ в API iikoFront. Это общепрограммистский вопрос :) Можете использовать любой способ получать картинку QR-кода по строке. 
п4. Понятнее не стало :) Вам нужно перенаправлять печать чеков iiko в PDF? Или печатать свои документы в нужные вам моменты времени? Если первое, то под "чеками" вы понимаете фискальные чеки и любые печатные формы iiko вроде пречеков, слипов банков, сервисную печать на кухню и т.д.

**Comment by Persik3D** [comment]
3. Bitmap я генерирую сам, вопрос как его на печатать на чеке? точнее пречеке в нашем случае:)
4. Я разработчик и у меня нету кассовых аппаратов. Моя задача написать плагин, следовательно мне нужно как то проверить печать чеков и прочих документов. Для этого мне нужно создать/подключить вывод печати моих тестовых печатей(чеки/пречеки/отчеты и тд). Естественно все это в рамках тестов :)

**Comment by ierof** [comment]
3. Если необходимо печатать QR-коды на чеках iiko, то как раз самим Bitmap не нужно генерировать, стоит воспользоваться возможностями расширения печатных форм iiko и тем методом, что я указала в первом комментарии: через `new XElement(Tags.QRCode, "any text to become QRCode")`.
4. Мне кажется, я всё ещё не понимаю, что именно вам нужно. Т.е. если вы пишете не плагин печатающего устройства, и вам нужно проверить то, что печатает iiko при своих стандартных процессах, то вы это уже сейчас можете найти в логах: `%appdata%\iiko\CashServer\Logs\virtual-printer.log`. Ничего специально подключать не нужно.

**Comment by Persik3D** [comment]
4. Спасибо, то что нужно! :)
3. Вот вам пример разницы использования Tags.QRCode и отдельного изображения. В наших QR мы можем сделать их приятными и хорошо читаемыми, в вашем - мы не можем такого сделать. Естественно иконка в центре была взята от балды)
![qr-code (4)](https://user-images.githubusercontent.com/23328020/60971965-80ca5b80-a34f-11e9-9637-aa840cbd0b33.png)
![qr-code](https://user-images.githubusercontent.com/23328020/60972149-e28ac580-a34f-11e9-8522-4dcf62175a16.gif)

**Comment by ierof** [comment]
По последнему вопросу:  в данный момент нет возможности печатать произвольные картинки средствами API.
