### ISSUE TITLE
ChangePaymentItemSum

### ISSUE THREAD

**Issue by Persik3D** [iiko/front.api.sdk#62]
IExternalPaymentProcessor-> OnPaymentAdded, все дело тут происходит.
1) Вызываю так: PluginContext.Operations.ChangePaymentItemSum(42m, 0m, 100500m, paymentItem, order, credentials);
Ошибка: One or more objects used in edit session are already in use.

2) Вызываю так: operations.ChangePaymentItemSum(42m, 0m, 100500m, paymentItem, order, credentials);
Ошибка: Выдано исключение типа "Resto.Front.Api.V6.Exceptions.UserSessionInvalidException"

3) Вызываю так:
var editSession = operations.CreateEditSession();
editSession.ChangePaymentItemSum(42m, 0m, 100500m, paymentItem, order);
Ошибки нет, но и действий никаких не происходить=\

iikoFront v6.4.1746.0
Как мне поменять сумму платежа?
С удалением платежа все абсолютно одинаково)  (DeleteExternalPaymentItem)

**Comment by vcpp** [comment]
1, В момент добавления оплаты заказ заблокирован самим приложением iikoFront, и из глобального контекста (`PluginContext.Operations`) на общих основаниях вы будете получать такую ошибку. Это защищает от несогласованных изменений, не связанных с текущей операцией. Для возможности редактирования в метод [`OnPaymentAdded`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IExternalPaymentProcessor_OnPaymentAdded.htm) передаётся специальный короткоживующий `IOperationService`, он привязан к локальному контексту и потому позволяет редактировать текущий заказ. Используйте его вместо `PluginContext.Operations` в этом методе.
2. А не пробовали смотреть документацию к классу [`UserSessionInvalidException`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Exceptions_UserSessionInvalidException.htm)? Она доступна и онлайн, и офлайн (chm), и в IDE при наличии xml-файла рядом с dll. Попробуйте заново вызвать [`AuthenticateByPin`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_AuthenticateByPin.htm).
3. Забыли вызвать [`SubmitChanges`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_SubmitChanges.htm). Если вам нужно выполнить только одно действие, проще использовать extension-метод из первого пункта (одна строка вместо трёх).

**Comment by Persik3D** [comment]
```
var editSession = operations.CreateEditSession();
editSession.ChangePaymentItemSum(42m, 0m, 100500m, paymentItem, order);
operations.SubmitChanges(PluginContext.Operations.AuthenticateByPin("111"), editSession);
```
и 
```
operations.ChangePaymentItemSum(42m, 0m, 100500m, paymentItem, order, PluginContext.Operations.AuthenticateByPin("111"));
```
Выдают ошибку [UserSessionInvalidException](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Exceptions_UserSessionInvalidException.htm)

**Comment by Persik3D** [comment]
Так же чутка не понятно, от куда брать pin для `AuthenticateByPin`? Не могу найти способа как можно его узнать, не подскажите?

**Comment by ierof** [comment]
1. Попробуйте не `PluginContext.Operations.AuthenticateByPin("111")`, а тот же объект `operations` использовать: `operations.AuthenticateByPin("111")`
1. Узнать данные, которые позволяют выполнять операцию от имени какого-либо пользоваться из API не получится. Это безопасность — не хранить ключи под ковриком. Следует завести в RMS специального юзера для вашей интеграции, договориться о него PIN-коде и использовать его.

**Comment by vcpp** [comment]
> Выдают ошибку `UserSessionInvalidException`

Стабильно? Или иногда?
Возможно, понадобятся логи, их можно отправить через техподдержку.

> не понятно, от куда брать pin для `AuthenticateByPin`

Всё никак не доделаем поддержку плагинных учётных записей :-(
В текущей реализации при установке плагина надо вручную создать пользователя, придумать и назначить ему пин-код, а затем указать тот же пин-код в конфиге плагина. Соответственно, плагин будет брать пин-код из конфига. Коряво, неудобно, но пока так.

**Comment by vcpp** [comment]
> Попробуйте не `PluginContext.Operations.AuthenticateByPin("111")`, а тот же объект operations использовать: `operations.AuthenticateByPin("111")`

Точно! В этом дело. Ошибка, поправим. Временное решение — использовать локальный `IOperationService`.

**Comment by Persik3D** [comment]
Спасибо, разобрался. Будем костыли  ставить значит))
