### ISSUE TITLE
Правильное прерывание операции с ФР

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#63]
Добрый день!

Такая ситуация: в Настройке оборудования делаем тестовую печать. Предположим, что в DoXReport произошла какая-нибудь ошибка, например, прервалась связь с ФР.
Как правильно прервать эту операцию, чтобы в офисе отобразилось какое-нибудь сообщение об ошибке?

Если кидать DeviceException с сообщением, тогда офис реагирует так:
![image](https://user-images.githubusercontent.com/2943468/61130340-218b5900-a4bf-11e9-9653-0230fa18eac6.png)

Если возвращать пустой CashRegisterResult с сообщением и Success = false, тогда офис вообще не ругается:
![image](https://user-images.githubusercontent.com/2943468/61130426-55ff1500-a4bf-11e9-96e3-960fc2d0610a.png)

SDK: V6Preview5
iiko: 6.4.1746

**Comment by ierof** [comment]
@GulnaraBikbova

**Comment by bildeyko** [comment]
Как дополнение, если выкинуть исключение DeviceException с сообщением в DoCorrection
![image](https://user-images.githubusercontent.com/2943468/61217741-0ae03e80-a719-11e9-8fee-0ffd71d0ff78.png)

**Comment by GulnaraBikbova** [comment]
Добрый день, 

Чтобы сообщить фронту или бэку об ошибке\неуспехе - кидайте исключение вида:
{code}
throw new DeviceException("Ваш текст сообщения об ошибке.");
{code}

**Comment by bildeyko** [comment]
@GulnaraBikbova в сообщениях выше я как раз бросаю `DeviceException`. 
Для примера, такой код приведет приведет к ошибке "Не удалось найти сборку ...", которая отображается в бэке.

```c#
public CashRegisterResult DoXReport(string cashierName, string cashierTaxpayerId, IViewManager viewManager)
{
    try
    {
        _spark.SetCashier(cashierName, cashierTaxpayerId);
        _spark.CRep(true);
        return GetCashRegisterData();
    }
    catch (Exception e)
    {
        throw new DeviceException(e.Message, e);
    }
}
```

**Comment by GulnaraBikbova** [comment]
Полагаю, ваш плагин именно с таким текстом исключение и бросает.
Попробуйте залогировать это момент перед выбросом исключения выше по стеку.

`PluginContext.Log.Error(e.Message);`

Фронт/бэк лишь отображает исключение на экран, текст которого формирует плагин.

**Comment by vcpp** [comment]
> я как раз бросаю `DeviceException`

Есть существенная разница между тем, как это делает ваш плагин, и тем, как показывает @GulnaraBikbova. Вы передаёте исходное исключение `e` в качестве `innerException` в конструктор `DeviceException`. Это ошибка.

Во-первых, это избыточно. Наличие вложенного исключения ни на что не влияет, операция будет отменена в любом случае.
Во-вторых, это ненадёжно. За базовым типом `Exception` может скрываться исключение любого типа. Этот тип может не быть сериализуемым (не помечен атрибутом `Serializable`). Этот тип может быть объявлен в сборке, которая не загружена в домен приложения iikoFront.

Нет никаких гарантий, что произвольное исключение удастся сериализовать, передать в другой домен и там десериализовать. Но это и не нужно. Просто уберите аргумент `e` :-)

Отдельный вопрос — логирование. Если сейчас просто убрать `e`, вы потеряете подробности об этом исключении. Эти подробности могли бы помочь при расследовании, но в остальное время это просто лишний спам в логах. Помимо предельно общего обработчика `catch (Exception)` желательно добавить обработчики конкретных ожидаемых типов исключений, и тогда можно будет не логировать (или логировать кратко) ожидаемые исключения и логировать детально, включая стектрейс, непредвиденные исключения.

С нашей стороны нехорошо получилось предоставление конструктора, принимающего `innerException`. Уберём его, начиная с V6.
