### ISSUE TITLE
QR-коды в virtual-printer.log

### ISSUE THREAD

**Issue by Persik3D** [iiko/front.api.sdk#65]
Для отслеживания печати чека есть виртуальный принтер: "\AppData\Roaming\iiko\CashServer\Logs\virtual-printer.log". Но там не печатаются QR-коды. Как можно проверить печать? Можно ли вывести печать чека на обычный принтер? Или может сохранить в pdf файл?
Так же 3ий вопрос)). У XElement есть такой тип Image. У вас в api он реализован как то? Полагаю это уже вопрос принтера? Но как тогда распечатать свою картинку? Лого например? И как я могу проверить может ли принтер распечатать QR-код/лого?
Тут есть [пример](https://stackoverflow.com/questions/5882508/serializing-deserializing-image-to-from-xelement) xelement и image

**Comment by ierof** [comment]
> Тут есть пример xelement и image

XElement это просто элемент разметки.  Тут может быть любой текст. Это протокол. Нужно, чтобы обе стороны его поддерживали. Так что искать в гугле возможные тэги XML не имеет смысла :) Печать произвольных картинок из API не поддерживается. 

Что касается настройки: это конечно не вопрос iikoFront API.
Настроить можно: https://i.imgur.com/2MQzvWp.gif
Но я проверила, и там у нас не эмулируется печать QR-кодов. Потому что всё-таки windows-принетры это достаточно экзотический кейс. На рулонных принтерах всё печатается. 

А чем вам так принципиально у себя проверять функционал печати QR-кодов системой iiko? :) Он печатается. Печатается читаемым.

**Comment by Persik3D** [comment]
Потому что наша система строится на QR кодах. Если они ВДРУГ не будут работать)) Нужно проверить, надеюсь вы правы и все будет печататься)

**Comment by ierof** [comment]
<sup>Для коллег из iiko — issuer на эту тему: RMS-49661</sup>
