### ISSUE TITLE
PrintBillCheque error

### ISSUE THREAD

**Issue by Persik3D** [iiko/front.api.sdk#66]
Все происходит тут: `IExternalPaymentProcessor->Pay/OnPaymentAdded`
При вызове [PrintBillCheque](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_PrintBillCheque.htm), вылетает ошибка: 
```
[2019-07-15 17:06:00,384]  INFO [51] [MessageService:Add:107] - Message: System.InvalidOperationException: Method “PrintBillCheque” cannot be called using operation service of notification event handler, use default operation service.

Server stack trace: 
   в Resto.Front.Api.V6.OperationService.Resto.Front.Api.V6.IOperationService.PrintBillCheque(ICredentials credentials, IOrder order, PrinterSelectionMode printerSelectionMode) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V6\Operations.g.cs:строка 2446
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.V6.IOperationService.PrintBillCheque(ICredentials credentials, IOrder order, PrinterSelectionMode printerSelectionMode)
   в Invoice.Modules.iiko.InvoicePaymentProcessor.Pay(Decimal sum, IOrder order, Guid paymentTypeId, Guid transactionId, IPointOfSale pointOfSale, IUser cashier, IOperationService operations, IReceiptPrinter printer, IViewManager viewManager, IPaymentDataContext context) в C:\projects\Invoice.Modules.iiko\Invoice.Modules.iiko\InvoicePaymentProcessor.cs:строка 209, Sender: Invoice, Type: Warning, ReceiveTime: 07/15/2019 17:06:00, ExpireTime: 07/16/2019 05:06:00
```
Пробовал по разному:
```
operations.PrintBillCheque(operations.AuthenticateByPin("111"), order);
operations.PrintBillCheque(PluginContext.Operations.AuthenticateByPin("111"), order);
PluginContext.Operations.PrintBillCheque(operations.AuthenticateByPin("111"), order);
PluginContext.Operations.PrintBillCheque(PluginContext.Operations.AuthenticateByPin("111"), 
order);
```
Как мне вызвать этот метод? Или просто напечатать чек с небольшим текстом (не вместе с общим, а отдельно).

**Comment by Persik3D** [comment]
Сделал через [printer.Print](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IReceiptPrinter_Print.htm).

**Comment by Persik3D** [comment]
Точно такая же ошибка кстати говоря при попытке вызова такой функции как: 
`operations.PayOrder(credentials, order);` 
Я думаю вопрос актуальный. Хотелось бы использовать в дальнейшем PayOrder)

**Comment by ierof** [comment]
У меня такой вопрос -- в рамках какой операцией API вы вызываете `operations.PayOrder(credentials, order);`?

**Comment by Persik3D** [comment]
IExternalPaymentProcessor->OnPaymentAdded

**Comment by ierof** [comment]
А какой заказ вы хотите закрывать в рамках добавления оплаты? Текущий?
Если текущий, то зачем? Добавление оплаты это обратимая операция и она подразумевает такой процесс, что сначала оплата добавляется в заказ, а потом кассир осуществляет закрытие заказа.

**Comment by Persik3D** [comment]
У нас есть механизм уведомлений о том, что оплата прошла. Соответственно может не только текущий заказ обслуживаться. Суть в том, что я жму оплатить и плагин выдает `throw new PaymentActionFailedException("Ожидаем оплату.");` Мне нужно следующее:
1) В случае если человек долго оплачивает(в первый раз регистрируется), то касса не должна на это время зависать, поэтому мы прерываем оплату и даем оператору обслуживать другого клиента(особенно необходимо в ресторанах).
2) В момент когда убрался наш тип оплаты - добавить его и изменить его сумму.(Естественно только после регистрации платежа через наш способ оплаты). Мне бы с этим пунктом чутка поподробнее, не могу ивенты нужные найти что-то и не хочет PayOrder работать :(

**Comment by Persik3D** [comment]
Мой новый вопрос очень схож с этим, поэтому задам тут, не открывая нового топика :)
Делаю я значит 2 подписки:
```
            disposables.Add(PluginContext.Notifications.OrderChanged
                .Select(x => x.Entity)
                .Where(x => Orders.ContainsKey(x.Id))
                .Subscribe(changes => OnOrderChanged(changes)));
            disposables.Add(PluginContext.Notifications.ScreenChanged
                .Where(x => x is IOrderPayScreen)
                .Select(x => x as IOrderPayScreen)
                .Subscribe(screen => OnOpenOrder(screen.Order)));
```
Вызываю в этих евинтах:
```
PluginContext.Operations.AddExternalPaymentItem(
    request.order.amount,
    true,
    null,
    PluginContext.Operations.GetPaymentTypes().Where(x => x.Name == PaymentSystemName).First(),
    order,
    PluginContext.Operations.AuthenticateByPin(Pin)
);
```
Как уже мне сказали ранее, payments лочатся в момент открытого OrderPayScreen. Подскажите пожалуйста, как можно это обойти? Как я могу добавить внешний платеж в список платежей? 
И как я могу вызвать `PayOrder` во время `OnPaymentAdded`?

**Comment by ierof** [comment]
В общем, по порядку, сначала общая информация тезисно:
1. Из API нельзя оплатить текущий заказ контекста операции. Т.е. при навигацию на кассу или при 
1. Из API можно добавить в состав оплат заказа что угодно в любой момент времени
     1. И в момент "покоя", когда текущий заказ никем не заблокирован на редактирование
     1. И в контексте интеропов редактирования заказа — при навигацию на кассу или при добавлении платежа плагинным типом
1. Метод `PayOrder` это метод фоновой оплаты заказа. Без участия кассира. Это не навигация на кассу по воле плагина. На этот метод него накладывается множество ограничений — когда и в каких условиях ом может выполняться.

Статьи про оплаты есть на https://iiko.github.io/front.api.doc/
1. [Внешние типы оплаты](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html)
1. [Оплатные действия](https://iiko.github.io/front.api.doc/v6/ru/Payments.html) 

Кстати, по https://iiko.github.io/front.api.doc/ работает поиск ;)

Теперь попробую ответить на ваши вопросы:
> Как уже мне сказали ранее, payments лочатся в момент открытого OrderPayScreen. Подскажите пожалуйста, как можно это обойти? Как я могу добавить внешний платеж в список платежей?

Тот код, что вы привели выше, с  `PluginContext.Notifications.ScreenChanged` это "наблюдатели". У них не подразумевается контекст текущего редактируемого заказа. 
Если вам нужен интероп при переходе на кассу, посмотрите на [INotificationService.SubscribeOnNavigatingToPaymentScreen](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_INotificationService_SubscribeOnNavigatingToPaymentScreen.htm). У него в контексте коллбэка есть `IOperationService`, через него можно выполнять операции на текущем заказе, так же, как в рамках во время операции `OnPaymentAdded`.

> И как я могу вызвать PayOrder во время OnPaymentAdded?

Вы так и не объяснили, зачем вам это. В процессе `OnPaymentAdded` вы можете инициировать оплату закрытие заказа, но не текущего редактируемого. Раз вы находитесь на кассе в UI iikoFront, предполагается, что текущий заказ закрывается кассиром.

**Comment by Persik3D** [comment]
Спасибо, `INotificationService.SubscribeOnNavigatingToPaymentScreen. ` то что нужно!
Но вот так и не выходит добавить тип оплаты при его удалении при `throw new PaymentActionFailedException("Ожидаем оплату.");`. 
Ход работы:
1) Кассир добавляет внешний тип оплаты(наш).
2) Вводит сумму
3) Жмет ОПЛАТИТЬ
3.1) В системе регистрируется платеж при нажатии
3.2) Выходит ошибка `throw new PaymentActionFailedException("Ожидаем оплату.");` для остановки оплаты.
3.3) Из-за ошибки метод оплаты исчезает из списка -> необходимо его добавить.
4) _Добавляем оплату сразу после удаления._
А вот с 4ым пунктом проблемы. Из `PluginContext.Notifications.OrderChanged` не выходит, так как там не передается `IOperationService`. А через `PluginContext.Operations` ошибка, так как в данный момент заблокирован контекст. 
Есть ли какое-то решение?

**Comment by Persik3D** [comment]
И есть ли способ проверить что-то по типу `order.IsLocked` ? Чтоб не ловить ошибки, а предотвращать их)

**Comment by ierof** [comment]
Из `PluginContext.Notifications.OrderChanged` не получится внести изменение в текущий заказ. 
Повторю, это наблюдатель. `order.IsLocked` тоже не узнать. 

> Из-за ошибки метод оплаты исчезает из списка -> необходимо его добавить.

Это нормальный флоу для iikoFront. Если оплата не проведена успешно, она удаляется из заказа. 


Могу предложить вам такой флоу:
- При выборе типа оплаты в `OnPaymentAdded` вы сохраняете данные в заказ через [`AddOrderExternalData`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_OperationServiceExtensions_AddOrderExternalData.htm) параметры авторизации юзера
- Происходит проблема при оплате вашим типом
- По инструкции кассир должен будет либо добавить вручную этот тип оплаты, либо выйти и зайти на экран кассы. 
- При повторном `OnPaymentAdded` или в `SubscribeOnNavigatingToPaymentScreen` считывать данные из заказа через [`ryGetOrderExternalDataByKey`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_TryGetOrderExternalDataByKey.htm) и добавить оплаты в заказ.

Вот это более правильный флоу. 

В ближайшие версии у нас запланирован ряд задач для большей гибкости экранов заказов через API. Можно будет по кнопке "подтянуть" все внешние оплаты, которые плагины хотели бы добавить в текущий заказ. Подумаем над тем, чтобы такую же возможность сделать после неуспешной оплаты.

**Comment by Persik3D** [comment]
Такой флоу я уже и сам сделал:) только со своими граблями. Спасибо за помощь в ответах.
