### ISSUE TITLE
IHostTerminal не наследует IEntity

### ISSUE THREAD

**Issue by xsxVeNxsx** [iiko/front.api.sdk#67]
В соответствии с [документацией](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Organization_IHostTerminal.htm), IHostTerminal наследует IEntity и содержит поле Id.

В **Resto.Front.Api.V6, Version=6.0.1127.0** это не так
![Resto.Front.Api.V6, Version=6.0.1127.0](https://user-images.githubusercontent.com/2202747/61291427-d7cda600-a811-11e9-99be-d5203f64696e.jpg)

Проблема в разных версиях SDK?
Если ли способ в моей версии SDK получить id текущего терминала?

**Comment by ierof** [comment]
1. [Статья про управление версиями](https://iiko.github.io/front.api.doc/versioning.html):
>| V6 | Разрабатываемая |
> Разрабатываемую версию использовать не рекомендуется, поскольку её интерфейс ещё не зафиксирован, обратная совместимость не обеспечивается, возможны любые изменения. Эта версия доступна для изучения нововведений и раннего начала разработки плагина для будущей версии API, чтобы к моменту её выпуска иметь готовый или почти готовый плагин, предоставляющий новые возможности.

`IHostTerminal` : [v5](http://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Organization_IHostTerminal.htm) vs [v6](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Organization_IHostTerminal.htm) и правда имеет отличия. Если я правильно помню, такие правки случились [в апреле 2019 года](https://iiko.github.io/front.api.doc/2019/04/12/order-edit-terminal.html). И вошли в API V6 Preview5 и версию iiko 6.4. 
=> на вашей версии этого не узнать.
