### ISSUE TITLE
Табачная продукция из iiko в ФР

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#68]
Добрый день,

public class ChequeSale 
в каких полях класса подается код табачной продукции ?
GTIN , SerialNumber

**Comment by GulnaraBikbova** [comment]
Добрый день,

Вам нужен `CommodityCode` - код табачной продукции.
`GtinCode` - это 14-тизначный "Global Trade Item Number" для позиции чека.

**Comment by igorpooh1978** [comment]
Доброе утро. 
А с какой версии появилось данное поле в ChequeSale ?
