### ISSUE TITLE
Получение значений от 2д сканера

### ISSUE THREAD

**Issue by loona-ai** [iiko/front.api.sdk#69]
Добрый день!

Мы разрабатываем плагин для iiko front. Нам нужно получить отсканированное значение 2Д сканера. В документации нигде не нашел объяснения. Подскажите пожалуйста как можно это реализовать.

**Comment by CLTanuki** [comment]
Не припоминаю такой явной возможности в SDK.
Так как  barcode сканер является HID устройством, у нас для подобных целей имеется библиотека, которая перехватывает клавиатуру и отслеживает ввод.

**Comment by HakobyanAram** [comment]
А можно по подробнее о библиотеке? И где можно взять эту библиотеку ?

**Comment by ierof** [comment]
to @HakobyanAram : @CLTanuki имеет ввиду, что для этих целей можно использовать любое решение, которое найдете, по получению инпута с HID-устройства. Это не является частью API iikoFront.
