### ISSUE TITLE
Перехватить событие печати фискального чека, возможно ли ? 

### ISSUE THREAD

**Issue by avrezvanov** [iiko/front.api.sdk#7]
Здравствуйте. 
Возможно ли перехватить событие печати фискального  чека? 
Есть плагин, добавление товаров к заказу. При работе с данным плагином в заказ пишется доп. информация.
Возможно ли при печати фискального чека, проверять доп. информацию в заказе и в выполнять какие либо действия, например записать доп. информацию в файл.

**Comment by avrezvanov** [comment]
Как вариант можно и момент закрытия заказа рассмотреть.

**Comment by ierof** [comment]
Просто печать чека в iiko != закрытие заказа.
К примеру, чек для заказа может напечататься и при внесении предоплаты. И если предоплата была на 100% суммы заказа, при закрытии заказа чек печататься не будет.
Или на заказ дали 100% скидку. 
Или заказ оплачивают какими-либо нефискальными бонусами... 
В общем масса вариантов, когда в iiko заказ становится закрытым, а чека при этом не печатается. 

Если отслеживать закрытие заказа, то можно подписываться на `PluginContext.Notifications.OrderChanged` и отслеживать смену `IOrder.Status`. 

Правда в текущих зафиксированных версиях API (v4, v5) есть следующий нюанс: нет привязки заказа к терминалу оплаты. Поэтому все существующие решения, которые отслеживают факт закрытия заказа работают только на  главной кассе группы. Чтобы в случае конфигурации с несколькими терминалами не дублировать выполнение.  Для этого можно анализировать `PluginContext.Operations.GetHostTerminalPointsOfSale().Any(i => i.IsMain)` перед подпиской на `OrderChanged`

В api v6 мы замкнули контур с [точками продаж ](https://iiko.github.io/front.api.doc/v6/ru/GroupsAndPointsOfSale.html). Поэтому для решения задачи отслеживания факта закрытия заказа можно попробовать такой класс:
```
using System;
using System.Linq;
using System.Reactive.Linq;
using Resto.Front.Api.V6;
using Resto.Front.Api.V6.Data.Orders;

namespace Resto.Front.Api.SamplePlugin
{
    internal sealed class OrderStatusChangeNotifier : IDisposable
    {
        private readonly IDisposable subscription;

        public OrderStatusChangeNotifier()
        {
            var pointsOfSaleIds = PluginContext.Operations.GetHostTerminalPointsOfSale().Select(i => i.Id).ToArray();
            if (pointsOfSaleIds.Length == 0)
            {
                PluginContext.Log.Info("It's not cash terminal, orders will not be closed on this terminal.");
                return;
            }
            var orders = PluginContext.Operations.GetOrders();
            var closedOrderIds = orders.Where(o => o.Status == OrderStatus.Closed).Select(o => o.Id).ToList();
            PluginContext.Log.Info($"On init: closed orders '{closedOrderIds.Count}'.");
            subscription =
                PluginContext.Notifications.OrderChanged
                    .Select(e => e.Entity)
                    .Where(o => o.Status == OrderStatus.Closed && !closedOrderIds.Contains(o.Id))
                    .Do(o => closedOrderIds.Add(o.Id))
                    .Where(o => IsPaidOnCurrentTerminal(o, pointsOfSaleIds))
                    .Subscribe(OnOrderClosed);
        }

        private static bool IsPaidOnCurrentTerminal(IOrder order, Guid[] pointsOfSaleIds)
        {
            return order.Payments.Any(p =>
                p.Status == PaymentStatus.Processed
                && !p.IsPrepay
                && p.PointOfSale != null
                && pointsOfSaleIds.Contains(p.PointOfSale.Id));
        }

        private void OnOrderClosed(IOrder order)
        {
            PluginContext.Log.Info($"Order {order.Number} ({order.Id}) is closed.");
        }

        public void Dispose()
        {
            subscription.Dispose();
        }
    }
}

```

В скором времени добавим пример таких отследивший в Sample Plugin :)

**Comment by vcpp** [comment]
> Чтобы в случае конфигурации с несколькими терминалами не дублировать выполнение. Для этого можно анализировать `PluginContext.Operations.GetHostTerminalPointsOfSale().Any(i => i.IsMain)` перед подпиской
Или пометить плагин атрибутом `SingleInstancePlugin` :-)
