### ISSUE TITLE
Получение информации об операторах

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#70]
Здравствуйте.

Подскажите, пожалуйста, возможно ли в front.api.sdk v6 получить информацию об операторах терминала: ID сотрудника и время аутентификации за текущую смену?

**Comment by vcpp** [comment]
Нет, сейчас такой возможности нет.
Можете рассказать, для чего хотели бы использовать эту информацию?

**Comment by iDoctor** [comment]
@vcpp, нам необходимо отслеживать активность сотрудников на рабочих местах (в частности - тех, кто работает за терминалом) для расчёта премий и надбавок.

**Comment by iDoctor** [comment]
Вообще возможно ли подобную информацию вытащить каким-то другим способом? Например, взаимодействие с iiko Office,...

**Comment by vcpp** [comment]
> необходимо отслеживать активность сотрудников на рабочих местах

О какой именно активности идёт речь? Залогинился/разлогинился?

**Comment by iDoctor** [comment]
> О какой именно активности идёт речь? Залогинился/разлогинился?

Именно: время входа/выхода из системы и id сотрудника

**Comment by vcpp** [comment]
Я все равно пока не вполне понимаю предполагаемую схему мотивации персонала. Дескать, если чаще логинился и дольше оставался залогиненным, значит, принёс больше выручки заведению? Мотивируем почаще логиниться и не блокировать терминал за собой?

Кроме того, сотрудники могут работать на подключенных через плагины мобильных терминалах (смартфоны, планшеты или специальные устройства типа orderman), это не будет учитываться?
Вы решаете задачу конкретного заказчика или хотите создать коробочный продукт?

Пока затея видится сомнительной, но, вероятно, я ещё не понял суть :-)

> Вообще возможно ли подобную информацию вытащить каким-то другим способом?

Эта информация фиксируется в журнале событий и, возможно, доступна в [серверном API](https://ru.iiko.help/articles/#!api-documentations/developments).

**Comment by iDoctor** [comment]
> Я все равно пока не вполне понимаю предполагаемую схему мотивации персонала...

Суть не в том, чтобы сотрудник чаще логинился. Ключевой момент - время первого логина и последнего логаута за смену, с любого устройства.

**Comment by vcpp** [comment]
А, так это у нас называется личной сменой. Сотрудник приходит на работу и открывает личную смену, а перед уходом закрывает. И даже есть встроенный механизм учёта явок с возможностью почасовой оплаты, задания персонального расписания, штрафов за опоздания и т. п.

Если штатных возможностей не хватает, и вы хотите сделать альтернативную систему учёта рабочего времени, то, на мой взгляд, уместнее будет использовать серверный API, чем ставить плагин на все терминалы и потом всё это агрегировать.

Если хотите решить именно плагином к iikoFront, можно найти такой вариант: у сотрудника есть поле [`IsSessionOpen`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Security_IUser_IsSessionOpen.htm), показывающее, открыта ли у него личная смена, достаточно подписаться на событие [`UserChanged`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_INotificationService_UserChanged.htm) и следить за изменением значения этого поля у разных сотрудников.

**Comment by iDoctor** [comment]
Спасибо! Будем пробовать оба варианта :)
