### ISSUE TITLE
Получение эквайринговых данных

### ISSUE THREAD

**Issue by wildcherrycandy** [iiko/front.api.sdk#71]
Добрый день!
Интересует возможность интеграции в части эквайринга. При рассчете картой, интересует получение таких данных как ID транзакции банка эквайрера. 

Конечная цель - понять, что конкретный клиент рассчитался именно картой, и иметь возможность сопоставить рассчету транзакцию в системе банка держателя карты.

Используем API SDK v5.

**Comment by ierof** [comment]
Такие данные из API iikoFront точно не получить. И, подозреваю, из API iikoServer эти данные тоже не получить. Максимум, что можно получить из серверного API это маскированный номер карты. Причём все банки маскируют номера карт по-своему, стандарта нет.
