### ISSUE TITLE
NullReferenceEx with IOpretationServices.SubmitChanges(credentials, session)

### ISSUE THREAD

**Issue by Tres-Poli** [iiko/front.api.sdk#72]
После метода SubmitChanges() выбрасывается исключение NullReferenceEx. 
[Log.txt](https://github.com/iiko/front.api.sdk/files/3410959/Log.txt)
Все тщательно проверили, но не знаем точно, что именно в параметре Session влияет на выброс ошибки.
[method_with_Ex.txt](https://github.com/iiko/front.api.sdk/files/3410970/method_with_Ex.txt)

**Comment by vcpp** [comment]
Во-первых, NRE — это ошибка в коде, в котором данное исключение возникло. Исключение возникло в коде приложения iikoFront, значит, это наш баг. Исправный код должен проверять входящие аргументы и, если вызывающая сторона неправа, возвращать понятную ошибку. NRE — это непредвиденная авария :-)
Поправим.

Во-вторых, плагин действительно пытался выполнить ошибочную последовательность действий, просто с нашей стороны не хватило защиты с понятным сообщением об ошибке. Добавим защиту, будет вместо NRE другое исключение, плагин в любом случае надо поправить.

Вы привели кусок кода, в котором нет самого интересного — реализации метода `addOrderProducts`, но ошибка и так понятна, вы добавляете в заказ составное блюдо (`AddOrderCompoundItem`), не добавляя к нему компонентов (`AddPrimaryComponent`/`AddSecondaryComponent`), и затем пытаетесь включить это блюдо в состав комбо (`AddOrderCombo`). Составное блюдо должно содержать хотя бы один компонент. Попробуйте сначала добавить в заказ составное блюдо с одним или двумя компонентами, а только потом собрать блюда в комбо. Можете посмотреть [примеры](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs) в SDK.

В-третьих, напрасно вы используете V6. Эта версия находится в разработке, в ней то и дело что-то меняется, включая breaking changes. Может так получиться, что клиент обновит iikoRMS, и написанный ранее плагин перестанет работать. Учитывайте этот риск.
По тому кусочку кода, что вы привели, показалось, что хватило бы и V5. Если чего-то не хватает и нужны новые фичи, безопаснее взять V6Preview5. Эти версии уже зафиксированы, и по ним гарантируется обратная совместимость. Подробнее [тут](https://iiko.github.io/front.api.doc/versioning.html).

**Comment by CLTanuki** [comment]
Итак, мы нашли.
Только вот конструкция, где надо добавить комбо, а потом ТОТ ЖЕ продукт добавляется в качестве основного компонента, кажется слегка... избыточной?
```C#
INewOrderCompoundItemStub cookingItemCompound = session.AddOrderCompoundItem(product, orderStub, guest, size);
INewOrderCompoundItemComponentStub primaryComponent = session.AddPrimaryComponent(product, orderStub, cookingItemCompound);
```

**Comment by vcpp** [comment]
Основная причина, почему добавление в заказ составного блюда и добавление в это блюдо обязательного первого компонента, сделано двумя отдельными действиями — это чтобы вернуть два результата: блюдо (`INewOrderCompoundItemStub`) и компонент (`INewOrderCompoundItemComponentStub`). Не хотелось добавлять операции, возвращающие два результата. А ссылки нужны на оба этих объекта, чтобы в той же сессии добавить модификаторы как общие, так и для отдельного компонента, а также применить прочие действия.

Ну и, кроме того, в общем случае могут быть использованы разные продукты.
