### ISSUE TITLE
Получение Схемы Модификаторов

### ISSUE THREAD

**Issue by ilyapostnik** [iiko/front.api.sdk#73]
Добрый день.
В ProductExtensions Methods есть методы
GetGroupModifiers
и 
GetSimpleModifiers

А какой метод использовать для получение схемы модификаторов? Если у блюда модификаторы заданы схемой то эти 2 метода возвращают пустоту

Спасибо

**Comment by vcpp** [comment]
[`IProduct.Template`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Assortment_IProduct_Template.htm) — шаблон составного блюда («схема модификаторов»).
Ну и дальше [`GetCommonGroupModifiers`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Data_Assortment_CompoundItemTemplateExtensions_GetCommonGroupModifiers.htm), [`GetCommonSimpleModifiers`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Data_Assortment_CompoundItemTemplateExtensions_GetCommonSimpleModifiers.htm), [`GetSplittableGroupModifiers`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Data_Assortment_CompoundItemTemplateExtensions_GetSplittableGroupModifiers.htm), [`GetSplittableSimpleModifiers`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Data_Assortment_CompoundItemTemplateExtensions_GetSplittableSimpleModifiers.htm).

А ещё можно посмотреть [примеры](https://github.com/iiko/front.api.sdk/blob/master/sample/Resto.Front.Api.SamplePlugin/EditorTester.cs)  в SDK.
