### ISSUE TITLE
 PaymentType should be CanBeExternalProcessed. API V6

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#74]
Здравствуйте, я разрабатываю плагин ExternalPaymentPlugin iiko 6.4 API V6. При добавлении PluginContext.Operations.AddExternalPaymentItem(10, true, additionalData, paymentType, order, credentials); выдаёт ошибку 
`Resto.Front.Api.V6.Exceptions.ConstraintViolationException 
Cannot Add card external prepay :-( 
Message: Payment item of type O!Dengi 
075a1f14-d59d-412c-9436-0deed0d187dc cannot be added as external processed. PaymentType should be CanBeExternalProcessed. `

Как мне указать CanBeExternalProcessed property для IPaymentType?

Можете привести пример?

ссылка на исходные данные плагина http://s000.tinyupload.com/index.php?file_id=08467637534977626421
Версия iiko 6.4, Версия API 6

**Comment by vcpp** [comment]
Посмотрите [здесь](https://ru.iiko.help/articles/#!iikooffice-6-4/topic-89/q/%D0%9C%D0%BE%D0%B6%D0%B5%D1%82%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D1%8C%D1%81%D1%8F%20%D0%B8%D0%B7%D0%B2%D0%BD%D0%B5/qid/194210/qp/1), надо установить галочку «Может приниматься извне» и в выпадающем списке «Проведение оплаты» выбрать «Только внешний» или «Как внешний, так и на стороне ресторана».

**Comment by Azamatjon** [comment]
Может приниматься извне не доступна для внешних типов оплат, а мне нужна именно она

**Comment by letolika** [comment]
К сожалению, на текущий момент нет возможности принимать проведенную оплату внешним типом оплаты. Насколько Вам принципиально передавать вторым аргументом _true_ в метод _AddExternalPaymentItem_? Можете описать, что это за оплата, которую не нужно процессить на стороне iikoFront?

**Comment by Azamatjon** [comment]
Опишу сценарий коротко:
У меня есть внешний тип оплаты – онлайн оплата кошельком. При выборе внешнего типа кошелька данные отправляется и создаётся инвойс со стороны онлайн кошелька, она нужна для дальнейшей оплаты QR кодом в пречеке. При сканировании в приложении кошелька клиент должен оплачивать счёт. В моём модуле каждая N-секунда отправляется запрос была ли успешная транзакция в кошельке или нет. После успешной транзакции автоматически нужно закрыть счёт в iiko. Методом Pay(), чтобы автоматически закрыть заказ, мне кажется мой тип оплаты должен быть CanBeProcessedExternal, а я не могу его установить, так как она "внешняя оплата", а не оплата "банковской картой". 

1. Как мне кодом печатать пречек на открытой кассе. Попробовал всех вариантов. То-ли Entity locked Exception, то-ли User Authentication Exception. 

2. Как мне автоматически закрыть заказ когда от сервера получаю уведомление об успешной оплате?

Разве iiko приложение для автоматизации системы, я даже элементарные автоматизации не могу делать...

**Comment by CLTanuki** [comment]
Уважаемый @Azamatjon , если Вы реализовали внешний тип оплаты, то Вам надо не добавлять его, так как в методе Pay он уже добавлен, а менять его сумму.
Только вот это надо по логике разработчиков делать ранее, в Pay() уже реагировать на начало оплаты (печати чека).
![Screenshot at 2019-10-10 12-24-58](https://user-images.githubusercontent.com/5824716/66556577-2bbe0180-eb59-11e9-94ab-99052563f70b.png)
![Screenshot at 2019-10-10 12-25-08](https://user-images.githubusercontent.com/5824716/66556578-2bbe0180-eb59-11e9-9f23-a64e3dcc2430.png)

**Comment by letolica** [comment]
Добрый день.

> Методом Pay(), чтобы автоматически закрыть заказ, мне кажется мой тип оплаты должен быть CanBeProcessedExternal, а я не могу его установить, так как она "внешняя оплата", а не оплата "банковской картой".

> Как мне автоматически закрыть заказ когда от сервера получаю уведомление об успешной оплате?

Теперь заказ из API, имеющий в себе внешнюю непроведенную оплату плагинным типом (второй аргумент `false` в методе `AddExternalPaymentItem`), можно закрыть методом `PayOrder`. Подробнее [тут](https://iiko.github.io/front.api.doc/2020/11/09/silent-plugin-payments.html).

> Как мне кодом печатать пречек на открытой кассе. Попробовал всех вариантов. То-ли Entity locked Exception, то-ли User Authentication Exception.

Возможность редактировать заказ, пока он открыт на фронте, реализована и будет доступна в ближайшей версии API.V7Preview5. Следите за [новостями](https://iiko.github.io/front.api.doc/changelog.html).

> Иногда не дожидаясь уведомления кассир нажимает на "ОПЛАТИТЬ". В методе SilentPay() я выдаю paymentErrorException, так как оплата ещё не была проведена, а тип оплаты удаляется из списка. Нужно вернуть Тип оплаты. Можете про этот сценарий тоже свои варианты подсказать?

Пока заказ оплачивается и управление приходит в метод `SilentPay` вашего плагина, на экране фронта висит прогрессбар. Можно не кидать exception из плагина, а дождаться проведения оплаты и успешности транзакции в кошельке.

> Можно ли реализовать UI переходы (пользовательский интерфейс) через ваш API? При печати пречека мне нужно выйти из кассы автоматически не нажимая кнопку назад.

Навигация между экранами фронта из API недоступна и пока не планируется.
