### ISSUE TITLE
Ошибка при добавлении скидки в заказ

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#75]
Здравствуйте.
Мы разрабатываем программу лояльности. И если у клиента тип программы - скидка, то необходимо применить к заказу скидку.
Стоит следующая проблема: мы применяем скидку следующим кодом на экране оплаты:
`
IEditSession editSession = PluginContext.Operations.CreateEditSession();
IReadOnlyList<IDiscountType> discounts = PluginContext.Operations.GetDiscountTypes();
IDiscountType discount = discounts.First(x => x.Name == "OurDiscountName");
editSession.AddDiscount(d, order);
string pin = "1111";
ICredentials credentials = PluginContext.Operations.AuthenticateByPin(pin);
PluginContext.Operations.SubmitChanges(credentials, editSession);
`
Но на последней строке, метод SubmitChanges вызывает EntityAlreadyInUseException.
Не знаем как решить проблему, подскажите, пожалуйста.

Писали в поддержку, они направили к вам (тикет [#ID-41987647] )

**Comment by vcpp** [comment]
В [статье о редактировании данных](https://iiko.github.io/front.api.doc/v6/ru/Data%20editing.html) есть раздел «Ожидаемые исключения» с кратким описанием: `EntityAlreadyInUseException` — попытка применить изменения к объекту, который в этот момент заблокирован. Можно повторить попытку позднее.

Заказ, к которому вы пытаетесь применить скидку, в этот момент редактируется кем-то другим (например, открыт в приложении iikoFront). Либо вам нужно выбрать момент, когда заказ никем не заблокирован, либо использовать точки расширения (например, `SubscribeOnServiceChequePrinted` или `SubscribeOnNavigatingToPaymentScreen`).

В какой момент, по какому условию или событию вы решаете, что пора добавить скидку?

**Comment by theDCM** [comment]
Скидка добавляется в момент добавления клиента программы лояльности на экране оплаты заказа.
То есть алгоритм следующий: кассир создает заказ, переходит на экран оплаты, вводит номер телефона клиента, от сервера приходит ответ с данными о клиенте, и если у него тип лояльности "скидка", то необходимо добавить скидку.
`SubscribeOnServiceChequePrinted` использовать не получится, так как это происходит уже после оплаты заказа, а `SubscribeOnNavigatingToPaymentScreen` - слишком рано, ведь клиент еще не определен.

**Comment by vcpp** [comment]
> переходит на экран оплаты, вводит номер телефона клиента, от сервера приходит ответ с данными о клиенте

Куда кассир вводит номер телефона? От какого сервера приходит ответ?

**Comment by theDCM** [comment]
Мы создаем и отображаем окно, в которое, при участии клиента в программе лояльности, кассир должен ввести его идентификатор, в нашем случае - номер телефона. Запрос с номером телефона отправляется на наш сервер программы лояльности, ответ содержит данные о клиенте.

**Comment by vcpp** [comment]
В какой момент, по какому событию вы показываете окно для ввода номера телефона?

**Comment by theDCM** [comment]
"Подписываемся" на `SubscribeOnNavigatingToPaymentScreen`
При переходе на экран оплаты, если клиент говорит, что хочет воспользоваться нашей программой лояльности, кассир нажимает на кнопку, которая отображает окно для ввода номера телефона/другого идентификатора

**Comment by vcpp** [comment]
Ух, завис этот вопрос :-(

Если я правильно понял, вы подписываетесь на событие [`SubscribeOnNavigatingToPaymentScreen`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_NotificationServiceExtensions_SubscribeOnNavigatingToPaymentScreen.htm) и в обработчике используете глобальный `PluginContext.Operations`. Так не получится. Обработчик события получит на вход локальный экземпляр этого сервиса (параметр `IOperationService`), и редактировать текущий заказ нужно через него:

```cs
IEditSession editSession = operationService.CreateEditSession();
IReadOnlyList<IDiscountType> discounts = PluginContext.Operations.GetDiscountTypes();
IDiscountType discount = discounts.First(x => x.Name == "OurDiscountName");
editSession.AddDiscount(d, order);
string pin = "1111";
ICredentials credentials = PluginContext.Operations.AuthenticateByPin(pin);
PluginContext.Operations.SubmitChanges(credentials, editSession);
```

Через глобальный `PluginContext.Operations` можно выполнять операции, не требующие блокировок, а также редактировать объекты, которые в этот момент никто не использует. Для объектов, заблокированных текущей операцией, надо использовать локальный контекст, доступный в рамках подписки на эту операцию.
