### ISSUE TITLE
Отключение округлений на iiko

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#76]
Добрый день, 
Как отключить округление в iiko для версии 6.4.1746, т.к. у нас возникают сложности при обработке товаров, постоянно появляется 1-2 копейки на сдачу
![изображение](https://user-images.githubusercontent.com/47010778/62006107-eb97d700-b144-11e9-9b91-35e29f4e2ffb.png)

**Comment by vcpp** [comment]
В [настройках валюты](https://ru.iiko.help/articles/#!iikooffice-6-4/topic-256/q/%D0%B2%D0%B0%D0%BB%D1%8E%D1%82%D0%B0/qid/199982/qp/3).

**Comment by igorpooh1978** [comment]
Мы отключили, но всё равно округление срабатывает!

**Comment by vcpp** [comment]
Округление срабатывает только при работе через API? Через UI самого приложения iikoFront округления нет?

**Comment by igorpooh1978** [comment]
При работе с API я получаю в RoundSum копейки округления в независимости от того включены или отключены настройки.

**Comment by ierof** [comment]
Заведена задача RMS-49794 на валидацию бага. 
Сценарий сформулирован так:
1. Выключить настройки округления
1. Создать заказ с нецелыми суммами
1. Оплатить его через API на реальном или плагинном ФР
1. Ошибка: в чеке будут следы применения округления. 

Правильно ли сформулирован проблемный сценарий или вы имеете ввиду что-то другое?

**Comment by ierof** [comment]
@igorpooh1978 
> Мы отключили, но всё равно округление срабатывает!

А расскажите всё-таки подробнее, как именно вы отключаете округление? 

7.0.3004.0
Результаты тестов:
1. Включено и округление и сервисный сбор "Округление цены за единицу в пользу 
гостя" - сумма в чеках везде указывается без копеек. Округляется верно.
1. Включено округление, сервисный сбор отключен - В квитанции об оплате заказа 
округление указано как скидка.
1. Округление отключено, включен сервисный сбор - Все суммы в чеках полные.
1. Если обе настройки включены - В квитанции об оплате заказа 
округление указано как скидка.

**Comment by igorpooh1978** [comment]
Добрый день,
Мы отключаем все округления
Также очень странная ситуация получается. Я вам пишу про тесты на одной версии, вы мне на другой и в итоге не понятно  ушла проблема или нет. Сейчас мы работаем на 6.4.2014. Проблема округления ушла, но теперь мне не понятно, какую сумму ожидает iiko от плагина в CashRegisterResult в случае возврата, с округлением или без ?


Если мы делаем возврат суммы, то какую сумму мы должны вернуть

**Comment by ierof** [comment]
bq. Я вам пишу про тесты на одной версии, вы мне на другой 
Мы проверяем на текущей разрабатываемой версии на предмет существования бага. 

bq. теперь мне не понятно, какую сумму ожидает iiko от плагина в CashRegisterResult в случае возврата, с округлением или без ?
По здравому смыслу — с такими же данными, как и при оплате. Но если вы опишете подробно свои настройки и желаемый сценарий, мы проверим у себя, как оно функционирует.
