### ISSUE TITLE
Внешняя оплата и оплата бонусами iikoCard

### ISSUE THREAD

**Issue by bildeyko** [iiko/front.api.sdk#78]
Добрый день!

Сейчас изучаю документации на возможность доработки нашего решения, чтобы была возможность начислять и оплачивать бонусами iikoCard.

#### Сейчас работает так:

1. На киоске создается заказ
2. Добавляется внешняя оплата на **всю** сумму заказа (AddExternalPaymentItem)
3. Заказ закрывается.

#### Как планируем:

1. На киоске создается заказ
2. Часть оплачивается бонусами
3. Часть оплачивается внешней оплатой.
4. Заказ закрывается.

Как правильно реализовать оплату бонусами, чтобы эта оплата нормально учитывалась в статистике офиса и на фронте?

С помощью pos api у меня получилось привязать гостя к заказу (`authorize`), рассчитать лимиты и возможные начисления (`update`), зафиксировать (`getPayments`) и оплатить бонусами (`pay`). 
При вызове `IOperationService.PayOrder`, фронт видимо сообщил pos-серверу о закрытии заказа и pos обновил кошелек у гостя.

Проблема в том, что фронт не знает, что я оплатил часть заказа бонусами через pos и в закрытых заказах отображает только внешнюю оплату. 

Можно как-то программно добавить к заказу настроенный тип оплаты iikoCard? Например, заказ на 100 рублей, внешняя оплата 80р, оплата бонусами 20р.

**Comment by ierof** [comment]
Лучше обратитесь на api@iiko.ru или в support@iiko.ru с даным вопросом. 
Потому что это вопрос скорее не для команды, поддерживающей iikoFront API, а для команды iikoCard.
