### ISSUE TITLE
Получение списка продуктов только определенного заведения

### ISSUE THREAD

**Issue by molchanovpavel** [iiko/front.api.sdk#79]
Здравствуйте!

Каким образом можно получить список продуктов определенного заведения ?
IOperationService.GetAllProducts, IOperationService.GetHierarchicalMenu вернули список продуктов из всех заведений

**Comment by rgrigorenko** [comment]
var menu = PluginContext.Operations.GetHierarchicalMenu();
                                MenuGroup data = GetMenuGroup(menu.Products.Where(a => a.Category == null).ToList(), menu.ProductGroups.ToList());
 
                               
MenuGroup GetMenuGroup(List<IProduct> products, List<IProductGroup> categories)
        {
            MenuGroup menuGroup = new MenuGroup();
            menuGroup.categories = new List<MenuGroup>();
            foreach (var cat in categories)
            {
                var group = GetMenuGroup(cat.GetChildProducts(PluginContext.Operations).ToList(), cat.GetChildGroups(PluginContext.Operations).ToList());
                if (group != null)
                {
                    group.name = cat.Name;
                    menuGroup.categories.Add(group);
                }
            }
            menuGroup.items = GetMenuProducts(products);
            if (menuGroup.categories?.Count == 0 && menuGroup.items?.Count == 0)
                return null;
            return menuGroup;
        }
 
        public List<MenuItem> GetMenuProducts(List<IProduct> products)
        {
            var result = new List<MenuItem>();
            foreach (var product in products.Where(a => a.IsActive).Where(a => a.Type == ProductType.Dish))
            {
                var item = new MenuItem();
                item.id = product.Id;
                item.name = product.Name;
                item.price = product.Price;
                item.category = product.Category?.Name ?? "";
                item.open_price = product.CanSetOpenPrice;
                item.description = product.Description;
                item.description_foreign = product.DescriptionForeign;
                item.expiration_time = product.ExpirationTime;
                item.food_value = new FootValue();
                item.food_value.caloricity = product.FoodValueCaloricity;
                item.food_value.carbohydrate = product.FoodValueCarbohydrate;
                item.food_value.fat = product.FoodValueFat;
                item.food_value.protein = product.FoodValueProtein;
                item.full_name = product.FullName;
                var image = product.GetProductMenuImage();
                if (image != null)
                {
                    item.image = image;
                }
                item.active = product.IsActive;
                item.unit_name = product.MeasuringUnitName;
                item.article = product.Number;
                item.tax = product.TaxPercent;
                item.type = product.Type.ToString();
                if (product.Scale != null)
                {
                    item.scale = new Scale();
                    item.scale.name = product.Scale.Name;
                    item.scale.size = product.Scale.DefaultSize?.Name;
                }
                var mods = PluginContext.Operations.GetSimpleModifiersByProduct(product);
                if (mods?.Count > 0)
                {
                    item.simpleModificators = new List<SimpleModificator>();
 
                    foreach (var mod in mods)
                    {
                        var modItem = new SimpleModificator();
                        modItem.id = mod.Product.Id;
                        modItem.name = mod.Product.Name;
                        modItem.price = mod.Product.Price;
                        modItem.max = mod.MaximumAmount;
                        modItem.min = mod.MinimumAmount;
                        item.simpleModificators.Add(modItem);
                    }
                }
                var gmods = PluginContext.Operations.GetGroupModifiersByProduct(product);
                if (gmods?.Count > 0)
                {
                    item.groupModificators = new List<GroupModificator>();
 
                    foreach (var gmod in gmods)
                    {
                        var modItem = new GroupModificator();
                        modItem.id = gmod.ProductGroup.Id;
                        modItem.name = gmod.ProductGroup.Name;
                        modItem.min = gmod.MinimumAmount;
                        modItem.max = gmod.MaximumAmount;
                        modItem.modificators = new List<SimpleModificator>();
                        foreach (var mod in gmod.Items)
                        {
                            modItem.modificators.Add(new SimpleModificator()
                            {
                                max = mod.MaximumAmount,
                                min = mod.MinimumAmount,
                                id = mod.Product.Id,
                                price = mod.Product.Price,
                                name = mod.Product.Name
                            });
                        }
                        item.groupModificators.Add(modItem);
                    }
                }
                result.Add(item);
            }
            return result;
        }
