### ISSUE TITLE
Вопросы по реализация плагина iiko.Front v 6

### ISSUE THREAD

**Issue by Plas-Tek-IgorK** [iiko/front.api.sdk#8]
1. Как в плагине подписаться на события открытия/закрытия смены?  Подписка PluginContext.Notifications.SubscribeOnCafeSessionOpening(CafeSessionOpening) - не срабатывает. 
2. Как в методе CollectData() (при вызове внешней оплаты) получить: IUser.Pin, код ресторана, код кассы?
3. Как правильно разделить реализацию расчета внешней оплаты по методам CollectData()  и OnPaymentAdded()? (В какой-то метод уходит валидация номера карты, а в какой-то вызов расчета по ней? Или валидацию и расчет можно проводить в одном из этих двух методов? Т.е. какова правильная стратегия их использования?

**Comment by Plas-Tek-IgorK** [comment]
Бизнес сценарий интеграции с iikoFront. Для начала хотим реализовать самый простой сценарий и интеграции iikoFront с сервисом программы лояльности.

 


№ п.п.

Касса

Внешний процессинг


1

Сотрудник (кассир или сотрудник с другой ролью) открывает смену.
Плагин передает данные сотрудника, ресторана, кассы, смены.

Аутентификация пользователя (выдача токена).
Открытие смены.


2

Операция пречека (заказ на оплату сформирован). Нажатие кнопки внешней оплаты (настроенной для внешней оплаты).
Плагин передает токен, полученный на первом шаге), локальное время, код открытой смены, идентификатор участника лояльности (номер карты/телефон/штрих код из мобильного приложения), состав чека по позициям (код товара, количество товаров в позиции, цена, (опционально: наименование товара, код/наименование категрии, другие атрибуты, имеющиеся в интерфейсе IProduct).
На основании ответа от процессинга формируется скидка на сумму. Печатается пречек.

Проверка токена сотрудника, полученного при открытии смены.
Расчет суммы скидки по программе лояльности.


3

Закрытие чека.
Плагин передает такие же данные как и в пречеке.
На основании ответа от процессинга касса закрывает заказ с оплатой со скидкой. Печатается чек. 

Проверка токена сотрудника, полученного при открытии смены.
Расчет суммы скидки по программе лояльности.
Проведение транзакции по начислению оплате бонусами.


4

Возврат товара. Печать чека возврата.
Плагин передает токен, данные по возвращаемому товару (позиция чека, количество возвращаемых товаров), идентификатор исходного чека, прошедшей с внешней оплатой, идентификатор участника лояльности.

Проверка токена сотрудника, полученного при открытии смены.
Проведение транзакции по удержанию начисленных бонусов и возврата части бонусов, которыми был оплачен заказ.


5

Закрытие смены.
Плагин передает токен и данные по закрывающейся смены.

Проверка токена сотрудника, полученного при открытии смены.
Закрытие смены.

 

Проверяли срабатывание:

1.       Написали плагин с методами класса Resto.Front.Api.SamplePaymentPlugin. ExternalPaymentProcessorSample

2.       Скопировали библиотеки в Plugin фронта. Приаттачили все процессы Resto.

3.       В плагине зарегистрировали подписку на открытие/закрытие не знаю чего:

 

subscriptions = new CompositeDisposable

{

    PluginContext.Notifications.SubscribeOnCafeSessionClosing(CafeSessionClosing),

    PluginContext.Notifications.SubscribeOnCafeSessionOpening(CafeSessionOpening)

};

4.       Поставили точки останова:

 



 

5.       Не ловит.

 

Ловится только в методах (которые пока в реализации): public void CollectData, public void OnPaymentAdded. Видимо и в других тоже будет останавливаться, связанных с оплатой.

 

Меня интересует юзер, который передается как параметр [NotNull] IUser cashier в методах оплаты itc.

 

Под кодом ресторана/кассы понимаю некие идентификаторы, которые существуют или должны существовать, однозначно интерпретирующие себя в системе iiko. Внешнему процессингу надо понимать с какой точки и кассы пришел вызов. Или такая константа и является подобным идентификатором [PluginLicenseModuleId(0021005918)] ???

 

Сценарий написал.

Спасибо за отклик.

 

С уважением,

Игорь Козлов

Руководитель направления разработки CRM системы

+7 495 605-3236

+7 495 605-3414

E-mail:                       igor.kozlov@plas-tek.ru <mailto:igor.kozlov@plas-tek.ru> 

ООО «ПЛАС-ТЕК»   <http://plas-tek.ru/> http://plas-tek.ru/

**Comment by ierof** [comment]
В такой постановке вам более правильно обратиться не к [евангелистам](https://ru.wikipedia.org/wiki/%D0%98%D0%A2-%D0%B5%D0%B2%D0%B0%D0%BD%D0%B3%D0%B5%D0%BB%D0%B8%D1%81%D1%82) API iikoFront, а к ответственному на направление итераций в iiko по api@iiko.ru :) 

Данная платформа подразумевает ответы на короткие технические вопросы. 
Желательно хорошо атомарные и хорошо оформленные. У вас пока очень сумбурно.

Чуть позднее ещё задам вам наводящих вопросов по исходным вашим вопросам, которые стали чуть понятнее после вашего пояснения на 124 строки.

**Comment by ierof** [comment]
по п.3 
Под бизнес-сценарием я имела ввиду не всё ваше ТЗ as is :) 
Мне хотелось иметь адаптированный юзер-кейс, чтобы понимать, что вы имеете ввиду под
*реализацией расчета внешней оплаты по методам CollectData() и OnPaymentAdded()*, что такое это *расчёт*.

**Comment by ierof** [comment]
п.2
Про IUser.Pin
> Меня интересует юзер, который передается как параметр [NotNull] IUser cashier в методах оплаты itc.
Пин-коды сотрудников не выставлены в API по секьюрным соображениям. Согласитесь, это как-то странно, давать возможность получить данные по Пин-е любого сотрудника предприятия, а потом от его имени без его ведома совершать какие-либо операции. Так что тут вам тоже нужно будет рассказать нам, для чего вам нужен этот Пин-код, чтобы мы могли что-то вам рекомендовать.

Про идентификаторы: 
Посмотрите на сигнатуры [`OperationService.GetHostTerminalPointsOfSale`](https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_GetHostTerminalPointsOfSale.htm) и соответственно [`IPointOfSale`](https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Organization_IPointOfSale.htm)

**Comment by Plas-Tek-IgorK** [comment]
Всё ещё не достаточно конкретно описано. "Ставим точку остановка" – куда ставите хотя бы укажите? Внутрь подписчика или на строчку кода

 

Письмом отвечал, там картинка была где стоит точка остановка. В GitHub картинка не передалась L Может поэтому и показалось сумбурно, что ответ сформировал с разметкой html в теле письма с картинкой и отформатированной таблицей сценария. GitHub всю красоту сожрал и стало неинформативно.

 

Ставлю точку останова на первую строчку тела обработчика события. Естественно тела методов в обработчиках есть. Не останавливается?!

 

Вы упомянули про документацию самого метода. Может действительно есть документация по методам интерфейса плагина, а не только либы самой SDK, в которой (в документации) словами было бы описано, какие методы для чего предназначены, как подписываться на обработку событий фронта? Если есть такая, то где посмотреть актуальную версию (нагуглил по плагинам Front 4, но  6 – я версия не соответствует нагугленному описанию).

 

реализацией расчета внешней оплаты по методам CollectData() и OnPaymentAdded(), что такое это расчёт.

 

В примере плагина SDK, при внешней оплате (OnClick кнопки внешней оплаты) по порядку срабатывает два обработчика CollectData() и OnPaymentAdded(). В примере CollectData() есть комментарий, типа обращаемся к внешнему источнику ждите... В методе OnPaymentAdded() идет редактирование/вставка скидки/подарка по внешней оплате. Нужно в каком-то из этих методов вызвать процессинг, который сделает расчет скидки и вернет на кассу. В каком из этих двух методов концептуально правильно реализовывать вызов такого расчета?

 

…вам тоже нужно будет рассказать нам, для чего вам нужен этот Пин-код, чтобы мы могли что-то вам рекомендовать.

В системе процессинга, также, как и на кассе, существует процесс аутентификации кассира. В идеале – это когда все кассиры сети заведены в базу процессинга и при открытии смены они проходят аутентификацию. Все дальнейшие операции этого кассира, проходят аутентификацию и авторизацию по bearer token, который он получил при входе в систему. Это необходимо для безопасности системы процессинга. Также заметили еще один момент из примера… метод operations.ChangePaymentItemSum(paymentItem.Sum + giftSum, giftSum, null, paymentItem, orderWithGift, credentials); Требует credentials. Его нельзя получить без пина. А пин, как вы говорите, глубоко в яйце. Т.е. он нам все равно нужен, чтобы не выводить его во внешний конфигуратор.

 

Про идентификаторы:
Посмотрите на сигнатуры  <https://iiko.github.io/front.api.sdk/v5/html/M_Resto_Front_Api_V5_IOperationService_GetHostTerminalPointsOfSale.htm> OperationService.GetHostTerminalPointsOfSale и соответственно  <https://iiko.github.io/front.api.sdk/v5/html/T_Resto_Front_Api_V5_Data_Organization_IPointOfSale.htm> IPointOfSale

Понял, посмотрю. Спасибо.

**Comment by ierof** [comment]
С вашего позволения, буду отвечать порционно, немного не упорядоченно и не факт, что быстро. 

> Вы упомянули про документацию самого метода. Может действительно есть документация по методам интерфейса плагина, а не только либы самой SDK, в которой (в документации) словами было бы описано, какие методы для чего предназначены, как подписываться на обработку событий фронта? Если есть такая, то где посмотреть актуальную версию (нагуглил по плагинам Front 4, но  6 – я версия не соответствует нагугленному описанию).

Во-первых, есть 
- https://iiko.github.io/front.api.sdk/v4 
- https://iiko.github.io/front.api.sdk/v5
- https://iiko.github.io/front.api.sdk/v6

и поиск внутри них. Ссылки туда можно найти на начальной странице этого проекта ;) 
Там есть поиск http://iiko.github.io/front.api.sdk/v6/search.html?SearchText=SubscribeOnCafeSessionClosing Но да, там автогенерированная документация. И подробностей мало. Примерно то же самое показывает вам R# при написании кода.

А ещё с  домашней страницы этого проекта есть ссылка https://iiko.github.io/front.api.doc/
И вот там есть статья по вашей теме про [Внешние типы оплаты](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html). Она как раз про API v6. В конце неё есть кое-что про кассовые смены.

**Comment by ierof** [comment]
> Ставлю точку останова на первую строчку тела обработчика события. Естественно тела методов в обработчиках есть. Не останавливается?!

Что касается кода открытия и закрытия кассовых смен: *"на моей машине всё работает"* :)
https://i.imgur.com/vILsJzU.gif

Всё-таки у вас не очень конкретное описание. Попробуйте дебажить с помощью логирования (``). Проверьте, не возникает ли у вас исключений в подписчиках на событие.
И, на всякий случай уточню. В вашем первом вопросе под *"событиями открытия/закрытия смены"* вы имеете ввиду кассовую смену, а личную смену какого-либо сотрудника?

**Comment by ierof** [comment]
>  В каком из этих двух методов концептуально правильно реализовывать вызов такого расчета? 

Каких-то концептуальных рекомендаций нет. На "бытовом" уровне разница между `CollectData()` и `OnPaymentAdded()` кроется в названии методов. Первый вызывается когда мы только собирам данные перед добавлением оплаты в заказ. Второй – когда оплата уже лежит в заказе и мы можем выполнить какие-либо пост-события. Т.е. к примеру в методе `CollectData()` можно собрать данные от пользователя (какая карта и т.д.). И если пользователь не ввёл номер карты, оплату не добавлять. А в методе `OnPaymentAdded()` например добавить в заказ какое-либо блюдо или скидку, если этого требует бизнес-логика.

**Comment by ierof** [comment]
> А пин, как вы говорите, глубоко в яйце.

С пин-кодом дела действительно обстоят хуже всего. Через API iikoFront его не получить. Можно делать какие-нибудь хитрости с [API iikoRMS севрера](https://ru.iiko.help/articles/#!api-documentations/employees). Можно вам переложить на пользователей дополнительное конфигурирование плагина, чтобы при настройке интеграции пин-коды прописывались (дублировались) вручную и где-нибудь в хранилище плагина.

> метод operations.ChangePaymentItemSum(paymentItem.Sum + giftSum, giftSum, null, paymentItem, orderWithGift, credentials); Требует credential
Если говорить о таких кейсах, то тут правильнее обязать заводить в iikoOffice специального юзера  для действий от имени вашего плагина. Идеологически это ведь не очень правильно, что скидки будет назначать "кассир Иванов" или "официант Петров". Потому что в системе iiko отслеживается, от чьего имени действие совершается. Именно поэтому для тех операций, где требуется определенный набор прав, в методах API и есть параметр `credentials`.
