### ISSUE TITLE
Проблемы с ApiV6 6.2.4

### ISSUE THREAD

**Issue by TrubovKirill** [iiko/front.api.sdk#82]
При разработки платежного плагина, нам потребовалось использовать ChequeTaskProcessor, а точнее его метод BeforeDoCheque()

Возникли сложности:

1) В документации на iiko.github.io указано, что метод должен возвращать значение типа BeforeDoCheckActionResult. В неймспейсе вообще не нашел такого класса. 
Я предположил что чек дополняется посредством вызова метода Add для параметра CashRegisterChequeExtensions 
Но после успешного выполнения метода, под дебагом смотрел, все значения туда успешно передались, однако чек не был дополнен. Возможно, потому-что параллельно мы подписались на SubscribeOnCashChequePrinting, он вроде как раньше срабатывает, но если даже и так, получается что чек должен был дополнится в CashRegisterChequeExtensions.

В общем хотелось бы услышать как это правильно должно работать.

2) Возник интересный баг - Получается что BeforeDoCheque срабатывает только с фискальными типами оплат, я так понял. При попытки закрыть заказ, где должен сработать этот метод, фронт не дает закрыть заказ, выводит такую ошибку
![image (39)](https://user-images.githubusercontent.com/53934151/62764895-a1451d00-ba97-11e9-96a1-93e9be525fb2.png)

Что интересно, после перезапуска фронта это проходит, случается это с частотой раз в 5-7 закрытий заказа, и при этом из наблюдений BeforeDoCheckAction перестает вызываться.

3) ExternalPaymentProcessor - метод Pay позволяет мне вызвать метод AddOrderExternalData через IOperationService который в него приходит.
Ошибок не выводит, всё замечательно, однако при попытке сделать возврат фронт выдает такую ошибку
![image (28)](https://user-images.githubusercontent.com/53934151/62765218-4eb83080-ba98-11e9-9d61-a7695081f76a.png)

4) на скрине из пункта 3 видно что у нас багнулся viewmanager, 
При первом же вызове    
var cardinput = viewManager.ShowInputDialog("Прокатайте карту или Просканируйте QR - Код", InputDialogTypes.Card);

Все последующие "Схожие" во фронте формы, которые не вызываются плагином, имеют такой title.

**Comment by ierof** [comment]
По п.3 нужен ваш `%appdata\CashServer%`, на котором вы воспроизвели проблему. Желательно — повторить только проблему на чистом CashServer, чтобы был всего один оплаченный вашим типом заказ. Потому что по скрину у вас образовался закрытый заказ с непроведенными платежами.

**Comment by TrubovKirill** [comment]
Теперь метод не выполняется, выдает ошибку, после чистки CashServer

System.InvalidOperationException: Method “CreateEditSession” cannot be called using operation service of ProcessPayment event handler.


Соответственно по п3. вопрос снят, впрочем, логически это и не должно работать, наверное

**Comment by ierof** [comment]
`System.InvalidOperationException: Method “CreateEditSession” cannot be called using operation service of ProcessPayment event handler.`
А вы в своём коде хотите создать сессию редактирования в процессе проведения оплаты? Так нельзя, и именно об этом исключение. 

А что вы хотите сделать?

**Comment by TrubovKirill** [comment]
Я это понимаю, как раз и написал, вопрос под номером 3 снят ввиду того что чистка кэшсервера вернула понятную ошибку после попытки воспроизвести.

**Comment by ierof** [comment]
Хорошо :) Я на всякий случай уточнила. 
Получается, и вопрос 4 снят, потому что он следовал из 3-го?

По вопросу 1: т.к. API V6 ещё не зафиксировано, то сигнатуры могут меняться. В частности, `BeforeDoCheckActionResult` добавился недавно. В релизах 6.4 его ещё нет. Так что если нужно добавлять что-то в чек, пока нужно подписываться на `SubscribeOnCashChequePrinting`

По вопросу 2: да, вы верно заметили, что `BeforeDoCheque` случается только при оплате фискальными типами.  И эта эта ошибка больше похоже на глюк viewManager-а, потому что это не окно ошибки, а какое-то кастомное окно. Или вы выводите сообщение об ошибке, которые  ловите в `catch` таким образом? Но не суть. 
В качестве гипотезы по симптомам, что воспроизводится не сразу: а у вас правильно определен `InitializeLifetimeService`? См. https://github.com/iiko/front.api.sdk/issues/59
Если моя гипотеза не подтвердилась, то опять же, нужны логи с воспроизведением проблемы. Будем разбираться.

**Comment by TrubovKirill** [comment]
по пункту 2 -   public override object InitializeLifetimeService() { return null; } в пеймент процессоре есть, попробую добавить и здесь, похоже на то да)


Сам бы и рад если бы 4й пункт отпал, но нет, к сожалению попробовал еще раз, при первом вызове пеймент плагина где используется viewmanager, все схожите фронтовые месдж боксы имеют тайтл тот который я задал view manager-у при вызове его метода. 

Как конкретно - 
CollectData -    var cardinput = viewManager.ShowInputDialog("Прокатайте карту или Просканируйте QR - Код", InputDialogTypes.Card);

Вот после этой строчки  "Прокатайте карту или Просканируйте QR - Код" встречаю везде на фронтовых окнах где есть тайтл, плагин не при делах уже в этих случаях.

**Comment by ierof** [comment]
Итого, я правильно понимаю, что неразобранной:
Окно с заголовком `"Прокатайте карту или Просканируйте QR - Код"`, которое показывается потом вместо всех окон iiko iikoFront?

Или что-то ещё? Так много разных "веток" дискуссии было изначально, что я могла какую-то "нить" потерять. Давайте ещё раз коротко и по пунктам текущее состояние.

**Comment by TrubovKirill** [comment]
Получается так, всё верно.

**Comment by ierof** [comment]
По заголовку окон: это баг в iiko, спасибо что наши его! Завели в нашем трекере и исправим по приоритетам.

**Comment by ierof** [comment]
<sub>RMS-49834 — внутренний номер</sub>

**Comment by TrubovKirill** [comment]
Спасибо и вам за помощь
