### ISSUE TITLE
UserSessionInvalidException

### ISSUE THREAD

**Issue by theDCM** [iiko/front.api.sdk#83]
Здравствуйте.
Пытаемся добавить скидку в заказ, используем метод IOperationService.AddExternalPaymentItem
Получаем Resto.Front.Api.V5.Exceptions.UserSessionInvalidException
StackTrace:

Server stack trace:
в Resto.Front.Api.V5.AuthenticationService.GetUser(ICredentials credentials) в M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\AuthenticationService.cs:строка 63
в Resto.Front.Api.V5.OperationService.Resto.Front.Api.V5.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession) в M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\Operations.g.cs:строка 2141
в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
в Resto.Front.Api.V5.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession)
в Resto.Front.Api.V5.Extensions.OperationServiceExtensions.AddExternalPaymentItem(IOperationService operationService, Decimal paymentSum, Boolean isProcessed, Object additionalData, IPaymentType paymentType, IOrder order, ICredentials credentials)
в Resto.Front.Api.SamplePlugin.Extenders.PluginWallzyExtender.goo(IOrder order, IOperationService operationService, IProgressBar progressBar) в C:\Users\user1\Desktop\proj\iiko-module-master\Extenders\PluginWallzyExtender.cs:строка 61

**Comment by vcpp** [comment]
#62 не смотрели?

**Comment by theDCM** [comment]
Спасибо
