### ISSUE TITLE
Как узнать версию iiko front api

### ISSUE THREAD

**Issue by wildcherrycandy** [iiko/front.api.sdk#85]
Добрый день!
Мы разрабатываем плагин для iiko front, но с толкнулись с тем, что не можем через SDK узнать версию iiko front. 
Пожалуйста, подскажите, решаемая ли это задача, если решаемая, то какие пути решения имеются?

**Comment by ierof** [comment]
Подскажите, а для какой цели вам нужно узнавать версию iiko?

**Comment by vcpp** [comment]
> не можем через SDK узнать версию iiko front.

Такая возможность появится в V7: [`GetApplicationVersion`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IPluginIntegrationService_GetApplicationVersion.htm).
