### ISSUE TITLE
Тип оплаты как скидка

### ISSUE THREAD

**Issue by aovcharenko** [iiko/front.api.sdk#86]
Добрый день.

Есть ли возможность определить, включен ли для типа оплаты параметр "Проводить как скидку"? Нашел у типа оплаты DiscountType, но это какая-то рекомендованная скидка к типу оплаты, с опцией "Проводить как скидку" не связана. Подскажите, пожалуйста.

**Comment by ierof** [comment]
Нет, этот признак не опубликован в API iikoFront.
Потому что это инфраструктурная настройка для нужд ядра: она влияет, как этот тип поведется фискально и по бухгалтерии.  

А зачем вам требуется узнать данный признак?

**Comment by aovcharenko** [comment]
В систему лояльности полную скидку передать, как на чеке.

**Comment by ierof** [comment]
Посмотрите в сторону выгрузчика чеков :  https://iiko.github.io/front.api.doc/v6/ru/ChequeTaskProcessor
Он больше подходит идеологически, если нужно делать "что-то как в чеке", чтобы не дублировать вычисления и логику, а пользоваться уже агрегированными нужным образом данные.

**Comment by aovcharenko** [comment]
Ок, спасибо.
