### ISSUE TITLE
Блокировка фронта

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#89]
День добрый, клиент захотел следующий сценарий
- после закрытия заказа  осуществлять блокировку экрана с целью контроля кассиров и отчётности по ним
- разблокировка  отпечатком пальца

Если
- разблокировка  отпечатком пальца это закрывается эмуляцией прокатки карты
, то  
- после закрытия заказа фронта осуществлять блокировку экрана
 Не нашли как в апи как и в стандартных настройках

https://ru.iiko.help/articles/#!iikofront-5-4/topic-4/q/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0%20%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B0/qid/222538/qp/1
Из инструкции есть Waiter Lock, по описанию подходит ,можно ли эмулировать его работу?

**Comment by ROSimulin** [comment]
И второй вопрос если можно сюда же
Пользователи хотят сделать авторизацию в бэк офис по отпечатку, из текущей реализации ввод логина и пароля с клавиатуры, можно как-то сделать автоматический запуск офиса с параметрами в виде логина пароля уже забитыми?

**Comment by ierof** [comment]
Ни то, ни другое средствами API iikoFront не сделать.
API это в первую очередь работа с данными, но не с состояниями iikoFront.

**Comment by vcpp** [comment]
> после закрытия заказа фронта осуществлять блокировку экрана

Мне кажется, это можно прямо настройкой в iikoOffice сделать. Там уже есть настройки, куда переходить после печати блюд и после печати пречека, в обоих случаях доступен вариант «Блокировать терминал». Подумаем, не сделать ли настройку, куда переходить после оплаты.

Если не трудно, можете поподробнее описать, как блокировка терминала после оплаты поможет *контролировать кассиров и отчётность по ним*? Что плохого может сделать кассир, если не заблокировать терминал после оплаты? Для защиты от посторонних (если кассир отошёл, забыв заблокировать) есть автоблокировка по таймауту бездействия.

**Comment by ROSimulin** [comment]
Да всё просто 2 кассира каждый из которых по очереди принимают заказ на 1 фронте, отходят и его выполняют, а мотивация настроена на личные заказы, чтобы не было ошибок нужно блокировать фронт после оплаты

**Comment by ROSimulin** [comment]
концепция кофейни мелкой и проблемы начинаются при наличии очереди, кассиры забывают разлогиниться
