### ISSUE TITLE
Работа с API из стороннего ПО

### ISSUE THREAD

**Issue by iDoctor** [iiko/front.api.sdk#9]
Добрый день.

Скомпилировал библиотеку Resto.Front.Api.SamplePlugin, к Фронту подцепляется, методы выполняются.
Однако, мы ведь создаём в первую очередь "прослойку" между iiko Front и нашим приложением. Поэтому, создали простое консольное тестовое приложение, подцепили собранную библиотеку Resto.Front.Api.SamplePlugin, но при попытке вызова какого-либо метода из этой библиотеки выбивает сообщение: "Plugin context isn't initialized".
Повторюсь, данная библиотека успешно подцепляется к Фронту, но к нашему приложению - нет.

Скажите, пожалуйста, почему это происходит и как обойти данную проблему?

**Comment by ierof** [comment]
https://iiko.github.io/front.api.doc/v6/ru/Intro.html

> Для загрузки каждого плагина iikoFront создаёт отдельный процесс-контейнер и загружает плагин в него, это позволяет избежать конфликтов зависимостей и обеспечивает надёжность системы (сбой в одном из плагинов не обрушит всё остальное). Каждый плагин устанавливается в отдельную подпапку папки Plugins, по умолчанию расположенной в C:\Program Files\iiko\iikoRMS\Front.Net. Сборка плагина должна содержать класс, имеющий публичный конструктор по умолчанию (без параметров) и реализующий интерфейс IFrontPlugin.

Если более простыми словами: просто подключить dll к своему проекту недостаточно, нужно, чтобы данная dll была инстанцирована хостом (`Resto.Front.Api.Host.exe`).  
И ещё кое-что про отладку можно почитать [тут|https://iiko.github.io/front.api.doc/v6/ru/Debugging.html].

**Comment by iDoctor** [comment]
Мы используем SamplePlugin. Интерфейс IFrontPlugin присутствует:
`public sealed class SamplePlugin : IFrontPlugin`
Для начала мы хотим попытаться взаимодействовать с iikoFront хотя бы любым методом.
Пробуем отправить сообщение в GUI через `PluginContext.Operations.AddWarningMessage()`
 Однако, выбивает ошибку "Plugin context isn't initialized".
Не совсем понял как можно обойти эту проблему.

**Comment by ierof** [comment]
Чтобы понять, как обойти вашу проблему, давайте попробуем синхронизировать наши знания о ней ;)
Вы понимаете, что вы пишете плагин к iikoFront? Как написано в документации, и как был сказано выше *"Каждый плагин устанавливается в отдельную подпапку папки Plugins, по умолчанию расположенной в C:\Program Files\iiko\iikoRMS\Front.Net."*
Последовали ли вы этой инструкции?

**Comment by iDoctor** [comment]
Давайте синхронизируем :)
В нашем случае плагин располагается в каталоге C:\Program Files\iiko\iikoRMS\Front.Net\Plugins\Resto.Front.Api.SamplePlugin

**Comment by ierof** [comment]
И при этом этот плагин не может воспользоваться ‘PluginContext’-ом? Или что-то другое — например, ваше тестовое приложение, которое работает вне iikoFront — не может воспользоваться этим статическим классом?

**Comment by iDoctor** [comment]
Плагин контактирует с iikoFront, но с нашим тестовым приложением не может установить связь.

**Comment by ierof** [comment]
Просто подкючив dll с API iikoFront или dll плагина к вашему тестовому приложению «канала» на iikoFront не будет. Это следует из тех принципов, что описаны во введении. 

В самом плагине может быть реализован клиент любого сервиса, любая «прослойка».

**Comment by iDoctor** [comment]
Вас понял! Значит все алгоритмы по обмену данными между системами необходимо будет реализовывать в текущем плагине (по крайней мере частично точно).
Спасибо!

**Comment by iDoctor** [comment]
Ирина, скажите, пожалуйста, собранный плагин в любом случае должен быть на выходе dll или это не обязательное условие?

Перед нами стоит следующая задача. Мы хотим из 1С и нашего веб-портала отправлять заказы прямо на iikoFront. Наиболее подходящим вариниантом, пожалуй, будет RESTful-сервис.
И вот здесь не совсем понятно как заставить работать наш WebApplication с iikoFront.
Если с обычным приложением (a-la Resto.Front.Api.SamplePlugin) ясно следующее: написан класс с интерфейсом IFrontPlugin, в котором вызываются другие методы. Output type проекта выставляем в Class library, подкидываем в каталог Plugins и всё.

Что нам необходимо подкорректировать, чтобы связать веб-сервис с iikoFront и получить/передать данные по заказу?
На разных ресурсах описывается различная информация по вытягиванию данных, не можем связать всё воедино :)
https://examples.iiko.ru/front/
http://help.iiko.ru/articles/#!api-documentations/authorization
http://help.iiko.ru/articles/#!api-documentations/front-web-api

**Comment by vcpp** [comment]
> собранный плагин в любом случае должен быть на выходе dll или это не обязательное условие?

Это обязательное условие.

> Что нам необходимо подкорректировать, чтобы связать веб-сервис с iikoFront и получить/передать данные по заказу?

Один из вариантов — поднять в рамках плагина веб-сервер (`System.Web.Http.SelfHost`), который при получении запросов на создание заказа будет создавать их в iikoFront. То же самое, что SamplePlugin, только в версии из SDK заказ создаётся нажатием на кнопку с какими-то зашитыми в коде блюдами, а у вас эта «кнопка» будет нажиматься по сети, состав заказа будет передаваться в теле запроса. Для этого варианта потребуется белый IP или ddns на машине с iikoFront, чтобы выступающий в роли клиента внешний сервис мог слать запросы в поднятый плагином веб-сервер.

Другой вариант — реализовать веб-сервер на базе 1С или веб-портала, а плагин заставить забирать оттуда заказы. Неудобство этого варианта в том, что инициатива на стороне плагина (он клиент), а заказы появляются на сервере, и плагин не знает, когда за ними идти. Понадобятся push notifications, либо long polling, зато можно спрятать iikoFront за NAT'ом и ходить наружу с серым IP.

> На разных ресурсах описывается различная информация по вытягиванию данных, не можем связать всё воедино :)

Все ссылки про другие API. Самое близкое — это Web API приложения iikoFront, но там пока доступ только на чтение.

**Comment by iDoctor** [comment]
> Все ссылки про другие API. Самое близкое — это Web API приложения iikoFront, но там пока доступ только на чтение.
Можно ли получить доступ к исходникам Plugin.Front.Api.Webapi? Хотим потестировать функционал.

**Comment by vcpp** [comment]
> Можно ли получить доступ к исходникам Plugin.Front.Api.Webapi?

Вероятно, вопрос был про плагин *Resto.Front.Api.WebServer*. Нет, этот плагин предоставляется как готовый продукт, его исходники не публикуются.

> Хотим потестировать функционал.

Какую именно функциональность хотите потестировать?
Свои плагины мы сами тестируем :-)

Вам нужно определиться с тем, как вы будете забирать данные из внешнего источника (сервер 1С, веб-портал), и это не связано с iikoFront API. Для начала можете считать, что пишете независимое консольное приложение, которое просто выводит на экран полученные данные. Когда это будет готово, останется поменять тип приложения с консольного на плагин и направлять данные не на экран, а в iikoFront API, это уже дело техники, если не будет получаться — поможем.

**Comment by iDoctor** [comment]
Создали консольное Self-Host приложение. В обычном режиме корректно работает.
А вот как из класса с интерфейсом IFrontPlugin запустить данный сервис не представляем.
Подскажите, пожалуйста, как можно сдружить iikoFront с плагином. Наш пробный код ниже.

[Чистое Self-Host приложение](http://DoctorIkari.quickconnect.to/d/f/470369449401131017)
[Приложение с Get/Post методами iiko](http://DoctorIkari.quickconnect.to/d/f/470369449961070603)

**Comment by ierof** [comment]
> А вот как из класса с интерфейсом IFrontPlugin запустить данный сервис не представляем.

Тогда это может быть очень долгий рассказ с нашей стороны "как писать на c#"...

Посмотрела ваш проект. `// КАК ЗАПУСТИТЬ ВЕБ-СЕРВИС?`
Точно так же, как вообще выполнить любую бизнес-логику: написать её :)

Пробовали в конструкторе объекта `iikoInit` написать то же самое, самое, что и в классе `Program`?

**Comment by iDoctor** [comment]
Разобрались, спасибо! :)
