### ISSUE TITLE
Как определить pin

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#90]
Добрый день. 
Для того чтоб получить `ICredentials` необходимо вызвать метод
ICredentials credentials = operationService.AuthenticateByPin(**pin**);
Скажите пожалуйста  есть ли возможность через API получить значение **pin**.

**Comment by vcpp** [comment]
Нет.

Для плагина, управляемого сотрудником, например, мобильный терминал официанта, предполагается, что сотрудник вводит пин-код своей учётки и далее плагин выполняет действия от его имени (по аналогии с UI самого iikoFront).

Для плагина, ведущего самостоятельную фоновую деятельность, нужно в iikoOffice создать отдельную учётную запись, выдать необходимые права, назначить пин-код и указать этот пин-код в настройках плагина (в конфиге).
Мы всё собираемся автоматизировать создание учётной записи для плагина, но пока это не сделано.
