### ISSUE TITLE
День добрый, интеграция с бонусной системой

### ISSUE THREAD

**Issue by ROSimulin** [iiko/front.api.sdk#91]
Дано есть внешняя бонусная система
В систему прошиты запросы
- накопление бонусов - списание бонусов - отмена бонусов
Каждая операция должна быть подтверждена одноразовым кодом, который предоставляет клиент
- Нужно выводить информацию о баллах / сумме к оплате на причеке 

SubscribeOnBeforeOrderBill Method - тут да мы можем каждый раз спрашивать про наличие бонусной карты и делать то что нам надо

Но нам нужна аналогия на Отмену пречека
Т.к для отмены причека нужно ввести одноразовый код для отмены транзакции

Интеграция с такой логикой нам и кард 5 не подходит исходя из вышеперечисленных ограничений

**Comment by CLTanuki** [comment]
@ROSimulin , для реализации подобных штук в SDK есть SamplePaymentPlugin. Рекомендую ознакомиться.

**Comment by ROSimulin** [comment]
Да я уже поговорил с Русланом на эту тему, и он тоже согласился что 2 пути либо менять апи айки ли меня апи бонусной системы. У нас достаточно большой опыт работы с пеймент плагинами

**Comment by vcpp** [comment]
> нам нужна аналогия на Отмену пречека
Т.к для отмены причека нужно ввести одноразовый код для отмены транзакции

Я правильно понимаю, что вы хотите зарегистрировать обработчик, который синхронно вызовется перед отменой пречека с возможностью прервать операцию?

Можете подробнее описать сценарий использования, в какой момент начисляются бонусы, в какой момент списываются/отменяются? Какие возможны злоупотребления, если пользователи будут отменять пречек без подтверждения кодом от клиента?

**Comment by ROSimulin** [comment]
-правильно

Учитывая ограничения апи  внешней бонусной системы, бонусы должны начисляться в момент выдачи причека и подтверждены одноразовым кодом паролем который действует 4 минуты

Отменяться бонусы также должны вместе с отменой причека и тоже при участии гостя, если гостя нет то отменить причек нельзя т.к в противно случае возможны махинации с бонусными балансами и ошибки линейного персонала , которые приведут к тому что гости получат неверное кол-во бонусов

Например махинации что был чек 5000 р, начислили бонусы, отменили причек, разделили заказ на 2 по 2500, на второй тоже прикрепили гостя и начислили бонусы

Оба заказа в впоследствии закрыли на нефискальный чек оплаты

Т.к у нас нет исключений на всех этапах данной махинации то с заказа в 5000 рублей будет начислено не 500 бонусов а 750

**Comment by vcpp** [comment]
> Например махинации что был чек 5000 р, начислили бонусы, отменили причек, разделили заказ на 2 по 2500, на второй тоже прикрепили гостя и начислили бонусы

На мой взгляд, это должно решаться не запретом отмены пречека, а безусловной отменой бонусов, которые были начислены при пречеке.
Пречекнули заказ на 5000 — начислили бонусы с 5000. Отменили пречек — отменили начисление бонусов, вернулись в исходное состояние.
Разделили заказ, пречекнули два заказа на 2500 — начислили бонусы с двух заказов по 2500. В итоге всё сойдётся.

Уведомление об отмене пречека есть: [`OrderBillCancelled`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_INotificationService_OrderBillCancelled.htm).
