### ISSUE TITLE
Бзналичный расчет

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#92]
Добрый день
В реализации метод `OnPaymentAdded `интерфейса `IExternalPaymentProcessor`, наш плагин выбрасывает исключения `PaymentActionCancelledException `и `PaymentActionFailedException `для прерывания процесса оплаты бонусами. После этого на кассе появляется "Бзналичный расчет". Возможно ли удалить "Бзналичный расчет" через API. 

![image](https://user-images.githubusercontent.com/51437851/65615668-cb608900-dfca-11e9-938f-02f350deb679.png)

**Comment by vcpp** [comment]
Если вы хотите отменить добавление оплаты в заказ, попробуйте выбросить [`PaymentActionCancelledException`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_Exceptions_PaymentActionCancelledException.htm) из метода [`CollectData`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_CollectData.htm). Данный метод вызывается перед добавлением оплаты.
Метод [`OnPaymentAdded`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IExternalPaymentProcessor_OnPaymentAdded.htm) вызывается уже после добавления оплаты в заказ, когда отменять добавление уже поздно. После этого остаётся только удалять оплату ([`DeletePaymentItem`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Editors_IEditSession_DeletePaymentItem.htm)).

**Comment by HakobyanAram** [comment]
Мы имплементируем 2D сканнер. Нам посоветовали использовать внешний тип оплаты.
Для сканирования карты мы реализовали следующие шаги:
1. В CollectData открываем диалог (viewManager.ShowExtendedNumericInputPopup)
2. Сканируем карту
3. Например, если карта скидочная назначаем скидку  operationService.AddDiscount (т.к.CollectData не имеет аргумент  IOperationService operationService следовательно мы не можем в методе CollectData  назначать скидку)

Мы попробовали вызвать метод  DeletePaymentItem. Если карта скидочная то при вызове метода DeletePaymentItem получаю следующее уведомление
![image](https://user-images.githubusercontent.com/51437851/65819253-5dff6300-e22b-11e9-8280-a303abd41b84.png)
Если карта бонусная и сумма бонуса = 0, при вызове метода  DeletePaymentItem удаляются и "Безналичный расчет" и "Оплата наличными", что не удобно для кассира он должен повторно нажать на кнопку "Оплата наличными"
![image](https://user-images.githubusercontent.com/51437851/65819375-c4d14c00-e22c-11e9-99df-7baacf889b80.png)

Мы попробовали вызвать метод DeleteExternalPaymentItem. 
При вызове этого метода в любом случае (если карта скидочная или бонусная) получаем уведомление 
![image](https://user-images.githubusercontent.com/51437851/65819253-5dff6300-e22b-11e9-8280-a303abd41b84.png)

**Comment by CLTanuki** [comment]
> Мы имплементируем 2D сканнер. Нам посоветовали использовать внешний тип оплаты.
> Для сканирования карты мы реализовали следующие шаги:
> 
> 1. В CollectData открываем диалог (viewManager.ShowExtendedNumericInputPopup)
> 2. Сканируем карту
> 3. Например, если карта скидочная назначаем скидку  operationService.AddDiscount (т.к.CollectData не имеет аргумент  IOperationService operationService следовательно мы не можем в методе CollectData  назначать скидку)
> 
> Мы попробовали вызвать метод DeletePaymentItem. Если карта скидочная то при вызове метода DeletePaymentItem получаю следующее уведомление
> ![image](https://user-images.githubusercontent.com/51437851/65819253-5dff6300-e22b-11e9-8280-a303abd41b84.png)
> Если карта бонусная и сумма бонуса = 0, при вызове метода DeletePaymentItem удаляются и "Безналичный расчет" и "Оплата наличными", что не удобно для кассира он должен повторно нажать на кнопку "Оплата наличными"
> ![image](https://user-images.githubusercontent.com/51437851/65819375-c4d14c00-e22c-11e9-99df-7baacf889b80.png)

Добрый день.
Простите, а что в логах? И покажите код, пожалуйста.

**Comment by HakobyanAram** [comment]
> Простите, а что в логах? И покажите код, пожалуйста.
Добрый день.
Выкладываю логи.
[api.log](https://github.com/iiko/front.api.sdk/files/3712174/api.log)
[cash-server.log](https://github.com/iiko/front.api.sdk/files/3712175/cash-server.log)

```
  public void CollectData(Guid orderId, Guid paymentTypeId, [NotNull] IUser cashier, IReceiptPrinter printer,
            IViewManager viewManager, IPaymentDataContext context, IProgressBar progressBar)
        {
            ExtendedInputSettings settings = new ExtendedInputSettings {EnableCardSlider = true, EnableNumericString = true, TabTitleNumericString = "Введите нoмер карты"};
            ICardInputResult result = viewManager.ShowExtendedNumericInputPopup("Test loyalty", "", settings) as ICardInputResult;
            context.SetRollbackData<CollectedData>(new CollectedData() {ScannedValue = result.Track2});
        }
```

```
  public void OnPaymentAdded([NotNull] IOrder order, [NotNull] IPaymentItem paymentItem, [NotNull] IUser cashier,
            [NotNull] IOperationService operationService, IReceiptPrinter printer, IViewManager viewManager,
            IPaymentDataContext context, IProgressBar progressBar)
        {
            CollectedData collectedData = context.GetRollbackData<CollectedData>();
            if (collectedData != null)
            {
                IikoWaiterCheckinResponse passResponse = GetPassScannedResponse(order, operationService, collectedData);
                ICredentials credentials = operationService.AuthenticateByPin("1945");
                if (passResponse.Pass.LoyaltyType == LoyaltyType.CASHBACK)
                {
                    PluginContext.Log.Info("Bonus Card");
                    if (viewManager.ShowYesNoPopup("Test", $"Накопленная сумма {100}\n Вы хотите применить бонусы?"))
                    {
                        PluginContext.Log.Info("Bonus Card");
                        operationService.ChangePaymentItemSum(100, 0, 100, paymentItem, order, credentials);
                    }
                    else
                    {
                        operationService.DeletePaymentItem(paymentItem, order, credentials);
                    }
                }
                else
                {
                    var discountType = PluginContext.Operations.GetDiscountTypes().Last(x => !x.Deleted && x.IsActive && !x.DiscountByFlexibleSum && x.Name == "LoonaLevel1");
                    operationService.AddDiscount(discountType, order, credentials);
                    operationService.DeletePaymentItem(paymentItem, order, credentials);
                }
            }
        }
```

**Comment by CLTanuki** [comment]
1. Вместо SetRollbackData для отмены платежа рекомендую (на мой взгляд эстетичнее) использовать SetCustomData.
2. Рекомендую обернуть всё в try-catch и ловить все ошибки там.
3. Переполчайте order новой ревизии перед каждым изменением через ```order = operationService.GetOrderById(order.Id)``` и будет Вам счастье.

**Comment by HakobyanAram** [comment]
> Переполчайте order новой ревизии перед каждым изменением через order = 

operationService.GetOrderById(order.Id) и будет Вам счастье.
Спасибо за ответ вызвал `GetOrderById` и эта ошибка  не вскакивает
![image](https://user-images.githubusercontent.com/51437851/65819253-5dff6300-e22b-11e9-8280-a303abd41b84.png)

но  остался вопрос этот вопрос открытым

> при вызове метода  DeletePaymentItem удаляются и "Безналичный расчет" и "Оплата наличными", что не удобно для кассира он должен повторно нажать на кнопку "Оплата наличными"
![image](https://user-images.githubusercontent.com/51437851/65819375-c4d14c00-e22c-11e9-99df-7baacf889b80.png)

**Comment by CLTanuki** [comment]
Цепляйтесь дебаггером и смотрите, сколько раз вызывается и что передаётся.

**Comment by vcpp** [comment]
> при вызове метода DeletePaymentItem удаляются и "Безналичный расчет" и "Оплата наличными", что не удобно для кассира он должен повторно нажать на кнопку "Оплата наличными"

Вероятно, «Наличные» удаляются не при вызове `DeletePaymentItem`, а раньше, при добавлении вашего типа «Loona Payment». При навигации на экран оплаты автоматически был выбран тип оплаты по умолчанию «Наличные», но кассир выбрал другой тип оплаты и другая оплата успешно добавилась. Поскольку добавленные по умолчанию «Наличные» не пригодились, они удаляются из заказа так же автоматически, как и добавились при навигации. На момент вызова `OnPaymentAdded`, надо полагать, в заказе только одна оплата — «Loona Payment». Когда вы её удаляете, список оплат остаётся пустым.

Могу предложить два варианта решения:
* Изящный — собирать все необходимые для оплаты данные на этапе `CollectData` и, если тип оплаты использовать нельзя, то и не позволять его добавить в заказ, сразу из `CollectData` выбрасывать исключение. Если тип оплаты использовать можно, и в связи с этим вы хотите внести в заказ какие-то изменения, сохраните собранную в `CollectData` информацию, чтобы внести изменения, когда оплата будет добавлена, то есть в `OnPaymentAdded`. Выброс исключения из `CollectData` приводит к отмене выбора нового типа оплаты, соответственно, предыдущий тип оплаты («Наличные») не удаляется. Плюсы: не добавляем то, что нельзя добавить, чтобы потом не удалять ошибочно добавленное, ну и ранее выбранная оплата не удаляется в случае отмены.
* Запасной — если вы решили сами манипулировать списком оплат, помимо удаления ненужного можете сами же добавить нужное. В `CollectData` запомните, какой тип оплаты был выбран до вашего, затем, если в `OnPaymentAdded` решите удалять свой тип оплаты, сможете вернуть в заказ предыдущий.
