### ISSUE TITLE
Типы скидок и правила

### ISSUE THREAD

**Issue by CLTanuki** [iiko/front.api.sdk#93]
Добрый день, коллеги.
Собственно, вопрос: как получить правила для автоматических скидок, если в интерфейсе IDiscountType есть только boolean? История в том, что мы добавляем заказ на кассу и потом добавляем внешнюю оплату на его сумму, однако где-то посреди применяется автоматическая скидка и сумма, которую мы добавляем становится "слишком большой".
Итого мы только можем понять, что скидка ВОЗМОЖНО будет применена в некоторых случаях автоматически.

1. Да, мы знаем, что можно провести всё это в одной транзакции.
2. Нет, мы не хотим лишать клиентом из внешнего источника скидок.

![Screenshot at 2019-10-10 12-44-26](https://user-images.githubusercontent.com/5824716/66558127-b99aec00-eb5b-11e9-9358-ef3fe82f1acf.png)

**Comment by vcpp** [comment]
> как получить правила для автоматических скидок

Никак, это деталь реализации.
Некоторые из этих скидок могут вычисляться внешними сервисами, при этом правила вычисления не будет знать даже само приложение iikoFront. Некоторые скидки имеют довольно сложные правила, не хотелось бы без острой необходимости документировать и публиковать это, провоцируя разработчиков плагинов дублировать логику применения этих скидок. Надо искать другие решения.

> где-то посреди применяется автоматическая скидка и сумма, которую мы добавляем становится "слишком большой"

Вы бы хотели зафиксировать сумму заказа, чтобы ни блюда нельзя было добавлять/удалять, ни скидки не применялись, не изменения цен, ничего? Можете подробнее описать сценарий?

**Comment by CLTanuki** [comment]
Мы можем зафиксировать, пройдя сценарий в одной транзакции так, чтобы фронт не успел применить скидки. Однако, нельзя ли какой-то метод, который будет возвращать заказ после калькуляций, но до создания?

**Comment by vcpp** [comment]
> нельзя ли какой-то метод, который будет возвращать заказ после калькуляций, но до создания?

Вы хотите при создании заказа предварительно узнать его сумму с учётом скидок, чтобы добавить внешнюю оплату на точную сумму? А что если сумма заказа изменится после этого? Например, начнут или перестанут действовать автоматические скидки, поменяются цены и т. д.

Просьба подробнее описать сценарий.

**Comment by CLTanuki** [comment]
В идеале хочется иметь, который позволит, передав заказ, получить все скидки и прочие условия программ лояльности, которые будут применены к нему после создания.
Допустим:
```cs
IOrder CheckOrderCreationResul(IOrder Order)
```

Где будет заполнено поле
```cs
IReadOnlyList<IDiscountItem> Discounts
```

А также расширение для IDiscountType:
Допустим:
```cs
public interface IDiscountTypeExtended : IDiscountType
{
    List<IDiscountableProduct> affectedProducts; // список продуктов, к которым может быть применена скидка
}

public class IDiscountableProduct
{
    IProduct product;
    IDiscountCondition;
}

public class IDiscountCondition
{
    int minAmount;
    int maxAmount;
    List<IProduct> shoulBeCombinedWith;
}
```

Это всего лишь идеи, так как я не очень глубоко знаю код iiko Front.

**Comment by CLTanuki** [comment]
Добрый день.
Смею напомнить об этой заявке.

Конечно, можно создать заказ и проверить, какие скидки применились, но можно ли это как-то сделать без непосредственного создания заказа? А то не все сессии заканчиваются оплатой и при использовании внешних интерфейсов создания заказов (например, терминала самообслуживания), очень много заказов, созданных ради калькуляции, придётся отменять.

Вероятно, помог бы даже аналог метода GetOrderAppliedDiscounts для IEditSession.

**Comment by vcpp** [comment]
> В идеале хочется иметь, который позволит, передав заказ, получить все скидки и прочие условия программ лояльности, которые будут применены к нему после создания.

Лет 5 назад была идея реализовать пробное применение изменений, то есть некий аналог метода [`SubmitChanges`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_SubmitChanges.htm), который вернёт результат применения изменений, но при этом не сохранит эти изменения. Предполагалось, что можно будет создать сессию редактирования, накидать каких-то действий, применить их понарошку, получив результат, который никуда не сохранён, накидать ещё действий, ещё раз понарошку применить, ..., в конце либо вызвать `SubmitChanges` для реального применения с сохранением, либо просто скормить сессию сборщику мусора, словно и не было ничего. Внутренний номер задачи: RMS-41559. С учётом высокой трудоёмкости и незначительного спроса эта задача висит без движения с 2016 года и, вероятно, будет висеть и дальше.

Чем изобретать dry run mode, оказалось проще к уже существующей функции создания заказов добавить функцию их бесследного физического удаления. Используйте [`DeleteOrderAndHideItemsFromOlap`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_DeleteOrderAndHideItemsFromOlap.htm) для обычных и [`CancelNewDeliveryAndHideItemsFromOlap`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_CancelNewDeliveryAndHideItemsFromOlap.htm) для доставочных заказов, чтобы удалять их так, словно они никогда и не создавались. Удалённые таким способом заказы не попадут в отчёты и, таким образом, не будут искажать статистику. Единственное, выданные этим заказам номера уйдут вместе с ними, образуя пропуски в нумерации.

> очень много заказов, созданных ради калькуляции, придётся отменять.

Досадно получилось — функция бесследного удаления заказов реализована в 2017 году, вы задали вопрос в 2019 году, а то, что эта функция, кажется, решает вашу задачу, мы поняли лишь в 2021 году.
