### ISSUE TITLE
Удаление или возврат оплаты закрытого закза

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#94]
Добрый день. 
Мы имплементируем собственную систему лояльности.
В iiko front возможно либо удалить либо вернуть оплату уже закрытого заказ.
В нашей системе необходимо знать удалился ли уже закрытый заказ, или производился ли возврат оплаты закрытого заказа.
Скажите пожалуйста на какое сабытие нужно подписатся чтобы перехватывать эти события.

**Comment by vcpp** [comment]
> необходимо знать удалился ли уже закрытый заказ, или производился ли возврат оплаты закрытого заказа.

За возвратами можно следить через [`SubscribeOnOrderStorning`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_Extensions_NotificationServiceExtensions_SubscribeOnOrderStorning.htm).
За удалениями можно следить через общую подписку на [`OrderChanged`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_INotificationService_OrderChanged.htm) с фильтром по `EventType == EntityEventType.Removed`.
