### ISSUE TITLE
external payment type

### ISSUE THREAD

**Issue by 6ruse** [iiko/front.api.sdk#95]
began to make the appearance of payment, made a simple preparation:
unit uIExternalPaymentProcessor;

interface

type IExternalPaymentProcessor = interface
    function PaymentSystemKey : string;
    function PaymentSystemName : string;
end;

{this function returns an instance of the interface}
function testInt : IExternalPaymentProcessor; stdcall; export;

type

TTestInt = class(TInterfacedObject,IExternalPaymentProcessor)
    function PaymentSystemKey : string;
    function PaymentSystemName : string;
end;

implementation

function testInt : IExternalPaymentProcessor;
begin
  result := TTestInt.Create;
end;

{ TTestInt }

function TTestInt.PaymentSystemKey: string;
begin
  result := 'PaymentSystemKey';
end;

function TTestInt.PaymentSystemName: string;
begin
  result := 'PaymentSystemName';
end;

end.

Manifest.xml

<?xml version="1.0" encoding="utf-8" ?>
<Manifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema ../Binaries/iiko/Manifest.xsd">
  <FileName>TuvisIIKO.dll</FileName>
  <TypeName>TestInt</TypeName>
  <ApiVersion>V6</ApiVersion>
  <LicenseModuleId>21005108</LicenseModuleId>
</Manifest>

but this type of payment does not appear on the list. what am I doing wrong?

**Comment by vcpp** [comment]
> but this type of payment does not appear on the list

It seems that you have only implemented some interface and no one knows about it.
First of all, you have to register your payment system (implementation of `IExternalPaymentProcessor`) by calling the [`RegisterPaymentSystem`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_RegisterPaymentSystem.htm) method. You will then be able to create one or more payment types based on your payment system. Payment types currently cannot be created and configured via API, do it manually using iikoOffice app.
Have you read the corresponding [article](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html) (in russian)?
Have you looked at the [sample payment plugin](https://github.com/iiko/front.api.sdk/tree/master/sample/Resto.Front.Api.SamplePaymentPlugin)?

**Comment by vcpp** [comment]
The issue has been closed by inactivity timeout. If it is still relevant for you, please, answer for the questions and provide missing info.
