### ISSUE TITLE
пример API

### ISSUE THREAD

**Issue by 6ruse** [iiko/front.api.sdk#96]
доброго времени суток!
1. скачал пример АПИ с https://github.com/iiko/front.api.sdk
2. открыл его в Microsoft Visual Studio 2019
3. в файле SamplePaymentPlugin.cs изменил [PluginLicenseModuleId(21016...)] (21016... наш)
4. собрал dll ctrl+sft+b
5. содержимое положил в ..\iiko\iikoRMS\Front.Net\Plugins\my.pay\
6. пытаюсь зарегистрировать безналичный способ оплаты, в окне выбора безналичного типа оплаты, ничего не выбирается.

что мы делаем не так?

**Comment by vcpp** [comment]
> что мы делаем не так?

Не читаете [документацию](https://iiko.github.io/front.api.doc/v6/ru/PaymentProcessor.html), переспрашиваете, игнорируя предыдущий [ответ](https://github.com/iiko/front.api.sdk/issues/95#issuecomment-544866422) :-(

Давайте этот вопрос закроем как дубликат и продолжим в #95.
