### ISSUE TITLE
Ошибки в примера и реальные результаты

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#97]
`       
         
        /// Печать текстового (нефискального) чека, информационного, рекламного, пречек и т.д.
        /// Могут присутствовать следующие теги:<para />
        /// <![CDATA[<f0/>]]> - дальше будет шрифт 0<para />
        /// <![CDATA[<f1/>]]> - дальше будет шрифт 1<para />
        /// <![CDATA[<f2/>]]> - дальше будет шрифт 2<para />
        /// <![CDATA[<papercut/>]]> - отрез ленты<para />
        /// <![CDATA[<bell/>]]> - звонок<para />
        /// <![CDATA[<barcode data="..."/>]]> - штрихкод<para />
        /// <![CDATA[<logo data="..."/>]]> - логотип<para />
        /// <![CDATA[<qrcode size="..." correction="...">...text...</qrcode>]]> - QR-код<para />
        /// </summary>
        /// <param name="text">Текст для печати, строки разделены символом LF (\\n)</param>
        public void PrintText(string text)
        {
            PluginContext.Log.InfoFormat("Device: '{0} ({1})' printed text {2}", DeviceName, deviceId, text);
        }
`

Коллеги, в версии 7 тег papercut неожиданно стал pagecut.

**Comment by vcpp** [comment]
Похоже, ошибка в примере. Тэгом для отреза ленты всегда был `pagecut`.

**Comment by igorpooh1978** [comment]
В шестой версии был именно papercut, мы почему и удивились, когда принтер прекратил отрезку бумаги

**Comment by fraddy91** [comment]
Изначально такая ошибка была допущена, вылилась она в проблемы при межплагинном и межсервисном взаимодействии (все остальное оборудование работает с `pagecut`). Как вы правильно заметили, в 7 версии тег для внешних устройств был заменён на `pagecut`.

**Comment by vcpp** [comment]
Версия V6 [зафиксирована](https://iiko.github.io/front.api.doc/2019/10/14/v6-release.html) в iikoRms 7.0 сразу с тэгом `pagecut`. Что там было до заморозки, неважно, на этапе разработки возможны любые изменения.
Проблема только с версией V6Preview5, которая была зафиксирована с тэгом `papercut`, но начиная с iikoRms 7.0 тихо перешла на `pagecut`. Это breaking change, увы, не уследили. Сейчас уже с этим ничего не поделаешь, чинить не смысла, ибо в 7.1 поддержка V6Preview5 прекратится. Решение — переход на V6.
