### ISSUE TITLE
Редактирование заказа

### ISSUE THREAD

**Issue by popowich** [iiko/front.api.sdk#98]
Здравствуйте. Есть необходимость добавить ценовую категорию в заказ, когда заказ открыт на фронте. Получаю ошибку One or more objects used in edit session are already in use я конечно понимаю необходимость лочить объект заказа от других терминалов, при его редактировании, но почему нужно его лочить от локальных плагинов ? насколько я понимаю есть единственная возможность изменить заказа только в контексте события OrderChanged ? или все же есть возможность изменить открытый на фронте заказ из локального плагина ? очень нужно

**Comment by popowich** [comment]
Я реализовывал не мало плагинов и активно юзаю изменение заказа в OrderChanged  например такой код вполне успешно отрабатывает в этом событии

var order = PluginContext.Operations.GetOrderById(orderId);
var iikoPaymentType = PluginContext.Operations.GetPaymentTypeById(paymentTypeId);
var editSession = PluginContext.Operations.CreateEditSession();
editSession.AddPaymentItem(order.FullSum, new CreditPaymentItemAdditionalData{CounteragentUserId = guestId }, iikoPaymentType, order);

PluginContext.Operations.SubmitChanges(PluginContext.Operations.AuthenticateByPin(PluginSettings.Instance.UserPin), editSession);

Я думал это фича, а не баг))) Но спасибо за ответ. В огромном количестве сценариев требует возможность изменения редактируемого заказа, буду надеяться вы что то сделаете с этим

**Comment by letolica** [comment]
Готово. [Экран редактирования заказа позволяет вносить изменения по инициативе плагина](https://iiko.github.io/front.api.doc/2020/10/20/edit-current-order.html).

**Comment by popowich** [comment]
@letolica Вот это подарок по НГ!!! респектую всеми руками и ногами ))) реально Вы решили самую большую проблему своего API Спасибо!
