### ISSUE TITLE
ResultSum с автоматически добавленными скидками

### ISSUE THREAD

**Issue by Azamatjon** [iiko/front.api.sdk#99]
Добрый день,
Пплагин для онлайн оплаты недавно перестал работать корректно. Дело в том что ResultSum не учитывает автоматически добавленную (привязанную на тип оплату) скидку. В методе onPaymetAdded() через order.ResultSum не получается брать эти данные. Посмотрел order.Discounts там ничего. Как решить проблему? Как мне учитывать авто скидку в системе?

**Comment by vcpp** [comment]
> плагин для онлайн оплаты недавно перестал работать корректно.

Какая версия API? Если известна версия iikoFront, тоже укажите. После чего плагин перестал работать? Или как обычно, ничего не меняли, оно само? :-)
А ещё хотелось бы знать сценарий, как происходит оплата, как считается скидка, что плагин собирается делать с суммой скидки в методе `OnPaymentAdded` и т. п.

Сейчас порядок действий такой:
- добавляем тип оплаты в заказ
- вызываем обработчик `OnPaymentAdded` у плагина
- добавляем привязанную к типу оплаты скидку.

Понятно, что в обработчике `OnPaymentAdded` плагин не видит скидку, ибо она ещё не добавлена. Надо посмотреть, нельзя ли поменять местами последние два действия.

**Comment by Azamatjon** [comment]
> > плагин для онлайн оплаты недавно перестал работать корректно.
> 
> Какая версия API? Если известна версия iikoFront, тоже укажите. После чего плагин перестал работать? Или как обычно, ничего не меняли, оно само? :-)
> А ещё хотелось бы знать сценарий, как происходит оплата, как считается скидка, что плагин собирается делать с суммой скидки в методе `OnPaymentAdded` и т. п.
> 
> Сейчас порядок действий такой:
> 
> * добавляем тип оплаты в заказ
> * вызываем обработчик `OnPaymentAdded` у плагина
> * добавляем привязанную к типу оплаты скидку.
> 
> Понятно, что в обработчике `OnPaymentAdded` плагин не видит скидку, ибо она ещё не добавлена. Надо посмотреть, нельзя ли поменять местами последние два действия (RMS-50276).

1. Версия V6
2. Я написал "перестал работать корректно", а не перестал работать. Потому что раньше автоматической скидки не было установлено для типа оплаты.
3. Сценарий:
Забиваем заказ (здесь пока не установлена скидка)
Переходим на выбор оплаты выбираем внешнюю оплату -> 
collectData() -> сделает запрос на сервер для получения транзакции, получаем данные, запоминаем и сохраняем на RollBackData, переходим на onPaymentAdded() ->удаляю только что добавленный тип оплаты, потому что оно считается как непроведенный тип оплаты, 
`editSession.AddExternalPaymentItem(resultSum, false, additionalData, paymentType, order);`
сохраняю editSession.
Пробовал посмотреть установленные скидки, там нет ничего.

> Надо посмотреть, нельзя ли поменять местами последние два действия (RMS-50276).

Как поменять последние 2 действия?

**Comment by vcpp** [comment]
> Как поменять последние 2 действия?

Мы посмотрим, нельзя ли во внутренней реализации сначала добавлять связанные с типом оплаты скидки и лишь затем вызывать обработчик `OnPaymentAdded`.
Спасибо за сценарий, мы подумаем, какое решение предложить.

**Comment by Azamatjon** [comment]
> > Как поменять последние 2 действия?
> 
> Мы посмотрим, нельзя ли во внутренней реализации сначала добавлять связанные с типом оплаты скидки и лишь затем вызывать обработчик `OnPaymentAdded`.
> Спасибо за сценарий, мы подумаем, какое решение предложить.

Жду вашего ответа

**Comment by Azamatjon** [comment]
@vcpp есть у вас решение?

**Comment by vcpp** [comment]
Да, поведение изменится, начиная с iikoRms 7.4.1.
Подробнее [тут](https://iiko.github.io/front.api.doc/2019/11/12/on-payment-added.html).

**Comment by Azamatjon** [comment]
@vcpp , а до этого как то манипулировать нельзя?

**Comment by vcpp** [comment]
Увы, в ранее выпущенных версиях поведение останется прежним — сначала вызовется обработчик `OnPaymentAdded`, а потом добавится скидка.

**Comment by Azamatjon** [comment]
> Да, поведение изменится, начиная с iikoRms 7.1.4.
> Подробнее [тут](https://iiko.github.io/front.api.doc/2019/11/12/on-payment-added.html).

Здравствуйте, вышла версия 7.1.6025.0 значит уже исправили динамические скидки?

**Comment by vcpp** [comment]
Да, начиная с 7.1.4 сначала обработчик `OnPaymentAdded` вызывается после добавления связанных с типом оплаты скидок.
